# Generated by Django 5.2.16 on 2026-08-21 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispositivos", "0005_remove_dispositivo_domicilio_institucion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VersionProyeccionTerritorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=128, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProvinciaTerritorialProyectada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.PositiveIntegerField()),
                ("nombre", models.CharField(max_length=255)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="provincias",
                        to="dispositivos.versionproyeccionterritorial",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre", "source_id"],
            },
        ),
        migrations.CreateModel(
            name="MunicipioTerritorialProyectado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_id", models.PositiveIntegerField()),
                ("nombre", models.CharField(max_length=255)),
                (
                    "provincia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="municipios",
                        to="dispositivos.provinciaterritorialproyectada",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="municipios",
                        to="dispositivos.versionproyeccionterritorial",
                    ),
                ),
            ],
            options={
                "ordering": ["nombre", "source_id"],
            },
        ),
        migrations.CreateModel(
            name="EstadoProyeccionTerritorial",
            fields=[
                (
                    "singleton",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="dispositivos.versionproyeccionterritorial",
                    ),
                ),
            ],
            options={
                "verbose_name": "estado de proyección territorial",
                "verbose_name_plural": "estado de proyección territorial",
            },
        ),
        migrations.AddConstraint(
            model_name="provinciaterritorialproyectada",
            constraint=models.UniqueConstraint(
                fields=("version", "source_id"),
                name="provincia_proyectada_unica_por_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="municipioterritorialproyectado",
            constraint=models.UniqueConstraint(
                fields=("version", "source_id"),
                name="municipio_proyectado_unico_por_version",
            ),
        ),
    ]
