from pwa.models import CatalogoActividadPWA


CATALOGO_ACTIVIDADES_INICIAL = [
    ("Artes Plasticas y Manualidades", "Modelado en porcelana fria"),
    ("Cultura", "Taller de pintura"),
    ("Cultura", "Danzas y talleres de arte"),
    ("Cultura", "Taller de percusion y trompeta"),
    ("Cultura", "Taller de guitarra"),
    ("Cultura", "Ensenanza de danzas clasicas"),
    ("Cultura", "Jazz"),
    ("Cultura", "Urbano"),
    ("Cultura", "Clases de danzas"),
    ("Cultura", "Clasico"),
    ("Cultura", "Arabe"),
    ("Cultura", "Pop"),
    ("Cultura", "Danza aerea juvenil"),
    ("Cultura", "Dibujo y pintura"),
    ("Cultura", "Art toy"),
    ("Cultura", "Caricaturas"),
    ("Cultura", "Stop motions"),
    ("Cultura", "Telas"),
    ("Cultura", "Danzas brasileras"),
    ("Cultura", "Reggaeton"),
    ("Cultura", "TikTokdance"),
    ("Cultura", "Bachata"),
    ("Cultura", "Taller de costura y bordado"),
    ("Cultura", "Dibujo y artesanias manuales"),
    ("Cultura", "KPOP"),
    ("Cultura", "Zumba kids"),
    ("Cultura", "Zumba Fitness"),
    ("Cultura", "Modelaje"),
    ("Cultura", "Hip hop"),
    ("Cultura", "Clases de piano"),
    ("Cultura", "Clases de guitarra"),
    ("Cultura", "Clases de trompeta"),
    ("Cultura", "Clases de bateria"),
    ("Cultura", "Clases de canto"),
    ("Cultura", "Clases de bajo"),
    ("Cultura", "Taller de Carnaval"),
    ("Deporte", "Futbol infantil"),
    ("Deporte", "Futbol masculino y femenino"),
    ("Deporte", "Basquet"),
    ("Deporte", "Taekwondo"),
    ("Deporte", "Karate"),
    ("Deporte", "Handball"),
    ("Deporte", "Boxeo"),
    ("Deporte", "Newcon"),
    ("Deporte", "Futsal"),
    ("Deporte", "Futbol masculino"),
    ("Deporte", "Futbol masculino y femenino y hockey"),
    ("Deporte", "Voley"),
    ("Deporte", "Artes marciales mixtas y deportes de combate"),
    ("Deporte", "Rugby y hockey masculino y femenino"),
    ("Deporte", "Gimnasia artistica"),
    ("Deporte", "Artes marciales"),
    ("Deporte", "Patin"),
    ("Deporte", "Boxeo recreativo"),
    ("Deporte", "Deportes y recreacion"),
    ("Deporte", "Defensa Personal"),
    ("Educacion", "Apoyo escolar primario"),
    ("Educacion", "Apoyo escolar"),
    ("Educacion", "Talleres de apoyo escolar y alfabetizacion"),
    ("Educacion", "Talleres de alfabetizacion"),
    ("Educacion", "Lectoescritura"),
    ("Educacion", "Matematicas"),
    ("Educacion", "Acompanamiento pedagogico y emocional"),
    ("Educacion", "Talleres educativos y de crecimiento personal"),
    ("Educacion", "Clases de apoyo escolar"),
    ("Educacion", "Ingles"),
    ("Salud", "Charla sobre nutricion"),
    ("Salud", "Gimnasio"),
    ("Salud", "Musculacion"),
    ("Salud", "Ritmos latinos y pilates"),
    ("Salud", "Zumba"),
    ("Salud", "Strong nation"),
    ("Salud", "strong Nation"),
    ("Salud", "Yoga kids"),
    ("Salud", "Hatha yoga"),
    ("Salud", "Aeroyoga"),
]


def bootstrap_catalogo_actividades(*, using: str = "default") -> None:
    """Garantiza el catálogo inicial de actividades PWA de forma idempotente."""
    for categoria, actividad in CATALOGO_ACTIVIDADES_INICIAL:
        CatalogoActividadPWA.objects.using(using).update_or_create(
            categoria=categoria,
            actividad=actividad,
            defaults={"activo": True},
        )
