# Generated by Django 4.2.20 on 2025-11-05 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0005_profile_fecha_creacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="coordinador",
            field=models.ForeignKey(
                blank=True,
                help_text="Coordinador asignado a este técnico",
                limit_choices_to={"groups__name": "Coordinador Gestion"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tecnicos_coordinados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Coordinador de Gestión",
            ),
        ),
    ]
