# Generated by Django 4.2.20 on 2025-11-05 14:21

import logging

from django.db import migrations
from django.contrib.auth.models import Group

logger = logging.getLogger("django")


def create_coordinador_gestion_group(apps, schema_editor):
    """
    Crear el grupo 'Coordinador Gestion' para coordinadores de área operativa.

    Este grupo permite visualizar:
    - Comedores de sus técnicos asociados
    - Admisiones de esos comedores
    - Acompañamiento de esos comedores
    - Rendiciones de esos comedores
    """
    try:
        _, created = Group.objects.get_or_create(name="Coordinador Gestion")

        if created:
            logger.info("✅ Grupo 'Coordinador Gestion' creado exitosamente")
        else:
            logger.info("ℹ️  Grupo 'Coordinador Gestion' ya existía")

    except Exception as e:
        logger.exception("❌ Error al crear grupo 'Coordinador Gestion': %s", e)
        raise


def remove_coordinador_gestion_group(apps, schema_editor):
    """
    Eliminar el grupo 'Coordinador Gestion'.
    """
    try:
        Group.objects.filter(name="Coordinador Gestion").delete()
        logger.info("✅ Grupo 'Coordinador Gestion' eliminado")

    except Exception as e:
        logger.warning("⚠️  Error al eliminar grupo 'Coordinador Gestion': %s", e)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_add_coordinador_to_profile"),
    ]

    operations = [
        migrations.RunPython(
            create_coordinador_gestion_group,
            remove_coordinador_gestion_group,
        ),
    ]
