# Generated by Django 4.2.27 on 2026-02-20

from django.db import migrations


UNUSED_GROUPS = [
    "Usuario Listar",
    "Admin Ver Expedientes",
    "Técnico Ver Tareas Asignadas",
    "Provincia Ver Estado Pago",
    "Provincia Crear Expediente",
    "Provincia Ver Lista Aprobados",
    "Provincia Cargar Formulario",
    "Provincia Finalizar Expediente",
    "Admin Asignar Técnico",
    "Técnico Subir Cruces",
    "Técnico Validar Resultado Cruce",
    "Técnico Registrar Informe Pago",
    "ApiCentroFamilia",
]


def remove_unused_groups(apps, schema_editor):
    """Elimina grupos huérfanos que ya no se usan en el sistema."""
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=UNUSED_GROUPS).delete()


def restore_unused_groups(apps, schema_editor):
    """Recrea los grupos eliminados en caso de rollback."""
    Group = apps.get_model("auth", "Group")
    for group_name in UNUSED_GROUPS:
        Group.objects.get_or_create(name=group_name)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_accesocomedorpwa_and_more"),
    ]

    operations = [
        migrations.RunPython(remove_unused_groups, restore_unused_groups),
    ]
