# Generated by Django 4.2 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_cleanup_unused_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="initial_password_expires_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Expira contraseña inicial en",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="Obliga al usuario a actualizar la contraseña en su próximo login web.",
                verbose_name="Debe cambiar contraseña",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="password_changed_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Contraseña actualizada en",
            ),
        ),
    ]
