# Generated by Django 4.2 on 2026-03-05

from django.db import migrations
from django.utils.text import slugify


def bootstrap_group_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")

    content_type = ContentType.objects.get(app_label="auth", model="group")

    for group in Group.objects.all():
        base_codename = f"role_{slugify(group.name).replace('-', '_')}"[:100]
        if not base_codename or base_codename == "role_":
            base_codename = f"role_group_{group.id}"

        codename = base_codename
        suffix = 1
        while (
            Permission.objects.filter(content_type=content_type, codename=codename)
            .exclude(name=group.name)
            .exists()
        ):
            suffix += 1
            codename = f"{base_codename[:95]}_{suffix}"[:100]

        permission, _ = Permission.objects.get_or_create(
            content_type=content_type,
            codename=codename,
            defaults={"name": group.name},
        )
        if permission.name != group.name:
            permission.name = group.name
            permission.save(update_fields=["name"])

        group.permissions.add(permission)


def noop_reverse(apps, schema_editor):
    """No-op: preserva permisos creados."""


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_profile_password_security_fields"),
    ]

    operations = [
        migrations.RunPython(bootstrap_group_permissions, noop_reverse),
    ]

