# Generated by Django 4.2 on 2026-03-06

from django.db import migrations
from django.utils.text import slugify


LEGACY_ALIAS_TO_PERMISSION_CODES = {
    "Usuario Ver": ("auth.view_user",),
    "Usuario Crear": ("auth.add_user",),
    "Usuario Editar": ("auth.change_user",),
    "Usuario Eliminar": ("auth.delete_user",),
    "Grupos Ver": ("auth.view_group",),
    "Comedor Ver": ("comedores.view_comedor",),
    "Comedores": ("comedores.view_comedor",),
    "Comedores Listar": ("comedores.view_comedor",),
    "Comedores Ver": ("comedores.view_comedor",),
    "Comedores Crear": ("comedores.add_comedor",),
    "Comedores Editar": ("comedores.change_comedor",),
    "Comedores Eliminar": ("comedores.delete_comedor",),
    "Comedores Observaciones Crear": ("comedores.add_observacion",),
    "Comedores Observaciones Detalle": ("comedores.view_observacion",),
    "Comedores Observaciones Editar": ("comedores.change_observacion",),
    "Comedores Observaciones Eliminar": ("comedores.delete_observacion",),
    "Comedores Intervencion Ver": ("intervenciones.view_intervencion",),
    "Comedores Intervencion Crear": ("intervenciones.add_intervencion",),
    "Comedores Intervencion Editar": ("intervenciones.change_intervencion",),
    "Comedores Intervenciones Detalle": ("intervenciones.view_intervencion",),
    "Comedores Nomina Ver": ("comedores.view_nomina",),
    "Comedores Nomina Crear": ("comedores.add_nomina",),
    "Comedores Nomina Editar": ("comedores.change_nomina",),
    "Comedores Nomina Borrar": ("comedores.delete_nomina",),
    "Comedores Dupla Asignar": ("duplas.change_dupla",),
    "Comedores Relevamiento Ver": ("relevamientos.view_relevamiento",),
    "Comedores Relevamiento Crear": ("relevamientos.add_relevamiento",),
    "Comedores Relevamiento Detalle": ("relevamientos.view_relevamiento",),
    "Comedores Relevamiento Editar": ("relevamientos.change_relevamiento",),
    "Tecnico Comedor": (
        "comedores.view_comedor",
        "admisiones.view_admision",
        "acompanamientos.view_informacionrelevante",
    ),
    "Abogado Dupla": (
        "comedores.view_comedor",
        "admisiones.view_admision",
        "acompanamientos.view_informacionrelevante",
    ),
    "Area Legales": (
        "comedores.view_comedor",
        "admisiones.view_admision",
        "acompanamientos.view_informacionrelevante",
        "expedientespagos.view_expedientepago",
    ),
    "Area Contable": ("comedores.view_comedor", "expedientespagos.view_expedientepago"),
    "Coordinador Equipo Tecnico": (
        "comedores.view_comedor",
        "admisiones.view_admision",
        "acompanamientos.view_informacionrelevante",
    ),
    "Coordinador general": ("comedores.view_comedor",),
    "Coordinador Gestion": ("comedores.view_comedor",),
    "Acompanamiento Listar": ("acompanamientos.view_informacionrelevante",),
    "Acompanamiento Detalle": ("acompanamientos.view_informacionrelevante",),
    "Organizaciones": ("organizaciones.view_organizacion",),
    "Ciudadanos": ("ciudadanos.view_ciudadano",),
    "ReferenteCentro": ("centrodefamilia.view_centro",),
    "CDF SSE": ("centrodefamilia.view_centro",),
    "Dashboard Centrodefamilia": ("dashboard.view_dashboard",),
    "Dashboard Comedor": ("dashboard.view_dashboard",),
    "Centro de Infancia Listar": ("centrodeinfancia.view_centrodeinfancia",),
    "Centro de Infancia Ver": ("centrodeinfancia.view_centrodeinfancia",),
    "Centro de Infancia Crear": ("centrodeinfancia.add_centrodeinfancia",),
    "Centro de Infancia Editar": ("centrodeinfancia.change_centrodeinfancia",),
    "Centro de Infancia Eliminar": ("centrodeinfancia.delete_centrodeinfancia",),
    "Centro de Infancia Nomina Ver": ("centrodeinfancia.view_nominacentroinfancia",),
    "Centro de Infancia Nomina Crear": ("centrodeinfancia.add_nominacentroinfancia",),
    "Centro de Infancia Nomina Editar": (
        "centrodeinfancia.change_nominacentroinfancia",
    ),
    "Centro de Infancia Nomina Borrar": (
        "centrodeinfancia.delete_nominacentroinfancia",
    ),
    "Centro de Infancia Intervencion Crear": (
        "centrodeinfancia.add_intervencioncentroinfancia",
    ),
    "Centro de Infancia Intervencion Editar": (
        "centrodeinfancia.change_intervencioncentroinfancia",
    ),
    "Centro de Infancia Intervencion Borrar": (
        "centrodeinfancia.delete_intervencioncentroinfancia",
    ),
    "Importar Expediente": ("importarexpediente.view_archivosimportados",),
    "Comunicado Crear": ("comunicados.add_comunicado",),
    "Comunicado Editar": ("comunicados.change_comunicado",),
    "Comunicado Publicar": ("comunicados.change_comunicado",),
    "Comunicado Archivar": ("comunicados.change_comunicado",),
    "Comunicado Interno Crear": ("comunicados.add_comunicado",),
    "Comunicado Interno Editar": ("comunicados.change_comunicado",),
    "Comunicado Interno Publicar": ("comunicados.change_comunicado",),
    "Comunicado Interno Archivar": ("comunicados.change_comunicado",),
    "Comunicado Comedores Crear": ("comunicados.add_comunicado",),
    "Comunicado Comedores Editar": ("comunicados.change_comunicado",),
    "Comunicado Comedores Publicar": ("comunicados.change_comunicado",),
    "Comunicado Comedores Archivar": ("comunicados.change_comunicado",),
    "TecnicoCeliaquia": ("celiaquia.view_expediente",),
    "CoordinadorCeliaquia": ("celiaquia.view_expediente",),
    "ProvinciaCeliaquia": ("celiaquia.view_expediente",),
    "Gestor prestaciones": ("core.view_montoprestacionprograma",),
    "Exportar a csv": ("auth.role_exportar_a_csv",),
    "Administrador": ("auth.role_administrador",),
    "Admin": ("auth.role_admin",),
    "superadmin": ("auth.role_superadmin",),
}


GROUP_BOOTSTRAP_ALIASES = {
    "Admin": (
        "Admin",
        "Usuario Ver",
        "Usuario Crear",
        "Usuario Editar",
        "Usuario Eliminar",
        "Grupos Ver",
        "auth.add_group",
        "auth.change_group",
        "Exportar a csv",
    ),
    "Administrador": (
        "Administrador",
        "Usuario Ver",
        "Usuario Crear",
        "Usuario Editar",
        "Usuario Eliminar",
        "Grupos Ver",
        "auth.add_group",
        "auth.change_group",
        "Exportar a csv",
    ),
    "superadmin": (
        "superadmin",
        "Usuario Ver",
        "Usuario Crear",
        "Usuario Editar",
        "Usuario Eliminar",
        "Grupos Ver",
        "auth.add_group",
        "auth.change_group",
        "Exportar a csv",
    ),
    "Comedores": ("Comedores Ver",),
    "Comedores Listar": ("Comedores Ver",),
    "Tecnico Comedor": (
        "Tecnico Comedor",
        "Comedores Ver",
        "Comedores Relevamiento Ver",
        "Comedores Intervencion Ver",
        "Comedores Nomina Ver",
        "Acompanamiento Listar",
    ),
    "Abogado Dupla": ("Abogado Dupla", "Comedores Ver", "Acompanamiento Listar"),
    "Area Legales": ("Area Legales", "Comedores Ver", "Acompanamiento Listar"),
    "Area Contable": ("Area Contable", "Comedores Ver"),
    "Coordinador Equipo Tecnico": (
        "Coordinador Equipo Tecnico",
        "Comedores Ver",
        "Acompanamiento Listar",
        "Comedores Relevamiento Ver",
    ),
    "Coordinador general": ("Coordinador general", "Comedores Ver"),
    "ReferenteCentro": ("ReferenteCentro", "CDF SSE"),
    "Dashboard Centrodefamilia": ("Dashboard Centrodefamilia", "CDF SSE"),
}


def _legacy_permission_code(alias):
    base = f"role_{slugify(alias).replace('-', '_')}"[:100]
    if not base or base == "role_":
        base = "role_group"
    return f"auth.{base}"


def _permission_codes_for_alias(alias):
    if not alias:
        return tuple()
    if "." in alias:
        return (alias,)
    mapped = LEGACY_ALIAS_TO_PERMISSION_CODES.get(alias)
    if mapped:
        return mapped
    return (_legacy_permission_code(alias),)


def _permission_codes_for_group(group_name):
    aliases = GROUP_BOOTSTRAP_ALIASES.get(group_name, (group_name,))
    result = []
    seen = set()
    for alias in aliases:
        for code in _permission_codes_for_alias(alias):
            if code not in seen:
                seen.add(code)
                result.append(code)
    return result


def assign_bootstrap_group_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    for group in Group.objects.all():
        permission_codes = _permission_codes_for_group(group.name)
        permissions = []
        for code in permission_codes:
            try:
                app_label, codename = code.split(".", 1)
            except ValueError:
                continue
            permission = Permission.objects.filter(
                content_type__app_label=app_label,
                codename=codename,
            ).first()
            if permission:
                permissions.append(permission)
        if permissions:
            group.permissions.add(*permissions)


def noop_reverse(apps, schema_editor):
    """No-op reversible."""


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_bootstrap_group_permissions"),
    ]

    operations = [
        migrations.RunPython(assign_bootstrap_group_permissions, noop_reverse),
    ]
