# Generated by Django 4.2.27 on 2026-03-27 16:46
# Generated by Django 4.2.27 on 2026-03-29 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_accesocomedorpwa_fecha_baja_and_audit"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditaccesocomedorpwa",
            new_name="users_audit_user_id_0e2825_idx",
            old_name="users_audit_user_74b57d_idx",
        ),
        migrations.RenameIndex(
            model_name="auditaccesocomedorpwa",
            new_name="users_audit_comedor_fa16b0_idx",
            old_name="users_audit_comedor_4b01f7_idx",
        ),
        migrations.RenameIndex(
            model_name="auditaccesocomedorpwa",
            new_name="users_audit_accion_71bafe_idx",
            old_name="users_audit_accion_9d4c59_idx",
        ),
    ]
