# Generated by Django 4.2.27 on 2026-03-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_profile_delegation_scope_fields"),
        (
            "users",
            "0020_rename_users_audit_user_74b57d_idx_users_audit_user_id_0e2825_idx_and_more",
        ),
    ]

    operations = []
