# Generated by Codex on 2026-03-31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_profile_password_reset_requested_at"),
        ("users", "0022_profile_temporary_password_plaintext"),
    ]

    operations = []
