# Generated by Django 4.2 on 2026-04-08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0026_admin_bulk_credentials_permission"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkCredentialsJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to=users.models.bulk_credentials_job_upload_to
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("send_type", models.CharField(db_index=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("processed_rows", models.PositiveIntegerField(default=0)),
                ("sent_rows", models.PositiveIntegerField(default=0)),
                ("updated_password_rows", models.PositiveIntegerField(default=0)),
                ("unchanged_password_rows", models.PositiveIntegerField(default=0)),
                ("rejected_rows", models.PositiveIntegerField(default=0)),
                ("next_row_index", models.PositiveIntegerField(default=0)),
                (
                    "last_successful_row",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "last_successful_username",
                    models.CharField(blank=True, max_length=150),
                ),
                (
                    "last_attempted_row",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "last_attempted_username",
                    models.CharField(blank=True, max_length=150),
                ),
                ("last_error_message", models.TextField(blank=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("resume_count", models.PositiveIntegerField(default=0)),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_activity_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="bulk_credentials_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote de credenciales masivas",
                "verbose_name_plural": "Lotes de credenciales masivas",
                "ordering": ["-requested_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "requested_at"],
                        name="users_bulk_status_dfc1d3_idx",
                    ),
                    models.Index(
                        fields=["requested_by", "requested_at"],
                        name="users_bulk_request_f960fc_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BulkCredentialsJobRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fila", models.PositiveIntegerField()),
                ("usuario", models.CharField(blank=True, max_length=150)),
                ("mail_destino", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Enviada"), ("failed", "Fallida")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("mensaje", models.TextField(blank=True)),
                ("password_actualizada", models.BooleanField(default=False)),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="users.bulkcredentialsjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado de fila de credenciales masivas",
                "verbose_name_plural": "Resultados de filas de credenciales masivas",
                "ordering": ["fila", "id"],
                "indexes": [
                    models.Index(
                        fields=["job", "status"],
                        name="users_bulk_job_id_a52ddf_idx",
                    ),
                    models.Index(
                        fields=["job", "processed_at"],
                        name="users_bulk_job_id_1361d3_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("job", "fila"),
                        name="users_bulk_credentials_job_row_unique",
                    )
                ],
            },
        ),
    ]
