# Generated by Django 4.2.27 on 2026-04-09 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_bulk_credentials_jobs"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="bulkcredentialsjob",
            new_name="users_bulkc_status_7d2f67_idx",
            old_name="users_bulk_status_dfc1d3_idx",
        ),
        migrations.RenameIndex(
            model_name="bulkcredentialsjob",
            new_name="users_bulkc_request_2f0831_idx",
            old_name="users_bulk_request_f960fc_idx",
        ),
        migrations.RenameIndex(
            model_name="bulkcredentialsjobrow",
            new_name="users_bulkc_job_id_af9261_idx",
            old_name="users_bulk_job_id_a52ddf_idx",
        ),
        migrations.RenameIndex(
            model_name="bulkcredentialsjobrow",
            new_name="users_bulkc_job_id_3d3e77_idx",
            old_name="users_bulk_job_id_1361d3_idx",
        ),
    ]
