# Generated by Django 4.2.27 on 2026-05-22 13:43

import django.db.models.deletion
from django.db import migrations, models

GROUP_NAME = "CDI - Referente centro"

PERMISSION_CODES = (
    "auth.role_centro_de_infancia_editar",
    "centrodeinfancia.change_centrodeinfancia",
    "auth.role_centro_de_infancia_formulario_borrar",
    "centrodeinfancia.delete_formulariocdi",
    "auth.role_centro_de_infancia_formulario_crear",
    "centrodeinfancia.add_formulariocdi",
    "auth.role_centro_de_infancia_formulario_editar",
    "centrodeinfancia.change_formulariocdi",
    "auth.role_centro_de_infancia_formulario_ver",
    "centrodeinfancia.view_formulariocdi",
    "auth.role_centro_de_infancia_intervencion_borrar",
    "centrodeinfancia.delete_intervencioncentroinfancia",
    "auth.role_centro_de_infancia_intervencion_crear",
    "centrodeinfancia.add_intervencioncentroinfancia",
    "auth.role_centro_de_infancia_intervencion_editar",
    "centrodeinfancia.change_intervencioncentroinfancia",
    "auth.role_centro_de_infancia_listar",
    "centrodeinfancia.view_centrodeinfancia",
    "auth.role_centro_de_infancia_nomina_borrar",
    "centrodeinfancia.delete_nominacentroinfancia",
    "auth.role_centro_de_infancia_nomina_crear",
    "centrodeinfancia.add_nominacentroinfancia",
    "auth.role_centro_de_infancia_nomina_editar",
    "centrodeinfancia.change_nominacentroinfancia",
    "auth.role_centro_de_infancia_nomina_ver",
    "centrodeinfancia.view_nominacentroinfancia",
    "auth.role_centro_de_infancia_ver",
)


def _resolve_permission(apps, code):
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    try:
        app_label, codename = code.split(".", 1)
    except ValueError:
        return None

    permission = Permission.objects.filter(
        content_type__app_label=app_label,
        codename=codename,
    ).first()
    if permission:
        return permission

    if app_label == "auth" and codename.startswith("role_"):
        group_ct, _ = ContentType.objects.get_or_create(app_label="auth", model="group")
        name = codename[len("role_") :].replace("_", " ").strip().title()
        permission, _ = Permission.objects.get_or_create(
            content_type=group_ct,
            codename=codename,
            defaults={"name": name or codename},
        )
        return permission

    return None


def bootstrap_cdi_referente_centro_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    group, _ = Group.objects.get_or_create(name=GROUP_NAME)

    permissions = []
    for code in PERMISSION_CODES:
        permission = _resolve_permission(apps, code)
        if permission:
            permissions.append(permission)
    if permissions:
        group.permissions.add(*permissions)


def migrate_legacy_profile_provincias(apps, schema_editor):
    Profile = apps.get_model("users", "Profile")
    ProfileTerritorialScope = apps.get_model("users", "ProfileTerritorialScope")

    profiles = Profile.objects.filter(
        es_usuario_provincial=True,
        provincia_id__isnull=False,
    ).only("id", "provincia_id")
    for profile in profiles.iterator():
        scope_key = f"p{profile.provincia_id}:m0:l0"
        ProfileTerritorialScope.objects.get_or_create(
            profile_id=profile.id,
            scope_key=scope_key,
            defaults={"provincia_id": profile.provincia_id},
        )


class Migration(migrations.Migration):

    replaces = [
        ("users", "0029_bootstrap_cdi_referente_centro_group"),
        ("users", "0030_profile_territorial_scope"),
    ]

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0001_squashed_0028"),
        ("core", "0008_programa_organismo_programa_descripcion"),
        ("centrodeinfancia", "0029_accesocdi_accesocdi_uniq_acceso_cdi_user_centro"),
    ]

    operations = [
        migrations.RunPython(
            code=bootstrap_cdi_referente_centro_group,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="ProfileTerritorialScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope_key",
                    models.CharField(db_index=True, editable=False, max_length=64),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.localidad",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.municipio",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="territorial_scopes",
                        to="users.profile",
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.provincia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alcance territorial de perfil",
                "verbose_name_plural": "Alcances territoriales de perfil",
            },
        ),
        migrations.AddConstraint(
            model_name="profileterritorialscope",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("localidad__isnull", True),
                    ("municipio__isnull", False),
                    _connector="OR",
                ),
                name="profile_scope_localidad_requires_municipio",
            ),
        ),
        migrations.AddConstraint(
            model_name="profileterritorialscope",
            constraint=models.UniqueConstraint(
                fields=("profile", "scope_key"),
                name="uniq_profile_scope_key",
            ),
        ),
        migrations.AddIndex(
            model_name="profileterritorialscope",
            index=models.Index(
                fields=["profile", "provincia"],
                name="users_profi_profile_4be6f7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="profileterritorialscope",
            index=models.Index(
                fields=["profile", "provincia", "municipio"],
                name="users_profi_profile_26d7f4_idx",
            ),
        ),
        migrations.RunPython(
            code=migrate_legacy_profile_provincias,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
