# Generated by Django 5.2.16 on 2026-08-24 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_programa_organismo_programa_descripcion"),
        ("users", "0045_profile_correo_institucional_declaracion"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="es_territorial_comedor",
            field=models.BooleanField(
                default=False,
                help_text="Marca al usuario como territorial (relevador) de comedores en SISOC - Mobile. El alcance se define por provincia en TerritorialComedorProvincia.",
                verbose_name="Acceso SISOC - Mobile Territorial comedor",
            ),
        ),
        migrations.CreateModel(
            name="TerritorialComedorProvincia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="territorial_comedor_provincias",
                        to="users.profile",
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.provincia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Provincia de territorial de comedor",
                "verbose_name_plural": "Provincias de territorial de comedor",
                "indexes": [
                    models.Index(
                        fields=["provincia"], name="users_terri_provinc_4ebe83_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "provincia"),
                        name="uniq_territorial_comedor_provincia",
                    )
                ],
            },
        ),
    ]
