# Generated by Django 5.2.16 on 2026-09-18 17:40

from django.db import migrations, models


def _tiene_restriccion_territorial(perfil):
    """True si el backoffice ya le limita el alcance a este perfil.

    Antes se preguntaba por "provincia completa" replicando
    ``get_full_province_scope_ids``, y ese predicado mete en la misma bolsa dos
    situaciones que no son equivalentes:

    - el perfil **no** tiene ``es_usuario_provincial``: hoy es irrestricto en el
      backoffice, asi que ascenderlo a Administrador Nacional no le agrega nada
      que no tuviera;
    - el perfil **si** lo tiene pero su alcance es solo municipal: hoy
      ``apply_relevamientos_scope`` le devuelve ``.none()``, o sea no ve nada.
      Clasificarlo ``administrador`` le regalaba el pais entero en la app y el
      cierre de cualquier operativo.

    Para decidir un rol la diferencia es todo, asi que la pregunta correcta es
    la restriccion, no la forma del alcance: cualquier perfil con la restriccion
    territorial activa queda ``coordinador``, tenga provincia completa o solo un
    municipio.
    """
    return bool(perfil.es_usuario_provincial)


def asignar_rol_a_coordinadores_existentes(apps, schema_editor):
    """Los coordinadores que ya existen tienen el grupo pero no el rol.

    Sin esto, el dia del despliegue quedan fuera de la app y del gate nuevo.
    Minimo privilegio: solo quien hoy es irrestricto en el backoffice -o sea,
    quien no tiene ``es_usuario_provincial``- queda ``administrador``. Cualquier
    perfil con la restriccion territorial activa queda ``coordinador``, aunque su
    alcance sea solo municipal: equivocarse para este lado cuesta un coordinador
    de mas, y para el otro, un administrador nacional que nadie decidio crear.
    """
    Group = apps.get_model("auth", "Group")
    Profile = apps.get_model("users", "Profile")

    grupo = Group.objects.filter(name="Coordinador DataCalle").first()
    if grupo is None:
        return

    perfiles = Profile.objects.filter(user__groups=grupo).distinct()
    for perfil in perfiles:
        if perfil.datacalle_rol:
            continue
        rol = (
            "coordinador" if _tiene_restriccion_territorial(perfil) else "administrador"
        )
        perfil.datacalle_rol = rol
        perfil.es_relevador_calle = True
        perfil.save(update_fields=["datacalle_rol", "es_relevador_calle"])


def asignar_rol_a_relevadores_existentes(apps, schema_editor):
    """Los relevadores que ya existen tienen el flag pero todavia no el rol.

    Sin esto quedan con ``es_relevador_calle=True`` y ``datacalle_rol=""``, que
    con la semantica nueva no es "relevador" sino "nadie": pierden el acceso a
    la app, dejan de ser ``es_solo_app`` (o sea que ganan el backoffice),
    desaparecen del selector de equipo -que filtra por
    ``datacalle_rol="entrevistador"``- y bloquean la edicion de cualquier
    operativo que los tenga en el equipo.

    Se excluye a los del grupo ``Coordinador DataCalle``: esos ya los clasifico
    la funcion de arriba. Idempotente: solo toca los que tienen el rol vacio.
    """
    Group = apps.get_model("auth", "Group")
    Profile = apps.get_model("users", "Profile")

    perfiles = Profile.objects.filter(es_relevador_calle=True, datacalle_rol="")
    grupo = Group.objects.filter(name="Coordinador DataCalle").first()
    if grupo is not None:
        perfiles = perfiles.exclude(user__groups=grupo)
    perfiles.update(datacalle_rol="entrevistador")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0052_bootstrap_reportes_cdi_permission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="datacalle_rol",
            field=models.CharField(
                blank=True,
                choices=[
                    ("administrador", "Administrador Nacional"),
                    ("coordinador", "Coordinador Provincial"),
                    ("entrevistador", "Relevador"),
                ],
                default="",
                help_text="Rol con el que el usuario opera en SISOC - Mobile DataCalle. Obligatorio cuando es_relevador_calle esta activo.",
                max_length=20,
                verbose_name="Rol en DataCalle",
            ),
        ),
        migrations.RunPython(
            asignar_rol_a_coordinadores_existentes,
            # Sin reversa de datos a proposito: no hay forma de distinguir un rol
            # que escribio esta migracion de uno que escribio un alta legitima
            # posterior, asi que revertir borraria roles que nadie pidio borrar.
            # El forward es idempotente (saltea los perfiles que ya tienen rol),
            # asi que volver a aplicar despues de un rollback sigue andando.
            migrations.RunPython.noop,
        ),
        migrations.RunPython(
            asignar_rol_a_relevadores_existentes,
            # Misma razon que arriba para no revertir datos.
            migrations.RunPython.noop,
        ),
    ]
