# Generated by Django 4.2.14 on 2024-07-31 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Legajos_Provincias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincias_Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poblacion', models.IntegerField(blank=True, null=True)),
                ('pobreza', models.IntegerField(blank=True, null=True)),
                ('PEA', models.IntegerField(blank=True, null=True)),
                ('ocupada', models.IntegerField(blank=True, null=True)),
                ('subocupada', models.IntegerField(blank=True, null=True)),
                ('desocupada', models.IntegerField(blank=True, null=True)),
                ('educ_incompleta_obligatoria', models.IntegerField(blank=True, null=True)),
                ('primara_incompleta_PAS', models.IntegerField(blank=True, null=True)),
                ('secundaria_incompleta_PAS', models.IntegerField(blank=True, null=True)),
                ('beneficiarios_PAS', models.IntegerField(blank=True, null=True)),
                ('porcentaje_PAS', models.IntegerField(blank=True, null=True)),
                ('q_expedientes', models.IntegerField(blank=True, null=True)),
                ('alimentos', models.IntegerField(blank=True, null=True)),
                ('ganaderia', models.IntegerField(blank=True, null=True)),
                ('agricultura_familiar', models.IntegerField(blank=True, null=True)),
                ('pesca', models.IntegerField(blank=True, null=True)),
                ('forestal', models.IntegerField(blank=True, null=True)),
                ('manufacturera', models.IntegerField(blank=True, null=True)),
                ('textil', models.IntegerField(blank=True, null=True)),
                ('carpinteria', models.BooleanField(default=False)),
                ('herreria', models.BooleanField(default=False)),
                ('mecanica', models.BooleanField(default=False)),
                ('matriceria', models.BooleanField(default=False)),
                ('otras_matriceria', models.BooleanField(default=False)),
                ('artesania_manufactureria', models.BooleanField(default=False)),
                ('albanileria', models.BooleanField(default=False)),
                ('otras_actividades_construccion', models.BooleanField(default=False)),
                ('reciclaje', models.BooleanField(default=False)),
                ('energia_renovable', models.BooleanField(default=False)),
                ('soporte_tecnico', models.BooleanField(default=False)),
                ('infraestructura_tecnologica', models.BooleanField(default=False)),
                ('desarrollo_software', models.BooleanField(default=False)),
                ('estetica_pedicuria_etc', models.BooleanField(default=False)),
                ('limpieza', models.BooleanField(default=False)),
                ('jardineria', models.BooleanField(default=False)),
                ('gastronomico', models.BooleanField(default=False)),
                ('logistica', models.BooleanField(default=False)),
                ('turismo', models.BooleanField(default=False)),
                ('comercializacion', models.BooleanField(default=False)),
                ('cuidados', models.BooleanField(default=False)),
                ('salud', models.BooleanField(default=False)),
                ('energia', models.BooleanField(default=False)),
                ('mineria', models.BooleanField(default=False)),
                ('petroquimica', models.BooleanField(default=False)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Legajos_Provincias.provincias')),
            ],
        ),
    ]
