# Generated by Django 4.2.14 on 2024-08-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Legajos_Provincias', '0005_alter_provincias_datos_poblacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincias_datos',
            name='beneficiarios_PAS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='provincias_datos',
            name='q_expedientes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
