# Generated by Django 4.2.20 on 2025-06-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admisiones",
            "0002_anexo_campoasubsanar_formularioproyectodisposicion_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="admision",
            name="enviado_acompaniamiento",
            field=models.BooleanField(
                default=False, verbose_name="¿Enviado a Acompañamiento?"
            ),
        ),
    ]
