# Generated by Django 4.2.20 on 2025-07-07 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admisiones", "0003_admision_enviado_acompaniamiento"),
    ]

    operations = [
        migrations.CreateModel(
            name="InformeComplementario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        null=True, upload_to="admisiones/informes_complementarios/"
                    ),
                ),
                ("creado", models.DateField(auto_now_add=True, null=True)),
                (
                    "admision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admisiones.admision",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "informe_tecnico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admisiones.informetecnico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InformeComplementarioCampos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campo", models.CharField(max_length=255)),
                ("value", models.CharField(max_length=255)),
                (
                    "informe_complementario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admisiones.informecomplementario",
                    ),
                ),
            ],
        ),
    ]
