# Generated by Django 4.2.20 on 2025-07-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0004_informecomplementario_informecomplementariocampos"),
    ]

    operations = [
        migrations.AddField(
            model_name="informetecnico",
            name="fecha_vencimiento_mandatos",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de vencimiento de mandatos"
            ),
        ),
    ]
