# Generated by Django 4.2.20 on 2025-09-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("admisiones", "0007_anexo_barrio"),
        ("admisiones", "0008_alter_anexo_barrio"),
    ]

    dependencies = [
        ("admisiones", "0006_informetecnico_conclusiones"),
    ]

    operations = [
        migrations.AddField(
            model_name="anexo",
            name="barrio",
            field=models.CharField(default="", max_length=50, verbose_name="Barrio"),
        ),
    ]
