# Generated by Django 4.2.20 on 2025-09-12 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0008_merge_20250911_1251"),
        ("admisiones", "0009_merge_20250911_1218"),
    ]

    operations = []
