# Generated by Django 4.2.20 on 2025-09-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0010_merge_20250912_1246"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anexo",
            name="barrio",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Barrio"
            ),
        ),
        migrations.AlterField(
            model_name="archivoadmision",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("validar", "A Validar"),
                    ("A Validar Abogado", "A Validar Abogado"),
                    ("Rectificar", "Rectificar"),
                    ("Aceptado", "Aceptado"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
