# Generated by Django 4.2.20 on 2025-09-01 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        (
            "organizaciones",
            "0002_organizacion_domicilio_organizacion_localidad_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizacion",
            name="localidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.localidad",
            ),
        ),
        migrations.AlterField(
            model_name="organizacion",
            name="provincia",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.provincia",
            ),
        ),
    ]
