# Generated by Django 4.2.20 on 2025-06-10 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizaciones",
            "0002_alter_organizacion_options_alter_organizacion_cuit_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RolFirmante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Rol de Firmante",
                "verbose_name_plural": "Roles de Firmante",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TipoEntidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Tipo de Entidad",
                "verbose_name_plural": "Tipos de Entidad",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoOrganizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Tipo de Organización",
                "verbose_name_plural": "Tipos de Organización",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SubtipoEntidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                (
                    "tipo_entidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtipos",
                        to="organizaciones.tipoentidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subtipo de Entidad",
                "verbose_name_plural": "Subtipos de Entidad",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Firmante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("cuit", models.BigIntegerField(blank=True, null=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firmantes",
                        to="organizaciones.organizacion",
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="firmantes",
                        to="organizaciones.rolfirmante",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aval2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                ("cuit", models.BigIntegerField(blank=True, null=True, unique=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avales2",
                        to="organizaciones.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aval 2",
                "verbose_name_plural": "Avales 2",
            },
        ),
        migrations.CreateModel(
            name="Aval1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                ("cuit", models.BigIntegerField(blank=True, null=True, unique=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avales1",
                        to="organizaciones.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aval 1",
                "verbose_name_plural": "Avales 1",
            },
        ),
        migrations.AddField(
            model_name="organizacion",
            name="subtipo_entidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizaciones",
                to="organizaciones.subtipoentidad",
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="tipo_entidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizaciones",
                to="organizaciones.tipoentidad",
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="tipo_organizacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizaciones",
                to="organizaciones.tipoorganizacion",
            ),
        ),
    ]
