# Generated by Django 4.2.16 on 2025-04-29 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizaciones",
            "0002_alter_organizacion_options_alter_organizacion_cuit_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoOrganizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Tipo de Organización",
                "verbose_name_plural": "Tipos de Organización",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="organizacion",
            name="firmante1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="firmante2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="firmante3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="tipo_organizacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizaciones",
                to="organizaciones.tipoorganizacion",
            ),
        ),
    ]
