# Generated by Django 4.2.16 on 2025-05-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizaciones", "0003_tipoorganizacion_organizacion_firmante1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacion",
            name="aval1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="aval2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="cuitaval1",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="cuitaval2",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
