# Generated by Django 4.2.20 on 2025-09-09 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizaciones", "0004_organizacion_municipio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizacion",
            name="tipo_organizacion",
        ),
    ]
