# Generated by Django 4.2.16 on 2025-05-08 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizaciones",
            "0005_firmanteecho_firmanteeclesiastica_firmantejuridica_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FirmanteEcho",
            new_name="FirmanteHecho",
        ),
        migrations.RenameField(
            model_name="organizacion",
            old_name="firmante_echo",
            new_name="firmante_hecho",
        ),
    ]
