# Generated by Django 4.2.20 on 2025-09-18 16:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizaciones", "0005_remove_organizacion_tipo_organizacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aval1",
            name="cuit",
            field=models.BigIntegerField(
                blank=True,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(99999999999),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="firmante",
            name="cuit",
            field=models.BigIntegerField(
                blank=True,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(99999999999),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="organizacion",
            name="cuit",
            field=models.BigIntegerField(
                blank=True,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(99999999999),
                ],
            ),
        ),
    ]
