# Generated by Django 4.2.20 on 2025-09-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizaciones",
            "0006_organizacion_fecha_inscripcion_alter_aval1_cuit_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacion",
            name="fecha_vencimiento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
