# Generated by Django 4.2.20 on 2025-10-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizaciones", "0006_aval_remove_aval2_organizacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacion",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
