# Generated by Django 4.2.16 on 2025-05-08 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizaciones", "0006_rename_firmanteecho_firmantehecho_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizacion",
            name="firmante_eclesiastica",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organizaciones.firmanteeclesiastica",
            ),
        ),
        migrations.AlterField(
            model_name="organizacion",
            name="firmante_hecho",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organizaciones.firmantehecho",
            ),
        ),
        migrations.AlterField(
            model_name="organizacion",
            name="firmante_juridica",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organizaciones.firmantejuridica",
            ),
        ),
    ]
