# Generated by Django 4.2.20 on 2025-09-22 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("organizaciones", "0007_organizacion_fecha_vencimiento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizacion",
            name="fecha_vencimiento",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Fecha de vencimiento"
            ),
        ),
    ]
