# Generated by Django 4.2.20 on 2025-09-22 18:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizaciones", "0008_alter_organizacion_fecha_vencimiento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "cuit",
                    models.BigIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99999999999),
                        ],
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avales1",
                        to="organizaciones.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aval",
                "verbose_name_plural": "Avales",
            },
        ),
        migrations.RemoveField(
            model_name="aval2",
            name="organizacion",
        ),
        migrations.DeleteModel(
            name="Aval1",
        ),
        migrations.DeleteModel(
            name="Aval2",
        ),
    ]
