# Generated by Django 4.2.20 on 2025-05-10 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizaciones",
            "0008_firmante_remove_organizacion_firmante_eclesiastica_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RolFirmante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Rol de Firmante",
                "verbose_name_plural": "Roles de Firmante",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="firmante",
            name="cuit",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="firmante",
            name="rol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="firmantes",
                to="organizaciones.rolfirmante",
            ),
        ),
    ]
