# Generated by Django 4.2.20 on 2025-06-09 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("organizaciones", "0010_tipoentidad_subtipoentidad_and_more"),
        ("organizaciones", "0011_alter_subtipoentidad_options_and_more"),
        ("organizaciones", "0012_alter_organizacion_subtipo_entidad_and_more"),
        ("organizaciones", "0013_subtipoentidad_tipo_entidad"),
        ("organizaciones", "0014_aval1_aval2"),
        ("organizaciones", "0015_aval1_organizacion_aval2_organizacion"),
        (
            "organizaciones",
            "0016_alter_aval1_cuit_alter_aval1_nombre_alter_aval2_cuit_and_more",
        ),
    ]

    dependencies = [
        ("organizaciones", "0009_rolfirmante_firmante_cuit_alter_firmante_rol"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoEntidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Tipo de Entidad",
                "verbose_name_plural": "Tipos de Entidad",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="SubtipoEntidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                (
                    "tipo_entidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtipos",
                        to="organizaciones.tipoentidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subtipo de Entidad",
                "verbose_name_plural": "Subtipos de Entidad",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="organizacion",
            name="subtipo_entidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizaciones",
                to="organizaciones.subtipoentidad",
            ),
        ),
        migrations.AddField(
            model_name="organizacion",
            name="tipo_entidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizaciones",
                to="organizaciones.tipoentidad",
            ),
        ),
        migrations.CreateModel(
            name="Aval1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                ("cuit", models.BigIntegerField(blank=True, null=True, unique=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avales1",
                        to="organizaciones.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aval 1",
                "verbose_name_plural": "Avales 1",
            },
        ),
        migrations.CreateModel(
            name="Aval2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                ("cuit", models.BigIntegerField(blank=True, null=True, unique=True)),
                (
                    "organizacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avales2",
                        to="organizaciones.organizacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aval 2",
                "verbose_name_plural": "Avales 2",
            },
        ),
    ]
