# Generated by Django 4.2.20 on 2025-09-24 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizaciones", "0010_alter_aval_organizacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="firmante",
            name="cuit",
            field=models.BigIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(99999999999),
                ],
            ),
        ),
    ]
