# Generated by Django 4.2.27 on 2026-03-17 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("VAT", "0002_remove_centro_faro_asociado_remove_centro_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="actividadcentro",
            name="fecha_fin",
            field=models.DateField(blank=True, null=True, verbose_name="Fecha de fin"),
        ),
        migrations.AddField(
            model_name="actividadcentro",
            name="fecha_inicio",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de inicio"
            ),
        ),
        migrations.CreateModel(
            name="Encuentro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_encuentro",
                    models.PositiveIntegerField(verbose_name="Número de encuentro"),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                ("hora_inicio", models.TimeField(verbose_name="Hora de inicio")),
                (
                    "hora_fin",
                    models.TimeField(blank=True, null=True, verbose_name="Hora de fin"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programado", "Programado"),
                            ("realizado", "Realizado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="programado",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "actividad_centro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encuentros",
                        to="VAT.actividadcentro",
                        verbose_name="Actividad del Centro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encuentro",
                "verbose_name_plural": "Encuentros",
                "ordering": ["fecha", "hora_inicio"],
                "unique_together": {("actividad_centro", "fecha")},
            },
        ),
        migrations.CreateModel(
            name="Asistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("presente", "Presente"),
                            ("ausente", "Ausente"),
                            ("justificado", "Justificado"),
                        ],
                        default="ausente",
                        max_length=20,
                        verbose_name="Estado de asistencia",
                    ),
                ),
                (
                    "hora_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Hora de registro"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "encuentro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="VAT.encuentro",
                        verbose_name="Encuentro",
                    ),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="VAT.participanteactividad",
                        verbose_name="Participante",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vat_asistencias_registradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistencia",
                "verbose_name_plural": "Asistencias",
            },
        ),
        migrations.AddConstraint(
            model_name="asistencia",
            constraint=models.UniqueConstraint(
                fields=("encuentro", "participante"),
                name="vat_unique_asistencia_encuentro_participante",
            ),
        ),
    ]
