# Generated by Django 4.2.27 on 2026-03-17 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("VAT", "0003_add_encuentro_asistencia_fechas_actividad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="centro",
            name="referente",
            field=models.ForeignKey(
                limit_choices_to={"groups__name": "ReferenteCentroVAT"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vat_centros",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
