# Generated by Django 4.2.27 on 2026-03-22 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("VAT", "0010_autoridadinstitucional_comision_comisionhorario_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inscripcionoferta",
            options={
                "ordering": ["-fecha_inscripcion"],
                "verbose_name": "Inscripción a Comisión",
                "verbose_name_plural": "Inscripciones a Comisiones",
            },
        ),
        migrations.AlterField(
            model_name="inscripcionoferta",
            name="oferta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inscripciones_oferta",
                to="VAT.comision",
                verbose_name="Comisión",
            ),
        ),
        migrations.DeleteModel(
            name="OfertaFormativa",
        ),
    ]
