# Generated by Django 4.2.27 on 2026-03-22 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("VAT", "0011_remove_ofertaformativa_inscripcion_to_comision"),
    ]

    operations = [
        migrations.CreateModel(
            name="SesionComision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_sesion",
                    models.PositiveIntegerField(verbose_name="Número de sesión"),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("programada", "Programada"),
                            ("realizada", "Realizada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="programada",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "comision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesiones",
                        to="VAT.comision",
                        verbose_name="Comisión",
                    ),
                ),
                (
                    "horario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sesiones",
                        to="VAT.comisionhorario",
                        verbose_name="Horario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión de Comisión",
                "verbose_name_plural": "Sesiones de Comisión",
                "ordering": ["fecha", "horario__hora_desde"],
                "indexes": [
                    models.Index(
                        fields=["comision", "estado"],
                        name="vat_sesion_comision_estado_idx",
                    )
                ],
                "unique_together": {("comision", "horario", "fecha")},
            },
        ),
    ]
