# Generated by Django 4.2.27 on 2026-03-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VAT", "0013_voucherparametria_inscripcion_unica_activa"),
    ]

    operations = [
        migrations.AddField(
            model_name="institucionubicacion",
            name="nombre_ubicacion",
            field=models.CharField(
                blank=True,
                help_text="Ejemplo: Sede Centro, Anexo Norte, Punto Barrio Sur.",
                max_length=120,
                null=True,
                verbose_name="Nombre de Ubicación",
            ),
        ),
    ]
