# Generated by Django 4.2.27 on 2026-03-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VAT", "0015_institucionidentificadorhist_ubicacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="centro",
            name="codigo_postal",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Código Postal",
            ),
        ),
        migrations.AddField(
            model_name="centro",
            name="entre_calles",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Entre Calles",
            ),
        ),
        migrations.AddField(
            model_name="centro",
            name="lote",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Lote",
            ),
        ),
        migrations.AddField(
            model_name="centro",
            name="manzana",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Manzana",
            ),
        ),
        migrations.AddField(
            model_name="institucioncontacto",
            name="email_contacto",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Correo del Contacto",
            ),
        ),
        migrations.AddField(
            model_name="institucioncontacto",
            name="nombre_contacto",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nombre del Contacto",
            ),
        ),
        migrations.AddField(
            model_name="institucioncontacto",
            name="rol_area",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Rol / Área",
            ),
        ),
        migrations.AddField(
            model_name="institucioncontacto",
            name="telefono_contacto",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Teléfono del Contacto",
            ),
        ),
    ]