# Generated by Django 4.2.27 on 2026-03-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("VAT", "0016_centro_campos_ubicacion_contacto_ampliado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="centro",
            name="fecha_alta",
        ),
        migrations.RemoveField(
            model_name="centro",
            name="foto",
        ),
        migrations.RemoveField(
            model_name="centro",
            name="link_redes",
        ),
        migrations.RemoveField(
            model_name="centro",
            name="modalidad_institucional",
        ),
        migrations.RemoveField(
            model_name="centro",
            name="organizacion_asociada",
        ),
    ]
