# Generated by Django 4.2.27 on 2026-03-31 15:50

import core.soft_delete.base
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("VAT", "0018_curso_comisioncurso"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="comisioncurso",
            managers=[
                ("objects", core.soft_delete.base.SoftDeleteManager()),
                (
                    "all_objects",
                    core.soft_delete.base.SoftDeleteManager(include_deleted=True),
                ),
            ],
        ),
        migrations.AlterModelManagers(
            name="curso",
            managers=[
                ("objects", core.soft_delete.base.SoftDeleteManager()),
                (
                    "all_objects",
                    core.soft_delete.base.SoftDeleteManager(include_deleted=True),
                ),
            ],
        ),
    ]
