# Generated by Django 4.2.27 on 2026-03-31 16:21

from django.db import migrations, models
import django.db.models.deletion


def _column_exists(schema_editor, table_name, column_name):
    with schema_editor.connection.cursor() as cursor:
        description = schema_editor.connection.introspection.get_table_description(
            cursor, table_name
        )
    return any(col.name == column_name for col in description)


def _add_plan_estudio_fk_columns_if_missing(apps, schema_editor):
    plan_model = apps.get_model("VAT", "PlanVersionCurricular")
    table_name = plan_model._meta.db_table

    if not _column_exists(schema_editor, table_name, "sector_id"):
        schema_editor.execute(
            f"ALTER TABLE `{table_name}` ADD COLUMN `sector_id` BIGINT NULL"
        )

    if not _column_exists(schema_editor, table_name, "subsector_id"):
        schema_editor.execute(
            f"ALTER TABLE `{table_name}` ADD COLUMN `subsector_id` BIGINT NULL"
        )


def _backfill_plan_estudio_sector_subsector(apps, schema_editor):
    # Usamos SQL crudo para evitar que el ORM seleccione columnas que pueden
    # no existir en la DB (ej: version/frecuencia ya eliminadas en DB pero
    # aún presentes en el historial del modelo).
    plan_model = apps.get_model("VAT", "PlanVersionCurricular")
    tabla_plan = plan_model._meta.db_table

    titulo_model = apps.get_model("VAT", "TituloReferencia")
    tabla_titulo = titulo_model._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f"""
            UPDATE `{tabla_plan}` p
            JOIN `{tabla_titulo}` t ON p.titulo_referencia_id = t.id
            SET
                p.sector_id = COALESCE(p.sector_id, t.sector_id),
                p.subsector_id = COALESCE(p.subsector_id, t.subsector_id)
            WHERE t.sector_id IS NOT NULL
            """
        )


def _remove_columns_if_exist(apps, schema_editor):
    plan_model = apps.get_model("VAT", "PlanVersionCurricular")
    table_name = plan_model._meta.db_table

    for col in ("version", "frecuencia"):
        if _column_exists(schema_editor, table_name, col):
            schema_editor.execute(
                f"ALTER TABLE `{table_name}` DROP COLUMN `{col}`"
            )


class Migration(migrations.Migration):

    dependencies = [
        ("VAT", "0019_alter_comisioncurso_managers_alter_curso_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="planversioncurricular",
            options={
                "ordering": ["titulo_referencia", "modalidad_cursada"],
                "verbose_name": "Plan de Estudio",
                "verbose_name_plural": "Planes de Estudio",
            },
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="planversioncurricular",
                    name="sector",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planes_estudio",
                        to="VAT.sector",
                        verbose_name="Sector",
                    ),
                ),
                migrations.AddField(
                    model_name="planversioncurricular",
                    name="subsector",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planes_estudio",
                        to="VAT.subsector",
                        verbose_name="Subsector",
                    ),
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    _add_plan_estudio_fk_columns_if_missing,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
        ),
        migrations.RunPython(
            _backfill_plan_estudio_sector_subsector,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="planversioncurricular",
            name="sector",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="planes_estudio",
                to="VAT.sector",
                verbose_name="Sector",
            ),
        ),
        migrations.AlterField(
            model_name="planversioncurricular",
            name="subsector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="planes_estudio",
                to="VAT.subsector",
                verbose_name="Subsector",
            ),
        ),
        migrations.AlterField(
            model_name="ofertainstitucional",
            name="plan_curricular",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ofertas_institucionales",
                to="VAT.planversioncurricular",
                verbose_name="Plan de Estudio",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="planversioncurricular",
                    name="frecuencia",
                ),
                migrations.RemoveField(
                    model_name="planversioncurricular",
                    name="version",
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    _remove_columns_if_exist,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name="planversioncurricular",
                    unique_together={("titulo_referencia", "modalidad_cursada")},
                )
            ],
            database_operations=[],
        ),
    ]
