# Generated by Django 4.2.27 on 2026-04-01 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_programa_organismo_programa_descripcion"),
        ("VAT", "0025_alter_curso_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="costo_creditos",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Cantidad de créditos a debitar por inscripción cuando usa voucher.",
                verbose_name="Costo en créditos",
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="programa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cursos_vat",
                to="core.programa",
                verbose_name="Programa",
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="usa_voucher",
            field=models.BooleanField(
                default=False,
                help_text="Si está activo, las inscripciones del curso validan y descuentan créditos de voucher.",
                verbose_name="Usa Voucher",
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="voucher_parametrias",
            field=models.ManyToManyField(
                blank=True,
                help_text="Parametrías de voucher permitidas para este curso.",
                related_name="cursos",
                to="VAT.voucherparametria",
                verbose_name="Vouchers habilitados",
            ),
        ),
    ]
