# Generated by Django 4.2 on 2026-04-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("VAT", "0026_curso_costo_creditos_curso_programa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="plan_estudio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.PROTECT,
                related_name="cursos",
                to="VAT.planversioncurricular",
                verbose_name="Plan de Estudio",
            ),
        ),
    ]
