# Generated by Django 4.2.27 on 2026-04-01 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("VAT", "0027_curso_plan_estudio"),
    ]

    operations = [
        migrations.AddField(
            model_name="comisionhorario",
            name="comision_curso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="horarios",
                to="VAT.comisioncurso",
                verbose_name="Comisión de Curso",
            ),
        ),
        migrations.AddField(
            model_name="inscripcion",
            name="comision_curso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inscripciones",
                to="VAT.comisioncurso",
                verbose_name="Comisión de Curso",
            ),
        ),
        migrations.AddField(
            model_name="sesioncomision",
            name="comision_curso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sesiones",
                to="VAT.comisioncurso",
                verbose_name="Comisión de Curso",
            ),
        ),
        migrations.AlterField(
            model_name="comisionhorario",
            name="comision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="horarios",
                to="VAT.comision",
                verbose_name="Comisión",
            ),
        ),
        migrations.AlterField(
            model_name="inscripcion",
            name="comision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inscripciones",
                to="VAT.comision",
                verbose_name="Comisión",
            ),
        ),
        migrations.AlterField(
            model_name="sesioncomision",
            name="comision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sesiones",
                to="VAT.comision",
                verbose_name="Comisión",
            ),
        ),
    ]
