# Generated by Django 4.2.27 on 2026-07-27 17:17

import core.soft_delete.base
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("VAT", "0049_comisioncurso_cupo_lista_espera"),
    ]

    operations = [
        migrations.AddField(
            model_name="inscripcion",
            name="resultado_fecha",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Carga del Resultado"
            ),
        ),
        migrations.AddField(
            model_name="inscripcion",
            name="resultado_final",
            field=models.CharField(
                blank=True,
                choices=[("aprobado", "Aprobado"), ("desaprobado", "Desaprobado")],
                help_text="Vacío = sin calificar.",
                max_length=20,
                null=True,
                verbose_name="Resultado Final",
            ),
        ),
        migrations.AddField(
            model_name="inscripcion",
            name="resultado_registrado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vat_resultados_curso_registrados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Resultado registrado por",
            ),
        ),
        migrations.CreateModel(
            name="ProfesorCentro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("apellido", models.CharField(max_length=255, verbose_name="Apellido")),
                ("nombre", models.CharField(max_length=255, verbose_name="Nombre")),
                ("documento", models.PositiveBigIntegerField(verbose_name="Documento")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "centro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vat_profesores",
                        to="VAT.centro",
                        verbose_name="Centro",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profesor de Centro",
                "verbose_name_plural": "Profesores de Centro",
                "ordering": ["apellido", "nombre"],
            },
            managers=[
                ("objects", core.soft_delete.base.SoftDeleteManager()),
                (
                    "all_objects",
                    core.soft_delete.base.SoftDeleteManager(include_deleted=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActaCierreComision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("fecha_fin", models.DateField(verbose_name="Fecha de Fin")),
                (
                    "numero_acta",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="N° de Acta"
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "comision_curso",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acta_cierre",
                        to="VAT.comisioncurso",
                        verbose_name="Comisión de Curso",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vat_actas_cierre",
                        to="VAT.profesorcentro",
                        verbose_name="Profesor a Cargo",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vat_actas_cierre_registradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acta de Cierre de Comisión",
                "verbose_name_plural": "Actas de Cierre de Comisión",
                "ordering": ["-fecha_fin"],
            },
            managers=[
                ("objects", core.soft_delete.base.SoftDeleteManager()),
                (
                    "all_objects",
                    core.soft_delete.base.SoftDeleteManager(include_deleted=True),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="profesorcentro",
            index=models.Index(
                fields=["centro", "apellido"], name="vat_prof_centro_ape_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="profesorcentro",
            unique_together={("centro", "documento")},
        ),
    ]
