services:
  bulk_credentials_worker:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    env_file:
      - .env
    environment:
      TZ: America/Argentina/Buenos_Aires
      DJANGO_SERVICE_ROLE: bulk_credentials_worker
    volumes:
      - .:/sisoc/
    user: "${RUN_UID:-0}:${RUN_GID:-0}"
    restart: unless-stopped
