# Generated by Django 4.2.20 on 2025-07-14 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0003_alter_comedor_localidad_alter_comedor_municipio_and_more"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prestacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.CharField(
                        choices=[
                            ("lunes", "Lunes"),
                            ("martes", "Martes"),
                            ("miercoles", "Miércoles"),
                            ("jueves", "Jueves"),
                            ("viernes", "Viernes"),
                            ("sabado", "Sábado"),
                            ("domingo", "Domingo"),
                        ],
                        max_length=20,
                        verbose_name="Día de la semana",
                    ),
                ),
                (
                    "desayuno",
                    models.BooleanField(default=False, verbose_name="Desayuno"),
                ),
                (
                    "almuerzo",
                    models.BooleanField(default=False, verbose_name="Almuerzo"),
                ),
                (
                    "merienda",
                    models.BooleanField(default=False, verbose_name="Merienda"),
                ),
                ("cena", models.BooleanField(default=False, verbose_name="Cena")),
                (
                    "desayuno_cantidad_actual",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Cantidad actual desayuno"
                    ),
                ),
                (
                    "desayuno_cantidad_espera",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Cantidad esperada desayuno"
                    ),
                ),
                (
                    "almuerzo_cantidad_actual",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Cantidad actual almuerzo"
                    ),
                ),
                (
                    "almuerzo_cantidad_espera",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Cantidad esperada almuerzo"
                    ),
                ),
                (
                    "merienda_cantidad_actual",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Cantidad actual merienda"
                    ),
                ),
                (
                    "merienda_cantidad_espera",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Cantidad esperada merienda"
                    ),
                ),
                (
                    "cena_cantidad_actual",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Cantidad actual cena"
                    ),
                ),
                (
                    "cena_cantidad_espera",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Cantidad esperada cena"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestaciones",
                        to="comedores.comedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestación",
                "verbose_name_plural": "Prestaciones",
                "ordering": ["comedor", "dia"],
                "unique_together": {("comedor", "dia")},
            },
        ),
    ]
