# Generated by Django 4.2.20 on 2025-07-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_migrate_prestacion_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="prestacion",
            name="merienda_reforzada",
            field=models.BooleanField(default=False, verbose_name="Merienda reforzada"),
        ),
        migrations.AddField(
            model_name="prestacion",
            name="merienda_reforzada_cantidad_actual",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Cantidad actual merienda reforzada"
            ),
        ),
        migrations.AddField(
            model_name="prestacion",
            name="merienda_reforzada_cantidad_espera",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Cantidad esperada merienda reforzada",
            ),
        ),
    ]
