# Generated by Django 4.2.27 on 2026-02-18 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0006_preferencia_columnas"),
    ]

    operations = [
        migrations.CreateModel(
            name="MontoPrestacionPrograma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="montos_prestacion",
                        to="core.programa",
                        verbose_name="Programa",
                    ),
                ),
                (
                    "desayuno_valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor desayuno",
                    ),
                ),
                (
                    "almuerzo_valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor almuerzo",
                    ),
                ),
                (
                    "merienda_valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor merienda",
                    ),
                ),
                (
                    "cena_valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor cena",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestación",
                "verbose_name_plural": "Prestaciones",
                "ordering": ["id"],
            },
        ),
        migrations.AddConstraint(
            model_name="montoprestacionprograma",
            constraint=models.CheckConstraint(
                check=(
                    models.Q(desayuno_valor__isnull=False)
                    | models.Q(almuerzo_valor__isnull=False)
                    | models.Q(merienda_valor__isnull=False)
                    | models.Q(cena_valor__isnull=False)
                ),
                name="monto_prestacion_al_menos_un_valor",
            ),
        ),
    ]
