# Generated by Django 4.2.27 on 2026-02-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0021_alter_nomina_estado"),
        ("comunicados", "0002_crear_grupos_permisos"),
    ]

    operations = [
        migrations.AddField(
            model_name="comunicado",
            name="comedores",
            field=models.ManyToManyField(
                blank=True,
                related_name="comunicados",
                to="comedores.comedor",
                verbose_name="Comedores destinatarios",
            ),
        ),
        migrations.AddField(
            model_name="comunicado",
            name="para_todos_comedores",
            field=models.BooleanField(
                default=False, verbose_name="Enviar a todos los comedores"
            ),
        ),
        migrations.AddField(
            model_name="comunicado",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("interno", "Comunicación Interna"),
                    ("externo", "Comunicación a Comedores"),
                ],
                default="interno",
                max_length=20,
                verbose_name="Tipo de comunicado",
            ),
        ),
    ]
