# Generated by Django 4.2.27 on 2026-02-13 13:10

from django.db import migrations


def create_groups(apps, schema_editor):
    """Crea los grupos de permisos para Comunicados v2."""
    Group = apps.get_model('auth', 'Group')

    grupos = [
        "Comunicado Interno Crear",
        "Comunicado Interno Editar",
        "Comunicado Interno Publicar",
        "Comunicado Interno Archivar",
        "Comunicado Comedores Crear",
        "Comunicado Comedores Editar",
        "Comunicado Comedores Publicar",
        "Comunicado Comedores Archivar",
    ]

    for nombre in grupos:
        Group.objects.get_or_create(name=nombre)


def remove_groups(apps, schema_editor):
    """Elimina los grupos (rollback)."""
    Group = apps.get_model('auth', 'Group')

    grupos = [
        "Comunicado Interno Crear",
        "Comunicado Interno Editar",
        "Comunicado Interno Publicar",
        "Comunicado Interno Archivar",
        "Comunicado Comedores Crear",
        "Comunicado Comedores Editar",
        "Comunicado Comedores Publicar",
        "Comunicado Comedores Archivar",
    ]

    Group.objects.filter(name__in=grupos).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("comunicados", "0003_add_tipo_comedores"),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]
