# Generated by Django 4.2.27 on 2026-02-13 13:10

from django.db import migrations


def create_groups(apps, schema_editor):
    """No-op: la creación de grupos se resuelve en bootstrap."""
    return


def remove_groups(apps, schema_editor):
    """No-op: no se eliminan grupos en migraciones."""
    return


class Migration(migrations.Migration):

    dependencies = [
        ("comunicados", "0003_add_tipo_comedores"),
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups),
    ]
