# Generated by Django 4.2.27 on 2026-02-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comunicados", "0005_add_subtipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comunicado",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("interno", "Comunicación Interna"),
                    ("externo", "Comunicación Externa"),
                ],
                default="interno",
                max_length=20,
                verbose_name="Tipo de comunicado",
            ),
        ),
    ]
