# Generated by Django 4.2.27 on 2026-06-10 15:08

import comunicados.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comunicados", "0001_squashed_0006"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to=comunicados.models.mailing_job_upload_to
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("asunto", models.CharField(max_length=255, verbose_name="Asunto")),
                ("cuerpo", models.TextField(verbose_name="Cuerpo")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("processed_rows", models.PositiveIntegerField(default=0)),
                ("sent_rows", models.PositiveIntegerField(default=0)),
                ("rejected_rows", models.PositiveIntegerField(default=0)),
                ("next_row_index", models.PositiveIntegerField(default=0)),
                (
                    "last_successful_row",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("last_successful_mail", models.EmailField(blank=True, max_length=254)),
                (
                    "last_attempted_row",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("last_attempted_mail", models.EmailField(blank=True, max_length=254)),
                ("last_error_message", models.TextField(blank=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("resume_count", models.PositiveIntegerField(default=0)),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_activity_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="mailing_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lote de mailing",
                "verbose_name_plural": "Lotes de mailing",
                "ordering": ["-requested_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MailingJobRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fila", models.PositiveIntegerField()),
                ("mail_destino", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Enviado"), ("failed", "Fallido")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("mensaje", models.TextField(blank=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="comunicados.mailingjob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado de fila de mailing",
                "verbose_name_plural": "Resultados de filas de mailing",
                "ordering": ["fila", "id"],
                "indexes": [
                    models.Index(
                        fields=["job", "status"], name="comunicados_job_id_ff2531_idx"
                    ),
                    models.Index(
                        fields=["job", "processed_at"],
                        name="comunicados_job_id_30fa08_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="mailingjobrow",
            constraint=models.UniqueConstraint(
                fields=("job", "fila"), name="comunicados_mailing_job_row_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="mailingjob",
            index=models.Index(
                fields=["status", "requested_at"], name="comunicados_status_7ae892_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mailingjob",
            index=models.Index(
                fields=["requested_by", "requested_at"],
                name="comunicados_request_165467_idx",
            ),
        ),
    ]
