# Generated by Django 4.2.16 on 2025-01-15 03:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name="Acciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                (
                    "observaciones",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "verbose_name": "Acciones",
                "verbose_name_plural": "Acciones",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="AgentesExternos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("apellido", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.PositiveIntegerField(blank=True, null=True)),
                ("rol", models.CharField(blank=True, max_length=30, null=True)),
                ("estado", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Agente Externo",
                "verbose_name_plural": "Agentes Externos",
                "ordering": ["apellido"],
            },
        ),
        migrations.CreateModel(
            name="Barrio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barrio", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Barrio",
                "verbose_name_plural": "Barrios",
            },
        ),
        migrations.CreateModel(
            name="CategoriaAlertas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("estado", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "CategoriaAlertas",
                "verbose_name_plural": "CategoriasAlertas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Circuito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("circuito", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Circuito",
                "verbose_name_plural": "Circuitos",
            },
        ),
        migrations.CreateModel(
            name="CriterioAlerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criterio", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Criterio de Alerta",
                "verbose_name_plural": "Criterios de Alerta",
            },
        ),
        migrations.CreateModel(
            name="Criterios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("permite_potencial", models.BooleanField(default=False)),
                ("estado", models.BooleanField(default=True)),
                (
                    "observaciones",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "verbose_name": "Criterio",
                "verbose_name_plural": "Criterios",
                "ordering": ["fk_sujeto"],
            },
        ),
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamento",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Dimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dimension", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Dimensión",
                "verbose_name_plural": "Dimensiones",
            },
        ),
        migrations.CreateModel(
            name="Impacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("impacto", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Impacto",
                "verbose_name_plural": "Impactos",
            },
        ),
        migrations.CreateModel(
            name="IndiceCriterios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "puntaje_base",
                    models.PositiveSmallIntegerField(
                        help_text="Permite valores entre 0 y 10.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "fk_criterio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fkcriterio",
                        to="configuraciones.criterios",
                    ),
                ),
            ],
            options={
                "verbose_name": "IndiceCriterios",
                "verbose_name_plural": "IndicesCriterios",
            },
        ),
        migrations.CreateModel(
            name="Jurisdiccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jurisdiccion", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Jurisdicción",
                "verbose_name_plural": "Jurisdicciones",
            },
        ),
        migrations.CreateModel(
            name="Localidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "fk_departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="configuraciones.departamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Localidad",
                "verbose_name_plural": "Localidad",
            },
        ),
        migrations.CreateModel(
            name="Organismos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("calle", models.CharField(blank=True, max_length=255, null=True)),
                ("altura", models.IntegerField(blank=True, null=True)),
                ("piso", models.CharField(blank=True, max_length=255, null=True)),
                ("telefono", models.IntegerField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("estado", models.BooleanField(default=True)),
                (
                    "observaciones",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "barrio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuraciones.barrio",
                    ),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuraciones.localidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organismo",
                "verbose_name_plural": "Organismos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Programas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("estado", models.BooleanField(default=True)),
                (
                    "observaciones",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "verbose_name": "Programa",
                "verbose_name_plural": "Programas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Provincia",
                "verbose_name_plural": "Provincia",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SalaVacante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sala", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Sala Vacante",
                "verbose_name_plural": "Salas Vacantes",
            },
        ),
        migrations.CreateModel(
            name="Secretarias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                (
                    "observaciones",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("estado", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Secretaría",
                "verbose_name_plural": "Secretarías",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Sujetos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Sujetos",
                "verbose_name_plural": "Sujetos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoDeDato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Tipo de Dato",
                "verbose_name_plural": "Tipos de Datos",
            },
        ),
        migrations.CreateModel(
            name="TipoDeFormulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Tipo de Formulario",
                "verbose_name_plural": "Tipos de Formularios",
            },
        ),
        migrations.CreateModel(
            name="TipoOrganismo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Tipo de Organismo",
                "verbose_name_plural": "Tipos de Organismos",
            },
        ),
        migrations.CreateModel(
            name="TurnoVacante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("turno", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Turno Vacante",
                "verbose_name_plural": "Turnos Vacantes",
            },
        ),
        migrations.CreateModel(
            name="Vacantes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "observaciones",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "manianabb",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Turno Mañana",
                    ),
                ),
                (
                    "tardebb",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Turno Tarde",
                    ),
                ),
                (
                    "maniana2",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Turno Mañana",
                    ),
                ),
                (
                    "tarde2",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Turno Tarde",
                    ),
                ),
                (
                    "maniana3",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Turno Mañana",
                    ),
                ),
                (
                    "tarde3",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Turno Tarde",
                    ),
                ),
                (
                    "maniana4",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Turno Mañana",
                    ),
                ),
                (
                    "tarde4",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Turno Tarde",
                    ),
                ),
                ("estado", models.BooleanField(default=True)),
                (
                    "fk_organismo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuraciones.organismos",
                    ),
                ),
                (
                    "fk_programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuraciones.programas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vacante",
                "verbose_name_plural": "Vacantes",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Subsecretarias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                (
                    "observaciones",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("estado", models.BooleanField(default=True)),
                (
                    "fk_secretaria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuraciones.secretarias",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subsecretaría",
                "verbose_name_plural": "Subecretarías",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="programas",
            name="fk_subsecretaria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="configuraciones.subsecretarias",
            ),
        ),
        migrations.CreateModel(
            name="PlanesSociales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("estado", models.BooleanField(default=True)),
                (
                    "observaciones",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "jurisdiccion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuraciones.jurisdiccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "PlanSocial",
                "verbose_name_plural": "PlanesSociales",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="organismos",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="configuraciones.tipoorganismo",
            ),
        ),
        migrations.CreateModel(
            name="Municipio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "fk_provincia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="configuraciones.provincia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Municipio",
                "verbose_name_plural": "Municipio",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="localidad",
            name="fk_municipio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="configuraciones.municipio",
            ),
        ),
        migrations.CreateModel(
            name="Indices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                (
                    "observaciones",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("estado", models.BooleanField(default=True)),
                (
                    "m2m_criterios",
                    models.ManyToManyField(
                        through="configuraciones.IndiceCriterios",
                        to="configuraciones.criterios",
                    ),
                ),
                (
                    "m2m_programas",
                    models.ManyToManyField(to="configuraciones.programas"),
                ),
            ],
            options={
                "verbose_name": "Indice",
                "verbose_name_plural": "Indices",
            },
        ),
        migrations.AddField(
            model_name="indicecriterios",
            name="fk_indice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fkindice",
                to="configuraciones.indices",
            ),
        ),
        migrations.CreateModel(
            name="GruposDestinatarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "observaciones",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("estado", models.BooleanField(default=True)),
                (
                    "m2m_agentes_externos",
                    models.ManyToManyField(
                        blank=True, to="configuraciones.agentesexternos"
                    ),
                ),
                (
                    "m2m_usuarios",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "GrupoDestinatarios",
                "verbose_name_plural": "GruposDestinatarios",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Equipos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "observaciones",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("estado", models.BooleanField(default=True)),
                (
                    "fk_coordinador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fkcoordinador",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fk_programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuraciones.programas",
                    ),
                ),
                ("m2m_usuarios", models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Equipo",
                "verbose_name_plural": "Equipos",
                "ordering": ["nombre"],
            },
        ),
        migrations.AddField(
            model_name="departamento",
            name="fk_provincia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="configuraciones.provincia",
            ),
        ),
        migrations.AddField(
            model_name="criterios",
            name="dimension",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="configuraciones.dimension",
                verbose_name="Dimensión",
            ),
        ),
        migrations.AddField(
            model_name="criterios",
            name="fk_sujeto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="configuraciones.sujetos",
            ),
        ),
        migrations.AddField(
            model_name="criterios",
            name="m2m_acciones",
            field=models.ManyToManyField(blank=True, to="configuraciones.acciones"),
        ),
        migrations.AddField(
            model_name="criterios",
            name="m2m_alertas",
            field=models.ManyToManyField(
                blank=True, to="configuraciones.categoriaalertas"
            ),
        ),
        migrations.AddField(
            model_name="categoriaalertas",
            name="dimension",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="configuraciones.dimension",
            ),
        ),
        migrations.CreateModel(
            name="Asentamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "fk_departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="configuraciones.departamento",
                    ),
                ),
                (
                    "fk_localidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="configuraciones.localidad",
                    ),
                ),
                (
                    "fk_municipio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="configuraciones.municipio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asentamiento",
                "verbose_name_plural": "Asentamientos",
            },
        ),
        migrations.AddField(
            model_name="agentesexternos",
            name="fk_organismo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="configuraciones.organismos",
            ),
        ),
        migrations.AddField(
            model_name="acciones",
            name="dimension",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="configuraciones.dimension",
                verbose_name="Dimensión",
            ),
        ),
        migrations.CreateModel(
            name="Alertas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("estado", models.BooleanField(default=True)),
                ("gravedad", models.CharField(max_length=500)),
                (
                    "fk_categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="configuraciones.categoriaalertas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta",
                "verbose_name_plural": "Alertas",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(
                        fields=["fk_categoria"], name="configuraci_fk_cate_e4ddce_idx"
                    ),
                    models.Index(
                        fields=["gravedad"], name="configuraci_graveda_d5db37_idx"
                    ),
                ],
            },
        ),
    ]
