# Generated by Django 4.2.20 on 2025-07-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuraciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Estados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estado", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Estado",
                "verbose_name_plural": "Estados",
            },
        ),
    ]
