# Generated by Django 4.2.16 on 2025-01-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuraciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sexo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sexo", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "Sexo",
                "verbose_name_plural": "Sexos",
            },
        ),
    ]
