# Generated by Django 4.0.2 on 2024-07-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuraciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertas',
            name='gravedad',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
