# Generated by Django 4.2.20 on 2025-06-26 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuraciones", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Dia",
        ),
        migrations.AlterUniqueTogether(
            name="localidad",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="localidad",
            name="municipio",
        ),
        migrations.DeleteModel(
            name="Mes",
        ),
        migrations.AlterUniqueTogether(
            name="municipio",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="municipio",
            name="provincia",
        ),
        migrations.DeleteModel(
            name="Sexo",
        ),
        migrations.DeleteModel(
            name="Turno",
        ),
        migrations.DeleteModel(
            name="Localidad",
        ),
        migrations.DeleteModel(
            name="Municipio",
        ),
        migrations.DeleteModel(
            name="Provincia",
        ),
    ]
