# Generated by Django 4.0.2 on 2024-09-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciones',
            name='dimension',
            field=models.CharField(choices=[(None, ''), ('FAMILIA', 'Familia'), ('VIVIENDA', 'Vivienda'), ('SALUD', 'Salud'), ('ECONOMIA', 'Economía'), ('EDUCACIÓN', 'Educación'), ('TRABAJO', 'Trabajo')], default='Desconocida', max_length=255),
        ),
        migrations.AlterField(
            model_name='categoriaalertas',
            name='dimension',
            field=models.CharField(blank=True, choices=[(None, ''), ('FAMILIA', 'Familia'), ('VIVIENDA', 'Vivienda'), ('SALUD', 'Salud'), ('ECONOMIA', 'Economía'), ('EDUCACIÓN', 'Educación'), ('TRABAJO', 'Trabajo')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='criterios',
            name='dimension',
            field=models.CharField(choices=[(None, ''), ('FAMILIA', 'Familia'), ('VIVIENDA', 'Vivienda'), ('SALUD', 'Salud'), ('ECONOMIA', 'Economía'), ('EDUCACIÓN', 'Educación'), ('TRABAJO', 'Trabajo')], default='Desconocida', max_length=255),
        ),
    ]
