# Generated by Django 4.0.2 on 2024-07-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuraciones', '0002_alter_alertas_gravedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertas',
            name='gravedad',
            field=models.CharField(max_length=500),
        ),
        migrations.AddIndex(
            model_name='alertas',
            index=models.Index(fields=['fk_categoria'], name='Configuraci_fk_cate_0c10ac_idx'),
        ),
        migrations.AddIndex(
            model_name='alertas',
            index=models.Index(fields=['gravedad'], name='Configuraci_graveda_707548_idx'),
        ),
    ]
