# Generated by Django 4.2.20 on 2025-07-04 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuraciones", "0002_estados"),
    ]

    operations = [
        migrations.RenameField(
            model_name="estados",
            old_name="estado",
            new_name="nombre",
        ),
    ]
