# Generated by Django 4.0.2 on 2024-10-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0002_alter_acciones_dimension_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrio', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Barrio',
                'verbose_name_plural': 'Barrios',
            },
        ),
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuito', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Circuito',
                'verbose_name_plural': 'Circuitos',
            },
        ),
        migrations.CreateModel(
            name='CriterioAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Criterio de Alerta',
                'verbose_name_plural': 'Criterios de Alerta',
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Dimensión',
                'verbose_name_plural': 'Dimensiones',
            },
        ),
        migrations.CreateModel(
            name='Impacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impacto', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Impacto',
                'verbose_name_plural': 'Impactos',
            },
        ),
        migrations.CreateModel(
            name='Jurisdiccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiccion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Jurisdicción',
                'verbose_name_plural': 'Jurisdicciones',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localidad', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='SalaVacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Sala Vacante',
                'verbose_name_plural': 'Salas Vacantes',
            },
        ),
        migrations.CreateModel(
            name='TipoDeDato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de Dato',
                'verbose_name_plural': 'Tipos de Datos',
            },
        ),
        migrations.CreateModel(
            name='TipoDeFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de Formulario',
                'verbose_name_plural': 'Tipos de Formularios',
            },
        ),
        migrations.CreateModel(
            name='TipoOrganismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de Organismo',
                'verbose_name_plural': 'Tipos de Organismos',
            },
        ),
        migrations.CreateModel(
            name='TurnoVacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Turno Vacante',
                'verbose_name_plural': 'Turnos Vacantes',
            },
        ),
        migrations.AlterField(
            model_name='acciones',
            name='dimension',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuraciones.dimension', verbose_name='Dimensión'),
        ),
        migrations.AlterField(
            model_name='categoriaalertas',
            name='dimension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuraciones.dimension'),
        ),
        migrations.AlterField(
            model_name='criterios',
            name='dimension',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuraciones.dimension', verbose_name='Dimensión'),
        ),
        migrations.AlterField(
            model_name='organismos',
            name='barrio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuraciones.barrio'),
        ),
        migrations.AlterField(
            model_name='organismos',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuraciones.localidad'),
        ),
        migrations.AlterField(
            model_name='organismos',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuraciones.tipoorganismo'),
        ),
        migrations.AlterField(
            model_name='planessociales',
            name='jurisdiccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='configuraciones.jurisdiccion'),
        ),
    ]
