# Generated by Django 4.2.20 on 2025-07-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuraciones", "0002_delete_migrated_models_after_core_migration"),
        ("configuraciones", "0003_rename_estado_estados_nombre"),
    ]

    operations = []
