# Generated by Django 4.0.2 on 2024-08-09 15:08

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('Configuraciones', '0003_alter_alertas_gravedad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionesGruposDestinatariosM2MUsuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('m2m_usuarios', models.ManyToManyField(to='Usuarios', blank=True)),
            ],
        ),
    ]
