# Generated by Django 4.2.20 on 2025-07-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuraciones", "0004_merge_20250710_0642"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Estados",
        ),
    ]
