# Generated by Django 4.2.16 on 2025-04-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuraciones", "0006_dia_mes_turno"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departamento",
            name="fk_provincia",
        ),
        migrations.RenameField(
            model_name="localidad",
            old_name="fk_municipio",
            new_name="municipio",
        ),
        migrations.RenameField(
            model_name="municipio",
            old_name="fk_provincia",
            new_name="provincia",
        ),
        migrations.RemoveField(
            model_name="localidad",
            name="fk_departamento",
        ),
        migrations.DeleteModel(
            name="Asentamiento",
        ),
        migrations.DeleteModel(
            name="Departamento",
        ),
    ]
