# Generated by Django 4.2.16 on 2025-04-01 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuraciones", "0006_dia_mes_turno"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="departamento",
            name="fk_provincia",
        ),
        migrations.RemoveField(
            model_name="localidad",
            name="fk_departamento",
        ),
        migrations.DeleteModel(
            name="Asentamiento",
        ),
        migrations.DeleteModel(
            name="Departamento",
        ),
    ]
