# Generated by Django 4.2.16 on 2025-04-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("configuraciones", "0007_remove_departamento_fk_provincia_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="localidad",
            old_name="fk_municipio",
            new_name="municipio",
        ),
        migrations.RenameField(
            model_name="municipio",
            old_name="fk_provincia",
            new_name="provincia",
        ),
    ]
