from django.contrib import admin


from relevamientos.models import (
    ActividadesExtrasSeguimiento,
    AlmacenamientoAlimentosSeguimiento,
    AsistenciaTecnicaSeguimiento,
    CantidadColaboradores,
    CierreSeguimiento,
    ComprasSeguimiento,
    CondicionesHigieneSeguimiento,
    FrecuenciaLimpieza,
    FrecuenciaAlimentosSeguimiento,
    FrecuenciaCompraAlimentosSeguimiento,
    FrecuenciaRecepcionRecursos,
    FuenteCompras,
    FuenteRecursos,
    FuncionamientoSeguimiento,
    ItemRecetaSeguimiento,
    MenuSeguimiento,
    TipoAgua,
    TipoCombustible,
    TipoDesague,
    TipoEspacio,
    TipoGestionQuejas,
    TipoModalidadPrestacion,
    TipoRecurso,
    Excepcion,
    MotivoExcepcion,
    Prestacion,
    PrestacionSeguimiento,
    PrimerSeguimiento,
    Relevamiento,
    RegistroAsistenciaSeguimiento,
    RendicionCuentasSeguimiento,
    RecursosSeguimiento,
    ServiciosBasicosSeguimiento,
    TareasComedorSeguimiento,
    TarjetaSeguimiento,
)

admin.site.register(TipoModalidadPrestacion)
admin.site.register(TipoEspacio)
admin.site.register(TipoCombustible)
admin.site.register(TipoAgua)
admin.site.register(TipoDesague)
admin.site.register(FrecuenciaLimpieza)
admin.site.register(CantidadColaboradores)
admin.site.register(FrecuenciaRecepcionRecursos)
admin.site.register(TipoGestionQuejas)
admin.site.register(TipoRecurso)
admin.site.register(FuenteRecursos)
admin.site.register(FuenteCompras)
admin.site.register(Prestacion)
admin.site.register(Relevamiento)
admin.site.register(MotivoExcepcion)
admin.site.register(Excepcion)
admin.site.register(FuncionamientoSeguimiento)
admin.site.register(ServiciosBasicosSeguimiento)
admin.site.register(AlmacenamientoAlimentosSeguimiento)
admin.site.register(CondicionesHigieneSeguimiento)
admin.site.register(TareasComedorSeguimiento)
admin.site.register(RecursosSeguimiento)
admin.site.register(ComprasSeguimiento)
admin.site.register(FrecuenciaCompraAlimentosSeguimiento)
admin.site.register(MenuSeguimiento)
admin.site.register(RegistroAsistenciaSeguimiento)
admin.site.register(FrecuenciaAlimentosSeguimiento)
admin.site.register(ActividadesExtrasSeguimiento)
admin.site.register(TarjetaSeguimiento)
admin.site.register(RendicionCuentasSeguimiento)
admin.site.register(AsistenciaTecnicaSeguimiento)
admin.site.register(CierreSeguimiento)
admin.site.register(PrimerSeguimiento)
admin.site.register(PrestacionSeguimiento)
admin.site.register(ItemRecetaSeguimiento)
