# Generated by Django 4.2.20 on 2025-07-31 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizaciones", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "ciudadanos",
            "0002_alter_ciudadano_localidad_alter_ciudadano_municipio_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la Actividad"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la Categoría"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.CreateModel(
            name="Centro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("faro", "faro"), ("adherido", "Adherido")],
                        max_length=20,
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="centros/"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("calle", models.CharField(blank=True, max_length=255, null=True)),
                ("numero", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "domicilio_actividad",
                    models.CharField(
                        max_length=255, verbose_name="Domicilio de actividades"
                    ),
                ),
                ("telefono", models.CharField(max_length=50, verbose_name="Teléfono")),
                ("celular", models.CharField(max_length=50, verbose_name="Celular")),
                (
                    "correo",
                    models.EmailField(
                        max_length=100, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "sitio_web",
                    models.URLField(blank=True, null=True, verbose_name="Sitio web"),
                ),
                (
                    "link_redes",
                    models.URLField(
                        blank=True, null=True, verbose_name="Redes sociales"
                    ),
                ),
                (
                    "nombre_referente",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del responsable"
                    ),
                ),
                (
                    "apellido_referente",
                    models.CharField(
                        max_length=100, verbose_name="Apellido del responsable"
                    ),
                ),
                (
                    "telefono_referente",
                    models.CharField(
                        max_length=50, verbose_name="Teléfono del responsable"
                    ),
                ),
                (
                    "correo_referente",
                    models.EmailField(
                        max_length=100, verbose_name="Correo del responsable"
                    ),
                ),
                (
                    "faro_asociado",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"activo": True, "tipo": "faro"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="centrodefamilia.centro",
                    ),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.localidad",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.municipio",
                    ),
                ),
                (
                    "organizacion_asociada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizaciones.organizacion",
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.provincia",
                    ),
                ),
                (
                    "referente",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "ReferenteCentro"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="centros",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="informes_cabal/")),
                (
                    "periodo",
                    models.DateField(
                        db_index=True, help_text="Fecha del informe Cabal"
                    ),
                ),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                ("procesado", models.BooleanField(db_index=True, default=False)),
                ("errores", models.TextField(blank=True)),
                (
                    "centro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expedientes_cabal",
                        to="centrodefamilia.centro",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expediente Cabal",
                "verbose_name_plural": "Expedientes Cabal",
                "ordering": ["-fecha_subida"],
            },
        ),
        migrations.CreateModel(
            name="ActividadCentro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_personas",
                    models.PositiveIntegerField(
                        verbose_name="Cantidad Estimada de Participantes"
                    ),
                ),
                ("horariosdesde", models.TimeField()),
                ("horarioshasta", models.TimeField(blank=True, null=True)),
                (
                    "precio",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="PrecioActividad"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("planificada", "Planificada"),
                            ("en_curso", "En curso"),
                            ("finalizada", "Finalizada"),
                        ],
                        default="planificada",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="centrodefamilia.actividad",
                        verbose_name="Actividad",
                    ),
                ),
                (
                    "centro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="centrodefamilia.centro",
                        verbose_name="Centro",
                    ),
                ),
                (
                    "dias",
                    models.ManyToManyField(
                        blank=True, related_name="DiaActividad", to="core.dia"
                    ),
                ),
                (
                    "sexoact",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sexoactividad",
                        to="core.sexo",
                        verbose_name="Actividad Dirigida a ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad del Centro",
                "verbose_name_plural": "Actividades por Centro",
            },
        ),
        migrations.AddField(
            model_name="actividad",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="centrodefamilia.categoria",
                verbose_name="Categoría",
            ),
        ),
        migrations.CreateModel(
            name="ParticipanteActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "actividad_centro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="centrodefamilia.actividadcentro",
                        verbose_name="Actividad del Centro",
                    ),
                ),
                (
                    "ciudadano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ciudadanos.ciudadano",
                        verbose_name="Ciudadano",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participante",
                "verbose_name_plural": "Participantes",
                "indexes": [
                    models.Index(
                        fields=["actividad_centro"],
                        name="centrodefam_activid_bb4135_idx",
                    )
                ],
                "unique_together": {("actividad_centro", "ciudadano")},
            },
        ),
        migrations.CreateModel(
            name="MovimientoCabal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monto registrado en el movimiento Cabal",
                        max_digits=12,
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        db_index=True,
                        help_text="Fecha del movimiento registrado en el Excel",
                    ),
                ),
                (
                    "fila_origen",
                    models.PositiveIntegerField(
                        db_index=True, help_text="Número de fila en el Excel de origen"
                    ),
                ),
                (
                    "centro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="centrodefamilia.centro",
                    ),
                ),
                (
                    "ciudadano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ciudadanos.ciudadano",
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="centrodefamilia.expediente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento Cabal",
                "verbose_name_plural": "Movimientos Cabal",
                "ordering": ["expediente", "fila_origen"],
                "indexes": [
                    models.Index(
                        fields=["expediente"], name="centrodefam_expedie_caf90e_idx"
                    ),
                    models.Index(
                        fields=["centro"], name="centrodefam_centro__2e1246_idx"
                    ),
                    models.Index(
                        fields=["ciudadano"], name="centrodefam_ciudada_3554ba_idx"
                    ),
                    models.Index(fields=["fecha"], name="centrodefam_fecha_578449_idx"),
                    models.Index(
                        fields=["fila_origen"], name="centrodefam_fila_or_d33861_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="expediente",
            index=models.Index(
                fields=["centro"], name="centrodefam_centro__a1e5a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expediente",
            index=models.Index(
                fields=["periodo"], name="centrodefam_periodo_202114_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expediente",
            index=models.Index(
                fields=["procesado"], name="centrodefam_procesa_54d5c5_idx"
            ),
        ),
    ]
