# Generated by Django 4.2.20 on 2025-07-10 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizaciones", "0001_initial"),
        ("configuraciones", "0003_rename_estado_estados_nombre"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ciudadanos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre de la Actividad"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la Categoría"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.CreateModel(
            name="Centro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("faro", "faro"), ("adherido", "Adherido")],
                        max_length=20,
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="centros/"),
                ),
                ("activo", models.BooleanField(default=True)),
                ("calle", models.CharField(blank=True, max_length=255, null=True)),
                ("numero", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "domicilio_actividad",
                    models.CharField(
                        max_length=255, verbose_name="Domicilio de actividades"
                    ),
                ),
                ("telefono", models.CharField(max_length=50, verbose_name="Teléfono")),
                ("celular", models.CharField(max_length=50, verbose_name="Celular")),
                (
                    "correo",
                    models.EmailField(
                        max_length=100, verbose_name="Correo electrónico"
                    ),
                ),
                (
                    "sitio_web",
                    models.URLField(blank=True, null=True, verbose_name="Sitio web"),
                ),
                (
                    "link_redes",
                    models.URLField(
                        blank=True, null=True, verbose_name="Redes sociales"
                    ),
                ),
                (
                    "nombre_referente",
                    models.CharField(
                        max_length=100, verbose_name="Nombre del responsable"
                    ),
                ),
                (
                    "apellido_referente",
                    models.CharField(
                        max_length=100, verbose_name="Apellido del responsable"
                    ),
                ),
                (
                    "telefono_referente",
                    models.CharField(
                        max_length=50, verbose_name="Teléfono del responsable"
                    ),
                ),
                (
                    "correo_referente",
                    models.EmailField(
                        max_length=100, verbose_name="Correo del responsable"
                    ),
                ),
                (
                    "faro_asociado",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"activo": True, "tipo": "faro"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="centrodefamilia.centro",
                    ),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="configuraciones.localidad",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="configuraciones.municipio",
                    ),
                ),
                (
                    "organizacion_asociada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizaciones.organizacion",
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="configuraciones.provincia",
                    ),
                ),
                (
                    "referente",
                    models.ForeignKey(
                        limit_choices_to={"groups__name": "ReferenteCentro"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="centros",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="informes_cabal/")),
                ("periodo", models.DateField(help_text="Fecha del informe")),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                ("procesado", models.BooleanField(default=False)),
                ("errores", models.TextField(blank=True)),
                (
                    "centro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expedientes_cabal",
                        to="centrodefamilia.centro",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActividadCentro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_personas",
                    models.PositiveIntegerField(
                        verbose_name="Cantidad Estimada de Participantes"
                    ),
                ),
                ("horariosdesde", models.TimeField()),
                ("horarioshasta", models.TimeField(blank=True, null=True)),
                (
                    "precio",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="PrecioActividad"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("planificada", "Planificada"),
                            ("en_curso", "En curso"),
                            ("finalizada", "Finalizada"),
                        ],
                        default="planificada",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="centrodefamilia.actividad",
                        verbose_name="Actividad",
                    ),
                ),
                (
                    "centro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="centrodefamilia.centro",
                        verbose_name="Centro",
                    ),
                ),
                (
                    "dias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="DiaActividad",
                        to="configuraciones.dia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad del Centro",
                "verbose_name_plural": "Actividades por Centro",
            },
        ),
        migrations.AddField(
            model_name="actividad",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="centrodefamilia.categoria",
                verbose_name="Categoría",
            ),
        ),
        migrations.CreateModel(
            name="ParticipanteActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "actividad_centro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="centrodefamilia.actividadcentro",
                        verbose_name="Actividad del Centro",
                    ),
                ),
                (
                    "ciudadano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ciudadanos.ciudadano",
                        verbose_name="Ciudadano",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participante",
                "verbose_name_plural": "Participantes",
                "unique_together": {("actividad_centro", "ciudadano")},
            },
        ),
    ]
