# Generated by Django 4.2.20 on 2025-06-12 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100, verbose_name="Nombre de la Actividad"
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad",
                "verbose_name_plural": "Actividades",
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Nombre de la Categoría",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de Actividad",
                "verbose_name_plural": "Categorías de Actividades",
            },
        ),
        migrations.CreateModel(
            name="Centro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nombre del Centro"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("faro", "Centro FARO"),
                            ("adherido", "Centro ADHERIDO"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de Centro",
                    ),
                ),
                ("direccion", models.TextField(verbose_name="Dirección")),
                (
                    "contacto",
                    models.CharField(
                        max_length=255, verbose_name="Teléfono o Responsable"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(default=True, verbose_name="¿Centro Activo?"),
                ),
                (
                    "faro_asociado",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"activo": True, "tipo": "faro"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adheridos",
                        to="centrodefamilia.centro",
                        verbose_name="Centro FARO Asociado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Centro de Familia",
                "verbose_name_plural": "Centros de Familia",
            },
        ),
        migrations.CreateModel(
            name="ActividadCentro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_personas",
                    models.PositiveIntegerField(
                        verbose_name="Cantidad Estimada de Participantes"
                    ),
                ),
                ("dias", models.CharField(max_length=100, verbose_name="Días")),
                ("horarios", models.CharField(max_length=100, verbose_name="Horarios")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("planificada", "Planificada"),
                            ("en_curso", "En curso"),
                            ("finalizada", "Finalizada"),
                        ],
                        default="planificada",
                        max_length=20,
                        verbose_name="EstadoCentro",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de Inicio")),
                ("fecha_fin", models.DateField(verbose_name="Fecha de Fin")),
                (
                    "actividad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="centrodefamilia.actividad",
                        verbose_name="Actividad",
                    ),
                ),
                (
                    "centro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="centrodefamilia.centro",
                        verbose_name="Centro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad del Centro",
                "verbose_name_plural": "Actividades por Centro",
            },
        ),
        migrations.AddField(
            model_name="actividad",
            name="categoria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="centrodefamilia.categoria",
                verbose_name="Categoría",
            ),
        ),
        migrations.CreateModel(
            name="ParticipanteActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="Apellido")),
                ("dni", models.CharField(max_length=15, verbose_name="DNI")),
                (
                    "genero",
                    models.CharField(
                        choices=[
                            ("masculino", "Masculino"),
                            ("femenino", "Femenino"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Género",
                    ),
                ),
                ("edad", models.PositiveIntegerField(verbose_name="Edad")),
                (
                    "cuit",
                    models.CharField(
                        max_length=20, verbose_name="CUIT del Participante"
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "actividad_centro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="centrodefamilia.actividadcentro",
                        verbose_name="Actividad del Centro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participante",
                "verbose_name_plural": "Participantes",
                "unique_together": {("actividad_centro", "cuit")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="actividad",
            unique_together={("nombre", "categoria")},
        ),
    ]
