# Generated by Django 4.2.20 on 2025-07-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("centrodefamilia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actividadcentro",
            name="dias",
            field=models.ManyToManyField(
                blank=True, related_name="DiaActividad", to="core.dia"
            ),
        ),
    ]
