# Generated by Django 4.2.20 on 2025-07-01 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuraciones", "0001_initial"),
        ("centrodefamilia", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="centro",
            name="domicilio_sede",
        ),
        migrations.AddField(
            model_name="centro",
            name="calle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="centro",
            name="localidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="configuraciones.localidad",
            ),
        ),
        migrations.AddField(
            model_name="centro",
            name="municipio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="configuraciones.municipio",
            ),
        ),
        migrations.AddField(
            model_name="centro",
            name="numero",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="centro",
            name="provincia",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="configuraciones.provincia",
            ),
        ),
    ]
