# Generated by Django 4.2.20 on 2025-06-12 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("centrodefamilia", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="actividad",
            options={},
        ),
        migrations.AlterModelOptions(
            name="categoria",
            options={"verbose_name": "Categoría", "verbose_name_plural": "Categorías"},
        ),
        migrations.AlterModelOptions(
            name="centro",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="actividad",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="actividad",
            name="nombre",
            field=models.CharField(
                max_length=200, verbose_name="Nombre de la Actividad"
            ),
        ),
        migrations.AlterField(
            model_name="actividadcentro",
            name="estado",
            field=models.CharField(
                choices=[
                    ("planificada", "Planificada"),
                    ("en_curso", "En curso"),
                    ("finalizada", "Finalizada"),
                ],
                default="planificada",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="categoria",
            name="nombre",
            field=models.CharField(
                max_length=100, verbose_name="Nombre de la Categoría"
            ),
        ),
        migrations.AlterField(
            model_name="centro",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="centro",
            name="contacto",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="centro",
            name="direccion",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="centro",
            name="faro_asociado",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"activo": True, "tipo": "faro"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="centrodefamilia.centro",
            ),
        ),
        migrations.AlterField(
            model_name="centro",
            name="nombre",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="centro",
            name="tipo",
            field=models.CharField(
                choices=[("faro", "FARO"), ("adherido", "Adherido")], max_length=20
            ),
        ),
    ]
