# Generated by Django 4.2.20 on 2025-07-31 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("centrodefamilia", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expediente",
            name="centro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="expedientes_cabal",
                to="centrodefamilia.centro",
            ),
        ),
    ]
