# centrodefamilia/migrations/0002_auto_unificar.py
# Generated by Django 4.2.20 on 2025-07-14 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centrodefamilia', '0001_initial'),
    ]

    operations = [
        # 1) Ajuste en ActividadCentro.dias (fusiona alteraciones de core.dia)
        migrations.AlterField(
            model_name='actividadcentro',
            name='dias',
            field=models.ManyToManyField(
                blank=True,
                related_name='DiaActividad',
                to='core.dia',
            ),
        ),

        # 2) Ajustes en Centro.localidad, municipio y provincia
        migrations.AlterField(
            model_name='centro',
            name='localidad',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='core.localidad',
            ),
        ),
        migrations.AlterField(
            model_name='centro',
            name='municipio',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='core.municipio',
            ),
        ),
        migrations.AlterField(
            model_name='centro',
            name='provincia',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='core.provincia',
            ),
        ),

        # 3) Añadir campo sexoact a ActividadCentro (fusiona las dos migraciones previas)
        migrations.AddField(
            model_name='actividadcentro',
            name='sexoact',
            field=models.ManyToManyField(
                blank=True,
                related_name='sexoactividad',
                to='core.sexo',
                verbose_name='Actividad Dirigida a ',
            ),
        ),

        # 4) Índice para acelerar consultas por actividad_centro
        migrations.AddIndex(
            model_name='participanteactividad',
            index=models.Index(
                fields=['actividad_centro'],
                name='centrodefam_activid_bb4135_idx',
            ),
        ),
    ]

