# Generated by Django 4.2.20 on 2025-07-04 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuraciones", "0002_estados"),
        ("centrodefamilia", "0002_remove_centro_domicilio_sede_centro_calle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participanteactividad",
            name="estado",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="configuraciones.estados",
                verbose_name="Actividad del participante",
            ),
            preserve_default=False,
        ),
    ]
