# Generated by Django 4.2.20 on 2025-08-04 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("centrodefamilia", "0002_expediente_remove_orientador_centro_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParticipanteActividadHistorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_anterior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("inscrito", "Inscrito"),
                            ("lista_espera", "Lista de Espera"),
                            ("dado_baja", "Dado de Baja"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Estado Anterior",
                    ),
                ),
                (
                    "estado_nuevo",
                    models.CharField(
                        choices=[
                            ("inscrito", "Inscrito"),
                            ("lista_espera", "Lista de Espera"),
                            ("dado_baja", "Dado de Baja"),
                        ],
                        max_length=20,
                        verbose_name="Estado Nuevo",
                    ),
                ),
                (
                    "fecha_cambio",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Cambio"
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Inscripción",
                "verbose_name_plural": "Historial de Inscripciones",
                "ordering": ["-fecha_cambio"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="participanteactividad",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="participanteactividad",
            name="estado",
            field=models.CharField(
                choices=[
                    ("inscrito", "Inscrito"),
                    ("lista_espera", "Lista de Espera"),
                    ("dado_baja", "Dado de Baja"),
                ],
                default="inscrito",
                max_length=20,
                verbose_name="Estado de Inscripción",
            ),
        ),
        migrations.AddField(
            model_name="participanteactividad",
            name="fecha_modificacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Fecha de Última Modificación"
            ),
        ),
        migrations.AlterField(
            model_name="centro",
            name="codigo",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name="participanteactividad",
            index=models.Index(fields=["estado"], name="centrodefam_estado_c4c1b9_idx"),
        ),
        migrations.AddConstraint(
            model_name="participanteactividad",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado__in", ["inscrito", "lista_espera"])),
                fields=("actividad_centro", "ciudadano"),
                name="unique_activo_inscripcion",
            ),
        ),
        migrations.AddField(
            model_name="participanteactividadhistorial",
            name="participante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial",
                to="centrodefamilia.participanteactividad",
            ),
        ),
        migrations.AddField(
            model_name="participanteactividadhistorial",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario que realizó el cambio",
            ),
        ),
    ]
