# Generated by Django 4.2.20 on 2025-06-12 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "centrodefamilia",
            "0002_alter_actividad_options_alter_categoria_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="actividadcentro",
            name="fecha_fin",
        ),
        migrations.RemoveField(
            model_name="actividadcentro",
            name="fecha_inicio",
        ),
    ]
