# Generated by Django 4.2.20 on 2025-06-12 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("centrodefamilia", "0003_remove_actividadcentro_fecha_fin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="centro",
            name="referente",
            field=models.ForeignKey(
                limit_choices_to={"groups__name": "ReferenteCentro"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="centros",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
