# Generated by Django 4.2.20 on 2025-07-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centrodefamilia", "0004_remove_participanteactividad_estado"),
    ]

    operations = [
        migrations.RenameField(
            model_name="actividadcentro",
            old_name="horarios",
            new_name="horariosdesde",
        ),
        migrations.AddField(
            model_name="actividadcentro",
            name="horarioshasta",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
