# Generated by Django 4.2.20 on 2025-08-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("centrodefamilia", "0004_alter_actividadcentro_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="horarioactividadcentro",
            name="sexoact",
        ),
        migrations.AddField(
            model_name="actividadcentro",
            name="sexoact",
            field=models.ManyToManyField(
                blank=True,
                related_name="sexo_horarios",
                to="core.sexo",
                verbose_name="Actividad dirigida a",
            ),
        ),
    ]
