# Generated by Django 4.2.20 on 2025-06-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centrodefamilia", "0004_centro_referente"),
    ]

    operations = [
        migrations.AddField(
            model_name="actividadcentro",
            name="precio",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="PrecioActividad"
            ),
        ),
    ]
