# Generated by Django 4.2.20 on 2025-08-08 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("centrodefamilia", "0005_alter_expediente_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CabalArchivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="informes_cabal/")),
                ("nombre_original", models.CharField(max_length=255)),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                ("advertencia_nombre_duplicado", models.BooleanField(default=False)),
                ("total_filas", models.PositiveIntegerField(default=0)),
                ("total_validas", models.PositiveIntegerField(default=0)),
                ("total_invalidas", models.PositiveIntegerField(default=0)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Archivo CABAL",
                "verbose_name_plural": "Archivos CABAL",
            },
        ),
        migrations.CreateModel(
            name="InformeCabalRegistro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nro_tarjeta", models.CharField(max_length=50)),
                ("nro_auto", models.CharField(max_length=50)),
                ("mti", models.CharField(max_length=20)),
                ("nro_comercio", models.CharField(max_length=50)),
                ("razon_social", models.CharField(blank=True, max_length=255)),
                (
                    "importe",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("fecha_trx", models.DateField(blank=True, null=True)),
                ("moneda_origen", models.CharField(blank=True, max_length=10)),
                (
                    "importe_mon_origen",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "importe_pesos",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("cant_cuotas", models.IntegerField(blank=True, null=True)),
                ("motivo_rechazo", models.CharField(blank=True, max_length=50)),
                ("desc_motivo_rechazo", models.CharField(blank=True, max_length=255)),
                ("disponibles", models.CharField(blank=True, max_length=50)),
                ("no_coincidente", models.BooleanField(default=False)),
                ("fila_numero", models.PositiveIntegerField(default=0)),
                (
                    "archivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros",
                        to="centrodefamilia.cabalarchivo",
                    ),
                ),
                (
                    "centro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="centrodefamilia.centro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro CABAL",
                "verbose_name_plural": "Registros CABAL",
                "indexes": [
                    models.Index(
                        fields=["archivo"], name="centrodefam_archivo_62343a_idx"
                    ),
                    models.Index(
                        fields=["centro"], name="centrodefam_centro__fdbcde_idx"
                    ),
                    models.Index(
                        fields=["nro_comercio"], name="centrodefam_nro_com_ef4edd_idx"
                    ),
                    models.Index(
                        fields=["fecha_trx"], name="centrodefam_fecha_t_21ee40_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="cabalarchivo",
            index=models.Index(
                fields=["fecha_subida"], name="centrodefam_fecha_s_77123a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cabalarchivo",
            index=models.Index(
                fields=["nombre_original"], name="centrodefam_nombre__187f10_idx"
            ),
        ),
    ]
