# Generated by Django 4.2.20 on 2025-07-06 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "centrodefamilia",
            "0005_rename_horarios_actividadcentro_horariosdesde_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Expediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="informes_cabal/%Y/%m/%d/")),
                ("periodo", models.DateField(help_text="Fecha del informe")),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                ("procesado", models.BooleanField(default=False)),
                ("errores", models.TextField(blank=True)),
                (
                    "centro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expedientes_cabal",
                        to="centrodefamilia.centro",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Orientador",
        ),
    ]
