# Generated by Django 4.2.20 on 2025-06-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centrodefamilia", "0005_actividadcentro_precio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="centro",
            name="tipo",
            field=models.CharField(
                choices=[("faro", "faro"), ("adherido", "Adherido")], max_length=20
            ),
        ),
    ]
