# Generated by Django 4.2.20 on 2025-07-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centrodefamilia", "0006_expediente_delete_orientador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expediente",
            name="archivo",
            field=models.FileField(upload_to="informes_cabal/"),
        ),
    ]
