# Generated by Django 4.2.20 on 2025-06-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centrodefamilia", "0006_alter_centro_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="centro",
            name="codigo",
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="centro",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="centros/"),
        ),
        migrations.AddField(
            model_name="centro",
            name="tipo_organizacion",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
