# Generated by Django 4.2.20 on 2025-09-03 05:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("centrodefamilia", "0007_delete_expediente"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeneficiariosResposablesRenaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iD_TRAMITE_PRINCIPAL",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "iD_TRAMITE_TARJETA_REIMPRESA",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("dni", models.CharField(blank=True, max_length=20, null=True)),
                ("genero", models.CharField(blank=True, max_length=20, null=True)),
                ("ejemplar", models.CharField(blank=True, max_length=5, null=True)),
                ("vencimiento", models.CharField(blank=True, max_length=20, null=True)),
                ("emision", models.CharField(blank=True, max_length=20, null=True)),
                ("apellido", models.CharField(blank=True, max_length=100, null=True)),
                ("nombres", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "fechaNacimiento",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("cuil", models.CharField(blank=True, max_length=20, null=True)),
                ("calle", models.CharField(blank=True, max_length=150, null=True)),
                ("numero", models.CharField(blank=True, max_length=20, null=True)),
                ("piso", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "departamento",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("cpostal", models.CharField(blank=True, max_length=20, null=True)),
                ("barrio", models.CharField(blank=True, max_length=100, null=True)),
                ("monoblock", models.CharField(blank=True, max_length=100, null=True)),
                ("ciudad", models.CharField(blank=True, max_length=100, null=True)),
                ("municipio", models.CharField(blank=True, max_length=100, null=True)),
                ("provincia", models.CharField(blank=True, max_length=100, null=True)),
                ("pais", models.CharField(blank=True, max_length=100, null=True)),
                ("codigoError", models.CharField(blank=True, max_length=20, null=True)),
                ("codigof", models.CharField(blank=True, max_length=20, null=True)),
                ("mensaf", models.CharField(blank=True, max_length=255, null=True)),
                ("origenf", models.CharField(blank=True, max_length=100, null=True)),
                ("fechaf", models.CharField(blank=True, max_length=20, null=True)),
                ("idciudadano", models.CharField(blank=True, max_length=50, null=True)),
                ("nroError", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "descripcionError",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tipo", models.CharField(blank=True, max_length=50, null=True)),
                ("fecha_creado", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PosiblesBeneficiarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cuil", models.CharField(max_length=20)),
                ("apellido", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=100)),
                ("genero", models.CharField(max_length=20)),
                ("fecha_nacimiento", models.DateField()),
                ("domicilio", models.CharField(max_length=255)),
                ("provincia", models.CharField(max_length=100)),
                ("municipio", models.CharField(max_length=100)),
                ("provincia_tabla", models.CharField(max_length=100)),
                ("municipio_tabla", models.CharField(max_length=100)),
                ("localidad_tabla", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Responsable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vinculo_parental",
                    models.CharField(
                        choices=[
                            ("Padre/Madre", "Padre/Madre"),
                            ("Abuelo/Abuela", "Abuelo/Abuela"),
                            ("Tío/Tía", "Tío/Tía"),
                            ("Hermano/Hermana", "Hermano/Hermana"),
                            ("Primo/Prima", "Primo/Prima"),
                            ("Padrino/Madrina", "Padrino/Madrina"),
                            ("Tutor/Tutora", "Tutor/Tutora"),
                        ],
                        max_length=50,
                    ),
                ),
                ("cuil", models.BigIntegerField(unique=True)),
                ("dni", models.PositiveIntegerField(unique=True)),
                ("apellido", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "genero",
                    models.CharField(
                        choices=[
                            ("F", "Femenino"),
                            ("M", "Masculino"),
                            ("X", "Otro/No binario"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_nacimiento", models.DateField()),
                ("codigo_postal", models.IntegerField(blank=True, null=True)),
                ("calle", models.CharField(max_length=150)),
                ("altura", models.IntegerField(blank=True, null=True)),
                (
                    "piso_vivienda",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "departamento_vivienda",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("barrio", models.CharField(blank=True, max_length=100, null=True)),
                ("monoblock", models.CharField(blank=True, max_length=100, null=True)),
                ("prefijo_celular", models.IntegerField(blank=True, null=True)),
                ("numero_celular", models.IntegerField(blank=True, null=True)),
                ("prefijo_telefono_fijo", models.IntegerField(blank=True, null=True)),
                ("numero_telefono_fijo", models.IntegerField(blank=True, null=True)),
                (
                    "correo_electronico",
                    models.EmailField(blank=True, max_length=150, null=True),
                ),
                (
                    "fecha_creado",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_modificado", models.DateTimeField(auto_now=True)),
                (
                    "localidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.localidad",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.municipio",
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.provincia",
                    ),
                ),
            ],
            options={
                "ordering": ["apellido", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ResponsableBeneficiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vinculo_parental",
                    models.CharField(
                        choices=[
                            ("Padre/Madre", "Padre/Madre"),
                            ("Abuelo/Abuela", "Abuelo/Abuela"),
                            ("Tío/Tía", "Tío/Tía"),
                            ("Hermano/Hermana", "Hermano/Hermana"),
                            ("Primo/Prima", "Primo/Prima"),
                            ("Padrino/Madrina", "Padrino/Madrina"),
                            ("Tutor/Tutora", "Tutor/Tutora"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "fecha_creado",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_modificado", models.DateTimeField(auto_now=True)),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beneficiarios_relacion",
                        to="centrodefamilia.responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relación Responsable-Beneficiario",
                "verbose_name_plural": "Relaciones Responsable-Beneficiario",
            },
        ),
        migrations.CreateModel(
            name="Beneficiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cuil", models.BigIntegerField(unique=True)),
                ("dni", models.PositiveIntegerField(unique=True)),
                ("apellido", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "genero",
                    models.CharField(
                        choices=[
                            ("F", "Femenino"),
                            ("M", "Masculino"),
                            ("X", "Otro/No binario"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_nacimiento", models.DateField()),
                (
                    "provincia_tabla",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "municipio_tabla",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "localidad_tabla",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("domicilio", models.CharField(max_length=255)),
                ("codigo_postal", models.IntegerField(blank=True, null=True)),
                ("calle", models.CharField(max_length=150)),
                ("altura", models.IntegerField(blank=True, null=True)),
                (
                    "piso_vivienda",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "departamento_vivienda",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("barrio", models.CharField(blank=True, max_length=100, null=True)),
                ("monoblock", models.CharField(blank=True, max_length=100, null=True)),
                ("prefijo_celular", models.IntegerField(blank=True, null=True)),
                ("numero_celular", models.IntegerField(blank=True, null=True)),
                ("prefijo_telefono_fijo", models.IntegerField(blank=True, null=True)),
                ("numero_telefono_fijo", models.IntegerField(blank=True, null=True)),
                (
                    "correo_electronico",
                    models.EmailField(blank=True, max_length=150, null=True),
                ),
                ("estado_academico", models.BooleanField(default=False)),
                (
                    "nivel_educativo_actual",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Jardín", "Jardín"),
                            ("Primario", "Primario"),
                            ("Secundario", "Secundario"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "maximo_nivel_educativo",
                    models.CharField(
                        choices=[
                            ("Sin instrucción", "Sin instrucción"),
                            ("Jardín incompleto", "Jardín incompleto"),
                            ("Jardín completo", "Jardín completo"),
                            ("Primario incompleto", "Primario incompleto"),
                            ("Primario completo", "Primario completo"),
                            ("Secundario incompleto", "Secundario incompleto"),
                            ("Secundario completo", "Secundario completo"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "institucion_academica",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("actividad_preferida", models.JSONField(blank=True, default=list)),
                ("actividades_extracurriculares", models.BooleanField(default=False)),
                (
                    "vinculo_parental",
                    models.CharField(
                        choices=[
                            ("Padre/Madre", "Padre/Madre"),
                            ("Abuelo/Abuela", "Abuelo/Abuela"),
                            ("Tío/Tía", "Tío/Tía"),
                            ("Hermano/Hermana", "Hermano/Hermana"),
                            ("Primo/Prima", "Primo/Prima"),
                            ("Padrino/Madrina", "Padrino/Madrina"),
                            ("Tutor/Tutora", "Tutor/Tutora"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "fecha_creado",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_modificado", models.DateTimeField(auto_now=True)),
                (
                    "actividades_detalle",
                    models.ManyToManyField(blank=True, to="centrodefamilia.actividad"),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.localidad",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.municipio",
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.provincia",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="beneficiarios",
                        to="centrodefamilia.responsable",
                    ),
                ),
            ],
            options={
                "ordering": ["apellido", "nombre"],
            },
        ),
    ]
