# Generated by Django 4.2.20 on 2025-06-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("centrodefamilia", "0008_centro_organizacionasociada"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="centro",
            name="tipo_organizacion",
        ),
    ]
