# Generated by Django 4.2.20 on 2025-09-03 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("centrodefamilia", "0008_beneficiariosresposablesrenaper_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="beneficiario",
            name="vinculo_parental",
        ),
        migrations.DeleteModel(
            name="ResponsableBeneficiario",
        ),
    ]
