# Generated by Django 4.2.20 on 2025-XX-XX

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "centrodefamilia",
            "0008_padronbeneficiarios_beneficiariosresponsablesrenaper_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="participanteactividad",
            unique_together={("actividad_centro", "ciudadano")},
        ),
    ]
