# Generated by Django 4.2.20 on 2025-09-03 05:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("centrodefamilia", "0009_remove_beneficiario_vinculo_parental_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeneficiarioResponsable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vinculo_parental",
                    models.CharField(
                        choices=[
                            ("Padre/Madre", "Padre/Madre"),
                            ("Abuelo/Abuela", "Abuelo/Abuela"),
                            ("Tío/Tía", "Tío/Tía"),
                            ("Hermano/Hermana", "Hermano/Hermana"),
                            ("Primo/Prima", "Primo/Prima"),
                            ("Padrino/Madrina", "Padrino/Madrina"),
                            ("Tutor/Tutora", "Tutor/Tutora"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "fecha_creado",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_modificado", models.DateTimeField(auto_now=True)),
                (
                    "beneficiario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="centrodefamilia.beneficiario",
                    ),
                ),
                (
                    "responsable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="centrodefamilia.responsable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vínculo Beneficiario-Responsable",
                "verbose_name_plural": "Vínculos Beneficiario-Responsable",
                "unique_together": {("beneficiario", "responsable")},
            },
        ),
    ]
