# Generated by Django 4.2.20 on 2025-06-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centrodefamilia", "0009_remove_centro_tipo_organizacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="centro",
            name="contacto",
        ),
        migrations.RemoveField(
            model_name="centro",
            name="direccion",
        ),
        migrations.AddField(
            model_name="centro",
            name="apellido_referente",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Apellido del responsable"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="centro",
            name="celular",
            field=models.CharField(default=1, max_length=50, verbose_name="Celular"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="centro",
            name="correo",
            field=models.EmailField(
                default=1, max_length=100, verbose_name="Correo electrónico"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="centro",
            name="correo_referente",
            field=models.EmailField(
                default=1, max_length=100, verbose_name="Correo del responsable"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="centro",
            name="domicilio_actividad",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Domicilio de actividades"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="centro",
            name="domicilio_sede",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Domicilio de la sede"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="centro",
            name="link_redes",
            field=models.URLField(blank=True, null=True, verbose_name="Redes sociales"),
        ),
        migrations.AddField(
            model_name="centro",
            name="nombre_referente",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Nombre del responsable"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="centro",
            name="sitio_web",
            field=models.URLField(blank=True, null=True, verbose_name="Sitio web"),
        ),
        migrations.AddField(
            model_name="centro",
            name="telefono",
            field=models.CharField(default=1, max_length=50, verbose_name="Teléfono"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="centro",
            name="telefono_referente",
            field=models.CharField(
                default=1, max_length=50, verbose_name="Teléfono del responsable"
            ),
            preserve_default=False,
        ),
    ]
