# Generated by Django 4.2.20 on 2025-06-23 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "centrodefamilia",
            "0010_remove_centro_contacto_remove_centro_direccion_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Orientadores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="Apellido")),
                ("dni", models.CharField(max_length=15, verbose_name="DNI")),
                (
                    "genero",
                    models.CharField(
                        choices=[
                            ("masculino", "Masculino"),
                            ("femenino", "Femenino"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Género",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="centros/orientador/"
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        choices=[
                            ("profesor", "profesor"),
                            ("administrativo", "administrativo"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                        verbose_name="Género",
                    ),
                ),
                (
                    "centro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="centrodefamilia.centro",
                        verbose_name="Centro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orientador",
                "verbose_name_plural": "Orientadores",
            },
        ),
    ]
