# Generated by Django 4.2.20 on 2025-06-27 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ciudadanos", "0001_initial"),
        ("centrodefamilia", "0011_orientadores"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="participanteactividad",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="participanteactividad",
            name="ciudadano",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ciudadanos.ciudadano",
                verbose_name="Ciudadano",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="participanteactividad",
            unique_together={("actividad_centro", "ciudadano")},
        ),
        migrations.RemoveField(
            model_name="participanteactividad",
            name="apellido",
        ),
        migrations.RemoveField(
            model_name="participanteactividad",
            name="cuit",
        ),
        migrations.RemoveField(
            model_name="participanteactividad",
            name="dni",
        ),
        migrations.RemoveField(
            model_name="participanteactividad",
            name="edad",
        ),
        migrations.RemoveField(
            model_name="participanteactividad",
            name="genero",
        ),
        migrations.RemoveField(
            model_name="participanteactividad",
            name="nombre",
        ),
    ]
