# Generated by Django 4.2.27 on 2026-07-03 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("centrodefamilia", "0014_accesocdf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="centro",
            name="referente",
            field=models.ForeignKey(
                limit_choices_to={
                    "groups__name__in": ["CDF - Referente centro", "ReferenteCentro"]
                },
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="centros",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
