# Generated by Django 4.2.27 on 2026-07-03 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("centrodefamilia", "0015_alter_centro_referente"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsistenciaActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                (
                    "presente",
                    models.BooleanField(default=False, verbose_name="Presente"),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Última Modificación"
                    ),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="centrodefamilia.participanteactividad",
                        verbose_name="Participante",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asistencias_cdf_registradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistencia a Actividad",
                "verbose_name_plural": "Asistencias a Actividades",
                "indexes": [
                    models.Index(
                        fields=["fecha", "presente"], name="cdf_asist_fecha_pres_idx"
                    )
                ],
                "unique_together": {("participante", "fecha")},
            },
        ),
    ]
