from django.contrib import admin
from provincias.models import (
    Rubro,
    Objetivo,
    TipoActividad,
    TipoComunidad,
    CantidadIntegrantes,
    Genero,
    TipoInmueble,
    TipoInternet,
    TipoDispositivosMoviles,
    PlataformaComunicacion,
    RedSocial,
    Comprador,
    EstudiosAlcanzados,
    TipoOcupacion,
    CondicionOcupacion,
    OcupacionHorasSemanales,
    IngresoPromedioFamiliar,
    CantidadClientes,
    LugarComercializacion,
    ModalidadComercializacion,
    FijacionPrecios,
    CantidadCompetidores,
    ConocimientoCompetidores,
    InteractuaCompetidores,
    ModalidadCompras,
    PlazoCompraCredito,
    MedioPlanificacion,
    CanalesVentas,
    DestinoMaterialesRecuperados,
    ModalidadCicloProductivo,
    Proyecto,
    AnexoSocioProductivo,
    PersoneriaOrganizacion,
    PersoneriaPersona,
    LineaDeAccion,
    Presupuesto,
    DestinatarioDirecto,
    DiagnosticoOrganizacion,
    DiagnosticoPersona,
    Observacion,
    AnexoFormacion,
)

# Registrar todos los modelos en el admin de Django
admin.site.register(Rubro)
admin.site.register(Objetivo)
admin.site.register(TipoActividad)
admin.site.register(TipoComunidad)
admin.site.register(CantidadIntegrantes)
admin.site.register(Genero)
admin.site.register(TipoInmueble)
admin.site.register(TipoInternet)
admin.site.register(TipoDispositivosMoviles)
admin.site.register(PlataformaComunicacion)
admin.site.register(RedSocial)
admin.site.register(Comprador)
admin.site.register(EstudiosAlcanzados)
admin.site.register(TipoOcupacion)
admin.site.register(CondicionOcupacion)
admin.site.register(OcupacionHorasSemanales)
admin.site.register(IngresoPromedioFamiliar)
admin.site.register(CantidadClientes)
admin.site.register(LugarComercializacion)
admin.site.register(ModalidadComercializacion)
admin.site.register(FijacionPrecios)
admin.site.register(CantidadCompetidores)
admin.site.register(ConocimientoCompetidores)
admin.site.register(InteractuaCompetidores)
admin.site.register(ModalidadCompras)
admin.site.register(PlazoCompraCredito)
admin.site.register(MedioPlanificacion)
admin.site.register(CanalesVentas)
admin.site.register(DestinoMaterialesRecuperados)
admin.site.register(ModalidadCicloProductivo)
admin.site.register(Proyecto)
admin.site.register(AnexoSocioProductivo)
admin.site.register(PersoneriaOrganizacion)
admin.site.register(PersoneriaPersona)
admin.site.register(LineaDeAccion)
admin.site.register(Presupuesto)
admin.site.register(DestinatarioDirecto)
admin.site.register(DiagnosticoOrganizacion)
admin.site.register(DiagnosticoPersona)
admin.site.register(Observacion)
admin.site.register(AnexoFormacion)
