# Generated by Django 4.2.20 on 2025-06-15 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comedores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpedientePago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expediente_pago",
                    models.CharField(max_length=255, verbose_name="Expediente de Pago"),
                ),
                (
                    "resolucion_pago",
                    models.CharField(max_length=255, verbose_name="Resolución de Pago"),
                ),
                ("anexo", models.CharField(max_length=255, verbose_name="Anexo")),
                (
                    "if_cantidad_de_prestaciones",
                    models.IntegerField(verbose_name="IF Cantidad de Prestaciones"),
                ),
                (
                    "if_pagado",
                    models.BooleanField(default=False, verbose_name="IF Pagado"),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto"
                    ),
                ),
                (
                    "numero_orden_pago",
                    models.CharField(
                        max_length=255, verbose_name="Número de Orden de Pago"
                    ),
                ),
                (
                    "fecha_pago_al_banco",
                    models.DateField(verbose_name="Fecha de pago al banco"),
                ),
                (
                    "fecha_acreditacion",
                    models.DateField(verbose_name="Fecha de acreditación"),
                ),
                ("observaciones", models.TextField(verbose_name="Observaciones")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "comedor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expedientes_pagos",
                        to="comedores.comedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expediente de Pago",
                "verbose_name_plural": "Expedientes de Pago",
            },
        ),
    ]
