# Generated by Django 4.2.27 on 2026-05-22 12:48

from decimal import Decimal

import core.soft_delete.base
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F, Value
from django.db.models.functions import Cast, Coalesce, ExtractYear


def backfill_expedientepago_fields(apps, schema_editor):
    ExpedientePago = apps.get_model("expedientespagos", "ExpedientePago")

    # Copiar monto -> total cuando total esté vacío
    ExpedientePago.objects.filter(total__isnull=True, monto__isnull=False).update(
        total=F("monto")
    )

    # Completar campos mensuales requeridos con 0
    int_fields = [
        "prestaciones_mensuales_desayuno",
        "prestaciones_mensuales_almuerzo",
        "prestaciones_mensuales_merienda",
        "prestaciones_mensuales_cena",
    ]
    for field in int_fields:
        ExpedientePago.objects.filter(**{f"{field}__isnull": True}).update(**{field: 0})

    dec_fields = [
        "monto_mensual_desayuno",
        "monto_mensual_almuerzo",
        "monto_mensual_merienda",
        "monto_mensual_cena",
    ]
    for field in dec_fields:
        ExpedientePago.objects.filter(**{f"{field}__isnull": True}).update(
            **{field: Decimal("0")}
        )

    # Evitar nulos en expediente_convenio (fallback a expediente_pago)
    ExpedientePago.objects.filter(expediente_convenio__isnull=True).update(
        expediente_convenio=Coalesce("expediente_pago", Value(""))
    )
    ExpedientePago.objects.filter(expediente_convenio="").update(
        expediente_convenio=Coalesce("expediente_pago", Value(""))
    )

    # Completar año desde fechas disponibles (sin fallback global)
    date_expr = Coalesce(
        "fecha_pago_al_banco",
        "fecha_acreditacion",
        Cast("fecha_creacion", models.DateField()),
    )
    ExpedientePago.objects.filter(ano__isnull=True).update(
        ano=Cast(ExtractYear(date_expr), models.CharField())
    )


class Migration(migrations.Migration):

    replaces = [
        ("expedientespagos", "0001_initial"),
        ("expedientespagos", "0002_alter_expedientepago_expediente_pago_and_more"),
        ("expedientespagos", "0003_remove_expedientepago_resolucion_pago_and_more"),
        ("expedientespagos", "0004_remove_expedientepago_monto_and_more"),
        ("expedientespagos", "0005_alter_expedientepago_managers_and_more"),
        ("expedientespagos", "0006_expedientepago_mes_convenio"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comedores", "0001_squashed_0023"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpedientePago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expediente_pago",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Expediente de Pago",
                    ),
                ),
                (
                    "expediente_convenio",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Expediente del Convenio",
                    ),
                ),
                (
                    "anexo",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Anexo"
                    ),
                ),
                (
                    "if_cantidad_de_prestaciones",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="IF Cantidad de Prestaciones",
                    ),
                ),
                (
                    "if_pagado",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="IF Pagado"
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Monto",
                    ),
                ),
                (
                    "numero_orden_pago",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Número de Orden de Pago",
                    ),
                ),
                (
                    "fecha_pago_al_banco",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de pago al banco"
                    ),
                ),
                (
                    "fecha_acreditacion",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de acreditación"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "comedor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expedientes_pagos",
                        to="comedores.comedor",
                    ),
                ),
                (
                    "monto_mensual_almuerzo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Monto mensual almuerzo",
                    ),
                ),
                (
                    "monto_mensual_cena",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Monto mensual cena",
                    ),
                ),
                (
                    "monto_mensual_desayuno",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Monto mensual desayuno",
                    ),
                ),
                (
                    "monto_mensual_merienda",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Monto mensual merienda",
                    ),
                ),
                (
                    "prestaciones_mensuales_almuerzo",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Prestaciones mensuales almuerzo",
                    ),
                ),
                (
                    "prestaciones_mensuales_cena",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Prestaciones mensuales cena",
                    ),
                ),
                (
                    "prestaciones_mensuales_desayuno",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Prestaciones mensuales desayuno",
                    ),
                ),
                (
                    "prestaciones_mensuales_merienda",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Prestaciones mensuales merienda",
                    ),
                ),
                (
                    "ano",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="Año"
                    ),
                ),
                (
                    "mes_pago",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Mes de Pago"
                    ),
                ),
                (
                    "organizacion_creacion",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Organización de creación",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Total",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expediente de Pago",
                "verbose_name_plural": "Expedientes de Pago",
            },
        ),
        migrations.RunPython(
            code=backfill_expedientepago_fields,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="expediente_convenio",
            field=models.CharField(
                max_length=255, verbose_name="Expediente del Convenio"
            ),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="prestaciones_mensuales_almuerzo",
            field=models.IntegerField(verbose_name="Prestaciones mensuales almuerzo"),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="prestaciones_mensuales_cena",
            field=models.IntegerField(verbose_name="Prestaciones mensuales cena"),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="prestaciones_mensuales_desayuno",
            field=models.IntegerField(verbose_name="Prestaciones mensuales desayuno"),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="prestaciones_mensuales_merienda",
            field=models.IntegerField(verbose_name="Prestaciones mensuales merienda"),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="monto_mensual_almuerzo",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Monto mensual almuerzo"
            ),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="monto_mensual_cena",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Monto mensual cena"
            ),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="monto_mensual_desayuno",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Monto mensual desayuno"
            ),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="monto_mensual_merienda",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Monto mensual merienda"
            ),
        ),
        migrations.RemoveField(
            model_name="expedientepago",
            name="monto",
        ),
        migrations.AlterModelManagers(
            name="expedientepago",
            managers=[
                ("objects", core.soft_delete.base.SoftDeleteManager()),
                (
                    "all_objects",
                    core.soft_delete.base.SoftDeleteManager(include_deleted=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="expedientepago",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="expedientepago",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expedientepago",
            name="mes_convenio",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
                verbose_name="Mes de Convenio",
            ),
        ),
    ]
