# Generated by Codex on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedientespagos", "0001_squashed_0006_expedientepago_mes_convenio"),
    ]

    operations = [
        migrations.AddField(
            model_name="expedientepago",
            name="total_prestaciones",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total Prestaciones",
            ),
        ),
        migrations.AddField(
            model_name="expedientepago",
            name="gastos_accesorios",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Gastos Accesorios 6%",
            ),
        ),
    ]
