# Generated by Django 4.2.20 on 2025-06-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedientespagos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expedientepago",
            name="expediente_pago",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Expediente de Pago"
            ),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="fecha_acreditacion",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de acreditación"
            ),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="fecha_pago_al_banco",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de pago al banco"
            ),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="if_cantidad_de_prestaciones",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="IF Cantidad de Prestaciones",
            ),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="if_pagado",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="IF Pagado"
            ),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="monto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Monto",
            ),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="numero_orden_pago",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Número de Orden de Pago",
            ),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="observaciones",
            field=models.TextField(blank=True, null=True, verbose_name="Observaciones"),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="resolucion_pago",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Resolución de Pago"
            ),
        ),
    ]
