# Generated by Django 4.2.16 on 2025-05-26 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("expedientespagos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expedientepago",
            name="acompanamiento",
        ),
    ]
