# Generated by Django 4.2.20 on 2026-01-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedientespagos", "0002_alter_expedientepago_expediente_pago_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expedientepago",
            old_name="resolucion_pago",
            new_name="expediente_convenio",
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="expediente_convenio",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Expediente del Convenio",
            ),
        ),
        migrations.AddField(
            model_name="expedientepago",
            name="monto_mensual_almuerzo",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Monto mensual almuerzo",
            ),
        ),
        migrations.AddField(
            model_name="expedientepago",
            name="monto_mensual_cena",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Monto mensual cena",
            ),
        ),
        migrations.AddField(
            model_name="expedientepago",
            name="monto_mensual_desayuno",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Monto mensual desayuno",
            ),
        ),
        migrations.AddField(
            model_name="expedientepago",
            name="monto_mensual_merienda",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Monto mensual merienda",
            ),
        ),
        migrations.AddField(
            model_name="expedientepago",
            name="prestaciones_mensuales_almuerzo",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Prestaciones mensuales almuerzo"
            ),
        ),
        migrations.AddField(
            model_name="expedientepago",
            name="prestaciones_mensuales_cena",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Prestaciones mensuales cena"
            ),
        ),
        migrations.AddField(
            model_name="expedientepago",
            name="prestaciones_mensuales_desayuno",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Prestaciones mensuales desayuno"
            ),
        ),
        migrations.AddField(
            model_name="expedientepago",
            name="prestaciones_mensuales_merienda",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Prestaciones mensuales merienda"
            ),
        ),
    ]
