# Generated by Django 5.2.16 on 2026-08-21 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0078_issue_2234_campo_informe_complementario"),
        ("expedientespagos", "0002_expedientepago_total_prestaciones_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expedientepago",
            name="admision",
            field=models.ForeignKey(
                blank=True,
                help_text="Si se deja vacío, se intenta resolver automáticamente a partir del expediente del convenio.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expedientes_pagos",
                to="admisiones.admision",
                verbose_name="Admisión",
            ),
        ),
    ]
