# Generated by Django 4.2.20 on 2025-12-30 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0019_merge_20251125_1049"),
        ("expedientespagos", "0002_alter_expedientepago_expediente_pago_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expedientepago",
            name="comedor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="expedientes_pagos",
                to="comedores.comedor",
            ),
        ),
    ]
