# Generated by Django 4.2.27 on 2026-02-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedientespagos", "0003_expedientepago_ano_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expedientepago",
            name="monto",
        ),
        migrations.RemoveField(
            model_name="expedientepago",
            name="resolucion_pago",
        ),
        migrations.AddField(
            model_name="expedientepago",
            name="monto_mensual_almuerzo",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=10,
                verbose_name="Monto mensual almuerzo",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expedientepago",
            name="monto_mensual_cena",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=10,
                verbose_name="Monto mensual cena",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expedientepago",
            name="monto_mensual_desayuno",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=10,
                verbose_name="Monto mensual desayuno",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expedientepago",
            name="monto_mensual_merienda",
            field=models.DecimalField(
                decimal_places=2,
                default=1,
                max_digits=10,
                verbose_name="Monto mensual merienda",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expedientepago",
            name="prestaciones_mensuales_almuerzo",
            field=models.IntegerField(
                default=1, verbose_name="Prestaciones mensuales almuerzo"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expedientepago",
            name="prestaciones_mensuales_cena",
            field=models.IntegerField(
                default=1, verbose_name="Prestaciones mensuales cena"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expedientepago",
            name="prestaciones_mensuales_desayuno",
            field=models.IntegerField(
                default=1, verbose_name="Prestaciones mensuales desayuno"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expedientepago",
            name="prestaciones_mensuales_merienda",
            field=models.IntegerField(
                default=1, verbose_name="Prestaciones mensuales merienda"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="ano",
            field=models.CharField(default=1, max_length=4, verbose_name="Año"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="expediente_convenio",
            field=models.CharField(
                max_length=255, verbose_name="Expediente del Convenio"
            ),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="expediente_pago",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Expediente de Pago"
            ),
        ),
    ]
