# Generated by Django 4.2.16 on 2025-06-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedientespagos", "0003_alter_expedientepago_comedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expedientepago",
            name="if_cantidad_de_prestaciones",
            field=models.CharField(
                max_length=255, verbose_name="IF Cantidad de Prestaciones"
            ),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="if_pagado",
            field=models.CharField(max_length=255, verbose_name="IF Pagado"),
        ),
    ]
