# Generated by Django 4.2.27 on 2026-02-09 00:00

from decimal import Decimal

from django.db import migrations, models
from django.db.models import F, Value
from django.db.models.functions import Cast, Coalesce, ExtractYear
from django.utils import timezone


def backfill_expedientepago_fields(apps, schema_editor):
    ExpedientePago = apps.get_model("expedientespagos", "ExpedientePago")

    # Copiar monto -> total cuando total esté vacío
    ExpedientePago.objects.filter(total__isnull=True, monto__isnull=False).update(
        total=F("monto")
    )

    # Completar campos mensuales requeridos con 0
    int_fields = [
        "prestaciones_mensuales_desayuno",
        "prestaciones_mensuales_almuerzo",
        "prestaciones_mensuales_merienda",
        "prestaciones_mensuales_cena",
    ]
    for field in int_fields:
        ExpedientePago.objects.filter(**{f"{field}__isnull": True}).update(
            **{field: 0}
        )

    dec_fields = [
        "monto_mensual_desayuno",
        "monto_mensual_almuerzo",
        "monto_mensual_merienda",
        "monto_mensual_cena",
    ]
    for field in dec_fields:
        ExpedientePago.objects.filter(**{f"{field}__isnull": True}).update(
            **{field: Decimal("0")}
        )

    # Evitar nulos en expediente_convenio (fallback a expediente_pago)
    ExpedientePago.objects.filter(expediente_convenio__isnull=True).update(
        expediente_convenio=Coalesce("expediente_pago", Value(""))
    )
    ExpedientePago.objects.filter(expediente_convenio="").update(
        expediente_convenio=Coalesce("expediente_pago", Value(""))
    )

    # Completar año desde fechas disponibles; si no hay fechas, usar año actual
    date_expr = Coalesce(
        "fecha_pago_al_banco",
        "fecha_acreditacion",
        Cast("fecha_creacion", models.DateField()),
    )
    ExpedientePago.objects.filter(ano__isnull=True).update(
        ano=Cast(ExtractYear(date_expr), models.CharField())
    )
    current_year = str(timezone.now().year)
    ExpedientePago.objects.filter(ano__isnull=True).update(ano=current_year)
    ExpedientePago.objects.filter(ano="").update(ano=current_year)


class Migration(migrations.Migration):

    dependencies = [
        ("expedientespagos", "0003_remove_expedientepago_resolucion_pago_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expedientepago",
            name="ano",
            field=models.CharField(
                blank=True, max_length=4, null=True, verbose_name="Año"
            ),
        ),
        migrations.AddField(
            model_name="expedientepago",
            name="mes_pago",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Mes de Pago"
            ),
        ),
        migrations.AddField(
            model_name="expedientepago",
            name="organizacion_creacion",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Organización de creación",
            ),
        ),
        migrations.AddField(
            model_name="expedientepago",
            name="total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Total",
            ),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="anexo",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Anexo"
            ),
        ),
        migrations.RunPython(
            backfill_expedientepago_fields, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="expediente_convenio",
            field=models.CharField(max_length=255, verbose_name="Expediente del Convenio"),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="ano",
            field=models.CharField(max_length=4, verbose_name="Año"),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="prestaciones_mensuales_almuerzo",
            field=models.IntegerField(verbose_name="Prestaciones mensuales almuerzo"),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="prestaciones_mensuales_cena",
            field=models.IntegerField(verbose_name="Prestaciones mensuales cena"),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="prestaciones_mensuales_desayuno",
            field=models.IntegerField(verbose_name="Prestaciones mensuales desayuno"),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="prestaciones_mensuales_merienda",
            field=models.IntegerField(verbose_name="Prestaciones mensuales merienda"),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="monto_mensual_almuerzo",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Monto mensual almuerzo"
            ),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="monto_mensual_cena",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Monto mensual cena"
            ),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="monto_mensual_desayuno",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Monto mensual desayuno"
            ),
        ),
        migrations.AlterField(
            model_name="expedientepago",
            name="monto_mensual_merienda",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Monto mensual merienda"
            ),
        ),
        migrations.RemoveField(
            model_name="expedientepago",
            name="monto",
        ),
    ]
