# Generated by Django 4.2.16 on 2025-06-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expedientespagos", "0005_alter_expedientepago_fecha_acreditacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expedientepago",
            name="numero_orden_pago",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Número de Orden de Pago",
            ),
        ),
    ]
