from django.urls import path

from comedores.views.web_views import (
    ComedorCreateView,
    ComedorDeleteView,
    ComedorDetailView,
    ComedorListView,
    ComedorUpdateView,
    ObservacionCreateView,
    ObservacionDeleteView,
    ObservacionDetailView,
    ObservacionUpdateView,
    RelevamientoListView,
    RelevamientoCreateView,
    RelevamientoDeleteView,
    RelevamientoDetailView,
    RelevamientoUpdateView,
    IntervencionDetail,
    IntervencionCreateView,
    IntervencionUpdateView,
    IntervencionDeleteView,
    NominaDetail,
    NominaCreateView,
    NominaDeleteView,
    NominaUpdateView,
    AsignarDuplaListView,
    sub_estados_intervenciones_ajax,
)
from configuraciones.decorators import group_required
from admisiones.views.web_views import (
    subir_archivo_admision,
    eliminar_archivo_admision,
    AdmisionesTecnicosListView,
    AdmisionesTecnicosCreateView,
    AdmisionesTecnicosUpdateView,
)

urlpatterns = [
    path(
        "comedores/listar",
        group_required("Comedores")(ComedorListView.as_view()),
        name="comedores",
    ),
    path(
        "comedores/crear",
        group_required("Comedores")(ComedorCreateView.as_view()),
        name="comedor_crear",
    ),
    path(
        "comedores/<pk>",
        group_required("Comedores")(ComedorDetailView.as_view()),
        name="comedor_detalle",
    ),
    path(
        "comedores/<pk>/editar",
        group_required("Comedores")(ComedorUpdateView.as_view()),
        name="comedor_editar",
    ),
    path(
        "comedores/<pk>/eliminar",
        group_required("Comedores")(ComedorDeleteView.as_view()),
        name="comedor_eliminar",
    ),
    path(
        "comedores/<comedor_pk>/relevamiento/listar",
        group_required("Comedores")(RelevamientoListView.as_view()),
        name="relevamientos",
    ),
    path(
        "comedores/<comedor_pk>/relevamiento/crear",
        group_required("Comedores")(RelevamientoCreateView.as_view()),
        name="relevamiento_crear",
    ),
    path(
        "comedores/<comedor_pk>/relevamiento/<pk>",
        group_required("Comedores")(RelevamientoDetailView.as_view()),
        name="relevamiento_detalle",
    ),
    path(
        "comedores/<comedor_pk>/relevamiento/<pk>/editar",
        group_required("Comedores")(RelevamientoUpdateView.as_view()),
        name="relevamiento_editar",
    ),
    path(
        "comedores/<comedor_pk>/relevamiento/<pk>/eliminar",
        group_required("Comedores")(RelevamientoDeleteView.as_view()),
        name="relevamiento_eliminar",
    ),
    path(
        "comedores/<comedor_pk>/observacion/crear",
        group_required("Comedores")(ObservacionCreateView.as_view()),
        name="observacion_crear",
    ),
    path(
        "comedores/<comedor_pk>/observacion/<pk>",
        group_required("Comedores")(ObservacionDetailView.as_view()),
        name="observacion_detalle",
    ),
    path(
        "comedores/<comedor_pk>/observacion/<pk>/editar",
        group_required("Comedores")(ObservacionUpdateView.as_view()),
        name="observacion_editar",
    ),
    path(
        "comedores/<comedor_pk>/observacion/<pk>/eliminar",
        group_required("Comedores")(ObservacionDeleteView.as_view()),
        name="observacion_eliminar",
    ),
    path(
        "comedores/intervencion/ver/<pk>",
        group_required("Comedores")(IntervencionDetail.as_view()),
        name="comedor_intervencion_ver",
    ),
    path(
        "comedores/nomina/ver/<pk>",
        group_required("Comedores")(NominaDetail.as_view()),
        name="nomina_ver",
    ),
    path(
        "comedores/nomina/crear/<pk>",
        group_required("Comedores")(NominaCreateView.as_view()),
        name="nomina_crear",
    ),
    path(
        "comedores/intervencion/crear/<pk>",
        group_required("Comedores")(IntervencionCreateView.as_view()),
        name="intervencion_crear",
    ),
    path(
        "comedores/intervencion/editar/<pk>/<pk2>",
        group_required("Comedores")(IntervencionUpdateView.as_view()),
        name="intervencion_editar",
    ),
    path(
        "comedores/nomina/editar/<pk>/<pk2>",
        group_required("Comedores")(NominaUpdateView.as_view()),
        name="nomina_editar",
    ),
    path(
        "comedores/intervencion/borrar/<pk>/<pk2>",
        group_required("Comedores")(IntervencionDeleteView.as_view()),
        name="intervencion_borrar",
    ),
    path(
        "comedores/nomina/borrar/<pk>/<pk2>",
        group_required("Comedores")(NominaDeleteView.as_view()),
        name="nomina_borrar",
    ),
    path(
        "comedores/admisiones/tecnicos/listar",
        group_required("Comedores")(AdmisionesTecnicosListView.as_view()),
        name="admisiones_tecnicos_listar",
    ),
    path(
        "comedores/admisiones/tecnicos/crear/<pk>",
        group_required("Comedores")(AdmisionesTecnicosCreateView.as_view()),
        name="admisiones_tecnicos_crear",
    ),
    path(
        "comedores/admisiones/tecnicos/editar/<pk>",
        group_required("Comedores")(AdmisionesTecnicosUpdateView.as_view()),
        name="admisiones_tecnicos_editar",
    ),
    path(
        "admision/<int:admision_id>/documentacion/<int:documentacion_id>/subir/",
        subir_archivo_admision,
        name="subir_archivo_admision",
    ),
    path(
        "admision/<int:admision_id>/documentacion/<int:documentacion_id>/eliminar/",
        eliminar_archivo_admision,
        name="eliminar_archivo_admision",
    ),
    path(
        "comedores/dupla/asignar/<pk>",
        group_required("Comedores")(AsignarDuplaListView.as_view()),
        name="dupla_asignar",
    ),
    path(
        "comedores/ajax/load-subestadosintervenciones/",
        sub_estados_intervenciones_ajax,
        name="ajax_load_subestadosintervenciones",
    ),
]
