from django.core.management.base import BaseCommand
from django.contrib.auth.models import Group


class Command(BaseCommand):
    help = "Crea los grupos de usuario predeterminados"

    def handle(self, *args, **kwargs):
        groups = [
            "Admin",
            "Comedores",
            "Exportar a csv",
            "Organizaciones",
            "Gestor prestaciones",
            "CDI",
            "Ciudadanos",
            "Tecnico Comedor",
            "Abogado Dupla",
            "Area Contable",
            "Area Legales",
            "Coordinador general",
            "Comedores Listar",
            "Comedores Crear",
            "Comedores Ver",
            "Comedores Editar",
            "Comedores Eliminar",
            "Comedores Relevamiento Ver",
            "Comedores Relevamiento Crear",
            "Comedores Relevamiento Detalle",
            "Comedores Relevamiento Editar",
            "Comedores Observaciones Crear",
            "Comedores Observaciones Detalle",
            "Comedores Observaciones Editar",
            "Comedores Observaciones Eliminar",
            "Comedores Intervencion Ver",
            "Comedores Intervencion Crear",
            "Comedores Intervencion Editar",
            "Comedores Intervenciones Detalle",
            "Comedores Nomina Ver",
            "Comedores Nomina Crear",
            "Comedores Nomina Editar",
            "Comedores Nomina Borrar",
            "Comedores Dupla Asignar",
            "Acompanamiento Detalle",
            "Acompanamiento Listar",
            "Usuario Crear",
            "Usuario Eliminar",
            "Usuario Editar",
            "Usuario Listar",
            "Grupos Ver",
            "Admin Ver Expedientes",
            "Técnico Ver Tareas Asignadas",
            "Provincia Ver Estado Pago",
            "Provincia Crear Expediente",
            "Provincia Ver Lista Aprobados",
            "Provincia Cargar Formulario",
            "Provincia Finalizar Expediente",
            "Admin Asignar Técnico",
            "Técnico Subir Cruces",
            "Técnico Validar Resultado Cruce",
            "Técnico Registrar Informe Pago",
            "ReferenteCentro",
            "CDF SSE",
            "Dashboard Comedor",
            "Dashboard Centrodefamilia",
            "Tablero DataCalle Chaco",
            "Tablero DataCalle Misiones",
            "Tablero DataCalle Salta",
            "Tablero DataCalle Corrientes",
            "Tablero DataCalle General",
            "Tablero DataCalle Chubut",
            "Tablero DataCalle San Lus",
            "Tablero DataCalle Entre Ríos",
            "Tablero DataCalle Mendoza",
            "Tablero DataCalle San Juan",
            "Tablero DataCalle Santa Cruz",
            "Tablero DataCalle Santa Fe",
            "Tablero DataCalle La Pampa",
            "Tablero DataCalle Catamarca",
            "Tablero DataCalle Rio Negro",
            "Tablero DataCalle Cordoba - Capital",
            "Tablero DataCalle Cordoba - San Francisco",
            "Tablero DataCalle Cordoba - Alta Gracia",
            "Tablero DataCalle Tucuman",
            "TecnicoCeliaquia",
            "CoordinadorCeliaquia",
            "ProvinciaCeliaquia",
            "ApiCentroFamilia",
        ]
        self.stdout.write(self.style.SUCCESS(f"Creando grupos de usuario..."))
        for group_name in groups:
            _group, created = Group.objects.get_or_create(name=group_name)
            if created:
                self.stdout.write(self.style.SUCCESS(f'Grupo "{group_name}" creado'))
