from django.urls import path
from core.decorators import permission_code_required, permissions_any_required
from .views import (
    ImportExpedientesView,
    ImportarExpedienteListView,
    ImportarExpedienteDetalleListView,
    ImportarFechasAcreditacionView,
    importarexpedientes_ajax,
    importarexpediente_detail_ajax,
    ImportDatosView,
    BorrarDatosImportadosView,
    descargar_archivo_importado,
)

urlpatterns = [
    path("importarexpedientes/upload", ImportExpedientesView.as_view(), name="upload"),
    path(
        "importarexpedientes/listar",
        permission_code_required("importarexpediente.view_archivosimportados")(
            ImportarExpedienteListView.as_view()
        ),
        name="importarexpedientes_list",
    ),
    path(
        "importarexpedientes/ajax/",
        permission_code_required("importarexpediente.view_archivosimportados")(
            importarexpedientes_ajax
        ),
        name="importarexpedientes_ajax",
    ),
    path(
        "importarexpedientes/<int:id_archivo>/",
        permission_code_required("importarexpediente.view_archivosimportados")(
            ImportarExpedienteDetalleListView.as_view()
        ),
        name="importarexpediente_detail",
    ),
    path(
        "importarexpedientes/<int:id_archivo>/descargar/",
        permission_code_required("importarexpediente.view_archivosimportados")(
            descargar_archivo_importado
        ),
        name="descargar_archivo_importado",
    ),
    path(
        "importarexpedientes/<int:id_archivo>/ajax/",
        permission_code_required("importarexpediente.view_archivosimportados")(
            importarexpediente_detail_ajax
        ),
        name="importarexpediente_detail_ajax",
    ),
    path(
        "importarexpedientes/<int:id_archivo>/fechas-acreditacion/",
        permissions_any_required(
            [
                "importarexpediente.change_archivosimportados",
                "expedientespagos.change_expedientepago",
            ]
        )(ImportarFechasAcreditacionView.as_view()),
        name="importar_fechas_acreditacion",
    ),
    path(
        "importarexpedientes/<int:id_archivo>/importar_datos/",
        ImportDatosView.as_view(),
        name="importar_datos",
    ),
    path(
        "importarexpedientes/<int:id_archivo>/borrar_datos_importados/",
        BorrarDatosImportadosView.as_view(),
        name="borrar_datos_importados",
    ),
]
