# Generated by Django 4.2.16 on 2025-01-28 14:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizaciones", "0001_initial"),
        ("configuraciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CentroDesarrolloInfantil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "comienzo",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2025),
                        ],
                        verbose_name="Año en el que comenzó a funcionar",
                    ),
                ),
                (
                    "modalidad_gestion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("nacional", "Gobierno Nacional"),
                            ("provincial", "Gobierno Provincial"),
                            ("municipal", "Gobierno Municipal"),
                            ("ong", "ONG"),
                            ("cogestion", "Co-gestión"),
                            ("otra", "Otra"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("partido", models.CharField(blank=True, max_length=255, null=True)),
                ("barrio", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "codigo_postal",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1000),
                            django.core.validators.MaxValueValidator(999999),
                        ],
                    ),
                ),
                ("direccion", models.TextField(blank=True, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("horario_inicio", models.TimeField(blank=True, null=True)),
                ("horario_fin", models.TimeField(blank=True, null=True)),
                ("cantidad_ninos", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cantidad_trabajadores",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "cobro_arancel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("inferior_15", "Arancel inferior al 15%"),
                            ("superior_15", "Arancel superior al 15%"),
                            ("no_cobra", "No se cobra arancel"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("estabilidad_matricula", models.BooleanField(blank=True, null=True)),
                (
                    "dias_funcionamiento",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="centros",
                        to="configuraciones.dia",
                    ),
                ),
                (
                    "localidad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="configuraciones.localidad",
                    ),
                ),
                (
                    "meses_funcionamiento",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="centros",
                        to="configuraciones.mes",
                    ),
                ),
                (
                    "municipio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="configuraciones.municipio",
                    ),
                ),
                (
                    "organizacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizaciones.organizacion",
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="configuraciones.provincia",
                    ),
                ),
                (
                    "turnos_funcionamiento",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="centros",
                        to="configuraciones.turno",
                    ),
                ),
            ],
        ),
    ]
