# Generated by Django 4.2.16 on 2025-01-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cdi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="centrodesarrolloinfantil",
            name="numexpe",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Numero de expediente"
            ),
        ),
        migrations.AddField(
            model_name="centrodesarrolloinfantil",
            name="numrepo",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Numero de Repi"
            ),
        ),
    ]
