# Generated by Django 4.2.20 on 2025-08-12 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cdi", "0002_alter_centrodesarrolloinfantil_dias_funcionamiento_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="centrodesarrolloinfantil",
            options={
                "verbose_name": "Centro de Desarrollo Infantil",
                "verbose_name_plural": "Centros de Desarrollo Infantil",
            },
        ),
    ]
