# Generated by Django 4.2.16 on 2025-04-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cdi", "0004_alter_centrodesarrolloinfantil_dias_funcionamiento_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="centrodesarrolloinfantil",
            old_name="foto_legajo",
            new_name="foto_legajo",
        ),
    ]
