# Generated by Django 4.2.27 on 2026-03-16 18:55

import core.soft_delete.base
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("centrodeinfancia", "0012_trabajador"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="trabajador",
            managers=[
                ("objects", core.soft_delete.base.SoftDeleteManager()),
                (
                    "all_objects",
                    core.soft_delete.base.SoftDeleteManager(include_deleted=True),
                ),
            ],
        ),
    ]
