# Generated by Django 4.2 on 2026-03-26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("centrodeinfancia", "0013_alter_trabajador_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="centrodeinfancia",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Centro de Desarrollo Infantil",
                "verbose_name_plural": "Centros de Desarrollo Infantil",
            },
        ),
        migrations.AlterModelOptions(
            name="intervencioncentroinfancia",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Intervención Centro de Desarrollo Infantil",
                "verbose_name_plural": "Intervenciones Centro de Desarrollo Infantil",
            },
        ),
        migrations.AlterModelOptions(
            name="nominacentroinfancia",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Nómina Centro de Desarrollo Infantil",
                "verbose_name_plural": "Nóminas Centro de Desarrollo Infantil",
            },
        ),
        migrations.AlterModelOptions(
            name="observacioncentroinfancia",
            options={
                "verbose_name": "Observación Centro de Desarrollo Infantil",
                "verbose_name_plural": "Observaciones Centro de Desarrollo Infantil",
            },
        ),
    ]
