# Generated manually for the CDI Spanish naming refactor.

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("centrodeinfancia", "0014_update_verbose_names_centros_desarrollo_infantil"),
    ]

    operations = [
        migrations.RenameField(
            model_name="centrodeinfancia",
            old_name="cdi_code",
            new_name="codigo_cdi",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="survey_date",
            new_name="fecha_relevamiento",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="respondent_full_name",
            new_name="nombre_completo_respondente",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="respondent_role",
            new_name="rol_respondente",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="respondent_email",
            new_name="email_respondente",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="cdi_name",
            new_name="nombre_cdi",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="cdi_code",
            new_name="codigo_cdi",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="cdi_province",
            new_name="provincia_cdi",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="cdi_department",
            new_name="departamento_cdi",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="cdi_municipality",
            new_name="municipio_cdi",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="cdi_locality",
            new_name="localidad_cdi",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="cdi_street",
            new_name="calle_cdi",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="cdi_door_number",
            new_name="numero_puerta_cdi",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="cdi_postal_code",
            new_name="codigo_postal_cdi",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="cdi_geo_latitude",
            new_name="latitud_geografica_cdi",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="cdi_geo_longitude",
            new_name="longitud_geografica_cdi",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="cdi_phone",
            new_name="telefono_cdi",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="cdi_email",
            new_name="email_cdi",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="cdi_contact_first_name",
            new_name="nombre_referente_cdi",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="cdi_contact_last_name",
            new_name="apellido_referente_cdi",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="cdi_contact_phone",
            new_name="telefono_referente_cdi",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="cdi_contact_email",
            new_name="email_referente_cdi",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="operation_months",
            new_name="meses_funcionamiento",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="operation_days",
            new_name="dias_funcionamiento",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="opening_time",
            new_name="horario_apertura",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="closing_time",
            new_name="horario_cierre",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="workday_type",
            new_name="tipo_jornada",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="workday_type_other",
            new_name="tipo_jornada_otra",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="total_children_count",
            new_name="cantidad_total_ninos",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="total_staff_count",
            new_name="cantidad_total_personal",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="management_mode",
            new_name="modalidad_gestion",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="management_mode_other",
            new_name="modalidad_gestion_otra",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="managing_organization_name",
            new_name="nombre_organizacion_gestora",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="managing_organization_cuit",
            new_name="cuit_organizacion_gestora",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="org_province",
            new_name="provincia_organizacion",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="org_department",
            new_name="departamento_organizacion",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="org_municipality",
            new_name="municipio_organizacion",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="org_locality",
            new_name="localidad_organizacion",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="org_street",
            new_name="calle_organizacion",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="org_number",
            new_name="numero_organizacion",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="org_postal_code",
            new_name="codigo_postal_organizacion",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="org_building",
            new_name="edificio_organizacion",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="org_floor",
            new_name="piso_organizacion",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="org_apartment",
            new_name="departamento_domicilio_organizacion",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="org_office",
            new_name="oficina_organizacion",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="org_phone",
            new_name="telefono_organizacion",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="org_email",
            new_name="email_organizacion",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="org_contact_first_name",
            new_name="nombre_referente_organizacion",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="org_contact_last_name",
            new_name="apellido_referente_organizacion",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="org_contact_phone",
            new_name="telefono_referente_organizacion",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="org_contact_email",
            new_name="email_referente_organizacion",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="tenure_mode",
            new_name="modalidad_tenencia",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="tenure_mode_other",
            new_name="modalidad_tenencia_otra",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="exclusive_space_use",
            new_name="uso_exclusivo_espacio",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="room_count_excluding_service_areas",
            new_name="cantidad_ambientes_sin_areas_servicio",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="electricity_access",
            new_name="acceso_energia",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="electrical_safety",
            new_name="seguridad_electrica",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="water_access",
            new_name="acceso_agua",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="safe_drinking_water_source",
            new_name="fuente_agua_segura_consumo",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="excreta_disposal",
            new_name="eliminacion_excretas",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="has_fire_extinguishers_current",
            new_name="tiene_extintores_vigentes",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="first_aid_kit_status",
            new_name="estado_botiquin_primeros_auxilios",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="has_working_computer",
            new_name="tiene_computadora_funcionando",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="internet_access_quality_staff",
            new_name="acceso_internet_personal",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="has_kitchen_space",
            new_name="tiene_espacio_cocina",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="cooking_fuel",
            new_name="combustible_cocinar",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="has_outdoor_space",
            new_name="tiene_espacio_exterior",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="has_outdoor_playground",
            new_name="tiene_juegos_exteriores",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="evacuation_plan_and_drills",
            new_name="plan_evacuacion_y_simulacros",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="first_aid_training_coverage",
            new_name="cobertura_capacitacion_primeros_auxilios",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="emergency_medical_service",
            new_name="servicio_emergencia_medica",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="health_protocol_items",
            new_name="items_protocolo_salud",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="meals_provided",
            new_name="prestaciones_alimentarias",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="meals_provided_other",
            new_name="prestaciones_alimentarias_otra",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="menu_preparation_quality",
            new_name="calidad_elaboracion_menu",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="menu_periodic_evaluation",
            new_name="evaluacion_periodica_menu",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="food_handling_training_coverage",
            new_name="cobertura_capacitacion_manipulacion_alimentos",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="breast_milk_storage_conditions",
            new_name="condiciones_almacenamiento_leche_humana",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="breastfeeding_awareness_actions",
            new_name="acciones_sensibilizacion_lactancia",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="has_waitlist_registry",
            new_name="tiene_registro_lista_espera",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="has_admission_prioritization_tool",
            new_name="tiene_instrumento_priorizacion_ingreso",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="children_with_disabilities_count",
            new_name="cantidad_ninos_discapacidad",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="children_specific_ethnicity_count",
            new_name="cantidad_ninos_etnia_especifica",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="has_entry_exit_staff",
            new_name="tiene_personal_entrada_salida",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="family_communication_frequency",
            new_name="frecuencia_comunicacion_familias",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="parenting_workshops_frequency",
            new_name="frecuencia_talleres_crianza",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="actions_promoting_rights_access",
            new_name="realiza_acciones_promocion_acceso_derechos",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="actions_against_rights_violations",
            new_name="realiza_acciones_acompanamiento_vulneracion_derechos",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="networking_level",
            new_name="nivel_trabajo_red",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="rights_violation_protocol",
            new_name="protocolo_vulneracion_derechos",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="technical_team_level",
            new_name="nivel_equipo_tecnico",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="child_development_record_frequency",
            new_name="frecuencia_registro_desarrollo_nino",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="family_info_record_frequency",
            new_name="frecuencia_registro_informacion_familiar",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="health_vaccine_record_frequency",
            new_name="frecuencia_registro_salud_vacunas",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="socioeducational_project_participants",
            new_name="participantes_proyecto_socioeducativo",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="classroom_activity_planning",
            new_name="planificacion_actividades_sala",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="integral_planning",
            new_name="planificacion_integral",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="direction_training_in_early_childhood",
            new_name="formacion_direccion_primera_infancia",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="pedagogical_pairs_coverage",
            new_name="cobertura_duplas_pedagogicas",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="qualified_teacher_coverage",
            new_name="cobertura_educadora_titulo_habilitante",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="assistant_training_coverage",
            new_name="cobertura_formacion_auxiliares",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="main_hiring_mode",
            new_name="modalidad_contratacion_principal",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="meetings_teaching_staff_frequency",
            new_name="frecuencia_reuniones_personal_sala",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="meetings_non_teaching_staff_frequency",
            new_name="frecuencia_reuniones_personal_no_docente",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="meetings_all_staff_frequency",
            new_name="frecuencia_reuniones_todo_personal",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="training_instances_all_staff_last_3y",
            new_name="instancias_capacitacion_todo_personal_ultimos_3_anios",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="training_instances_room_staff_last_3y",
            new_name="instancias_capacitacion_personal_sala_ultimos_3_anios",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="training_instances_technical_team_last_3y",
            new_name="instancias_capacitacion_equipo_tecnico_ultimos_3_anios",
        ),
        migrations.RenameField(
            model_name="formulariocdi",
            old_name="training_instances_kitchen_staff_last_3y",
            new_name="instancias_capacitacion_personal_cocina_ultimos_3_anios",
        ),
        migrations.RenameField(
            model_name="formulariocdiroomdistribution",
            old_name="age_group",
            new_name="grupo_etario",
        ),
        migrations.RenameField(
            model_name="formulariocdiroomdistribution",
            old_name="room_count",
            new_name="cantidad_salas",
        ),
        migrations.RenameField(
            model_name="formulariocdiroomdistribution",
            old_name="exclusive_area_m2",
            new_name="superficie_exclusiva_m2",
        ),
        migrations.RenameField(
            model_name="formulariocdiroomdistribution",
            old_name="children_count",
            new_name="cantidad_ninos",
        ),
        migrations.RenameField(
            model_name="formulariocdiroomdistribution",
            old_name="staff_count",
            new_name="cantidad_personal_sala",
        ),
        migrations.RenameField(
            model_name="formulariocdiwaitlistbyagegroup",
            old_name="age_group",
            new_name="grupo_etario",
        ),
        migrations.RenameField(
            model_name="formulariocdiwaitlistbyagegroup",
            old_name="waitlist_count",
            new_name="cantidad_demanda_insatisfecha",
        ),
        migrations.RenameField(
            model_name="formulariocdiarticulationfrequency",
            old_name="institution_type",
            new_name="tipo_institucion",
        ),
        migrations.RenameField(
            model_name="formulariocdiarticulationfrequency",
            old_name="frequency",
            new_name="frecuencia",
        ),
    ]
