# Generated by Django 4.2.27 on 2026-03-30 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centrodeinfancia", "0019_formulariocdi_departamentos_ipi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulariocdi",
            name="cobertura_educadora_titulo_habilitante",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "todas",
                        "Sí, en todas las salas una educadora cuenta con título habilitante de nivel inicial",
                    ),
                    (
                        "mayoria",
                        "Sí, en la mayoría de las salas una educadora cuenta con título habilitante de nivel inicial",
                    ),
                    (
                        "algunas",
                        "Solo en algunas salas una educadora cuenta con título habilitante de nivel inicial",
                    ),
                    (
                        "muy_pocas",
                        "Muy pocas salas tienen una educadora con título habilitante",
                    ),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formulariocdi",
            name="telefono_cdi",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ingrese un teléfono válido: solo números o grupos numéricos separados por guiones.",
                        regex="^\\d+(?:-\\d+)*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="formulariocdi",
            name="telefono_organizacion",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ingrese un teléfono válido: solo números o grupos numéricos separados por guiones.",
                        regex="^\\d+(?:-\\d+)*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="formulariocdi",
            name="telefono_referente_cdi",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ingrese un teléfono válido: solo números o grupos numéricos separados por guiones.",
                        regex="^\\d+(?:-\\d+)*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="formulariocdi",
            name="telefono_referente_organizacion",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ingrese un teléfono válido: solo números o grupos numéricos separados por guiones.",
                        regex="^\\d+(?:-\\d+)*$",
                    )
                ],
            ),
        ),
    ]
