# Generated by Django 4.2.27 on 2026-03-31 13:58

import core.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


MESES_MAP = {
    "ENE": "enero",
    "FEB": "febrero",
    "MAR": "marzo",
    "ABR": "abril",
    "MAY": "mayo",
    "JUN": "junio",
    "JUL": "julio",
    "AGO": "agosto",
    "SET": "septiembre",
    "SEP": "septiembre",
    "OCT": "octubre",
    "NOV": "noviembre",
    "DIC": "diciembre",
    "enero": "enero",
    "febrero": "febrero",
    "marzo": "marzo",
    "abril": "abril",
    "mayo": "mayo",
    "junio": "junio",
    "julio": "julio",
    "agosto": "agosto",
    "septiembre": "septiembre",
    "octubre": "octubre",
    "noviembre": "noviembre",
    "diciembre": "diciembre",
}

DIA_MAP = {
    "LUNES": "lunes",
    "MARTES": "martes",
    "MIERCOLES": "miercoles",
    "MIÉRCOLES": "miercoles",
    "JUEVES": "jueves",
    "VIERNES": "viernes",
    "SABADO": "sabado",
    "SÁBADO": "sabado",
    "DOMINGO": "domingo",
    "lunes": "lunes",
    "martes": "martes",
    "miercoles": "miercoles",
    "miércoles": "miercoles",
    "jueves": "jueves",
    "viernes": "viernes",
    "sabado": "sabado",
    "sábado": "sabado",
    "domingo": "domingo",
}

MODALIDAD_GESTION_MAP = {
    "ong": "gestion_tercer_sector",
    "gobierno_nacional": "gobierno_nacional",
    "gobierno_provincial": "gobierno_provincial",
    "gobierno_municipal": "gobierno_municipal",
    "gestion_privada": "gestion_privada",
    "gestion_tercer_sector": "gestion_tercer_sector",
    "cogestion_provincial_municipal": "cogestion_provincial_municipal",
    "cogestion_ong_provincial_municipal": "cogestion_ong_provincial_municipal",
    "otra": "otra",
}


def _normalizar_lista(values, mapping):
    if not isinstance(values, list):
        return []

    normalizados = []
    vistos = set()
    for item in values:
        normalized = mapping.get(item, mapping.get(str(item), item))
        if not normalized or normalized in vistos:
            continue
        normalizados.append(normalized)
        vistos.add(normalized)
    return normalizados


def _solo_digitos(value):
    if value in (None, ""):
        return None
    digits = "".join(ch for ch in str(value) if ch.isdigit())
    return digits or None


def migrar_datos_existentes(apps, schema_editor):
    CentroDeInfancia = apps.get_model("centrodeinfancia", "CentroDeInfancia")
    FormularioCDI = apps.get_model("centrodeinfancia", "FormularioCDI")
    FormularioCDIHorarioFuncionamiento = apps.get_model(
        "centrodeinfancia", "FormularioCDIHorarioFuncionamiento"
    )

    for centro in CentroDeInfancia.objects.select_related("organizacion").iterator():
        organizacion = getattr(centro, "organizacion", None)
        centro.organizacion_texto = (
            getattr(organizacion, "nombre", None) if organizacion else None
        )
        centro.save(update_fields=["organizacion_texto"])

    for formulario in FormularioCDI.objects.all().iterator():
        meses = _normalizar_lista(formulario.meses_funcionamiento, MESES_MAP)
        dias = _normalizar_lista(formulario.dias_funcionamiento, DIA_MAP)
        modalidad = MODALIDAD_GESTION_MAP.get(
            formulario.modalidad_gestion, formulario.modalidad_gestion
        )
        codigo_postal = _solo_digitos(formulario.codigo_postal_cdi)
        cuit = _solo_digitos(formulario.cuit_organizacion_gestora)

        update_fields = [
            "meses_funcionamiento",
            "dias_funcionamiento",
            "modalidad_gestion",
            "codigo_postal_cdi",
            "cuit_organizacion_gestora",
        ]
        formulario.meses_funcionamiento = meses
        formulario.dias_funcionamiento = dias
        formulario.modalidad_gestion = modalidad
        formulario.codigo_postal_cdi = (
            int(codigo_postal) if codigo_postal is not None else None
        )
        formulario.cuit_organizacion_gestora = cuit
        formulario.save(update_fields=update_fields)

        if dias and (formulario.horario_apertura or formulario.horario_cierre):
            for dia in dias:
                FormularioCDIHorarioFuncionamiento.objects.update_or_create(
                    formulario=formulario,
                    dia=dia,
                    defaults={
                        "hora_apertura": formulario.horario_apertura,
                        "hora_cierre": formulario.horario_cierre,
                    },
                )


class Migration(migrations.Migration):

    dependencies = [
        (
            "centrodeinfancia",
            "0020_alter_formulariocdi_cobertura_educadora_titulo_habilitante_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="centrodeinfancia",
            name="ambito",
            field=models.CharField(
                choices=[
                    ("sin_informacion", "Sin informaciÃ³n"),
                    ("rural", "Rural"),
                    ("urbano", "Urbano"),
                ],
                default="sin_informacion",
                max_length=32,
                verbose_name="Ãmbito",
            ),
        ),
        migrations.AddField(
            model_name="centrodeinfancia",
            name="codigo_postal",
            field=models.PositiveBigIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(9999999999),
                ],
                verbose_name="CÃ³digo postal",
            ),
        ),
        migrations.AddField(
            model_name="centrodeinfancia",
            name="cuit_organizacion_gestiona",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ingrese un CUIT vÃ¡lido de 11 dÃ­gitos.",
                        regex="^\\d{11}$",
                    )
                ],
                verbose_name="CUIT del organismo u organizaciÃ³n que gestiona",
            ),
        ),
        migrations.AddField(
            model_name="centrodeinfancia",
            name="dias_funcionamiento",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="centrodeinfancia",
            name="latitud",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=8,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
        migrations.AddField(
            model_name="centrodeinfancia",
            name="longitud",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
            ),
        ),
        migrations.AddField(
            model_name="centrodeinfancia",
            name="mail",
            field=core.fields.UnicodeEmailField(
                blank=True, max_length=254, null=True, verbose_name="Mail"
            ),
        ),
        migrations.AddField(
            model_name="centrodeinfancia",
            name="meses_funcionamiento",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="centrodeinfancia",
            name="modalidad_gestion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gobierno_nacional", "Gobierno nacional"),
                    ("gobierno_provincial", "Gobierno provincial"),
                    ("gobierno_municipal", "Gobierno municipal"),
                    (
                        "gestion_privada",
                        "GestiÃ³n privada (Organizaciones con fines de lucro)",
                    ),
                    (
                        "gestion_tercer_sector",
                        "GestiÃ³n Tercer Sector (Organizaciones sin fines de lucro; incluye organizaciones no gubernamentales, organizaciones sociales, movimientos sociales, grupos comunitarios o barriales, etc.)",
                    ),
                    (
                        "cogestion_provincial_municipal",
                        "Co-gestiÃ³n: Gob. Provincial y municipal",
                    ),
                    (
                        "cogestion_ong_provincial_municipal",
                        "Co-gestiÃ³n: ONG/Gob. Provincial/municipal",
                    ),
                    ("otra", "Otra: especificar"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="centrodeinfancia",
            name="modalidad_gestion_otra",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="centrodeinfancia",
            name="oferta_servicios",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lactantes", "Lactantes"),
                    ("deambuladores", "Deambuladores"),
                    ("dos_anos", "2 aÃ±os"),
                    ("tres_anos", "3 aÃ±os"),
                    ("cuatro_anos", "4 aÃ±os"),
                    ("multiedad", "Multiedad"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="centrodeinfancia",
            name="tipo_jornada",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "simple_single_shift",
                        "Jornada simple (un solo turno con un Ãºnico grupo de niÃ±os)",
                    ),
                    (
                        "multiple_simple_shifts",
                        "Dos o mÃ¡s jornadas simples (dos o mÃ¡s turnos a los que asisten distintos grupos de niÃ±os)",
                    ),
                    (
                        "full_double_same_group",
                        "Jornada completa/doble (dos o mÃ¡s turnos a los que asiste un mismo grupo de niÃ±os)",
                    ),
                    ("other", "Otra (especificar)"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="centrodeinfancia",
            name="tipo_jornada_otra",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="centrodeinfancia",
            name="organizacion_texto",
            field=models.CharField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="DenominaciÃ³n del organismo u organizaciÃ³n que gestiona",
            ),
        ),
        migrations.AddField(
            model_name="formulariocdi",
            name="ambito",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sin_informacion", "Sin informaciÃ³n"),
                    ("rural", "Rural"),
                    ("urbano", "Urbano"),
                ],
                default="sin_informacion",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="formulariocdi",
            name="oferta_servicios",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lactantes", "Lactantes"),
                    ("deambuladores", "Deambuladores"),
                    ("dos_anos", "2 aÃ±os"),
                    ("tres_anos", "3 aÃ±os"),
                    ("cuatro_anos", "4 aÃ±os"),
                    ("multiedad", "Multiedad"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="FormularioCDIHorarioFuncionamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.CharField(
                        choices=[
                            ("lunes", "Lunes"),
                            ("martes", "Martes"),
                            ("miercoles", "MiÃ©rcoles"),
                            ("jueves", "Jueves"),
                            ("viernes", "Viernes"),
                            ("sabado", "SÃ¡bado"),
                            ("domingo", "Domingo"),
                        ],
                        max_length=16,
                    ),
                ),
                ("hora_apertura", models.TimeField(blank=True, null=True)),
                ("hora_cierre", models.TimeField(blank=True, null=True)),
                (
                    "formulario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios_funcionamiento",
                        to="centrodeinfancia.formulariocdi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horario de funcionamiento del formulario CDI",
                "verbose_name_plural": "Horarios de funcionamiento del formulario CDI",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CentroDeInfanciaHorarioFuncionamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.CharField(
                        choices=[
                            ("lunes", "Lunes"),
                            ("martes", "Martes"),
                            ("miercoles", "MiÃ©rcoles"),
                            ("jueves", "Jueves"),
                            ("viernes", "Viernes"),
                            ("sabado", "SÃ¡bado"),
                            ("domingo", "Domingo"),
                        ],
                        max_length=16,
                    ),
                ),
                ("hora_apertura", models.TimeField(blank=True, null=True)),
                ("hora_cierre", models.TimeField(blank=True, null=True)),
                (
                    "centro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios_funcionamiento",
                        to="centrodeinfancia.centrodeinfancia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Horario de funcionamiento del CDI",
                "verbose_name_plural": "Horarios de funcionamiento del CDI",
                "ordering": ["id"],
            },
        ),
        migrations.RunPython(migrar_datos_existentes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="centrodeinfancia",
            name="organizacion",
        ),
        migrations.RenameField(
            model_name="centrodeinfancia",
            old_name="organizacion_texto",
            new_name="organizacion",
        ),
        migrations.AlterField(
            model_name="formulariocdi",
            name="codigo_postal_cdi",
            field=models.PositiveBigIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(9999999999),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="formulariocdi",
            name="cuit_organizacion_gestora",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ingrese un CUIT vÃ¡lido de 11 dÃ­gitos.",
                        regex="^\\d{11}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="formulariocdi",
            name="modalidad_gestion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gobierno_nacional", "Gobierno nacional"),
                    ("gobierno_provincial", "Gobierno provincial"),
                    ("gobierno_municipal", "Gobierno municipal"),
                    (
                        "gestion_privada",
                        "GestiÃ³n privada (Organizaciones con fines de lucro)",
                    ),
                    (
                        "gestion_tercer_sector",
                        "GestiÃ³n Tercer Sector (Organizaciones sin fines de lucro; incluye organizaciones no gubernamentales, organizaciones sociales, movimientos sociales, grupos comunitarios o barriales, etc.)",
                    ),
                    (
                        "cogestion_provincial_municipal",
                        "Co-gestiÃ³n: Gob. Provincial y municipal",
                    ),
                    (
                        "cogestion_ong_provincial_municipal",
                        "Co-gestiÃ³n: ONG/Gob. Provincial/municipal",
                    ),
                    ("otra", "Otra: especificar"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formulariocdi",
            name="tipo_jornada",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "simple_single_shift",
                        "Jornada simple (un solo turno con un Ãºnico grupo de niÃ±os)",
                    ),
                    (
                        "multiple_simple_shifts",
                        "Dos o mÃ¡s jornadas simples (dos o mÃ¡s turnos a los que asisten distintos grupos de niÃ±os)",
                    ),
                    (
                        "full_double_same_group",
                        "Jornada completa/doble (dos o mÃ¡s turnos a los que asiste un mismo grupo de niÃ±os)",
                    ),
                    ("other", "Otra (especificar)"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="formulariocdihorariofuncionamiento",
            constraint=models.UniqueConstraint(
                fields=("formulario", "dia"),
                name="uniq_formulario_cdi_horario_funcionamiento_dia",
            ),
        ),
        migrations.AddConstraint(
            model_name="centrodeinfanciahorariofuncionamiento",
            constraint=models.UniqueConstraint(
                fields=("centro", "dia"), name="uniq_cdi_horario_funcionamiento_dia"
            ),
        ),
    ]
