# Generated by Django 4.2.27 on 2026-03-31 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centrodeinfancia", "0021_centrodeinfancia_ambito_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="centrodeinfancia",
            name="ambito",
            field=models.CharField(
                choices=[
                    ("sin_informacion", "Sin información"),
                    ("rural", "Rural"),
                    ("urbano", "Urbano"),
                ],
                default="sin_informacion",
                max_length=32,
                verbose_name="Ámbito",
            ),
        ),
        migrations.AlterField(
            model_name="centrodeinfancia",
            name="codigo_postal",
            field=models.PositiveBigIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(9999999999),
                ],
                verbose_name="Código postal",
            ),
        ),
        migrations.AlterField(
            model_name="centrodeinfancia",
            name="cuit_organizacion_gestiona",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ingrese un CUIT válido de 11 dígitos.",
                        regex="^\\d{11}$",
                    )
                ],
                verbose_name="CUIT del organismo u organización que gestiona",
            ),
        ),
        migrations.AlterField(
            model_name="centrodeinfancia",
            name="modalidad_gestion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gobierno_nacional", "Gobierno nacional"),
                    ("gobierno_provincial", "Gobierno provincial"),
                    ("gobierno_municipal", "Gobierno municipal"),
                    (
                        "gestion_privada",
                        "Gestión privada (Organizaciones con fines de lucro)",
                    ),
                    (
                        "gestion_tercer_sector",
                        "Gestión Tercer Sector (Organizaciones sin fines de lucro; incluye organizaciones no gubernamentales, organizaciones sociales, movimientos sociales, grupos comunitarios o barriales, etc.)",
                    ),
                    (
                        "cogestion_provincial_municipal",
                        "Co-gestión: Gob. Provincial y municipal",
                    ),
                    (
                        "cogestion_ong_provincial_municipal",
                        "Co-gestión: ONG/Gob. Provincial/municipal",
                    ),
                    ("otra", "Otra: especificar"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="centrodeinfancia",
            name="oferta_servicios",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lactantes", "Lactantes"),
                    ("deambuladores", "Deambuladores"),
                    ("dos_anos", "2 años"),
                    ("tres_anos", "3 años"),
                    ("cuatro_anos", "4 años"),
                    ("multiedad", "Multiedad"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="centrodeinfancia",
            name="organizacion",
            field=models.CharField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Denominación del organismo u organización que gestiona",
            ),
        ),
        migrations.AlterField(
            model_name="centrodeinfancia",
            name="tipo_jornada",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "simple_single_shift",
                        "Jornada simple (un solo turno con un único grupo de niños)",
                    ),
                    (
                        "multiple_simple_shifts",
                        "Dos o más jornadas simples (dos o más turnos a los que asisten distintos grupos de niños)",
                    ),
                    (
                        "full_double_same_group",
                        "Jornada completa/doble (dos o más turnos a los que asiste un mismo grupo de niños)",
                    ),
                    ("other", "Otra (especificar)"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="centrodeinfanciahorariofuncionamiento",
            name="dia",
            field=models.CharField(
                choices=[
                    ("lunes", "Lunes"),
                    ("martes", "Martes"),
                    ("miercoles", "Miércoles"),
                    ("jueves", "Jueves"),
                    ("viernes", "Viernes"),
                    ("sabado", "Sábado"),
                    ("domingo", "Domingo"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="formulariocdi",
            name="ambito",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sin_informacion", "Sin información"),
                    ("rural", "Rural"),
                    ("urbano", "Urbano"),
                ],
                default="sin_informacion",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="formulariocdi",
            name="cuit_organizacion_gestora",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ingrese un CUIT válido de 11 dígitos.",
                        regex="^\\d{11}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="formulariocdi",
            name="modalidad_gestion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gobierno_nacional", "Gobierno nacional"),
                    ("gobierno_provincial", "Gobierno provincial"),
                    ("gobierno_municipal", "Gobierno municipal"),
                    (
                        "gestion_privada",
                        "Gestión privada (Organizaciones con fines de lucro)",
                    ),
                    (
                        "gestion_tercer_sector",
                        "Gestión Tercer Sector (Organizaciones sin fines de lucro; incluye organizaciones no gubernamentales, organizaciones sociales, movimientos sociales, grupos comunitarios o barriales, etc.)",
                    ),
                    (
                        "cogestion_provincial_municipal",
                        "Co-gestión: Gob. Provincial y municipal",
                    ),
                    (
                        "cogestion_ong_provincial_municipal",
                        "Co-gestión: ONG/Gob. Provincial/municipal",
                    ),
                    ("otra", "Otra: especificar"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formulariocdi",
            name="oferta_servicios",
            field=models.CharField(
                blank=True,
                choices=[
                    ("lactantes", "Lactantes"),
                    ("deambuladores", "Deambuladores"),
                    ("dos_anos", "2 años"),
                    ("tres_anos", "3 años"),
                    ("cuatro_anos", "4 años"),
                    ("multiedad", "Multiedad"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formulariocdi",
            name="tipo_jornada",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "simple_single_shift",
                        "Jornada simple (un solo turno con un único grupo de niños)",
                    ),
                    (
                        "multiple_simple_shifts",
                        "Dos o más jornadas simples (dos o más turnos a los que asisten distintos grupos de niños)",
                    ),
                    (
                        "full_double_same_group",
                        "Jornada completa/doble (dos o más turnos a los que asiste un mismo grupo de niños)",
                    ),
                    ("other", "Otra (especificar)"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formulariocdihorariofuncionamiento",
            name="dia",
            field=models.CharField(
                choices=[
                    ("lunes", "Lunes"),
                    ("martes", "Martes"),
                    ("miercoles", "Miércoles"),
                    ("jueves", "Jueves"),
                    ("viernes", "Viernes"),
                    ("sabado", "Sábado"),
                    ("domingo", "Domingo"),
                ],
                max_length=16,
            ),
        ),
    ]
