# Generated by Django 4.2.27 on 2026-04-01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "centrodeinfancia",
            "0021_expandir_nomina_cdi",
        ),
        (
            "centrodeinfancia",
            "0022_alter_centrodeinfancia_ambito_and_more",
        ),
    ]

    operations = []
