# Generated by Django 4.2.27 on 2026-04-13 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "centrodeinfancia",
            "0023_merge_0021_expandir_nomina_cdi_0022_alter_centrodeinfancia_ambito_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="intervencioncentroinfancia",
            name="creado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
    ]
