# Generated by Django 4.2.27 on 2026-04-17 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("centrodeinfancia", "0024_intervencioncentroinfancia_creado_por"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intervencioncentroinfancia",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
    ]
