# Generated by Django 4.2.27 on 2026-04-20 17:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centrodeinfancia", "0024_alter_centrodeinfancia_nombre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="centrodeinfancia",
            name="fecha_inicio",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(datetime.date(1990, 1, 1))
                ],
                verbose_name="Año de inicio de actividades del CDI",
            ),
        ),
        migrations.AlterField(
            model_name="centrodeinfancia",
            name="organizacion",
            field=models.CharField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Denominación del organismo u organización que gestiona el CDI",
            ),
        ),
    ]
