# Generated by Django 4.2.27 on 2026-04-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centrodeinfancia", "0027_merge_20260427_1431"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulariocdi",
            name="condiciones_almacenamiento_leche_humana",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "heladera_exclusiva_identificada_y_rotulada",
                        "Se conserva en heladera exclusiva, identificada por niño/a y rotulada con fecha de extracción.",
                    ),
                    (
                        "heladera_compartida_sector_exclusivo_identificada_y_rotulada",
                        "Se conserva en heladera compartida, en un sector exclusivo, identificada por niño/a y rotulada con fecha de extracción.",
                    ),
                    (
                        "heladera_exclusiva_identificada_sin_fecha",
                        "Se conserva en heladera exclusiva, identificada por niño/a pero sin rotulación con fecha de extracción.",
                    ),
                    (
                        "heladera_compartida_sector_exclusivo_identificada_sin_fecha",
                        "Se conserva en heladera compartida, en un sector exclusivo, identificada por niño/a pero sin rotulación con fecha de extracción.",
                    ),
                    (
                        "sin_espacio_exclusivo_ni_identificacion",
                        "No se conserva en espacio exclusivo ni se identifica por niño/a.",
                    ),
                    (
                        "no_aplica_o_no_se_realiza_conservación_de_leche_humana",
                        "No aplica o no se realiza conservación de leche humana",
                    ),
                ],
                max_length=128,
                null=True,
            ),
        ),
    ]
