# Generated by Django 4.2.27 on 2026-05-18 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "centrodeinfancia",
            "0001_squashed_0028",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AccesoCDI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_baja", models.DateTimeField(blank=True, null=True)),
                (
                    "centro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesos_usuarios",
                        to="centrodeinfancia.centrodeinfancia",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accesos_cdi_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesos_cdi",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Acceso de usuario a CDI",
                "verbose_name_plural": "Accesos de usuarios a CDI",
                "indexes": [
                    models.Index(
                        fields=["centro", "activo"],
                        name="centrodeinf_centro__2b86dc_idx",
                    ),
                    models.Index(
                        fields=["user", "activo"], name="centrodeinf_user_id_8ade46_idx"
                    ),
                    models.Index(
                        fields=["creado_por", "activo"],
                        name="centrodeinf_creado__22fecf_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="accesocdi",
            constraint=models.UniqueConstraint(
                fields=("user", "centro"), name="uniq_acceso_cdi_user_centro"
            ),
        ),
    ]
