# Generated by Django 4.2.27 on 2026-06-08 13:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_programa_organismo_programa_descripcion"),
        ("centrodeinfancia", "0029_accesocdi_accesocdi_uniq_acceso_cdi_user_centro"),
    ]

    operations = [
        migrations.AddField(
            model_name="trabajador",
            name="anos_trabajo_primera_infancia",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "1"),
                    ("2", "2"),
                    ("3", "3"),
                    ("4", "4"),
                    ("5", "5"),
                    ("6", "6"),
                    ("7", "7"),
                    ("8", "8"),
                    ("9", "9"),
                    ("10_o_mas", "10 o más"),
                ],
                max_length=16,
                null=True,
                verbose_name="Años de trabajo en primera infancia",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="calle_contacto",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Calle y numeración"
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="capacitaciones_certificadas",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="Capacitaciones certificadas (últimos tres años)",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="carga_horaria_semanal",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(60),
                ],
                verbose_name="Carga horaria semanal (CDI)",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="cuit",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ingrese un CUIT válido de 11 dígitos.",
                        regex="^\\d{11}$",
                    )
                ],
                verbose_name="CUIT",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="dni",
            field=models.PositiveBigIntegerField(
                blank=True, null=True, verbose_name="Número de documento"
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Correo electrónico"
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="es_interprete",
            field=models.CharField(
                blank=True,
                choices=[
                    ("si", "Sí"),
                    ("no", "No"),
                    ("no_corresponde", "No corresponde"),
                ],
                max_length=16,
                null=True,
                verbose_name="¿Es intérprete?",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="fecha_carga",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de carga"
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="fecha_nacimiento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de nacimiento"
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="formacion_academica",
            field=models.CharField(
                blank=True,
                choices=[
                    ("artes_visuales", "Artes visuales"),
                    ("atencion_temprana", "Atención temprana"),
                    ("auxiliar_jardin_maternal", "Auxiliar de jardín maternal"),
                    ("ciencias_educacion", "Ciencias de la educación"),
                    ("educacion_fisica", "Educación física"),
                    ("estimulacion_temprana", "Estimulación temprana"),
                    ("gestion_educativa", "Gestión educativa"),
                    ("magisterio", "Magisterio"),
                    ("musica", "Música"),
                    ("musicoterapia", "Musicoterapia"),
                    ("nutricion", "Nutrición"),
                    ("profesorado_nivel_inicial", "Profesorado de nivel inicial"),
                    ("psicologia", "Psicología"),
                    ("psicomotricidad", "Psicomotricidad"),
                    ("psicopedagogia", "Psicopedagogía"),
                    ("trabajo_social", "Trabajo social"),
                    ("otro", "Otro"),
                ],
                max_length=32,
                null=True,
                verbose_name="Formación académica",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="funcion_cdi",
            field=models.CharField(
                blank=True,
                choices=[
                    ("educador_docente_sala", "Educador o docente de sala"),
                    ("auxiliar_sala", "Auxiliar de sala"),
                    ("director_coordinador", "Director/a o coordinador/a"),
                    ("administrativo", "Administrativo/a"),
                    ("equipo_tecnico", "Equipo técnico"),
                    ("seguridad", "Seguridad"),
                    ("limpieza", "Limpieza"),
                    ("cocina", "Cocina"),
                    ("mantenimiento", "Mantenimiento"),
                    ("otro", "Otro"),
                ],
                max_length=32,
                null=True,
                verbose_name="Función (CDI)",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="funcion_egp",
            field=models.CharField(
                blank=True,
                choices=[
                    ("coordinacion_general", "Coordinación General"),
                    ("ref_calidad_cdi", "Referente de Calidad de los CDI"),
                    (
                        "ref_saf",
                        "Referente del Servicio de Acompañamiento Familiar (SAF)",
                    ),
                    ("ref_monitoreo", "Referente de Monitoreo"),
                    ("ref_capacitacion", "Referente de capacitación"),
                    ("apoyo_administrativo", "Apoyo administrativo"),
                    ("no_corresponde", "No corresponde"),
                ],
                max_length=32,
                null=True,
                verbose_name="Función (EGP)",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="grupo_pertenencia",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="¿Desciende, tiene antepasados o pertenece a alguno de los siguientes grupos?",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="lenguajes",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Lenguajes que utiliza"
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="localidad_contacto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.localidad",
                verbose_name="Localidad",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="municipio_contacto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.municipio",
                verbose_name="Municipio",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="nacionalidad_trabajador",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="¿Cuál es su nacionalidad?",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="nivel_educativo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nunca", "Nunca asistió a un establecimiento educativo"),
                    ("inicial_incompleto", "Inicial incompleto"),
                    ("inicial_en_curso", "Inicial en curso"),
                    ("inicial_completo", "Inicial completo"),
                    ("primario_incompleto", "Primario incompleto"),
                    ("primario_en_curso", "Primario en curso"),
                    ("primario_completo", "Primario completo"),
                    ("secundario_incompleto", "Secundario incompleto"),
                    ("secundario_en_curso", "Secundario en curso"),
                    ("secundario_completo", "Secundario completo"),
                    ("superior_incompleto", "Superior incompleto"),
                    ("superior_en_curso", "Superior en curso"),
                    ("superior_completo", "Superior completo"),
                ],
                max_length=32,
                null=True,
                verbose_name="Nivel educativo",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="numero_cud",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Número de CUD (ANSES)",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="pais_nacimiento",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="¿Cuál es su país de nacimiento?",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="provincia_contacto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.provincia",
                verbose_name="Jurisdicción",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="pueblo_originario",
            field=models.CharField(
                blank=True,
                choices=[
                    ("atacama", "Atacama"),
                    ("ava_guarani", "Ava Guaraní"),
                    ("chane", "Chané"),
                    ("chane_guarani", "Chané - Guaraní"),
                    ("charrua", "Charrúa"),
                    ("chicha", "Chicha"),
                    ("chorote", "Chorote"),
                    ("chorote_wichi", "Chorote - Wichí"),
                    ("chulup_nivcale", "Chulupí (Nivaclé)"),
                    ("chulup_nivcale_omaguaca", "Chulupí (Nivaclé) - Omaguaca"),
                    ("comechingon", "Comechingón"),
                    ("comechingon_sanaviron", "Comechingón - Sanavirón"),
                    ("corundi", "Corundí"),
                    ("diaguita", "Diaguita"),
                    ("diaguita_cacano", "Diaguita (Cacano)"),
                    ("diaguita_calchaqui", "Diaguita Calchaquí"),
                    (
                        "diaguita_calchaqui_wichi_lule",
                        "Diaguita Calchaquí - Wichí - Lule",
                    ),
                    ("fiscara", "Fiscara"),
                    ("guarani", "Guaraní"),
                    ("guarani_chane", "Guaraní - Chané"),
                    ("guaycuru", "Guaycurú"),
                    ("huarpe", "Huarpe"),
                    ("iogys", "Iogys"),
                    ("kolla", "Kolla"),
                    ("kolla_guarani", "Kolla - Guaraní"),
                    ("kolla_wichi_guarani", "Kolla - Wichí - Guaraní"),
                    ("kolla_atacameno", "Kolla Atacameño"),
                    ("lule", "Lule"),
                    ("lule_vilela", "Lule Vilela"),
                    ("mapuche", "Mapuche"),
                    ("mapuche_pehuenche", "Mapuche Pehuenche"),
                    ("mapuche_tehuelche", "Mapuche Tehuelche"),
                    ("mbya_guarani", "Mbya Guaraní"),
                    ("moqoit_mocovi", "Moqoit (Mocoví)"),
                    ("moqoit_mocovi_qom_toba", "Moqoit (Mocoví) - Qom (Toba)"),
                    ("ocloya", "Ocloya"),
                    ("omaguaca", "Omaguaca"),
                    ("pilaga", "Pilagá"),
                    ("qom_toba", "Qom (Toba)"),
                    ("qom_toba_moqoit_mocovi", "Qom (Toba) - Moqoit (Mocoví)"),
                    ("qom_toba_pilaga_wichi", "Qom (Toba) - Pilagá - Wichí"),
                    ("quechua", "Quechua"),
                    ("ranquel", "Ranquel"),
                    ("ranquel_mapuche", "Ranquel - Mapuche"),
                    ("sanaviron", "Sanavirón"),
                    ("selknam_onas", "Selk'Nam (Onas)"),
                    ("sin_dato", "Sin dato"),
                    ("tapiete", "Tapiete"),
                    ("tastil", "Tastil"),
                    ("tehuelche", "Tehuelche"),
                    ("tehuelche_mapuche", "Tehuelche Mapuche"),
                    ("tilian", "Tilián"),
                    ("toara", "Toara"),
                    ("tonokote", "Tonokoté"),
                    ("tupi_guarani", "Tupí Guaraní"),
                    ("vilela", "Vilela"),
                    ("wichi", "Wichí"),
                    ("wichi_chiriguano", "Wichí - Chiriguano"),
                    ("wichi_chorote", "Wichí - Chorote"),
                    ("wichi_guarani", "Wichí - Guaraní"),
                    ("wichi_qom_toba", "Wichí - Qom (Toba)"),
                    ("yagan", "Yagán"),
                ],
                max_length=40,
                null=True,
                verbose_name="Pueblo originario al que pertenece",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="recibe_apoyo_discapacidad",
            field=models.CharField(
                blank=True,
                choices=[("si", "Sí"), ("no", "No"), ("no_sabe", "No sabe")],
                max_length=8,
                null=True,
                verbose_name="¿Recibe actualmente algún tipo de apoyo, tratamiento o acompañamiento?",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="sala_cdi",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no_corresponde", "No corresponde"),
                    ("menores_1_anio", "Menores de 1 año"),
                    ("1_anio", "1 año"),
                    ("2_anios", "2 años"),
                    ("3_anios", "3 años"),
                    ("4_anios", "4 años"),
                    ("multiedad", "Multiedad"),
                ],
                max_length=16,
                null=True,
                verbose_name="Sala (CDI)",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="sexo_registral",
            field=models.CharField(
                blank=True,
                choices=[
                    ("varon", "Varón"),
                    ("mujer", "Mujer"),
                    ("indeterminado", "Indeterminado"),
                ],
                max_length=16,
                null=True,
                verbose_name="Sexo registral",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="subcomponente",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pfpi", "PFPI"),
                    ("egp", "EGP"),
                    ("cdi", "CDI"),
                    ("uaf", "UAF"),
                ],
                max_length=8,
                null=True,
                verbose_name="Subcomponente",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="tiene_cud",
            field=models.CharField(
                blank=True,
                choices=[("si", "Sí"), ("no", "No")],
                max_length=4,
                null=True,
                verbose_name="¿Tiene CUD?",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="tiene_discapacidad",
            field=models.CharField(
                blank=True,
                choices=[("si", "Sí"), ("no", "No"), ("no_sabe", "No sabe")],
                max_length=8,
                null=True,
                verbose_name="¿Tiene alguna discapacidad y/o requiere apoyos específicos?",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="tipo_barrio",
            field=models.CharField(
                blank=True,
                choices=[
                    ("urbano", "Urbano"),
                    ("rural", "Rural"),
                    ("villa", "Villa"),
                    ("asentamiento", "Asentamiento"),
                    ("urbanizacion_informal", "Urbanización informal"),
                ],
                max_length=24,
                null=True,
                verbose_name="Tipo de barrio",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="tipo_contratacion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("relacion_dependencia", "Relación de dependencia"),
                    ("contrato_anual", "Contratación renovable anualmente"),
                    ("contrato_temporal", "Contratación temporal"),
                    ("pasantia", "Pasantía"),
                    ("voluntariado", "Voluntariado"),
                    ("inclusion_social", "Programa de inclusión social"),
                ],
                max_length=32,
                null=True,
                verbose_name="Tipo de contratación",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="tipo_discapacidad",
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name="¿Qué tipo de discapacidad presenta?",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="tipo_documentacion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ninguna", "Ninguna documentación"),
                    (
                        "origen_con_tramite",
                        "Sólo tengo mi documento de origen, pero inicié los trámites de radicación",
                    ),
                    (
                        "origen_sin_tramite",
                        "Sólo tengo mi documento de origen y no inicié ningún trámite de radicación",
                    ),
                    (
                        "res_precaria_migraciones",
                        "Certificado de residencia precaria de Migraciones",
                    ),
                    (
                        "res_precaria_conare",
                        "Certificado de residencia precaria de la CONARE",
                    ),
                    ("dni_temporario", "DNI temporario"),
                    ("res_transitoria", "Residencia transitoria"),
                    ("dni_permanente", "DNI permanente"),
                    ("naturalizacion", "Naturalización / Ciudadanía argentina"),
                ],
                max_length=40,
                null=True,
                verbose_name="¿Con qué tipo de documentación cuenta en Argentina?",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="unidad_funcional",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Unidad funcional (piso, departamento)",
            ),
        ),
        migrations.AlterField(
            model_name="trabajador",
            name="rol",
            field=models.CharField(
                blank=True,
                choices=[
                    ("profesor", "Profesor"),
                    ("director", "Director"),
                    ("administrativo", "Administrativo"),
                ],
                max_length=20,
            ),
        ),
    ]
