# Generated by Django 5.2.14 on 2026-06-12 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centrodeinfancia', '0030_trabajador_anos_trabajo_primera_infancia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NominaCentroInfanciaDerivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(blank=True)),
                ('centro_origen_id', models.IntegerField()),
                ('centro_destino_id', models.IntegerField()),
                ('nomina_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones_destino', to='centrodeinfancia.nominacentroinfancia')),
                ('nomina_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones_origen', to='centrodeinfancia.nominacentroinfancia')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Derivación de nómina CDI',
                'verbose_name_plural': 'Derivaciones de nómina CDI',
                'ordering': ['-fecha'],
            },
        ),
    ]
