# Generated by Django 4.2.27 on 2026-06-12 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("centrodeinfancia", "0031_nomina_derivacion"),
        (
            "centrodeinfancia",
            "0031_nominacentroinfancia_alergias_alimentarias_and_more",
        ),
    ]

    operations = []
