# Generated by Django 4.2.27 on 2026-06-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centrodeinfancia", "0033_nomina_pais_nacionalidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="trabajador",
            name="departamento_contacto",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Departamento"
            ),
        ),
    ]
