# Generated by Django 4.2.27 on 2026-07-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centrodeinfancia", "0039_alter_trabajador_es_interprete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trabajador",
            name="campos_verificados_renaper",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
