# Generated by Django 4.2.27 on 2026-07-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centrodeinfancia", "0040_trabajador_campos_verificados_renaper"),
    ]

    operations = [
        migrations.AddField(
            model_name="trabajador",
            name="fecha_actualizacion",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha de actualización del personal",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="funcion_pfpi",
            field=models.CharField(
                blank=True,
                choices=[
                    ("direccion", "Dirección"),
                    ("simepi", "SIMEPI"),
                    ("auditoria", "Auditoría"),
                    ("administracion", "Administración"),
                    ("control", "Control"),
                    ("finanzas", "Finanzas"),
                    ("tecnico_primera_infancia", "Técnico de primera infancia"),
                ],
                max_length=32,
                null=True,
                verbose_name="Función (PFPI)",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="funcion_uaf",
            field=models.CharField(
                blank=True,
                choices=[
                    ("coordinador_uaf", "Coordinador UAF"),
                    ("supervisor", "Supervisor/a"),
                    ("tutor", "Tutor/a"),
                    ("facilitador", "Facilitador/a"),
                    ("orientador", "Orientador/a"),
                    ("otro", "Otro"),
                ],
                max_length=32,
                null=True,
                verbose_name="Función (UAF)",
            ),
        ),
        migrations.AddField(
            model_name="trabajador",
            name="registro_tipo",
            field=models.CharField(
                blank=True,
                choices=[("alta", "Alta"), ("baja", "Baja"), ("edicion", "Edición")],
                max_length=16,
                null=True,
                verbose_name="Tipo de registro",
            ),
        ),
    ]
