# Generated by Django 4.2.27 on 2026-07-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centrodeinfancia", "0041_trabajador_fecha_actualizacion_and_more"),
    ]

    # Mantiene el estado histórico para que 0043 pueda restaurar físicamente la
    # columna en entornos donde esta migración ya se aplicó, sin convertir datos
    # legacy en los entornos que todavía deben cruzar 0042.
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="nominacentroinfancia",
                    name="talla",
                    field=models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
            ],
        ),
    ]
