# Generated by Django 4.2.27 on 2026-07-24 14:01

from decimal import Decimal, InvalidOperation

from django.db import migrations, models


MAX_TALLA_DECIMAL = Decimal("9999.9")
UN_DECIMAL = Decimal("0.1")


def normalizar_talla_legacy(valor):
    """Devuelve una representación Decimal(5, 1) sin pérdida de precisión."""

    texto = str(valor).strip()
    if not texto:
        return None

    try:
        decimal = Decimal(texto.replace(",", "."))
    except InvalidOperation as exc:
        raise ValueError("no es un número decimal") from exc

    if not decimal.is_finite():
        raise ValueError("no es un número decimal finito")
    if abs(decimal) > MAX_TALLA_DECIMAL:
        raise ValueError("supera la capacidad de Decimal(5, 1)")

    normalizado = decimal.quantize(UN_DECIMAL)
    if decimal != normalizado:
        raise ValueError("tiene más de un decimal")
    return format(normalizado, "f")


def preparar_tallas_legacy(apps, schema_editor):
    """Normaliza sólo valores convertibles antes de cambiar el tipo de columna.

    Si hay valores ambiguos, se aborta antes del `AlterField` para que el deploy no
    convierta, trunque ni pierda datos silenciosamente.
    """

    NominaCentroInfancia = apps.get_model("centrodeinfancia", "NominaCentroInfancia")
    actualizaciones = []
    invalidos = []

    for nomina in NominaCentroInfancia.objects.exclude(talla__isnull=True).iterator():
        try:
            talla_normalizada = normalizar_talla_legacy(nomina.talla)
        except ValueError as exc:
            invalidos.append(f"id={nomina.pk} ({exc})")
            continue

        if talla_normalizada != nomina.talla:
            nomina.talla = talla_normalizada
            actualizaciones.append(nomina)

    if invalidos:
        muestra = ", ".join(invalidos[:10])
        raise RuntimeError(
            "No se puede convertir NominaCentroInfancia.talla a Decimal(5, 1). "
            f"Corrija los valores históricos antes de reintentar la migración: {muestra}."
        )

    NominaCentroInfancia.objects.bulk_update(actualizaciones, ["talla"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("centrodeinfancia", "0041_trabajador_fecha_actualizacion_and_more"),
    ]

    operations = [
        migrations.RunPython(
            preparar_tallas_legacy,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="nominacentroinfancia",
            name="talla",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
    ]
