# Generated by Django 4.2.27 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centrodeinfancia", "0042_alter_nominacentroinfancia_talla"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nominacentroinfancia",
            name="talla",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
