# Generated by Django 4.2.27 on 2026-08-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("centrodeinfancia", "0043_revert_nominacentroinfancia_talla_to_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="nominacentroinfancia",
            name="departamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nominas_centros_infancia",
                to="centrodeinfancia.departamentoipi",
                verbose_name="Departamento (jurisdicción)",
            ),
        ),
    ]
