# Generated by Django 4.2.27 on 2026-08-28

from datetime import date

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centrodeinfancia", "0045_centrodeinfancia_dni_cuil_referente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="centrodeinfancia",
            name="fecha_inicio",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[MinValueValidator(date(1900, 1, 1))],
                verbose_name="Año de inicio de actividades del CDI",
            ),
        ),
    ]
