# Generated by Django 5.2.16 on 2026-08-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("centrodeinfancia", "0046_alter_centrodeinfancia_fecha_inicio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulariocdi",
            name="realiza_acciones_acompanamiento_vulneracion_derechos",
            field=models.CharField(
                blank=True,
                choices=[("si", "Si"), ("no", "No"), ("ns_nc", "No sabe")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formulariocdi",
            name="realiza_acciones_promocion_acceso_derechos",
            field=models.CharField(
                blank=True,
                choices=[("si", "Si"), ("no", "No"), ("ns_nc", "No sabe")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formulariocdi",
            name="tiene_personal_entrada_salida",
            field=models.CharField(
                blank=True,
                choices=[("si", "Si"), ("no", "No"), ("ns_nc", "No sabe")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="formulariocdi",
            name="tiene_registro_lista_espera",
            field=models.CharField(
                blank=True,
                choices=[("si", "Si"), ("no", "No"), ("ns_nc", "No sabe")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nominacentroinfancia",
            name="discapacidad_tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("motora", "Motora"),
                    ("visual", "Visual"),
                    ("auditiva", "Auditiva"),
                    ("intelectual", "Intelectual"),
                    ("mental", "Mental"),
                    ("visceral", "Visceral"),
                    ("multiple", "Múltiple"),
                    ("ns_nc", "No sabe"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nominacentroinfancia",
            name="habla_lengua_originaria_hogar",
            field=models.CharField(
                blank=True,
                choices=[("si", "Si"), ("no", "No"), ("ns_nc", "No sabe")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nominacentroinfancia",
            name="pertenece_pueblo_originario",
            field=models.CharField(
                blank=True,
                choices=[("si", "Si"), ("no", "No"), ("ns_nc", "No sabe")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nominacentroinfancia",
            name="responsable_legal_1_percibe_alimenta",
            field=models.CharField(
                blank=True,
                choices=[("si", "Si"), ("no", "No"), ("ns_nc", "No sabe")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nominacentroinfancia",
            name="responsable_legal_1_percibe_auh",
            field=models.CharField(
                blank=True,
                choices=[("si", "Si"), ("no", "No"), ("ns_nc", "No sabe")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nominacentroinfancia",
            name="responsable_legal_2_percibe_alimenta",
            field=models.CharField(
                blank=True,
                choices=[("si", "Si"), ("no", "No"), ("ns_nc", "No sabe")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nominacentroinfancia",
            name="responsable_legal_2_percibe_auh",
            field=models.CharField(
                blank=True,
                choices=[("si", "Si"), ("no", "No"), ("ns_nc", "No sabe")],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="nominacentroinfancia",
            name="tiene_discapacidad",
            field=models.CharField(
                blank=True,
                choices=[("si", "Si"), ("no", "No"), ("ns_nc", "No sabe")],
                max_length=16,
                null=True,
            ),
        ),
    ]
