# Generated by Django 4.2.20 on 2025-06-24 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_move_configuraciones_data"),
        ("ciudadanos", "0002_update_configuraciones_to_core"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ciudadano",
            name="localidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.localidad",
            ),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="municipio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.municipio",
            ),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="provincia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.provincia",
            ),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="sexo",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.sexo"
            ),
        ),
        migrations.AlterField(
            model_name="dimensioneducacion",
            name="localidadInstitucion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.localidad",
                verbose_name="Localidad de la institucion",
            ),
        ),
        migrations.AlterField(
            model_name="dimensioneducacion",
            name="municipioInstitucion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.municipio",
                verbose_name="Municipio de la institucion",
            ),
        ),
        migrations.AlterField(
            model_name="dimensioneducacion",
            name="provinciaInstitucion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.provincia",
                verbose_name="Provincia de la institucion",
            ),
        ),
    ]
