# Generated by Django 4.2.20 on 2025-08-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "ciudadanos",
            "0002_alter_ciudadano_localidad_alter_ciudadano_municipio_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ciudadanoprograma",
            unique_together={("ciudadano", "programas")},
        ),
    ]
