# Generated by Django 4.2.20 on 2025-09-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ciudadanos", "0003_alter_ciudadanoprograma_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ciudadano",
            name="telefono",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="telefono_alternativo",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Telefono Alternativo"
            ),
        ),
    ]
