# Generated by Django 4.2.20 on 2025-09-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ciudadanos", "0005_alter_ciudadano_documento"),
    ]

    operations = [
        migrations.AddField(
            model_name="ciudadano",
            name="demo_centro_familia",
            field=models.BooleanField(
                default=False, verbose_name="Demo Centro de Familia"
            ),
        ),
    ]
