# Generated by Django 4.2.20 on 2025-10-21 21:08

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ciudadanos", "0006_ciudadano_demo_centro_familia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ciudadano",
            name="documento",
            field=models.PositiveBigIntegerField(
                blank=True,
                null=True,
                validators=[MinValueValidator(3000000)],
            ),
        ),
    ]
