# Generated by Django 4.2.27 on 2026-05-07 16:30

import core.soft_delete.base
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


# --- RunPython: 0009_remove_alerta_categoria_... ---

def migrate_nacionalidades(apps, schema_editor):
    connection = schema_editor.connection
    quote = schema_editor.quote_name

    with connection.cursor() as cursor:
        existing_tables = set(connection.introspection.table_names(cursor))

    def table_exists(name: str) -> bool:
        return name in existing_tables

    if not table_exists("ciudadanos_nacionalidad"):
        return

    if not table_exists("core_nacionalidad"):
        if connection.vendor == "sqlite":
            schema_editor.execute(
                f"""
                CREATE TABLE {quote("core_nacionalidad")} (
                    {quote("id")} integer PRIMARY KEY AUTOINCREMENT,
                    {quote("nacionalidad")} varchar(50) NOT NULL
                );
                """
            )
        else:
            schema_editor.execute(
                f"""
                CREATE TABLE {quote("core_nacionalidad")} (
                    {quote("id")} bigint AUTO_INCREMENT PRIMARY KEY,
                    {quote("nacionalidad")} varchar(50) NOT NULL
                );
                """
            )

    if connection.vendor == "sqlite":
        schema_editor.execute(
            """
            INSERT OR REPLACE INTO core_nacionalidad (id, nacionalidad)
            SELECT id, nacionalidad FROM ciudadanos_nacionalidad;
            """
        )
    else:
        schema_editor.execute(
            """
            INSERT INTO core_nacionalidad (id, nacionalidad)
            SELECT id, nacionalidad FROM ciudadanos_nacionalidad
            ON DUPLICATE KEY UPDATE nacionalidad = VALUES(nacionalidad);
            """
        )

    if connection.vendor == "mysql":
        with connection.cursor() as cursor:
            cursor.execute("SELECT IFNULL(MAX(id), 0) + 1 FROM core_nacionalidad;")
            next_id = cursor.fetchone()
        if next_id:
            schema_editor.execute(
                f"ALTER TABLE {quote('core_nacionalidad')} AUTO_INCREMENT = {int(next_id[0])}"
            )


def safe_cleanup(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor == "sqlite":
        return
    quote = schema_editor.quote_name

    def table_exists(name: str) -> bool:
        with connection.cursor() as cursor:
            return name in set(connection.introspection.table_names(cursor))

    def column_exists(table: str, column: str) -> bool:
        if not table_exists(table):
            return False
        with connection.cursor() as cursor:
            return column in [col.name for col in connection.introspection.get_table_description(cursor, table)]

    def drop_column_if_exists(table: str, column: str) -> None:
        if column_exists(table, column):
            schema_editor.execute(f"ALTER TABLE {quote(table)} DROP COLUMN {quote(column)}")

    def add_column_if_missing(table: str, column: str, definition_sql: str) -> None:
        if table_exists(table) and not column_exists(table, column):
            schema_editor.execute(f"ALTER TABLE {quote(table)} ADD COLUMN {definition_sql}")

    def drop_index_if_exists(table: str, index_name: str) -> None:
        if not table_exists(table):
            return
        with connection.cursor() as cursor:
            constraints = connection.introspection.get_constraints(cursor, table)
        if index_name in constraints:
            schema_editor.execute(f"DROP INDEX {quote(index_name)} ON {quote(table)}")

    def add_index_if_missing(table: str, index_name: str, columns: list) -> None:
        if not table_exists(table):
            return
        with connection.cursor() as cursor:
            constraints = connection.introspection.get_constraints(cursor, table)
        if index_name not in constraints:
            cols_sql = ", ".join(quote(col) for col in columns)
            schema_editor.execute(f"CREATE INDEX {quote(index_name)} ON {quote(table)} ({cols_sql})")

    def drop_fk_constraints(table: str, column: str) -> None:
        if not table_exists(table):
            return
        with connection.cursor() as cursor:
            constraints = connection.introspection.get_constraints(cursor, table)
        for name, details in constraints.items():
            if column in details.get("columns", []) and details.get("foreign_key"):
                schema_editor.execute(f"ALTER TABLE {quote(table)} DROP FOREIGN KEY {quote(name)}")

    def drop_unique_constraints(table: str, column: str) -> None:
        if not table_exists(table):
            return
        with connection.cursor() as cursor:
            constraints = connection.introspection.get_constraints(cursor, table)
        for name, details in constraints.items():
            if details.get("unique") and column in details.get("columns", []):
                schema_editor.execute(f"ALTER TABLE {quote(table)} DROP INDEX {quote(name)}")

    def migrate_tipo_documento() -> None:
        table = "ciudadanos_ciudadano"
        fk_col = "tipo_documento_id"
        text_col = "tipo_documento"

        if not table_exists(table):
            return

        has_fk_col = column_exists(table, fk_col)
        has_text_col = column_exists(table, text_col)

        if not has_fk_col and has_text_col:
            return

        add_column_if_missing(table, text_col, f"{quote(text_col)} VARCHAR(20) NOT NULL DEFAULT 'DNI'")

        if table_exists("ciudadanos_tipodocumento"):
            schema_editor.execute(
                f"""
                UPDATE {quote(table)} c
                LEFT JOIN {quote("ciudadanos_tipodocumento")} t ON c.{quote(fk_col)} = t.{quote("id")}
                SET c.{quote(text_col)} = COALESCE(NULLIF(t.{quote("tipo")}, ''), 'DNI');
                """
            )
        else:
            schema_editor.execute(
                f"""
                UPDATE {quote(table)}
                SET {quote(text_col)} = 'DNI'
                WHERE {quote(text_col)} IS NULL OR {quote(text_col)} = '';
                """
            )

        drop_fk_constraints(table, fk_col)
        drop_unique_constraints(table, fk_col)
        drop_column_if_exists(table, fk_col)

    with connection.cursor() as cursor:
        existing_tables = set(connection.introspection.table_names(cursor))

    keep_tables = {
        "ciudadanos_ciudadano",
        "ciudadanos_grupofamiliar",
        "ciudadanos_ciudadanoprograma",
        "ciudadanos_historialciudadanoprogramas",
    }
    migrate_tipo_documento()
    drop_tables = [
        table
        for table in existing_tables
        if table.startswith("ciudadanos_") and table not in keep_tables
    ]

    if drop_tables:
        schema_editor.execute("SET FOREIGN_KEY_CHECKS=0;")
        for table in drop_tables:
            schema_editor.execute(f"DROP TABLE IF EXISTS {quote(table)}")
        schema_editor.execute("SET FOREIGN_KEY_CHECKS=1;")

    drop_ciudadano_columns = [
        "circuito_id", "demo_centro_familia_id", "escalera_manzana",
        "estado_id", "estado_civil_id", "latitud", "longitud", "torre_pasillo",
    ]
    if drop_ciudadano_columns:
        schema_editor.execute("SET FOREIGN_KEY_CHECKS=0;")
        for column in drop_ciudadano_columns:
            drop_fk_constraints("ciudadanos_ciudadano", column)
            drop_column_if_exists("ciudadanos_ciudadano", column)
        schema_editor.execute("SET FOREIGN_KEY_CHECKS=1;")

    add_column_if_missing("ciudadanos_ciudadano", "activo", "activo BOOL NOT NULL DEFAULT 1")
    add_column_if_missing("ciudadanos_ciudadano", "barrio", "barrio VARCHAR(100) NULL")

    drop_index_if_exists("ciudadanos_ciudadano", "ciudadanos__apellid_8f0c3b_idx")
    drop_index_if_exists("ciudadanos_ciudadano", "ciudadanos__fecha_n_aa8772_idx")
    drop_index_if_exists("ciudadanos_ciudadano", "ciudadanos__observa_517ba3_idx")
    add_index_if_missing("ciudadanos_ciudadano", "ciudadanos__apellid_02f758_idx", ["apellido", "nombre"])

    drop_column_if_exists("ciudadanos_grupofamiliar", "vinculo_inverso")
    add_column_if_missing("ciudadanos_grupofamiliar", "creado", "creado DATETIME(6) NULL")
    add_column_if_missing("ciudadanos_grupofamiliar", "modificado", "modificado DATETIME(6) NULL")
    schema_editor.execute(
        f"UPDATE {quote('ciudadanos_grupofamiliar')} SET {quote('creado')} = COALESCE({quote('creado')}, CURRENT_TIMESTAMP(6)), {quote('modificado')} = COALESCE({quote('modificado')}, CURRENT_TIMESTAMP(6))"
    )
    add_index_if_missing("ciudadanos_grupofamiliar", "ciudadanos__ciudada_0b736a_idx", ["ciudadano_1_id"])
    add_index_if_missing("ciudadanos_grupofamiliar", "ciudadanos__ciudada_547f88_idx", ["ciudadano_2_id"])


# --- RunPython: 0012_fix_ciudadano_datetime_fields ---

def ensure_datetime_columns(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor != "mysql":
        return

    quote = schema_editor.quote_name
    table = quote("ciudadanos_ciudadano")
    created_col = quote("creado")
    modified_col = quote("modificado")

    with connection.cursor() as cursor:
        cursor.execute(
            f"""
            UPDATE {table}
            SET {created_col} = COALESCE({created_col}, CURRENT_TIMESTAMP(6)),
                {modified_col} = COALESCE({modified_col}, CURRENT_TIMESTAMP(6));
            """
        )
        cursor.execute(
            f"""
            ALTER TABLE {table}
            MODIFY {created_col} DATETIME(6) NOT NULL,
            MODIFY {modified_col} DATETIME(6) NOT NULL;
            """
        )


# --- RunPython: 0013_fix_grupofamiliar_text_fields ---

def ensure_grupofamiliar_text_fields(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor != "mysql":
        return

    quote = schema_editor.quote_name

    def table_exists(name: str) -> bool:
        with connection.cursor() as cursor:
            return name in set(connection.introspection.table_names(cursor))

    def column_exists(table: str, column: str) -> bool:
        if not table_exists(table):
            return False
        with connection.cursor() as cursor:
            return column in [col.name for col in connection.introspection.get_table_description(cursor, table)]

    def add_column_if_missing(table: str, column: str, definition_sql: str) -> None:
        if table_exists(table) and not column_exists(table, column):
            schema_editor.execute(f"ALTER TABLE {quote(table)} ADD COLUMN {definition_sql}")

    def drop_fk_constraints(table: str, column: str) -> None:
        if not table_exists(table):
            return
        with connection.cursor() as cursor:
            constraints = connection.introspection.get_constraints(cursor, table)
        for name, details in constraints.items():
            if column in details.get("columns", []) and details.get("foreign_key"):
                schema_editor.execute(f"ALTER TABLE {quote(table)} DROP FOREIGN KEY {quote(name)}")

    def drop_unique_constraints(table: str, column: str) -> None:
        if not table_exists(table):
            return
        with connection.cursor() as cursor:
            constraints = connection.introspection.get_constraints(cursor, table)
        for name, details in constraints.items():
            if details.get("unique") and column in details.get("columns", []):
                schema_editor.execute(f"ALTER TABLE {quote(table)} DROP INDEX {quote(name)}")

    def drop_column_if_exists(table: str, column: str) -> None:
        if table_exists(table) and column_exists(table, column):
            schema_editor.execute(f"ALTER TABLE {quote(table)} DROP COLUMN {quote(column)}")

    table = "ciudadanos_grupofamiliar"

    add_column_if_missing(table, "vinculo", f"{quote('vinculo')} VARCHAR(20) NULL")
    add_column_if_missing(table, "estado_relacion", f"{quote('estado_relacion')} VARCHAR(20) NULL")

    if column_exists(table, "vinculo") and column_exists(table, "vinculo_id"):
        if table_exists("ciudadanos_vinculofamiliar"):
            schema_editor.execute(
                f"""
                UPDATE {quote(table)} gf
                LEFT JOIN {quote("ciudadanos_vinculofamiliar")} vf
                    ON gf.{quote("vinculo_id")} = vf.{quote("id")}
                SET gf.{quote("vinculo")} = COALESCE(gf.{quote("vinculo")}, vf.{quote("vinculo")})
                WHERE gf.{quote("vinculo")} IS NULL;
                """
            )
        drop_fk_constraints(table, "vinculo_id")
        drop_unique_constraints(table, "vinculo_id")
        drop_column_if_exists(table, "vinculo_id")

    if column_exists(table, "estado_relacion") and column_exists(table, "estado_relacion_id"):
        if table_exists("ciudadanos_estadorelacion"):
            schema_editor.execute(
                f"""
                UPDATE {quote(table)} gf
                LEFT JOIN {quote("ciudadanos_estadorelacion")} er
                    ON gf.{quote("estado_relacion_id")} = er.{quote("id")}
                SET gf.{quote("estado_relacion")} = COALESCE(gf.{quote("estado_relacion")}, er.{quote("estado")})
                WHERE gf.{quote("estado_relacion")} IS NULL;
                """
            )
        drop_fk_constraints(table, "estado_relacion_id")
        drop_unique_constraints(table, "estado_relacion_id")
        drop_column_if_exists(table, "estado_relacion_id")


# --- RunPython: 0014_remove_ciudadano_estado_column ---

def drop_estado_column(apps, schema_editor):
    connection = schema_editor.connection
    quote = schema_editor.quote_name
    table = "ciudadanos_ciudadano"
    estado_col = "estado"
    activo_col = "activo"

    with connection.cursor() as cursor:
        existing_tables = set(connection.introspection.table_names(cursor))

    if table not in existing_tables:
        return

    def column_exists(column: str) -> bool:
        with connection.cursor() as cursor:
            columns = connection.introspection.get_table_description(cursor, table)
        return any(col.name == column for col in columns)

    if not column_exists(estado_col):
        return

    if not column_exists(activo_col):
        schema_editor.execute(
            f"ALTER TABLE {quote(table)} ADD COLUMN {quote(activo_col)} BOOL NOT NULL DEFAULT 1"
        )

    schema_editor.execute(
        f"""
        UPDATE {quote(table)}
        SET {quote(activo_col)} = {quote(estado_col)}
        WHERE {quote(estado_col)} IS NOT NULL
        """
    )
    schema_editor.execute(f"ALTER TABLE {quote(table)} DROP COLUMN {quote(estado_col)}")


# --- RunPython: 0015_cleanup_ciudadano_legacy_columns ---

def drop_legacy_columns(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor == "sqlite":
        return
    quote = schema_editor.quote_name
    table = "ciudadanos_ciudadano"

    def table_exists(name: str) -> bool:
        with connection.cursor() as cursor:
            return name in set(connection.introspection.table_names(cursor))

    if not table_exists(table):
        return

    def column_exists(column: str) -> bool:
        with connection.cursor() as cursor:
            columns = connection.introspection.get_table_description(cursor, table)
        return any(col.name == column for col in columns)

    def drop_fk_constraints(column: str) -> None:
        with connection.cursor() as cursor:
            constraints = connection.introspection.get_constraints(cursor, table)
        for name, details in constraints.items():
            if column in details.get("columns", []) and details.get("foreign_key"):
                schema_editor.execute(f"ALTER TABLE {quote(table)} DROP FOREIGN KEY {quote(name)}")

    def drop_column_if_exists(column: str) -> None:
        if not column_exists(column):
            return
        drop_fk_constraints(column)
        schema_editor.execute(f"ALTER TABLE {quote(table)} DROP COLUMN {quote(column)}")

    legacy_columns = [
        "demo_centro_familia", "demo_centro_familia_id", "estado", "estado_id",
        "circuito_id", "escalera_manzana", "torre_pasillo",
    ]
    for column in legacy_columns:
        drop_column_if_exists(column)


# --- RunPython: 0016_add_ciudadano_etapa1_fields ---

def add_ciudadano_fields(apps, schema_editor):
    Ciudadano = apps.get_model("ciudadanos", "Ciudadano")
    table = Ciudadano._meta.db_table
    connection = schema_editor.connection

    def column_exists(name: str) -> bool:
        with connection.cursor() as cursor:
            columns = connection.introspection.get_table_description(cursor, table)
        return any(col.name == name for col in columns)

    fields = [
        ("latitud", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
        ("longitud", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
        ("estado_civil", models.CharField(blank=True, choices=[("soltero", "Soltero/a"), ("casado", "Casado/a"), ("divorciado", "Divorciado/a"), ("viudo", "Viudo/a"), ("union_convivencial", "Unión convivencial")], max_length=20, null=True)),
        ("cuil_cuit", models.CharField(blank=True, max_length=13, null=True)),
        ("origen_dato", models.CharField(choices=[("anses", "ANSES"), ("renaper", "RENAPER"), ("manual", "Carga Manual"), ("migracion", "Migración")], default="manual", max_length=20)),
    ]

    for name, field in fields:
        if column_exists(name):
            continue
        field.set_attributes_from_name(name)
        field.model = Ciudadano
        schema_editor.add_field(Ciudadano, field)


# --- RunPython: 0021_ensure_ciudadano_geo_columns ---

def ensure_ciudadano_geo_columns(apps, schema_editor):
    connection = schema_editor.connection
    Ciudadano = apps.get_model("ciudadanos", "Ciudadano")
    table = Ciudadano._meta.db_table

    with connection.cursor() as cursor:
        columns = {col.name for col in connection.introspection.get_table_description(cursor, table)}

    for field_name in ("latitud", "longitud", "estado_civil", "cuil_cuit", "origen_dato"):
        if field_name in columns:
            continue
        schema_editor.add_field(Ciudadano, Ciudadano._meta.get_field(field_name))


class Migration(migrations.Migration):

    replaces = [('ciudadanos', '0009_remove_alerta_categoria_remove_archivo_ciudadano_and_more'), ('ciudadanos', '0010_historialciudadanoprogramas_ciudadanoprograma'), ('ciudadanos', '0011_alter_ciudadanoprograma_fecha_creado'), ('ciudadanos', '0012_fix_ciudadano_datetime_fields'), ('ciudadanos', '0013_fix_grupofamiliar_text_fields'), ('ciudadanos', '0014_remove_ciudadano_estado_column'), ('ciudadanos', '0015_cleanup_ciudadano_legacy_columns'), ('ciudadanos', '0016_add_ciudadano_etapa1_fields'), ('ciudadanos', '0017_programatransferencia'), ('ciudadanos', '0018_historialtransferencia'), ('ciudadanos', '0019_interaccion'), ('ciudadanos', '0020_remove_historialtransferencia_unique_historial_ciudadano_mes_anio_and_more'), ('ciudadanos', '0021_ensure_ciudadano_geo_columns'), ('ciudadanos', '0022_alter_ciudadano_managers_and_more'), ('ciudadanos', '0027_alter_ciudadano_telefono_longitud'), ('ciudadanos', '0023_ciudadano_identidad_fase1'), ('ciudadanos', '0024_ciudadano_revision_identidad_permission'), ('ciudadanos', '0025_alter_ciudadano_fecha_nacimiento_nullable'), ('ciudadanos', '0023_optimize_listado_ciudadanos_indexes'), ('ciudadanos', '0026_merge_0023_optimize_listado_ciudadanos_indexes_0025_alter_ciudadano_fecha_nacimiento_nullable'), ('ciudadanos', '0028_merge_20260505_1126')]

    dependencies = [
        ('core', '0001_squashed_0007'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ciudadanos', '0001_squashed_0008'),
        ('comedores', '0001_squashed_0023'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    code=migrate_nacionalidades,
                    reverse_code=migrations.RunPython.noop,
                ),
                migrations.AlterField(
                    model_name='ciudadano',
                    name='nacionalidad',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nacionalidad'),
                ),
                migrations.AlterField(
                    model_name='ciudadanoprograma',
                    name='programas',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programa_ciudadano', to='core.programa'),
                ),
                migrations.AlterField(
                    model_name='historialciudadanoprogramas',
                    name='programa',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hist_prog_ciudadano', to='core.programa'),
                ),
                migrations.RunPython(
                    code=safe_cleanup,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='alerta',
                    name='categoria',
                ),
                migrations.RemoveField(
                    model_name='archivo',
                    name='ciudadano',
                ),
                migrations.RemoveField(
                    model_name='categoriaalerta',
                    name='dimension',
                ),
                migrations.DeleteModel(
                    name='Condicion',
                ),
                migrations.RemoveField(
                    model_name='derivacion',
                    name='alertas',
                ),
                migrations.RemoveField(
                    model_name='derivacion',
                    name='ciudadano',
                ),
                migrations.RemoveField(
                    model_name='derivacion',
                    name='estado',
                ),
                migrations.RemoveField(
                    model_name='derivacion',
                    name='importancia',
                ),
                migrations.RemoveField(
                    model_name='derivacion',
                    name='motivo_rechazo',
                ),
                migrations.RemoveField(
                    model_name='derivacion',
                    name='organismo',
                ),
                migrations.RemoveField(
                    model_name='derivacion',
                    name='programa',
                ),
                migrations.RemoveField(
                    model_name='derivacion',
                    name='programa_solicitante',
                ),
                migrations.RemoveField(
                    model_name='derivacion',
                    name='usuario',
                ),
                migrations.RemoveField(
                    model_name='dimensioneconomia',
                    name='ciudadano',
                ),
                migrations.RemoveField(
                    model_name='dimensioneconomia',
                    name='planes',
                ),
                migrations.RemoveField(
                    model_name='dimensioneducacion',
                    name='area_curso',
                ),
                migrations.RemoveField(
                    model_name='dimensioneducacion',
                    name='area_oficio',
                ),
                migrations.RemoveField(
                    model_name='dimensioneducacion',
                    name='asiste_escuela',
                ),
                migrations.RemoveField(
                    model_name='dimensioneducacion',
                    name='ciclo',
                ),
                migrations.RemoveField(
                    model_name='dimensioneducacion',
                    name='ciudadano',
                ),
                migrations.RemoveField(
                    model_name='dimensioneducacion',
                    name='estado_nivel',
                ),
                migrations.RemoveField(
                    model_name='dimensioneducacion',
                    name='gestion',
                ),
                migrations.RemoveField(
                    model_name='dimensioneducacion',
                    name='grado',
                ),
                migrations.RemoveField(
                    model_name='dimensioneducacion',
                    name='institucion',
                ),
                migrations.RemoveField(
                    model_name='dimensioneducacion',
                    name='localidadInstitucion',
                ),
                migrations.RemoveField(
                    model_name='dimensioneducacion',
                    name='max_nivel',
                ),
                migrations.RemoveField(
                    model_name='dimensioneducacion',
                    name='municipioInstitucion',
                ),
                migrations.RemoveField(
                    model_name='dimensioneducacion',
                    name='nivel_incompleto',
                ),
                migrations.RemoveField(
                    model_name='dimensioneducacion',
                    name='provinciaInstitucion',
                ),
                migrations.RemoveField(
                    model_name='dimensioneducacion',
                    name='sin_educacion_formal',
                ),
                migrations.RemoveField(
                    model_name='dimensioneducacion',
                    name='turno',
                ),
                migrations.RemoveField(
                    model_name='dimensionfamilia',
                    name='ciudadano',
                ),
                migrations.RemoveField(
                    model_name='dimensionsalud',
                    name='ciudadano',
                ),
                migrations.RemoveField(
                    model_name='dimensionsalud',
                    name='frecuencia_controles_medicos',
                ),
                migrations.RemoveField(
                    model_name='dimensionsalud',
                    name='lugares_atencion',
                ),
                migrations.RemoveField(
                    model_name='dimensiontrabajo',
                    name='Tiempobusqueda_laboral',
                ),
                migrations.RemoveField(
                    model_name='dimensiontrabajo',
                    name='actividadRealizadaComo',
                ),
                migrations.RemoveField(
                    model_name='dimensiontrabajo',
                    name='aportesJubilacion',
                ),
                migrations.RemoveField(
                    model_name='dimensiontrabajo',
                    name='ciudadano',
                ),
                migrations.RemoveField(
                    model_name='dimensiontrabajo',
                    name='duracionTrabajo',
                ),
                migrations.RemoveField(
                    model_name='dimensiontrabajo',
                    name='modo_contratacion',
                ),
                migrations.RemoveField(
                    model_name='dimensiontrabajo',
                    name='nobusqueda_laboral',
                ),
                migrations.RemoveField(
                    model_name='dimensionvivienda',
                    name='agua',
                ),
                migrations.RemoveField(
                    model_name='dimensionvivienda',
                    name='cant_ambientes',
                ),
                migrations.RemoveField(
                    model_name='dimensionvivienda',
                    name='ciudadano',
                ),
                migrations.RemoveField(
                    model_name='dimensionvivienda',
                    name='desague',
                ),
                migrations.RemoveField(
                    model_name='dimensionvivienda',
                    name='gas',
                ),
                migrations.RemoveField(
                    model_name='dimensionvivienda',
                    name='hay_banio',
                ),
                migrations.RemoveField(
                    model_name='dimensionvivienda',
                    name='material',
                ),
                migrations.RemoveField(
                    model_name='dimensionvivienda',
                    name='pisos',
                ),
                migrations.RemoveField(
                    model_name='dimensionvivienda',
                    name='posesion',
                ),
                migrations.RemoveField(
                    model_name='dimensionvivienda',
                    name='techos',
                ),
                migrations.RemoveField(
                    model_name='dimensionvivienda',
                    name='tipo',
                ),
                migrations.RemoveField(
                    model_name='dimensionvivienda',
                    name='ubicacion_vivienda',
                ),
                migrations.RemoveField(
                    model_name='grupohogar',
                    name='ciudadano_1Hogar',
                ),
                migrations.RemoveField(
                    model_name='grupohogar',
                    name='ciudadano_2Hogar',
                ),
                migrations.RemoveField(
                    model_name='grupohogar',
                    name='estado_relacion',
                ),
                migrations.RemoveField(
                    model_name='historialalerta',
                    name='alerta',
                ),
                migrations.RemoveField(
                    model_name='historialalerta',
                    name='ciudadano',
                ),
                migrations.RemoveField(
                    model_name='historialalerta',
                    name='creada_por',
                ),
                migrations.RemoveField(
                    model_name='historialalerta',
                    name='eliminada_por',
                ),
                migrations.RemoveField(
                    model_name='intervencion',
                    name='ciudadano',
                ),
                migrations.RemoveField(
                    model_name='intervencion',
                    name='direccion',
                ),
                migrations.RemoveField(
                    model_name='intervencion',
                    name='estado',
                ),
                migrations.RemoveField(
                    model_name='intervencion',
                    name='subintervencion',
                ),
                migrations.RemoveField(
                    model_name='intervencion',
                    name='tipo_intervencion',
                ),
                migrations.RemoveField(
                    model_name='intervencion',
                    name='usuario',
                ),
                migrations.RemoveField(
                    model_name='llamado',
                    name='ciudadano',
                ),
                migrations.RemoveField(
                    model_name='llamado',
                    name='estado',
                ),
                migrations.RemoveField(
                    model_name='llamado',
                    name='programas_llamados',
                ),
                migrations.RemoveField(
                    model_name='llamado',
                    name='subtipo_llamado',
                ),
                migrations.RemoveField(
                    model_name='llamado',
                    name='tipo_llamado',
                ),
                migrations.RemoveField(
                    model_name='llamado',
                    name='usuario',
                ),
                migrations.RemoveField(
                    model_name='organismo',
                    name='localidad',
                ),
                migrations.RemoveField(
                    model_name='organismo',
                    name='tipo',
                ),
                migrations.RemoveField(
                    model_name='plansocial',
                    name='jurisdiccion',
                ),
                migrations.RemoveField(
                    model_name='programa',
                    name='subsecretaria',
                ),
                migrations.RemoveField(
                    model_name='subintervencion',
                    name='subintervencion',
                ),
                migrations.RemoveField(
                    model_name='subsecretarias',
                    name='secretaria',
                ),
                migrations.RemoveField(
                    model_name='subtipollamado',
                    name='tipo_llamado',
                ),
                migrations.RemoveField(
                    model_name='tipollamado',
                    name='programas_llamados',
                ),
                migrations.AlterModelOptions(
                    name='ciudadano',
                    options={'ordering': ['apellido', 'nombre']},
                ),
                migrations.AlterModelOptions(
                    name='grupofamiliar',
                    options={'ordering': ['ciudadano_1', 'ciudadano_2']},
                ),
                migrations.RemoveIndex(
                    model_name='ciudadano',
                    name='ciudadanos__apellid_8f0c3b_idx',
                ),
                migrations.RemoveIndex(
                    model_name='ciudadano',
                    name='ciudadanos__fecha_n_aa8772_idx',
                ),
                migrations.RemoveIndex(
                    model_name='ciudadano',
                    name='ciudadanos__observa_517ba3_idx',
                ),
                migrations.RemoveIndex(
                    model_name='grupofamiliar',
                    name='ciudadanos__ciudada_0b736a_idx',
                ),
                migrations.RemoveIndex(
                    model_name='grupofamiliar',
                    name='ciudadanos__ciudada_547f88_idx',
                ),
                migrations.RemoveField(
                    model_name='ciudadano',
                    name='alertas',
                ),
                migrations.RemoveField(
                    model_name='ciudadano',
                    name='circuito',
                ),
                migrations.RemoveField(
                    model_name='ciudadano',
                    name='demo_centro_familia',
                ),
                migrations.RemoveField(
                    model_name='ciudadano',
                    name='escalera_manzana',
                ),
                migrations.RemoveField(
                    model_name='ciudadano',
                    name='estado',
                ),
                migrations.RemoveField(
                    model_name='ciudadano',
                    name='estado_civil',
                ),
                migrations.RemoveField(
                    model_name='ciudadano',
                    name='latitud',
                ),
                migrations.RemoveField(
                    model_name='ciudadano',
                    name='longitud',
                ),
                migrations.RemoveField(
                    model_name='ciudadano',
                    name='torre_pasillo',
                ),
                migrations.RemoveField(
                    model_name='grupofamiliar',
                    name='vinculo_inverso',
                ),
                migrations.AddField(
                    model_name='ciudadano',
                    name='activo',
                    field=models.BooleanField(default=True),
                ),
                migrations.AddField(
                    model_name='ciudadano',
                    name='barrio',
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
                migrations.AddField(
                    model_name='grupofamiliar',
                    name='creado',
                    field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                migrations.AddField(
                    model_name='grupofamiliar',
                    name='modificado',
                    field=models.DateTimeField(auto_now=True),
                ),
                migrations.AlterField(
                    model_name='ciudadano',
                    name='altura',
                    field=models.CharField(blank=True, max_length=10, null=True),
                ),
                migrations.AlterField(
                    model_name='ciudadano',
                    name='codigo_postal',
                    field=models.CharField(blank=True, max_length=12, null=True),
                ),
                migrations.AlterField(
                    model_name='ciudadano',
                    name='creado',
                    field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                migrations.AlterField(
                    model_name='ciudadano',
                    name='creado_por',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudadano_creado_por', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AlterField(
                    model_name='ciudadano',
                    name='documento',
                    field=models.PositiveBigIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
                ),
                migrations.AlterField(
                    model_name='ciudadano',
                    name='modificado',
                    field=models.DateTimeField(auto_now=True),
                ),
                migrations.AlterField(
                    model_name='ciudadano',
                    name='modificado_por',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudadano_modificado_por', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AlterField(
                    model_name='ciudadano',
                    name='nacionalidad',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nacionalidad'),
                ),
                migrations.AlterField(
                    model_name='ciudadano',
                    name='observaciones',
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AlterField(
                    model_name='ciudadano',
                    name='piso_departamento',
                    field=models.CharField(blank=True, max_length=50, null=True),
                ),
                migrations.AlterField(
                    model_name='ciudadano',
                    name='sexo',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sexo'),
                ),
                migrations.AlterField(
                    model_name='ciudadano',
                    name='telefono',
                    field=models.CharField(blank=True, max_length=30, null=True),
                ),
                migrations.AlterField(
                    model_name='ciudadano',
                    name='telefono_alternativo',
                    field=models.CharField(blank=True, max_length=30, null=True),
                ),
                migrations.AlterField(
                    model_name='ciudadano',
                    name='tipo_documento',
                    field=models.CharField(choices=[('DNI', 'DNI'), ('CUIT', 'CUIT'), ('PASAPORTE', 'Pasaporte'), ('LE', 'Libreta de enrolamiento')], default='DNI', max_length=20),
                ),
                migrations.AlterField(
                    model_name='grupofamiliar',
                    name='ciudadano_1',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_salientes', to='ciudadanos.ciudadano'),
                ),
                migrations.AlterField(
                    model_name='grupofamiliar',
                    name='ciudadano_2',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_entrantes', to='ciudadanos.ciudadano'),
                ),
                migrations.AlterField(
                    model_name='grupofamiliar',
                    name='conviven',
                    field=models.BooleanField(default=False),
                ),
                migrations.AlterField(
                    model_name='grupofamiliar',
                    name='cuidador_principal',
                    field=models.BooleanField(default=False),
                ),
                migrations.AlterField(
                    model_name='grupofamiliar',
                    name='estado_relacion',
                    field=models.CharField(blank=True, choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('conflictivo', 'Conflictivo')], max_length=20, null=True),
                ),
                migrations.AlterField(
                    model_name='grupofamiliar',
                    name='observaciones',
                    field=models.TextField(blank=True, null=True),
                ),
                migrations.AlterField(
                    model_name='grupofamiliar',
                    name='vinculo',
                    field=models.CharField(blank=True, choices=[('PADRE/MADRE', 'Padre/Madre'), ('HIJO/A', 'Hijo/a'), ('PAREJA', 'Pareja'), ('HERMANO/A', 'Hermano/a'), ('TUTOR/A', 'Tutor/a'), ('OTRO', 'Otro')], max_length=20, null=True),
                ),
                migrations.AddIndex(
                    model_name='ciudadano',
                    index=models.Index(fields=['apellido', 'nombre'], name='ciudadanos__apellid_02f758_idx'),
                ),
                migrations.AddIndex(
                    model_name='grupofamiliar',
                    index=models.Index(fields=['ciudadano_1'], name='ciudadanos__ciudada_0b736a_idx'),
                ),
                migrations.AddIndex(
                    model_name='grupofamiliar',
                    index=models.Index(fields=['ciudadano_2'], name='ciudadanos__ciudada_547f88_idx'),
                ),
                migrations.AlterField(
                    model_name='ciudadanoprograma',
                    name='programas',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programa_ciudadano', to='core.programa'),
                ),
                migrations.AlterField(
                    model_name='historialciudadanoprogramas',
                    name='programa',
                    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hist_prog_ciudadano', to='core.programa'),
                ),
                migrations.DeleteModel(
                    name='ActividadRealizada',
                ),
                migrations.DeleteModel(
                    name='Agua',
                ),
                migrations.DeleteModel(
                    name='Alerta',
                ),
                migrations.DeleteModel(
                    name='AportesJubilacion',
                ),
                migrations.DeleteModel(
                    name='Archivo',
                ),
                migrations.DeleteModel(
                    name='AreaCurso',
                ),
                migrations.DeleteModel(
                    name='AsisteEscuela',
                ),
                migrations.DeleteModel(
                    name='CantidadAmbientes',
                ),
                migrations.DeleteModel(
                    name='CategoriaAlerta',
                ),
                migrations.DeleteModel(
                    name='CentrosSalud',
                ),
                migrations.DeleteModel(
                    name='Circuito',
                ),
                migrations.DeleteModel(
                    name='Derivacion',
                ),
                migrations.DeleteModel(
                    name='Desague',
                ),
                migrations.DeleteModel(
                    name='Dimension',
                ),
                migrations.DeleteModel(
                    name='DimensionEconomia',
                ),
                migrations.DeleteModel(
                    name='DimensionEducacion',
                ),
                migrations.DeleteModel(
                    name='DimensionFamilia',
                ),
                migrations.DeleteModel(
                    name='DimensionSalud',
                ),
                migrations.DeleteModel(
                    name='DimensionTrabajo',
                ),
                migrations.DeleteModel(
                    name='DimensionVivienda',
                ),
                migrations.DeleteModel(
                    name='Direccion',
                ),
                migrations.DeleteModel(
                    name='DuracionTrabajo',
                ),
                migrations.DeleteModel(
                    name='EstadoCivil',
                ),
                migrations.DeleteModel(
                    name='EstadoDerivacion',
                ),
                migrations.DeleteModel(
                    name='EstadoIntervencion',
                ),
                migrations.DeleteModel(
                    name='EstadoLlamado',
                ),
                migrations.DeleteModel(
                    name='EstadoNivelEducativo',
                ),
                migrations.DeleteModel(
                    name='EstadoRelacion',
                ),
                migrations.DeleteModel(
                    name='Frecuencia',
                ),
                migrations.DeleteModel(
                    name='Gas',
                ),
                migrations.DeleteModel(
                    name='Grado',
                ),
                migrations.DeleteModel(
                    name='GrupoHogar',
                ),
                migrations.DeleteModel(
                    name='HistorialAlerta',
                ),
                migrations.DeleteModel(
                    name='Importancia',
                ),
                migrations.DeleteModel(
                    name='Inodoro',
                ),
                migrations.DeleteModel(
                    name='InstitucionEducativas',
                ),
                migrations.DeleteModel(
                    name='Intervencion',
                ),
                migrations.DeleteModel(
                    name='Jurisdiccion',
                ),
                migrations.DeleteModel(
                    name='Llamado',
                ),
                migrations.DeleteModel(
                    name='ModoContratacion',
                ),
                migrations.DeleteModel(
                    name='MotivoNivelIncompleto',
                ),
                migrations.DeleteModel(
                    name='Nacionalidad',
                ),
                migrations.DeleteModel(
                    name='NivelEducativo',
                ),
                migrations.DeleteModel(
                    name='NobusquedaLaboral',
                ),
                migrations.DeleteModel(
                    name='Organismo',
                ),
                migrations.DeleteModel(
                    name='PlanSocial',
                ),
                migrations.DeleteModel(
                    name='Programa',
                ),
                migrations.DeleteModel(
                    name='ProgramasLlamados',
                ),
                migrations.DeleteModel(
                    name='Rechazo',
                ),
                migrations.DeleteModel(
                    name='Secretarias',
                ),
                migrations.DeleteModel(
                    name='SubIntervencion',
                ),
                migrations.DeleteModel(
                    name='Subsecretarias',
                ),
                migrations.DeleteModel(
                    name='SubtipoLlamado',
                ),
                migrations.DeleteModel(
                    name='TiempoBusquedaLaboral',
                ),
                migrations.DeleteModel(
                    name='TipoConstruccionVivienda',
                ),
                migrations.DeleteModel(
                    name='TipoDocumento',
                ),
                migrations.DeleteModel(
                    name='TipoGestion',
                ),
                migrations.DeleteModel(
                    name='TipoIntervencion',
                ),
                migrations.DeleteModel(
                    name='TipoLlamado',
                ),
                migrations.DeleteModel(
                    name='TipoOrganismo',
                ),
                migrations.DeleteModel(
                    name='TipoPisosVivienda',
                ),
                migrations.DeleteModel(
                    name='TipoPosesionVivienda',
                ),
                migrations.DeleteModel(
                    name='TipoTechoVivienda',
                ),
                migrations.DeleteModel(
                    name='TipoVivienda',
                ),
                migrations.DeleteModel(
                    name='Turno',
                ),
                migrations.DeleteModel(
                    name='UbicacionVivienda',
                ),
                migrations.DeleteModel(
                    name='VinculoFamiliar',
                ),
            ],
        ),
        migrations.RunPython(
            code=migrations.RunPython.noop,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='ciudadanoprograma',
            name='fecha_creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RunPython(
            code=ensure_datetime_columns,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=ensure_grupofamiliar_text_fields,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=drop_estado_column,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=drop_legacy_columns,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    code=add_ciudadano_fields,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='ciudadano',
                    name='latitud',
                    field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                migrations.AddField(
                    model_name='ciudadano',
                    name='longitud',
                    field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
                ),
                migrations.AddField(
                    model_name='ciudadano',
                    name='estado_civil',
                    field=models.CharField(blank=True, choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a'), ('union_convivencial', 'Unión convivencial')], max_length=20, null=True),
                ),
                migrations.AddField(
                    model_name='ciudadano',
                    name='cuil_cuit',
                    field=models.CharField(blank=True, max_length=13, null=True),
                ),
                migrations.AddField(
                    model_name='ciudadano',
                    name='origen_dato',
                    field=models.CharField(choices=[('anses', 'ANSES'), ('renaper', 'RENAPER'), ('manual', 'Carga Manual'), ('migracion', 'Migración')], default='manual', max_length=20),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('auh', 'AUH'), ('prestacion_alimentar', 'Prestación Alimentar'), ('centro_familia', 'Centro de Familia'), ('comedor', 'Asiste a comedor'), ('aduana', 'Aduana')], max_length=30)),
                ('categoria', models.CharField(choices=[('directa', 'Transferencia Directa'), ('indirecta', 'Transferencia Indirecta')], max_length=20)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_texto', models.CharField(blank=True, help_text="Ej: '2 colchones'", max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_transferencia', to='ciudadanos.ciudadano')),
            ],
            options={
                'verbose_name': 'Programa de Transferencia',
                'verbose_name_plural': 'Programas de Transferencia',
                'ordering': ['categoria', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='HistorialTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('monto_auh', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_prestacion_alimentar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_centro_familia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_comedor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_transferencias', to='ciudadanos.ciudadano')),
            ],
            options={
                'verbose_name': 'Historial de Transferencia',
                'verbose_name_plural': 'Historial de Transferencias',
                'ordering': ['-anio', '-mes'],
            },
        ),
        migrations.AddConstraint(
            model_name='historialtransferencia',
            constraint=models.UniqueConstraint(fields=('ciudadano', 'mes', 'anio'), name='unique_historial_ciudadano_mes_anio'),
        ),
        migrations.CreateModel(
            name='Interaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Ej: Rendición de cuentas, Contacto por teléfono, Relevamiento', max_length=255)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('completo', 'Completo'), ('en_plan', 'En Plan'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='ciudadanos.ciudadano')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interacción',
                'verbose_name_plural': 'Interacciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='historialtransferencia',
            name='unique_historial_ciudadano_mes_anio',
        ),
        migrations.AlterField(
            model_name='historialtransferencia',
            name='anio',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='historialtransferencia',
            name='mes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterUniqueTogether(
            name='historialtransferencia',
            unique_together={('ciudadano', 'mes', 'anio')},
        ),
        migrations.RunPython(
            code=ensure_ciudadano_geo_columns,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterModelManagers(
            name='ciudadano',
            managers=[
                ('objects', core.soft_delete.base.SoftDeleteManager()),
                ('all_objects', core.soft_delete.base.SoftDeleteManager(include_deleted=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='grupofamiliar',
            managers=[
                ('objects', core.soft_delete.base.SoftDeleteManager()),
                ('all_objects', core.soft_delete.base.SoftDeleteManager(include_deleted=True)),
            ],
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grupofamiliar',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='grupofamiliar',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='telefono_alternativo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='ciudadano',
                    unique_together=set(),
                ),
            ],
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='tipo_registro_identidad',
            field=models.CharField(choices=[('ESTANDAR', 'Estándar'), ('SIN_DNI', 'Sin DNI'), ('DNI_NO_VALIDADO_RENAPER', 'DNI no validado por RENAPER')], db_index=True, default='ESTANDAR', max_length=30),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='estado_validacion_renaper',
            field=models.CharField(choices=[('NO_CONSULTADO', 'No consultado'), ('VALIDADO', 'Validado'), ('NO_VALIDADO', 'No validado')], db_index=True, default='NO_CONSULTADO', max_length=20),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='fecha_validacion_renaper',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='datos_renaper',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='motivo_sin_dni',
            field=models.CharField(blank=True, choices=[('NO_REGISTRADO_NACER', 'No fue registrado al nacer'), ('MENOR_SIN_DOCUMENTO', 'Menor de edad sin documento tramitado'), ('EXTRANJERO_SIN_DNI', 'Extranjero sin DNI argentino'), ('DOCUMENTO_EXTRAVIADO', 'Documento extraviado o en trámite'), ('VULNERABILIDAD_EXTREMA', 'Víctima de violencia / vulnerabilidad extrema'), ('OTRO', 'Otro')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='motivo_sin_dni_descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='motivo_no_validacion_renaper',
            field=models.CharField(blank=True, choices=[('ERROR_TRANSCRIPCION', 'Errores en la transcripción de datos manuales'), ('RENAPER_DESACTUALIZADO', 'Cambios recientes en RENAPER aún no reflejados'), ('DOC_NO_ACTUALIZADA', 'Documentación del usuario no actualizada'), ('ERROR_TIPOGRAFICO', 'Errores tipográficos en el ingreso de datos'), ('MULTIPLES_IDENTIDADES', 'Personas con múltiples identidades o nombres'), ('CAMBIO_NOMBRE_LEGAL', 'Cambios de nombre legal no registrados en RENAPER'), ('DIFERENCIA_FORMATO_NOMBRE', 'Diferencias en el formato o tipo de nombre'), ('DISCREPANCIA_FECHA_NACIMIENTO', 'Discrepancias en fechas de nacimiento o partidas'), ('OTRO', 'Otro')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='motivo_no_validacion_descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='requiere_revision_manual',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='identificador_interno',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='documento_unico_key',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterModelOptions(
            name='ciudadano',
            options={'ordering': ['apellido', 'nombre'], 'permissions': [('revision_identidad', 'Puede revisar y cerrar casos de identidad pendientes')]},
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='ciudadano',
            index=models.Index(fields=['deleted_at', 'id'], name='ciud_delid_idx'),
        ),
        migrations.AddIndex(
            model_name='ciudadano',
            index=models.Index(fields=['deleted_at', 'provincia', 'id'], name='ciud_delprov_id_idx'),
        ),
        migrations.AddIndex(
            model_name='ciudadano',
            index=models.Index(fields=['deleted_at', 'documento'], name='ciud_deldoc_idx'),
        ),
    ]
