# Generated by Django 4.2.20 on 2025-11-26 13:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def migrate_nacionalidades(apps, schema_editor):
    """
    Copia los datos de ciudadanos_nacionalidad hacia core_nacionalidad
    preservando los IDs para que las FK existentes sigan siendo válidas.
    Crea la tabla de destino si aún no existe.
    """
    connection = schema_editor.connection
    quote = schema_editor.quote_name

    with connection.cursor() as cursor:
        existing_tables = set(connection.introspection.table_names(cursor))

    def table_exists(name: str) -> bool:
        return name in existing_tables

    if not table_exists("ciudadanos_nacionalidad"):
        return

    if not table_exists("core_nacionalidad"):
        if connection.vendor == "sqlite":
            schema_editor.execute(
                f"""
                CREATE TABLE {quote("core_nacionalidad")} (
                    {quote("id")} integer PRIMARY KEY AUTOINCREMENT,
                    {quote("nacionalidad")} varchar(50) NOT NULL
                );
                """
            )
        else:
            schema_editor.execute(
                f"""
                CREATE TABLE {quote("core_nacionalidad")} (
                    {quote("id")} bigint AUTO_INCREMENT PRIMARY KEY,
                    {quote("nacionalidad")} varchar(50) NOT NULL
                );
                """
            )

    if connection.vendor == "sqlite":
        schema_editor.execute(
            """
            INSERT OR REPLACE INTO core_nacionalidad (id, nacionalidad)
            SELECT id, nacionalidad FROM ciudadanos_nacionalidad;
            """
        )
    else:
        schema_editor.execute(
            """
            INSERT INTO core_nacionalidad (id, nacionalidad)
            SELECT id, nacionalidad FROM ciudadanos_nacionalidad
            ON DUPLICATE KEY UPDATE nacionalidad = VALUES(nacionalidad);
            """
        )

    if connection.vendor == "mysql":
        with connection.cursor() as cursor:
            cursor.execute("SELECT IFNULL(MAX(id), 0) + 1 FROM core_nacionalidad;")
            next_id = cursor.fetchone()
        if next_id:
            schema_editor.execute(
                f"ALTER TABLE {quote('core_nacionalidad')} AUTO_INCREMENT = {int(next_id[0])}"
            )


def safe_cleanup(apps, schema_editor):
    connection = schema_editor.connection
    if connection.vendor == "sqlite":
        return
    quote = schema_editor.quote_name

    def table_exists(name: str) -> bool:
        with connection.cursor() as cursor:
            return name in set(connection.introspection.table_names(cursor))

    def column_exists(table: str, column: str) -> bool:
        if not table_exists(table):
            return False
        with connection.cursor() as cursor:
            return column in [col.name for col in connection.introspection.get_table_description(cursor, table)]

    def drop_column_if_exists(table: str, column: str) -> None:
        if column_exists(table, column):
            schema_editor.execute(f"ALTER TABLE {quote(table)} DROP COLUMN {quote(column)}")

    def add_column_if_missing(table: str, column: str, definition_sql: str) -> None:
        if table_exists(table) and not column_exists(table, column):
            schema_editor.execute(f"ALTER TABLE {quote(table)} ADD COLUMN {definition_sql}")

    def drop_index_if_exists(table: str, index_name: str) -> None:
        if not table_exists(table):
            return
        with connection.cursor() as cursor:
            constraints = connection.introspection.get_constraints(cursor, table)
        if index_name in constraints:
            schema_editor.execute(f"DROP INDEX {quote(index_name)} ON {quote(table)}")

    def add_index_if_missing(table: str, index_name: str, columns: list[str]) -> None:
        if not table_exists(table):
            return
        with connection.cursor() as cursor:
            constraints = connection.introspection.get_constraints(cursor, table)
        if index_name not in constraints:
            cols_sql = ", ".join(quote(col) for col in columns)
            schema_editor.execute(f"CREATE INDEX {quote(index_name)} ON {quote(table)} ({cols_sql})")

    def drop_fk_constraints(table: str, column: str) -> None:
        if not table_exists(table):
            return
        with connection.cursor() as cursor:
            constraints = connection.introspection.get_constraints(cursor, table)
        for name, details in constraints.items():
            if column in details.get("columns", []) and details.get("foreign_key"):
                schema_editor.execute(f"ALTER TABLE {quote(table)} DROP FOREIGN KEY {quote(name)}")

    def drop_unique_constraints(table: str, column: str) -> None:
        if not table_exists(table):
            return
        with connection.cursor() as cursor:
            constraints = connection.introspection.get_constraints(cursor, table)
        for name, details in constraints.items():
            if details.get("unique") and column in details.get("columns", []):
                schema_editor.execute(f"ALTER TABLE {quote(table)} DROP INDEX {quote(name)}")

    def migrate_tipo_documento() -> None:
        """
        Convierte el FK tipo_documento_id a un campo varchar usando el valor de ciudadanos_tipodocumento.tipo.
        Deja datos por defecto en 'DNI' si no existe referencia. Idempotente.
        """
        table = "ciudadanos_ciudadano"
        fk_col = "tipo_documento_id"
        text_col = "tipo_documento"

        if not table_exists(table):
            return

        has_fk_col = column_exists(table, fk_col)
        has_text_col = column_exists(table, text_col)

        if not has_fk_col and has_text_col:
            return

        add_column_if_missing(
            table,
            text_col,
            f"{quote(text_col)} VARCHAR(20) NOT NULL DEFAULT 'DNI'",
        )

        if table_exists("ciudadanos_tipodocumento"):
            schema_editor.execute(
                f"""
                UPDATE {quote(table)} c
                LEFT JOIN {quote("ciudadanos_tipodocumento")} t ON c.{quote(fk_col)} = t.{quote("id")}
                SET c.{quote(text_col)} = COALESCE(NULLIF(t.{quote("tipo")}, ''), 'DNI');
                """
            )
        else:
            schema_editor.execute(
                f"""
                UPDATE {quote(table)}
                SET {quote(text_col)} = 'DNI'
                WHERE {quote(text_col)} IS NULL OR {quote(text_col)} = '';
                """
            )

        drop_fk_constraints(table, fk_col)
        drop_unique_constraints(table, fk_col)
        drop_column_if_exists(table, fk_col)

    with connection.cursor() as cursor:
        existing_tables = set(connection.introspection.table_names(cursor))

    keep_tables = {
        "ciudadanos_ciudadano",
        "ciudadanos_grupofamiliar",
        "ciudadanos_ciudadanoprograma",
        "ciudadanos_historialciudadanoprogramas",
    }
    migrate_tipo_documento()
    drop_tables = [
        table
        for table in existing_tables
        if table.startswith("ciudadanos_") and table not in keep_tables
    ]

    if drop_tables:
        schema_editor.execute("SET FOREIGN_KEY_CHECKS=0;")
        for table in drop_tables:
            schema_editor.execute(f"DROP TABLE IF EXISTS {quote(table)}")
        schema_editor.execute("SET FOREIGN_KEY_CHECKS=1;")

    drop_ciudadano_columns = [
        "circuito_id",
        "demo_centro_familia_id",
        "escalera_manzana",
        "estado_id",
        "estado_civil_id",
        "latitud",
        "longitud",
        "torre_pasillo",
    ]
    if drop_ciudadano_columns:
        schema_editor.execute("SET FOREIGN_KEY_CHECKS=0;")
        for column in drop_ciudadano_columns:
            drop_fk_constraints("ciudadanos_ciudadano", column)
            drop_column_if_exists("ciudadanos_ciudadano", column)
        schema_editor.execute("SET FOREIGN_KEY_CHECKS=1;")

    add_column_if_missing(
        "ciudadanos_ciudadano",
        "activo",
        "activo BOOL NOT NULL DEFAULT 1",
    )
    add_column_if_missing(
        "ciudadanos_ciudadano",
        "barrio",
        "barrio VARCHAR(100) NULL",
    )

    drop_index_if_exists("ciudadanos_ciudadano", "ciudadanos__apellid_8f0c3b_idx")
    drop_index_if_exists("ciudadanos_ciudadano", "ciudadanos__fecha_n_aa8772_idx")
    drop_index_if_exists("ciudadanos_ciudadano", "ciudadanos__observa_517ba3_idx")
    add_index_if_missing(
        "ciudadanos_ciudadano",
        "ciudadanos__apellid_02f758_idx",
        ["apellido", "nombre"],
    )

    drop_column_if_exists("ciudadanos_grupofamiliar", "vinculo_inverso")
    add_column_if_missing(
        "ciudadanos_grupofamiliar",
        "creado",
        "creado DATETIME(6) NULL",
    )
    add_column_if_missing(
        "ciudadanos_grupofamiliar",
        "modificado",
        "modificado DATETIME(6) NULL",
    )
    schema_editor.execute(
        f"UPDATE {quote('ciudadanos_grupofamiliar')} SET {quote('creado')} = COALESCE({quote('creado')}, CURRENT_TIMESTAMP(6)), {quote('modificado')} = COALESCE({quote('modificado')}, CURRENT_TIMESTAMP(6))"
    )
    add_index_if_missing(
        "ciudadanos_grupofamiliar",
        "ciudadanos__ciudada_0b736a_idx",
        ["ciudadano_1_id"],
    )
    add_index_if_missing(
        "ciudadanos_grupofamiliar",
        "ciudadanos__ciudada_547f88_idx",
        ["ciudadano_2_id"],
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_nacionalidad"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comedores", "0013_alter_nomina_estado"),
        ("ciudadanos", "0008_alter_ciudadano_documento"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    migrate_nacionalidades, migrations.RunPython.noop
                ),
                migrations.AlterField(
                    model_name="ciudadano",
                    name="nacionalidad",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.nacionalidad",
                    ),
                ),
                migrations.AlterField(
                    model_name="ciudadanoprograma",
                    name="programas",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programa_ciudadano",
                        to="core.programa",
                    ),
                ),
                migrations.AlterField(
                    model_name="historialciudadanoprogramas",
                    name="programa",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hist_prog_ciudadano",
                        to="core.programa",
                    ),
                ),
                migrations.RunPython(safe_cleanup, migrations.RunPython.noop),
            ],
            state_operations=[
                    migrations.RemoveField(
                        model_name="alerta",
                        name="categoria",
                    ),
                    migrations.RemoveField(
                        model_name="archivo",
                        name="ciudadano",
                    ),
                    migrations.RemoveField(
                        model_name="categoriaalerta",
                        name="dimension",
                    ),
                    migrations.DeleteModel(
                        name="Condicion",
                    ),
                    migrations.RemoveField(
                        model_name="derivacion",
                        name="alertas",
                    ),
                    migrations.RemoveField(
                        model_name="derivacion",
                        name="ciudadano",
                    ),
                    migrations.RemoveField(
                        model_name="derivacion",
                        name="estado",
                    ),
                    migrations.RemoveField(
                        model_name="derivacion",
                        name="importancia",
                    ),
                    migrations.RemoveField(
                        model_name="derivacion",
                        name="motivo_rechazo",
                    ),
                    migrations.RemoveField(
                        model_name="derivacion",
                        name="organismo",
                    ),
                    migrations.RemoveField(
                        model_name="derivacion",
                        name="programa",
                    ),
                    migrations.RemoveField(
                        model_name="derivacion",
                        name="programa_solicitante",
                    ),
                    migrations.RemoveField(
                        model_name="derivacion",
                        name="usuario",
                    ),
                    migrations.RemoveField(
                        model_name="dimensioneconomia",
                        name="ciudadano",
                    ),
                    migrations.RemoveField(
                        model_name="dimensioneconomia",
                        name="planes",
                    ),
                    migrations.RemoveField(
                        model_name="dimensioneducacion",
                        name="area_curso",
                    ),
                    migrations.RemoveField(
                        model_name="dimensioneducacion",
                        name="area_oficio",
                    ),
                    migrations.RemoveField(
                        model_name="dimensioneducacion",
                        name="asiste_escuela",
                    ),
                    migrations.RemoveField(
                        model_name="dimensioneducacion",
                        name="ciclo",
                    ),
                    migrations.RemoveField(
                        model_name="dimensioneducacion",
                        name="ciudadano",
                    ),
                    migrations.RemoveField(
                        model_name="dimensioneducacion",
                        name="estado_nivel",
                    ),
                    migrations.RemoveField(
                        model_name="dimensioneducacion",
                        name="gestion",
                    ),
                    migrations.RemoveField(
                        model_name="dimensioneducacion",
                        name="grado",
                    ),
                    migrations.RemoveField(
                        model_name="dimensioneducacion",
                        name="institucion",
                    ),
                    migrations.RemoveField(
                        model_name="dimensioneducacion",
                        name="localidadInstitucion",
                    ),
                    migrations.RemoveField(
                        model_name="dimensioneducacion",
                        name="max_nivel",
                    ),
                    migrations.RemoveField(
                        model_name="dimensioneducacion",
                        name="municipioInstitucion",
                    ),
                    migrations.RemoveField(
                        model_name="dimensioneducacion",
                        name="nivel_incompleto",
                    ),
                    migrations.RemoveField(
                        model_name="dimensioneducacion",
                        name="provinciaInstitucion",
                    ),
                    migrations.RemoveField(
                        model_name="dimensioneducacion",
                        name="sin_educacion_formal",
                    ),
                    migrations.RemoveField(
                        model_name="dimensioneducacion",
                        name="turno",
                    ),
                    migrations.RemoveField(
                        model_name="dimensionfamilia",
                        name="ciudadano",
                    ),
                    migrations.RemoveField(
                        model_name="dimensionsalud",
                        name="ciudadano",
                    ),
                    migrations.RemoveField(
                        model_name="dimensionsalud",
                        name="frecuencia_controles_medicos",
                    ),
                    migrations.RemoveField(
                        model_name="dimensionsalud",
                        name="lugares_atencion",
                    ),
                    migrations.RemoveField(
                        model_name="dimensiontrabajo",
                        name="Tiempobusqueda_laboral",
                    ),
                    migrations.RemoveField(
                        model_name="dimensiontrabajo",
                        name="actividadRealizadaComo",
                    ),
                    migrations.RemoveField(
                        model_name="dimensiontrabajo",
                        name="aportesJubilacion",
                    ),
                    migrations.RemoveField(
                        model_name="dimensiontrabajo",
                        name="ciudadano",
                    ),
                    migrations.RemoveField(
                        model_name="dimensiontrabajo",
                        name="duracionTrabajo",
                    ),
                    migrations.RemoveField(
                        model_name="dimensiontrabajo",
                        name="modo_contratacion",
                    ),
                    migrations.RemoveField(
                        model_name="dimensiontrabajo",
                        name="nobusqueda_laboral",
                    ),
                    migrations.RemoveField(
                        model_name="dimensionvivienda",
                        name="agua",
                    ),
                    migrations.RemoveField(
                        model_name="dimensionvivienda",
                        name="cant_ambientes",
                    ),
                    migrations.RemoveField(
                        model_name="dimensionvivienda",
                        name="ciudadano",
                    ),
                    migrations.RemoveField(
                        model_name="dimensionvivienda",
                        name="desague",
                    ),
                    migrations.RemoveField(
                        model_name="dimensionvivienda",
                        name="gas",
                    ),
                    migrations.RemoveField(
                        model_name="dimensionvivienda",
                        name="hay_banio",
                    ),
                    migrations.RemoveField(
                        model_name="dimensionvivienda",
                        name="material",
                    ),
                    migrations.RemoveField(
                        model_name="dimensionvivienda",
                        name="pisos",
                    ),
                    migrations.RemoveField(
                        model_name="dimensionvivienda",
                        name="posesion",
                    ),
                    migrations.RemoveField(
                        model_name="dimensionvivienda",
                        name="techos",
                    ),
                    migrations.RemoveField(
                        model_name="dimensionvivienda",
                        name="tipo",
                    ),
                    migrations.RemoveField(
                        model_name="dimensionvivienda",
                        name="ubicacion_vivienda",
                    ),
                    migrations.RemoveField(
                        model_name="grupohogar",
                        name="ciudadano_1Hogar",
                    ),
                    migrations.RemoveField(
                        model_name="grupohogar",
                        name="ciudadano_2Hogar",
                    ),
                    migrations.RemoveField(
                        model_name="grupohogar",
                        name="estado_relacion",
                    ),
                    migrations.RemoveField(
                        model_name="historialalerta",
                        name="alerta",
                    ),
                    migrations.RemoveField(
                        model_name="historialalerta",
                        name="ciudadano",
                    ),
                    migrations.RemoveField(
                        model_name="historialalerta",
                        name="creada_por",
                    ),
                    migrations.RemoveField(
                        model_name="historialalerta",
                        name="eliminada_por",
                    ),
                    migrations.RemoveField(
                        model_name="intervencion",
                        name="ciudadano",
                    ),
                    migrations.RemoveField(
                        model_name="intervencion",
                        name="direccion",
                    ),
                    migrations.RemoveField(
                        model_name="intervencion",
                        name="estado",
                    ),
                    migrations.RemoveField(
                        model_name="intervencion",
                        name="subintervencion",
                    ),
                    migrations.RemoveField(
                        model_name="intervencion",
                        name="tipo_intervencion",
                    ),
                    migrations.RemoveField(
                        model_name="intervencion",
                        name="usuario",
                    ),
                    migrations.RemoveField(
                        model_name="llamado",
                        name="ciudadano",
                    ),
                    migrations.RemoveField(
                        model_name="llamado",
                        name="estado",
                    ),
                    migrations.RemoveField(
                        model_name="llamado",
                        name="programas_llamados",
                    ),
                    migrations.RemoveField(
                        model_name="llamado",
                        name="subtipo_llamado",
                    ),
                    migrations.RemoveField(
                        model_name="llamado",
                        name="tipo_llamado",
                    ),
                    migrations.RemoveField(
                        model_name="llamado",
                        name="usuario",
                    ),
                    migrations.RemoveField(
                        model_name="organismo",
                        name="localidad",
                    ),
                    migrations.RemoveField(
                        model_name="organismo",
                        name="tipo",
                    ),
                    migrations.RemoveField(
                        model_name="plansocial",
                        name="jurisdiccion",
                    ),
                    migrations.RemoveField(
                        model_name="programa",
                        name="subsecretaria",
                    ),
                    migrations.RemoveField(
                        model_name="subintervencion",
                        name="subintervencion",
                    ),
                    migrations.RemoveField(
                        model_name="subsecretarias",
                        name="secretaria",
                    ),
                    migrations.RemoveField(
                        model_name="subtipollamado",
                        name="tipo_llamado",
                    ),
                    migrations.RemoveField(
                        model_name="tipollamado",
                        name="programas_llamados",
                    ),
                    migrations.AlterModelOptions(
                        name="ciudadano",
                        options={"ordering": ["apellido", "nombre"]},
                    ),
                    migrations.AlterModelOptions(
                        name="grupofamiliar",
                        options={"ordering": ["ciudadano_1", "ciudadano_2"]},
                    ),
                    migrations.RemoveIndex(
                        model_name="ciudadano",
                        name="ciudadanos__apellid_8f0c3b_idx",
                    ),
                    migrations.RemoveIndex(
                        model_name="ciudadano",
                        name="ciudadanos__fecha_n_aa8772_idx",
                    ),
                    migrations.RemoveIndex(
                        model_name="ciudadano",
                        name="ciudadanos__observa_517ba3_idx",
                    ),
                    migrations.RemoveIndex(
                        model_name="grupofamiliar",
                        name="ciudadanos__ciudada_0b736a_idx",
                    ),
                    migrations.RemoveIndex(
                        model_name="grupofamiliar",
                        name="ciudadanos__ciudada_547f88_idx",
                    ),
                    migrations.RemoveField(
                        model_name="ciudadano",
                        name="alertas",
                    ),
                    migrations.RemoveField(
                        model_name="ciudadano",
                        name="circuito",
                    ),
                    migrations.RemoveField(
                        model_name="ciudadano",
                        name="demo_centro_familia",
                    ),
                    migrations.RemoveField(
                        model_name="ciudadano",
                        name="escalera_manzana",
                    ),
                    migrations.RemoveField(
                        model_name="ciudadano",
                        name="estado",
                    ),
                    migrations.RemoveField(
                        model_name="ciudadano",
                        name="estado_civil",
                    ),
                    migrations.RemoveField(
                        model_name="ciudadano",
                        name="latitud",
                    ),
                    migrations.RemoveField(
                        model_name="ciudadano",
                        name="longitud",
                    ),
                    migrations.RemoveField(
                        model_name="ciudadano",
                        name="torre_pasillo",
                    ),
                    migrations.RemoveField(
                        model_name="grupofamiliar",
                        name="vinculo_inverso",
                    ),
                    migrations.AddField(
                        model_name="ciudadano",
                        name="activo",
                        field=models.BooleanField(default=True),
                    ),
                    migrations.AddField(
                        model_name="ciudadano",
                        name="barrio",
                        field=models.CharField(blank=True, max_length=100, null=True),
                    ),
                    migrations.AddField(
                        model_name="grupofamiliar",
                        name="creado",
                        field=models.DateTimeField(
                            default=django.utils.timezone.now, editable=False
                        ),
                    ),
                    migrations.AddField(
                        model_name="grupofamiliar",
                        name="modificado",
                        field=models.DateTimeField(auto_now=True),
                    ),
                    migrations.AlterField(
                        model_name="ciudadano",
                        name="altura",
                        field=models.CharField(blank=True, max_length=10, null=True),
                    ),
                    migrations.AlterField(
                        model_name="ciudadano",
                        name="codigo_postal",
                        field=models.CharField(blank=True, max_length=12, null=True),
                    ),
                    migrations.AlterField(
                        model_name="ciudadano",
                        name="creado",
                        field=models.DateTimeField(
                            default=django.utils.timezone.now, editable=False
                        ),
                    ),
                    migrations.AlterField(
                        model_name="ciudadano",
                        name="creado_por",
                        field=models.ForeignKey(
                            blank=True,
                            null=True,
                            on_delete=django.db.models.deletion.SET_NULL,
                            related_name="ciudadano_creado_por",
                            to=settings.AUTH_USER_MODEL,
                        ),
                    ),
                    migrations.AlterField(
                        model_name="ciudadano",
                        name="documento",
                        field=models.PositiveBigIntegerField(
                            null=True, validators=[django.core.validators.MinValueValidator(1)]
                        ),
                    ),
                    migrations.AlterField(
                        model_name="ciudadano",
                        name="modificado",
                        field=models.DateTimeField(auto_now=True),
                    ),
                    migrations.AlterField(
                        model_name="ciudadano",
                        name="modificado_por",
                        field=models.ForeignKey(
                            blank=True,
                            null=True,
                            on_delete=django.db.models.deletion.SET_NULL,
                            related_name="ciudadano_modificado_por",
                            to=settings.AUTH_USER_MODEL,
                        ),
                    ),
                    migrations.AlterField(
                        model_name="ciudadano",
                        name="nacionalidad",
                        field=models.ForeignKey(
                            blank=True,
                            null=True,
                            on_delete=django.db.models.deletion.SET_NULL,
                            to="core.nacionalidad",
                        ),
                    ),
                    migrations.AlterField(
                        model_name="ciudadano",
                        name="observaciones",
                        field=models.TextField(blank=True, null=True),
                    ),
                    migrations.AlterField(
                        model_name="ciudadano",
                        name="piso_departamento",
                        field=models.CharField(blank=True, max_length=50, null=True),
                    ),
                    migrations.AlterField(
                        model_name="ciudadano",
                        name="sexo",
                        field=models.ForeignKey(
                            blank=True,
                            null=True,
                            on_delete=django.db.models.deletion.SET_NULL,
                            to="core.sexo",
                        ),
                    ),
                    migrations.AlterField(
                        model_name="ciudadano",
                        name="telefono",
                        field=models.CharField(blank=True, max_length=30, null=True),
                    ),
                    migrations.AlterField(
                        model_name="ciudadano",
                        name="telefono_alternativo",
                        field=models.CharField(blank=True, max_length=30, null=True),
                    ),
                    migrations.AlterField(
                        model_name="ciudadano",
                        name="tipo_documento",
                        field=models.CharField(
                            choices=[
                                ("DNI", "DNI"),
                                ("CUIT", "CUIT"),
                                ("PASAPORTE", "Pasaporte"),
                                ("LE", "Libreta de enrolamiento"),
                            ],
                            default="DNI",
                            max_length=20,
                        ),
                    ),
                    migrations.AlterField(
                        model_name="grupofamiliar",
                        name="ciudadano_1",
                        field=models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="relaciones_salientes",
                            to="ciudadanos.ciudadano",
                        ),
                    ),
                    migrations.AlterField(
                        model_name="grupofamiliar",
                        name="ciudadano_2",
                        field=models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="relaciones_entrantes",
                            to="ciudadanos.ciudadano",
                        ),
                    ),
                    migrations.AlterField(
                        model_name="grupofamiliar",
                        name="conviven",
                        field=models.BooleanField(default=False),
                    ),
                    migrations.AlterField(
                        model_name="grupofamiliar",
                        name="cuidador_principal",
                        field=models.BooleanField(default=False),
                    ),
                    migrations.AlterField(
                        model_name="grupofamiliar",
                        name="estado_relacion",
                        field=models.CharField(
                            blank=True,
                            choices=[
                                ("bueno", "Bueno"),
                                ("regular", "Regular"),
                                ("conflictivo", "Conflictivo"),
                            ],
                            max_length=20,
                            null=True,
                        ),
                    ),
                    migrations.AlterField(
                        model_name="grupofamiliar",
                        name="observaciones",
                        field=models.TextField(blank=True, null=True),
                    ),
                    migrations.AlterField(
                        model_name="grupofamiliar",
                        name="vinculo",
                        field=models.CharField(
                            blank=True,
                            choices=[
                                ("PADRE/MADRE", "Padre/Madre"),
                                ("HIJO/A", "Hijo/a"),
                                ("PAREJA", "Pareja"),
                                ("HERMANO/A", "Hermano/a"),
                                ("TUTOR/A", "Tutor/a"),
                                ("OTRO", "Otro"),
                            ],
                            max_length=20,
                            null=True,
                        ),
                    ),
                    migrations.AddIndex(
                        model_name="ciudadano",
                        index=models.Index(
                            fields=["apellido", "nombre"], name="ciudadanos__apellid_02f758_idx"
                        ),
                    ),
                    migrations.AddIndex(
                        model_name="grupofamiliar",
                        index=models.Index(
                            fields=["ciudadano_1"], name="ciudadanos__ciudada_0b736a_idx"
                        ),
                    ),
                    migrations.AddIndex(
                        model_name="grupofamiliar",
                        index=models.Index(
                            fields=["ciudadano_2"], name="ciudadanos__ciudada_547f88_idx"
                        ),
                    ),
                    migrations.AlterField(
                        model_name="ciudadanoprograma",
                        name="programas",
                        field=models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="programa_ciudadano",
                            to="core.programa",
                        ),
                    ),
                    migrations.AlterField(
                        model_name="historialciudadanoprogramas",
                        name="programa",
                        field=models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="hist_prog_ciudadano",
                            to="core.programa",
                        ),
                    ),
                    migrations.DeleteModel(
                        name="ActividadRealizada",
                    ),
                    migrations.DeleteModel(
                        name="Agua",
                    ),
                    migrations.DeleteModel(
                        name="Alerta",
                    ),
                    migrations.DeleteModel(
                        name="AportesJubilacion",
                    ),
                    migrations.DeleteModel(
                        name="Archivo",
                    ),
                    migrations.DeleteModel(
                        name="AreaCurso",
                    ),
                    migrations.DeleteModel(
                        name="AsisteEscuela",
                    ),
                    migrations.DeleteModel(
                        name="CantidadAmbientes",
                    ),
                    migrations.DeleteModel(
                        name="CategoriaAlerta",
                    ),
                    migrations.DeleteModel(
                        name="CentrosSalud",
                    ),
                    migrations.DeleteModel(
                        name="Circuito",
                    ),
                    migrations.DeleteModel(
                        name="Derivacion",
                    ),
                    migrations.DeleteModel(
                        name="Desague",
                    ),
                    migrations.DeleteModel(
                        name="Dimension",
                    ),
                    migrations.DeleteModel(
                        name="DimensionEconomia",
                    ),
                    migrations.DeleteModel(
                        name="DimensionEducacion",
                    ),
                    migrations.DeleteModel(
                        name="DimensionFamilia",
                    ),
                    migrations.DeleteModel(
                        name="DimensionSalud",
                    ),
                    migrations.DeleteModel(
                        name="DimensionTrabajo",
                    ),
                    migrations.DeleteModel(
                        name="DimensionVivienda",
                    ),
                    migrations.DeleteModel(
                        name="Direccion",
                    ),
                    migrations.DeleteModel(
                        name="DuracionTrabajo",
                    ),
                    migrations.DeleteModel(
                        name="EstadoCivil",
                    ),
                    migrations.DeleteModel(
                        name="EstadoDerivacion",
                    ),
                    migrations.DeleteModel(
                        name="EstadoIntervencion",
                    ),
                    migrations.DeleteModel(
                        name="EstadoLlamado",
                    ),
                    migrations.DeleteModel(
                        name="EstadoNivelEducativo",
                    ),
                    migrations.DeleteModel(
                        name="EstadoRelacion",
                    ),
                    migrations.DeleteModel(
                        name="Frecuencia",
                    ),
                    migrations.DeleteModel(
                        name="Gas",
                    ),
                    migrations.DeleteModel(
                        name="Grado",
                    ),
                    migrations.DeleteModel(
                        name="GrupoHogar",
                    ),
                    migrations.DeleteModel(
                        name="HistorialAlerta",
                    ),
                    migrations.DeleteModel(
                        name="Importancia",
                    ),
                    migrations.DeleteModel(
                        name="Inodoro",
                    ),
                    migrations.DeleteModel(
                        name="InstitucionEducativas",
                    ),
                    migrations.DeleteModel(
                        name="Intervencion",
                    ),
                    migrations.DeleteModel(
                        name="Jurisdiccion",
                    ),
                    migrations.DeleteModel(
                        name="Llamado",
                    ),
                    migrations.DeleteModel(
                        name="ModoContratacion",
                    ),
                    migrations.DeleteModel(
                        name="MotivoNivelIncompleto",
                    ),
                    migrations.DeleteModel(
                        name="Nacionalidad",
                    ),
                    migrations.DeleteModel(
                        name="NivelEducativo",
                    ),
                    migrations.DeleteModel(
                        name="NobusquedaLaboral",
                    ),
                    migrations.DeleteModel(
                        name="Organismo",
                    ),
                    migrations.DeleteModel(
                        name="PlanSocial",
                    ),
                    migrations.DeleteModel(
                        name="Programa",
                    ),
                    migrations.DeleteModel(
                        name="ProgramasLlamados",
                    ),
                    migrations.DeleteModel(
                        name="Rechazo",
                    ),
                    migrations.DeleteModel(
                        name="Secretarias",
                    ),
                    migrations.DeleteModel(
                        name="SubIntervencion",
                    ),
                    migrations.DeleteModel(
                        name="Subsecretarias",
                    ),
                    migrations.DeleteModel(
                        name="SubtipoLlamado",
                    ),
                    migrations.DeleteModel(
                        name="TiempoBusquedaLaboral",
                    ),
                    migrations.DeleteModel(
                        name="TipoConstruccionVivienda",
                    ),
                    migrations.DeleteModel(
                        name="TipoDocumento",
                    ),
                    migrations.DeleteModel(
                        name="TipoGestion",
                    ),
                    migrations.DeleteModel(
                        name="TipoIntervencion",
                    ),
                    migrations.DeleteModel(
                        name="TipoLlamado",
                    ),
                    migrations.DeleteModel(
                        name="TipoOrganismo",
                    ),
                    migrations.DeleteModel(
                        name="TipoPisosVivienda",
                    ),
                    migrations.DeleteModel(
                        name="TipoPosesionVivienda",
                    ),
                    migrations.DeleteModel(
                        name="TipoTechoVivienda",
                    ),
                    migrations.DeleteModel(
                        name="TipoVivienda",
                    ),
                    migrations.DeleteModel(
                        name="Turno",
                    ),
                    migrations.DeleteModel(
                        name="UbicacionVivienda",
                    ),
                    migrations.DeleteModel(
                        name="VinculoFamiliar",
                    ),
            ],
        ),
    ]
