# Generated by Django 4.2.20 on 2025-11-11 20:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.db import OperationalError, ProgrammingError


def drop_column_if_exists(schema_editor, table_name, column_name):
    query = """
        SELECT COUNT(*)
        FROM information_schema.columns
        WHERE table_schema = DATABASE()
          AND table_name = %s
          AND column_name = %s
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(query, [table_name, column_name])
        if cursor.fetchone()[0]:
            cursor.execute(f"ALTER TABLE `{table_name}` DROP COLUMN `{column_name}`")


def drop_index_if_exists(schema_editor, table_name, index_name):
    query = """
        SELECT COUNT(*)
        FROM information_schema.statistics
        WHERE table_schema = DATABASE()
          AND table_name = %s
          AND index_name = %s
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(query, [table_name, index_name])
        if cursor.fetchone()[0]:
            cursor.execute(f"ALTER TABLE `{table_name}` DROP INDEX `{index_name}`")


def drop_table_if_exists(schema_editor, table_name):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"DROP TABLE IF EXISTS `{table_name}`")


def drop_obsolete_indexes(apps, schema_editor):
    indexes = {
        "ciudadanos_ciudadano": [
            "ciudadanos__apellid_8f0c3b_idx",
            "ciudadanos__fecha_n_aa8772_idx",
            "ciudadanos__observa_517ba3_idx",
        ],
        "ciudadanos_grupofamiliar": [
            "ciudadanos__ciudada_0b736a_idx",
            "ciudadanos__ciudada_547f88_idx",
        ],
    }
    for table, names in indexes.items():
        for name in names:
            drop_index_if_exists(schema_editor, table, name)


def cleanup_ciudadano_fields(apps, schema_editor):
    drop_table_if_exists(schema_editor, "ciudadanos_ciudadano_alertas")
    for column in [
        "circuito_id",
        "demo_centro_familia",
        "escalera_manzana",
        "estado_id",
        "estado_civil_id",
        "latitud",
        "longitud",
        "torre_pasillo",
    ]:
        drop_column_if_exists(schema_editor, "ciudadanos_ciudadano", column)
    drop_column_if_exists(schema_editor, "ciudadanos_grupofamiliar", "vinculo_inverso")


def drop_legacy_tables(apps, schema_editor):
    tables = [
        "ciudadanos_actividadrealizada",
        "ciudadanos_agua",
        "ciudadanos_alerta",
        "ciudadanos_aportesjubilacion",
        "ciudadanos_archivo",
        "ciudadanos_areacurso",
        "ciudadanos_asisteescuela",
        "ciudadanos_cantidadambientes",
        "ciudadanos_categoriaalerta",
        "ciudadanos_centrossalud",
        "ciudadanos_circuito",
        "ciudadanos_ciudadanoprograma",
        "ciudadanos_condicion",
        "ciudadanos_derivacion",
        "ciudadanos_desague",
        "ciudadanos_dimension",
        "ciudadanos_dimensioneconomia",
        "ciudadanos_dimensioneducacion",
        "ciudadanos_dimensionfamilia",
        "ciudadanos_dimensionsalud",
        "ciudadanos_dimensiontrabajo",
        "ciudadanos_dimensionvivienda",
        "ciudadanos_direccion",
        "ciudadanos_duraciontrabajo",
        "ciudadanos_estadocivil",
        "ciudadanos_estadoderivacion",
        "ciudadanos_estadointervencion",
        "ciudadanos_estadollamado",
        "ciudadanos_estadoniveleducativo",
        "ciudadanos_estadorelacion",
        "ciudadanos_frecuencia",
        "ciudadanos_gas",
        "ciudadanos_grado",
        "ciudadanos_grupohogar",
        "ciudadanos_historialalerta",
        "ciudadanos_historialciudadanoprogramas",
        "ciudadanos_importancia",
        "ciudadanos_inodoro",
        "ciudadanos_institucioneducativas",
        "ciudadanos_intervencion",
        "ciudadanos_jurisdiccion",
        "ciudadanos_llamado",
        "ciudadanos_modocontratacion",
        "ciudadanos_motivonivelincompleto",
        "ciudadanos_nacionalidad",
        "ciudadanos_niveleducativo",
        "ciudadanos_nobusquedalaboral",
        "ciudadanos_organismo",
        "ciudadanos_plansocial",
        "ciudadanos_programa",
        "ciudadanos_programasllamados",
        "ciudadanos_rechazo",
        "ciudadanos_secretarias",
        "ciudadanos_subintervencion",
        "ciudadanos_subsecretarias",
        "ciudadanos_subtipollamado",
        "ciudadanos_tiempobusquedalaboral",
        "ciudadanos_tipoconstruccionvivienda",
        "ciudadanos_tipodocumento",
        "ciudadanos_tipogestion",
        "ciudadanos_tipointervencion",
        "ciudadanos_tipollamado",
        "ciudadanos_tipoorganismo",
        "ciudadanos_tipopisosvivienda",
        "ciudadanos_tipoposesionvivienda",
        "ciudadanos_tipotechovivienda",
        "ciudadanos_tipovivienda",
        "ciudadanos_turno",
        "ciudadanos_ubicacionvivienda",
        "ciudadanos_vinculofamiliar",
    ]
    for table in tables:
        drop_table_if_exists(schema_editor, table)


def copy_nacionalidad_to_text(apps, schema_editor):
    Ciudadano = apps.get_model("ciudadanos", "Ciudadano")
    try:
        Nacionalidad = apps.get_model("ciudadanos", "Nacionalidad")
    except LookupError:
        return

    try:
        nacionalidades = {
            nacionalidad.pk: nacionalidad.nombre
            for nacionalidad in Nacionalidad.objects.only("pk", "nombre")
        }
    except (ProgrammingError, OperationalError):
        return

    try:
        ciudadanos = Ciudadano.objects.exclude(nacionalidad="").only("pk", "nacionalidad")
    except (ProgrammingError, OperationalError):
        return

    for ciudadano in ciudadanos.iterator(chunk_size=500):
        try:
            nacionalidad_id = int(ciudadano.nacionalidad)
        except (TypeError, ValueError):
            nacionalidad_id = None

        nacionalidad_nombre = nacionalidades.get(nacionalidad_id) or ciudadano.nacionalidad or ""

        if nacionalidad_nombre != ciudadano.nacionalidad:
            Ciudadano.objects.filter(pk=ciudadano.pk).update(
                nacionalidad=nacionalidad_nombre
            )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comedores", "0013_alter_nomina_estado"),
        ("core", "0002_alter_provincia_nombre"),
        ("ciudadanos", "0007_alter_ciudadano_documento"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ciudadano",
            options={"ordering": ["apellido", "nombre"]},
        ),
        migrations.AlterModelOptions(
            name="grupofamiliar",
            options={"ordering": ["ciudadano_1", "ciudadano_2"]},
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    drop_obsolete_indexes, reverse_code=migrations.RunPython.noop
                )
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name="ciudadano",
                    name="ciudadanos__apellid_8f0c3b_idx",
                ),
                migrations.RemoveIndex(
                    model_name="ciudadano",
                    name="ciudadanos__fecha_n_aa8772_idx",
                ),
                migrations.RemoveIndex(
                    model_name="ciudadano",
                    name="ciudadanos__observa_517ba3_idx",
                ),
                migrations.RemoveIndex(
                    model_name="grupofamiliar",
                    name="ciudadanos__ciudada_0b736a_idx",
                ),
                migrations.RemoveIndex(
                    model_name="grupofamiliar",
                    name="ciudadanos__ciudada_547f88_idx",
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    cleanup_ciudadano_fields, reverse_code=migrations.RunPython.noop
                )
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="ciudadano",
                    name="alertas",
                ),
                migrations.RemoveField(
                    model_name="ciudadano",
                    name="circuito",
                ),
                migrations.RemoveField(
                    model_name="ciudadano",
                    name="demo_centro_familia",
                ),
                migrations.RemoveField(
                    model_name="ciudadano",
                    name="escalera_manzana",
                ),
                migrations.RemoveField(
                    model_name="ciudadano",
                    name="estado",
                ),
                migrations.RemoveField(
                    model_name="ciudadano",
                    name="estado_civil",
                ),
                migrations.RemoveField(
                    model_name="ciudadano",
                    name="latitud",
                ),
                migrations.RemoveField(
                    model_name="ciudadano",
                    name="longitud",
                ),
                migrations.RemoveField(
                    model_name="ciudadano",
                    name="torre_pasillo",
                ),
                migrations.RemoveField(
                    model_name="grupofamiliar",
                    name="vinculo_inverso",
                ),
            ],
        ),
        migrations.AddField(
            model_name="ciudadano",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="ciudadano",
            name="barrio",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="grupofamiliar",
            name="creado",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="grupofamiliar",
            name="modificado",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="altura",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="calle",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="codigo_postal",
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="creado",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ciudadano_creado_por",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="documento",
            field=models.PositiveBigIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="modificado",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="modificado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ciudadano_modificado_por",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="nacionalidad",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(
            copy_nacionalidad_to_text, reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="observaciones",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="piso_departamento",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="sexo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.sexo",
            ),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="telefono",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="telefono_alternativo",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("DNI", "DNI"),
                    ("CUIT", "CUIT"),
                    ("PASAPORTE", "Pasaporte"),
                    ("LE", "Libreta de enrolamiento"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="grupofamiliar",
            name="ciudadano_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relaciones_salientes",
                to="ciudadanos.ciudadano",
            ),
        ),
        migrations.AlterField(
            model_name="grupofamiliar",
            name="ciudadano_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relaciones_entrantes",
                to="ciudadanos.ciudadano",
            ),
        ),
        migrations.AlterField(
            model_name="grupofamiliar",
            name="conviven",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="grupofamiliar",
            name="cuidador_principal",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="grupofamiliar",
            name="estado_relacion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("bueno", "Bueno"),
                    ("regular", "Regular"),
                    ("conflictivo", "Conflictivo"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="grupofamiliar",
            name="observaciones",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="grupofamiliar",
            name="vinculo",
            field=models.CharField(
                choices=[
                    ("PADRE/MADRE", "Padre/Madre"),
                    ("HIJO/A", "Hijo/a"),
                    ("PAREJA", "Pareja"),
                    ("HERMANO/A", "Hermano/a"),
                    ("TUTOR/A", "Tutor/a"),
                    ("OTRO", "Otro"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="ciudadano",
            index=models.Index(
                fields=["apellido", "nombre"], name="ciudadanos__apellid_02f758_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grupofamiliar",
            index=models.Index(
                fields=["ciudadano_1"], name="ciudadanos__ciudada_0b736a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grupofamiliar",
            index=models.Index(
                fields=["ciudadano_2"], name="ciudadanos__ciudada_547f88_idx"
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    drop_legacy_tables, reverse_code=migrations.RunPython.noop
                )
            ],
            state_operations=[
                migrations.DeleteModel(
                    name="Condicion",
                ),
                migrations.DeleteModel(
                    name="ActividadRealizada",
                ),
                migrations.DeleteModel(
                    name="Agua",
                ),
                migrations.DeleteModel(
                    name="Alerta",
                ),
                migrations.DeleteModel(
                    name="AportesJubilacion",
                ),
                migrations.DeleteModel(
                    name="Archivo",
                ),
                migrations.DeleteModel(
                    name="AreaCurso",
                ),
                migrations.DeleteModel(
                    name="AsisteEscuela",
                ),
                migrations.DeleteModel(
                    name="CantidadAmbientes",
                ),
                migrations.DeleteModel(
                    name="CategoriaAlerta",
                ),
                migrations.DeleteModel(
                    name="CentrosSalud",
                ),
                migrations.DeleteModel(
                    name="Circuito",
                ),
                migrations.DeleteModel(
                    name="CiudadanoPrograma",
                ),
                migrations.DeleteModel(
                    name="Derivacion",
                ),
                migrations.DeleteModel(
                    name="Desague",
                ),
                migrations.DeleteModel(
                    name="Dimension",
                ),
                migrations.DeleteModel(
                    name="DimensionEconomia",
                ),
                migrations.DeleteModel(
                    name="DimensionEducacion",
                ),
                migrations.DeleteModel(
                    name="DimensionFamilia",
                ),
                migrations.DeleteModel(
                    name="DimensionSalud",
                ),
                migrations.DeleteModel(
                    name="DimensionTrabajo",
                ),
                migrations.DeleteModel(
                    name="DimensionVivienda",
                ),
                migrations.DeleteModel(
                    name="Direccion",
                ),
                migrations.DeleteModel(
                    name="DuracionTrabajo",
                ),
                migrations.DeleteModel(
                    name="EstadoCivil",
                ),
                migrations.DeleteModel(
                    name="EstadoDerivacion",
                ),
                migrations.DeleteModel(
                    name="EstadoIntervencion",
                ),
                migrations.DeleteModel(
                    name="EstadoLlamado",
                ),
                migrations.DeleteModel(
                    name="EstadoNivelEducativo",
                ),
                migrations.DeleteModel(
                    name="EstadoRelacion",
                ),
                migrations.DeleteModel(
                    name="Frecuencia",
                ),
                migrations.DeleteModel(
                    name="Gas",
                ),
                migrations.DeleteModel(
                    name="Grado",
                ),
                migrations.DeleteModel(
                    name="GrupoHogar",
                ),
                migrations.DeleteModel(
                    name="HistorialAlerta",
                ),
                migrations.DeleteModel(
                    name="HistorialCiudadanoProgramas",
                ),
                migrations.DeleteModel(
                    name="Importancia",
                ),
                migrations.DeleteModel(
                    name="Inodoro",
                ),
                migrations.DeleteModel(
                    name="InstitucionEducativas",
                ),
                migrations.DeleteModel(
                    name="Intervencion",
                ),
                migrations.DeleteModel(
                    name="Jurisdiccion",
                ),
                migrations.DeleteModel(
                    name="Llamado",
                ),
                migrations.DeleteModel(
                    name="ModoContratacion",
                ),
                migrations.DeleteModel(
                    name="MotivoNivelIncompleto",
                ),
                migrations.DeleteModel(
                    name="Nacionalidad",
                ),
                migrations.DeleteModel(
                    name="NivelEducativo",
                ),
                migrations.DeleteModel(
                    name="NobusquedaLaboral",
                ),
                migrations.DeleteModel(
                    name="Organismo",
                ),
                migrations.DeleteModel(
                    name="PlanSocial",
                ),
                migrations.DeleteModel(
                    name="Programa",
                ),
                migrations.DeleteModel(
                    name="ProgramasLlamados",
                ),
                migrations.DeleteModel(
                    name="Rechazo",
                ),
                migrations.DeleteModel(
                    name="Secretarias",
                ),
                migrations.DeleteModel(
                    name="SubIntervencion",
                ),
                migrations.DeleteModel(
                    name="Subsecretarias",
                ),
                migrations.DeleteModel(
                    name="SubtipoLlamado",
                ),
                migrations.DeleteModel(
                    name="TiempoBusquedaLaboral",
                ),
                migrations.DeleteModel(
                    name="TipoConstruccionVivienda",
                ),
                migrations.DeleteModel(
                    name="TipoDocumento",
                ),
                migrations.DeleteModel(
                    name="TipoGestion",
                ),
                migrations.DeleteModel(
                    name="TipoIntervencion",
                ),
                migrations.DeleteModel(
                    name="TipoLlamado",
                ),
                migrations.DeleteModel(
                    name="TipoOrganismo",
                ),
                migrations.DeleteModel(
                    name="TipoPisosVivienda",
                ),
                migrations.DeleteModel(
                    name="TipoPosesionVivienda",
                ),
                migrations.DeleteModel(
                    name="TipoTechoVivienda",
                ),
                migrations.DeleteModel(
                    name="TipoVivienda",
                ),
                migrations.DeleteModel(
                    name="Turno",
                ),
                migrations.DeleteModel(
                    name="UbicacionVivienda",
                ),
                migrations.DeleteModel(
                    name="VinculoFamiliar",
                ),
            ],
        ),
    ]
