# Generated by Django 4.2.20 on 2025-11-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ciudadanos", "0008_alter_ciudadano_documento"),
        ("ciudadanos", "0009_remove_unused_models"),
    ]

    operations = []
