# Generated by Django 4.2.20 on 2025-11-25 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ciudadanos", "0010_merge_20251125_1049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ciudadano",
            name="documento",
            field=models.PositiveBigIntegerField(
                default="", validators=[django.core.validators.MinValueValidator(1)]
            ),
            preserve_default=False,
        ),
    ]
