# Generated by Django 4.2.20 on 2025-01-30

from django.db import migrations

TIPO_DOC_DEFAULT = "DNI"


def _normalize_tipo_documento(raw):
    value = (raw or "").strip().upper()
    if value in {"DNI", "D.N.I", "D.N.I.", "DOCUMENTO", "DOC"}:
        return "DNI"
    if value in {"CUIT", "C.U.I.T", "C.U.I.T."}:
        return "CUIT"
    if value in {"PASAPORTE", "PASSPORT"}:
        return "PASAPORTE"
    if value in {"LE", "L.E", "L.E.", "LIBRETA DE ENROLAMIENTO"}:
        return "LE"
    return value[:20] or TIPO_DOC_DEFAULT


def ensure_tipo_documento_column(apps, schema_editor):
    connection = schema_editor.connection
    quote_name = connection.ops.quote_name
    ciudadano_table = "ciudadanos_ciudadano"
    tipo_doc_table = "ciudadanos_tipodocumento"

    with connection.cursor() as cursor:
        table_names = set(connection.introspection.table_names(cursor))
        if ciudadano_table not in table_names:
            return

        columns = {
            col.name
            for col in connection.introspection.get_table_description(
                cursor, ciudadano_table
            )
        }
        has_tipo_documento = "tipo_documento" in columns
        has_tipo_documento_id = "tipo_documento_id" in columns

        if not has_tipo_documento:
            cursor.execute(
                f"ALTER TABLE {quote_name(ciudadano_table)} "
                f"ADD COLUMN {quote_name('tipo_documento')} "
                "varchar(20) NOT NULL DEFAULT %s",
                [TIPO_DOC_DEFAULT],
            )
            has_tipo_documento = True

        if has_tipo_documento_id:
            mapping = {}
            if tipo_doc_table in table_names:
                cursor.execute(
                    f"SELECT id, tipo FROM {quote_name(tipo_doc_table)}"
                )
                mapping = {
                    pk: _normalize_tipo_documento(tipo) for pk, tipo in cursor.fetchall()
                }

            if mapping:
                cases = " ".join(["WHEN %s THEN %s"] * len(mapping))
                sql = (
                    f"UPDATE {quote_name(ciudadano_table)} "
                    f"SET {quote_name('tipo_documento')} = CASE tipo_documento_id "
                    f"{cases} ELSE {quote_name('tipo_documento')} END "
                    "WHERE tipo_documento_id IS NOT NULL"
                )
                params = []
                for pk, tipo in mapping.items():
                    params.extend([pk, tipo])
                cursor.execute(sql, params)
            else:
                cursor.execute(
                    f"UPDATE {quote_name(ciudadano_table)} "
                    f"SET {quote_name('tipo_documento')} = "
                    "LEFT(CAST(tipo_documento_id AS CHAR(20)), 20) "
                    "WHERE tipo_documento_id IS NOT NULL",
                )

            cursor.execute(
                f"ALTER TABLE {quote_name(ciudadano_table)} "
                f"DROP COLUMN {quote_name('tipo_documento_id')}"
            )

        constraints = connection.introspection.get_constraints(cursor, ciudadano_table)
        target_columns = {"tipo_documento", "documento"}
        has_unique = any(
            details.get("unique") and set(details.get("columns", [])) == target_columns
            for details in constraints.values()
        )
        if has_tipo_documento and not has_unique:
            constraint_name = "ciudadano_tipo_doc_doc_uniq"
            max_length = connection.ops.max_name_length()
            if max_length:
                constraint_name = constraint_name[:max_length]
            cursor.execute(
                f"ALTER TABLE {quote_name(ciudadano_table)} "
                f"ADD CONSTRAINT {quote_name(constraint_name)} UNIQUE "
                f"({quote_name('tipo_documento')}, {quote_name('documento')})"
            )


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("ciudadanos", "0011_alter_ciudadano_documento"),
    ]

    operations = [
        migrations.RunPython(
            ensure_tipo_documento_column,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
