# Generated by Django 4.2.27 on 2026-04-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ciudadanos", "0022_alter_ciudadano_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ciudadano",
            name="telefono",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="telefono_alternativo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
