# Generated by Django 5.2.16 on 2026-08-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ciudadanos",
            "0029_ciudadano_estado_revision_manual_squashed_0030_ciudadanos_import_jobs",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ciudadano",
            name="en_situacion_de_calle",
            field=models.CharField(
                blank=True,
                choices=[("SI", "Sí"), ("NO", "No")],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ciudadano",
            name="persona_con_celiaquia",
            field=models.CharField(
                blank=True,
                choices=[("SI", "Sí"), ("NO", "No")],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ciudadano",
            name="pertenece_comunidad_indigena",
            field=models.CharField(
                blank=True,
                choices=[("SI", "Sí"), ("NO", "No")],
                max_length=5,
                null=True,
            ),
        ),
    ]
