# Generated by Django 5.2.16 on 2026-09-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ciudadanos", "0031_ciudadano_en_situacion_de_calle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ciudadano",
            name="documento_pasaporte",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="ciudadano",
            name="pais_emisor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="ciudadano",
            index=models.Index(
                fields=["deleted_at", "tipo_documento", "documento_pasaporte"],
                name="ciud_delpas_idx",
            ),
        ),
    ]
