# Generated by Django 5.2.16 on 2026-08-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ciudadanos", "0031_ciudadano_en_situacion_de_calle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ciudadano",
            name="en_situacion_de_calle",
            field=models.CharField(
                blank=True,
                choices=[("SI", "Sí"), ("NO", "No")],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="persona_con_celiaquia",
            field=models.CharField(
                blank=True,
                choices=[("SI", "Sí"), ("NO", "No")],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ciudadano",
            name="pertenece_comunidad_indigena",
            field=models.CharField(
                blank=True,
                choices=[("SI", "Sí"), ("NO", "No")],
                max_length=5,
                null=True,
            ),
        ),
    ]
