# Generated by Django 4.2.20 on 2025-08-23 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        (
            "ciudadanos",
            "0002_alter_ciudadano_localidad_alter_ciudadano_municipio_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadoExpediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Estado del Expediente",
                "verbose_name_plural": "Estados del Expediente",
            },
        ),
        migrations.CreateModel(
            name="EstadoLegajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Estado del Legajo",
                "verbose_name_plural": "Estados del Legajo",
            },
        ),
        migrations.CreateModel(
            name="Expediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "excel_masivo",
                    models.FileField(
                        blank=True, null=True, upload_to="expedientes/masivos/"
                    ),
                ),
                (
                    "cruce_excel",
                    models.FileField(
                        blank=True, null=True, upload_to="expedientes/cruces/"
                    ),
                ),
                (
                    "documento",
                    models.FileField(
                        blank=True, null=True, upload_to="expedientes/prd/"
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expedientes",
                        to="celiaquia.estadoexpediente",
                    ),
                ),
                (
                    "usuario_modificador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expedientes_modificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_provincia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expedientes_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expediente",
                "verbose_name_plural": "Expedientes",
            },
        ),
        migrations.CreateModel(
            name="Organismo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Organismo de Cruce",
                "verbose_name_plural": "Organismos de Cruce",
            },
        ),
        migrations.CreateModel(
            name="TipoCruce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "verbose_name": "Tipo de Cruce",
                "verbose_name_plural": "Tipos de Cruce",
            },
        ),
        migrations.CreateModel(
            name="ProvinciaCupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_asignado", models.PositiveIntegerField(default=0)),
                ("usados", models.PositiveIntegerField(default=0)),
                (
                    "provincia",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cupo",
                        to="core.provincia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cupo por Provincia",
                "verbose_name_plural": "Cupos por Provincia",
            },
        ),
        migrations.CreateModel(
            name="ExpedienteCiudadano",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo1",
                    models.FileField(
                        blank=True, null=True, upload_to="legajos/archivos/"
                    ),
                ),
                (
                    "archivo2",
                    models.FileField(
                        blank=True, null=True, upload_to="legajos/archivos/"
                    ),
                ),
                (
                    "archivo3",
                    models.FileField(
                        blank=True, null=True, upload_to="legajos/archivos/"
                    ),
                ),
                ("cruce_ok", models.BooleanField(blank=True, null=True)),
                (
                    "observacion_cruce",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("modificado_en", models.DateTimeField(auto_now=True)),
                (
                    "revision_tecnico",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADO", "Aprobado por técnico"),
                            ("RECHAZADO", "Rechazado por técnico"),
                            ("SUBSANAR", "Solicitar subsanación"),
                            (
                                "PENDIENTE_SUBSANACION",
                                "Enviado por provincia (pendiente de revisión)",
                            ),
                        ],
                        default="PENDIENTE",
                        max_length=24,
                    ),
                ),
                (
                    "resultado_sintys",
                    models.CharField(
                        choices=[
                            ("SIN_CRUCE", "Sin cruce"),
                            ("MATCH", "Matcheado"),
                            ("NO_MATCH", "No matcheado"),
                        ],
                        default="SIN_CRUCE",
                        max_length=10,
                    ),
                ),
                (
                    "estado_cupo",
                    models.CharField(
                        choices=[
                            ("NO_EVAL", "No evaluado"),
                            ("DENTRO", "Dentro de cupo"),
                            ("FUERA", "Fuera de cupo"),
                        ],
                        default="NO_EVAL",
                        max_length=8,
                    ),
                ),
                ("es_titular_activo", models.BooleanField(default=False)),
                ("subsanacion_motivo", models.TextField(blank=True, null=True)),
                (
                    "subsanacion_solicitada_en",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("subsanacion_enviada_en", models.DateTimeField(blank=True, null=True)),
                (
                    "ciudadano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expedientes",
                        to="ciudadanos.ciudadano",
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expediente_ciudadanos",
                        to="celiaquia.estadolegajo",
                    ),
                ),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expediente_ciudadanos",
                        to="celiaquia.expediente",
                    ),
                ),
                (
                    "subsanacion_usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subsanaciones_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expediente Ciudadano",
                "verbose_name_plural": "Expedientes Ciudadano",
                "unique_together": {("expediente", "ciudadano")},
            },
        ),
        migrations.CreateModel(
            name="CupoMovimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ALTA", "Alta"),
                            ("BAJA", "Baja"),
                            ("AJUSTE", "Ajuste"),
                        ],
                        max_length=10,
                    ),
                ),
                ("delta", models.IntegerField()),
                ("motivo", models.CharField(blank=True, max_length=255)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "expediente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos_cupo",
                        to="celiaquia.expediente",
                    ),
                ),
                (
                    "legajo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos_cupo",
                        to="celiaquia.expedienteciudadano",
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos_cupo",
                        to="core.provincia",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimientos_cupo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Cupo",
                "verbose_name_plural": "Movimientos de Cupo",
                "ordering": ("-creado_en",),
            },
        ),
        migrations.CreateModel(
            name="AsignacionTecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                (
                    "expediente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignacion_tecnico",
                        to="celiaquia.expediente",
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expedientes_asignados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación de Técnico",
                "verbose_name_plural": "Asignaciones de Técnico",
            },
        ),
    ]
