# Generated by Django 4.2.20 on 2025-06-06 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadoExpediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Estado del Expediente",
                "verbose_name_plural": "Estados del Expediente",
            },
        ),
        migrations.CreateModel(
            name="Expediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provincia", models.CharField(max_length=255)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="celiaquia.estadoexpediente",
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expedientes_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Expediente",
                "verbose_name_plural": "Expedientes",
            },
        ),
        migrations.CreateModel(
            name="ResultadoCruce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dni", models.CharField(max_length=20)),
                (
                    "estado",
                    models.CharField(
                        choices=[("aceptado", "Aceptado"), ("rechazado", "Rechazado")],
                        max_length=10,
                    ),
                ),
                ("motivo_rechazo", models.TextField(blank=True, null=True)),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="celiaquia.expediente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonaFormulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("apellido", models.CharField(max_length=255)),
                ("dni", models.CharField(max_length=20)),
                ("sexo", models.CharField(max_length=10)),
                ("fecha_nacimiento", models.DateField()),
                ("datos_complementarios", models.JSONField(blank=True, null=True)),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personas",
                        to="celiaquia.expediente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InformePago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pago", models.DateField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "expediente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="celiaquia.expediente",
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Informe de Pago",
                "verbose_name_plural": "Informes de Pago",
            },
        ),
        migrations.CreateModel(
            name="AsignacionTecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_asignacion", models.DateTimeField(auto_now_add=True)),
                (
                    "expediente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="celiaquia.expediente",
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expedientes_asignados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArchivoCruce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="cruces/")),
                (
                    "organismo",
                    models.CharField(
                        choices=[
                            ("syntis", "Syntis"),
                            ("salud", "Salud"),
                            ("renaper", "Renaper"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("aprobado", "Aprobado"), ("rechazado", "Rechazado")],
                        max_length=10,
                    ),
                ),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "expediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archivos_cruce",
                        to="celiaquia.expediente",
                    ),
                ),
            ],
        ),
    ]
