# Generated by Django 4.2.20 on 2025-09-26 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("celiaquia", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expediente",
            name="numero_expediente",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="expedienteciudadano",
            name="estado_validacion_renaper",
            field=models.IntegerField(
                db_index=True,
                default=0,
                help_text="0=no validado, 1=aceptado, 2=rechazado, 3=subsanar",
            ),
        ),
        migrations.AddField(
            model_name="expedienteciudadano",
            name="subsanacion_renaper_archivo",
            field=models.FileField(
                blank=True,
                help_text="Archivo de respuesta a subsanación Renaper",
                null=True,
                upload_to="legajos/subsanacion_renaper/",
            ),
        ),
        migrations.AddField(
            model_name="expedienteciudadano",
            name="subsanacion_renaper_comentario",
            field=models.TextField(
                blank=True,
                help_text="Comentario de respuesta a subsanación Renaper",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="asignaciontecnico",
            name="expediente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asignaciones_tecnicos",
                to="celiaquia.expediente",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="asignaciontecnico",
            unique_together={("expediente", "tecnico")},
        ),
        migrations.AddIndex(
            model_name="asignaciontecnico",
            index=models.Index(fields=["expediente"], name="asig_expediente_idx"),
        ),
        migrations.AddIndex(
            model_name="expedienteciudadano",
            index=models.Index(
                fields=["estado_cupo", "es_titular_activo"], name="leg_cupo_activo_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expedienteciudadano",
            index=models.Index(
                fields=["revision_tecnico", "resultado_sintys"],
                name="leg_rev_sintys_idx",
            ),
        ),
    ]
