# Generated by Django 4.2.20 on 2025-08-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celiaquia", "0002_alter_cupomovimiento_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cupomovimiento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ALTA", "Alta"),
                    ("REACTIVACION", "Reactivacion"),
                    ("BAJA", "Baja"),
                    ("AJUSTE", "Ajuste"),
                    ("SUSPENDIDO", "Suspendido"),
                ],
                max_length=20,
            ),
        ),
    ]
