# Generated by Django 4.2.20 on 2025-09-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celiaquia", "0002_expediente_numero_expediente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expedienteciudadano",
            name="estado_validacion_renaper",
            field=models.IntegerField(
                db_index=True,
                default=0,
                help_text="0=no validado, 1=aceptado, 2=rechazado, 3=subsanar",
            ),
        ),
        migrations.AddField(
            model_name="expedienteciudadano",
            name="subsanacion_renaper_archivo",
            field=models.FileField(
                blank=True,
                help_text="Archivo de respuesta a subsanación Renaper",
                null=True,
                upload_to="legajos/subsanacion_renaper/",
            ),
        ),
        migrations.AddField(
            model_name="expedienteciudadano",
            name="subsanacion_renaper_comentario",
            field=models.TextField(
                blank=True,
                help_text="Comentario de respuesta a subsanación Renaper",
                null=True,
            ),
        ),
    ]
