# Generated by Django 4.2.20 on 2025-08-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "celiaquia",
            "0002_estadolegajo_expedienteciudadano_organismo_tipocruce_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="informepago",
            name="expediente",
        ),
        migrations.RemoveField(
            model_name="informepago",
            name="tecnico",
        ),
        migrations.RemoveField(
            model_name="resultadocruce",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="resultadocruce",
            name="expediente",
        ),
        migrations.RemoveField(
            model_name="resultadocruce",
            name="expediente_ciudadano",
        ),
        migrations.RemoveField(
            model_name="resultadocruce",
            name="organismo",
        ),
        migrations.DeleteModel(
            name="ArchivoCruce",
        ),
        migrations.DeleteModel(
            name="InformePago",
        ),
        migrations.DeleteModel(
            name="ResultadoCruce",
        ),
    ]
