# Generated by Django 4.2.20 on 2025-08-27 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
        ("celiaquia", "0003_alter_cupomovimiento_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="PagoExpediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periodo",
                    models.CharField(db_index=True, help_text="YYYY-MM", max_length=7),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("ENVIADO", "Enviado a Sintys"),
                            ("PROCESADO", "Cruce procesado"),
                            ("CERRADO", "Cerrado"),
                        ],
                        default="BORRADOR",
                        max_length=12,
                    ),
                ),
                (
                    "archivo_envio",
                    models.FileField(blank=True, null=True, upload_to="pagos/envios/"),
                ),
                (
                    "archivo_respuesta",
                    models.FileField(
                        blank=True, null=True, upload_to="pagos/respuestas/"
                    ),
                ),
                ("total_candidatos", models.PositiveIntegerField(default=0)),
                ("total_validados", models.PositiveIntegerField(default=0)),
                ("total_excluidos", models.PositiveIntegerField(default=0)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("modificado_en", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos_modificados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos_expedientes",
                        to="core.provincia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Expediente de Pago",
                "verbose_name_plural": "Expedientes de Pago",
                "ordering": ("-creado_en", "pk"),
            },
        ),
        migrations.CreateModel(
            name="PagoNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("documento", models.CharField(db_index=True, max_length=16)),
                ("nombre", models.CharField(blank=True, max_length=80)),
                ("apellido", models.CharField(blank=True, max_length=80)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("VALIDADO", "Validado para pago"),
                            ("EXCLUIDO", "Excluido por cruce"),
                        ],
                        default="VALIDADO",
                        max_length=12,
                    ),
                ),
                ("observacion", models.CharField(blank=True, max_length=255)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "legajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos",
                        to="celiaquia.expedienteciudadano",
                    ),
                ),
                (
                    "pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nomina",
                        to="celiaquia.pagoexpediente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fila nómina de pago",
                "verbose_name_plural": "Nómina de pago",
                "indexes": [
                    models.Index(
                        fields=["pago", "estado"], name="pago_nomina_estado_idx"
                    ),
                    models.Index(fields=["documento"], name="pago_nomina_doc_idx"),
                ],
                "unique_together": {("pago", "legajo")},
            },
        ),
        migrations.AddIndex(
            model_name="pagoexpediente",
            index=models.Index(
                fields=["provincia", "periodo", "estado"],
                name="pago_prov_per_estado_idx",
            ),
        ),
    ]
