# Generated by Django 4.2.20 on 2025-08-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celiaquia", "0003_remove_informepago_expediente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expediente",
            name="cruce_excel",
            field=models.FileField(
                blank=True, null=True, upload_to="expedientes/cruces/"
            ),
        ),
        migrations.AddField(
            model_name="expediente",
            name="documento",
            field=models.FileField(blank=True, null=True, upload_to="expedientes/prd/"),
        ),
        migrations.AddField(
            model_name="expedienteciudadano",
            name="cruce_ok",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expedienteciudadano",
            name="observacion_cruce",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
