# Generated by Django 4.2.20 on 2025-08-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celiaquia", "0004_expediente_cruce_excel_expediente_documento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expedienteciudadano",
            name="resultado_sintys",
            field=models.CharField(
                choices=[
                    ("SIN_CRUCE", "Sin cruce"),
                    ("MATCH", "Matcheado"),
                    ("NO_MATCH", "No matcheado"),
                ],
                default="SIN_CRUCE",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="expedienteciudadano",
            name="revision_tecnico",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("APROBADO", "Aprobado por técnico"),
                    ("RECHAZADO", "Rechazado por técnico"),
                ],
                default="PENDIENTE",
                max_length=10,
            ),
        ),
    ]
