# Generated by Django 5.2.16 on 2026-08-27 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("celiaquia", "0004_historialcomentarios_es_interno_db_default"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="expediente",
            options={
                "ordering": ("-fecha_creacion", "pk"),
                "permissions": [
                    (
                        "view_cupo_dashboard",
                        "Puede ver el Dashboard de Cupos de Celiaquía",
                    ),
                    (
                        "view_reporte_provincias",
                        "Puede ver el Reporte por provincias de Celiaquía",
                    ),
                ],
                "verbose_name": "Expediente",
                "verbose_name_plural": "Expedientes",
            },
        ),
    ]
