# Generated by Django 4.2.27 on 2026-01-30 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "ciudadanos",
            "0020_remove_historialtransferencia_unique_historial_ciudadano_mes_anio_and_more",
        ),
        ("celiaquia", "0005_add_rol_and_new_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="CruceResultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resultado_sintys",
                    models.CharField(
                        choices=[
                            ("SIN_CRUCE", "Sin cruce"),
                            ("MATCH", "Matcheado"),
                            ("NO_MATCH", "No matcheado"),
                        ],
                        default="SIN_CRUCE",
                        max_length=10,
                    ),
                ),
                ("cruce_ok", models.BooleanField(blank=True, null=True)),
                (
                    "observacion_cruce",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("modificado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Resultado de Cruce",
                "verbose_name_plural": "Resultados de Cruce",
            },
        ),
        migrations.CreateModel(
            name="CupoTitular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_cupo",
                    models.CharField(
                        choices=[
                            ("NO_EVAL", "No evaluado"),
                            ("DENTRO", "Dentro de cupo"),
                            ("FUERA", "Fuera de cupo"),
                        ],
                        default="NO_EVAL",
                        max_length=8,
                    ),
                ),
                ("es_titular_activo", models.BooleanField(default=False)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("modificado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cupo Titular",
                "verbose_name_plural": "Cupos Titulares",
            },
        ),
        migrations.CreateModel(
            name="DocumentoLegajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="legajos/documentos/")),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
                ("observaciones", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Documento de Legajo",
                "verbose_name_plural": "Documentos de Legajo",
                "ordering": ["-fecha_carga"],
            },
        ),
        migrations.CreateModel(
            name="HistorialComentarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_comentario",
                    models.CharField(
                        choices=[
                            ("VALIDACION_TECNICA", "Validación Técnica"),
                            ("SUBSANACION_MOTIVO", "Motivo de Subsanación"),
                            ("SUBSANACION_RESPUESTA", "Respuesta de Subsanación"),
                            ("RENAPER_VALIDACION", "Validación RENAPER"),
                            ("OBSERVACION_GENERAL", "Observación General"),
                            ("CRUCE_SINTYS", "Cruce SINTYS"),
                            ("PAGO_OBSERVACION", "Observación de Pago"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("comentario", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "archivo_adjunto",
                    models.FileField(blank=True, null=True, upload_to="comentarios/"),
                ),
                (
                    "estado_relacionado",
                    models.CharField(
                        blank=True,
                        help_text="Estado del legajo al momento del comentario",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Comentarios",
                "verbose_name_plural": "Historial de Comentarios",
                "ordering": ("-fecha_creacion",),
            },
        ),
        migrations.CreateModel(
            name="HistorialCupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_cupo_anterior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NO_EVAL", "No evaluado"),
                            ("DENTRO", "Dentro de cupo"),
                            ("FUERA", "Fuera de cupo"),
                        ],
                        max_length=8,
                        null=True,
                    ),
                ),
                (
                    "estado_cupo_nuevo",
                    models.CharField(
                        choices=[
                            ("NO_EVAL", "No evaluado"),
                            ("DENTRO", "Dentro de cupo"),
                            ("FUERA", "Fuera de cupo"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "es_titular_activo_anterior",
                    models.BooleanField(blank=True, null=True),
                ),
                ("es_titular_activo_nuevo", models.BooleanField()),
                (
                    "tipo_movimiento",
                    models.CharField(
                        choices=[
                            ("ALTA", "Alta"),
                            ("REACTIVACION", "Reactivacion"),
                            ("BAJA", "Baja"),
                            ("AJUSTE", "Ajuste"),
                            ("SUSPENDIDO", "Suspendido"),
                        ],
                        max_length=20,
                    ),
                ),
                ("motivo", models.TextField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Historial Cupo",
                "verbose_name_plural": "Historiales Cupo",
                "ordering": ("-creado_en",),
            },
        ),
        migrations.CreateModel(
            name="HistorialValidacionTecnica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_anterior",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADO", "Aprobado por el tecnico"),
                            ("RECHAZADO", "Rechazado por el tecnico"),
                            ("SUBSANAR", "Subsanar"),
                            ("SUBSANADO", "Subsanado"),
                        ],
                        max_length=24,
                        null=True,
                    ),
                ),
                (
                    "estado_nuevo",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADO", "Aprobado por el tecnico"),
                            ("RECHAZADO", "Rechazado por el tecnico"),
                            ("SUBSANAR", "Subsanar"),
                            ("SUBSANADO", "Subsanado"),
                        ],
                        max_length=24,
                    ),
                ),
                ("motivo", models.TextField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Historial Validación Técnica",
                "verbose_name_plural": "Historiales Validación Técnica",
                "ordering": ("-creado_en",),
            },
        ),
        migrations.CreateModel(
            name="RegistroErroneoReprocesado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intento_numero", models.PositiveIntegerField()),
                (
                    "resultado",
                    models.CharField(
                        choices=[("EXITOSO", "Exitoso"), ("FALLIDO", "Fallido")],
                        max_length=10,
                    ),
                ),
                ("error_mensaje", models.TextField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Registro Erróneo Reprocesado",
                "verbose_name_plural": "Registros Erróneos Reprocesados",
                "ordering": ("-creado_en",),
            },
        ),
        migrations.CreateModel(
            name="SubsanacionRespuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo1",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="legajos/subsanacion_respuesta/",
                    ),
                ),
                (
                    "archivo2",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="legajos/subsanacion_respuesta/",
                    ),
                ),
                (
                    "archivo3",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="legajos/subsanacion_respuesta/",
                    ),
                ),
                ("comentario", models.TextField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Respuesta de Subsanación",
                "verbose_name_plural": "Respuestas de Subsanación",
                "ordering": ("-creado_en",),
            },
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("requerido", models.BooleanField(default=True)),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0, help_text="Orden de presentación"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipo de Documento",
                "verbose_name_plural": "Tipos de Documento",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ValidacionRenaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_validacion",
                    models.IntegerField(
                        choices=[
                            (0, "No validado"),
                            (1, "Aceptado"),
                            (2, "Rechazado"),
                            (3, "Subsanar"),
                        ],
                        default=0,
                    ),
                ),
                ("comentario", models.TextField(blank=True, null=True)),
                (
                    "archivo",
                    models.FileField(
                        blank=True, null=True, upload_to="legajos/subsanacion_renaper/"
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("modificado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Validación Renaper",
                "verbose_name_plural": "Validaciones Renaper",
            },
        ),
        migrations.CreateModel(
            name="ValidacionTecnica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revision_tecnico",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("APROBADO", "Aprobado por el tecnico"),
                            ("RECHAZADO", "Rechazado por el tecnico"),
                            ("SUBSANAR", "Subsanar"),
                            ("SUBSANADO", "Subsanado"),
                        ],
                        default="PENDIENTE",
                        max_length=24,
                    ),
                ),
                ("subsanacion_motivo", models.TextField(blank=True, null=True)),
                (
                    "subsanacion_solicitada_en",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("subsanacion_enviada_en", models.DateTimeField(blank=True, null=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("modificado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Validación Técnica",
                "verbose_name_plural": "Validaciones Técnicas",
            },
        ),
        migrations.RemoveIndex(
            model_name="asignaciontecnico",
            name="asig_tecnico_idx",
        ),
        migrations.RemoveIndex(
            model_name="asignaciontecnico",
            name="asig_expediente_idx",
        ),
        migrations.AddField(
            model_name="asignaciontecnico",
            name="activa",
            field=models.BooleanField(
                default=True, help_text="Indica si la asignación está activa"
            ),
        ),
        migrations.AddField(
            model_name="expedienteciudadano",
            name="rol",
            field=models.CharField(
                choices=[
                    ("beneficiario", "Solo Beneficiario"),
                    ("responsable", "Solo Responsable"),
                    ("beneficiario_y_responsable", "Beneficiario y Responsable"),
                ],
                db_index=True,
                default="beneficiario",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="asignaciontecnico",
            index=models.Index(
                fields=["tecnico", "activa"], name="asig_tecnico_activa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asignaciontecnico",
            index=models.Index(
                fields=["expediente", "activa"], name="asig_expediente_activa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expedienteciudadano",
            index=models.Index(
                fields=["estado_cupo", "es_titular_activo", "rol"],
                name="leg_cupo_activo_rol_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expedienteestadohistorial",
            index=models.Index(
                fields=["expediente", "-fecha"], name="exp_hist_exp_fecha_idx"
            ),
        ),
        migrations.AddField(
            model_name="validaciontecnica",
            name="legajo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="validacion_tecnica",
                to="celiaquia.expedienteciudadano",
            ),
        ),
        migrations.AddField(
            model_name="validaciontecnica",
            name="subsanacion_usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="validaciones_tecnicas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="validacionrenaper",
            name="legajo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="validacion_renaper",
                to="celiaquia.expedienteciudadano",
            ),
        ),
        migrations.AddField(
            model_name="subsanacionrespuesta",
            name="legajo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subsanaciones_respuestas",
                to="celiaquia.expedienteciudadano",
            ),
        ),
        migrations.AddField(
            model_name="subsanacionrespuesta",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subsanaciones_respondidas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subsanacionrespuesta",
            name="validacion_tecnica",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respuestas",
                to="celiaquia.validaciontecnica",
            ),
        ),
        migrations.AddField(
            model_name="registroerroneoreprocesado",
            name="ciudadano_creado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ciudadanos.ciudadano",
            ),
        ),
        migrations.AddField(
            model_name="registroerroneoreprocesado",
            name="legajo_creado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="celiaquia.expedienteciudadano",
            ),
        ),
        migrations.AddField(
            model_name="registroerroneoreprocesado",
            name="registro_erroneo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reprocesados",
                to="celiaquia.registroerroneo",
            ),
        ),
        migrations.AddField(
            model_name="registroerroneoreprocesado",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reprocesados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historialvalidaciontecnica",
            name="legajo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial_validacion_tecnica",
                to="celiaquia.expedienteciudadano",
            ),
        ),
        migrations.AddField(
            model_name="historialvalidaciontecnica",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cambios_validacion_tecnica",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historialcupo",
            name="legajo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial_cupo",
                to="celiaquia.expedienteciudadano",
            ),
        ),
        migrations.AddField(
            model_name="historialcupo",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cambios_cupo",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historialcomentarios",
            name="legajo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial_comentarios",
                to="celiaquia.expedienteciudadano",
            ),
        ),
        migrations.AddField(
            model_name="historialcomentarios",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comentarios_realizados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentolegajo",
            name="legajo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentos",
                to="celiaquia.expedienteciudadano",
            ),
        ),
        migrations.AddField(
            model_name="documentolegajo",
            name="tipo_documento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documentos_legajo",
                to="celiaquia.tipodocumento",
            ),
        ),
        migrations.AddField(
            model_name="documentolegajo",
            name="usuario_carga",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_cargados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cupotitular",
            name="legajo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cupo_titular",
                to="celiaquia.expedienteciudadano",
            ),
        ),
        migrations.AddField(
            model_name="cruceresultado",
            name="legajo",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cruce_resultado",
                to="celiaquia.expedienteciudadano",
            ),
        ),
        migrations.AddIndex(
            model_name="subsanacionrespuesta",
            index=models.Index(
                fields=["legajo", "-creado_en"], name="celiaquia_s_legajo__b876fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subsanacionrespuesta",
            index=models.Index(
                fields=["validacion_tecnica"], name="celiaquia_s_validac_8850b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registroerroneoreprocesado",
            index=models.Index(
                fields=["registro_erroneo", "-creado_en"],
                name="celiaquia_r_registr_dd2d41_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="registroerroneoreprocesado",
            index=models.Index(
                fields=["resultado"], name="celiaquia_r_resulta_7d0d5f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="registroerroneoreprocesado",
            unique_together={("registro_erroneo", "intento_numero")},
        ),
        migrations.AddIndex(
            model_name="historialvalidaciontecnica",
            index=models.Index(
                fields=["legajo", "-creado_en"], name="celiaquia_h_legajo__c4a426_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="historialcupo",
            index=models.Index(
                fields=["legajo", "-creado_en"], name="celiaquia_h_legajo__a5d2e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="historialcupo",
            index=models.Index(
                fields=["tipo_movimiento", "-creado_en"],
                name="celiaquia_h_tipo_mo_4ec6fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="historialcomentarios",
            index=models.Index(
                fields=["legajo", "-fecha_creacion"],
                name="celiaquia_h_legajo__123fc8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="historialcomentarios",
            index=models.Index(
                fields=["tipo_comentario", "-fecha_creacion"],
                name="celiaquia_h_tipo_co_558cb7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="historialcomentarios",
            index=models.Index(
                fields=["usuario", "-fecha_creacion"],
                name="celiaquia_h_usuario_989d09_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentolegajo",
            index=models.Index(
                fields=["legajo", "tipo_documento"],
                name="celiaquia_d_legajo__194cb5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentolegajo",
            index=models.Index(
                fields=["fecha_carga"], name="celiaquia_d_fecha_c_023657_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentolegajo",
            unique_together={("legajo", "tipo_documento")},
        ),
        migrations.AddIndex(
            model_name="cupotitular",
            index=models.Index(
                fields=["estado_cupo", "es_titular_activo"],
                name="celiaquia_c_estado__b13c1c_idx",
            ),
        ),
    ]
