# Generated by Django 4.2.20 on 2025-12-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("celiaquia", "0005_add_rol_and_new_models"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="registroerroneoreprocesado",
            name="celiaquia_registroerroneoreprocesado_unique",
        ),
        migrations.RenameIndex(
            model_name="cupotitular",
            new_name="celiaquia_c_estado__b13c1c_idx",
            old_name="celiaquia_c_estado__idx",
        ),
        migrations.RenameIndex(
            model_name="historialcupo",
            new_name="celiaquia_h_legajo__a5d2e4_idx",
            old_name="celiaquia_h_legajo__idx2",
        ),
        migrations.RenameIndex(
            model_name="historialcupo",
            new_name="celiaquia_h_tipo_mo_4ec6fb_idx",
            old_name="celiaquia_h_tipo_mo__idx",
        ),
        migrations.RenameIndex(
            model_name="historialvalidaciontecnica",
            new_name="celiaquia_h_legajo__c4a426_idx",
            old_name="celiaquia_h_legajo__idx",
        ),
        migrations.RenameIndex(
            model_name="registroerroneoreprocesado",
            new_name="celiaquia_r_registr_dd2d41_idx",
            old_name="celiaquia_r_registr__idx",
        ),
        migrations.RenameIndex(
            model_name="registroerroneoreprocesado",
            new_name="celiaquia_r_resulta_7d0d5f_idx",
            old_name="celiaquia_r_resulta__idx",
        ),
        migrations.RenameIndex(
            model_name="subsanacionrespuesta",
            new_name="celiaquia_s_legajo__b876fc_idx",
            old_name="celiaquia_s_legajo__idx",
        ),
        migrations.RenameIndex(
            model_name="subsanacionrespuesta",
            new_name="celiaquia_s_validac_8850b2_idx",
            old_name="celiaquia_s_validac__idx",
        ),
        migrations.AlterUniqueTogether(
            name="registroerroneoreprocesado",
            unique_together={("registro_erroneo", "intento_numero")},
        ),
    ]
