# Generated by Django 4.2.20 on 2025-08-22 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("celiaquia", "0006_remove_expediente_codigo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CupoMovimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ALTA", "Alta (consumo de cupo)"),
                            ("BAJA", "Baja (liberación de cupo)"),
                            ("AJUSTE", "Ajuste manual"),
                        ],
                        max_length=10,
                    ),
                ),
                ("delta", models.SmallIntegerField(default=0)),
                ("motivo", models.CharField(blank=True, max_length=255)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Movimiento de Cupo",
                "verbose_name_plural": "Movimientos de Cupo",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="ProvinciaCupo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_asignado", models.PositiveIntegerField(default=0)),
                ("usados", models.PositiveIntegerField(default=0)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cupo de Provincia",
                "verbose_name_plural": "Cupos de Provincia",
            },
        ),
        migrations.AddField(
            model_name="expedienteciudadano",
            name="es_titular_activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="expedienteciudadano",
            name="estado_cupo",
            field=models.CharField(
                choices=[
                    ("NO_EVAL", "No evaluado"),
                    ("DENTRO", "Dentro de cupo"),
                    ("FUERA", "Fuera de cupo"),
                ],
                default="NO_EVAL",
                max_length=8,
            ),
        ),
        migrations.AddIndex(
            model_name="expedienteciudadano",
            index=models.Index(
                fields=["expediente", "estado_cupo"],
                name="celiaquia_e_expedie_8bb316_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expedienteciudadano",
            index=models.Index(
                fields=["revision_tecnico", "resultado_sintys"],
                name="celiaquia_e_revisio_7e9aa7_idx",
            ),
        ),
        migrations.AddField(
            model_name="provinciacupo",
            name="provincia",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cupo_provincia",
                to="core.provincia",
            ),
        ),
        migrations.AddField(
            model_name="cupomovimiento",
            name="expediente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimientos_cupo",
                to="celiaquia.expediente",
            ),
        ),
        migrations.AddField(
            model_name="cupomovimiento",
            name="legajo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimientos_cupo",
                to="celiaquia.expedienteciudadano",
            ),
        ),
        migrations.AddField(
            model_name="cupomovimiento",
            name="provincia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimientos_cupo",
                to="core.provincia",
            ),
        ),
        migrations.AddField(
            model_name="cupomovimiento",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="movimientos_cupo_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="cupomovimiento",
            index=models.Index(
                fields=["provincia", "creado_en"], name="celiaquia_c_provinc_a8be80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cupomovimiento",
            index=models.Index(fields=["tipo"], name="celiaquia_c_tipo_d00bfe_idx"),
        ),
    ]
