# Generated by Django 4.2.27 on 2026-01-30 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "celiaquia",
            "0006_remove_registroerroneoreprocesado_celiaquia_registroerroneoreprocesado_unique_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentoLegajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="legajos/documentos/")),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
                ("observaciones", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Documento de Legajo",
                "verbose_name_plural": "Documentos de Legajo",
                "ordering": ["-fecha_carga"],
            },
        ),
        migrations.CreateModel(
            name="HistorialComentarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_comentario",
                    models.CharField(
                        choices=[
                            ("VALIDACION_TECNICA", "Validación Técnica"),
                            ("SUBSANACION_MOTIVO", "Motivo de Subsanación"),
                            ("SUBSANACION_RESPUESTA", "Respuesta de Subsanación"),
                            ("RENAPER_VALIDACION", "Validación RENAPER"),
                            ("OBSERVACION_GENERAL", "Observación General"),
                            ("CRUCE_SINTYS", "Cruce SINTYS"),
                            ("PAGO_OBSERVACION", "Observación de Pago"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("comentario", models.TextField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "archivo_adjunto",
                    models.FileField(blank=True, null=True, upload_to="comentarios/"),
                ),
                (
                    "estado_relacionado",
                    models.CharField(
                        blank=True,
                        help_text="Estado del legajo al momento del comentario",
                        max_length=50,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Comentarios",
                "verbose_name_plural": "Historial de Comentarios",
                "ordering": ("-fecha_creacion",),
            },
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("requerido", models.BooleanField(default=True)),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0, help_text="Orden de presentación"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipo de Documento",
                "verbose_name_plural": "Tipos de Documento",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.RemoveIndex(
            model_name="asignaciontecnico",
            name="asig_tecnico_idx",
        ),
        migrations.RemoveIndex(
            model_name="asignaciontecnico",
            name="asig_expediente_idx",
        ),
        migrations.AddField(
            model_name="asignaciontecnico",
            name="activa",
            field=models.BooleanField(
                default=True, help_text="Indica si la asignación está activa"
            ),
        ),
        migrations.AddIndex(
            model_name="asignaciontecnico",
            index=models.Index(
                fields=["tecnico", "activa"], name="asig_tecnico_activa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asignaciontecnico",
            index=models.Index(
                fields=["expediente", "activa"], name="asig_expediente_activa_idx"
            ),
        ),
        migrations.AddField(
            model_name="historialcomentarios",
            name="legajo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="historial_comentarios",
                to="celiaquia.expedienteciudadano",
            ),
        ),
        migrations.AddField(
            model_name="historialcomentarios",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comentarios_realizados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documentolegajo",
            name="legajo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentos",
                to="celiaquia.expedienteciudadano",
            ),
        ),
        migrations.AddField(
            model_name="documentolegajo",
            name="tipo_documento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="documentos_legajo",
                to="celiaquia.tipodocumento",
            ),
        ),
        migrations.AddField(
            model_name="documentolegajo",
            name="usuario_carga",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_cargados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="historialcomentarios",
            index=models.Index(
                fields=["legajo", "-fecha_creacion"],
                name="celiaquia_h_legajo__123fc8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="historialcomentarios",
            index=models.Index(
                fields=["tipo_comentario", "-fecha_creacion"],
                name="celiaquia_h_tipo_co_558cb7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="historialcomentarios",
            index=models.Index(
                fields=["usuario", "-fecha_creacion"],
                name="celiaquia_h_usuario_989d09_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentolegajo",
            index=models.Index(
                fields=["legajo", "tipo_documento"],
                name="celiaquia_d_legajo__194cb5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentolegajo",
            index=models.Index(
                fields=["fecha_carga"], name="celiaquia_d_fecha_c_023657_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentolegajo",
            unique_together={("legajo", "tipo_documento")},
        ),
    ]
