# Generated by Django 4.2.20 on 2025-12-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("celiaquia", "0007_historialcomentarios"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="historialcomentarios",
            new_name="celiaquia_h_legajo__123fc8_idx",
            old_name="celiaquia_h_legajo_b8b8c8_idx",
        ),
        migrations.RenameIndex(
            model_name="historialcomentarios",
            new_name="celiaquia_h_tipo_co_558cb7_idx",
            old_name="celiaquia_h_tipo_co_86d7a4_idx",
        ),
        migrations.RenameIndex(
            model_name="historialcomentarios",
            new_name="celiaquia_h_usuario_989d09_idx",
            old_name="celiaquia_h_usuario_f2e1a3_idx",
        ),
    ]
