# Generated by Django 4.2.27 on 2026-03-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celiaquia", "0008_alter_asignaciontecnico_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expedienteciudadano",
            name="subsanacion_tipo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
