# Generated by Django 4.2.27 on 2026-03-10 14:34

import core.soft_delete.base
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("celiaquia", "0010_expediente_soft_delete_fields"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="expediente",
            managers=[
                ("objects", core.soft_delete.base.SoftDeleteManager()),
                (
                    "all_objects",
                    core.soft_delete.base.SoftDeleteManager(include_deleted=True),
                ),
            ],
        ),
    ]
