# Generated by Django 4.2.20 on 2025-12-19 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "celiaquia",
            "0008_rename_celiaquia_h_legajo_b8b8c8_idx_celiaquia_h_legajo__123fc8_idx_and_more",
        ),
        ("celiaquia", "0011_deprecate_old_file_fields"),
    ]

    operations = []
