# Generated by Django 4.2.20 on 2025-12-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("celiaquia", "0012_merge_20251219_0803"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="documentolegajo",
            new_name="celiaquia_d_legajo__194cb5_idx",
            old_name="celiaquia_d_legajo_b8b8c8_idx",
        ),
        migrations.RenameIndex(
            model_name="documentolegajo",
            new_name="celiaquia_d_fecha_c_023657_idx",
            old_name="celiaquia_d_fecha_c_86d7a4_idx",
        ),
        migrations.AlterField(
            model_name="expedienteciudadano",
            name="archivo1",
            field=models.FileField(
                blank=True, null=True, upload_to="legajos/archivos/"
            ),
        ),
        migrations.AlterField(
            model_name="expedienteciudadano",
            name="archivo2",
            field=models.FileField(
                blank=True, null=True, upload_to="legajos/archivos/"
            ),
        ),
        migrations.AlterField(
            model_name="expedienteciudadano",
            name="archivo3",
            field=models.FileField(
                blank=True, null=True, upload_to="legajos/archivos/"
            ),
        ),
        migrations.AlterField(
            model_name="expedienteciudadano",
            name="observacion_cruce",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="expedienteciudadano",
            name="subsanacion_motivo",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="expedienteciudadano",
            name="subsanacion_renaper_comentario",
            field=models.TextField(
                blank=True,
                help_text="Comentario de respuesta a subsanación Renaper",
                null=True,
            ),
        ),
    ]
