# Generated by Django 4.2.20 on 2025-06-26 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("provincias", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personafisica",
            name="provincia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.provincia",
                verbose_name="Provincia",
            ),
        ),
        migrations.AlterField(
            model_name="personajuridica",
            name="provincia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="core.provincia",
                verbose_name="Provincia",
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="provincia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.provincia",
            ),
        ),
    ]
