# Generated by Django 4.0.2 on 2024-11-13 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0004_provincia_alter_localidad_options_and_more'),
        ('provincias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configuraciones.provincia'),
        ),
        migrations.AlterField(
            model_name='observacion',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones', to='provincias.proyecto'),
        ),
        migrations.AlterField(
            model_name='personafisica',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuraciones.provincia', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='personajuridica',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuraciones.provincia', verbose_name='Provincia'),
        ),
    ]
