# Generated by Django 4.2.16 on 2024-12-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provincias", "0004_merge_20241114_1121"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosticofisica",
            name="tecnologias_mejorar_eficiencia",
            field=models.BooleanField(
                default=False,
                verbose_name="¿Se utilizan tecnologías para mejorar la eficiencia en la recolección, clasificación y reciclaje de materialesy los recicladores tienen acceso a plataformas digitales?",
            ),
        ),
        migrations.AlterField(
            model_name="diagnosticojuridica",
            name="tecnologias_mejorar_eficiencia",
            field=models.BooleanField(
                default=False,
                verbose_name="¿Se utilizan tecnologías para mejorar la eficiencia en la recolección, clasificación y reciclaje de materialesy los recicladores tienen acceso a plataformas digitales?",
            ),
        ),
    ]
