# Generated by Django 4.2.27 on 2026-06-26 13:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import insumos.models
import insumos.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0008_programa_organismo_programa_descripcion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InsumoCategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, default="", verbose_name="Descripción"
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                ("activo", models.BooleanField(default=True, verbose_name="Activa")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="insumo_categorias",
                        to="core.programa",
                        verbose_name="Programa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoría de insumo",
                "verbose_name_plural": "Categorías de insumos",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Insumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, default="", verbose_name="Descripción"
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        max_length=255,
                        upload_to=insumos.models.insumo_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=(
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                    "csv",
                                ),
                                message="Solo se permiten archivos PDF, imágenes, Word, Excel o CSV.",
                            ),
                            insumos.validators.validate_insumo_file_size,
                            insumos.validators.validate_insumo_content_type,
                        ],
                        verbose_name="Archivo",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="insumos",
                        to="insumos.insumocategoria",
                        verbose_name="Categoría",
                    ),
                ),
                (
                    "programa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="insumos",
                        to="core.programa",
                        verbose_name="Programa",
                    ),
                ),
                (
                    "usuario_actualizacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="insumos_actualizados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario de actualización",
                    ),
                ),
                (
                    "usuario_creacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="insumos_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario de creación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insumo",
                "verbose_name_plural": "Insumos",
                "ordering": ["-fecha_creacion", "titulo"],
            },
        ),
        migrations.AddConstraint(
            model_name="insumocategoria",
            constraint=models.UniqueConstraint(
                fields=("programa", "nombre"),
                name="uniq_insumocategoria_programa_nombre",
            ),
        ),
    ]
