# Generated by Django 4.2.20 on 2025-10-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relevamientos", "0002_prestacion_domingo_merienda_reforzada_actual_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="relevamiento",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
