# Generated by Django 4.2.20 on 2025-07-18 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_prestacion_merienda_reforzada_and_more"),
        ("relevamientos", "0003_remove_old_prestacion_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relevamiento",
            name="prestacion",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.prestacion",
            ),
        ),
    ]
