# Generated by Django 4.2.27 on 2026-04-27 17:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0036_capacitacion_comedor_certificado"),
        (
            "relevamientos",
            "0006_alter_relevamiento_managers_relevamiento_deleted_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ActividadesExtrasSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_actividad",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("talleres_recreativos", models.BooleanField(blank=True, null=True)),
                (
                    "talleres_recreativos_donde",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "talleres_recreativos_frecuencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("apoyo_educativo", models.BooleanField(blank=True, null=True)),
                (
                    "apoyo_educativo_donde",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "apoyo_educativo_frecuencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("grupos_contencion", models.BooleanField(blank=True, null=True)),
                (
                    "grupos_contencion_donde",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "grupos_contencion_frecuencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("actividades_deportivas", models.BooleanField(blank=True, null=True)),
                (
                    "actividades_deportivas_donde",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "actividades_deportivas_frecuencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("talleres_oficio", models.BooleanField(blank=True, null=True)),
                (
                    "talleres_oficio_donde",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "talleres_oficio_frecuencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("huerta", models.BooleanField(blank=True, null=True)),
                (
                    "huerta_donde",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "huerta_frecuencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("actividades_culturales", models.BooleanField(blank=True, null=True)),
                (
                    "actividades_culturales_donde",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "actividades_culturales_frecuencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("actividades_religiosas", models.BooleanField(blank=True, null=True)),
                (
                    "actividades_religiosas_donde",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "actividades_religiosas_frecuencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "actividades_discapacidad",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "actividades_discapacidad_donde",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "actividades_discapacidad_frecuencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ayuda_tramites", models.BooleanField(blank=True, null=True)),
                (
                    "ayuda_tramites_donde",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ayuda_tramites_frecuencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("servicios_legales", models.BooleanField(blank=True, null=True)),
                (
                    "servicios_legales_donde",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "servicios_legales_frecuencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("terminalidad_educativa", models.BooleanField(blank=True, null=True)),
                (
                    "terminalidad_educativa_donde",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "terminalidad_educativa_frecuencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "emprendimientos_productivos",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "emprendimientos_productivos_donde",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "emprendimientos_productivos_frecuencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("promocion_salud", models.BooleanField(blank=True, null=True)),
                (
                    "promocion_salud_donde",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "promocion_salud_frecuencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("otro", models.BooleanField(blank=True, null=True)),
                ("otro_donde", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "otro_frecuencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Actividades extras de primer seguimiento",
                "verbose_name_plural": "Actividades extras de primer seguimiento",
            },
        ),
        migrations.CreateModel(
            name="AlmacenamientoAlimentosSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alimentos_secos_cerrados",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "alimentos_secos_cerrados_adecuados",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "alimentos_secos_desparramados",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "alimentos_secos_noseobservan",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "otros_alimentos_secos",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("heladera_existe", models.BooleanField(blank=True, null=True)),
                ("freezer_existe", models.BooleanField(blank=True, null=True)),
                (
                    "almacenado_cerrados_heladera",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(11),
                        ],
                    ),
                ),
                (
                    "almacenado_cerrados_freezer",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(11),
                        ],
                    ),
                ),
                (
                    "almacenado_cerradoscondiciones_heladera",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(11),
                        ],
                    ),
                ),
                (
                    "almacenado_cerradoscondiciones_freezer",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(11),
                        ],
                    ),
                ),
                (
                    "almacenado_desparramados_heladera",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(11),
                        ],
                    ),
                ),
                (
                    "almacenado_desparramados_freezer",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(11),
                        ],
                    ),
                ),
                (
                    "almacenado_etiquetados_heladera",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(11),
                        ],
                    ),
                ),
                (
                    "almacenado_etiquetados_freezer",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(11),
                        ],
                    ),
                ),
                (
                    "almacenado_noseobservan_heladera",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(11),
                        ],
                    ),
                ),
                (
                    "almacenado_noseobservan_freezer",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(11),
                        ],
                    ),
                ),
                (
                    "almacenado_otro",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Almacenamiento de alimentos de primer seguimiento",
                "verbose_name_plural": "Almacenamientos de alimentos de primer seguimiento",
            },
        ),
        migrations.CreateModel(
            name="AsistenciaTecnicaSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_asistencia",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "socio_organizativo",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "alimentario_nutricion",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "seguridad_higiene",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "administrativo_rendicion",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                ("otro", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Asistencia tecnica de primer seguimiento",
                "verbose_name_plural": "Asistencias tecnicas de primer seguimiento",
            },
        ),
        migrations.CreateModel(
            name="CierreSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "info_adicional",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "realizo_forma",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Completa", "Completa"),
                            ("Parcial", "Parcial"),
                            ("No corresponde", "No corresponde"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("comentarios_finales", models.TextField(blank=True, null=True)),
                (
                    "firma_entrevistado",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
                (
                    "firma_tecnico",
                    models.CharField(blank=True, max_length=600, null=True),
                ),
            ],
            options={
                "verbose_name": "Cierre de primer seguimiento",
                "verbose_name_plural": "Cierres de primer seguimiento",
            },
        ),
        migrations.CreateModel(
            name="ComprasSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lugares_compra",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "lugares_compra_otros",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_compras",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "otra_frecuencia_compras",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "quien_realiza_compras",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "quien_realiza_compras_otro",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "elije_alimentos_compra",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Siempre", "Siempre"),
                            ("A veces", "A veces"),
                            ("Nunca", "Nunca"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "fuente_compras",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="relevamientos.fuentecompras",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compras de primer seguimiento",
                "verbose_name_plural": "Compras de primer seguimiento",
            },
        ),
        migrations.CreateModel(
            name="CondicionesHigieneSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condiciones_piso_limpieza",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Adecuada", "Adecuada"),
                            ("Medianamente adecuada", "Medianamente adecuada"),
                            ("Inadecuada", "Inadecuada"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "condiciones_piso_orden",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Adecuada", "Adecuada"),
                            ("Medianamente adecuada", "Medianamente adecuada"),
                            ("Inadecuada", "Inadecuada"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "condiciones_mesada_limpieza",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Adecuada", "Adecuada"),
                            ("Medianamente adecuada", "Medianamente adecuada"),
                            ("Inadecuada", "Inadecuada"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "condiciones_mesada_orden",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Adecuada", "Adecuada"),
                            ("Medianamente adecuada", "Medianamente adecuada"),
                            ("Inadecuada", "Inadecuada"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "condiciones_mesas_limpieza",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Adecuada", "Adecuada"),
                            ("Medianamente adecuada", "Medianamente adecuada"),
                            ("Inadecuada", "Inadecuada"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "condiciones_mesas_orden",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Adecuada", "Adecuada"),
                            ("Medianamente adecuada", "Medianamente adecuada"),
                            ("Inadecuada", "Inadecuada"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "condiciones_bacha_limpieza",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Adecuada", "Adecuada"),
                            ("Medianamente adecuada", "Medianamente adecuada"),
                            ("Inadecuada", "Inadecuada"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "condiciones_bachas_orden",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Adecuada", "Adecuada"),
                            ("Medianamente adecuada", "Medianamente adecuada"),
                            ("Inadecuada", "Inadecuada"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "condiciones_equipamiento_limpieza",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Adecuada", "Adecuada"),
                            ("Medianamente adecuada", "Medianamente adecuada"),
                            ("Inadecuada", "Inadecuada"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "condiciones_equipamiento_orden",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Adecuada", "Adecuada"),
                            ("Medianamente adecuada", "Medianamente adecuada"),
                            ("Inadecuada", "Inadecuada"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "condiciones_utensillos_limpieza",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Adecuada", "Adecuada"),
                            ("Medianamente adecuada", "Medianamente adecuada"),
                            ("Inadecuada", "Inadecuada"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "condiciones_utensillos_orden",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Adecuada", "Adecuada"),
                            ("Medianamente adecuada", "Medianamente adecuada"),
                            ("Inadecuada", "Inadecuada"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "entregan_viandas",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Adecuada", "Adecuada"),
                            ("Medianamente adecuada", "Medianamente adecuada"),
                            ("Inadecuada", "Inadecuada"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Condiciones de higiene de primer seguimiento",
                "verbose_name_plural": "Condiciones de higiene de primer seguimiento",
            },
        ),
        migrations.CreateModel(
            name="FrecuenciaAlimentosSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frecuencia_alimentos_alm_cena_frutas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_alimentos_alm_cena_verduras",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_alimentos_alm_cena_carne",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_alimentos_alm_cena_pollo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_alimentos_alm_cena_pescado",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_alimentos_alm_cena_fideos",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_alimentos_alm_cena_legumbres",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_alimentos_alm_cena_ultraprocesados",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_alimentos_alm_cena_huevos",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_alimentos_des_merienda_leche",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_alimentos_des_merienda_te",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_alimentos_des_merienda_mate_cocido",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_alimentos_des_merienda_yogurt",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_alimentos_des_merienda_queso",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_alimentos_des_merienda_fruta",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_alimentos_des_merienda_pan",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_alimentos_des_merienda_galletitas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_alimentos_des_merienda_mermelada_dulce",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Frecuencia de alimentos de primer seguimiento",
                "verbose_name_plural": "Frecuencias de alimentos de primer seguimiento",
            },
        ),
        migrations.CreateModel(
            name="FrecuenciaCompraAlimentosSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frecuencia_compra_hortalizas_frutas",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_compra_leche_yogur_queso",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_compra_carnes",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_compra_legumbres",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_compra_alimentos_secos",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_compra_pan",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_compra_huevos",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_compra_otros",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Frecuencia de compra de alimentos de primer seguimiento",
                "verbose_name_plural": "Frecuencias de compra de alimentos de primer seguimiento",
            },
        ),
        migrations.CreateModel(
            name="FuncionamientoSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "funcionamiento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Abierto en funcionamiento", "Abierto en funcionamiento"),
                            (
                                "Abierto sin funcionamiento",
                                "Abierto sin funcionamiento",
                            ),
                            ("Cerrado", "Cerrado"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Funcionamiento de primer seguimiento",
                "verbose_name_plural": "Funcionamientos de primer seguimiento",
            },
        ),
        migrations.CreateModel(
            name="MenuSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_menu",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "tipo_prestacion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cantidad_personas_menu",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("cambios_menu", models.BooleanField(blank=True, null=True)),
                (
                    "cambios_cuales",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cambios_porque",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "menu_semana_pasada_lunes",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "menu_semana_pasada_martes",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "menu_semana_pasada_miercoles",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "menu_semana_pasada_jueves",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "menu_semana_pasada_viernes",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "menu_semana_pasada_sabado",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "menu_semana_pasada_domingo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("menu_preestablecido", models.BooleanField(blank=True, null=True)),
                (
                    "menu_preestablecido_porquien",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "frecuencia_menu_preestablecido",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "menu_preestablecido_porque",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("considera_menu_variado", models.BooleanField(blank=True, null=True)),
                (
                    "considera_menu_saludable",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "considera_menu_porque",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "considera_menu_tamanio_porciones",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "considera_personas_conformes",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "considera_personas_conformes_porque",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mejora_alimentacion_ofrecida",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "modalidad_prestacion_del_dia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="relevamientos.tipomodalidadprestacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu de primer seguimiento",
                "verbose_name_plural": "Menus de primer seguimiento",
            },
        ),
        migrations.CreateModel(
            name="RegistroAsistenciaSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registro_asistencia", models.BooleanField(blank=True, null=True)),
                (
                    "registro_asistencia_quien",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "registro_asistencia_metodo",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("asisten_personas_calle", models.BooleanField(blank=True, null=True)),
                (
                    "asisten_personas_calle_cantidad",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "cantidad_asistencia_total",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "verbose_name": "Registro de asistencia de primer seguimiento",
                "verbose_name_plural": "Registros de asistencia de primer seguimiento",
            },
        ),
        migrations.CreateModel(
            name="RendicionCuentasSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_rendicion",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("persona_encargada", models.BooleanField(blank=True, null=True)),
                ("recibio_capacitacion", models.BooleanField(blank=True, null=True)),
                ("norecibio_porque", models.BooleanField(blank=True, null=True)),
                ("sencilla_plataforma", models.BooleanField(blank=True, null=True)),
                ("nosencilla_porque", models.BooleanField(blank=True, null=True)),
                ("inconvenientes_carga", models.BooleanField(blank=True, null=True)),
                (
                    "incovenientes_porque",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Rendicion de cuentas de primer seguimiento",
                "verbose_name_plural": "Rendiciones de cuentas de primer seguimiento",
            },
        ),
        migrations.CreateModel(
            name="ServiciosBasicosSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agua_potable", models.BooleanField(blank=True, null=True)),
                (
                    "gas_red",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "gas_envasado",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "electricidad",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "lenia_carbon",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                (
                    "otros_cocina",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("banio", models.CharField(blank=True, max_length=255, null=True)),
                ("recipiente", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "otro_recipiente",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("observan_animales", models.BooleanField(blank=True, null=True)),
                ("elementos_guardados", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Servicios basicos de primer seguimiento",
                "verbose_name_plural": "Servicios basicos de primer seguimiento",
            },
        ),
        migrations.CreateModel(
            name="TarjetaSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_tarjeta",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("persona_responsable", models.BooleanField(blank=True, null=True)),
                ("llegada_tarjeta", models.BooleanField(blank=True, null=True)),
                ("mes_notificado", models.BooleanField(blank=True, null=True)),
                ("conforme_tarjeta", models.BooleanField(blank=True, null=True)),
                (
                    "conforme_porque",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Tarjeta de primer seguimiento",
                "verbose_name_plural": "Tarjetas de primer seguimiento",
            },
        ),
        migrations.CreateModel(
            name="TareasComedorSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tareas_capacitacion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tareas_capacitacion_especificar",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tareas_comedor_cant_personas",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="relevamientos.cantidadcolaboradores",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tareas de comedor de primer seguimiento",
                "verbose_name_plural": "Tareas de comedor de primer seguimiento",
            },
        ),
        migrations.CreateModel(
            name="RecursosSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recursos_comedor_estado_nacional",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "recursos_comedor_estado_nacional_frecuencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "recursos_comedor_estado_nacional_recibe",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "recursos_comedor_estado_provincial",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "recursos_comedor_estado_provincial_frecuencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "recursos_comedor_estado_provincial_recibe",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "recursos_comedor_estado_municipal",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "recursos_comedor_estado_municipal_frecuencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "recursos_comedor_estado_municipal_recibe",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "recursos_comedor_donaciones",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "recursos_comedor_donaciones_frecuencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "recursos_comedor_donaciones_recibe",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "financiamiento_principal",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "financiamiento_principal_otros",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "financiaminento_otras_necesidades",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "financiaminento_otras_necesidades_paraque",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "financiaminento_otras_necesidades_frecuencia",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "fuente_recursos",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="relevamientos.fuenterecursos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recursos de primer seguimiento",
                "verbose_name_plural": "Recursos de primer seguimiento",
            },
        ),
        migrations.CreateModel(
            name="PrimerSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField(blank=True, null=True)),
                ("tecnico", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "estado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Asignado", "Asignado"),
                            ("En Proceso", "En Proceso"),
                            ("Completo", "Completo"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "actividades_extras",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="relevamientos.actividadesextrasseguimiento",
                    ),
                ),
                (
                    "almacenamiento_alimentos",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="relevamientos.almacenamientoalimentosseguimiento",
                    ),
                ),
                (
                    "asistencia_tecnica",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="relevamientos.asistenciatecnicaseguimiento",
                    ),
                ),
                (
                    "cierre",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="relevamientos.cierreseguimiento",
                    ),
                ),
                (
                    "compras",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="relevamientos.comprasseguimiento",
                    ),
                ),
                (
                    "condiciones_higiene",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="relevamientos.condicioneshigieneseguimiento",
                    ),
                ),
                (
                    "frecuencia_alimentos",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="relevamientos.frecuenciaalimentosseguimiento",
                    ),
                ),
                (
                    "frecuencia_compra_alimentos",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="relevamientos.frecuenciacompraalimentosseguimiento",
                    ),
                ),
                (
                    "funcionamiento",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="relevamientos.funcionamientoseguimiento",
                    ),
                ),
                (
                    "id_relevamiento",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primer_seguimiento",
                        to="relevamientos.relevamiento",
                    ),
                ),
                (
                    "menu",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="relevamientos.menuseguimiento",
                    ),
                ),
                (
                    "recursos",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="relevamientos.recursosseguimiento",
                    ),
                ),
                (
                    "referente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comedores.referente",
                    ),
                ),
                (
                    "registro_asistencia",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="relevamientos.registroasistenciaseguimiento",
                    ),
                ),
                (
                    "rendicion_cuentas",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="relevamientos.rendicioncuentasseguimiento",
                    ),
                ),
                (
                    "servicios_basicos",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="relevamientos.serviciosbasicosseguimiento",
                    ),
                ),
                (
                    "tareas_comedor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="relevamientos.tareascomedorseguimiento",
                    ),
                ),
                (
                    "tarjeta",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="relevamientos.tarjetaseguimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Primer seguimiento de relevamiento",
                "verbose_name_plural": "Primeros seguimientos de relevamiento",
            },
        ),
        migrations.CreateModel(
            name="PrestacionSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_prestacion_seg",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "dias_prestacion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tipo_prestacion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ap_presencial", models.PositiveIntegerField(blank=True, null=True)),
                ("ap_vianda", models.PositiveIntegerField(blank=True, null=True)),
                ("de_presencial", models.PositiveIntegerField(blank=True, null=True)),
                ("de_vianda", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "seguimiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestaciones",
                        to="relevamientos.primerseguimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestacion de primer seguimiento",
                "verbose_name_plural": "Prestaciones de primer seguimiento",
            },
        ),
        migrations.CreateModel(
            name="ItemRecetaSeguimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_item_receta",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "ingrediente",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "unidad_medida",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "cantidad_medida",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receta_items",
                        to="relevamientos.menuseguimiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de receta de primer seguimiento",
                "verbose_name_plural": "Items de receta de primer seguimiento",
            },
        ),
        migrations.AddIndex(
            model_name="primerseguimiento",
            index=models.Index(fields=["estado"], name="relevamient_estado_5340dc_idx"),
        ),
    ]
