# Generated by Django 5.2.16 on 2026-09-03 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relevamientos", "0013_alter_relevamiento_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="primerseguimiento",
            name="coordinador",
            field=models.ForeignKey(
                blank=True,
                help_text="Coordinador que hizo la última revisión.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss_revisados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="primerseguimiento",
            name="estado_validacion",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Pendiente validación coordinador",
                        "Pendiente validación coordinador",
                    ),
                    ("A subsanar", "A subsanar"),
                    ("Validado", "Validado"),
                ],
                help_text="Vacío = todavía no se envió a validación del coordinador.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="primerseguimiento",
            name="fecha_revision_coordinador",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="primerseguimiento",
            name="observaciones_coordinador",
            field=models.TextField(
                blank=True,
                help_text="Qué debe corregir el territorial cuando queda 'A subsanar'.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="relevamiento",
            name="coordinador",
            field=models.ForeignKey(
                blank=True,
                help_text="Coordinador que hizo la última revisión.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)ss_revisados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="relevamiento",
            name="estado_validacion",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Pendiente validación coordinador",
                        "Pendiente validación coordinador",
                    ),
                    ("A subsanar", "A subsanar"),
                    ("Validado", "Validado"),
                ],
                help_text="Vacío = todavía no se envió a validación del coordinador.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="relevamiento",
            name="fecha_revision_coordinador",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="relevamiento",
            name="observaciones_coordinador",
            field=models.TextField(
                blank=True,
                help_text="Qué debe corregir el territorial cuando queda 'A subsanar'.",
                null=True,
            ),
        ),
    ]
