# Generated by Django 5.2.16 on 2026-09-04 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0057_huecos_seguimiento_n19"),
        ("relevamientos", "0016_instancias_seguimiento_n14"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="primerseguimiento",
            name="asignado_desde_sisoc",
            field=models.BooleanField(
                default=True,
                help_text="False cuando lo autoactivó el territorial desde la app.",
            ),
        ),
        migrations.AddField(
            model_name="primerseguimiento",
            name="client_uuid",
            field=models.CharField(
                blank=True,
                help_text="Identificador estable del cliente para deduplicar reintentos offline del alta. En MySQL los NULL son distintos, así que solo enforcea cuando viene informado.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="primerseguimiento",
            name="origen",
            field=models.CharField(
                choices=[("sisoc", "SISOC"), ("app", "App territorial")],
                default="sisoc",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="relevamiento",
            name="asignado_desde_sisoc",
            field=models.BooleanField(
                default=True,
                help_text="False cuando lo autoactivó el territorial desde la app.",
            ),
        ),
        migrations.AddField(
            model_name="relevamiento",
            name="client_uuid",
            field=models.CharField(
                blank=True,
                help_text="Identificador estable del cliente para deduplicar reintentos offline del alta. En MySQL los NULL son distintos, así que solo enforcea cuando viene informado.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="relevamiento",
            name="origen",
            field=models.CharField(
                choices=[("sisoc", "SISOC"), ("app", "App territorial")],
                default="sisoc",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ActaComplementaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[("sisoc", "SISOC"), ("app", "App territorial")],
                        default="sisoc",
                        max_length=16,
                    ),
                ),
                (
                    "asignado_desde_sisoc",
                    models.BooleanField(
                        default=True,
                        help_text="False cuando lo autoactivó el territorial desde la app.",
                    ),
                ),
                (
                    "client_uuid",
                    models.CharField(
                        blank=True,
                        help_text="Identificador estable del cliente para deduplicar reintentos offline del alta. En MySQL los NULL son distintos, así que solo enforcea cuando viene informado.",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                ("fecha_hora", models.DateTimeField(blank=True, null=True)),
                (
                    "observaciones",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Motivo / observaciones del cambio de prestación",
                    ),
                ),
                ("firma", models.CharField(blank=True, max_length=600, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "comedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actas_complementarias",
                        to="comedores.comedor",
                    ),
                ),
                (
                    "tecnico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actas_complementarias",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Acta complementaria extraordinaria",
                "verbose_name_plural": "Actas complementarias extraordinarias",
                "ordering": ["-fecha_hora", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PrestacionActaComplementaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dias_prestacion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tipo_prestacion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cantidad_actual", models.PositiveIntegerField(blank=True, null=True)),
                ("cantidad_espera", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "acta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestaciones",
                        to="relevamientos.actacomplementaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestacion de acta complementaria",
                "verbose_name_plural": "Prestaciones de actas complementarias",
            },
        ),
    ]
