# Generated by Django 4.2.20 on 2025-11-12 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ciudadanos", "0007_alter_ciudadano_documento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ciudadano",
            name="documento",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
