# centrodefamilia/urls.py
from django.urls import path
from core.decorators import permissions_any_required

from centrodefamilia.views.informecabal import (
    InformeCabalArchivoDetailView,
    InformeCabalListView,
    InformeCabalPreviewAjaxView,
    InformeCabalProcessAjaxView,
    InformeCabalRegistroDetailView,
    InformeCabalReprocessCenterAjaxView,
)

from centrodefamilia.views.centro import (
    CentroCreateView,
    CentroDeleteView,
    CentroDetailView,
    CentroListView,
    CentroUpdateView,
    InformeCabalArchivoPorCentroDetailView,
    centros_ajax,
)

from centrodefamilia.views.actividad import (
    ActividadCentroCreateView,
    ActividadCentroDetailView,
    ActividadCentroListView,
    ActividadCentroUpdateView,
    ActividadCreateView,
    cargar_actividades_por_categoria,
)

from centrodefamilia.views.participante import (
    ParticipanteActividadCreateView,
    ParticipanteActividadDeleteView,
    ParticipanteActividadListEsperaView,
    ParticipanteActividadPromoverView,
)

from .views.beneficiarios import (
    BeneficiariosListView,
    BeneficiariosDetailView,
    ResponsableListView,
    ResponsableDetailView,
    BeneficiariosCreateView,
    BuscarCUILView,
    BuscarResponsableView,
)

urlpatterns = [
    path(
        "centros/<int:centro_id>/informecabal/<int:pk>/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            InformeCabalArchivoPorCentroDetailView.as_view()
        ),
        name="informecabal_archivo_centro_detail",
    ),
    path(
        "centros/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            CentroListView.as_view()
        ),
        name="centro_list",
    ),
    path(
        "centros/ajax/",
        permissions_any_required(["centrodefamilia.view_centro"])(centros_ajax),
        name="centros_ajax",
    ),
    path(
        "centros/nuevo/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            CentroCreateView.as_view()
        ),
        name="centro_create",
    ),
    path(
        "centros/<int:pk>/editar/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            CentroUpdateView.as_view()
        ),
        name="centro_update",
    ),
    path(
        "centros/<int:pk>/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            CentroDetailView.as_view()
        ),
        name="centro_detail",
    ),
    path(
        "centros/<int:pk>/eliminar/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            CentroDeleteView.as_view()
        ),
        name="centro_delete",
    ),
    path(
        "actividades/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            ActividadCentroListView.as_view()
        ),
        name="actividadcentro_list",
    ),
    path(
        "centros/<int:centro_id>/actividades/nueva/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            ActividadCentroCreateView.as_view()
        ),
        name="actividadcentro_create",
    ),
    path(
        "centros/actividades/<int:pk>/detalle/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            ActividadCentroDetailView.as_view()
        ),
        name="actividadcentro_detail",
    ),
    path(
        "centros/<int:centro_id>/actividades/<int:actividad_id>/participantes/crear/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            ParticipanteActividadCreateView.as_view()
        ),
        name="participanteactividad_create",
    ),
    path(
        "centros/actividades/<int:pk>/editar/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            ActividadCentroUpdateView.as_view()
        ),
        name="actividadcentro_edit",
    ),
    path(
        "ajax/actividades/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            cargar_actividades_por_categoria
        ),
        name="ajax_cargar_actividades",
    ),
    path(
        "centros/<int:centro_id>/actividades/<int:actividad_id>/participantes/<int:pk>/eliminar/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            ParticipanteActividadDeleteView.as_view()
        ),
        name="participanteactividad_delete",
    ),
    path(
        "centros/<int:centro_id>/actividades/<int:actividad_id>/lista-espera/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            ParticipanteActividadListEsperaView.as_view()
        ),
        name="actividadcentro_lista_espera",
    ),
    path(
        "centros/<int:centro_id>/actividades/<int:actividad_id>/lista-espera/<int:pk>/promover/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            ParticipanteActividadPromoverView.as_view()
        ),
        name="participanteactividad_promover",
    ),
    # ——— NUEVO: Informe CABAL ———
    path(
        "informecabal/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            InformeCabalListView.as_view()
        ),
        name="informecabal_list",
    ),
    path(
        "informecabal/preview/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            InformeCabalPreviewAjaxView.as_view()
        ),
        name="informecabal_preview",
    ),
    path(
        "informecabal/<int:pk>/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            InformeCabalArchivoDetailView.as_view()
        ),
        name="informecabal_archivo_detail",
    ),
    path(
        "informecabal/process/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            InformeCabalProcessAjaxView.as_view()
        ),
        name="informecabal_process",
    ),
    path(
        "informecabal/registro/<int:pk>/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            InformeCabalRegistroDetailView.as_view()
        ),
        name="informecabal_registro_detail",
    ),
    # (Dejamos tus rutas previas de “expedientes” intactas, aunque NO se usan en este flujo)
    path(
        "actividades/nueva/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            ActividadCreateView.as_view()
        ),
        name="actividad_create_sola",
    ),
    # repro
    path(
        "informecabal/reprocess/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            InformeCabalReprocessCenterAjaxView.as_view()
        ),
        name="informecabal_reprocess_center",
    ),
    # URLs de Beneficiarios
    path(
        "beneficiarios/beneficiarios/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            BeneficiariosListView.as_view()
        ),
        name="beneficiarios_list",
    ),
    path(
        "beneficiarios/beneficiarios/<int:pk>/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            BeneficiariosDetailView.as_view()
        ),
        name="beneficiarios_detail",
    ),
    path(
        "beneficiarios/nuevo/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            BeneficiariosCreateView.as_view()
        ),
        name="beneficiarios_crear",
    ),
    path(
        "beneficiarios/responsables/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            ResponsableListView.as_view()
        ),
        name="responsables_list",
    ),
    path(
        "beneficiarios/responsables/<int:pk>/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            ResponsableDetailView.as_view()
        ),
        name="responsables_detail",
    ),
    path(
        "beneficiarios/buscar-cuil/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            BuscarCUILView.as_view()
        ),
        name="buscar_cuil",
    ),
    path(
        "beneficiarios/buscar-responsable/",
        permissions_any_required(["centrodefamilia.view_centro"])(
            BuscarResponsableView.as_view()
        ),
        name="buscar_responsable",
    ),
]
