from django.urls import path
from django.views.decorators.http import require_POST

from core.decorators import permissions_all_required, permissions_any_required
from ver_para_ser_libre import views


urlpatterns = [
    path(
        "ver-para-ser-libre/",
        permissions_any_required(["ver_para_ser_libre.view_itinerariovpsl"])(
            views.ItinerarioListView.as_view()
        ),
        name="vpsl_itinerario_list",
    ),
    path(
        "ver-para-ser-libre/sedes/autocomplete/",
        permissions_any_required(
            [
                "ver_para_ser_libre.view_sedevpsl",
                "ver_para_ser_libre.view_itinerariovpsl",
            ]
        )(views.sedes_autocomplete),
        name="vpsl_sedes_autocomplete",
    ),
    path(
        "ver-para-ser-libre/renaper/consultar/",
        permissions_any_required(
            [
                "ver_para_ser_libre.add_registronominalvpsl",
                "ver_para_ser_libre.change_registronominalvpsl",
                "ver_para_ser_libre.add_jornadavpsl",
                "ver_para_ser_libre.change_jornadavpsl",
            ]
        )(views.consultar_renaper_vpsl),
        name="vpsl_renaper_consultar",
    ),
    path(
        "ver-para-ser-libre/sedes/",
        permissions_any_required(["ver_para_ser_libre.view_sedevpsl"])(
            views.SedeListView.as_view()
        ),
        name="vpsl_sede_list",
    ),
    path(
        "ver-para-ser-libre/sedes/crear/",
        permissions_any_required(["ver_para_ser_libre.add_sedevpsl"])(
            views.SedeCreateView.as_view()
        ),
        name="vpsl_sede_create",
    ),
    path(
        "ver-para-ser-libre/sedes/<int:pk>/editar/",
        permissions_any_required(["ver_para_ser_libre.change_sedevpsl"])(
            views.SedeUpdateView.as_view()
        ),
        name="vpsl_sede_update",
    ),
    path(
        "ver-para-ser-libre/sedes/<int:pk>/eliminar/",
        permissions_any_required(["ver_para_ser_libre.delete_sedevpsl"])(
            views.SedeDeleteView.as_view()
        ),
        name="vpsl_sede_delete",
    ),
    path(
        "ver-para-ser-libre/crear/",
        permissions_any_required(["ver_para_ser_libre.add_itinerariovpsl"])(
            views.ItinerarioCreateView.as_view()
        ),
        name="vpsl_itinerario_create",
    ),
    path(
        "ver-para-ser-libre/<int:pk>/",
        permissions_any_required(["ver_para_ser_libre.view_itinerariovpsl"])(
            views.ItinerarioDetailView.as_view()
        ),
        name="vpsl_itinerario_detail",
    ),
    path(
        "ver-para-ser-libre/<int:pk>/exportar/",
        permissions_all_required(
            ["ver_para_ser_libre.view_itinerariovpsl", "auth.role_exportar_a_csv"]
        )(views.ItinerarioExportView.as_view()),
        name="vpsl_itinerario_export",
    ),
    path(
        "ver-para-ser-libre/<int:pk>/editar/",
        permissions_any_required(["ver_para_ser_libre.change_itinerariovpsl"])(
            views.ItinerarioUpdateView.as_view()
        ),
        name="vpsl_itinerario_update",
    ),
    path(
        "ver-para-ser-libre/<int:pk>/eliminar/",
        permissions_any_required(["ver_para_ser_libre.delete_itinerariovpsl"])(
            views.ItinerarioDeleteView.as_view()
        ),
        name="vpsl_itinerario_delete",
    ),
    path(
        "ver-para-ser-libre/<int:pk>/subsanar/",
        permissions_any_required(["ver_para_ser_libre.change_itinerariovpsl"])(
            views.ItinerarioSubsanarView.as_view()
        ),
        name="vpsl_itinerario_subsanar",
    ),
    path(
        "ver-para-ser-libre/<int:pk>/presentar/",
        permissions_any_required(["ver_para_ser_libre.change_itinerariovpsl"])(
            require_POST(views.presentar_itinerario)
        ),
        name="vpsl_itinerario_presentar",
    ),
    path(
        "ver-para-ser-libre/<int:pk>/aprobar/",
        permissions_any_required(["ver_para_ser_libre.change_itinerariovpsl"])(
            require_POST(views.aprobar_itinerario)
        ),
        name="vpsl_itinerario_aprobar",
    ),
    path(
        "ver-para-ser-libre/<int:itinerario_pk>/jornadas/crear/",
        permissions_any_required(["ver_para_ser_libre.add_jornadavpsl"])(
            views.JornadaCreateView.as_view()
        ),
        name="vpsl_jornada_create",
    ),
    path(
        "ver-para-ser-libre/jornadas/<int:pk>/",
        permissions_any_required(["ver_para_ser_libre.view_jornadavpsl"])(
            views.JornadaDetailView.as_view()
        ),
        name="vpsl_jornada_detail",
    ),
    path(
        "ver-para-ser-libre/jornadas/<int:pk>/exportar/",
        permissions_all_required(
            ["ver_para_ser_libre.view_jornadavpsl", "auth.role_exportar_a_csv"]
        )(views.JornadaExportView.as_view()),
        name="vpsl_jornada_export",
    ),
    path(
        "ver-para-ser-libre/jornadas/<int:pk>/editar/",
        permissions_any_required(["ver_para_ser_libre.change_jornadavpsl"])(
            views.JornadaUpdateView.as_view()
        ),
        name="vpsl_jornada_update",
    ),
    path(
        "ver-para-ser-libre/jornadas/<int:pk>/eliminar/",
        permissions_any_required(["ver_para_ser_libre.delete_jornadavpsl"])(
            views.JornadaDeleteView.as_view()
        ),
        name="vpsl_jornada_delete",
    ),
    path(
        "ver-para-ser-libre/jornadas/<int:pk>/habilitar/",
        permissions_any_required(["ver_para_ser_libre.change_jornadavpsl"])(
            require_POST(views.habilitar_jornada)
        ),
        name="vpsl_jornada_habilitar",
    ),
    path(
        "ver-para-ser-libre/jornadas/<int:pk>/cierre-definitivo/",
        permissions_any_required(["ver_para_ser_libre.change_jornadavpsl"])(
            require_POST(views.cierre_definitivo_jornada)
        ),
        name="vpsl_jornada_cierre_definitivo",
    ),
    path(
        "ver-para-ser-libre/jornadas/<int:jornada_pk>/checklist/crear/",
        permissions_any_required(["ver_para_ser_libre.add_checklistjornadavpsl"])(
            views.ChecklistCreateView.as_view()
        ),
        name="vpsl_checklist_create",
    ),
    path(
        "ver-para-ser-libre/jornadas/<int:jornada_pk>/registros/crear/",
        permissions_any_required(["ver_para_ser_libre.add_registronominalvpsl"])(
            views.RegistroNominalCreateView.as_view()
        ),
        name="vpsl_registro_create",
    ),
    path(
        "ver-para-ser-libre/registros/<int:pk>/editar/",
        permissions_any_required(["ver_para_ser_libre.change_registronominalvpsl"])(
            views.RegistroNominalUpdateView.as_view()
        ),
        name="vpsl_registro_update",
    ),
    path(
        "ver-para-ser-libre/registros/<int:pk>/eliminar/",
        permissions_any_required(["ver_para_ser_libre.delete_registronominalvpsl"])(
            views.RegistroNominalDeleteView.as_view()
        ),
        name="vpsl_registro_delete",
    ),
    path(
        "ver-para-ser-libre/laboratorio/<int:pk>/editar/",
        permissions_any_required(["ver_para_ser_libre.change_casolaboratoriovpsl"])(
            views.CasoLaboratorioUpdateView.as_view()
        ),
        name="vpsl_laboratorio_update",
    ),
    path(
        "ver-para-ser-libre/jornadas/<int:pk>/laboratorio/actualizar-masivo/",
        permissions_any_required(["ver_para_ser_libre.change_casolaboratoriovpsl"])(
            require_POST(views.actualizar_laboratorio_masivo)
        ),
        name="vpsl_laboratorio_bulk_update",
    ),
    path(
        "ver-para-ser-libre/jornadas/<int:jornada_pk>/cierre/crear/",
        permissions_any_required(["ver_para_ser_libre.add_cierrediariovpsl"])(
            views.CierreDiarioCreateView.as_view()
        ),
        name="vpsl_cierre_create",
    ),
]
