# Generated by Django 4.2.16 on 2025-11-06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('duplas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dupla',
            name='coordinador',
            field=models.ForeignKey(
                blank=True,
                help_text='Coordinador asignado a esta dupla. Si se elimina el coordinador, este campo quedará vacío.',
                limit_choices_to={'groups__name': 'Coordinador Equipo Tecnico'},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='duplas_coordinadas',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Coordinador de Equipo Técnico'
            ),
        ),
    ]
