# Generated by Django 4.2.16 on 2025-04-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("duplas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dupla",
            name="estado",
            field=models.CharField(
                choices=[("Activo", "Activo"), ("Inactivo", "Inactivo")],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dupla",
            name="fecha",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
