# Generated by Django 4.2.27 on 2026-03-05 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pwa", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditoriasesionpwa",
            new_name="pwa_auditor_user_id_951231_idx",
            old_name="pwa_auditor_user_id_52e452_idx",
        ),
        migrations.RenameIndex(
            model_name="auditoriasesionpwa",
            new_name="pwa_auditor_evento_5c0ad0_idx",
            old_name="pwa_auditor_evento_49cf48_idx",
        ),
        migrations.RenameIndex(
            model_name="auditoriasesionpwa",
            new_name="pwa_auditor_resulta_ae14a4_idx",
            old_name="pwa_auditor_resulta_2d6494_idx",
        ),
    ]
