# Generated by Django 4.2.27 on 2026-03-06 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("comedores", "0023_alter_comedor_managers_alter_nomina_managers_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("pwa", "0002_rename_pwa_auditor_user_id_52e452_idx_pwa_auditor_user_id_951231_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColaboradorEspacioPWA",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("dni", models.CharField(max_length=8)),
                ("telefono", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=255)),
                ("rol_funcion", models.CharField(max_length=150)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("fecha_baja", models.DateTimeField(blank=True, null=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="colaboradores_pwa_actualizados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "comedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colaboradores_pwa",
                        to="comedores.comedor",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="colaboradores_pwa_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Colaborador PWA",
                "verbose_name_plural": "Colaboradores PWA",
                "ordering": ("apellido", "nombre", "-id"),
            },
        ),
        migrations.AddConstraint(
            model_name="colaboradorespaciopwa",
            constraint=models.UniqueConstraint(
                condition=Q(("activo", True)),
                fields=("comedor", "dni"),
                name="uniq_colaborador_pwa_dni_activo_por_comedor",
            ),
        ),
        migrations.AddIndex(
            model_name="colaboradorespaciopwa",
            index=models.Index(fields=["comedor", "activo"], name="pwa_colab_comedor_activo_idx"),
        ),
        migrations.AddIndex(
            model_name="colaboradorespaciopwa",
            index=models.Index(fields=["comedor", "dni"], name="pwa_colab_comedor_dni_idx"),
        ),
    ]
