# Generated by Django 4.2.27 on 2026-03-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pwa", "0003_colaboradores_espacio_pwa"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="colaboradorespaciopwa",
                    name="uniq_colaborador_pwa_dni_activo_por_comedor",
                )
            ],
        ),
        migrations.AddConstraint(
            model_name="colaboradorespaciopwa",
            constraint=models.UniqueConstraint(
                fields=("comedor", "dni"),
                name="uniq_colaborador_pwa_dni_por_comedor",
            ),
        ),
    ]
