# Generated by Django 4.2.27 on 2026-03-06 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comedores", "0023_alter_comedor_managers_alter_nomina_managers_and_more"),
        ("pwa", "0005_actividades_pwa"),
    ]

    operations = [
        migrations.CreateModel(
            name="NominaEspacioPWA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asistencia_alimentaria", models.BooleanField(default=True)),
                ("asistencia_actividades", models.BooleanField(default=False)),
                ("es_indocumentado", models.BooleanField(default=False)),
                (
                    "identificador_interno",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("activo", models.BooleanField(default=True)),
                ("fecha_alta", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("fecha_baja", models.DateTimeField(blank=True, null=True)),
                (
                    "actualizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nominas_pwa_actualizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nominas_pwa_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nomina",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_pwa",
                        to="comedores.nomina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nomina Espacio PWA",
                "verbose_name_plural": "Nominas Espacio PWA",
                "indexes": [
                    models.Index(fields=["activo"], name="pwa_nomina_activo_idx"),
                    models.Index(
                        fields=["asistencia_alimentaria", "asistencia_actividades"],
                        name="pwa_nomina_asistencia_idx",
                    ),
                    models.Index(
                        fields=["es_indocumentado"], name="pwa_nomina_indoc_idx"
                    ),
                ],
            },
        ),
    ]
