# Generated by Django 4.2.20 on 2025-12-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tablero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre visible en el menú y el encabezado del tablero.",
                        max_length=255,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Identificador único para la URL del tablero.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="URL embebida del tablero (Power BI u otra herramienta).",
                    ),
                ),
                (
                    "mensaje_construccion",
                    models.TextField(
                        blank=True,
                        help_text="Mensaje a mostrar cuando el tablero no tiene URL.",
                    ),
                ),
                (
                    "orden",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Orden de aparición en el menú de tableros.",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Define si el tablero aparece en el menú.",
                    ),
                ),
                (
                    "permisos",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Listado de grupos con acceso al tablero.",
                    ),
                ),
            ],
            options={
                "verbose_name": "tablero",
                "verbose_name_plural": "tableros",
                "ordering": ["orden", "nombre"],
            },
        ),
    ]
