# Generated by Django 4.2.27 on 2026-03-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_tablero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablero",
            name="permisos",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Listado de permisos con acceso al tablero (app_label.codename). Se aceptan nombres de grupo legacy por compatibilidad.",
            ),
        ),
    ]
