from django.urls import path
from core.decorators import permissions_any_required
from admisiones.views.web_views import (
    subir_archivo_admision,
    eliminar_archivo_admision,
    actualizar_estado_archivo,
    actualizar_numero_gde_archivo,
    actualizar_numero_gde_organizacion_admision,
    actualizar_convenio_numero,
    actualizar_vigente_pwa,
    actualizar_personas_conveniadas_nomina,
    actualizar_num_expediente,
    crear_documento_personalizado,
    previsualizar_informe_tecnico_template,
    descargar_informe_tecnico_para_gde,
    reportar_configuracion_faltante_template,
    resync_convenio_admision,
    AdmisionesTecnicosListView,
    AdmisionesTecnicosUpdateView,
    AdmisionDetailView,
    InformeTecnicosCreateView,
    InformeTecnicosUpdateView,
    InformeTecnicoDetailView,
    InformeTecnicoComplementarioDetailView,
    InformeTecnicoComplementarioReviewView,
    AdmisionesLegalesListView,
    AdmisionesLegalesDetailView,
    admisiones_legales_ajax,
)
from admisiones.views.templates_informe_tecnico import (
    IncidenciaTemplateInformeTecnicoDetailView,
    IncidenciaTemplateInformeTecnicoListView,
    PlantillaInformeTecnicoCreateView,
    PlantillaInformeTecnicoDeactivateView,
    PlantillaInformeTecnicoDetailView,
    PlantillaInformeTecnicoListView,
    PlantillaInformeTecnicoVersionCreateView,
    PlantillaInformeTecnicoVersionDiscardView,
    PlantillaInformeTecnicoVersionPreviewView,
    PlantillaInformeTecnicoVersionPublishView,
    PlantillaInformeTecnicoVersionUpdateView,
    VariableTemplateInformeTecnicoListView,
    VariableTemplateInformeTecnicoToggleView,
)

urlpatterns = [
    path(
        "comedores/configuracion/templates/",
        permissions_any_required(["admisiones.gestionar_templates_informe_tecnico"])(
            PlantillaInformeTecnicoListView.as_view()
        ),
        name="gestor_templates_listar",
    ),
    path(
        "comedores/configuracion/templates/crear/",
        permissions_any_required(["admisiones.gestionar_templates_informe_tecnico"])(
            PlantillaInformeTecnicoCreateView.as_view()
        ),
        name="gestor_templates_crear",
    ),
    path(
        "comedores/configuracion/templates/incidencias/",
        permissions_any_required(["admisiones.gestionar_templates_informe_tecnico"])(
            IncidenciaTemplateInformeTecnicoListView.as_view()
        ),
        name="gestor_templates_incidencias_listar",
    ),
    path(
        "comedores/configuracion/templates/incidencias/<int:pk>/",
        permissions_any_required(["admisiones.gestionar_templates_informe_tecnico"])(
            IncidenciaTemplateInformeTecnicoDetailView.as_view()
        ),
        name="gestor_templates_incidencia_detalle",
    ),
    path(
        "comedores/configuracion/templates/variables/",
        permissions_any_required(["admisiones.gestionar_templates_informe_tecnico"])(
            VariableTemplateInformeTecnicoListView.as_view()
        ),
        name="gestor_templates_variables_listar",
    ),
    path(
        "comedores/configuracion/templates/variables/<int:pk>/alternar/",
        permissions_any_required(["admisiones.gestionar_templates_informe_tecnico"])(
            VariableTemplateInformeTecnicoToggleView.as_view()
        ),
        name="gestor_templates_variables_alternar",
    ),
    path(
        "comedores/configuracion/templates/<int:pk>/",
        permissions_any_required(["admisiones.gestionar_templates_informe_tecnico"])(
            PlantillaInformeTecnicoDetailView.as_view()
        ),
        name="gestor_templates_detalle",
    ),
    path(
        "comedores/configuracion/templates/<int:plantilla_pk>/versiones/crear/",
        permissions_any_required(["admisiones.gestionar_templates_informe_tecnico"])(
            PlantillaInformeTecnicoVersionCreateView.as_view()
        ),
        name="gestor_templates_version_crear",
    ),
    path(
        "comedores/configuracion/templates/<int:plantilla_pk>/versiones/<int:version_pk>/editar/",
        permissions_any_required(["admisiones.gestionar_templates_informe_tecnico"])(
            PlantillaInformeTecnicoVersionUpdateView.as_view()
        ),
        name="gestor_templates_version_editar",
    ),
    path(
        "comedores/configuracion/templates/<int:plantilla_pk>/versiones/<int:version_pk>/descartar/",
        permissions_any_required(["admisiones.gestionar_templates_informe_tecnico"])(
            PlantillaInformeTecnicoVersionDiscardView.as_view()
        ),
        name="gestor_templates_version_descartar",
    ),
    path(
        "comedores/configuracion/templates/<int:plantilla_pk>/versiones/<int:version_pk>/previsualizar/",
        permissions_any_required(["admisiones.gestionar_templates_informe_tecnico"])(
            PlantillaInformeTecnicoVersionPreviewView.as_view()
        ),
        name="gestor_templates_version_previsualizar",
    ),
    path(
        "comedores/configuracion/templates/<int:plantilla_pk>/versiones/<int:version_pk>/publicar/",
        permissions_any_required(["admisiones.gestionar_templates_informe_tecnico"])(
            PlantillaInformeTecnicoVersionPublishView.as_view()
        ),
        name="gestor_templates_version_publicar",
    ),
    path(
        "comedores/configuracion/templates/<int:pk>/inactivar/",
        permissions_any_required(["admisiones.gestionar_templates_informe_tecnico"])(
            PlantillaInformeTecnicoDeactivateView.as_view()
        ),
        name="gestor_templates_inactivar",
    ),
    path(
        "comedores/admisiones/tecnicos/listar",
        permissions_any_required(
            [
                "comedores.view_comedor",
                "admisiones.view_admision",
                "acompanamientos.view_informacionrelevante",
            ]
        )(AdmisionesTecnicosListView.as_view()),
        name="admisiones_tecnicos_listar",
    ),
    path(
        "comedores/admisiones/tecnicos/editar/<int:pk>",
        permissions_any_required(
            [
                "comedores.view_comedor",
                "admisiones.view_admision",
                "acompanamientos.view_informacionrelevante",
            ]
        )(AdmisionesTecnicosUpdateView.as_view()),
        name="admisiones_tecnicos_editar",
    ),
    path(
        "comedores/<int:comedor_pk>/admision/<int:pk>/detalle/",
        permissions_any_required(
            [
                "comedores.view_comedor",
                "admisiones.view_admision",
                "acompanamientos.view_informacionrelevante",
            ]
        )(AdmisionDetailView.as_view()),
        name="admision_detalle",
    ),
    path(
        "admision/<int:admision_id>/documentacion/<int:documentacion_id>/subir/",
        subir_archivo_admision,
        name="subir_archivo_admision",
    ),
    path(
        "admision/<int:admision_id>/documentacion/<int:documentacion_id>/eliminar/",
        eliminar_archivo_admision,
        name="eliminar_archivo_admision",
    ),
    path(
        "admision/<int:admision_id>/documentacion/personalizada/agregar/",
        crear_documento_personalizado,
        name="documento_personalizado_crear",
    ),
    path(
        "comedores/admision/informe_tecnico/<str:tipo>/<int:admision_id>/crear/",
        permissions_any_required(
            [
                "comedores.view_comedor",
                "admisiones.view_admision",
                "acompanamientos.view_informacionrelevante",
            ]
        )(InformeTecnicosCreateView.as_view()),
        name="informe_tecnico_crear",
    ),
    path(
        "comedores/admision/informe_tecnico/<str:tipo>/<int:pk>/editar/",
        permissions_any_required(
            [
                "comedores.view_comedor",
                "admisiones.view_admision",
                "acompanamientos.view_informacionrelevante",
            ]
        )(InformeTecnicosUpdateView.as_view()),
        name="informe_tecnico_editar",
    ),
    path(
        "comedores/admision/informe_tecnico/<str:tipo>/<int:pk>/previsualizar/",
        previsualizar_informe_tecnico_template,
        name="informe_tecnico_previsualizar_template",
    ),
    path(
        "comedores/admision/informe_tecnico/<str:tipo>/<int:pk>/descargar-para-gde/",
        permissions_any_required(
            [
                "comedores.view_comedor",
                "admisiones.view_admision",
                "acompanamientos.view_informacionrelevante",
            ]
        )(descargar_informe_tecnico_para_gde),
        name="informe_tecnico_descargar_para_gde",
    ),
    path(
        "comedores/admisiones/<int:pk>/templates/reportar-faltante/",
        reportar_configuracion_faltante_template,
        name="admisiones_reportar_configuracion_faltante_template",
    ),
    path(
        "comedores/admision/informe_tecnico/<str:tipo>/<int:pk>/ver/",
        permissions_any_required(
            [
                "comedores.view_comedor",
                "admisiones.view_admision",
                "acompanamientos.view_informacionrelevante",
            ]
        )(InformeTecnicoDetailView.as_view()),
        name="informe_tecnico_ver",
    ),
    path(
        "comedores/admision/informe_complementario/<str:tipo>/<int:pk>/ver/",
        permissions_any_required(
            [
                "comedores.view_comedor",
                "admisiones.view_admision",
                "acompanamientos.view_informacionrelevante",
            ]
        )(InformeTecnicoComplementarioDetailView.as_view()),
        name="informe_complementario_ver",
    ),
    path(
        "ajax/actualizar-estado/",
        actualizar_estado_archivo,
        name="actualizar_estado_archivo",
    ),
    path(
        "ajax/actualizar-numero-gde/",
        actualizar_numero_gde_archivo,
        name="actualizar_numero_gde_archivo",
    ),
    path(
        "ajax/actualizar-numero-gde-organizacion/",
        actualizar_numero_gde_organizacion_admision,
        name="actualizar_numero_gde_organizacion_admision",
    ),
    path(
        "admisiones/<int:admision_pk>/resync-convenio/",
        resync_convenio_admision,
        name="admision_resync_convenio",
    ),
    path(
        "ajax/actualizar-convenio-numero/",
        actualizar_convenio_numero,
        name="actualizar_convenio_numero",
    ),
    path(
        "ajax/actualizar-vigente-pwa/",
        actualizar_vigente_pwa,
        name="actualizar_vigente_pwa",
    ),
    path(
        "ajax/actualizar-personas-conveniadas-nomina/",
        actualizar_personas_conveniadas_nomina,
        name="actualizar_personas_conveniadas_nomina",
    ),
    path(
        "ajax/actualizar-num-expediente/",
        actualizar_num_expediente,
        name="actualizar_num_expediente",
    ),
    # Legales
    path(
        "comedores/admisiones/legales/listar",
        permissions_any_required(
            [
                "comedores.view_comedor",
                "admisiones.view_admision",
                "acompanamientos.view_informacionrelevante",
                "expedientespagos.view_expedientepago",
            ]
        )(AdmisionesLegalesListView.as_view()),
        name="admisiones_legales_listar",
    ),
    path(
        "comedores/admisiones/legales/ver/<int:pk>",
        permissions_any_required(
            [
                "comedores.view_comedor",
                "admisiones.view_admision",
                "acompanamientos.view_informacionrelevante",
                "expedientespagos.view_expedientepago",
            ]
        )(AdmisionesLegalesDetailView.as_view()),
        name="admisiones_legales_ver",
    ),
    path(
        "comedores/admisiones/legales/revisar-complementario/<int:pk>",
        permissions_any_required(
            [
                "comedores.view_comedor",
                "admisiones.view_admision",
                "acompanamientos.view_informacionrelevante",
                "expedientespagos.view_expedientepago",
            ]
        )(InformeTecnicoComplementarioReviewView.as_view()),
        name="revisar_informe_complementario",
    ),
    # AJAX endpoints
    path(
        "comedores/admisiones/legales/ajax/",
        admisiones_legales_ajax,
        name="admisiones_legales_ajax",
    ),
]
