from django.urls import path
from django.contrib.auth.decorators import login_required
from comedores.views import (
    ComedorCreateView,
    ComedorDeleteView,
    ComedorDetailView,
    ComedorListView,
    ComedorUpdateView,
    ObservacionCreateView,
    ObservacionDeleteView,
    ObservacionDetailView,
    ObservacionUpdateView,
    NominaDetailView,
    NominaCreateView,
    NominaDeleteView,
    NominaImportarView,
    AsignarDuplaListView,
    relevamiento_crear_editar_ajax,
    nomina_editar_ajax,
    validar_comedor,
)
from comedores.views.export import ComedorExportView


from comedores.views_territorial import (
    obtener_territoriales_api,
    sincronizar_territoriales_api,
    estadisticas_cache_territoriales,
)

# Views de prueba eliminadas

from intervenciones.views import (
    sub_estados_intervenciones_ajax,
    IntervencionCreateView,
    IntervencionUpdateView,
    IntervencionDeleteView,
    subir_archivo_intervencion,
    eliminar_archivo_intervencion,
    IntervencionDetailIndividualView,
    IntervencionDetailView,
)
from core.decorators import permissions_any_required

urlpatterns = [
    path(
        "comedores/listar",
        permissions_any_required(
            [
                "comedores.view_comedor",
                "admisiones.view_admision",
                "acompanamientos.view_informacionrelevante",
            ]
        )(ComedorListView.as_view()),
        name="comedores",
    ),
    path(
        "comedores/exportar",
        permissions_any_required(
            ["auth.role_exportar_a_csv", "auth.role_administrador"]
        )(ComedorExportView.as_view()),
        name="comedor_export",
    ),
    path(
        "comedores/crear",
        permissions_any_required(["comedores.add_comedor"])(
            ComedorCreateView.as_view()
        ),
        name="comedor_crear",
    ),
    path(
        "comedores/<int:pk>",
        permissions_any_required(
            [
                "comedores.view_comedor",
                "admisiones.view_admision",
                "acompanamientos.view_informacionrelevante",
            ]
        )(ComedorDetailView.as_view()),
        name="comedor_detalle",
    ),
    path(
        "comedores/<int:pk>/editar",
        permissions_any_required(["comedores.change_comedor"])(
            ComedorUpdateView.as_view()
        ),
        name="comedor_editar",
    ),
    path(
        "comedores/<int:pk>/eliminar",
        permissions_any_required(["comedores.delete_comedor"])(
            ComedorDeleteView.as_view()
        ),
        name="comedor_eliminar",
    ),
    path(
        "comedores/<comedor_pk>/observacion/crear",
        permissions_any_required(["comedores.add_observacion"])(
            ObservacionCreateView.as_view()
        ),
        name="observacion_crear",
    ),
    path(
        "comedores/observacion/<int:pk>",
        permissions_any_required(["comedores.view_observacion"])(
            ObservacionDetailView.as_view()
        ),
        name="observacion_detalle",
    ),
    path(
        "comedores/observacion/<int:pk>/editar",
        permissions_any_required(["comedores.change_observacion"])(
            ObservacionUpdateView.as_view()
        ),
        name="observacion_editar",
    ),
    path(
        "comedores/observacion/<int:pk>/eliminar",
        permissions_any_required(["comedores.delete_observacion"])(
            ObservacionDeleteView.as_view()
        ),
        name="observacion_eliminar",
    ),
    path(
        "comedores/intervencion/ver/<int:pk>",
        permissions_any_required(["intervenciones.view_intervencion"])(
            IntervencionDetailView.as_view()
        ),
        name="comedor_intervencion_ver",
    ),
    path(
        "comedores/intervencion/crear/<int:pk>",
        permissions_any_required(["intervenciones.add_intervencion"])(
            IntervencionCreateView.as_view()
        ),
        name="comedor_intervencion_crear",
    ),
    path(
        "comedores/intervencion/editar/<int:pk>/<int:pk2>",
        permissions_any_required(["intervenciones.change_intervencion"])(
            IntervencionUpdateView.as_view()
        ),
        name="comedores_intervencion_editar",
    ),
    path(
        "comedores/intervencion/borrar/<int:comedor_id>/<int:intervencion_id>/",
        permissions_any_required(["comedores.delete_nomina"])(
            IntervencionDeleteView.as_view()
        ),
        name="comedor_intervencion_borrar",
    ),
    path(
        "comedores/dupla/asignar/<int:pk>",
        permissions_any_required(["duplas.change_dupla"])(
            AsignarDuplaListView.as_view()
        ),
        name="dupla_asignar",
    ),
    path(
        "comedores/ajax/load-subestadosintervenciones/",
        login_required(sub_estados_intervenciones_ajax),
        name="ajax_load_subestadosintervenciones",
    ),
    path(
        # TODO: Migrar a router DRF (estilo centrodefamilia).
        "intervencion/<int:intervencion_id>/documentacion/subir/",
        permissions_any_required(
            [
                "comedores.view_comedor",
                "admisiones.view_admision",
                "acompanamientos.view_informacionrelevante",
            ]
        )(subir_archivo_intervencion),
        name="subir_archivo_intervencion",
    ),
    path(
        # TODO: Migrar a router DRF (estilo centrodefamilia).
        "intervencion/<int:intervencion_id>/documentacion/eliminar/",
        permissions_any_required(
            [
                "comedores.view_comedor",
                "admisiones.view_admision",
                "acompanamientos.view_informacionrelevante",
            ]
        )(eliminar_archivo_intervencion),
        name="eliminar_archivo_intervencion",
    ),
    path(
        "intervencion/detalle/<int:pk>/",
        permissions_any_required(["intervenciones.view_intervencion"])(
            IntervencionDetailIndividualView.as_view()
        ),
        name="intervencion_detalle",
    ),
    path(
        "comedores/<int:pk>/admision/<int:admision_pk>/nomina/",
        permissions_any_required(["comedores.view_nomina"])(NominaDetailView.as_view()),
        name="nomina_ver",
    ),
    path(
        "comedores/editar-nomina/<int:pk>/",
        permissions_any_required(["comedores.change_nomina"])(nomina_editar_ajax),
        name="nomina_editar_ajax",
    ),
    path(
        "comedores/<int:pk>/admision/<int:admision_pk>/nomina/crear/",
        permissions_any_required(["comedores.add_nomina"])(NominaCreateView.as_view()),
        name="nomina_crear",
    ),
    path(
        "comedores/<int:pk>/admision/<int:admision_pk>/nomina/<int:pk2>/eliminar/",
        permissions_any_required(["comedores.delete_nomina"])(
            NominaDeleteView.as_view()
        ),
        name="nomina_borrar",
    ),
    path(
        "comedores/<int:pk>/admision/<int:admision_pk>/nomina/importar/",
        permissions_any_required(["comedores.add_nomina"])(
            NominaImportarView.as_view()
        ),
        name="nomina_importar",
    ),
    path(
        "comedores/ajax/<int:pk>/relevamiento/",
        relevamiento_crear_editar_ajax,
        name="relevamiento_create_edit_ajax",
    ),
    # esto es prueba de nuevo front para el comedor
    path(
        "comedores_nuevo/<int:pk>",
        permissions_any_required(
            [
                "comedores.view_comedor",
                "admisiones.view_admision",
                "acompanamientos.view_informacionrelevante",
            ]
        )(ComedorDetailView.as_view(template_name="comedor/new_comedor_detail.html")),
        name="nuevo_comedor_detalle",
    ),
    path(
        "comedores/<int:comedor_id>/territoriales/",
        obtener_territoriales_api,
        name="api_obtener_territoriales",
    ),
    path(
        "comedores/<int:comedor_id>/territoriales/sincronizar/",
        sincronizar_territoriales_api,
        name="api_sincronizar_territoriales",
    ),
    path(
        "comedores/territoriales/estadisticas/",
        estadisticas_cache_territoriales,
        name="api_estadisticas_territoriales",
    ),
    path(
        "comedores/<int:pk>/validar/",
        login_required(validar_comedor),
        name="validar_comedor",
    ),
]
