# Generated by Django 4.2.16 on 2025-05-13 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comedores", "0023_comedor_codigo_de_proyecto"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prestacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.CharField(
                        choices=[
                            ("lunes", "Lunes"),
                            ("martes", "Martes"),
                            ("miercoles", "Miércoles"),
                            ("jueves", "Jueves"),
                            ("viernes", "Viernes"),
                            ("sabado", "Sábado"),
                            ("domingo", "Domingo"),
                        ],
                        max_length=20,
                    ),
                ),
                ("desayuno", models.BooleanField(default=False)),
                ("almuerzo", models.BooleanField(default=False)),
                ("merienda", models.BooleanField(default=False)),
                ("cena", models.BooleanField(default=False)),
                (
                    "comedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comedores.comedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InformacionRelevante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_expediente", models.CharField(max_length=255)),
                ("numero_resolucion", models.CharField(max_length=255)),
                ("vencimiento_mandato", models.DateField()),
                ("if_relevamiento", models.CharField(max_length=255)),
                (
                    "comedor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="comedores.comedor",
                    ),
                ),
            ],
        ),
    ]
