# Generated by Django 4.2.16 on 2025-05-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acompanamientos", "0002_compararhitosintervenciones_hitos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hitos",
            name="alta_usuario_plataforma",
            field=models.BooleanField(
                default=False, verbose_name="Alta de usuario en plataforma"
            ),
        ),
        migrations.AlterField(
            model_name="hitos",
            name="habilitacion_tarjeta",
            field=models.BooleanField(
                default=False, verbose_name="Habilitación de tarjeta"
            ),
        ),
    ]
