# Generated by Django 4.2.27 on 2026-04-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acompanamientos", "0005_acompanamiento_data_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acompanamiento",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
