# Generated by Django 5.2.16 on 2026-08-14 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acompanamientos", "0001_squashed_0008"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="acompanamiento",
            name="fecha_finalizado",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Fecha de finalización del acompañamiento",
            ),
        ),
        migrations.AddField(
            model_name="acompanamiento",
            name="finalizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="acompanamientos_finalizados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Finalizado por",
            ),
        ),
    ]
