# Generated by Django 4.2.16 on 2025-04-15 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comedores", "0024_remove_archivosadmision_admision_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Admision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado", models.DateField(auto_now_add=True, null=True)),
                ("modificado", models.DateField(auto_now=True, null=True)),
                (
                    "comedor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="comedores.comedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "admisiontecnico",
                "verbose_name_plural": "admisionestecnicos",
                "ordering": ["-creado"],
            },
        ),
        migrations.CreateModel(
            name="TipoConvenio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "tipoconvenio",
                "verbose_name_plural": "tiposconvenios",
                "indexes": [
                    models.Index(
                        fields=["nombre"], name="admisiones__nombre_bdabcc_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EstadoAdmision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "estadosadmision",
                "verbose_name_plural": "estadosadmisiones",
                "indexes": [
                    models.Index(
                        fields=["nombre"], name="admisiones__nombre_bcd423_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DuplaContacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("whatsapp", "Whatsapp"),
                            ("email", "Email"),
                            ("llamada", "Llamada"),
                        ],
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField()),
                (
                    "comedor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="comedores.comedor",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Documentacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("todos", "Todos"), ("especifico", "Específico")],
                        default="especifico",
                        max_length=20,
                    ),
                ),
                (
                    "convenios",
                    models.ManyToManyField(blank=True, to="admisiones.tipoconvenio"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArchivoAdmision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True, null=True, upload_to="comedor/admisiones_archivos/"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("pendiente", "Pendiente"), ("validar", "A Validar")],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "admision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admisiones.admision",
                    ),
                ),
                (
                    "documentacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admisiones.documentacion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="admision",
            name="estado",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="admisiones.estadoadmision",
            ),
        ),
        migrations.AddField(
            model_name="admision",
            name="tipo_convenio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="admisiones.tipoconvenio",
            ),
        ),
        migrations.AddIndex(
            model_name="admision",
            index=models.Index(
                fields=["comedor"], name="admisiones__comedor_1d8f2b_idx"
            ),
        ),
    ]
