# Generated by Django 4.2.16 on 2025-04-16 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDocumentacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Tipo de Documentación",
                "verbose_name_plural": "Tipos de Documentación",
                "ordering": ["nombre"],
            },
        ),
        migrations.AlterField(
            model_name="documentacion",
            name="tipo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="admisiones.tipodocumentacion",
            ),
        ),
    ]
