# Generated by Django 4.2.16 on 2025-05-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0002_tipodocumentacion_alter_documentacion_tipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivoadmision",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("validar", "A Validar"),
                    ("A Validar Abogado", "A Validar Abogado"),
                    ("Rectificar", "Rectificar"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
