# Generated by Django 4.2.16 on 2025-05-06 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0003_alter_archivoadmision_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="estadoadmision",
            name="nombre",
            field=models.CharField(max_length=15),
        ),
    ]
