# Generated by Django 4.2.20 on 2025-07-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0004_informecomplementario_informecomplementariocampos"),
    ]

    operations = [
        migrations.AddField(
            model_name="informecomplementario",
            name="pdf",
            field=models.FileField(
                null=True, upload_to="admisiones/informes_complementarios/"
            ),
        ),
    ]
