# Generated by Django 4.2.16 on 2025-05-07 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0004_alter_estadoadmision_nombre"),
    ]

    operations = [
        migrations.CreateModel(
            name="InformeTecnicoJuridico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expediente_nro",
                    models.CharField(max_length=100, verbose_name="Expediente Nro."),
                ),
                (
                    "nombre_org",
                    models.CharField(
                        max_length=255,
                        verbose_name="Nombre de la Organización Solicitante",
                    ),
                ),
                (
                    "domicilio_org",
                    models.CharField(
                        max_length=255,
                        verbose_name="Domicilio de la Organización Solicitante",
                    ),
                ),
                (
                    "localidad_org",
                    models.CharField(
                        max_length=255,
                        verbose_name="Localidad de la Organización Solicitante",
                    ),
                ),
                (
                    "partido_org",
                    models.CharField(
                        max_length=255,
                        verbose_name="Partido de la Organización Solicitante",
                    ),
                ),
                (
                    "provincia_org",
                    models.CharField(
                        max_length=255,
                        verbose_name="Provincia de la Organización Solicitante",
                    ),
                ),
                (
                    "telefono_org",
                    models.CharField(
                        max_length=50,
                        verbose_name="Teléfono de la Organización Solicitante",
                    ),
                ),
                (
                    "mail_org",
                    models.EmailField(
                        max_length=254,
                        verbose_name="Mail de la Organización Solicitante",
                    ),
                ),
                (
                    "cuit_org",
                    models.CharField(
                        max_length=20,
                        verbose_name="CUIT de la Organización Solicitante",
                    ),
                ),
                (
                    "representante_nombre",
                    models.CharField(
                        max_length=255,
                        verbose_name="Nombre y Apellido del Representante",
                    ),
                ),
                (
                    "representante_cargo",
                    models.CharField(
                        max_length=100, verbose_name="Cargo del Representante"
                    ),
                ),
                (
                    "representante_dni",
                    models.CharField(
                        max_length=20, verbose_name="DNI del Representante"
                    ),
                ),
                (
                    "tipo_espacio",
                    models.CharField(
                        choices=[("Comedor", "Comedor"), ("Merendero", "Merendero")],
                        max_length=50,
                        verbose_name="Tipo de Espacio Comunitario",
                    ),
                ),
                (
                    "nombre_espacio",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Comedor/Merendero"
                    ),
                ),
                (
                    "domicilio_espacio",
                    models.CharField(
                        max_length=255, verbose_name="Domicilio del Comedor/Merendero"
                    ),
                ),
                (
                    "barrio_espacio",
                    models.CharField(
                        max_length=255, verbose_name="Barrio del Comedor/Merendero"
                    ),
                ),
                (
                    "localidad_espacio",
                    models.CharField(
                        max_length=255, verbose_name="Localidad del Comedor/Merendero"
                    ),
                ),
                (
                    "partido_espacio",
                    models.CharField(
                        max_length=255, verbose_name="Partido del Comedor/Merendero"
                    ),
                ),
                (
                    "provincia_espacio",
                    models.CharField(
                        max_length=255, verbose_name="Provincia del Comedor/Merendero"
                    ),
                ),
                (
                    "responsable_tarjeta_nombre",
                    models.CharField(
                        max_length=255,
                        verbose_name="Nombre del Responsable de la Tarjeta",
                    ),
                ),
                (
                    "responsable_tarjeta_dni",
                    models.CharField(
                        max_length=20, verbose_name="DNI del Responsable de la Tarjeta"
                    ),
                ),
                (
                    "responsable_tarjeta_domicilio",
                    models.CharField(
                        max_length=255,
                        verbose_name="Domicilio del Responsable de la Tarjeta",
                    ),
                ),
                (
                    "responsable_tarjeta_localidad",
                    models.CharField(
                        max_length=255,
                        verbose_name="Localidad del Responsable de la Tarjeta",
                    ),
                ),
                (
                    "responsable_tarjeta_provincia",
                    models.CharField(
                        max_length=255,
                        verbose_name="Provincia del Responsable de la Tarjeta",
                    ),
                ),
                (
                    "responsable_tarjeta_telefono",
                    models.CharField(
                        max_length=50,
                        verbose_name="Teléfono del Responsable de la Tarjeta",
                    ),
                ),
                (
                    "responsable_tarjeta_mail",
                    models.EmailField(
                        max_length=254,
                        verbose_name="Mail del Responsable de la Tarjeta",
                    ),
                ),
                (
                    "nota_gde_if",
                    models.CharField(max_length=255, verbose_name="Nota GDE IF"),
                ),
                (
                    "personas_desayuno_letras",
                    models.CharField(
                        max_length=255,
                        verbose_name="Cantidad Personas Desayuno (en letras)",
                    ),
                ),
                (
                    "dias_desayuno_letras",
                    models.CharField(
                        max_length=255,
                        verbose_name="Cantidad Días Desayuno (en letras)",
                    ),
                ),
                (
                    "personas_almuerzo_letras",
                    models.CharField(
                        max_length=255,
                        verbose_name="Cantidad Personas Almuerzo (en letras)",
                    ),
                ),
                (
                    "dias_almuerzo_letras",
                    models.CharField(
                        max_length=255,
                        verbose_name="Cantidad Días Almuerzo (en letras)",
                    ),
                ),
                (
                    "personas_merienda_letras",
                    models.CharField(
                        max_length=255,
                        verbose_name="Cantidad Personas Merienda (en letras)",
                    ),
                ),
                (
                    "dias_merienda_letras",
                    models.CharField(
                        max_length=255,
                        verbose_name="Cantidad Días Merienda (en letras)",
                    ),
                ),
                (
                    "personas_cena_letras",
                    models.CharField(
                        max_length=255,
                        verbose_name="Cantidad Personas Cena (en letras)",
                    ),
                ),
                (
                    "dias_cena_letras",
                    models.CharField(
                        max_length=255, verbose_name="Cantidad Días Cena (en letras)"
                    ),
                ),
                (
                    "constancia_subsidios_dnsa",
                    models.CharField(
                        max_length=255,
                        verbose_name="Constancia IF RTA DNSA sobre subsidios",
                    ),
                ),
                (
                    "constancia_subsidios_pnud",
                    models.CharField(
                        max_length=255,
                        verbose_name="Constancia IF RTA PNUD sobre subsidios",
                    ),
                ),
                (
                    "validacion_rncm_if",
                    models.CharField(
                        max_length=255,
                        verbose_name="Validación Registro Nacional Comedores/Merenderos (IF)",
                    ),
                ),
                (
                    "partido_destinataria",
                    models.CharField(
                        max_length=255,
                        verbose_name="Partido donde se ubica la población destinataria",
                    ),
                ),
                (
                    "provincia_destinataria",
                    models.CharField(
                        max_length=255,
                        verbose_name="Provincia donde se ubica la población destinataria",
                    ),
                ),
                (
                    "if_relevamiento",
                    models.CharField(
                        max_length=255, verbose_name="IF de relevamiento territorial"
                    ),
                ),
                (
                    "prestaciones_aprobadas_desayuno",
                    models.IntegerField(
                        default=0,
                        verbose_name="Cantidad de prestaciones aprobadas Desayuno (Lunes a Domingo)",
                    ),
                ),
                (
                    "prestaciones_aprobadas_almuerzo",
                    models.IntegerField(
                        default=0,
                        verbose_name="Cantidad de prestaciones aprobadas Almuerzo (Lunes a Domingo)",
                    ),
                ),
                (
                    "prestaciones_aprobadas_merienda",
                    models.IntegerField(
                        default=0,
                        verbose_name="Cantidad de prestaciones aprobadas Merienda (Lunes a Domingo)",
                    ),
                ),
                (
                    "prestaciones_aprobadas_cena",
                    models.IntegerField(
                        default=0,
                        verbose_name="Cantidad de prestaciones aprobadas Cena (Lunes a Domingo)",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Para revision", "Para revisión"),
                            ("Validado", "Validado"),
                            ("A subsanar", "A subsanar"),
                        ],
                        default="Para revision",
                        max_length=20,
                        verbose_name="Estado del Informe",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InformeTecnicoBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expediente_nro", models.CharField(max_length=100)),
                (
                    "nombre_org",
                    models.CharField(
                        max_length=255,
                        verbose_name="Nombre de la Organización Solicitante",
                    ),
                ),
                (
                    "domicilio_org",
                    models.CharField(
                        max_length=255,
                        verbose_name="Domicilio de la Organización Solicitante",
                    ),
                ),
                (
                    "localidad_org",
                    models.CharField(
                        max_length=255,
                        verbose_name="Localidad de la Organización Solicitante",
                    ),
                ),
                (
                    "partido_org",
                    models.CharField(
                        max_length=255,
                        verbose_name="Partido de la Organización Solicitante",
                    ),
                ),
                (
                    "provincia_org",
                    models.CharField(
                        max_length=255,
                        verbose_name="Provincia de la Organización Solicitante",
                    ),
                ),
                (
                    "telefono_org",
                    models.CharField(
                        max_length=50,
                        verbose_name="Teléfono de la Organización Solicitante",
                    ),
                ),
                (
                    "mail_org",
                    models.EmailField(
                        max_length=254,
                        verbose_name="Mail de la Organización Solicitante",
                    ),
                ),
                (
                    "cuit_org",
                    models.CharField(
                        max_length=20,
                        verbose_name="CUIT de la Organización Solicitante",
                    ),
                ),
                (
                    "representante_nombre",
                    models.CharField(
                        max_length=255,
                        verbose_name="Nombre y Apellido del Representante",
                    ),
                ),
                (
                    "representante_cargo",
                    models.CharField(
                        max_length=100, verbose_name="Cargo del Representante"
                    ),
                ),
                (
                    "representante_dni",
                    models.CharField(
                        max_length=20, verbose_name="DNI del Representante"
                    ),
                ),
                (
                    "tipo_espacio",
                    models.CharField(
                        choices=[("Comedor", "Comedor"), ("Merendero", "Merendero")],
                        max_length=50,
                        verbose_name="Tipo de Espacio Comunitario",
                    ),
                ),
                (
                    "nombre_espacio",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Comedor/Merendero"
                    ),
                ),
                (
                    "domicilio_espacio",
                    models.CharField(
                        max_length=255, verbose_name="Domicilio del Comedor/Merendero"
                    ),
                ),
                (
                    "barrio_espacio",
                    models.CharField(
                        max_length=255, verbose_name="Barrio del Comedor/Merendero"
                    ),
                ),
                (
                    "localidad_espacio",
                    models.CharField(
                        max_length=255, verbose_name="Localidad del Comedor/Merendero"
                    ),
                ),
                (
                    "partido_espacio",
                    models.CharField(
                        max_length=255, verbose_name="Partido del Comedor/Merendero"
                    ),
                ),
                (
                    "provincia_espacio",
                    models.CharField(
                        max_length=255, verbose_name="Provincia del Comedor/Merendero"
                    ),
                ),
                (
                    "responsable_tarjeta_nombre",
                    models.CharField(
                        max_length=255,
                        verbose_name="Nombre del Responsable de la Tarjeta",
                    ),
                ),
                (
                    "responsable_tarjeta_dni",
                    models.CharField(
                        max_length=20, verbose_name="DNI del Responsable de la Tarjeta"
                    ),
                ),
                (
                    "responsable_tarjeta_domicilio",
                    models.CharField(
                        max_length=255, verbose_name="Domicilio del Responsable"
                    ),
                ),
                (
                    "responsable_tarjeta_localidad",
                    models.CharField(
                        max_length=255, verbose_name="Localidad del Responsable"
                    ),
                ),
                (
                    "responsable_tarjeta_provincia",
                    models.CharField(
                        max_length=255, verbose_name="Provincia del Responsable"
                    ),
                ),
                (
                    "responsable_tarjeta_telefono",
                    models.CharField(
                        max_length=50, verbose_name="Teléfono del Responsable"
                    ),
                ),
                (
                    "responsable_tarjeta_mail",
                    models.EmailField(
                        max_length=254, verbose_name="Mail del Responsable"
                    ),
                ),
                (
                    "declaracion_jurada",
                    models.CharField(
                        max_length=255,
                        verbose_name="Declaración Jurada sobre recepción de subsidios nacionales",
                    ),
                ),
                (
                    "constancia_inexistencia_subsidios",
                    models.CharField(
                        max_length=255,
                        verbose_name="Constancia de inexistencia de percepción de otros subsidios nacionales",
                    ),
                ),
                (
                    "organizacion_avalista_1",
                    models.CharField(
                        max_length=255, verbose_name="Organización Avalista 1"
                    ),
                ),
                (
                    "organizacion_avalista_2",
                    models.CharField(
                        max_length=255, verbose_name="Organización Avalista 2"
                    ),
                ),
                (
                    "material_difusion",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Material de difusión vinculado",
                    ),
                ),
                (
                    "prestaciones_desayuno",
                    models.IntegerField(
                        default=0,
                        verbose_name="Cantidad de Prestaciones Mensuales Desayuno",
                    ),
                ),
                (
                    "prestaciones_almuerzo",
                    models.IntegerField(
                        default=0,
                        verbose_name="Cantidad de Prestaciones Mensuales Almuerzo",
                    ),
                ),
                (
                    "prestaciones_merienda",
                    models.IntegerField(
                        default=0,
                        verbose_name="Cantidad de Prestaciones Mensuales Merienda",
                    ),
                ),
                (
                    "prestaciones_cena",
                    models.IntegerField(
                        default=0,
                        verbose_name="Cantidad de Prestaciones Mensuales Cena",
                    ),
                ),
                (
                    "prestaciones_totales",
                    models.IntegerField(
                        default=0, verbose_name="Total Mensual de Prestaciones"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Para revision", "Para revisión"),
                            ("Validado", "Validado"),
                            ("A subsanar", "A subsanar"),
                        ],
                        default="Para revision",
                        max_length=20,
                        verbose_name="Estado de la Solicitud",
                    ),
                ),
                (
                    "admision",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="admisiones.admision",
                    ),
                ),
            ],
        ),
    ]
