# Generated by Django 4.2.16 on 2025-05-07 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0005_informetecnicojuridico_informetecnicobase"),
    ]

    operations = [
        migrations.AddField(
            model_name="informetecnicojuridico",
            name="admision",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="admisiones.admision",
            ),
        ),
    ]
