# Generated by Django 4.2.20 on 2025-09-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0006_informetecnico_conclusiones"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivoadmision",
            name="numero_gde",
            field=models.CharField(
                blank=True,
                help_text="Número de expediente GDE asignado por el técnico después de la carga en sistema externo",
                max_length=50,
                null=True,
                verbose_name="Número de GDE",
            ),
        ),
    ]
