# Generated by Django 4.2.16 on 2025-05-07 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0029_comedor_num_expediente_comedor_num_if"),
        ("admisiones", "0006_informetecnicojuridico_admision"),
    ]

    operations = [
        migrations.CreateModel(
            name="InformeTecnicoPDF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("base", "Base"), ("juridico", "Jurídico")],
                        max_length=20,
                    ),
                ),
                ("informe_id", models.PositiveIntegerField()),
                ("archivo", models.FileField(upload_to="informes_tecnicos/")),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "admision",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="informe_pdf",
                        to="admisiones.admision",
                    ),
                ),
                (
                    "comedor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="comedores.comedor",
                    ),
                ),
            ],
        ),
    ]
