# Generated by Django 4.2.20 on 2025-09-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0007_alter_informetecnico_conclusiones"),
        ("admisiones", "0007_anexo_barrio_squashed_0008_alter_anexo_barrio"),
    ]

    operations = []
