# Generated by Django 4.2.20 on 2025-10-01 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "comedores",
            "0007_rename_comedores_territorial_provincia_activo_idx_comedores_t_provinc_38a553_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admisiones", "0011_alter_anexo_barrio_alter_archivoadmision_estado"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentacion",
            name="tipo",
        ),
        migrations.AddField(
            model_name="admision",
            name="archivo_convenio",
            field=models.FileField(
                blank=True, null=True, upload_to="admisiones/convenios/"
            ),
        ),
        migrations.AddField(
            model_name="admision",
            name="archivo_disposicion",
            field=models.FileField(
                blank=True, null=True, upload_to="admisiones/disposicion/"
            ),
        ),
        migrations.AddField(
            model_name="admision",
            name="dictamen_motivo",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "observacion en informe técnico",
                        "Observación en informe técnico",
                    ),
                    (
                        "observacion en proyecto de convenio",
                        "Observación en proyecto de convenio",
                    ),
                    (
                        "observacion en proyecto de disposicion",
                        "Observación en proyecto de disposición",
                    ),
                ],
                max_length=40,
                null=True,
                verbose_name="Tipo de observación",
            ),
        ),
        migrations.AddField(
            model_name="admision",
            name="enviada_a_archivo",
            field=models.BooleanField(default=False, verbose_name="Enviada a Archivo"),
        ),
        migrations.AddField(
            model_name="admision",
            name="informe_sga",
            field=models.BooleanField(
                default=False, verbose_name="Estados Informe SGA"
            ),
        ),
        migrations.AddField(
            model_name="admision",
            name="intervencion_juridicos",
            field=models.CharField(
                blank=True,
                choices=[("validado", "Validado"), ("rechazado", "Rechazado")],
                max_length=20,
                null=True,
                verbose_name="Intervención Jurídicos",
            ),
        ),
        migrations.AddField(
            model_name="admision",
            name="numero_convenio",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="admision",
            name="numero_disposicion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="admision",
            name="observaciones_informe_tecnico_complementario",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Observaciones informe técnico complementario",
            ),
        ),
        migrations.AddField(
            model_name="admision",
            name="observaciones_reinicio_expediente",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Observaciones reinicio de expediente",
            ),
        ),
        migrations.AddField(
            model_name="admision",
            name="rechazo_juridicos_motivo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("providencia", "Por providencia"),
                    ("dictamen", "Por dictamen"),
                ],
                max_length=40,
                null=True,
                verbose_name="Motivo Rechazo Jurídicos",
            ),
        ),
        migrations.AddField(
            model_name="archivoadmision",
            name="nombre_personalizado",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Nombre personalizado",
            ),
        ),
        migrations.AddField(
            model_name="documentacion",
            name="obligatorio",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="formularioproyectodeconvenio",
            name="archivo_docx",
            field=models.FileField(
                null=True, upload_to="admisiones/formularios_convenio/docx"
            ),
        ),
        migrations.AddField(
            model_name="formularioproyectodeconvenio",
            name="numero_if",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="formularioproyectodisposicion",
            name="archivo_docx",
            field=models.FileField(
                null=True, upload_to="admisiones/formularios_disposicion/docx"
            ),
        ),
        migrations.AddField(
            model_name="formularioproyectodisposicion",
            name="numero_if",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="informetecnico",
            name="estado_formulario",
            field=models.CharField(
                choices=[("borrador", "Borrador"), ("finalizado", "Finalizado")],
                default="borrador",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="informetecnicopdf",
            name="archivo_docx",
            field=models.FileField(
                blank=True, null=True, upload_to="admisiones/informes_tecnicos/docx"
            ),
        ),
        migrations.AlterField(
            model_name="admision",
            name="comedor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admisiones_admisiones",
                to="comedores.comedor",
            ),
        ),
        migrations.AlterField(
            model_name="admisionhistorial",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admisiones_historial",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="archivoadmision",
            name="documentacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="admisiones.documentacion",
            ),
        ),
        migrations.AlterField(
            model_name="archivoadmision",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("Documento adjunto", "Documento adjunto"),
                    ("A Validar Abogado", "A Validar Abogado"),
                    ("Rectificar", "Rectificar"),
                    ("Aceptado", "Aceptado"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="formularioproyectodeconvenio",
            name="admision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admisiones_proyecto_convenio",
                to="admisiones.admision",
            ),
        ),
        migrations.AlterField(
            model_name="formularioproyectodeconvenio",
            name="archivo",
            field=models.FileField(
                null=True, upload_to="admisiones/formularios_convenio/pdf"
            ),
        ),
        migrations.AlterField(
            model_name="formularioproyectodeconvenio",
            name="creado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admisiones_formularios_convenio",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="formularioproyectodisposicion",
            name="admision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admisiones_proyecto_disposicion",
                to="admisiones.admision",
            ),
        ),
        migrations.AlterField(
            model_name="formularioproyectodisposicion",
            name="archivo",
            field=models.FileField(
                null=True, upload_to="admisiones/formularios_disposicion/pdf"
            ),
        ),
        migrations.AlterField(
            model_name="formularioproyectodisposicion",
            name="creado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admisiones_formularios_disposicion",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="informecomplementario",
            name="creado_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admisiones_informes_complementarios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="informetecnico",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Iniciado", "Iniciado"),
                    ("Para revision", "Para revisión"),
                    ("Validado", "Validado"),
                    ("A subsanar", "A subsanar"),
                ],
                max_length=20,
                verbose_name="Estado del Informe",
            ),
        ),
        migrations.AlterField(
            model_name="informetecnico",
            name="prestaciones_almuerzo_letras",
            field=models.CharField(
                max_length=255,
                verbose_name="Cantidad de Prestaciones Semanales Almuerzo - En números (Solicitante)",
            ),
        ),
        migrations.AlterField(
            model_name="informetecnico",
            name="prestaciones_cena_letras",
            field=models.CharField(
                max_length=255,
                verbose_name="Cantidad de Prestaciones Semanales Cena - En números (Solicitante)",
            ),
        ),
        migrations.AlterField(
            model_name="informetecnico",
            name="prestaciones_desayuno_letras",
            field=models.CharField(
                max_length=255,
                verbose_name="Cantidad de Prestaciones Semanales Desayuno - En números (Solicitante)",
            ),
        ),
        migrations.AlterField(
            model_name="informetecnico",
            name="prestaciones_merienda_letras",
            field=models.CharField(
                max_length=255,
                verbose_name="Cantidad de Prestaciones Semanales Merienda - En números (Solicitante)",
            ),
        ),
        migrations.AlterField(
            model_name="informetecnicopdf",
            name="archivo",
            field=models.FileField(upload_to="admisiones/informes_tecnicos/pdf"),
        ),
        migrations.AlterField(
            model_name="informetecnicopdf",
            name="comedor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admisiones_informes_tecnicos_pdf",
                to="comedores.comedor",
            ),
        ),
        migrations.DeleteModel(
            name="TipoDocumentacion",
        ),
    ]
