# Generated by Django 4.2.16 on 2025-05-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0013_admisionhistorial"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivoadmision",
            name="num_if",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
