# Generated by Django 4.2.16 on 2025-05-20 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admisiones", "0014_archivoadmision_num_if"),
    ]

    operations = [
        migrations.AddField(
            model_name="admision",
            name="legales_num_if",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="admision",
            name="estado_legales",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A Rectificar", "A Rectificar"),
                    ("Rectificado", "Rectificado"),
                    ("Pendiente de Validación", "Pendiente de Validación"),
                    ("Finalizado", "Finalizado"),
                ],
                max_length=40,
                null=True,
                verbose_name="Estado",
            ),
        ),
        migrations.CreateModel(
            name="FormularioRESO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pregunta1", models.TextField()),
                ("pregunta2", models.TextField()),
                ("pregunta3", models.TextField()),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "admision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formularios_reso",
                        to="admisiones.admision",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormularioProyectoDeConvenio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pregunta1", models.TextField()),
                ("pregunta2", models.TextField()),
                ("pregunta3", models.TextField()),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "admision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formularios_proyecto_convenio",
                        to="admisiones.admision",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
