# Generated by Django 4.2.16 on 2025-05-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0016_alter_formularioproyectodeconvenio_pregunta1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admision",
            name="estado_legales",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A Rectificar", "A Rectificar"),
                    ("Rectificado", "Rectificado"),
                    ("Pendiente de Validacion", "Pendiente de Validacion"),
                    ("Finalizado", "Finalizado"),
                ],
                max_length=40,
                null=True,
                verbose_name="Estado",
            ),
        ),
    ]
