# Generated by Django 4.2.16 on 2025-05-21 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0017_alter_admision_estado_legales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admision",
            name="estado_legales",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A Rectificar", "A Rectificar"),
                    ("Rectificado", "Rectificado"),
                    ("Pendiente de Validacion", "Pendiente de Validacion"),
                    ("Informe SGA Generado", "Informe SGA Generado"),
                    ("Resolucion Generada", "Resolucion Generada"),
                    ("Convenio Firmado", "Convenio Firmado"),
                    ("Finalizado", "Finalizado"),
                ],
                max_length=40,
                null=True,
                verbose_name="Estado",
            ),
        ),
        migrations.CreateModel(
            name="DocumentosExpediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=255, null=True)),
                ("tipo", models.CharField(blank=True, max_length=255, null=True)),
                ("value", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="comedor/admisiones_archivos/expediente",
                    ),
                ),
                (
                    "rectificar",
                    models.BooleanField(default=False, verbose_name="Rectificar"),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                ("num_if", models.CharField(blank=True, max_length=100, null=True)),
                ("creado", models.DateField(auto_now_add=True, null=True)),
                (
                    "admision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admisiones.admision",
                    ),
                ),
            ],
        ),
    ]
