# Generated by Django 4.2.20 on 2025-06-15 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0018_alter_admision_estado_legales_documentosexpediente"),
    ]

    operations = [
        migrations.CreateModel(
            name="InformeTecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("base", "Base"), ("juridico", "Jurídico")],
                        max_length=20,
                    ),
                ),
                ("expediente_nro", models.CharField(max_length=100)),
                (
                    "nombre_organizacion",
                    models.CharField(
                        max_length=255,
                        verbose_name="Nombre de la Organización Solicitante",
                    ),
                ),
                (
                    "domicilio_organizacion",
                    models.CharField(
                        max_length=255,
                        verbose_name="Domicilio de la Organización Solicitante",
                    ),
                ),
                (
                    "localidad_organizacion",
                    models.CharField(
                        max_length=255,
                        verbose_name="Localidad de la Organización Solicitante",
                    ),
                ),
                (
                    "partido_organizacion",
                    models.CharField(
                        max_length=255,
                        verbose_name="Partido de la Organización Solicitante",
                    ),
                ),
                (
                    "provincia_organizacion",
                    models.CharField(
                        max_length=255,
                        verbose_name="Provincia de la Organización Solicitante",
                    ),
                ),
                (
                    "telefono_organizacion",
                    models.CharField(
                        max_length=50,
                        verbose_name="Teléfono de la Organización Solicitante",
                    ),
                ),
                (
                    "mail_organizacion",
                    models.EmailField(
                        max_length=254,
                        verbose_name="Mail de la Organización Solicitante",
                    ),
                ),
                (
                    "cuit_organizacion",
                    models.CharField(
                        max_length=20,
                        verbose_name="CUIT de la Organización Solicitante",
                    ),
                ),
                (
                    "representante_nombre",
                    models.CharField(
                        max_length=255,
                        verbose_name="Nombre y Apellido del Representante",
                    ),
                ),
                (
                    "representante_cargo",
                    models.CharField(
                        max_length=100, verbose_name="Cargo del Representante"
                    ),
                ),
                (
                    "representante_dni",
                    models.CharField(
                        max_length=20, verbose_name="DNI del Representante"
                    ),
                ),
                (
                    "tipo_espacio",
                    models.CharField(
                        choices=[("Comedor", "Comedor"), ("Merendero", "Merendero")],
                        max_length=50,
                        verbose_name="Tipo de Espacio Comunitario",
                    ),
                ),
                (
                    "nombre_espacio",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Comedor/Merendero"
                    ),
                ),
                (
                    "domicilio_espacio",
                    models.CharField(
                        max_length=255, verbose_name="Domicilio del Comedor/Merendero"
                    ),
                ),
                (
                    "barrio_espacio",
                    models.CharField(
                        max_length=255, verbose_name="Barrio del Comedor/Merendero"
                    ),
                ),
                (
                    "localidad_espacio",
                    models.CharField(
                        max_length=255, verbose_name="Localidad del Comedor/Merendero"
                    ),
                ),
                (
                    "partido_espacio",
                    models.CharField(
                        max_length=255, verbose_name="Partido del Comedor/Merendero"
                    ),
                ),
                (
                    "provincia_espacio",
                    models.CharField(
                        max_length=255, verbose_name="Provincia del Comedor/Merendero"
                    ),
                ),
                (
                    "responsable_tarjeta_nombre",
                    models.CharField(
                        max_length=255,
                        verbose_name="Nombre del Responsable de la Tarjeta",
                    ),
                ),
                (
                    "responsable_tarjeta_dni",
                    models.CharField(
                        max_length=20, verbose_name="DNI del Responsable de la Tarjeta"
                    ),
                ),
                (
                    "responsable_tarjeta_domicilio",
                    models.CharField(
                        max_length=255,
                        verbose_name="Domicilio del Responsable de la Tarjeta",
                    ),
                ),
                (
                    "responsable_tarjeta_localidad",
                    models.CharField(
                        max_length=255,
                        verbose_name="Localidad del Responsable de la Tarjeta",
                    ),
                ),
                (
                    "responsable_tarjeta_provincia",
                    models.CharField(
                        max_length=255,
                        verbose_name="Provincia del Responsable de la Tarjeta",
                    ),
                ),
                (
                    "responsable_tarjeta_telefono",
                    models.CharField(
                        max_length=50,
                        verbose_name="Teléfono del Responsable de la Tarjeta",
                    ),
                ),
                (
                    "responsable_tarjeta_mail",
                    models.EmailField(
                        max_length=254,
                        verbose_name="Mail del Responsable de la Tarjeta",
                    ),
                ),
                (
                    "nota_gde_if",
                    models.CharField(max_length=255, verbose_name="Nota GDE IF"),
                ),
                (
                    "constancia_subsidios_dnsa",
                    models.CharField(
                        max_length=255,
                        verbose_name="Constancia IF RTA DNSA sobre subsidios",
                    ),
                ),
                (
                    "constancia_subsidios_pnud",
                    models.CharField(
                        max_length=255,
                        verbose_name="Constancia IF RTA PNUD sobre subsidios",
                    ),
                ),
                (
                    "partido_poblacion_destinataria",
                    models.CharField(
                        max_length=255,
                        verbose_name="Partido donde se ubica la población destinataria",
                    ),
                ),
                (
                    "provincia_poblacion_destinataria",
                    models.CharField(
                        max_length=255,
                        verbose_name="Provincia donde se ubica la población destinataria",
                    ),
                ),
                (
                    "prestaciones_desayuno_numero",
                    models.IntegerField(
                        default=0,
                        verbose_name="Cantidad de Prestaciones Semanales Desayuno - En números (Solicitante)",
                    ),
                ),
                (
                    "prestaciones_almuerzo_numero",
                    models.IntegerField(
                        default=0,
                        verbose_name="Cantidad de Prestaciones Semanales Almuerzo - En números (Solicitante)",
                    ),
                ),
                (
                    "prestaciones_merienda_numero",
                    models.IntegerField(
                        default=0,
                        verbose_name="Cantidad de Prestaciones Semanales Merienda - En números (Solicitante)",
                    ),
                ),
                (
                    "prestaciones_cena_numero",
                    models.IntegerField(
                        default=0,
                        verbose_name="Cantidad de Prestaciones Semanales Cena - En números (Solicitante)",
                    ),
                ),
                (
                    "prestaciones_desayuno_letras",
                    models.CharField(
                        max_length=255,
                        verbose_name="Cantidad de Prestaciones Semanales Desayuno - En letras (Solicitante)",
                    ),
                ),
                (
                    "prestaciones_almuerzo_letras",
                    models.CharField(
                        max_length=255,
                        verbose_name="Cantidad de Prestaciones Semanales Almuerzo - En letras (Solicitante)",
                    ),
                ),
                (
                    "prestaciones_merienda_letras",
                    models.CharField(
                        max_length=255,
                        verbose_name="Cantidad de Prestaciones Semanales Merienda - En letras (Solicitante)",
                    ),
                ),
                (
                    "prestaciones_cena_letras",
                    models.CharField(
                        max_length=255,
                        verbose_name="Cantidad de Prestaciones Semanales Cena - En letras (Solicitante)",
                    ),
                ),
                (
                    "if_relevamiento",
                    models.CharField(
                        max_length=255, verbose_name="IF de relevamiento territorial"
                    ),
                ),
                (
                    "declaracion_jurada_recepcion_subsidios",
                    models.CharField(
                        max_length=255,
                        verbose_name="Declaración Jurada sobre recepción de subsidios nacionales",
                    ),
                ),
                (
                    "constancia_inexistencia_percepcion_otros_subsidios",
                    models.CharField(
                        max_length=255,
                        verbose_name="Constancia de inexistencia de percepción de otros subsidios nacionales",
                    ),
                ),
                (
                    "organizacion_avalista_1",
                    models.CharField(
                        max_length=255, verbose_name="Organización Avalista 1"
                    ),
                ),
                (
                    "organizacion_avalista_2",
                    models.CharField(
                        max_length=255, verbose_name="Organización Avalista 2"
                    ),
                ),
                (
                    "material_difusion_vinculado",
                    models.CharField(
                        max_length=255, verbose_name="Material de difusión vinculado"
                    ),
                ),
                (
                    "validacion_registro_nacional",
                    models.CharField(
                        max_length=255,
                        verbose_name="Validación Registro Nacional Comedores/Merenderos",
                    ),
                ),
                (
                    "IF_relevamiento_territorial",
                    models.CharField(
                        max_length=255, verbose_name="IF de relevamiento territorial"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("Para revision", "Para revisión"),
                            ("Validado", "Validado"),
                            ("A subsanar", "A subsanar"),
                        ],
                        default="Para revision",
                        max_length=20,
                        verbose_name="Estado del Informe",
                    ),
                ),
                (
                    "admision",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="admisiones.admision",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="informetecnicojuridico",
            name="admision",
        ),
        migrations.DeleteModel(
            name="InformeTecnicoBase",
        ),
        migrations.DeleteModel(
            name="InformeTecnicoJuridico",
        ),
    ]
