# Generated by Django 4.2.20 on 2025-06-15 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0020_alter_informetecnico_expediente_nro_anexo"),
    ]

    operations = [
        migrations.AddField(
            model_name="anexo",
            name="domicilio",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Domicilio"
            ),
        ),
        migrations.AddField(
            model_name="anexo",
            name="efector",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Efector (nombre)"
            ),
        ),
        migrations.AddField(
            model_name="anexo",
            name="expediente",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Expediente"
            ),
        ),
        migrations.AddField(
            model_name="anexo",
            name="mail",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Correo Electrónico"
            ),
        ),
        migrations.AddField(
            model_name="anexo",
            name="plazo_ejecucion",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Plazo de Ejecución"
            ),
        ),
        migrations.AddField(
            model_name="anexo",
            name="responsable_apellido",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Apellido"
            ),
        ),
        migrations.AddField(
            model_name="anexo",
            name="responsable_cuit",
            field=models.BigIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(10000000000),
                    django.core.validators.MaxValueValidator(99999999999),
                ],
                verbose_name="CUIT / CUIL",
            ),
        ),
        migrations.AddField(
            model_name="anexo",
            name="responsable_domicilio",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Domicilio"
            ),
        ),
        migrations.AddField(
            model_name="anexo",
            name="responsable_mail",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Correo Electrónico"
            ),
        ),
        migrations.AddField(
            model_name="anexo",
            name="responsable_nombre",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Nombre"
            ),
        ),
        migrations.AddField(
            model_name="anexo",
            name="tipo_espacio",
            field=models.CharField(
                blank=True,
                choices=[("Comedor", "Comedor"), ("Merendero", "Merendero")],
                max_length=50,
                null=True,
                verbose_name="Tipo (Comedor / Merendero)",
            ),
        ),
        migrations.AddField(
            model_name="anexo",
            name="total_acreditaciones",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Total de acreditaciones a Producir",
            ),
        ),
    ]
