# Generated by Django 4.2.20 on 2025-10-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0021_alter_admision_estado_legales"),
    ]

    operations = [
        migrations.AddField(
            model_name="admision",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("incorporacion", "Incorporación"),
                    ("renovacion", "Renovación"),
                ],
                max_length=20,
                null=True,
                verbose_name="Tipo de Admisión",
            ),
        ),
    ]
