# Generated by Django 4.2.20 on 2025-06-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0021_anexo_domicilio_anexo_efector_anexo_expediente_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anexo",
            name="tipo_espacio",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Comedor", "Comedor"),
                    ("Merendero", "Merendero"),
                    ("Comedor y Merendero", "Comedor y Merendero"),
                ],
                max_length=50,
                null=True,
                verbose_name="Tipo (Comedor / Merendero)",
            ),
        ),
        migrations.AlterField(
            model_name="informetecnico",
            name="tipo_espacio",
            field=models.CharField(
                choices=[
                    ("Comedor", "Comedor"),
                    ("Merendero", "Merendero"),
                    ("Comedor y Merendero", "Comedor y Merendero"),
                ],
                max_length=50,
                verbose_name="Tipo de Espacio Comunitario",
            ),
        ),
    ]
