# Generated by Django 4.2.20 on 2025-06-15 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0022_alter_anexo_tipo_espacio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObservacionGeneralInforme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField()),
                (
                    "informe",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admisiones.informetecnico",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampoASubsanar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campo", models.CharField(max_length=100)),
                (
                    "informe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admisiones.informetecnico",
                    ),
                ),
            ],
        ),
    ]
