# Generated by Django 4.2.20 on 2025-10-12 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0022_admision_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="informetecnico",
            name="monto_1",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="informetecnico",
            name="monto_2",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="informetecnico",
            name="monto_3",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="informetecnico",
            name="monto_4",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="informetecnico",
            name="monto_5",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="informetecnico",
            name="monto_6",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="informetecnico",
            name="resolucion_de_pago_1",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Resolución de pago 1",
            ),
        ),
        migrations.AddField(
            model_name="informetecnico",
            name="resolucion_de_pago_2",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Resolución de pago 2",
            ),
        ),
        migrations.AddField(
            model_name="informetecnico",
            name="resolucion_de_pago_3",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Resolución de pago 3",
            ),
        ),
        migrations.AddField(
            model_name="informetecnico",
            name="resolucion_de_pago_4",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Resolución de pago 4",
            ),
        ),
        migrations.AddField(
            model_name="informetecnico",
            name="resolucion_de_pago_5",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Resolución de pago 5",
            ),
        ),
        migrations.AddField(
            model_name="informetecnico",
            name="resolucion_de_pago_6",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                verbose_name="Resolución de pago 6",
            ),
        ),
    ]
