# Generated by Django 4.2.20 on 2025-06-16 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admisiones", "0023_observaciongeneralinforme_campoasubsanar"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormularioProyectoDisposicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("incorporacion", "Incorporación"),
                            ("renovacion", "Renovación"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "archivo",
                    models.FileField(null=True, upload_to="formularios_disposicion/"),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "admision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proyecto_disposicion",
                        to="admisiones.admision",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="formularioproyectodeconvenio",
            name="pregunta1",
        ),
        migrations.RemoveField(
            model_name="formularioproyectodeconvenio",
            name="pregunta2",
        ),
        migrations.RemoveField(
            model_name="formularioproyectodeconvenio",
            name="pregunta3",
        ),
        migrations.AddField(
            model_name="formularioproyectodeconvenio",
            name="archivo",
            field=models.FileField(null=True, upload_to="formularios_convenio/"),
        ),
        migrations.AlterField(
            model_name="formularioproyectodeconvenio",
            name="admision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="proyecto_convenio",
                to="admisiones.admision",
            ),
        ),
        migrations.DeleteModel(
            name="FormularioRESO",
        ),
    ]
