# Generated by Django 4.2.20 on 2025-10-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0023_informetecnico_monto_1_informetecnico_monto_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="informetecnico",
            name="responsable_tarjeta_cuit",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="CUIL/CUIT del Responsable de la Tarjeta",
            ),
        ),
    ]
