# Generated by Django 4.2.20 on 2025-06-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0024_formularioproyectodisposicion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivoadmision",
            name="archivo",
            field=models.FileField(
                blank=True, null=True, upload_to="admisiones/admisiones_archivos/"
            ),
        ),
        migrations.AlterField(
            model_name="documentosexpediente",
            name="archivo",
            field=models.FileField(
                blank=True, null=True, upload_to="admisiones/expediente"
            ),
        ),
        migrations.AlterField(
            model_name="formularioproyectodeconvenio",
            name="archivo",
            field=models.FileField(
                null=True, upload_to="admisiones/formularios_convenio/"
            ),
        ),
        migrations.AlterField(
            model_name="formularioproyectodisposicion",
            name="archivo",
            field=models.FileField(
                null=True, upload_to="admisiones/formularios_disposicion/"
            ),
        ),
        migrations.AlterField(
            model_name="informetecnicopdf",
            name="archivo",
            field=models.FileField(upload_to="admisiones/informes_tecnicos/"),
        ),
    ]
