# Generated by Django 4.2.20 on 2025-10-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0024_informetecnico_responsable_tarjeta_cuit"),
    ]

    operations = [
        migrations.AddField(
            model_name="informetecnico",
            name="domicilio_electronico_espacio",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Domicilio electronico constituido del Comedor/Merendero",
            ),
        ),
        migrations.AlterField(
            model_name="informetecnico",
            name="tipo_espacio",
            field=models.CharField(
                choices=[
                    ("Comedor", "Comedor"),
                    ("Merendero", "Merendero"),
                    ("Punto de Entrega", "Punto de Entrega"),
                    ("Comedor y Merendero", "Comedor y Merendero"),
                ],
                max_length=50,
                verbose_name="Tipo de Espacio Comunitario",
            ),
        ),
    ]
