# Generated by Django 4.2.20 on 2025-10-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0026_archivoadmision_motivo_descarte_expediente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archivoadmision",
            name="motivo_descarte_expediente",
        ),
        migrations.AddField(
            model_name="admision",
            name="motivo_descarte_expediente",
            field=models.TextField(
                blank=True, null=True, verbose_name="Motivo de descarte del Expediente"
            ),
        ),
    ]
