# Generated by Django 4.2.20 on 2025-10-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admisiones",
            "0027_remove_archivoadmision_motivo_descarte_expediente_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="admision",
            name="fecha_descarte_expediente",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de descarte del Expediente"
            ),
        ),
        migrations.AlterField(
            model_name="admision",
            name="estado_legales",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Enviado a Legales", "Enviado a Legales"),
                    ("A Rectificar", "A Rectificar"),
                    ("Rectificado", "Rectificado"),
                    ("Pendiente de Validacion", "Pendiente de Validacion"),
                    ("Expediente Agregado", "Expediente Agregado"),
                    ("Formulario Convenio Creado", "Formulario Convenio Creado"),
                    ("IF Convenio Asignado", "IF Convenio Asignado"),
                    ("Formulario Disposición Creado", "Formulario Disposición Creado"),
                    ("IF Disposición Asignado", "IF Disposición Asignado"),
                    ("Juridicos: Validado", "Juridicos: Validado"),
                    ("Juridicos: Rechazado", "Juridicos: Rechazado"),
                    ("Informe SGA Generado", "Informe SGA Generado"),
                    ("Convenio Firmado", "Convenio Firmado"),
                    ("Acompañamiento Pendiente", "Acompañamiento Pendiente"),
                    ("Archivado", "Archivado"),
                    (
                        "Informe Complementario Solicitado",
                        "Informe Complementario Solicitado",
                    ),
                    (
                        "Informe Complementario Enviado",
                        "Informe Complementario Enviado",
                    ),
                    (
                        "Informe Complementario: Validado",
                        "Informe Complementario: Validado",
                    ),
                    ("Finalizado", "Finalizado"),
                    ("Descartado", "Descartado"),
                ],
                max_length=40,
                null=True,
                verbose_name="Estado",
            ),
        ),
    ]
