# Generated by Django 4.2.20 on 2025-10-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0028_admision_fecha_descarte_expediente_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="informetecnico",
            name="responsable_admin_apellido",
        ),
        migrations.RemoveField(
            model_name="informetecnico",
            name="responsable_admin_cuit",
        ),
        migrations.RemoveField(
            model_name="informetecnico",
            name="responsable_admin_domicilio",
        ),
        migrations.RemoveField(
            model_name="informetecnico",
            name="responsable_admin_mail",
        ),
        migrations.RemoveField(
            model_name="informetecnico",
            name="responsable_admin_nombre",
        ),
    ]
