# Generated by Django 4.2.20 on 2025-11-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0031_alter_admision_numero_if_tecnico"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivoadmision",
            name="orden",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
