# Generated by Django 4.2.20 on 2025-11-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0032_archivoadmision_orden"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archivoadmision",
            name="orden",
        ),
        migrations.AddField(
            model_name="documentacion",
            name="orden",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
