# Generated by Django 4.2.20 on 2025-11-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0034_admision_estado_admision"),
    ]

    operations = [
        migrations.AddField(
            model_name="admision",
            name="activa",
            field=models.BooleanField(default=True, verbose_name="¿Activa?"),
        ),
    ]
