# Generated by Django 4.2.20 on 2026-01-04 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admisiones", "0043_alter_admision_estado_legales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informetecnico",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admisiones_informes_tecnicos_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="informetecnico",
            name="modificado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admisiones_informes_tecnicos_modificados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
