# Generated by Django 4.2.20 on 2025-10-24 00:00

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0045_update_documentacion_aval_labels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informetecnico",
            name="monto_1",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(Decimal("99000000.00")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="informetecnico",
            name="monto_2",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(Decimal("99000000.00")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="informetecnico",
            name="monto_3",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(Decimal("99000000.00")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="informetecnico",
            name="monto_4",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(Decimal("99000000.00")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="informetecnico",
            name="monto_5",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(Decimal("99000000.00")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="informetecnico",
            name="monto_6",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(Decimal("99000000.00")),
                ],
            ),
        ),
    ]
