# Generated by Django 4.2.20 on 2026-01-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0047_informetecnico_no_corresponde_fecha_vencimiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="admision",
            name="convenio_numero",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
