# Generated by Django 4.2.27 on 2026-01-20 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0048_make_validacion_registro_nacional_optional"),
        ("admisiones", "0050_backfill_informetecnico_ultimo_convenio"),
    ]

    operations = []
