# Generated by Django 4.2.27 on 2026-02-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0053_alter_admision_estado_admision"),
    ]

    operations = [
        migrations.AddField(
            model_name="admision",
            name="archivo_informe_tecnico_GDE",
            field=models.FileField(
                blank=True, null=True, upload_to="admisiones/informe_tecnico_GDE/"
            ),
        ),
    ]
