# Generated by Django 4.2.27 on 2026-02-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0055_update_docx_editado_display_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="informetecnico",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Iniciado", "Iniciado"),
                    ("Para revision", "Para revisión"),
                    ("Docx generado", "DOCX generado"),
                    ("Docx editado", "DOCX enviado a validar"),
                    ("Validado", "Validado"),
                    ("A subsanar", "A subsanar"),
                ],
                max_length=20,
                verbose_name="Estado del Informe",
            ),
        ),
    ]
