# Generated by Django 4.2.27 on 2026-04-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0057_alter_archivoadmision_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admision",
            name="estado_admision",
            field=models.CharField(
                choices=[
                    ("iniciada", "Iniciada"),
                    ("convenio_seleccionado", "Convenio seleccionado"),
                    ("documentacion_en_proceso", "Documentaci\u00f3n en proceso"),
                    ("documentacion_finalizada", "Documentaci\u00f3n cargada"),
                    ("documentacion_aprobada", "Documentaci\u00f3n aprobada"),
                    (
                        "documentacion_carga_finalizada",
                        "Carga de documentaci\u00f3n finalizada",
                    ),
                    ("expediente_cargado", "Expediente cargado"),
                    ("informe_tecnico_en_proceso", "Informe t\u00e9cnico en proceso"),
                    ("informe_tecnico_finalizado", "Informe t\u00e9cnico finalizado"),
                    (
                        "informe_tecnico_docx_editado",
                        "Informe t\u00e9cnico DOCX enviado a validar",
                    ),
                    ("informe_tecnico_en_revision", "Informe t\u00e9cnico en revisi\u00f3n"),
                    (
                        "informe_tecnico_en_subsanacion",
                        "Informe t\u00e9cnico en subsanaci\u00f3n",
                    ),
                    ("informe_tecnico_aprobado", "Informe t\u00e9cnico aprobado"),
                    ("if_informe_tecnico_cargado", "IF Informe t\u00e9cnico cargado"),
                    ("enviado_a_legales", "Enviado a legales"),
                    ("enviado_a_acompaniamiento", "Enviado a acompa\u00f1amiento"),
                    ("inactivada", "Inactivada"),
                    ("descartado", "Descartado"),
                ],
                default="iniciada",
                max_length=40,
                verbose_name="Estado de Admisi\u00f3n",
            ),
        ),
    ]
