# Generated by Django 4.2.27 on 2026-06-01 15:10

from django.db import migrations, models
import django.db.models.deletion


def backfill_origen(apps, schema_editor):
    """Backfill best-effort de ``archivo_organizacion_origen``.

    Al materializar, ``congelar_documentacion_organizacional`` copia
    ``archivo=archivo_org.archivo.name``, por lo que el nombre de archivo del
    ``ArchivoAdmision`` materializado coincide EXACTAMENTE con el del
    ``ArchivoOrganizacion`` de origen dentro de la misma organizacion. Usamos
    esa coincidencia como clave de join. Si hay 0 o >1 coincidencias no se
    setea (se evita asociar de forma ambigua).
    """

    ArchivoAdmision = apps.get_model("admisiones", "ArchivoAdmision")
    ArchivoOrganizacion = apps.get_model("organizaciones", "ArchivoOrganizacion")
    db_alias = schema_editor.connection.alias

    candidatos = (
        ArchivoAdmision.objects.using(db_alias)
        .filter(archivo_organizacion_origen__isnull=True)
        .exclude(archivo="")
        .exclude(archivo__isnull=True)
        .select_related("admision__comedor")
    )

    # Cache por organizacion para evitar N+1 contra ArchivoOrganizacion.
    archivos_org_por_organizacion = {}

    for archivo_adm in candidatos.iterator(chunk_size=500):
        admision = archivo_adm.admision
        comedor = getattr(admision, "comedor", None) if admision else None
        organizacion_id = getattr(comedor, "organizacion_id", None)
        if not organizacion_id:
            continue

        cache_org = archivos_org_por_organizacion.get(organizacion_id)
        if cache_org is None:
            cache_org = {}
            for archivo_name, archivo_id in (
                ArchivoOrganizacion.objects.using(db_alias)
                .filter(organizacion_id=organizacion_id)
                .values_list("archivo", "id")
            ):
                ids = cache_org.setdefault(archivo_name, [])
                if len(ids) < 2:
                    ids.append(archivo_id)
            archivos_org_por_organizacion[organizacion_id] = cache_org

        matches = cache_org.get(archivo_adm.archivo.name, [])
        if len(matches) == 1:
            archivo_adm.archivo_organizacion_origen_id = matches[0]
            archivo_adm.save(
                using=db_alias, update_fields=["archivo_organizacion_origen"]
            )

class Migration(migrations.Migration):

    dependencies = [
        (
            "organizaciones",
            "0012_documentacion_organizacion_squashed_0013_archivoorganizacion_numero_gde",
        ),
        ("admisiones", "0060_numero_gde_organizacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivoadmision",
            name="archivo_organizacion_origen",
            field=models.ForeignKey(
                blank=True,
                help_text="Si el documento fue materializado desde el legajo de la organizacion, referencia al ArchivoOrganizacion de origen. Permite replicar el GDE y detectar cambios sin depender del matching por nombre.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archivos_admision_materializados",
                to="organizaciones.archivoorganizacion",
                verbose_name="Archivo de organizacion de origen",
            ),
        ),
        migrations.RunPython(backfill_origen, migrations.RunPython.noop),
    ]
