# Generated by Django 4.2.27 on 2026-06-01 15:10

from django.db import migrations, models
import django.db.models.deletion


def backfill_origen(apps, schema_editor):
    """Backfill best-effort de ``archivo_organizacion_origen``.

    Al materializar, ``congelar_documentacion_organizacional`` copia
    ``archivo=archivo_org.archivo.name``, por lo que el nombre de archivo del
    ``ArchivoAdmision`` materializado coincide EXACTAMENTE con el del
    ``ArchivoOrganizacion`` de origen dentro de la misma organizacion. Usamos
    esa coincidencia como clave de join. Si hay 0 o >1 coincidencias no se
    setea (se evita asociar de forma ambigua).
    """

    ArchivoAdmision = apps.get_model("admisiones", "ArchivoAdmision")
    ArchivoOrganizacion = apps.get_model("organizaciones", "ArchivoOrganizacion")

    candidatos = (
        ArchivoAdmision.objects.filter(archivo_organizacion_origen__isnull=True)
        .exclude(archivo="")
        .exclude(archivo__isnull=True)
        .select_related("admision__comedor")
    )
    for archivo_adm in candidatos.iterator(chunk_size=500):
        admision = archivo_adm.admision
        comedor = getattr(admision, "comedor", None) if admision else None
        organizacion_id = getattr(comedor, "organizacion_id", None)
        if not organizacion_id:
            continue
        matches = list(
            ArchivoOrganizacion.objects.filter(
                organizacion_id=organizacion_id,
                archivo=archivo_adm.archivo.name,
            ).values_list("id", flat=True)[:2]
        )
        if len(matches) == 1:
            archivo_adm.archivo_organizacion_origen_id = matches[0]
            archivo_adm.save(update_fields=["archivo_organizacion_origen"])


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizaciones",
            "0012_documentacion_organizacion_squashed_0013_archivoorganizacion_numero_gde",
        ),
        ("admisiones", "0060_numero_gde_organizacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivoadmision",
            name="archivo_organizacion_origen",
            field=models.ForeignKey(
                blank=True,
                help_text="Si el documento fue materializado desde el legajo de la organizacion, referencia al ArchivoOrganizacion de origen. Permite replicar el GDE y detectar cambios sin depender del matching por nombre.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="archivos_admision_materializados",
                to="organizaciones.archivoorganizacion",
                verbose_name="Archivo de organizacion de origen",
            ),
        ),
        migrations.RunPython(backfill_origen, migrations.RunPython.noop),
    ]
