# Generated by Django 4.2.27 on 2026-06-01 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0062_backfill_gde_a_organizacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmisionDocOrgSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slot_key", models.CharField(max_length=64)),
                ("etiqueta", models.CharField(blank=True, max_length=255, null=True)),
                ("token", models.CharField(max_length=255)),
                ("synced_at", models.DateTimeField(auto_now=True)),
                (
                    "admision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots_doc_org",
                        to="admisiones.admision",
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot de documentacion organizacional por admision",
                "verbose_name_plural": "Snapshots de documentacion organizacional por admision",
            },
        ),
        migrations.AddConstraint(
            model_name="admisiondocorgsnapshot",
            constraint=models.UniqueConstraint(
                fields=("admision", "slot_key"), name="unq_snapshot_doc_org"
            ),
        ),
    ]
