# Generated by Django 4.2.27 on 2026-07-31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admisiones", "0068_admision_vigente_pwa_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="admision",
            name="es_ex_pnud",
            field=models.CharField(
                blank=True,
                choices=[("si", "Sí"), ("no", "No")],
                max_length=2,
                null=True,
                verbose_name="¿Es Ex PNUD?",
            ),
        ),
        migrations.AddField(
            model_name="admision",
            name="estado_convenio_pnud",
            field=models.CharField(
                blank=True,
                choices=[("vigente", "Vigente"), ("finalizado", "Finalizado")],
                max_length=12,
                null=True,
                verbose_name="Estado del convenio PNUD",
            ),
        ),
        migrations.AddField(
            model_name="admision",
            name="estado_financiamiento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vigente", "Financiamiento vigente"),
                    ("finalizado", "Financiamiento finalizado"),
                ],
                max_length=12,
                null=True,
                verbose_name="Estado del financiamiento",
            ),
        ),
        migrations.AddField(
            model_name="admision",
            name="tipo_renovacion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("primera", "Primera renovación"),
                    ("segunda_o_posterior", "Segunda renovación o posterior"),
                ],
                max_length=22,
                null=True,
                verbose_name="Renovación que tramita",
            ),
        ),
    ]
