# Generated by Django 4.2.27 on 2026-07-31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


GESTOR_TEMPLATES_GROUP = "Gestor de templates"
GESTOR_TEMPLATES_PERMISSION = "gestionar_templates_informe_tecnico"


def crear_rol_gestor_templates(apps, schema_editor):
    content_type_model = apps.get_model("contenttypes", "ContentType")
    permission_model = apps.get_model("auth", "Permission")
    group_model = apps.get_model("auth", "Group")
    content_type, _ = content_type_model.objects.get_or_create(
        app_label="admisiones",
        model="plantillainformetecnico",
    )
    permission, _ = permission_model.objects.get_or_create(
        content_type=content_type,
        codename=GESTOR_TEMPLATES_PERMISSION,
        defaults={"name": "Puede gestionar templates de Informes Técnicos"},
    )
    group, _ = group_model.objects.get_or_create(name=GESTOR_TEMPLATES_GROUP)
    group.permissions.add(permission)


def desasignar_rol_gestor_templates(apps, schema_editor):
    permission_model = apps.get_model("auth", "Permission")
    group_model = apps.get_model("auth", "Group")
    permission = permission_model.objects.filter(
        content_type__app_label="admisiones",
        codename=GESTOR_TEMPLATES_PERMISSION,
    ).first()
    group = group_model.objects.filter(name=GESTOR_TEMPLATES_GROUP).first()
    if permission and group:
        group.permissions.remove(permission)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admisiones", "0069_admision_es_ex_pnud_admision_estado_convenio_pnud_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlantillaInformeTecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "tipo_admision",
                    models.CharField(
                        choices=[
                            ("incorporacion", "Incorporación"),
                            ("renovacion", "Renovación"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "es_ex_pnud",
                    models.CharField(
                        blank=True,
                        choices=[("si", "Sí"), ("no", "No")],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "estado_convenio_pnud",
                    models.CharField(
                        blank=True,
                        choices=[("vigente", "Vigente"), ("finalizado", "Finalizado")],
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "tipo_renovacion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("primera", "Primera renovación"),
                            ("segunda_o_posterior", "Segunda renovación o posterior"),
                        ],
                        max_length=22,
                        null=True,
                    ),
                ),
                (
                    "estado_financiamiento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("vigente", "Financiamiento vigente"),
                            ("finalizado", "Financiamiento finalizado"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activa", "Activa"),
                            ("inactiva", "Inactiva"),
                            ("eliminada", "Eliminada lógicamente"),
                        ],
                        default="activa",
                        max_length=12,
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("modificado", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plantillas_informe_tecnico_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plantillas_informe_tecnico_modificadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tipo_convenio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="admisiones.tipoconvenio",
                    ),
                ),
            ],
            options={
                "verbose_name": "plantilla de Informe Técnico",
                "verbose_name_plural": "plantillas de Informes Técnicos",
                "permissions": [
                    (
                        "gestionar_templates_informe_tecnico",
                        "Puede gestionar templates de Informes Técnicos",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlantillaInformeTecnicoVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("contenido_html", models.TextField(blank=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("publicada", "Publicada"),
                            ("inactiva", "Inactiva"),
                            ("eliminada", "Eliminada lógicamente"),
                        ],
                        default="borrador",
                        max_length=12,
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("modificado", models.DateTimeField(auto_now=True)),
                ("publicado", models.DateTimeField(blank=True, null=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versiones_plantilla_informe_tecnico_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plantilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versiones",
                        to="admisiones.plantillainformetecnico",
                    ),
                ),
                (
                    "publicado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versiones_plantilla_informe_tecnico_publicadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "versión de plantilla de Informe Técnico",
                "verbose_name_plural": "versiones de plantillas de Informes Técnicos",
                "ordering": ["-numero"],
            },
        ),
        migrations.CreateModel(
            name="PlantillaInformeTecnicoPublicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave_condiciones", models.CharField(max_length=255, unique=True)),
                ("publicada", models.DateTimeField(auto_now_add=True)),
                (
                    "plantilla",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publicacion_vigente",
                        to="admisiones.plantillainformetecnico",
                    ),
                ),
                (
                    "publicada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publicaciones_plantilla_informe_tecnico",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publicacion",
                        to="admisiones.plantillainformetecnicoversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "publicación de plantilla de Informe Técnico",
                "verbose_name_plural": "publicaciones de plantillas de Informes Técnicos",
            },
        ),
        migrations.AddIndex(
            model_name="plantillainformetecnicoversion",
            index=models.Index(
                fields=["plantilla", "estado"],
                name="admisiones__plantil_bbbfa1_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="plantillainformetecnicoversion",
            constraint=models.UniqueConstraint(
                fields=("plantilla", "numero"),
                name="unq_plantilla_informe_tecnico_version",
            ),
        ),
        migrations.AddIndex(
            model_name="plantillainformetecnico",
            index=models.Index(
                fields=["tipo_admision", "tipo_convenio", "estado"],
                name="admisiones__tipo_ad_c55900_idx",
            ),
        ),
        migrations.RunPython(
            crear_rol_gestor_templates,
            desasignar_rol_gestor_templates,
        ),
    ]
