# Generated by Django 4.2.27 on 2026-07-31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0070_plantillainformetecnico_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="informetecnicopdf",
            name="plantilla_informe_tecnico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_generados",
                to="admisiones.plantillainformetecnico",
            ),
        ),
        migrations.AddField(
            model_name="informetecnicopdf",
            name="version_plantilla_informe_tecnico",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_generados",
                to="admisiones.plantillainformetecnicoversion",
            ),
        ),
    ]
