# Generated by Django 4.2.27 on 2026-07-31

from django.db import migrations, models


DIAS = (
    ("lunes", "Lunes"),
    ("martes", "Martes"),
    ("miercoles", "Miércoles"),
    ("jueves", "Jueves"),
    ("viernes", "Viernes"),
    ("sabado", "Sábado"),
    ("domingo", "Domingo"),
)
PRESTACIONES = (
    ("desayuno", "Desayunos"),
    ("almuerzo", "Almuerzos"),
    ("merienda", "Meriendas"),
    ("cena", "Cenas"),
)


def catalogo_inicial():
    """Las 106 expresiones que usan los cuatro templates DOCX vigentes."""

    variables = []
    for prestacion, etiqueta_prestacion in PRESTACIONES:
        for dia, etiqueta_dia in DIAS:
            variables.append(
                (
                    f"informe.aprobadas_{prestacion}_{dia}",
                    f"{etiqueta_prestacion} aprobados - {etiqueta_dia}",
                    "Prestaciones aprobadas",
                )
            )
    for prestacion, etiqueta_prestacion in PRESTACIONES:
        for dia, etiqueta_dia in DIAS:
            variables.append(
                (
                    f"informe.aprobadas_ultimo_convenio_{prestacion}_{dia}",
                    f"{etiqueta_prestacion} aprobados último convenio - {etiqueta_dia}",
                    "Prestaciones aprobadas - último convenio",
                )
            )
    for numero in range(1, 7):
        variables.extend(
            (
                (
                    f"informe.resolucion_de_pago_{numero}",
                    f"Resolución de pago {numero}",
                    "Resoluciones de pago",
                ),
                (
                    f"informe.monto_{numero}",
                    f"Monto de pago {numero}",
                    "Resoluciones de pago",
                ),
            )
        )
    variables.extend(
        (
            (
                "informe.IF_relevamiento_territorial",
                "Informe de relevamiento territorial",
                "Información complementaria",
            ),
            (
                "informe.admision.comedor.organizacion.subtipo_entidad",
                "Subtipo de entidad de la organización",
                "Organización",
            ),
            ("informe.barrio_espacio", "Barrio del espacio", "Espacio"),
            ("informe.conclusiones", "Conclusiones", "Información complementaria"),
            (
                "informe.constancia_subsidios_dnsa",
                "Constancia de subsidios DNSA",
                "Información complementaria",
            ),
            (
                "informe.constancia_subsidios_pnud",
                "Constancia de subsidios PNUD",
                "Información complementaria",
            ),
            ("informe.cuit_organizacion", "CUIT de la organización", "Organización"),
            ("informe.domicilio_espacio", "Domicilio del espacio", "Espacio"),
            (
                "informe.domicilio_organizacion",
                "Domicilio de la organización",
                "Organización",
            ),
            (
                "informe.expediente_nro",
                "Número de expediente",
                "Información complementaria",
            ),
            ("informe.localidad_espacio", "Localidad del espacio", "Espacio"),
            (
                "informe.localidad_organizacion",
                "Localidad de la organización",
                "Organización",
            ),
            ("informe.mail_organizacion", "Correo de la organización", "Organización"),
            ("informe.nombre_espacio", "Nombre del espacio", "Espacio"),
            (
                "informe.nombre_organizacion",
                "Nombre de la organización",
                "Organización",
            ),
            (
                "informe.nota_gde_if",
                "Nota GDE IF",
                "Información complementaria",
            ),
            (
                "informe.organizacion_avalista_1",
                "Organización avalista 1",
                "Información complementaria",
            ),
            (
                "informe.organizacion_avalista_2",
                "Organización avalista 2",
                "Información complementaria",
            ),
            ("informe.partido_espacio", "Partido del espacio", "Espacio"),
            (
                "informe.partido_organizacion",
                "Partido de la organización",
                "Organización",
            ),
            ("informe.provincia_espacio", "Provincia del espacio", "Espacio"),
            (
                "informe.provincia_organizacion",
                "Provincia de la organización",
                "Organización",
            ),
            ("informe.representante_cargo", "Cargo del representante", "Representante"),
            ("informe.representante_dni", "DNI del representante", "Representante"),
            (
                "informe.representante_nombre",
                "Nombre del representante",
                "Representante",
            ),
            (
                "informe.responsable_tarjeta_dni",
                "DNI del responsable de tarjeta",
                "Responsable de tarjeta",
            ),
            (
                "informe.responsable_tarjeta_domicilio",
                "Domicilio del responsable de tarjeta",
                "Responsable de tarjeta",
            ),
            (
                "informe.responsable_tarjeta_localidad",
                "Localidad del responsable de tarjeta",
                "Responsable de tarjeta",
            ),
            (
                "informe.responsable_tarjeta_mail",
                "Correo del responsable de tarjeta",
                "Responsable de tarjeta",
            ),
            (
                "informe.responsable_tarjeta_nombre",
                "Nombre del responsable de tarjeta",
                "Responsable de tarjeta",
            ),
            (
                "informe.responsable_tarjeta_provincia",
                "Provincia del responsable de tarjeta",
                "Responsable de tarjeta",
            ),
            (
                "informe.responsable_tarjeta_telefono",
                "Teléfono del responsable de tarjeta",
                "Responsable de tarjeta",
            ),
            (
                "informe.telefono_organizacion",
                "Teléfono de la organización",
                "Organización",
            ),
            ("informe.tipo_espacio", "Tipo de espacio", "Espacio"),
            ("texto_comidas.Almuerzos", "Texto de almuerzos", "Prestaciones"),
            ("texto_comidas.Cenas", "Texto de cenas", "Prestaciones"),
            ("texto_comidas.Desayunos", "Texto de desayunos", "Prestaciones"),
            ("texto_comidas.Meriendas", "Texto de meriendas", "Prestaciones"),
        )
    )
    return variables


def cargar_catalogo_inicial(apps, schema_editor):
    Variable = apps.get_model("admisiones", "VariableTemplateInformeTecnico")
    for orden, (codigo, nombre, categoria) in enumerate(catalogo_inicial(), start=1):
        Variable.objects.get_or_create(
            codigo=codigo,
            defaults={
                "nombre": nombre,
                "categoria": categoria,
                "orden": orden,
                "activo": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0072_incidencias_templates_informe_tecnico"),
    ]

    operations = [
        migrations.CreateModel(
            name="VariableTemplateInformeTecnico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=255, unique=True)),
                ("nombre", models.CharField(max_length=255)),
                ("categoria", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("modificado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "variable de template de Informe Técnico",
                "verbose_name_plural": "variables de templates de Informes Técnicos",
                "ordering": ["categoria", "orden", "nombre", "codigo"],
            },
        ),
        migrations.AddIndex(
            model_name="variabletemplateinformetecnico",
            index=models.Index(
                fields=["activo", "categoria"], name="admisiones__activo_6bb868_idx"
            ),
        ),
        migrations.RunPython(cargar_catalogo_inicial, migrations.RunPython.noop),
    ]
