# Generated by Django 5.2.16 on 2026-09-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admisiones", "0081_issue_2326_ampliar_numero_pv"),
    ]

    operations = [
        migrations.AddField(
            model_name="admision",
            name="num_expediente_borrador",
            field=models.CharField(
                blank=True,
                help_text="Carátula a medio cargar. Guarda el avance sin validar ni ocupar el número real; al finalizar se compila en num_expediente y se limpia.",
                max_length=255,
                null=True,
                verbose_name="Carátula en borrador",
            ),
        ),
    ]
