# Generated by Django 4.2.16 on 2025-01-28 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Grupos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Grupo",
                "verbose_name_plural": "Grupos",
            },
        ),
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rol", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
            },
        ),
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="usuarios/"),
                ),
                (
                    "dni",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("telefono", models.CharField(blank=True, max_length=255, null=True)),
                ("darkmode", models.BooleanField(blank=True, default=True, null=True)),
                ("provincia", models.CharField(blank=True, max_length=255, null=True)),
                ("grupos", models.ManyToManyField(blank=True, to="usuarios.grupos")),
                (
                    "rol",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="usuarios.rol",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "usuarios",
                "permissions": [
                    ("rol_directivo", "Directivo"),
                    ("rol_operativo", "Equipo operativo"),
                    ("rol_consultante", "Consultante"),
                    ("rol_observador", "Observador"),
                    ("rol_tecnico", "Equipo técnico"),
                    ("rol_admin", "Administrador"),
                    ("programa_externo", "Externo"),
                    ("programa_CDIF", "CDIF"),
                    ("programa_CDLE", "CDLE"),
                    ("programa_PDV", "PDV"),
                    ("programa_1000D", "1000D"),
                    ("programa_SL", "SL"),
                    ("programa_MA", "MA"),
                    ("programa_Reporte", "Reporte"),
                    ("programa_Administracion", "Administración"),
                    ("programa_Legajo", "Legajo"),
                    ("programa_Configuracion", "Configuración"),
                    ("programa_Dashboard", "Dashboard"),
                ],
            },
        ),
    ]
