# Generated by Django 4.2.16 on 2025-01-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grupos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grupo", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Grupo",
                "verbose_name_plural": "Grupos",
            },
        ),
        migrations.AddField(
            model_name="usuarios",
            name="grupos",
            field=models.ManyToManyField(blank=True, to="usuarios.grupos"),
        ),
    ]
