# Generated by Django 4.0.2 on 2024-09-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'permissions': [('rol_directivo', 'Directivo'), ('rol_operativo', 'Equipo operativo'), ('rol_consultante', 'Consultante'), ('rol_observador', 'Observador'), ('rol_tecnico', 'Equipo técnico'), ('rol_admin', 'Administrador'), ('programa_externo', 'Externo'), ('programa_CDIF', 'CDIF'), ('programa_CDLE', 'CDLE'), ('programa_PDV', 'PDV'), ('programa_1000D', '1000D'), ('programa_SL', 'SL'), ('programa_MA', 'MA'), ('programa_Reporte', 'Reporte'), ('programa_Administracion', 'Administración'), ('programa_Legajo', 'Legajo'), ('programa_Configuracion', 'Configuración'), ('programa_Dashboard', 'Dashboard')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
