# Generated by Django 4.2.16 on 2025-01-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_grupos_usuarios_grupos"),
    ]

    operations = [
        migrations.RenameField(
            model_name="grupos",
            old_name="grupo",
            new_name="nombre",
        ),
    ]
