# Generated by Django 4.0.2 on 2024-11-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rol_usuarios_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='provincia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
