"""Definiciones compartidas para FormularioCDI."""

from __future__ import annotations

from centrodeinfancia.formulario_cdi_textos import (
    SOBREESCRITURAS_ETIQUETAS_CAMPOS,
    SOBREESCRITURAS_ETIQUETAS_OPCIONES,
    SOBREESCRITURAS_ETIQUETAS_OPCIONES_MULTIPLES,
)


def humanizar_codigo(value: str) -> str:
    """Convierte códigos internos en etiquetas legibles."""
    text = str(value or "").replace("_", " ")
    replacements = {
        "nino": "niño",
        "nina": "niña",
        "ninos": "niños",
        "ninas": "niñas",
        "ano": "año",
        "anos": "años",
        "tecnico": "técnico",
        "dias": "días",
    }
    for source, target in replacements.items():
        text = text.replace(source, target)
    return text.capitalize()


OPCIONES_MESES = [
    ("enero", "Enero"),
    ("febrero", "Febrero"),
    ("marzo", "Marzo"),
    ("abril", "Abril"),
    ("mayo", "Mayo"),
    ("junio", "Junio"),
    ("julio", "Julio"),
    ("agosto", "Agosto"),
    ("septiembre", "Septiembre"),
    ("octubre", "Octubre"),
    ("noviembre", "Noviembre"),
    ("diciembre", "Diciembre"),
]

OPCIONES_DIAS_SEMANA = [
    ("lunes", "Lunes"),
    ("martes", "Martes"),
    ("miercoles", "Miércoles"),
    ("jueves", "Jueves"),
    ("viernes", "Viernes"),
    ("sabado", "Sábado"),
    ("domingo", "Domingo"),
]

OPCIONES_GRUPO_ETARIO_SALAS = [
    ("lactantes", "Lactantes"),
    ("deambuladores", "Deambuladores"),
    ("dos_anos", "Dos años"),
    ("tres_anos", "Tres años"),
    ("cuatro_anos", "Cuatro Años"),
    ("multiedad", "Multiedad"),
]

OPCIONES_GRUPO_ETARIO_DEMANDA = [
    ("lactantes", "Lactantes"),
    ("deambuladores", "Deambuladores"),
    ("un_ano", "Un año"),
    ("dos_anos", "Dos años"),
    ("tres_anos", "Tres años"),
    ("cuatro_anos", "Cuatro años"),
]

OPCIONES_INSTITUCIONES_ARTICULACION = [
    ("servicio_promocion_proteccion_local", "Servicio de promocion y proteccion local"),
    ("servicio_promocion_proteccion_zonal", "Servicio de promocion y proteccion zonal"),
    ("salud_caps_hospital_municipal", "Salud CAPS/Hospital municipal"),
    ("salud_hospital_provincial", "Salud hospital provincial"),
    ("educacion_jardin_maternal", "Educacion jardin maternal"),
    ("educacion_escuela_primaria", "Educacion escuela primaria"),
    ("desarrollo_social_municipal", "Desarrollo social municipal"),
    ("desarrollo_social_provincial", "Desarrollo social provincial"),
    ("justicia_juzgado", "Justicia/Juzgado"),
    ("cultura_juegotecas", "Cultura/Juegotecas"),
    ("cultura_espacios_comunitarios", "Cultura/Espacios comunitarios"),
    ("cultura_iglesias", "Cultura/Iglesias"),
    ("seguridad_policia", "Seguridad/Policia"),
    ("seguridad_social_anses", "Seguridad social/ANSES"),
    ("identidad_renaper", "Identidad/RENAPER"),
]


def _construir_opciones(*values: str) -> list[tuple[str, str]]:
    return [(value, humanizar_codigo(value)) for value in values]


CAMPOS_OPCIONES = {
    "ambito": [
        ("sin_informacion", "Sin información"),
        ("rural", "Rural"),
        ("urbano", "Urbano"),
    ],
    "tipo_jornada": [
        (
            "simple_single_shift",
            "Jornada simple (un solo turno con un único grupo de niños)",
        ),
        (
            "multiple_simple_shifts",
            "Dos o más jornadas simples (dos o más turnos a los que asisten distintos grupos de niños)",
        ),
        (
            "full_double_same_group",
            "Jornada completa/doble (dos o más turnos a los que asiste un mismo grupo de niños)",
        ),
        ("other", "Otra (especificar)"),
    ],
    "oferta_servicios": [
        ("lactantes", "Lactantes"),
        ("deambuladores", "Deambuladores"),
        ("dos_anos", "2 años"),
        ("tres_anos", "3 años"),
        ("cuatro_anos", "4 años"),
        ("multiedad", "Multiedad"),
    ],
    "modalidad_gestion": [
        ("gobierno_nacional", "Gobierno nacional"),
        ("gobierno_provincial", "Gobierno provincial"),
        ("gobierno_municipal", "Gobierno municipal"),
        (
            "gestion_privada",
            "Gestión privada (Organizaciones con fines de lucro)",
        ),
        (
            "gestion_tercer_sector",
            "Gestión Tercer Sector (Organizaciones sin fines de lucro; incluye organizaciones no gubernamentales, organizaciones sociales, movimientos sociales, grupos comunitarios o barriales, etc.)",
        ),
        (
            "cogestion_provincial_municipal",
            "Co-gestión: Gob. Provincial y municipal",
        ),
        (
            "cogestion_ong_provincial_municipal",
            "Co-gestión: ONG/Gob. Provincial/municipal",
        ),
        ("otra", "Otra: especificar"),
    ],
    "modalidad_tenencia": _construir_opciones(
        "propio",
        "alquilado",
        "cedido_gubernamental",
        "cedido_privado",
        "comodato",
        "ocupado_de_hecho",
        "otra",
    ),
    "acceso_energia": _construir_opciones(
        "red_formal",
        "red_informal",
        "generacion_propia_motor",
        "generacion_propia_otros",
        "sin_electricidad",
    ),
    "seguridad_electrica": _construir_opciones(
        "cumple_y_revision_mayor_a_un_ano",
        "cumple_y_revision_anual",
        "cumple_sin_revisiones",
        "cumple_solo_zonas_ninos_sin_revisiones",
        "no_cumple_sin_revisiones",
    ),
    "acceso_agua": _construir_opciones(
        "caneria_dentro_cdi",
        "fuera_cdi_dentro_terreno",
        "fuera_del_terreno",
        "sin_agua",
    ),
    "fuente_agua_segura_consumo": _construir_opciones(
        "red_o_embotellada_segura",
        "pozo_analisis_vigente",
        "pozo_analisis_vencido_o_sin_control",
        "otra_con_proceso_sin_garantia_formal",
        "otra_sin_info_potabilizacion",
    ),
    "eliminacion_excretas": _construir_opciones(
        "red_publica_cloaca",
        "camara_septica_pozo_ciego",
        "solo_pozo_ciego",
        "hoyo_tierra",
        "sin_sistema",
    ),
    "estado_botiquin_primeros_auxilios": _construir_opciones(
        "completo_todas_salas_ok_vigente_fuera_alcance",
        "incompleto_todas_salas_ok_vigente_fuera_alcance",
        "unico_completo_compartido_ok_vigente_fuera_alcance",
        "incompleto_compartido_o_mal_estado_o_vencido",
        "no_tienen_o_al_alcance_ninos",
    ),
    "acceso_internet_personal": _construir_opciones(
        "alta_velocidad_con_acceso_personal",
        "estable_con_acceso_personal",
        "estable_sin_acceso_personal",
        "mala_calidad_con_acceso_personal",
        "sin_servicio",
    ),
    "tiene_espacio_cocina": [
        ("si", "Si"),
        ("no", "No"),
        ("no_sabe_no_responde", "No sabe / No responde"),
    ],
    "combustible_cocinar": _construir_opciones(
        "gas_red",
        "gas_granel_tubo_garrafa",
        "electricidad",
        "lena_o_carbon",
        "no_utiliza",
    ),
    "tiene_espacio_exterior": [
        ("si", "Si"),
        ("no", "No"),
        ("no_responde", "No responde"),
    ],
    "tiene_juegos_exteriores": [
        ("si", "Si"),
        ("no", "No"),
        ("no_responde", "No responde"),
    ],
    "plan_evacuacion_y_simulacros": _construir_opciones(
        "protocolo_escrito_y_2_simulacros_o_mas",
        "protocolo_escrito_y_simulacros_sin_frecuencia",
        "protocolo_escrito_sin_simulacros",
        "practicas_informales_sin_protocolo",
        "sin_protocolo",
    ),
    "cobertura_capacitacion_primeros_auxilios": _construir_opciones(
        "todo_personal_certificado",
        "entre_70_y_99",
        "entre_40_y_69",
        "menos_40",
        "ninguno",
    ),
    "servicio_emergencia_medica": _construir_opciones(
        "servicio_y_cobertura_identificada",
        "servicio_sin_cobertura_identificada",
        "sin_servicio_con_cobertura_identificada",
        "sin_servicio_con_cobertura_parcial",
        "sin_servicio_y_sin_cobertura",
    ),
    "calidad_elaboracion_menu": _construir_opciones(
        "nutricionista_indicaciones_y_frescos",
        "nutricionista_indicaciones_a_veces_sin_frescos",
        "no_siempre_nutricionista_parcial_y_mixto",
        "sin_nutricionista_pocas_indicaciones_procesados",
        "sin_nutricionista_ultraprocesados",
    ),
    "evaluacion_periodica_menu": _construir_opciones(
        "periodica_todas_necesidades_y_patrones_y_personas",
        "periodica_mayoria_necesidades_y_algunos_patrones",
        "ocasional_parcial_y_capacitacion_esporadica",
        "rara_vez_limitada_sin_patrones",
        "no_evalua",
    ),
    "cobertura_capacitacion_manipulacion_alimentos": _construir_opciones(
        "todo_personal_anmat",
        "entre_70_y_99",
        "entre_40_y_60",
        "menos_40",
        "ninguno",
    ),
    "condiciones_almacenamiento_leche_humana": _construir_opciones(
        "heladera_exclusiva_identificada_y_rotulada",
        "heladera_compartida_sector_exclusivo_identificada_y_rotulada",
        "heladera_exclusiva_identificada_sin_fecha",
        "heladera_compartida_sector_exclusivo_identificada_sin_fecha",
        "sin_espacio_exclusivo_ni_identificacion",
    ),
    "acciones_sensibilizacion_lactancia": _construir_opciones(
        "dos_o_mas_anuales_todas_familias",
        "una_anual_todas_familias",
        "una_anual_alcance_limitado",
        "muy_ocasionales_limitadas",
        "ninguna",
    ),
    "tiene_registro_lista_espera": [("si", "Si"), ("no", "No"), ("ns_nc", "NS/NC")],
    "tiene_personal_entrada_salida": [("si", "Si"), ("no", "No"), ("ns_nc", "NS/NC")],
    "frecuencia_comunicacion_familias": _construir_opciones(
        "reuniones_mensuales_y_canales_formales",
        "reuniones_trimestrales_y_canales_formales",
        "reuniones_semestrales_y_algunos_canales",
        "reuniones_anuales_sin_canales",
        "sin_reuniones_ni_canales",
    ),
    "frecuencia_talleres_crianza": _construir_opciones(
        "trimestral_o_mas",
        "cada_4_a_6_meses",
        "una_vez_al_ano",
        "esporadica",
        "no_se_realizan",
    ),
    "realiza_acciones_promocion_acceso_derechos": [
        ("si", "Si"),
        ("no", "No"),
        ("ns_nc", "NS/NC"),
    ],
    "realiza_acciones_acompanamiento_vulneracion_derechos": [
        ("si", "Si"),
        ("no", "No"),
        ("ns_nc", "NS/NC"),
    ],
    "nivel_trabajo_red": _construir_opciones(
        "red_mapeo_mesas_trimestral_o_mas",
        "red_mapeo_mesas_semestral",
        "sin_red_con_mapeo_y_mesas",
        "sin_red_sin_mesas_con_mapeo",
        "sin_red_ni_mapeo",
    ),
    "protocolo_vulneracion_derechos": _construir_opciones(
        "protocolo_revision_periodica_mayoria_conoce",
        "protocolo_revision_periodica_menos_mitad",
        "protocolo_sin_revision_mayoria_conoce",
        "protocolo_sin_revision_menos_mitad",
        "no_existe",
    ),
    "nivel_equipo_tecnico": _construir_opciones(
        "completo_mas_20_horas",
        "perfiles_diversos_15_19_horas",
        "al_menos_un_perfil_o_10_14_horas",
        "limitado_un_perfil_o_9_o_menos",
        "sin_equipo",
    ),
    "frecuencia_registro_desarrollo_nino": _construir_opciones(
        "mensual",
        "trimestral",
        "semestral",
        "anual",
        "no_registra",
    ),
    "frecuencia_registro_informacion_familiar": _construir_opciones(
        "mensual",
        "trimestral",
        "semestral",
        "anual",
        "no_registra",
    ),
    "frecuencia_registro_salud_vacunas": _construir_opciones(
        "mensual",
        "trimestral",
        "semestral",
        "anual",
        "no_registra",
    ),
    "participantes_proyecto_socioeducativo": _construir_opciones(
        "conduccion_sala_equipo_auxiliar_familias_comunidad",
        "conduccion_sala_equipo_familias",
        "conduccion_sala_equipo",
        "conduccion_y_o_equipo",
        "no_tienen",
    ),
    "planificacion_actividades_sala": _construir_opciones(
        "semanal_en_marco_mensual_o_semestral_y_anual",
        "semanal_en_marco_mensual_o_semestral_sin_anual",
        "semanal_en_marco_anual",
        "solo_semanal",
        "no_planifican",
    ),
    "planificacion_integral": _construir_opciones(
        "intereses_caracteristicas_necesidades_e_integralidad",
        "solo_intereses_caracteristicas_necesidades",
        "solo_integralidad",
        "ninguno",
        "no_planifican",
    ),
    "formacion_direccion_primera_infancia": _construir_opciones(
        "titulo_superior_completo_especifico",
        "carrera_75_o_mas_o_posgrados",
        "cursando_formacion_formal",
        "solo_cursos_cortos",
        "sin_formacion",
    ),
    "cobertura_duplas_pedagogicas": _construir_opciones(
        "todas",
        "mayoria",
        "algunas",
        "muy_pocas",
        "ninguna",
    ),
    "cobertura_educadora_titulo_habilitante": _construir_opciones(
        "todas",
        "mayoria",
        "algunas",
        "muy_pocas",
    ),
    "cobertura_formacion_auxiliares": _construir_opciones(
        "todos",
        "mayoria",
        "algunos",
        "muy_pocos",
        "ninguno",
    ),
    "modalidad_contratacion_principal": _construir_opciones(
        "permanente",
        "temporal",
        "beca_o_pasantia",
        "programa_social_insercion",
        "voluntario_u_otra",
    ),
    "frecuencia_reuniones_personal_sala": _construir_opciones(
        "mensual",
        "trimestral",
        "semestral",
        "anual",
        "no_se_realizan",
    ),
    "frecuencia_reuniones_personal_no_docente": _construir_opciones(
        "mensual",
        "trimestral",
        "semestral",
        "anual",
        "no_se_realizan",
    ),
    "frecuencia_reuniones_todo_personal": _construir_opciones(
        "mensual",
        "trimestral",
        "semestral",
        "anual",
        "no_se_realizan",
    ),
    "instancias_capacitacion_todo_personal_ultimos_3_anios": _construir_opciones(
        "seis_o_mas",
        "cuatro_o_cinco",
        "dos_o_tres",
        "una",
        "ninguna",
    ),
    "instancias_capacitacion_personal_sala_ultimos_3_anios": _construir_opciones(
        "seis_o_mas",
        "cuatro_o_cinco",
        "dos_o_tres",
        "una",
        "ninguna",
    ),
    "instancias_capacitacion_equipo_tecnico_ultimos_3_anios": _construir_opciones(
        "seis_o_mas",
        "cuatro_o_cinco",
        "dos_o_tres",
        "una",
        "ninguna",
    ),
    "instancias_capacitacion_personal_cocina_ultimos_3_anios": _construir_opciones(
        "seis_o_mas",
        "cuatro_o_cinco",
        "dos_o_tres",
        "una",
        "ninguna",
        "no_aplica",
    ),
}

CAMPOS_OPCIONES_MULTIPLES = {
    "meses_funcionamiento": OPCIONES_MESES,
    "dias_funcionamiento": OPCIONES_DIAS_SEMANA,
    "items_protocolo_salud": _construir_opciones(
        "emergencias_medicas",
        "suministro_medicamentos",
        "sintomas_enfermedad",
        "reintegro_post_enfermedad",
        "conocido_por_todo_el_personal",
        "no_existe_protocolo_escrito",
    ),
    "prestaciones_alimentarias": _construir_opciones(
        "desayuno",
        "almuerzo",
        "merienda",
        "pre_cena",
        "cena",
        "otra",
        "ninguna",
    ),
}

ETIQUETAS_BOOLEANAS = {
    "uso_exclusivo_espacio": (
        "Si, compartido con otras actividades/personas/organizaciones",
        "No",
    ),
}

ETIQUETAS_CAMPOS = {
    "fecha_relevamiento": "Fecha",
    "nombre_completo_respondente": "Nombre y apellido de quien responde el cuestionario",
    "rol_respondente": "Funcion que cumple",
    "email_respondente": "Mail de contacto",
    "nombre_cdi": "Nombre del Centro de Desarrollo Infantil",
    "codigo_cdi": "Identificador interno del CDI",
    "provincia_cdi": "Provincia del CDI",
    "departamento_cdi": "Departamento del CDI",
    "municipio_cdi": "Municipio del CDI",
    "localidad_cdi": "Localidad del CDI",
    "ambito": "Ámbito",
    "calle_cdi": "Calle del CDI",
    "numero_puerta_cdi": "Numeracion de puerta del CDI",
    "codigo_postal_cdi": "Codigo postal del CDI",
    "latitud_geografica_cdi": "Coordenada geografica latitud",
    "longitud_geografica_cdi": "Coordenada geografica longitud",
    "telefono_cdi": "Teléfono del CDI",
    "email_cdi": "Mail del CDI",
    "nombre_referente_cdi": "Referente del CDI nombre/s",
    "apellido_referente_cdi": "Referente del CDI apellido/s",
    "telefono_referente_cdi": "Referente del CDI telefono",
    "email_referente_cdi": "Referente del CDI mail",
    "meses_funcionamiento": "Meses de funcionamiento del CDI",
    "dias_funcionamiento": "Días de funcionamiento del CDI",
    "tipo_jornada": "Tipo de jornada",
    "tipo_jornada_otra": "Otra jornada - especificar",
    "oferta_servicios": "Oferta de servicios",
    "cantidad_total_ninos": "Cantidad de niños que asisten en total",
    "cantidad_total_personal": "Cantidad de personal en total",
    "modalidad_gestion": "Modalidad de gestion",
    "modalidad_gestion_otra": "Modalidad de gestion - otra",
    "nombre_organizacion_gestora": "Denominacion del organismo u organizacion",
    "cuit_organizacion_gestora": "CUIT del organismo",
    "provincia_organizacion": "Provincia del organismo",
    "departamento_organizacion": "Departamento del organismo",
    "municipio_organizacion": "Municipio del organismo",
    "localidad_organizacion": "Localidad del organismo",
    "calle_organizacion": "Calle",
    "numero_organizacion": "Numeracion",
    "codigo_postal_organizacion": "Codigo postal",
    "edificio_organizacion": "Edificio",
    "piso_organizacion": "Piso",
    "departamento_domicilio_organizacion": "Departamento",
    "oficina_organizacion": "Oficina",
    "telefono_organizacion": "Teléfono",
    "email_organizacion": "Mail",
    "nombre_referente_organizacion": "Referente institucional nombre/s",
    "apellido_referente_organizacion": "Referente institucional apellido/s",
    "telefono_referente_organizacion": "Referente institucional telefono",
    "email_referente_organizacion": "Referente institucional mail",
    "modalidad_tenencia": "Modalidad de tenencia",
    "modalidad_tenencia_otra": "Modalidad de tenencia - otra",
    "uso_exclusivo_espacio": "Uso exclusivo del espacio",
    "cantidad_ambientes_sin_areas_servicio": "Cantidad de ambientes (sin cocina/banos/pasillos/garajes)",
    "acceso_energia": "Acceso a energia",
    "seguridad_electrica": "Seguridad electrica",
    "acceso_agua": "Acceso a agua",
    "fuente_agua_segura_consumo": "Acceso a agua segura para consumo",
    "eliminacion_excretas": "Eliminacion de excretas",
    "tiene_extintores_vigentes": "Existencia de extintores",
    "estado_botiquin_primeros_auxilios": "Existencia de Botiquín",
    "tiene_computadora_funcionando": "Existencia de computadora",
    "acceso_internet_personal": "Acceso a internet",
    "tiene_espacio_cocina": "Espacio de cocina",
    "combustible_cocinar": "Combustible usado para cocinar",
    "tiene_espacio_exterior": "Espacio exterior",
    "tiene_juegos_exteriores": "Juegos infantiles de exterior",
    "plan_evacuacion_y_simulacros": "Plan de evacuacion",
    "cobertura_capacitacion_primeros_auxilios": "Capacitación en primeros auxilios",
    "servicio_emergencia_medica": "Servicio de emergencia medica + cobertura identificada",
    "items_protocolo_salud": "Protocolo de actuación en salud",
    "prestaciones_alimentarias": "Alimentacion",
    "prestaciones_alimentarias_otra": "Otra comida - especificar",
    "calidad_elaboracion_menu": "Elaboracion de alimentos",
    "evaluacion_periodica_menu": "Evaluacion periodica del menu",
    "cobertura_capacitacion_manipulacion_alimentos": "Capacitaciones en manipulación de alimentos",
    "condiciones_almacenamiento_leche_humana": "Condiciones para almacenamiento de leche humana",
    "acciones_sensibilizacion_lactancia": "Acciones de informacion y sensibilizacion de lactancia",
    "tiene_registro_lista_espera": "Existe registro de lista de espera",
    "tiene_instrumento_priorizacion_ingreso": "Existe instrumento de priorización de ingreso de los niños/as",
    "cantidad_ninos_discapacidad": "Cantidad de niños con discapacidad",
    "cantidad_ninos_etnia_especifica": "Cantidad de niños de alguna etnia en particular",
    "tiene_personal_entrada_salida": "Personal encargado para entrada y salida",
    "frecuencia_comunicacion_familias": "Comunicacion con las familias",
    "frecuencia_talleres_crianza": "Talleres de crianza / charlas con profesionales",
    "realiza_acciones_promocion_acceso_derechos": "Acciones de promocion y acceso a derechos",
    "realiza_acciones_acompanamiento_vulneracion_derechos": "Acciones de acompanamiento ante vulneracion de derechos",
    "nivel_trabajo_red": "Trabajo en red",
    "protocolo_vulneracion_derechos": "Protocolo frente a vulneracion de derechos",
    "nivel_equipo_tecnico": "Equipo técnico",
    "frecuencia_registro_desarrollo_nino": "Registro de desarrollo del niño/a",
    "frecuencia_registro_informacion_familiar": "Registro de informacion familiar",
    "frecuencia_registro_salud_vacunas": "Registro de controles de salud y vacunas",
    "participantes_proyecto_socioeducativo": "Proyecto socioeducativo institucional",
    "planificacion_actividades_sala": "Existencia de planificacion de actividades en sala",
    "planificacion_integral": "Planificacion integral",
    "formacion_direccion_primera_infancia": "Formación de la dirección/coordinación en primera infancia",
    "cobertura_duplas_pedagogicas": "Trabajo en duplas en sala",
    "cobertura_educadora_titulo_habilitante": "Formacion habilitante del personal de sala",
    "cobertura_formacion_auxiliares": "Formacion de auxiliares en primera infancia",
    "modalidad_contratacion_principal": "Modalidad de contratacion",
    "frecuencia_reuniones_personal_sala": "Reuniones entre personal de sala, coordinación y/o equipo técnico",
    "frecuencia_reuniones_personal_no_docente": "Reuniones entre personal no docente y coordinación",
    "frecuencia_reuniones_todo_personal": "Reuniones entre todo el personal",
    "instancias_capacitacion_todo_personal_ultimos_3_anios": "Instancias de capacitación para todo el personal en últimos 3 años",
    "instancias_capacitacion_personal_sala_ultimos_3_anios": "Instancias de capacitación para personal de sala en últimos 3 años",
    "instancias_capacitacion_equipo_tecnico_ultimos_3_anios": "Instancias de capacitación para equipo técnico en últimos 3 años",
    "instancias_capacitacion_personal_cocina_ultimos_3_anios": "Instancias de capacitación para cocina/comedor en últimos 3 años",
}

for field_name, label_overrides in SOBREESCRITURAS_ETIQUETAS_OPCIONES.items():
    if field_name in CAMPOS_OPCIONES:
        CAMPOS_OPCIONES[field_name] = [
            (value, label_overrides.get(value, label))
            for value, label in CAMPOS_OPCIONES[field_name]
        ]

for field_name, label_overrides in SOBREESCRITURAS_ETIQUETAS_OPCIONES_MULTIPLES.items():
    if field_name in CAMPOS_OPCIONES_MULTIPLES:
        CAMPOS_OPCIONES_MULTIPLES[field_name] = [
            (value, label_overrides.get(value, label))
            for value, label in CAMPOS_OPCIONES_MULTIPLES[field_name]
        ]

ETIQUETAS_CAMPOS.update(SOBREESCRITURAS_ETIQUETAS_CAMPOS)

SECCIONES_FORMULARIO_CDI = [
    {
        "id": "metadatos",
        "title": "Metadatos del relevamiento",
        "fields": [
            "fecha_relevamiento",
            "nombre_completo_respondente",
            "rol_respondente",
            "email_respondente",
        ],
    },
    {
        "id": "caracterizacion_general",
        "title": "Caracterizacion general",
        "fields": [
            "nombre_cdi",
            "codigo_cdi",
            "ambito",
            "provincia_cdi",
            "departamento_cdi",
            "municipio_cdi",
            "localidad_cdi",
            "calle_cdi",
            "numero_puerta_cdi",
            "codigo_postal_cdi",
            "latitud_geografica_cdi",
            "longitud_geografica_cdi",
            "telefono_cdi",
            "email_cdi",
            "nombre_referente_cdi",
            "apellido_referente_cdi",
            "telefono_referente_cdi",
            "email_referente_cdi",
            "meses_funcionamiento",
            "dias_funcionamiento",
            "tipo_jornada",
            "tipo_jornada_otra",
            "oferta_servicios",
            "cantidad_total_ninos",
            "cantidad_total_personal",
        ],
    },
    {
        "id": "participacion_pfpi",
        "title": "CDI que participan del PFPI",
        "fields": [
            "modalidad_gestion",
            "modalidad_gestion_otra",
            "nombre_organizacion_gestora",
            "cuit_organizacion_gestora",
            "provincia_organizacion",
            "departamento_organizacion",
            "municipio_organizacion",
            "localidad_organizacion",
            "calle_organizacion",
            "numero_organizacion",
            "codigo_postal_organizacion",
            "edificio_organizacion",
            "piso_organizacion",
            "departamento_domicilio_organizacion",
            "oficina_organizacion",
            "telefono_organizacion",
            "email_organizacion",
            "nombre_referente_organizacion",
            "apellido_referente_organizacion",
            "telefono_referente_organizacion",
            "email_referente_organizacion",
            "modalidad_tenencia",
            "modalidad_tenencia_otra",
            "uso_exclusivo_espacio",
            "cantidad_ambientes_sin_areas_servicio",
        ],
    },
    {
        "id": "infraestructura_servicios",
        "title": "Infraestructura y servicios",
        "fields": [
            "acceso_energia",
            "seguridad_electrica",
            "acceso_agua",
            "fuente_agua_segura_consumo",
            "eliminacion_excretas",
            "tiene_extintores_vigentes",
            "estado_botiquin_primeros_auxilios",
            "tiene_computadora_funcionando",
            "acceso_internet_personal",
            "tiene_espacio_cocina",
            "combustible_cocinar",
            "tiene_espacio_exterior",
            "tiene_juegos_exteriores",
            "plan_evacuacion_y_simulacros",
            "cobertura_capacitacion_primeros_auxilios",
            "servicio_emergencia_medica",
            "items_protocolo_salud",
        ],
    },
    {
        "id": "modulo_alimentacion",
        "title": "Alimentacion",
        "fields": [
            "prestaciones_alimentarias",
            "prestaciones_alimentarias_otra",
            "calidad_elaboracion_menu",
            "evaluacion_periodica_menu",
            "cobertura_capacitacion_manipulacion_alimentos",
            "condiciones_almacenamiento_leche_humana",
            "acciones_sensibilizacion_lactancia",
        ],
    },
    {
        "id": "demanda_ingreso_poblacion",
        "title": "Demanda, ingreso y poblacion",
        "fields": [
            "tiene_registro_lista_espera",
            "tiene_instrumento_priorizacion_ingreso",
            "cantidad_ninos_discapacidad",
            "cantidad_ninos_etnia_especifica",
            "tiene_personal_entrada_salida",
        ],
    },
    {
        "id": "familias_derechos",
        "title": "Familias, derechos y articulacion",
        "fields": [
            "frecuencia_comunicacion_familias",
            "frecuencia_talleres_crianza",
            "realiza_acciones_promocion_acceso_derechos",
            "realiza_acciones_acompanamiento_vulneracion_derechos",
        ],
    },
    {
        "id": "trabajo_red_protocolos",
        "title": "Trabajo en red y protocolos",
        "fields": [
            "nivel_trabajo_red",
            "protocolo_vulneracion_derechos",
        ],
    },
    {
        "id": "equipo_tecnico",
        "title": "Equipo técnico",
        "fields": ["nivel_equipo_tecnico"],
    },
    {
        "id": "registros_ninos_proyecto_pedagogico",
        "title": "Registros del niño y proyecto pedagógico",
        "fields": [
            "frecuencia_registro_desarrollo_nino",
            "frecuencia_registro_informacion_familiar",
            "frecuencia_registro_salud_vacunas",
            "participantes_proyecto_socioeducativo",
            "planificacion_actividades_sala",
            "planificacion_integral",
            "formacion_direccion_primera_infancia",
        ],
    },
    {
        "id": "perfil_personal",
        "title": "Perfil y contratacion del personal",
        "fields": [
            "cobertura_duplas_pedagogicas",
            "cobertura_educadora_titulo_habilitante",
            "cobertura_formacion_auxiliares",
            "modalidad_contratacion_principal",
        ],
    },
    {
        "id": "reuniones_capacitaciones",
        "title": "Reuniones y capacitación",
        "fields": [
            "frecuencia_reuniones_personal_sala",
            "frecuencia_reuniones_personal_no_docente",
            "frecuencia_reuniones_todo_personal",
            "instancias_capacitacion_todo_personal_ultimos_3_anios",
            "instancias_capacitacion_personal_sala_ultimos_3_anios",
            "instancias_capacitacion_equipo_tecnico_ultimos_3_anios",
            "instancias_capacitacion_personal_cocina_ultimos_3_anios",
        ],
    },
]

CAMPOS_RESUMEN = [
    "id",
    "fecha_relevamiento",
    "nombre_completo_respondente",
    "created_at",
    "updated_at",
]
