"""Definiciones compartidas para FormularioCDI."""

from __future__ import annotations

SOBREESCRITURAS_ETIQUETAS_OPCIONES = {
    "tipo_jornada": {
        "simple_single_shift": "Jornada simple (un solo turno con un único grupo de niños)",
        "multiple_simple_shifts": "Dos o más jornadas simples (dos o más turnos a los que asisten distintos grupos de niños)",
        "full_double_same_group": "Jornada completa/doble (dos o más turnos a los que asiste un mismo grupo de niños)",
    },
    "modalidad_gestion": {
        "ong": "ONG (incluye organizaciones sociales, movimientos sociales, grupos comunitarios o barriales, etc.)",
        "cogestion_provincial_municipal": "Co-gestión: Gob. Provincial y municipal",
        "cogestion_ong_provincial_municipal": "Co-gestión: ONG/Gob. Provincial/municipal",
    },
    "modalidad_tenencia": {
        "cedido_gubernamental": "Cedido o prestado por ente gubernamental (Municipio / Comuna / Provincia)",
        "cedido_privado": "Cedido o prestado por un privado",
        "comodato": "Comodato",
    },
    "acceso_energia": {
        "generacion_propia_motor": "Por generación propia a motor / grupo electrógeno",
        "generacion_propia_otros": "Por generación propia por otros medios (solar, eólica)",
        "sin_electricidad": "No tiene electricidad",
    },
    "seguridad_electrica": {
        "cumple_y_revision_mayor_a_un_ano": "La instalación eléctrica cumple con normas de seguridad y tiene revisiones con una frecuencia mayor al año",
        "cumple_y_revision_anual": "La instalación eléctrica cumple con normas de seguridad y tiene revisiones periódicas anuales",
        "cumple_sin_revisiones": "La instalación eléctrica cumple con normas de seguridad y no tiene revisiones periódicas",
        "cumple_solo_zonas_ninos_sin_revisiones": "La instalación eléctrica cumple con normas de seguridad únicamente en las zonas donde circulan los niños y no tiene revisiones periódicas",
        "no_cumple_sin_revisiones": "La instalación eléctrica no cumple con normas de seguridad y no tiene revisiones periódicas",
    },
    "acceso_agua": {
        "caneria_dentro_cdi": "Por cañería dentro del CDI",
        "fuera_cdi_dentro_terreno": "Fuera del CDI pero dentro del terreno",
        "sin_agua": "No tiene agua",
    },
    "fuente_agua_segura_consumo": {
        "red_o_embotellada_segura": "Agua de red o embotellada – considerada segura para el consumo.",
        "pozo_analisis_vigente": "Agua de pozo con análisis vigente – con aprobación de laboratorio en los últimos 2 años o potabilizada según métodos recomendados.",
        "pozo_analisis_vencido_o_sin_control": "Agua de pozo con análisis vencido o sin control – con aprobación de laboratorio de más de 2 años o sin análisis disponible.",
        "otra_con_proceso_sin_garantia_formal": "Otra fuente de agua con información parcial – existe algún proceso de potabilización pero sin garantía formal.",
        "otra_sin_info_potabilizacion": "Otra fuente de agua sin información sobre su potabilización – no se puede asegurar que sea apta para consumo.",
    },
    "eliminacion_excretas": {
        "red_publica_cloaca": "A red pública (cloaca)",
        "camara_septica_pozo_ciego": "A cámara séptica y pozo ciego",
        "solo_pozo_ciego": "Sólo a pozo ciego",
        "hoyo_tierra": "A hoyo o excavación en la tierra",
        "sin_sistema": "No tiene sistema de eliminación de excretas",
    },
    "estado_botiquin_primeros_auxilios": {
        "completo_todas_salas_ok_vigente_fuera_alcance": "Cuentan con botiquín completo de primeros auxilios en todas las salas, en buena conservación y con insumos dentro de la fecha de vencimiento; fuera del alcance de los niños",
        "incompleto_todas_salas_ok_vigente_fuera_alcance": "Cuentan con botiquín incompleto de primeros auxilios en todas las salas, en buena conservación y con insumos dentro de la fecha de vencimiento; fuera del alcance de los niños",
        "unico_completo_compartido_ok_vigente_fuera_alcance": "Cuentan con un único botiquín completo de primeros auxilios compartido por las salas, en buena conservación y con insumos dentro de la fecha de vencimiento; fuera del alcance de los niños",
        "incompleto_compartido_o_mal_estado_o_vencido": "Cuentan con botiquín incompleto de primeros auxilios compartido por las salas y/o los insumos se encuentran en mala conservación y fuera de la fecha de vencimiento",
        "no_tienen_o_al_alcance_ninos": "No cuentan con botiquín de primeros auxilios o el botiquín está al alcance de los niños",
    },
    "acceso_internet_personal": {
        "alta_velocidad_con_acceso_personal": "El CDI cuenta con un servicio de internet de alta velocidad al que accede el personal",
        "estable_con_acceso_personal": "El CDI cuenta con un servicio de internet relativamente estable al que accede el personal",
        "estable_sin_acceso_personal": "El CDI cuenta con un servicio de internet relativamente estable al que accede el personal",
        "mala_calidad_con_acceso_personal": "El CDI cuenta con un servicio de internet de mala calidad al que accede el personal",
        "sin_servicio": "El CDI no cuenta con un servicio de internet",
    },
    "combustible_cocinar": {
        "gas_red": "Gas de red",
        "gas_granel_tubo_garrafa": "Gas a granel, tubo o en garrafa",
        "lena_o_carbon": "Leña o carbon",
        "no_utiliza": "No utiliza combustible para cocinar",
    },
    "plan_evacuacion_y_simulacros": {
        "protocolo_escrito_y_2_simulacros_o_mas": "Hay un protocolo de evacuación por escrito y realizan simulacros al menos dos veces por año .",
        "protocolo_escrito_y_simulacros_sin_frecuencia": "Hay un protocolo de evacuación por escrito y se realizan simulacros, aunque no con la frecuencia estipulada.",
        "protocolo_escrito_sin_simulacros": "Hay un protocolo de evacuación por escrito y no se realizan simulacros.",
        "practicas_informales_sin_protocolo": "Solo hay prácticas informales sin protocolos escritos.",
        "sin_protocolo": "No hay protocolo de evacuación.",
    },
    "cobertura_capacitacion_primeros_auxilios": {
        "todo_personal_certificado": "Todo el personal cuenta con capacitaciones en primeros auxilios certificadas (Cruz Roja, Bomberos, otros)",
        "entre_70_y_99": "Del 70% al 99% del personal cuenta con capacitaciones en primeros auxilios certificadas",
        "entre_40_y_69": "Del 40% al 69% del personal cuenta con capacitaciones en primeros auxilios certificadas",
        "menos_40": "Menos del 40% del personal cuenta con capacitaciones en primeros auxilios certificadas",
        "ninguno": "El personal no tiene capacitaciones en primeros auxilios certificadas",
    },
    "servicio_emergencia_medica": {
        "servicio_y_cobertura_identificada": "Tienen servicio de emergencia médica y la cobertura de cada niño está identificada.",
        "servicio_sin_cobertura_identificada": "Tienen servicio de emergencia médica, pero la cobertura de cada niño no está identificada.",
        "sin_servicio_con_cobertura_identificada": "No tienen servicio de emergencia médica, pero sí la cobertura identificada por niño.",
        "sin_servicio_con_cobertura_parcial": "No tienen servicio de emergencia médica y la cobertura está identificada sólo parcialmente.",
        "sin_servicio_y_sin_cobertura": "No tienen servicio de emergencia médica ni la cobertura de cada niño identificada.",
    },
    "calidad_elaboracion_menu": {
        "nutricionista_indicaciones_y_frescos": "El menú es elaborado por nutricionista, respetando indicaciones para la preparación de alimentos e incluyendo alimentos frescos o mínimamente procesados.",
        "nutricionista_indicaciones_a_veces_sin_frescos": "El menú es elaborado por nutricionista, respeta indicaciones, pero a veces no incluye alimentos frescos o mínimamente procesados.",
        "no_siempre_nutricionista_parcial_y_mixto": "El menú no siempre es elaborado por nutricionista; respeta parcialmente las indicaciones y combina alimentos frescos con procesados.",
        "sin_nutricionista_pocas_indicaciones_procesados": "El menú no es elaborado por nutricionista, respeta pocas indicaciones y predominan los alimentos procesados",
        "sin_nutricionista_ultraprocesados": "El menú no es elaborado por nutricionista y utiliza alimentos ultraprocesados",
    },
    "evaluacion_periodica_menu": {
        "periodica_todas_necesidades_y_patrones_y_personas": "El menú se evalúa periódicamente; contempla todas las necesidades nutricionales y patrones alimentarios; el personal está capacitado para su implementación.",
        "periodica_mayoria_necesidades_y_algunos_patrones": "El menú se evalúa periódicamente; contempla la mayoría de las necesidades nutricionales y algunos patrones alimentarios; el personal cuenta con capacitación básica.",
        "ocasional_parcial_y_capacitacion_esporadica": "El menú se evalúa de manera ocasional; contempla parcialmente las necesidades nutricionales y no incluye todos los patrones alimentarios; las capacitaciones al personal son esporádicas.",
        "rara_vez_limitada_sin_patrones": "El menú rara vez se evalúa; contempla de manera limitada las necesidades nutricionales y no considera patrones alimentarios; el personal carece de capacitación específica.",
        "no_evalua": "El menú no se evalúa; no contempla necesidades nutricionales ni patrones alimentarios; el personal no cuenta con capacitación.",
    },
    "cobertura_capacitacion_manipulacion_alimentos": {
        "todo_personal_anmat": "Todo el personal de cocina y comedor tiene capacitaciones y carnet emitido por ANMAT",
        "entre_70_y_99": "Entre el 70% y el 99% del personal tiene capacitaciones y carnet emitido por ANMAT",
        "entre_40_y_60": "Entre el 40% y el 60% del personal tiene capacitaciones y carnet emitido por ANMAT",
        "menos_40": "Menos del 40% del personal tiene capacitaciones y carnet emitido por ANMAT",
        "ninguno": "Ningún integrante del personal tiene capacitaciones ni carnet emitido por ANMAT",
    },
    "condiciones_almacenamiento_leche_humana": {
        "heladera_exclusiva_identificada_y_rotulada": "Se conserva en heladera exclusiva, identificada por niño/a y rotulada con fecha de extracción.",
        "heladera_compartida_sector_exclusivo_identificada_y_rotulada": "Se conserva en heladera compartida, en un sector exclusivo, identificada por niño/a y rotulada con fecha de extracción.",
        "heladera_exclusiva_identificada_sin_fecha": "Se conserva en heladera exclusiva, identificada por niño/a pero sin rotulación con fecha de extracción.",
        "heladera_compartida_sector_exclusivo_identificada_sin_fecha": "Se conserva en heladera compartida, en un sector exclusivo, identificada por niño/a pero sin rotulación con fecha de extracción.",
        "sin_espacio_exclusivo_ni_identificacion": "No se conserva en espacio exclusivo ni se identifica por niño/a.",
    },
    "acciones_sensibilizacion_lactancia": {
        "dos_o_mas_anuales_todas_familias": "Se realizan dos o más acciones anuales con alcance a todas las familias.",
        "una_anual_todas_familias": "Se realiza una acción anual con alcance a todas las familias.",
        "una_anual_alcance_limitado": "Se realizan acciones muy ocasionales y con alcance limitado a las familias.",
        "muy_ocasionales_limitadas": "Se realizan acciones muy ocasionales y con alcance limitado a las familias.",
        "ninguna": "No se realizan acciones de información y sensibilización sobre lactancia.",
    },
    "frecuencia_comunicacion_familias": {
        "reuniones_mensuales_y_canales_formales": "Se realizan reuniones mensuales con las familias y existen canales de comunicación formales (ej. cuaderno, cartelera, mensajes institucionales, plataforma).",
        "reuniones_trimestrales_y_canales_formales": "Se realizan reuniones trimestrales y existen canales formales de comunicación.",
        "reuniones_semestrales_y_algunos_canales": "Se realizan reuniones semestrales y solo algunos canales de comunicación formal funcionan regularmente.",
        "reuniones_anuales_sin_canales": "Se realizan reuniones anuales y no se dispone de canales formales de comunicación.",
        "sin_reuniones_ni_canales": "No se realizan reuniones con familias ni existen canales formales de comunicación.",
    },
    "frecuencia_talleres_crianza": {
        "trimestral_o_mas": "Se realizan al menos cada tres meses",
        "cada_4_a_6_meses": "Se realizan cada cuatro a seis meses",
        "una_vez_al_ano": "Se realiza al menos una vez al año",
        "esporadica": "Se realizan de manera esporádica, no todos los años",
        "no_se_realizan": "No se realizan talleres de crianza ni charlas con profesionales",
    },
    "nivel_trabajo_red": {
        "red_mapeo_mesas_trimestral_o_mas": "Trabaja en red con otras instituciones, cuenta con mapeo de actores y participa en mesas intersectoriales con reuniones trimestrales o más frecuentes.",
        "red_mapeo_mesas_semestral": "Trabaja en red con otras instituciones, cuenta con mapeo de actores y participa en mesas intersectoriales con reuniones semestrales.",
        "sin_red_con_mapeo_y_mesas": "No trabaja en red con otras instituciones, pero cuenta con mapeo de actores y participa en mesas intersectoriales al menos semestralmente.",
        "sin_red_sin_mesas_con_mapeo": "No trabaja en red con otras instituciones, no participa en mesas intersectoriales, pero cuenta con mapeo de actores",
        "sin_red_ni_mapeo": "No trabaja en red con instituciones ni cuenta con mapeo de actores de primera infancia.",
    },
    "protocolo_vulneracion_derechos": {
        "protocolo_revision_periodica_mayoria_conoce": "El CDI cuenta con protocolos específicos de intervención para la actuación ante sospecha o vulneración de derechos de los niños, que se revisan periódicamente y es conocido por más de la mitad del personal",
        "protocolo_revision_periodica_menos_mitad": "El CDI cuenta con protocolos específicos de intervención para la actuación ante sospecha o vulneración de derechos de los niños, que se revisan periódicamente y es conocido por menos de la mitad del personal",
        "protocolo_sin_revision_mayoria_conoce": "El CDI cuenta con protocolos específicos de intervención para la actuación ante sospecha o vulneración de derechos de los niños, que no tiene revisiones periódicas y es conocido por la más de la mitad del personal",
        "protocolo_sin_revision_menos_mitad": "El CDI cuenta con protocolos específicos de intervención para la actuación ante sospecha o vulneración de derechos de los niños, que no tiene revisiones periódicas y es conocido por menos de la mitad del personal",
        "no_existe": "El CDI no cuenta con protocolos específicos de intervención para la actuación ante sospecha o vulneración de derechos de los niños.",
    },
    "nivel_equipo_tecnico": {
        "completo_mas_20_horas": "El CDI cuenta con un equipo técnico completo y más de 20 horas semanales de trabajo.",
        "perfiles_diversos_15_19_horas": "El CDI cuenta con un equipo técnico con perfiles diversos (al menos dos de los sugeridos) y entre 15 y 19 horas semanales de trabajo.",
        "al_menos_un_perfil_o_10_14_horas": "El CDI cuenta con un equipo técnico con al menos un perfil profesional y/o con entre 10 y 14 horas semanales de trabajo.",
        "limitado_un_perfil_o_9_o_menos": "El CDI cuenta con un equipo técnico limitado (un solo perfil profesional) y/o 9 horas o menos de trabajo semanal.",
        "sin_equipo": "El CDI no cuenta con equipo técnico.",
    },
    "participantes_proyecto_socioeducativo": {
        "conduccion_sala_equipo_auxiliar_familias_comunidad": "Participan la conducción, el personal de sala, el equipo técnico, el personal auxiliar, las familias y actores comunitarios",
        "conduccion_sala_equipo_familias": "Participan la conducción, el personal de sala, el equipo técnico y las familias",
        "conduccion_sala_equipo": "Participan la conducción, el personal de sala y el equipo técnico",
        "conduccion_y_o_equipo": "Participan la conducción y/o el equipo técnico",
        "no_tienen": "No tienen proyecto socioeducativo institucional",
    },
    "planificacion_actividades_sala": {
        "semanal_en_marco_mensual_o_semestral_y_anual": "Se diseñan actividades semanales enmarcadas en planificaciones más amplias (mensuales o semestrales) y en un plan anual.",
        "semanal_en_marco_mensual_o_semestral_sin_anual": "Se diseñan actividades semanales enmarcadas en planificaciones más amplias (mensuales o semestrales), pero sin plan anual.",
        "semanal_en_marco_anual": "Se diseñan actividades semanales enmarcadas únicamente en un plan anual.",
        "solo_semanal": "Se diseñan únicamente actividades semanales, sin articulación con planificaciones más amplias.",
        "no_planifican": "No se realizan planificaciones de actividades.",
    },
    "planificacion_integral": {
        "intereses_caracteristicas_necesidades_e_integralidad": "Sí, se tienen en cuenta intereses, características, necesidades e integralidad de contenidos",
        "solo_intereses_caracteristicas_necesidades": "Solo se tienen en cuenta los intereses, características y necesidades del grupo",
        "solo_integralidad": "Solo se tiene en cuenta la integralidad de los contenidos",
        "ninguno": "No se tienen en cuenta los intereses, características, necesidades ni integralidad de los contenidos",
        "no_planifican": "No se realizan planificaciones",
    },
    "formacion_direccion_primera_infancia": {
        "titulo_superior_completo_especifico": "Posee título universitario o terciario completo de carreras específicas en primera infancia (ej. Educación Inicial, Trabajo Social, Psicología, Psicopedagogía, Estimulación Temprana u otras afines).",
        "carrera_75_o_mas_o_posgrados": "Posee al menos el 75% de una carrera superior en temáticas vinculadas a la infancia o cuenta con posgrados/cursos de especialización acreditados.",
        "cursando_formacion_formal": "Se encuentra actualmente cursando una carrera o formación formal relacionada con la primera infancia.",
        "solo_cursos_cortos": "Ha realizado solo cursos o capacitaciones cortas no sistemáticas en temas de infancia.",
        "sin_formacion": "No posee formación superior ni capacitaciones en temáticas vinculadas a la infancia.",
    },
    "cobertura_duplas_pedagogicas": {
        "todas": "Sí, en todas las salas trabajan en dupla",
        "mayoria": "Sí, en la mayoría de las salas trabajan en dupla",
        "algunas": "Solo en algunas salas trabajan en dupla",
        "muy_pocas": "Muy pocas salas trabajan en duplas",
        "ninguna": "No se trabaja en duplas en ninguna sala",
    },
    "cobertura_educadora_titulo_habilitante": {
        "todas": "Sí, en todas las salas una educadora cuenta cn título habilitante de nivel inicial",
        "mayoria": "Sí, en la mayoría de las salas una educadora cuenta con título habilitante de nivel inicial",
        "algunas": "Solo en algunas salas una educadora cuenta con título habilitante de nivel inicial",
        "muy_pocas": "Muy pocas salas tienen una educadora con título habilitante",
    },
    "cobertura_formacion_auxiliares": {
        "todos": "Todos los auxiliares cuentan con formación específica en primera infancia",
        "mayoria": "La mayoría de los auxiliares cuentan con formación específica en primera infancia",
        "algunos": "Algunos auxiliares cuentan con formación específica en primera infancia",
        "muy_pocos": "Muy pocos auxiliares cuentan con formación específica en primera infancia",
        "ninguno": "Ningún auxiliar cuenta con formación en primera infancia",
    },
    "modalidad_contratacion_principal": {
        "permanente": "La mayor proporción de personal tiene Contratación permanente",
        "temporal": "La mayor proporción de personal tiene Contratación temporal",
        "beca_o_pasantia": "La mayor proporción de personal tiene Beca o pasantía",
        "programa_social_insercion": "La mayor proporción de personal tiene Programa social de inserción laboral",
        "voluntario_u_otra": "La mayor proporción de personal es voluntario u otra modalidad",
    },
}

SOBREESCRITURAS_ETIQUETAS_OPCIONES_MULTIPLES = {
    "items_protocolo_salud": {
        "emergencias_medicas": "Actuación frente a emergencias médicas",
        "suministro_medicamentos": "Suministro de medicamentos",
        "sintomas_enfermedad": "Pautas de actuación frente a síntomas de enfermedad",
        "reintegro_post_enfermedad": "Pautas para el reintegro de niños después de una enfermedad",
        "conocido_por_todo_el_personal": "El protocolo es conocido por todo el personal",
        "no_existe_protocolo_escrito": "No existe protocolo escrito",
    },
}

SOBREESCRITURAS_ETIQUETAS_CAMPOS = {
    "fecha_relevamiento": "Fecha de Relevamiento",
    "uso_exclusivo_espacio": "Uso Exclusivo del Espacio: ¿El lugar físico en donde funciona el CDI es compartido con otras actividades, personas u organizaciones?",
    "acceso_energia": "Acceso a Energía: ¿El CDI tiene electricidad? (marcar la opción que corresponda)",
    "seguridad_electrica": "Seguridad Eléctrica: ¿Las instalaciones eléctricas cumplen con la normativa de seguridad y se verifican periódicamente?",
    "acceso_agua": "Acceso a Agua: ¿El CDI tiene agua?",
    "fuente_agua_segura_consumo": "Acceso a Agua segura para consumo: ¿Cuál es la fuente de agua utilizada para consumo en el CDI?",
    "eliminacion_excretas": "Eliminación de excretas - El desagüe del CDI es:",
    "acceso_internet_personal": "Acceso a internet: ¿El CDI tiene acceso a internet y es compartido por el personal?",
    "plan_evacuacion_y_simulacros": "Plan de evacuación ¿El CDI cuenta con plan de evacuación y realiza simulacros?",
    "cobertura_capacitacion_primeros_auxilios": "Capacitación en primeros auxilios ¿Cuenta todo el personal del CDI con capacitación certificada en primeros auxilios (Cruz Roja, Bomberos, otros)?",
    "servicio_emergencia_medica": "Servicio de emergencia médica ¿El CDI cuenta con un servicio de emergencia médica (a domicilio pago o línea prioritaria SAME/SEM) y tiene identificada la cobertura correspondiente a cada niño?",
    "items_protocolo_salud": "Existencia de protocolo de actuación en salud. ¿El CDI cuenta con un protocolo escrito que contemple los siguientes aspectos? (Marcar todas las opciones que correspondan).",
    "prestaciones_alimentarias": "Prestación Alimentaria del CDI",
    "calidad_elaboracion_menu": "Elaboración de alimentos : En referencia al menú, ¿cómo se elabora y qué tipo de alimentos incluye?",
    "evaluacion_periodica_menu": "Evaluación periódica del menú: ¿El CDI realiza evaluaciones periódicas del menú y contempla las necesidades nutricionales (celiaquía, bajo peso, obesidad, diabetes, etc.) y los distintos patrones alimentarios (incluyendo opciones basadas en plantas) de los niños y niñas?",
    "cobertura_capacitacion_manipulacion_alimentos": "Capacitaciones en manipulación de alimentos ¿El personal de cocina y comedor cuenta con capacitaciones en manipulación de alimentos y carnet emitido por ANMAT?",
    "condiciones_almacenamiento_leche_humana": "Condiciones para el almacenamiento de leche humana ¿El CDI cuenta con condiciones adecuadas para la conservación de leche humana?",
    "acciones_sensibilizacion_lactancia": "Acciones de información y sensibilización de la lactancia ¿Con qué frecuencia y alcance el CDI realiza acciones de información y sensibilización sobre lactancia (talleres, reuniones, folletería u otras)?",
    "tiene_personal_entrada_salida": "¿Hay personal encargado para la entrada y salida de los niños y niñas al CDI?",
    "frecuencia_comunicacion_familias": "Comunicación con las familias ¿Con qué frecuencia el CDI mantiene reuniones con las familias y dispone de canales formales de comunicación?",
    "frecuencia_talleres_crianza": "Talleres de crianza, charlas con profesionales ¿Con qué frecuencia el CDI ofrece talleres de crianza o charlas con profesionales dirigidas a las familias?",
    "realiza_acciones_promocion_acceso_derechos": "Acciones de Promoción y acceso a derechos: ¿El CDI realiza acciones para facilitar el acceso de los/as niños/as y sus familias a derechos y políticas/programas de promoción y protección social (identidad, AUH/AUD/AUE, pensiones, salud, discapacidad, entre otros)?",
    "realiza_acciones_acompanamiento_vulneracion_derechos": "Acciones de acompañamiento ante vulneración de derechos ¿El CDI realiza acciones de acompañamiento a las familias ante situaciones de vulneración de derechos (violencia intrafamiliar, judicialización de conflictos familiares, abuso sexual, entre otras)?",
    "nivel_trabajo_red": "Trabajo en red ¿El CDI trabaja en red con otras instituciones, cuenta con un mapeo de actores de primera infancia y participa en mesas intersectoriales?",
    "protocolo_vulneracion_derechos": "Protocolo frente a vulneración de derechos ¿El CDI cuenta con protocolos específicos para la actuación ante sospecha o vulneración de derechos de los niños, se revisan periódicamente y son conocidos por el personal?",
    "nivel_equipo_tecnico": "¿El CDI cuenta con un equipo técnico completo (trabajador/a social, psicólogo/a, psicopedagogo/a o estimulador/a temprano) y cuántas horas semanales de trabajo dedica?",
    "frecuencia_registro_desarrollo_nino": "desarrollo del niño/a. Registro y frecuencia de actualización ¿Con qué frecuencia el CDI registra y actualiza la información sobre el desarrollo de cada niño/a?",
    "frecuencia_registro_informacion_familiar": "Información familiar. Registro y frecuencia de actualización ¿Con qué frecuencia el CDI registra y actualiza la información familiar de cada niño/a?",
    "frecuencia_registro_salud_vacunas": "Información de controles de salud y vacunas. Registro y frecuencia de actualización ¿Con qué frecuencia el CDI registra y actualiza la información sobre los controles de salud y vacunas de cada niño/a?",
    "participantes_proyecto_socioeducativo": "Proyecto socioeducativo institucional ¿Quiénes participan en la elaboración del proyecto socioeducativo institucional del CDI?",
    "planificacion_actividades_sala": "Existencia de planificación de actividades en sala ¿Cómo se planifican las actividades en sala dentro del CDI?",
    "planificacion_integral": "Planificación integral ¿Las planificaciones de actividades en sala se realizan teniendo en cuenta los intereses, características y necesidades del grupo como así también la integralidad de los contenidos?",
    "formacion_direccion_primera_infancia": "Formación de la dirección/coordinación en primera infancia ¿La dirección o coordinación del CDI cuenta con formación superior en temáticas vinculadas a la primera infancia?",
    "cobertura_duplas_pedagogicas": "Trabajo en duplas en sala. ¿En todas las salas del CDI se trabaja con duplas pedagógicas a cargo?",
    "cobertura_educadora_titulo_habilitante": "Formación habilitante del personal de sala. ¿Al menos una educadora cuenta con título habilitante de nivel inicial?",
    "cobertura_formacion_auxiliares": "Formación de auxiliares en primera infancia. ¿Los auxiliares de sala cuentan con formación específica en primera infancia?",
    "modalidad_contratacion_principal": "Modalidad de contratación ¿Cuál es la principal modalidad de contratación del personal del CDI?",
    "frecuencia_reuniones_personal_sala": "¿Con qué frecuencia se realizan reuniones entre el personal de sala, la coordinación y/o el equipo técnico del CDI?",
    "frecuencia_reuniones_personal_no_docente": "¿Con qué frecuencia se realizan reuniones entre el personal no docente del CDI (cocina, limpieza, mantenimiento, etc.) y la coordinación?",
    "frecuencia_reuniones_todo_personal": "¿Con qué frecuencia se realizan reuniones entre todo el personal?",
    "instancias_capacitacion_todo_personal_ultimos_3_anios": "En los últimos 3 años, ¿cuántas instancias de capacitación ha promovido el CDI para todo su personal?",
    "instancias_capacitacion_personal_sala_ultimos_3_anios": "En los últimos 3 años, ¿cuántas instancias de capacitación ha promovido el CDI para el personal de sala?",
    "instancias_capacitacion_equipo_tecnico_ultimos_3_anios": "En los últimos 3 años, ¿cuántas instancias de capacitación ha promovido el CDI para el equipo técnico?",
    "instancias_capacitacion_personal_cocina_ultimos_3_anios": "En los últimos 3 años, ¿cuántas instancias de capacitación ha promovido el CDI para el personal de cocina y comedor?",
    "combustible_cocinar": "Para cocinar, el CDI utiliza principalmente: (marcar la opción que corresponda)",
    "tiene_espacio_exterior": "Espacio exterior: ¿El CDI cuenta con espacio exterior donde puedan realizarse actividades con los niños (patio, jardín, etc.)?",
    "tiene_juegos_exteriores": "Juegos infantiles de exterior ¿El espacio cuenta con juegos infantiles de exterior (hamacas, toboganes, etc.)?",
    "modalidad_gestion": "Modalidad de Gestión",
    "modalidad_tenencia": "Modalidad de Tenencia",
}






def humanizar_codigo(value: str) -> str:
    """Convierte códigos internos en etiquetas legibles."""
    text = str(value or "").replace("_", " ")
    replacements = {
        "nino": "niño",
        "nina": "niña",
        "ninos": "niños",
        "ninas": "niñas",
        "ano": "año",
        "anos": "años",
        "tecnico": "técnico",
        "dias": "días",
    }
    for source, target in replacements.items():
        text = text.replace(source, target)
    return text.capitalize()


OPCIONES_MESES = [
    ("ENE", "ENE"),
    ("FEB", "FEB"),
    ("MAR", "MAR"),
    ("ABR", "ABR"),
    ("MAY", "MAY"),
    ("JUN", "JUN"),
    ("JUL", "JUL"),
    ("AGO", "AGO"),
    ("SET", "SET"),
    ("OCT", "OCT"),
    ("NOV", "NOV"),
    ("DIC", "DIC"),
]

OPCIONES_DIAS_SEMANA = [
    ("LUNES", "Lunes"),
    ("MARTES", "Martes"),
    ("MIERCOLES", "Miercoles"),
    ("JUEVES", "Jueves"),
    ("VIERNES", "Viernes"),
    ("SABADO", "Sabado"),
    ("DOMINGO", "Domingo"),
]

OPCIONES_GRUPO_ETARIO_SALAS = [
    ("lactantes", "Lactantes"),
    ("deambuladores", "Deambuladores"),
    ("dos_anos", "Dos años"),
    ("tres_anos", "Tres años"),
    ("cuatro_anos", "Cuatro Años"),
    ("multiedad", "Multiedad"),
]

OPCIONES_GRUPO_ETARIO_DEMANDA = [
    ("lactantes", "Lactantes"),
    ("deambuladores", "Deambuladores"),
    ("un_ano", "Un año"),
    ("dos_anos", "dos años"),
    ("tres_anos", "tres años"),
    ("cuatro_anos", "cuatro años"),
]

OPCIONES_INSTITUCIONES_ARTICULACION = [
    ("servicio_promocion_proteccion_local", "Servicio de promocion y proteccion local"),
    ("servicio_promocion_proteccion_zonal", "Servicio de promocion y proteccion zonal"),
    ("salud_caps_hospital_municipal", "Salud CAPS/Hospital municipal"),
    ("salud_hospital_provincial", "Salud hospital provincial"),
    ("educacion_jardin_maternal", "Educacion jardin maternal"),
    ("educacion_escuela_primaria", "Educacion escuela primaria"),
    ("desarrollo_social_municipal", "Desarrollo social municipal"),
    ("desarrollo_social_provincial", "Desarrollo social provincial"),
    ("justicia_juzgado", "Justicia/Juzgado"),
    ("cultura_juegotecas", "Cultura/Juegotecas"),
    ("cultura_espacios_comunitarios", "Cultura/Espacios comunitarios"),
    ("cultura_iglesias", "Cultura/Iglesias"),
    ("seguridad_policia", "Seguridad/Policia"),
    ("seguridad_social_anses", "Seguridad social/ANSES"),
    ("identidad_renaper", "Identidad/RENAPER"),
]


def _construir_opciones(*values: str) -> list[tuple[str, str]]:
    return [(value, humanizar_codigo(value)) for value in values]


CAMPOS_OPCIONES = {
    "tipo_jornada": [
        ("simple_single_shift", "Jornada simple"),
        ("multiple_simple_shifts", "Dos o mas jornadas simples"),
        ("full_double_same_group", "Jornada completa/doble"),
        ("other", "Otra"),
    ],
    "modalidad_gestion": _construir_opciones(
        "gobierno_nacional",
        "gobierno_provincial",
        "gobierno_municipal",
        "ong",
        "cogestion_provincial_municipal",
        "cogestion_ong_provincial_municipal",
        "otra",
    ),
    "modalidad_tenencia": _construir_opciones(
        "propio",
        "alquilado",
        "cedido_gubernamental",
        "cedido_privado",
        "comodato",
        "ocupado_de_hecho",
        "otra",
    ),
    "acceso_energia": _construir_opciones(
        "red_formal",
        "red_informal",
        "generacion_propia_motor",
        "generacion_propia_otros",
        "sin_electricidad",
    ),
    "seguridad_electrica": _construir_opciones(
        "cumple_y_revision_mayor_a_un_ano",
        "cumple_y_revision_anual",
        "cumple_sin_revisiones",
        "cumple_solo_zonas_ninos_sin_revisiones",
        "no_cumple_sin_revisiones",
    ),
    "acceso_agua": _construir_opciones(
        "caneria_dentro_cdi",
        "fuera_cdi_dentro_terreno",
        "fuera_del_terreno",
        "sin_agua",
    ),
    "fuente_agua_segura_consumo": _construir_opciones(
        "red_o_embotellada_segura",
        "pozo_analisis_vigente",
        "pozo_analisis_vencido_o_sin_control",
        "otra_con_proceso_sin_garantia_formal",
        "otra_sin_info_potabilizacion",
    ),
    "eliminacion_excretas": _construir_opciones(
        "red_publica_cloaca",
        "camara_septica_pozo_ciego",
        "solo_pozo_ciego",
        "hoyo_tierra",
        "sin_sistema",
    ),
    "estado_botiquin_primeros_auxilios": [
        (
            "completo_todas_salas_ok_vigente_fuera_alcance",
            "Cuentan con botiquín completo de primeros auxilios en todas las salas, en buena conservación y con insumos dentro de la fecha de vencimiento; fuera del alcance de los niños",
        ),
        (
            "incompleto_todas_salas_ok_vigente_fuera_alcance",
            "Cuentan con botiquín incompleto de primeros auxilios en todas las salas, en buena conservación y con insumos dentro de la fecha de vencimiento; fuera del alcance de los niños",
        ),
        (
            "unico_completo_compartido_ok_vigente_fuera_alcance",
            "Cuentan con un único botiquín completo de primeros auxilios compartido por las salas, en buena conservación y con insumos dentro de la fecha de vencimiento; fuera del alcance de los niños",
        ),
        (
            "incompleto_compartido_o_mal_estado_o_vencido",
            "Cuentan con botiquín incompleto de primeros auxilios compartido por las salas y/o los insumos se encuentran en mala conservación y fuera de la fecha de vencimiento",
        ),
        (
            "no_tienen_o_al_alcance_ninos",
            "No cuentan con botiquín de primeros auxilios o el botiquín está al alcance de los niños",
        ),
    ],
    "acceso_internet_personal": _construir_opciones(
        "alta_velocidad_con_acceso_personal",
        "estable_con_acceso_personal",
        "estable_sin_acceso_personal",
        "mala_calidad_con_acceso_personal",
        "sin_servicio",
    ),
    "tiene_espacio_cocina": [
        ("si", "Si"),
        ("no", "No"),
        ("no_sabe_no_responde", "No sabe / No responde"),
    ],
    "combustible_cocinar": _construir_opciones(
        "gas_red",
        "gas_granel_tubo_garrafa",
        "electricidad",
        "lena_o_carbon",
        "no_utiliza",
    ),
    "tiene_espacio_exterior": [("si", "Si"), ("no", "No"), ("no_responde", "No responde")],
    "tiene_juegos_exteriores": [
        ("si", "Si"),
        ("no", "No"),
        ("no_responde", "No responde"),
    ],
    "plan_evacuacion_y_simulacros": _construir_opciones(
        "protocolo_escrito_y_2_simulacros_o_mas",
        "protocolo_escrito_y_simulacros_sin_frecuencia",
        "protocolo_escrito_sin_simulacros",
        "practicas_informales_sin_protocolo",
        "sin_protocolo",
    ),
    "cobertura_capacitacion_primeros_auxilios": _construir_opciones(
        "todo_personal_certificado",
        "entre_70_y_99",
        "entre_40_y_69",
        "menos_40",
        "ninguno",
    ),
    "servicio_emergencia_medica": _construir_opciones(
        "servicio_y_cobertura_identificada",
        "servicio_sin_cobertura_identificada",
        "sin_servicio_con_cobertura_identificada",
        "sin_servicio_con_cobertura_parcial",
        "sin_servicio_y_sin_cobertura",
    ),
    "calidad_elaboracion_menu": _construir_opciones(
        "nutricionista_indicaciones_y_frescos",
        "nutricionista_indicaciones_a_veces_sin_frescos",
        "no_siempre_nutricionista_parcial_y_mixto",
        "sin_nutricionista_pocas_indicaciones_procesados",
        "sin_nutricionista_ultraprocesados",
    ),
    "evaluacion_periodica_menu": _construir_opciones(
        "periodica_todas_necesidades_y_patrones_y_personas",
        "periodica_mayoria_necesidades_y_algunos_patrones",
        "ocasional_parcial_y_capacitacion_esporadica",
        "rara_vez_limitada_sin_patrones",
        "no_evalua",
    ),
    "cobertura_capacitacion_manipulacion_alimentos": _construir_opciones(
        "todo_personal_anmat",
        "entre_70_y_99",
        "entre_40_y_60",
        "menos_40",
        "ninguno",
    ),
    "condiciones_almacenamiento_leche_humana": _construir_opciones(
        "heladera_exclusiva_identificada_y_rotulada",
        "heladera_compartida_sector_exclusivo_identificada_y_rotulada",
        "heladera_exclusiva_identificada_sin_fecha",
        "heladera_compartida_sector_exclusivo_identificada_sin_fecha",
        "sin_espacio_exclusivo_ni_identificacion",
    ),
    "acciones_sensibilizacion_lactancia": _construir_opciones(
        "dos_o_mas_anuales_todas_familias",
        "una_anual_todas_familias",
        "una_anual_alcance_limitado",
        "muy_ocasionales_limitadas",
        "ninguna",
    ),
    "tiene_registro_lista_espera": [("si", "Si"), ("no", "No"), ("ns_nc", "NS/NC")],
    "tiene_personal_entrada_salida": [("si", "Si"), ("no", "No"), ("ns_nc", "NS/NC")],
    "frecuencia_comunicacion_familias": _construir_opciones(
        "reuniones_mensuales_y_canales_formales",
        "reuniones_trimestrales_y_canales_formales",
        "reuniones_semestrales_y_algunos_canales",
        "reuniones_anuales_sin_canales",
        "sin_reuniones_ni_canales",
    ),
    "frecuencia_talleres_crianza": _construir_opciones(
        "trimestral_o_mas",
        "cada_4_a_6_meses",
        "una_vez_al_ano",
        "esporadica",
        "no_se_realizan",
    ),
    "realiza_acciones_promocion_acceso_derechos": [("si", "Si"), ("no", "No"), ("ns_nc", "NS/NC")],
    "realiza_acciones_acompanamiento_vulneracion_derechos": [
        ("si", "Si"),
        ("no", "No"),
        ("ns_nc", "NS/NC"),
    ],
    "nivel_trabajo_red": _construir_opciones(
        "red_mapeo_mesas_trimestral_o_mas",
        "red_mapeo_mesas_semestral",
        "sin_red_con_mapeo_y_mesas",
        "sin_red_sin_mesas_con_mapeo",
        "sin_red_ni_mapeo",
    ),
    "protocolo_vulneracion_derechos": _construir_opciones(
        "protocolo_revision_periodica_mayoria_conoce",
        "protocolo_revision_periodica_menos_mitad",
        "protocolo_sin_revision_mayoria_conoce",
        "protocolo_sin_revision_menos_mitad",
        "no_existe",
    ),
    "nivel_equipo_tecnico": _construir_opciones(
        "completo_mas_20_horas",
        "perfiles_diversos_15_19_horas",
        "al_menos_un_perfil_o_10_14_horas",
        "limitado_un_perfil_o_9_o_menos",
        "sin_equipo",
    ),
    "frecuencia_registro_desarrollo_nino": _construir_opciones(
        "mensual",
        "trimestral",
        "semestral",
        "anual",
        "no_registra",
    ),
    "frecuencia_registro_informacion_familiar": _construir_opciones(
        "mensual",
        "trimestral",
        "semestral",
        "anual",
        "no_registra",
    ),
    "frecuencia_registro_salud_vacunas": _construir_opciones(
        "mensual",
        "trimestral",
        "semestral",
        "anual",
        "no_registra",
    ),
    "participantes_proyecto_socioeducativo": _construir_opciones(
        "conduccion_sala_equipo_auxiliar_familias_comunidad",
        "conduccion_sala_equipo_familias",
        "conduccion_sala_equipo",
        "conduccion_y_o_equipo",
        "no_tienen",
    ),
    "planificacion_actividades_sala": _construir_opciones(
        "semanal_en_marco_mensual_o_semestral_y_anual",
        "semanal_en_marco_mensual_o_semestral_sin_anual",
        "semanal_en_marco_anual",
        "solo_semanal",
        "no_planifican",
    ),
    "planificacion_integral": _construir_opciones(
        "intereses_caracteristicas_necesidades_e_integralidad",
        "solo_intereses_caracteristicas_necesidades",
        "solo_integralidad",
        "ninguno",
        "no_planifican",
    ),
    "formacion_direccion_primera_infancia": _construir_opciones(
        "titulo_superior_completo_especifico",
        "carrera_75_o_mas_o_posgrados",
        "cursando_formacion_formal",
        "solo_cursos_cortos",
        "sin_formacion",
    ),
    "cobertura_duplas_pedagogicas": _construir_opciones(
        "todas",
        "mayoria",
        "algunas",
        "muy_pocas",
        "ninguna",
    ),
    "cobertura_educadora_titulo_habilitante": _construir_opciones(
        "todas",
        "mayoria",
        "algunas",
        "muy_pocas",
    ),
    "cobertura_formacion_auxiliares": _construir_opciones(
        "todos",
        "mayoria",
        "algunos",
        "muy_pocos",
        "ninguno",
    ),
    "modalidad_contratacion_principal": _construir_opciones(
        "permanente",
        "temporal",
        "beca_o_pasantia",
        "programa_social_insercion",
        "voluntario_u_otra",
    ),
    "frecuencia_reuniones_personal_sala": _construir_opciones(
        "mensual",
        "trimestral",
        "semestral",
        "anual",
        "no_se_realizan",
    ),
    "frecuencia_reuniones_personal_no_docente": _construir_opciones(
        "mensual",
        "trimestral",
        "semestral",
        "anual",
        "no_se_realizan",
    ),
    "frecuencia_reuniones_todo_personal": _construir_opciones(
        "mensual",
        "trimestral",
        "semestral",
        "anual",
        "no_se_realizan",
    ),
    "instancias_capacitacion_todo_personal_ultimos_3_anios": _construir_opciones(
        "seis_o_mas",
        "cuatro_o_cinco",
        "dos_o_tres",
        "una",
        "ninguna",
    ),
    "instancias_capacitacion_personal_sala_ultimos_3_anios": _construir_opciones(
        "seis_o_mas",
        "cuatro_o_cinco",
        "dos_o_tres",
        "una",
        "ninguna",
    ),
    "instancias_capacitacion_equipo_tecnico_ultimos_3_anios": _construir_opciones(
        "seis_o_mas",
        "cuatro_o_cinco",
        "dos_o_tres",
        "una",
        "ninguna",
    ),
    "instancias_capacitacion_personal_cocina_ultimos_3_anios": _construir_opciones(
        "seis_o_mas",
        "cuatro_o_cinco",
        "dos_o_tres",
        "una",
        "ninguna",
        "no_aplica",
    ),
}

CAMPOS_OPCIONES_MULTIPLES = {
    "meses_funcionamiento": OPCIONES_MESES,
    "dias_funcionamiento": OPCIONES_DIAS_SEMANA,
    "items_protocolo_salud": _construir_opciones(
        "emergencias_medicas",
        "suministro_medicamentos",
        "sintomas_enfermedad",
        "reintegro_post_enfermedad",
        "conocido_por_todo_el_personal",
        "no_existe_protocolo_escrito",
    ),
    "prestaciones_alimentarias": _construir_opciones(
        "desayuno",
        "almuerzo",
        "merienda",
        "pre_cena",
        "cena",
        "otra",
        "ninguna",
    ),
}

ETIQUETAS_BOOLEANAS = {
    "uso_exclusivo_espacio": (
        "Si, compartido con otras actividades/personas/organizaciones",
        "No",
    ),
}

ETIQUETAS_CAMPOS = {
    "fecha_relevamiento": "Fecha",
    "nombre_completo_respondente": "Nombre y apellido de quien responde el cuestionario",
    "rol_respondente": "Funcion que cumple",
    "email_respondente": "Mail de contacto",
    "nombre_cdi": "Nombre del Centro de Desarrollo Infantil",
    "codigo_cdi": "Identificador interno del CDI",
    "provincia_cdi": "Provincia del CDI",
    "departamento_cdi": "Departamento del CDI",
    "municipio_cdi": "Municipio del CDI",
    "localidad_cdi": "Localidad del CDI",
    "calle_cdi": "Calle del CDI",
    "numero_puerta_cdi": "Numeracion de puerta del CDI",
    "codigo_postal_cdi": "Codigo postal del CDI",
    "latitud_geografica_cdi": "Coordenada geografica latitud",
    "longitud_geografica_cdi": "Coordenada geografica longitud",
    "telefono_cdi": "Teléfono del CDI",
    "email_cdi": "Mail del CDI",
    "nombre_referente_cdi": "Referente del CDI nombre/s",
    "apellido_referente_cdi": "Referente del CDI apellido/s",
    "telefono_referente_cdi": "Referente del CDI telefono",
    "email_referente_cdi": "Referente del CDI mail",
    "meses_funcionamiento": "Meses de funcionamiento del CDI",
    "dias_funcionamiento": "Días de funcionamiento del CDI",
    "horario_apertura": "Horario de apertura",
    "horario_cierre": "Horario de cierre",
    "tipo_jornada": "Tipo de jornada",
    "tipo_jornada_otra": "Otra jornada - especificar",
    "cantidad_total_ninos": "Cantidad de niños que asisten en total",
    "cantidad_total_personal": "Cantidad de personal en total",
    "modalidad_gestion": "Modalidad de gestion",
    "modalidad_gestion_otra": "Modalidad de gestion - otra",
    "nombre_organizacion_gestora": "Denominacion del organismo u organizacion",
    "cuit_organizacion_gestora": "CUIT del organismo",
    "provincia_organizacion": "Provincia del organismo",
    "departamento_organizacion": "Departamento del organismo",
    "municipio_organizacion": "Municipio del organismo",
    "localidad_organizacion": "Localidad del organismo",
    "calle_organizacion": "Calle",
    "numero_organizacion": "Numeracion",
    "codigo_postal_organizacion": "Codigo postal",
    "edificio_organizacion": "Edificio",
    "piso_organizacion": "Piso",
    "departamento_domicilio_organizacion": "Departamento",
    "oficina_organizacion": "Oficina",
    "telefono_organizacion": "Teléfono",
    "email_organizacion": "Mail",
    "nombre_referente_organizacion": "Referente institucional nombre/s",
    "apellido_referente_organizacion": "Referente institucional apellido/s",
    "telefono_referente_organizacion": "Referente institucional telefono",
    "email_referente_organizacion": "Referente institucional mail",
    "modalidad_tenencia": "Modalidad de tenencia",
    "modalidad_tenencia_otra": "Modalidad de tenencia - otra",
    "uso_exclusivo_espacio": "Uso exclusivo del espacio",
    "cantidad_ambientes_sin_areas_servicio": "Cantidad de ambientes (sin cocina/banos/pasillos/garajes)",
    "acceso_energia": "Acceso a energia",
    "seguridad_electrica": "Seguridad electrica",
    "acceso_agua": "Acceso a agua",
    "fuente_agua_segura_consumo": "Acceso a agua segura para consumo",
    "eliminacion_excretas": "Eliminacion de excretas",
    "tiene_extintores_vigentes": "Existencia de extintores",
    "estado_botiquin_primeros_auxilios": "Existencia de Botiquín",
    "tiene_computadora_funcionando": "Existencia de computadora",
    "acceso_internet_personal": "Acceso a internet",
    "tiene_espacio_cocina": "Espacio de cocina",
    "combustible_cocinar": "Combustible usado para cocinar",
    "tiene_espacio_exterior": "Espacio exterior",
    "tiene_juegos_exteriores": "Juegos infantiles de exterior",
    "plan_evacuacion_y_simulacros": "Plan de evacuacion",
    "cobertura_capacitacion_primeros_auxilios": "Capacitación en primeros auxilios",
    "servicio_emergencia_medica": "Servicio de emergencia medica + cobertura identificada",
    "items_protocolo_salud": "Protocolo de actuación en salud",
    "prestaciones_alimentarias": "Alimentacion",
    "prestaciones_alimentarias_otra": "Otra comida - especificar",
    "calidad_elaboracion_menu": "Elaboracion de alimentos",
    "evaluacion_periodica_menu": "Evaluacion periodica del menu",
    "cobertura_capacitacion_manipulacion_alimentos": "Capacitaciones en manipulación de alimentos",
    "condiciones_almacenamiento_leche_humana": "Condiciones para almacenamiento de leche humana",
    "acciones_sensibilizacion_lactancia": "Acciones de informacion y sensibilizacion de lactancia",
    "tiene_registro_lista_espera": "Existe registro de lista de espera",
    "tiene_instrumento_priorizacion_ingreso": "Existe instrumento de priorización de ingreso de los niños/as",
    "cantidad_ninos_discapacidad": "Cantidad de niños con discapacidad",
    "cantidad_ninos_etnia_especifica": "Cantidad de niños de alguna etnia en particular",
    "tiene_personal_entrada_salida": "Personal encargado para entrada y salida",
    "frecuencia_comunicacion_familias": "Comunicacion con las familias",
    "frecuencia_talleres_crianza": "Talleres de crianza / charlas con profesionales",
    "realiza_acciones_promocion_acceso_derechos": "Acciones de promocion y acceso a derechos",
    "realiza_acciones_acompanamiento_vulneracion_derechos": "Acciones de acompanamiento ante vulneracion de derechos",
    "nivel_trabajo_red": "Trabajo en red",
    "protocolo_vulneracion_derechos": "Protocolo frente a vulneracion de derechos",
    "nivel_equipo_tecnico": "Equipo técnico",
    "frecuencia_registro_desarrollo_nino": "Registro de desarrollo del niño/a",
    "frecuencia_registro_informacion_familiar": "Registro de informacion familiar",
    "frecuencia_registro_salud_vacunas": "Registro de controles de salud y vacunas",
    "participantes_proyecto_socioeducativo": "Proyecto socioeducativo institucional",
    "planificacion_actividades_sala": "Existencia de planificacion de actividades en sala",
    "planificacion_integral": "Planificacion integral",
    "formacion_direccion_primera_infancia": "Formación de la dirección/coordinación en primera infancia",
    "cobertura_duplas_pedagogicas": "Trabajo en duplas en sala",
    "cobertura_educadora_titulo_habilitante": "Formacion habilitante del personal de sala",
    "cobertura_formacion_auxiliares": "Formacion de auxiliares en primera infancia",
    "modalidad_contratacion_principal": "Modalidad de contratacion",
    "frecuencia_reuniones_personal_sala": "Reuniones entre personal de sala, coordinación y/o equipo técnico",
    "frecuencia_reuniones_personal_no_docente": "Reuniones entre personal no docente y coordinación",
    "frecuencia_reuniones_todo_personal": "Reuniones entre todo el personal",
    "instancias_capacitacion_todo_personal_ultimos_3_anios": "Instancias de capacitación para todo el personal en últimos 3 años",
    "instancias_capacitacion_personal_sala_ultimos_3_anios": "Instancias de capacitación para personal de sala en últimos 3 años",
    "instancias_capacitacion_equipo_tecnico_ultimos_3_anios": "Instancias de capacitación para equipo técnico en últimos 3 años",
    "instancias_capacitacion_personal_cocina_ultimos_3_anios": "Instancias de capacitación para cocina/comedor en últimos 3 años",
}

for field_name, label_overrides in SOBREESCRITURAS_ETIQUETAS_OPCIONES.items():
    if field_name in CAMPOS_OPCIONES:
        CAMPOS_OPCIONES[field_name] = [
            (value, label_overrides.get(value, label))
            for value, label in CAMPOS_OPCIONES[field_name]
        ]

for field_name, label_overrides in SOBREESCRITURAS_ETIQUETAS_OPCIONES_MULTIPLES.items():
    if field_name in CAMPOS_OPCIONES_MULTIPLES:
        CAMPOS_OPCIONES_MULTIPLES[field_name] = [
            (value, label_overrides.get(value, label))
            for value, label in CAMPOS_OPCIONES_MULTIPLES[field_name]
        ]

ETIQUETAS_CAMPOS.update(SOBREESCRITURAS_ETIQUETAS_CAMPOS)

SECCIONES_FORMULARIO_CDI = [
    {
        "id": "metadatos",
        "title": "Metadatos del relevamiento",
        "fields": [
            "fecha_relevamiento",
            "nombre_completo_respondente",
            "rol_respondente",
            "email_respondente",
        ],
    },
    {
        "id": "caracterizacion_general",
        "title": "Caracterizacion general",
        "fields": [
            "nombre_cdi",
            "codigo_cdi",
            "provincia_cdi",
            "departamento_cdi",
            "municipio_cdi",
            "localidad_cdi",
            "calle_cdi",
            "numero_puerta_cdi",
            "codigo_postal_cdi",
            "latitud_geografica_cdi",
            "longitud_geografica_cdi",
            "telefono_cdi",
            "email_cdi",
            "nombre_referente_cdi",
            "apellido_referente_cdi",
            "telefono_referente_cdi",
            "email_referente_cdi",
            "meses_funcionamiento",
            "dias_funcionamiento",
            "horario_apertura",
            "horario_cierre",
            "tipo_jornada",
            "tipo_jornada_otra",
            "cantidad_total_ninos",
            "cantidad_total_personal",
        ],
    },
    {
        "id": "participacion_pfpi",
        "title": "CDI que participan del PFPI",
        "fields": [
            "modalidad_gestion",
            "modalidad_gestion_otra",
            "nombre_organizacion_gestora",
            "cuit_organizacion_gestora",
            "provincia_organizacion",
            "departamento_organizacion",
            "municipio_organizacion",
            "localidad_organizacion",
            "calle_organizacion",
            "numero_organizacion",
            "codigo_postal_organizacion",
            "edificio_organizacion",
            "piso_organizacion",
            "departamento_domicilio_organizacion",
            "oficina_organizacion",
            "telefono_organizacion",
            "email_organizacion",
            "nombre_referente_organizacion",
            "apellido_referente_organizacion",
            "telefono_referente_organizacion",
            "email_referente_organizacion",
            "modalidad_tenencia",
            "modalidad_tenencia_otra",
            "uso_exclusivo_espacio",
            "cantidad_ambientes_sin_areas_servicio",
        ],
    },
    {
        "id": "infraestructura_servicios",
        "title": "Infraestructura y servicios",
        "fields": [
            "acceso_energia",
            "seguridad_electrica",
            "acceso_agua",
            "fuente_agua_segura_consumo",
            "eliminacion_excretas",
            "tiene_extintores_vigentes",
            "estado_botiquin_primeros_auxilios",
            "tiene_computadora_funcionando",
            "acceso_internet_personal",
            "tiene_espacio_cocina",
            "combustible_cocinar",
            "tiene_espacio_exterior",
            "tiene_juegos_exteriores",
            "plan_evacuacion_y_simulacros",
            "cobertura_capacitacion_primeros_auxilios",
            "servicio_emergencia_medica",
            "items_protocolo_salud",
        ],
    },
    {
        "id": "modulo_alimentacion",
        "title": "Alimentacion",
        "fields": [
            "prestaciones_alimentarias",
            "prestaciones_alimentarias_otra",
            "calidad_elaboracion_menu",
            "evaluacion_periodica_menu",
            "cobertura_capacitacion_manipulacion_alimentos",
            "condiciones_almacenamiento_leche_humana",
            "acciones_sensibilizacion_lactancia",
        ],
    },
    {
        "id": "demanda_ingreso_poblacion",
        "title": "Demanda, ingreso y poblacion",
        "fields": [
            "tiene_registro_lista_espera",
            "tiene_instrumento_priorizacion_ingreso",
            "cantidad_ninos_discapacidad",
            "cantidad_ninos_etnia_especifica",
            "tiene_personal_entrada_salida",
        ],
    },
    {
        "id": "familias_derechos",
        "title": "Familias, derechos y articulacion",
        "fields": [
            "frecuencia_comunicacion_familias",
            "frecuencia_talleres_crianza",
            "realiza_acciones_promocion_acceso_derechos",
            "realiza_acciones_acompanamiento_vulneracion_derechos",
        ],
    },
    {
        "id": "trabajo_red_protocolos",
        "title": "Trabajo en red y protocolos",
        "fields": [
            "nivel_trabajo_red",
            "protocolo_vulneracion_derechos",
        ],
    },
    {
        "id": "equipo_tecnico",
        "title": "Equipo técnico",
        "fields": ["nivel_equipo_tecnico"],
    },
    {
        "id": "registros_ninos_proyecto_pedagogico",
        "title": "Registros del niño y proyecto pedagógico",
        "fields": [
            "frecuencia_registro_desarrollo_nino",
            "frecuencia_registro_informacion_familiar",
            "frecuencia_registro_salud_vacunas",
            "participantes_proyecto_socioeducativo",
            "planificacion_actividades_sala",
            "planificacion_integral",
            "formacion_direccion_primera_infancia",
        ],
    },
    {
        "id": "perfil_personal",
        "title": "Perfil y contratacion del personal",
        "fields": [
            "cobertura_duplas_pedagogicas",
            "cobertura_educadora_titulo_habilitante",
            "cobertura_formacion_auxiliares",
            "modalidad_contratacion_principal",
        ],
    },
    {
        "id": "reuniones_capacitaciones",
        "title": "Reuniones y capacitación",
        "fields": [
            "frecuencia_reuniones_personal_sala",
            "frecuencia_reuniones_personal_no_docente",
            "frecuencia_reuniones_todo_personal",
            "instancias_capacitacion_todo_personal_ultimos_3_anios",
            "instancias_capacitacion_personal_sala_ultimos_3_anios",
            "instancias_capacitacion_equipo_tecnico_ultimos_3_anios",
            "instancias_capacitacion_personal_cocina_ultimos_3_anios",
        ],
    },
]

CAMPOS_RESUMEN = [
    "id",
    "fecha_relevamiento",
    "nombre_completo_respondente",
    "created_at",
    "updated_at",
]




