"""Catálogo textual del formulario CDI."""

# pylint: disable=line-too-long

SOBREESCRITURAS_ETIQUETAS_OPCIONES = {
    "tipo_jornada": {
        "simple_single_shift": "Jornada simple (un solo turno con un único grupo de niños)",
        "multiple_simple_shifts": "Dos o más jornadas simples (dos o más turnos a los que asisten distintos grupos de niños)",
        "full_double_same_group": "Jornada completa/doble (dos o más turnos a los que asiste un mismo grupo de niños)",
    },
    "modalidad_gestion": {
        "ong": "ONG (incluye organizaciones sociales, movimientos sociales, grupos comunitarios o barriales, etc.)",
        "cogestion_provincial_municipal": "Co-gestión: Gob. Provincial y municipal",
        "cogestion_ong_provincial_municipal": "Co-gestión: ONG/Gob. Provincial/municipal",
    },
    "modalidad_tenencia": {
        "cedido_gubernamental": "Cedido o prestado por ente gubernamental (Municipio / Comuna / Provincia)",
        "cedido_privado": "Cedido o prestado por un privado",
        "comodato": "Comodato",
    },
    "acceso_energia": {
        "generacion_propia_motor": "Por generación propia a motor / grupo electrógeno",
        "generacion_propia_otros": "Por generación propia por otros medios (solar, eólica)",
        "sin_electricidad": "No tiene electricidad",
    },
    "seguridad_electrica": {
        "cumple_y_revision_mayor_a_un_ano": "La instalación eléctrica cumple con normas de seguridad y tiene revisiones con una frecuencia mayor al año",
        "cumple_y_revision_anual": "La instalación eléctrica cumple con normas de seguridad y tiene revisiones periódicas anuales",
        "cumple_sin_revisiones": "La instalación eléctrica cumple con normas de seguridad y no tiene revisiones periódicas",
        "cumple_solo_zonas_ninos_sin_revisiones": "La instalación eléctrica cumple con normas de seguridad únicamente en las zonas donde circulan los niños y no tiene revisiones periódicas",
        "no_cumple_sin_revisiones": "La instalación eléctrica no cumple con normas de seguridad y no tiene revisiones periódicas",
    },
    "acceso_agua": {
        "caneria_dentro_cdi": "Por cañería dentro del CDI",
        "fuera_cdi_dentro_terreno": "Fuera del CDI pero dentro del terreno",
        "sin_agua": "No tiene agua",
    },
    "fuente_agua_segura_consumo": {
        "red_o_embotellada_segura": "Agua de red o embotellada – considerada segura para el consumo.",
        "pozo_analisis_vigente": "Agua de pozo con análisis vigente – con aprobación de laboratorio en los últimos 2 años o potabilizada según métodos recomendados.",
        "pozo_analisis_vencido_o_sin_control": "Agua de pozo con análisis vencido o sin control – con aprobación de laboratorio de más de 2 años o sin análisis disponible.",
        "otra_con_proceso_sin_garantia_formal": "Otra fuente de agua con información parcial – existe algún proceso de potabilización pero sin garantía formal.",
        "otra_sin_info_potabilizacion": "Otra fuente de agua sin información sobre su potabilización – no se puede asegurar que sea apta para consumo.",
    },
    "eliminacion_excretas": {
        "red_publica_cloaca": "A red pública (cloaca)",
        "camara_septica_pozo_ciego": "A cámara séptica y pozo ciego",
        "solo_pozo_ciego": "Sólo a pozo ciego",
        "hoyo_tierra": "A hoyo o excavación en la tierra",
        "sin_sistema": "No tiene sistema de eliminación de excretas",
    },
    "estado_botiquin_primeros_auxilios": {
        "completo_todas_salas_ok_vigente_fuera_alcance": "Cuentan con botiquín completo de primeros auxilios en todas las salas, en buena conservación y con insumos dentro de la fecha de vencimiento; fuera del alcance de los niños",
        "incompleto_todas_salas_ok_vigente_fuera_alcance": "Cuentan con botiquín incompleto de primeros auxilios en todas las salas, en buena conservación y con insumos dentro de la fecha de vencimiento; fuera del alcance de los niños",
        "unico_completo_compartido_ok_vigente_fuera_alcance": "Cuentan con un único botiquín completo de primeros auxilios compartido por las salas, en buena conservación y con insumos dentro de la fecha de vencimiento; fuera del alcance de los niños",
        "incompleto_compartido_o_mal_estado_o_vencido": "Cuentan con botiquín incompleto de primeros auxilios compartido por las salas y/o los insumos se encuentran en mala conservación y fuera de la fecha de vencimiento",
        "no_tienen_o_al_alcance_ninos": "No cuentan con botiquín de primeros auxilios o el botiquín está al alcance de los niños",
    },
    "acceso_internet_personal": {
        "alta_velocidad_con_acceso_personal": "El CDI cuenta con un servicio de internet de alta velocidad al que accede el personal",
        "estable_con_acceso_personal": "El CDI cuenta con un servicio de internet relativamente estable al que accede el personal",
        "estable_sin_acceso_personal": "El CDI cuenta con un servicio de internet relativamente estable al que accede el personal",
        "mala_calidad_con_acceso_personal": "El CDI cuenta con un servicio de internet de mala calidad al que accede el personal",
        "sin_servicio": "El CDI no cuenta con un servicio de internet",
    },
    "combustible_cocinar": {
        "gas_red": "Gas de red",
        "gas_granel_tubo_garrafa": "Gas a granel, tubo o en garrafa",
        "lena_o_carbon": "Leña o carbon",
        "no_utiliza": "No utiliza combustible para cocinar",
    },
    "plan_evacuacion_y_simulacros": {
        "protocolo_escrito_y_2_simulacros_o_mas": "Hay un protocolo de evacuación por escrito y realizan simulacros al menos dos veces por año .",
        "protocolo_escrito_y_simulacros_sin_frecuencia": "Hay un protocolo de evacuación por escrito y se realizan simulacros, aunque no con la frecuencia estipulada.",
        "protocolo_escrito_sin_simulacros": "Hay un protocolo de evacuación por escrito y no se realizan simulacros.",
        "practicas_informales_sin_protocolo": "Solo hay prácticas informales sin protocolos escritos.",
        "sin_protocolo": "No hay protocolo de evacuación.",
    },
    "cobertura_capacitacion_primeros_auxilios": {
        "todo_personal_certificado": "Todo el personal cuenta con capacitaciones en primeros auxilios certificadas (Cruz Roja, Bomberos, otros)",
        "entre_70_y_99": "Del 70% al 99% del personal cuenta con capacitaciones en primeros auxilios certificadas",
        "entre_40_y_69": "Del 40% al 69% del personal cuenta con capacitaciones en primeros auxilios certificadas",
        "menos_40": "Menos del 40% del personal cuenta con capacitaciones en primeros auxilios certificadas",
        "ninguno": "El personal no tiene capacitaciones en primeros auxilios certificadas",
    },
    "servicio_emergencia_medica": {
        "servicio_y_cobertura_identificada": "Tienen servicio de emergencia médica y la cobertura de cada niño está identificada.",
        "servicio_sin_cobertura_identificada": "Tienen servicio de emergencia médica, pero la cobertura de cada niño no está identificada.",
        "sin_servicio_con_cobertura_identificada": "No tienen servicio de emergencia médica, pero sí la cobertura identificada por niño.",
        "sin_servicio_con_cobertura_parcial": "No tienen servicio de emergencia médica y la cobertura está identificada sólo parcialmente.",
        "sin_servicio_y_sin_cobertura": "No tienen servicio de emergencia médica ni la cobertura de cada niño identificada.",
    },
    "calidad_elaboracion_menu": {
        "nutricionista_indicaciones_y_frescos": "El menú es elaborado por nutricionista, respetando indicaciones para la preparación de alimentos e incluyendo alimentos frescos o mínimamente procesados.",
        "nutricionista_indicaciones_a_veces_sin_frescos": "El menú es elaborado por nutricionista, respeta indicaciones, pero a veces no incluye alimentos frescos o mínimamente procesados.",
        "no_siempre_nutricionista_parcial_y_mixto": "El menú no siempre es elaborado por nutricionista; respeta parcialmente las indicaciones y combina alimentos frescos con procesados.",
        "sin_nutricionista_pocas_indicaciones_procesados": "El menú no es elaborado por nutricionista, respeta pocas indicaciones y predominan los alimentos procesados",
        "sin_nutricionista_ultraprocesados": "El menú no es elaborado por nutricionista y utiliza alimentos ultraprocesados",
    },
    "evaluacion_periodica_menu": {
        "periodica_todas_necesidades_y_patrones_y_personas": "El menú se evalúa periódicamente; contempla todas las necesidades nutricionales y patrones alimentarios; el personal está capacitado para su implementación.",
        "periodica_mayoria_necesidades_y_algunos_patrones": "El menú se evalúa periódicamente; contempla la mayoría de las necesidades nutricionales y algunos patrones alimentarios; el personal cuenta con capacitación básica.",
        "ocasional_parcial_y_capacitacion_esporadica": "El menú se evalúa de manera ocasional; contempla parcialmente las necesidades nutricionales y no incluye todos los patrones alimentarios; las capacitaciones al personal son esporádicas.",
        "rara_vez_limitada_sin_patrones": "El menú rara vez se evalúa; contempla de manera limitada las necesidades nutricionales y no considera patrones alimentarios; el personal carece de capacitación específica.",
        "no_evalua": "El menú no se evalúa; no contempla necesidades nutricionales ni patrones alimentarios; el personal no cuenta con capacitación.",
    },
    "cobertura_capacitacion_manipulacion_alimentos": {
        "todo_personal_anmat": "Todo el personal de cocina y comedor tiene capacitaciones y carnet emitido por ANMAT",
        "entre_70_y_99": "Entre el 70% y el 99% del personal tiene capacitaciones y carnet emitido por ANMAT",
        "entre_40_y_60": "Entre el 40% y el 60% del personal tiene capacitaciones y carnet emitido por ANMAT",
        "menos_40": "Menos del 40% del personal tiene capacitaciones y carnet emitido por ANMAT",
        "ninguno": "Ningún integrante del personal tiene capacitaciones ni carnet emitido por ANMAT",
    },
    "condiciones_almacenamiento_leche_humana": {
        "heladera_exclusiva_identificada_y_rotulada": "Se conserva en heladera exclusiva, identificada por niño/a y rotulada con fecha de extracción.",
        "heladera_compartida_sector_exclusivo_identificada_y_rotulada": "Se conserva en heladera compartida, en un sector exclusivo, identificada por niño/a y rotulada con fecha de extracción.",
        "heladera_exclusiva_identificada_sin_fecha": "Se conserva en heladera exclusiva, identificada por niño/a pero sin rotulación con fecha de extracción.",
        "heladera_compartida_sector_exclusivo_identificada_sin_fecha": "Se conserva en heladera compartida, en un sector exclusivo, identificada por niño/a pero sin rotulación con fecha de extracción.",
        "sin_espacio_exclusivo_ni_identificacion": "No se conserva en espacio exclusivo ni se identifica por niño/a.",
    },
    "acciones_sensibilizacion_lactancia": {
        "dos_o_mas_anuales_todas_familias": "Se realizan dos o más acciones anuales con alcance a todas las familias.",
        "una_anual_todas_familias": "Se realiza una acción anual con alcance a todas las familias.",
        "una_anual_alcance_limitado": "Se realizan acciones muy ocasionales y con alcance limitado a las familias.",
        "muy_ocasionales_limitadas": "Se realizan acciones muy ocasionales y con alcance limitado a las familias.",
        "ninguna": "No se realizan acciones de información y sensibilización sobre lactancia.",
    },
    "frecuencia_comunicacion_familias": {
        "reuniones_mensuales_y_canales_formales": "Se realizan reuniones mensuales con las familias y existen canales de comunicación formales (ej. cuaderno, cartelera, mensajes institucionales, plataforma).",
        "reuniones_trimestrales_y_canales_formales": "Se realizan reuniones trimestrales y existen canales formales de comunicación.",
        "reuniones_semestrales_y_algunos_canales": "Se realizan reuniones semestrales y solo algunos canales de comunicación formal funcionan regularmente.",
        "reuniones_anuales_sin_canales": "Se realizan reuniones anuales y no se dispone de canales formales de comunicación.",
        "sin_reuniones_ni_canales": "No se realizan reuniones con familias ni existen canales formales de comunicación.",
    },
    "frecuencia_talleres_crianza": {
        "trimestral_o_mas": "Se realizan al menos cada tres meses",
        "cada_4_a_6_meses": "Se realizan cada cuatro a seis meses",
        "una_vez_al_ano": "Se realiza al menos una vez al año",
        "esporadica": "Se realizan de manera esporádica, no todos los años",
        "no_se_realizan": "No se realizan talleres de crianza ni charlas con profesionales",
    },
    "nivel_trabajo_red": {
        "red_mapeo_mesas_trimestral_o_mas": "Trabaja en red con otras instituciones, cuenta con mapeo de actores y participa en mesas intersectoriales con reuniones trimestrales o más frecuentes.",
        "red_mapeo_mesas_semestral": "Trabaja en red con otras instituciones, cuenta con mapeo de actores y participa en mesas intersectoriales con reuniones semestrales.",
        "sin_red_con_mapeo_y_mesas": "No trabaja en red con otras instituciones, pero cuenta con mapeo de actores y participa en mesas intersectoriales al menos semestralmente.",
        "sin_red_sin_mesas_con_mapeo": "No trabaja en red con otras instituciones, no participa en mesas intersectoriales, pero cuenta con mapeo de actores",
        "sin_red_ni_mapeo": "No trabaja en red con instituciones ni cuenta con mapeo de actores de primera infancia.",
    },
    "protocolo_vulneracion_derechos": {
        "protocolo_revision_periodica_mayoria_conoce": "El CDI cuenta con protocolos específicos de intervención para la actuación ante sospecha o vulneración de derechos de los niños, que se revisan periódicamente y es conocido por más de la mitad del personal",
        "protocolo_revision_periodica_menos_mitad": "El CDI cuenta con protocolos específicos de intervención para la actuación ante sospecha o vulneración de derechos de los niños, que se revisan periódicamente y es conocido por menos de la mitad del personal",
        "protocolo_sin_revision_mayoria_conoce": "El CDI cuenta con protocolos específicos de intervención para la actuación ante sospecha o vulneración de derechos de los niños, que no tiene revisiones periódicas y es conocido por la más de la mitad del personal",
        "protocolo_sin_revision_menos_mitad": "El CDI cuenta con protocolos específicos de intervención para la actuación ante sospecha o vulneración de derechos de los niños, que no tiene revisiones periódicas y es conocido por menos de la mitad del personal",
        "no_existe": "El CDI no cuenta con protocolos específicos de intervención para la actuación ante sospecha o vulneración de derechos de los niños.",
    },
    "nivel_equipo_tecnico": {
        "completo_mas_20_horas": "El CDI cuenta con un equipo técnico completo y más de 20 horas semanales de trabajo.",
        "perfiles_diversos_15_19_horas": "El CDI cuenta con un equipo técnico con perfiles diversos (al menos dos de los sugeridos) y entre 15 y 19 horas semanales de trabajo.",
        "al_menos_un_perfil_o_10_14_horas": "El CDI cuenta con un equipo técnico con al menos un perfil profesional y/o con entre 10 y 14 horas semanales de trabajo.",
        "limitado_un_perfil_o_9_o_menos": "El CDI cuenta con un equipo técnico limitado (un solo perfil profesional) y/o 9 horas o menos de trabajo semanal.",
        "sin_equipo": "El CDI no cuenta con equipo técnico.",
    },
    "participantes_proyecto_socioeducativo": {
        "conduccion_sala_equipo_auxiliar_familias_comunidad": "Participan la conducción, el personal de sala, el equipo técnico, el personal auxiliar, las familias y actores comunitarios",
        "conduccion_sala_equipo_familias": "Participan la conducción, el personal de sala, el equipo técnico y las familias",
        "conduccion_sala_equipo": "Participan la conducción, el personal de sala y el equipo técnico",
        "conduccion_y_o_equipo": "Participan la conducción y/o el equipo técnico",
        "no_tienen": "No tienen proyecto socioeducativo institucional",
    },
    "planificacion_actividades_sala": {
        "semanal_en_marco_mensual_o_semestral_y_anual": "Se diseñan actividades semanales enmarcadas en planificaciones más amplias (mensuales o semestrales) y en un plan anual.",
        "semanal_en_marco_mensual_o_semestral_sin_anual": "Se diseñan actividades semanales enmarcadas en planificaciones más amplias (mensuales o semestrales), pero sin plan anual.",
        "semanal_en_marco_anual": "Se diseñan actividades semanales enmarcadas únicamente en un plan anual.",
        "solo_semanal": "Se diseñan únicamente actividades semanales, sin articulación con planificaciones más amplias.",
        "no_planifican": "No se realizan planificaciones de actividades.",
    },
    "planificacion_integral": {
        "intereses_caracteristicas_necesidades_e_integralidad": "Sí, se tienen en cuenta intereses, características, necesidades e integralidad de contenidos",
        "solo_intereses_caracteristicas_necesidades": "Solo se tienen en cuenta los intereses, características y necesidades del grupo",
        "solo_integralidad": "Solo se tiene en cuenta la integralidad de los contenidos",
        "ninguno": "No se tienen en cuenta los intereses, características, necesidades ni integralidad de los contenidos",
        "no_planifican": "No se realizan planificaciones",
    },
    "formacion_direccion_primera_infancia": {
        "titulo_superior_completo_especifico": "Posee título universitario o terciario completo de carreras específicas en primera infancia (ej. Educación Inicial, Trabajo Social, Psicología, Psicopedagogía, Estimulación Temprana u otras afines).",
        "carrera_75_o_mas_o_posgrados": "Posee al menos el 75% de una carrera superior en temáticas vinculadas a la infancia o cuenta con posgrados/cursos de especialización acreditados.",
        "cursando_formacion_formal": "Se encuentra actualmente cursando una carrera o formación formal relacionada con la primera infancia.",
        "solo_cursos_cortos": "Ha realizado solo cursos o capacitaciones cortas no sistemáticas en temas de infancia.",
        "sin_formacion": "No posee formación superior ni capacitaciones en temáticas vinculadas a la infancia.",
    },
    "cobertura_duplas_pedagogicas": {
        "todas": "Sí, en todas las salas trabajan en dupla",
        "mayoria": "Sí, en la mayoría de las salas trabajan en dupla",
        "algunas": "Solo en algunas salas trabajan en dupla",
        "muy_pocas": "Muy pocas salas trabajan en duplas",
        "ninguna": "No se trabaja en duplas en ninguna sala",
    },
    "cobertura_educadora_titulo_habilitante": {
        "todas": "Sí, en todas las salas una educadora cuenta cn título habilitante de nivel inicial",
        "mayoria": "Sí, en la mayoría de las salas una educadora cuenta con título habilitante de nivel inicial",
        "algunas": "Solo en algunas salas una educadora cuenta con título habilitante de nivel inicial",
        "muy_pocas": "Muy pocas salas tienen una educadora con título habilitante",
    },
    "cobertura_formacion_auxiliares": {
        "todos": "Todos los auxiliares cuentan con formación específica en primera infancia",
        "mayoria": "La mayoría de los auxiliares cuentan con formación específica en primera infancia",
        "algunos": "Algunos auxiliares cuentan con formación específica en primera infancia",
        "muy_pocos": "Muy pocos auxiliares cuentan con formación específica en primera infancia",
        "ninguno": "Ningún auxiliar cuenta con formación en primera infancia",
    },
    "modalidad_contratacion_principal": {
        "permanente": "La mayor proporción de personal tiene Contratación permanente",
        "temporal": "La mayor proporción de personal tiene Contratación temporal",
        "beca_o_pasantia": "La mayor proporción de personal tiene Beca o pasantía",
        "programa_social_insercion": "La mayor proporción de personal tiene Programa social de inserción laboral",
        "voluntario_u_otra": "La mayor proporción de personal es voluntario u otra modalidad",
    },
}

SOBREESCRITURAS_ETIQUETAS_OPCIONES_MULTIPLES = {
    "items_protocolo_salud": {
        "emergencias_medicas": "Actuación frente a emergencias médicas",
        "suministro_medicamentos": "Suministro de medicamentos",
        "sintomas_enfermedad": "Pautas de actuación frente a síntomas de enfermedad",
        "reintegro_post_enfermedad": "Pautas para el reintegro de niños después de una enfermedad",
        "conocido_por_todo_el_personal": "El protocolo es conocido por todo el personal",
        "no_existe_protocolo_escrito": "No existe protocolo escrito",
    },
}

SOBREESCRITURAS_ETIQUETAS_CAMPOS = {
    "fecha_relevamiento": "Fecha de Relevamiento",
    "uso_exclusivo_espacio": "Uso Exclusivo del Espacio: ¿El lugar físico en donde funciona el CDI es compartido con otras actividades, personas u organizaciones?",
    "acceso_energia": "Acceso a Energía: ¿El CDI tiene electricidad? (marcar la opción que corresponda)",
    "seguridad_electrica": "Seguridad Eléctrica: ¿Las instalaciones eléctricas cumplen con la normativa de seguridad y se verifican periódicamente?",
    "acceso_agua": "Acceso a Agua: ¿El CDI tiene agua?",
    "fuente_agua_segura_consumo": "Acceso a Agua segura para consumo: ¿Cuál es la fuente de agua utilizada para consumo en el CDI?",
    "eliminacion_excretas": "Eliminación de excretas - El desagüe del CDI es:",
    "acceso_internet_personal": "Acceso a internet: ¿El CDI tiene acceso a internet y es compartido por el personal?",
    "plan_evacuacion_y_simulacros": "Plan de evacuación ¿El CDI cuenta con plan de evacuación y realiza simulacros?",
    "cobertura_capacitacion_primeros_auxilios": "Capacitación en primeros auxilios ¿Cuenta todo el personal del CDI con capacitación certificada en primeros auxilios (Cruz Roja, Bomberos, otros)?",
    "servicio_emergencia_medica": "Servicio de emergencia médica ¿El CDI cuenta con un servicio de emergencia médica (a domicilio pago o línea prioritaria SAME/SEM) y tiene identificada la cobertura correspondiente a cada niño?",
    "items_protocolo_salud": "Existencia de protocolo de actuación en salud. ¿El CDI cuenta con un protocolo escrito que contemple los siguientes aspectos? (Marcar todas las opciones que correspondan).",
    "prestaciones_alimentarias": "Prestación Alimentaria del CDI",
    "calidad_elaboracion_menu": "Elaboración de alimentos : En referencia al menú, ¿cómo se elabora y qué tipo de alimentos incluye?",
    "evaluacion_periodica_menu": "Evaluación periódica del menú: ¿El CDI realiza evaluaciones periódicas del menú y contempla las necesidades nutricionales (celiaquía, bajo peso, obesidad, diabetes, etc.) y los distintos patrones alimentarios (incluyendo opciones basadas en plantas) de los niños y niñas?",
    "cobertura_capacitacion_manipulacion_alimentos": "Capacitaciones en manipulación de alimentos ¿El personal de cocina y comedor cuenta con capacitaciones en manipulación de alimentos y carnet emitido por ANMAT?",
    "condiciones_almacenamiento_leche_humana": "Condiciones para el almacenamiento de leche humana ¿El CDI cuenta con condiciones adecuadas para la conservación de leche humana?",
    "acciones_sensibilizacion_lactancia": "Acciones de información y sensibilización de la lactancia ¿Con qué frecuencia y alcance el CDI realiza acciones de información y sensibilización sobre lactancia (talleres, reuniones, folletería u otras)?",
    "tiene_personal_entrada_salida": "¿Hay personal encargado para la entrada y salida de los niños y niñas al CDI?",
    "frecuencia_comunicacion_familias": "Comunicación con las familias ¿Con qué frecuencia el CDI mantiene reuniones con las familias y dispone de canales formales de comunicación?",
    "frecuencia_talleres_crianza": "Talleres de crianza, charlas con profesionales ¿Con qué frecuencia el CDI ofrece talleres de crianza o charlas con profesionales dirigidas a las familias?",
    "realiza_acciones_promocion_acceso_derechos": "Acciones de Promoción y acceso a derechos: ¿El CDI realiza acciones para facilitar el acceso de los/as niños/as y sus familias a derechos y políticas/programas de promoción y protección social (identidad, AUH/AUD/AUE, pensiones, salud, discapacidad, entre otros)?",
    "realiza_acciones_acompanamiento_vulneracion_derechos": "Acciones de acompañamiento ante vulneración de derechos ¿El CDI realiza acciones de acompañamiento a las familias ante situaciones de vulneración de derechos (violencia intrafamiliar, judicialización de conflictos familiares, abuso sexual, entre otras)?",
    "nivel_trabajo_red": "Trabajo en red ¿El CDI trabaja en red con otras instituciones, cuenta con un mapeo de actores de primera infancia y participa en mesas intersectoriales?",
    "protocolo_vulneracion_derechos": "Protocolo frente a vulneración de derechos ¿El CDI cuenta con protocolos específicos para la actuación ante sospecha o vulneración de derechos de los niños, se revisan periódicamente y son conocidos por el personal?",
    "nivel_equipo_tecnico": "¿El CDI cuenta con un equipo técnico completo (trabajador/a social, psicólogo/a, psicopedagogo/a o estimulador/a temprano) y cuántas horas semanales de trabajo dedica?",
    "frecuencia_registro_desarrollo_nino": "desarrollo del niño/a. Registro y frecuencia de actualización ¿Con qué frecuencia el CDI registra y actualiza la información sobre el desarrollo de cada niño/a?",
    "frecuencia_registro_informacion_familiar": "Información familiar. Registro y frecuencia de actualización ¿Con qué frecuencia el CDI registra y actualiza la información familiar de cada niño/a?",
    "frecuencia_registro_salud_vacunas": "Información de controles de salud y vacunas. Registro y frecuencia de actualización ¿Con qué frecuencia el CDI registra y actualiza la información sobre los controles de salud y vacunas de cada niño/a?",
    "participantes_proyecto_socioeducativo": "Proyecto socioeducativo institucional ¿Quiénes participan en la elaboración del proyecto socioeducativo institucional del CDI?",
    "planificacion_actividades_sala": "Existencia de planificación de actividades en sala ¿Cómo se planifican las actividades en sala dentro del CDI?",
    "planificacion_integral": "Planificación integral ¿Las planificaciones de actividades en sala se realizan teniendo en cuenta los intereses, características y necesidades del grupo como así también la integralidad de los contenidos?",
    "formacion_direccion_primera_infancia": "Formación de la dirección/coordinación en primera infancia ¿La dirección o coordinación del CDI cuenta con formación superior en temáticas vinculadas a la primera infancia?",
    "cobertura_duplas_pedagogicas": "Trabajo en duplas en sala. ¿En todas las salas del CDI se trabaja con duplas pedagógicas a cargo?",
    "cobertura_educadora_titulo_habilitante": "Formación habilitante del personal de sala. ¿Al menos una educadora cuenta con título habilitante de nivel inicial?",
    "cobertura_formacion_auxiliares": "Formación de auxiliares en primera infancia. ¿Los auxiliares de sala cuentan con formación específica en primera infancia?",
    "modalidad_contratacion_principal": "Modalidad de contratación ¿Cuál es la principal modalidad de contratación del personal del CDI?",
    "frecuencia_reuniones_personal_sala": "¿Con qué frecuencia se realizan reuniones entre el personal de sala, la coordinación y/o el equipo técnico del CDI?",
    "frecuencia_reuniones_personal_no_docente": "¿Con qué frecuencia se realizan reuniones entre el personal no docente del CDI (cocina, limpieza, mantenimiento, etc.) y la coordinación?",
    "frecuencia_reuniones_todo_personal": "¿Con qué frecuencia se realizan reuniones entre todo el personal?",
    "instancias_capacitacion_todo_personal_ultimos_3_anios": "En los últimos 3 años, ¿cuántas instancias de capacitación ha promovido el CDI para todo su personal?",
    "instancias_capacitacion_personal_sala_ultimos_3_anios": "En los últimos 3 años, ¿cuántas instancias de capacitación ha promovido el CDI para el personal de sala?",
    "instancias_capacitacion_equipo_tecnico_ultimos_3_anios": "En los últimos 3 años, ¿cuántas instancias de capacitación ha promovido el CDI para el equipo técnico?",
    "instancias_capacitacion_personal_cocina_ultimos_3_anios": "En los últimos 3 años, ¿cuántas instancias de capacitación ha promovido el CDI para el personal de cocina y comedor?",
    "combustible_cocinar": "Para cocinar, el CDI utiliza principalmente: (marcar la opción que corresponda)",
    "tiene_espacio_exterior": "Espacio exterior: ¿El CDI cuenta con espacio exterior donde puedan realizarse actividades con los niños (patio, jardín, etc.)?",
    "tiene_juegos_exteriores": "Juegos infantiles de exterior ¿El espacio cuenta con juegos infantiles de exterior (hamacas, toboganes, etc.)?",
    "modalidad_gestion": "Modalidad de Gestión",
    "modalidad_tenencia": "Modalidad de Tenencia",
}
