"""Definiciones compartidas para FormularioCDI."""

from __future__ import annotations

from centrodeinfancia.formulario_cdi_text_overrides import (
    CHOICE_LABEL_OVERRIDES,
    FIELD_LABEL_OVERRIDES,
    MULTI_CHOICE_LABEL_OVERRIDES,
)

def humanize_code(value: str) -> str:
    """Convierte códigos internos en etiquetas legibles."""
    text = str(value or "").replace("_", " ")
    replacements = {
        "nino": "niño",
        "nina": "niña",
        "ninos": "niños",
        "ninas": "niñas",
        "ano": "año",
        "anos": "años",
        "tecnico": "técnico",
        "dias": "días",
    }
    for source, target in replacements.items():
        text = text.replace(source, target)
    return text.capitalize()


MONTH_OPTIONS = [
    ("ENE", "ENE"),
    ("FEB", "FEB"),
    ("MAR", "MAR"),
    ("ABR", "ABR"),
    ("MAY", "MAY"),
    ("JUN", "JUN"),
    ("JUL", "JUL"),
    ("AGO", "AGO"),
    ("SET", "SET"),
    ("OCT", "OCT"),
    ("NOV", "NOV"),
    ("DIC", "DIC"),
]

WEEKDAY_OPTIONS = [
    ("LUNES", "Lunes"),
    ("MARTES", "Martes"),
    ("MIERCOLES", "Miercoles"),
    ("JUEVES", "Jueves"),
    ("VIERNES", "Viernes"),
    ("SABADO", "Sabado"),
    ("DOMINGO", "Domingo"),
]

ROOM_AGE_GROUP_OPTIONS = [
    ("lactantes", "Lactantes"),
    ("deambuladores", "Deambuladores"),
    ("dos_anos", "Dos años"),
    ("tres_anos", "Tres años"),
    ("cuatro_anos", "Cuatro Años"),
    ("multiedad", "Multiedad"),
]

WAITLIST_AGE_GROUP_OPTIONS = [
    ("lactantes", "Lactantes"),
    ("deambuladores", "Deambuladores"),
    ("un_ano", "Un año"),
    ("dos_anos", "dos años"),
    ("tres_anos", "tres años"),
    ("cuatro_anos", "cuatro años"),
]

ARTICULATION_INSTITUTION_OPTIONS = [
    ("servicio_promocion_proteccion_local", "Servicio de promocion y proteccion local"),
    ("servicio_promocion_proteccion_zonal", "Servicio de promocion y proteccion zonal"),
    ("salud_caps_hospital_municipal", "Salud CAPS/Hospital municipal"),
    ("salud_hospital_provincial", "Salud hospital provincial"),
    ("educacion_jardin_maternal", "Educacion jardin maternal"),
    ("educacion_escuela_primaria", "Educacion escuela primaria"),
    ("desarrollo_social_municipal", "Desarrollo social municipal"),
    ("desarrollo_social_provincial", "Desarrollo social provincial"),
    ("justicia_juzgado", "Justicia/Juzgado"),
    ("cultura_juegotecas", "Cultura/Juegotecas"),
    ("cultura_espacios_comunitarios", "Cultura/Espacios comunitarios"),
    ("cultura_iglesias", "Cultura/Iglesias"),
    ("seguridad_policia", "Seguridad/Policia"),
    ("seguridad_social_anses", "Seguridad social/ANSES"),
    ("identidad_renaper", "Identidad/RENAPER"),
]


def _options(*values: str) -> list[tuple[str, str]]:
    return [(value, humanize_code(value)) for value in values]


CHOICE_FIELDS = {
    "workday_type": [
        ("simple_single_shift", "Jornada simple"),
        ("multiple_simple_shifts", "Dos o mas jornadas simples"),
        ("full_double_same_group", "Jornada completa/doble"),
        ("other", "Otra"),
    ],
    "management_mode": _options(
        "gobierno_nacional",
        "gobierno_provincial",
        "gobierno_municipal",
        "ong",
        "cogestion_provincial_municipal",
        "cogestion_ong_provincial_municipal",
        "otra",
    ),
    "tenure_mode": _options(
        "propio",
        "alquilado",
        "cedido_gubernamental",
        "cedido_privado",
        "comodato",
        "ocupado_de_hecho",
        "otra",
    ),
    "electricity_access": _options(
        "red_formal",
        "red_informal",
        "generacion_propia_motor",
        "generacion_propia_otros",
        "sin_electricidad",
    ),
    "electrical_safety": _options(
        "cumple_y_revision_mayor_a_un_ano",
        "cumple_y_revision_anual",
        "cumple_sin_revisiones",
        "cumple_solo_zonas_ninos_sin_revisiones",
        "no_cumple_sin_revisiones",
    ),
    "water_access": _options(
        "caneria_dentro_cdi",
        "fuera_cdi_dentro_terreno",
        "fuera_del_terreno",
        "sin_agua",
    ),
    "safe_drinking_water_source": _options(
        "red_o_embotellada_segura",
        "pozo_analisis_vigente",
        "pozo_analisis_vencido_o_sin_control",
        "otra_con_proceso_sin_garantia_formal",
        "otra_sin_info_potabilizacion",
    ),
    "excreta_disposal": _options(
        "red_publica_cloaca",
        "camara_septica_pozo_ciego",
        "solo_pozo_ciego",
        "hoyo_tierra",
        "sin_sistema",
    ),
    "first_aid_kit_status": [
        (
            "completo_todas_salas_ok_vigente_fuera_alcance",
            "Cuentan con botiquín completo de primeros auxilios en todas las salas, en buena conservación y con insumos dentro de la fecha de vencimiento; fuera del alcance de los niños",
        ),
        (
            "incompleto_todas_salas_ok_vigente_fuera_alcance",
            "Cuentan con botiquín incompleto de primeros auxilios en todas las salas, en buena conservación y con insumos dentro de la fecha de vencimiento; fuera del alcance de los niños",
        ),
        (
            "unico_completo_compartido_ok_vigente_fuera_alcance",
            "Cuentan con un único botiquín completo de primeros auxilios compartido por las salas, en buena conservación y con insumos dentro de la fecha de vencimiento; fuera del alcance de los niños",
        ),
        (
            "incompleto_compartido_o_mal_estado_o_vencido",
            "Cuentan con botiquín incompleto de primeros auxilios compartido por las salas y/o los insumos se encuentran en mala conservación y fuera de la fecha de vencimiento",
        ),
        (
            "no_tienen_o_al_alcance_ninos",
            "No cuentan con botiquín de primeros auxilios o el botiquín está al alcance de los niños",
        ),
    ],
    "internet_access_quality_staff": _options(
        "alta_velocidad_con_acceso_personal",
        "estable_con_acceso_personal",
        "estable_sin_acceso_personal",
        "mala_calidad_con_acceso_personal",
        "sin_servicio",
    ),
    "has_kitchen_space": [
        ("si", "Si"),
        ("no", "No"),
        ("no_sabe_no_responde", "No sabe / No responde"),
    ],
    "cooking_fuel": _options(
        "gas_red",
        "gas_granel_tubo_garrafa",
        "electricidad",
        "lena_o_carbon",
        "no_utiliza",
    ),
    "has_outdoor_space": [("si", "Si"), ("no", "No"), ("no_responde", "No responde")],
    "has_outdoor_playground": [
        ("si", "Si"),
        ("no", "No"),
        ("no_responde", "No responde"),
    ],
    "evacuation_plan_and_drills": _options(
        "protocolo_escrito_y_2_simulacros_o_mas",
        "protocolo_escrito_y_simulacros_sin_frecuencia",
        "protocolo_escrito_sin_simulacros",
        "practicas_informales_sin_protocolo",
        "sin_protocolo",
    ),
    "first_aid_training_coverage": _options(
        "todo_personal_certificado",
        "entre_70_y_99",
        "entre_40_y_69",
        "menos_40",
        "ninguno",
    ),
    "emergency_medical_service": _options(
        "servicio_y_cobertura_identificada",
        "servicio_sin_cobertura_identificada",
        "sin_servicio_con_cobertura_identificada",
        "sin_servicio_con_cobertura_parcial",
        "sin_servicio_y_sin_cobertura",
    ),
    "menu_preparation_quality": _options(
        "nutricionista_indicaciones_y_frescos",
        "nutricionista_indicaciones_a_veces_sin_frescos",
        "no_siempre_nutricionista_parcial_y_mixto",
        "sin_nutricionista_pocas_indicaciones_procesados",
        "sin_nutricionista_ultraprocesados",
    ),
    "menu_periodic_evaluation": _options(
        "periodica_todas_necesidades_y_patrones_y_personal_capacitado",
        "periodica_mayoria_necesidades_y_algunos_patrones",
        "ocasional_parcial_y_capacitacion_esporadica",
        "rara_vez_limitada_sin_patrones",
        "no_evalua",
    ),
    "food_handling_training_coverage": _options(
        "todo_personal_anmat",
        "entre_70_y_99",
        "entre_40_y_60",
        "menos_40",
        "ninguno",
    ),
    "breast_milk_storage_conditions": _options(
        "heladera_exclusiva_identificada_y_rotulada",
        "heladera_compartida_sector_exclusivo_identificada_y_rotulada",
        "heladera_exclusiva_identificada_sin_fecha",
        "heladera_compartida_sector_exclusivo_identificada_sin_fecha",
        "sin_espacio_exclusivo_ni_identificacion",
    ),
    "breastfeeding_awareness_actions": _options(
        "dos_o_mas_anuales_todas_familias",
        "una_anual_todas_familias",
        "una_anual_alcance_limitado",
        "muy_ocasionales_limitadas",
        "ninguna",
    ),
    "has_waitlist_registry": [("si", "Si"), ("no", "No"), ("ns_nc", "NS/NC")],
    "has_entry_exit_staff": [("si", "Si"), ("no", "No"), ("ns_nc", "NS/NC")],
    "family_communication_frequency": _options(
        "reuniones_mensuales_y_canales_formales",
        "reuniones_trimestrales_y_canales_formales",
        "reuniones_semestrales_y_algunos_canales",
        "reuniones_anuales_sin_canales",
        "sin_reuniones_ni_canales",
    ),
    "parenting_workshops_frequency": _options(
        "trimestral_o_mas",
        "cada_4_a_6_meses",
        "una_vez_al_ano",
        "esporadica",
        "no_se_realizan",
    ),
    "actions_promoting_rights_access": [("si", "Si"), ("no", "No"), ("ns_nc", "NS/NC")],
    "actions_against_rights_violations": [
        ("si", "Si"),
        ("no", "No"),
        ("ns_nc", "NS/NC"),
    ],
    "networking_level": _options(
        "red_mapeo_mesas_trimestral_o_mas",
        "red_mapeo_mesas_semestral",
        "sin_red_con_mapeo_y_mesas",
        "sin_red_sin_mesas_con_mapeo",
        "sin_red_ni_mapeo",
    ),
    "rights_violation_protocol": _options(
        "protocolo_revision_periodica_mayoria_conoce",
        "protocolo_revision_periodica_menos_mitad",
        "protocolo_sin_revision_mayoria_conoce",
        "protocolo_sin_revision_menos_mitad",
        "no_existe",
    ),
    "technical_team_level": _options(
        "completo_mas_20_horas",
        "perfiles_diversos_15_19_horas",
        "al_menos_un_perfil_o_10_14_horas",
        "limitado_un_perfil_o_9_o_menos",
        "sin_equipo",
    ),
    "child_development_record_frequency": _options(
        "mensual",
        "trimestral",
        "semestral",
        "anual",
        "no_registra",
    ),
    "family_info_record_frequency": _options(
        "mensual",
        "trimestral",
        "semestral",
        "anual",
        "no_registra",
    ),
    "health_vaccine_record_frequency": _options(
        "mensual",
        "trimestral",
        "semestral",
        "anual",
        "no_registra",
    ),
    "socioeducational_project_participants": _options(
        "conduccion_sala_equipo_auxiliar_familias_comunidad",
        "conduccion_sala_equipo_familias",
        "conduccion_sala_equipo",
        "conduccion_y_o_equipo",
        "no_tienen",
    ),
    "classroom_activity_planning": _options(
        "semanal_en_marco_mensual_o_semestral_y_anual",
        "semanal_en_marco_mensual_o_semestral_sin_anual",
        "semanal_en_marco_anual",
        "solo_semanal",
        "no_planifican",
    ),
    "integral_planning": _options(
        "intereses_caracteristicas_necesidades_e_integralidad",
        "solo_intereses_caracteristicas_necesidades",
        "solo_integralidad",
        "ninguno",
        "no_planifican",
    ),
    "direction_training_in_early_childhood": _options(
        "titulo_superior_completo_especifico",
        "carrera_75_o_mas_o_posgrados",
        "cursando_formacion_formal",
        "solo_cursos_cortos",
        "sin_formacion",
    ),
    "pedagogical_pairs_coverage": _options(
        "todas",
        "mayoria",
        "algunas",
        "muy_pocas",
        "ninguna",
    ),
    "qualified_teacher_coverage": _options(
        "todas",
        "mayoria",
        "algunas",
        "muy_pocas",
    ),
    "assistant_training_coverage": _options(
        "todos",
        "mayoria",
        "algunos",
        "muy_pocos",
        "ninguno",
    ),
    "main_hiring_mode": _options(
        "permanente",
        "temporal",
        "beca_o_pasantia",
        "programa_social_insercion",
        "voluntario_u_otra",
    ),
    "meetings_teaching_staff_frequency": _options(
        "mensual",
        "trimestral",
        "semestral",
        "anual",
        "no_se_realizan",
    ),
    "meetings_non_teaching_staff_frequency": _options(
        "mensual",
        "trimestral",
        "semestral",
        "anual",
        "no_se_realizan",
    ),
    "meetings_all_staff_frequency": _options(
        "mensual",
        "trimestral",
        "semestral",
        "anual",
        "no_se_realizan",
    ),
    "training_instances_all_staff_last_3y": _options(
        "seis_o_mas",
        "cuatro_o_cinco",
        "dos_o_tres",
        "una",
        "ninguna",
    ),
    "training_instances_room_staff_last_3y": _options(
        "seis_o_mas",
        "cuatro_o_cinco",
        "dos_o_tres",
        "una",
        "ninguna",
    ),
    "training_instances_technical_team_last_3y": _options(
        "seis_o_mas",
        "cuatro_o_cinco",
        "dos_o_tres",
        "una",
        "ninguna",
    ),
    "training_instances_kitchen_staff_last_3y": _options(
        "seis_o_mas",
        "cuatro_o_cinco",
        "dos_o_tres",
        "una",
        "ninguna",
        "no_aplica",
    ),
}

MULTI_CHOICE_FIELDS = {
    "operation_months": MONTH_OPTIONS,
    "operation_days": WEEKDAY_OPTIONS,
    "health_protocol_items": _options(
        "emergencias_medicas",
        "suministro_medicamentos",
        "sintomas_enfermedad",
        "reintegro_post_enfermedad",
        "conocido_por_todo_el_personal",
        "no_existe_protocolo_escrito",
    ),
    "meals_provided": _options(
        "desayuno",
        "almuerzo",
        "merienda",
        "pre_cena",
        "cena",
        "otra",
        "ninguna",
    ),
}

BOOLEAN_LABELS = {
    "exclusive_space_use": (
        "Si, compartido con otras actividades/personas/organizaciones",
        "No",
    ),
}

FIELD_LABELS = {
    "survey_date": "Fecha",
    "respondent_full_name": "Nombre y apellido de quien responde el cuestionario",
    "respondent_role": "Funcion que cumple",
    "respondent_email": "Mail de contacto",
    "cdi_name": "Nombre del Centro de Desarrollo Infantil",
    "cdi_code": "Identificador interno del CDI",
    "cdi_province": "Provincia del CDI",
    "cdi_department": "Departamento del CDI",
    "cdi_municipality": "Municipio del CDI",
    "cdi_locality": "Localidad del CDI",
    "cdi_street": "Calle del CDI",
    "cdi_door_number": "Numeracion de puerta del CDI",
    "cdi_postal_code": "Codigo postal del CDI",
    "cdi_geo_latitude": "Coordenada geografica latitud",
    "cdi_geo_longitude": "Coordenada geografica longitud",
    "cdi_phone": "Telefono del CDI",
    "cdi_email": "Mail del CDI",
    "cdi_contact_first_name": "Referente del CDI nombre/s",
    "cdi_contact_last_name": "Referente del CDI apellido/s",
    "cdi_contact_phone": "Referente del CDI telefono",
    "cdi_contact_email": "Referente del CDI mail",
    "operation_months": "Meses de funcionamiento del CDI",
    "operation_days": "Días de funcionamiento del CDI",
    "opening_time": "Horario de apertura",
    "closing_time": "Horario de cierre",
    "workday_type": "Tipo de jornada",
    "workday_type_other": "Otra jornada - especificar",
    "total_children_count": "Cantidad de niños que asisten en total",
    "total_staff_count": "Cantidad de personal en total",
    "management_mode": "Modalidad de gestion",
    "management_mode_other": "Modalidad de gestion - otra",
    "managing_organization_name": "Denominacion del organismo u organizacion",
    "managing_organization_cuit": "CUIT del organismo",
    "org_province": "Provincia del organismo",
    "org_department": "Departamento del organismo",
    "org_municipality": "Municipio del organismo",
    "org_locality": "Localidad del organismo",
    "org_street": "Calle",
    "org_number": "Numeracion",
    "org_postal_code": "Codigo postal",
    "org_building": "Edificio",
    "org_floor": "Piso",
    "org_apartment": "Departamento",
    "org_office": "Oficina",
    "org_phone": "Telefono",
    "org_email": "Mail",
    "org_contact_first_name": "Referente institucional nombre/s",
    "org_contact_last_name": "Referente institucional apellido/s",
    "org_contact_phone": "Referente institucional telefono",
    "org_contact_email": "Referente institucional mail",
    "tenure_mode": "Modalidad de tenencia",
    "tenure_mode_other": "Modalidad de tenencia - otra",
    "exclusive_space_use": "Uso exclusivo del espacio",
    "room_count_excluding_service_areas": "Cantidad de ambientes (sin cocina/banos/pasillos/garajes)",
    "electricity_access": "Acceso a energia",
    "electrical_safety": "Seguridad electrica",
    "water_access": "Acceso a agua",
    "safe_drinking_water_source": "Acceso a agua segura para consumo",
    "excreta_disposal": "Eliminacion de excretas",
    "has_fire_extinguishers_current": "Existencia de extintores",
    "first_aid_kit_status": "Existencia de Botiquín",
    "has_working_computer": "Existencia de computadora",
    "internet_access_quality_staff": "Acceso a internet",
    "has_kitchen_space": "Espacio de cocina",
    "cooking_fuel": "Combustible usado para cocinar",
    "has_outdoor_space": "Espacio exterior",
    "has_outdoor_playground": "Juegos infantiles de exterior",
    "evacuation_plan_and_drills": "Plan de evacuacion",
    "first_aid_training_coverage": "Capacitacion en primeros auxilios",
    "emergency_medical_service": "Servicio de emergencia medica + cobertura identificada",
    "health_protocol_items": "Protocolo de actuación en salud",
    "meals_provided": "Alimentacion",
    "meals_provided_other": "Otra comida - especificar",
    "menu_preparation_quality": "Elaboracion de alimentos",
    "menu_periodic_evaluation": "Evaluacion periodica del menu",
    "food_handling_training_coverage": "Capacitaciones en manipulacion de alimentos",
    "breast_milk_storage_conditions": "Condiciones para almacenamiento de leche humana",
    "breastfeeding_awareness_actions": "Acciones de informacion y sensibilizacion de lactancia",
    "has_waitlist_registry": "Existe registro de lista de espera",
    "has_admission_prioritization_tool": "Existe instrumento de priorización de ingreso de los niños/as",
    "children_with_disabilities_count": "Cantidad de niños con discapacidad",
    "children_specific_ethnicity_count": "Cantidad de niños de alguna etnia en particular",
    "has_entry_exit_staff": "Personal encargado para entrada y salida",
    "family_communication_frequency": "Comunicacion con las familias",
    "parenting_workshops_frequency": "Talleres de crianza / charlas con profesionales",
    "actions_promoting_rights_access": "Acciones de promocion y acceso a derechos",
    "actions_against_rights_violations": "Acciones de acompanamiento ante vulneracion de derechos",
    "networking_level": "Trabajo en red",
    "rights_violation_protocol": "Protocolo frente a vulneracion de derechos",
    "technical_team_level": "Equipo tecnico",
    "child_development_record_frequency": "Registro de desarrollo del niño/a",
    "family_info_record_frequency": "Registro de informacion familiar",
    "health_vaccine_record_frequency": "Registro de controles de salud y vacunas",
    "socioeducational_project_participants": "Proyecto socioeducativo institucional",
    "classroom_activity_planning": "Existencia de planificacion de actividades en sala",
    "integral_planning": "Planificacion integral",
    "direction_training_in_early_childhood": "Formacion de la direccion/coordinacion en primera infancia",
    "pedagogical_pairs_coverage": "Trabajo en duplas en sala",
    "qualified_teacher_coverage": "Formacion habilitante del personal de sala",
    "assistant_training_coverage": "Formacion de auxiliares en primera infancia",
    "main_hiring_mode": "Modalidad de contratacion",
    "meetings_teaching_staff_frequency": "Reuniones entre personal de sala, coordinacion y/o equipo tecnico",
    "meetings_non_teaching_staff_frequency": "Reuniones entre personal no docente y coordinacion",
    "meetings_all_staff_frequency": "Reuniones entre todo el personal",
    "training_instances_all_staff_last_3y": "Instancias de capacitacion para todo el personal en ultimos 3 anos",
    "training_instances_room_staff_last_3y": "Instancias de capacitacion para personal de sala en ultimos 3 anos",
    "training_instances_technical_team_last_3y": "Instancias de capacitacion para equipo tecnico en ultimos 3 anos",
    "training_instances_kitchen_staff_last_3y": "Instancias de capacitacion para cocina/comedor en ultimos 3 anos",
}

for field_name, label_overrides in CHOICE_LABEL_OVERRIDES.items():
    if field_name in CHOICE_FIELDS:
        CHOICE_FIELDS[field_name] = [
            (value, label_overrides.get(value, label))
            for value, label in CHOICE_FIELDS[field_name]
        ]

for field_name, label_overrides in MULTI_CHOICE_LABEL_OVERRIDES.items():
    if field_name in MULTI_CHOICE_FIELDS:
        MULTI_CHOICE_FIELDS[field_name] = [
            (value, label_overrides.get(value, label))
            for value, label in MULTI_CHOICE_FIELDS[field_name]
        ]

FIELD_LABELS.update(FIELD_LABEL_OVERRIDES)

FORMULARIO_CDI_SECTIONS = [
    {
        "id": "metadata",
        "title": "Metadatos del relevamiento",
        "fields": [
            "survey_date",
            "respondent_full_name",
            "respondent_role",
            "respondent_email",
        ],
    },
    {
        "id": "general_characterization",
        "title": "Caracterizacion general",
        "fields": [
            "cdi_name",
            "cdi_code",
            "cdi_province",
            "cdi_department",
            "cdi_municipality",
            "cdi_locality",
            "cdi_street",
            "cdi_door_number",
            "cdi_postal_code",
            "cdi_geo_latitude",
            "cdi_geo_longitude",
            "cdi_phone",
            "cdi_email",
            "cdi_contact_first_name",
            "cdi_contact_last_name",
            "cdi_contact_phone",
            "cdi_contact_email",
            "operation_months",
            "operation_days",
            "opening_time",
            "closing_time",
            "workday_type",
            "workday_type_other",
            "total_children_count",
            "total_staff_count",
        ],
    },
    {
        "id": "pfpi_participation",
        "title": "CDI que participan del PFPI",
        "fields": [
            "management_mode",
            "management_mode_other",
            "managing_organization_name",
            "managing_organization_cuit",
            "org_province",
            "org_department",
            "org_municipality",
            "org_locality",
            "org_street",
            "org_number",
            "org_postal_code",
            "org_building",
            "org_floor",
            "org_apartment",
            "org_office",
            "org_phone",
            "org_email",
            "org_contact_first_name",
            "org_contact_last_name",
            "org_contact_phone",
            "org_contact_email",
            "tenure_mode",
            "tenure_mode_other",
            "exclusive_space_use",
            "room_count_excluding_service_areas",
        ],
    },
    {
        "id": "infrastructure_services",
        "title": "Infraestructura y servicios",
        "fields": [
            "electricity_access",
            "electrical_safety",
            "water_access",
            "safe_drinking_water_source",
            "excreta_disposal",
            "has_fire_extinguishers_current",
            "first_aid_kit_status",
            "has_working_computer",
            "internet_access_quality_staff",
            "has_kitchen_space",
            "cooking_fuel",
            "has_outdoor_space",
            "has_outdoor_playground",
            "evacuation_plan_and_drills",
            "first_aid_training_coverage",
            "emergency_medical_service",
            "health_protocol_items",
        ],
    },
    {
        "id": "food_module",
        "title": "Alimentacion",
        "fields": [
            "meals_provided",
            "meals_provided_other",
            "menu_preparation_quality",
            "menu_periodic_evaluation",
            "food_handling_training_coverage",
            "breast_milk_storage_conditions",
            "breastfeeding_awareness_actions",
        ],
    },
    {
        "id": "admissions_and_population",
        "title": "Demanda, ingreso y poblacion",
        "fields": [
            "has_waitlist_registry",
            "has_admission_prioritization_tool",
            "children_with_disabilities_count",
            "children_specific_ethnicity_count",
            "has_entry_exit_staff",
        ],
    },
    {
        "id": "families_and_rights",
        "title": "Familias, derechos y articulacion",
        "fields": [
            "family_communication_frequency",
            "parenting_workshops_frequency",
            "actions_promoting_rights_access",
            "actions_against_rights_violations",
        ],
    },
    {
        "id": "networking_and_protocols",
        "title": "Trabajo en red y protocolos",
        "fields": [
            "networking_level",
            "rights_violation_protocol",
        ],
    },
    {
        "id": "technical_team",
        "title": "Equipo tecnico",
        "fields": ["technical_team_level"],
    },
    {
        "id": "child_records_and_pedagogical_project",
        "title": "Registros del niño y proyecto pedagógico",
        "fields": [
            "child_development_record_frequency",
            "family_info_record_frequency",
            "health_vaccine_record_frequency",
            "socioeducational_project_participants",
            "classroom_activity_planning",
            "integral_planning",
            "direction_training_in_early_childhood",
        ],
    },
    {
        "id": "staff_profile",
        "title": "Perfil y contratacion del personal",
        "fields": [
            "pedagogical_pairs_coverage",
            "qualified_teacher_coverage",
            "assistant_training_coverage",
            "main_hiring_mode",
        ],
    },
    {
        "id": "team_meetings_and_training",
        "title": "Reuniones y capacitacion",
        "fields": [
            "meetings_teaching_staff_frequency",
            "meetings_non_teaching_staff_frequency",
            "meetings_all_staff_frequency",
            "training_instances_all_staff_last_3y",
            "training_instances_room_staff_last_3y",
            "training_instances_technical_team_last_3y",
            "training_instances_kitchen_staff_last_3y",
        ],
    },
]

SUMMARY_FIELD_NAMES = [
    "id",
    "survey_date",
    "respondent_full_name",
    "created_at",
    "updated_at",
]
