from django.urls import path

from core.decorators import permissions_any_required
from centrodeinfancia.views import (
    CentroDeInfanciaCreateView,
    CentroDeInfanciaDeleteView,
    CentroDeInfanciaDetailView,
    CentroDeInfanciaListView,
    CentroDeInfanciaUpdateView,
    IntervencionCentroInfanciaCreateView,
    IntervencionCentroInfanciaDeleteView,
    IntervencionCentroInfanciaDetailView,
    IntervencionCentroInfanciaUpdateView,
    NominaCentroInfanciaCreateView,
    NominaCentroInfanciaDeleteView,
    NominaCentroInfanciaDetailView,
    ObservacionCentroInfanciaCreateView,
    ObservacionCentroInfanciaDeleteView,
    ObservacionCentroInfanciaDetailView,
    ObservacionCentroInfanciaUpdateView,
    centrodeinfancia_ajax,
    eliminar_archivo_intervencion_centrodeinfancia,
    nomina_centrodeinfancia_editar_ajax,
    subir_archivo_intervencion_centrodeinfancia,
)
from centrodeinfancia.views_formulario_cdi import (
    FormularioCDICreateView,
    FormularioCDIDetailView,
    FormularioCDIListView,
    FormularioCDIUpdateView,
)
from centrodeinfancia.views_export import CentroDeInfanciaExportView


urlpatterns = [
    path(
        "centrodeinfancia/listar",
        permissions_any_required(["centrodeinfancia.view_centrodeinfancia"])(
            CentroDeInfanciaListView.as_view()
        ),
        name="centrodeinfancia",
    ),
    path(
        "centrodeinfancia/exportar",
        permissions_any_required(
            ["centrodeinfancia.view_centrodeinfancia", "auth.role_exportar_a_csv"]
        )(CentroDeInfanciaExportView.as_view()),
        name="centrodeinfancia_exportar",
    ),
    path(
        "centrodeinfancia/crear",
        permissions_any_required(["centrodeinfancia.add_centrodeinfancia"])(
            CentroDeInfanciaCreateView.as_view()
        ),
        name="centrodeinfancia_crear",
    ),
    path(
        "centrodeinfancia/detalle/<int:pk>",
        permissions_any_required(["centrodeinfancia.view_centrodeinfancia"])(
            CentroDeInfanciaDetailView.as_view()
        ),
        name="centrodeinfancia_detalle",
    ),
    path(
        "centrodeinfancia/editar/<int:pk>",
        permissions_any_required(["centrodeinfancia.change_centrodeinfancia"])(
            CentroDeInfanciaUpdateView.as_view()
        ),
        name="centrodeinfancia_editar",
    ),
    path(
        "centrodeinfancia/eliminar/<int:pk>",
        permissions_any_required(["centrodeinfancia.delete_centrodeinfancia"])(
            CentroDeInfanciaDeleteView.as_view()
        ),
        name="centrodeinfancia_eliminar",
    ),
    path(
        "centrodeinfancia/ajax/",
        centrodeinfancia_ajax,
        name="centrodeinfancia_ajax",
    ),
    path(
        "centrodeinfancia/<int:pk>/nomina/",
        permissions_any_required(["centrodeinfancia.view_nominacentroinfancia"])(
            NominaCentroInfanciaDetailView.as_view()
        ),
        name="centrodeinfancia_nomina_ver",
    ),
    path(
        "centrodeinfancia/<int:pk>/nomina/crear/",
        permissions_any_required(["centrodeinfancia.add_nominacentroinfancia"])(
            NominaCentroInfanciaCreateView.as_view()
        ),
        name="centrodeinfancia_nomina_crear",
    ),
    path(
        "centrodeinfancia/editar-nomina/<int:pk>/",
        permissions_any_required(["centrodeinfancia.change_nominacentroinfancia"])(
            nomina_centrodeinfancia_editar_ajax
        ),
        name="centrodeinfancia_nomina_editar_ajax",
    ),
    path(
        "centrodeinfancia/<int:pk>/nomina/<int:pk2>/eliminar/",
        permissions_any_required(["centrodeinfancia.delete_nominacentroinfancia"])(
            NominaCentroInfanciaDeleteView.as_view()
        ),
        name="centrodeinfancia_nomina_borrar",
    ),
    path(
        "centrodeinfancia/intervencion/crear/<int:pk>",
        permissions_any_required(["centrodeinfancia.add_intervencioncentroinfancia"])(
            IntervencionCentroInfanciaCreateView.as_view()
        ),
        name="centrodeinfancia_intervencion_crear",
    ),
    path(
        "centrodeinfancia/intervencion/editar/<int:pk>/<int:pk2>",
        permissions_any_required(
            ["centrodeinfancia.change_intervencioncentroinfancia"]
        )(IntervencionCentroInfanciaUpdateView.as_view()),
        name="centrodeinfancia_intervencion_editar",
    ),
    path(
        "centrodeinfancia/intervencion/borrar/<int:pk>/<int:intervencion_id>/",
        permissions_any_required(
            ["centrodeinfancia.delete_intervencioncentroinfancia"]
        )(IntervencionCentroInfanciaDeleteView.as_view()),
        name="centrodeinfancia_intervencion_borrar",
    ),
    path(
        "centrodeinfancia/intervencion/detalle/<int:pk>/",
        permissions_any_required(["centrodeinfancia.view_centrodeinfancia"])(
            IntervencionCentroInfanciaDetailView.as_view()
        ),
        name="centrodeinfancia_intervencion_detalle",
    ),
    path(
        "centrodeinfancia/intervencion/<int:intervencion_id>/documentacion/subir/",
        permissions_any_required(
            ["centrodeinfancia.change_intervencioncentroinfancia"]
        )(subir_archivo_intervencion_centrodeinfancia),
        name="centrodeinfancia_subir_archivo_intervencion",
    ),
    path(
        "centrodeinfancia/intervencion/<int:intervencion_id>/documentacion/eliminar/",
        permissions_any_required(
            ["centrodeinfancia.delete_intervencioncentroinfancia"]
        )(eliminar_archivo_intervencion_centrodeinfancia),
        name="centrodeinfancia_eliminar_archivo_intervencion",
    ),
    path(
        "centrodeinfancia/<int:pk>/observacion/crear/",
        permissions_any_required(["centrodeinfancia.add_intervencioncentroinfancia"])(
            ObservacionCentroInfanciaCreateView.as_view()
        ),
        name="centrodeinfancia_observacion_crear",
    ),
    path(
        "centrodeinfancia/observacion/<int:pk>/",
        permissions_any_required(["centrodeinfancia.view_centrodeinfancia"])(
            ObservacionCentroInfanciaDetailView.as_view()
        ),
        name="centrodeinfancia_observacion_detalle",
    ),
    path(
        "centrodeinfancia/observacion/<int:pk>/editar/",
        permissions_any_required(
            ["centrodeinfancia.change_intervencioncentroinfancia"]
        )(ObservacionCentroInfanciaUpdateView.as_view()),
        name="centrodeinfancia_observacion_editar",
    ),
    path(
        "centrodeinfancia/observacion/<int:pk>/eliminar/",
        permissions_any_required(
            ["centrodeinfancia.delete_intervencioncentroinfancia"]
        )(ObservacionCentroInfanciaDeleteView.as_view()),
        name="centrodeinfancia_observacion_eliminar",
    ),
    path(
        "centrodeinfancia/<int:pk>/formularios/",
        permissions_any_required(["centrodeinfancia.view_formulariocdi"])(
            FormularioCDIListView.as_view()
        ),
        name="centrodeinfancia_formulario_listado",
    ),
    path(
        "centrodeinfancia/<int:pk>/formularios/crear/",
        permissions_any_required(["centrodeinfancia.add_formulariocdi"])(
            FormularioCDICreateView.as_view()
        ),
        name="centrodeinfancia_formulario_crear",
    ),
    path(
        "centrodeinfancia/<int:pk>/formularios/<int:form_pk>/",
        permissions_any_required(["centrodeinfancia.view_formulariocdi"])(
            FormularioCDIDetailView.as_view()
        ),
        name="centrodeinfancia_formulario_detalle",
    ),
    path(
        "centrodeinfancia/<int:pk>/formularios/<int:form_pk>/editar/",
        permissions_any_required(["centrodeinfancia.change_formulariocdi"])(
            FormularioCDIUpdateView.as_view()
        ),
        name="centrodeinfancia_formulario_editar",
    ),
]
