# Generated by Django 5.2.16 on 2026-09-07 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pas", "0005_pascontrolrenaper_pasincompatibilidad"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PasSupervivenciaRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField(unique=True)),
                ("cutoff", models.DateField()),
                ("status", models.CharField(default="pending", max_length=24)),
                (
                    "active_slot",
                    models.PositiveSmallIntegerField(null=True, unique=True),
                ),
                ("origin", models.CharField(default="manual", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PasSupervivenciaBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("persona_ids", models.JSONField(default=list)),
                ("size", models.PositiveIntegerField(default=0)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(db_index=True, default="pending", max_length=24),
                ),
                ("heartbeat", models.DateTimeField(null=True)),
                ("dispatched_at", models.DateTimeField(null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("counts", models.JSONField(default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="pas.passupervivenciarun",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pascontrolrenaper",
            name="run",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pas.passupervivenciarun",
            ),
        ),
        migrations.AddField(
            model_name="pasincompatibilidad",
            name="run",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pas.passupervivenciarun",
            ),
        ),
    ]
