# Generated by Django 5.2.16 on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pas", "0006_passupervivenciarun_passupervivenciabatch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paspersona",
            name="altura",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="paspersona",
            name="calle",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="paspersona",
            name="genero",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculino"), ("F", "Femenino"), ("X", "No binario")],
                max_length=1,
            ),
        ),
    ]
