INSERT INTO hsudev.Legajos_legajos (
    _id,
    apellido,
    nombre,
    fecha_nacimiento,
    tipo_doc,
    documento,
    sexo,
    nacionalidad,
    estado_civil,
    calle,
    altura,
    piso,
    circuito,
    barrio,
    localidad,
    telefono,
    email,
    foto,
    observaciones,
    estado,
    creado,
    modificado,
    creado_por_id,
    modificado_por_id,
    cuit,
    identidad,
    provincia,
    pais,
    municipio,
    cp,
    manzana,
    prefijo_tel2,
    telefono2,
    prefijo_tel_alt,
    telefono_alt,
    observaciones_benef,
    tiene_Hijos,
    tiene_Cud,
    cantidad_Hijos,
    presenta_Discapacidad,
    cantidad_Presenta_Discapacidad,
    modalidad_Cobro,
    otra_Modalidad_Cobro
)
SELECT
    NULL as _id,
    a.APELLIDO as apellido,
    a.NONMBRE as nombre,
    a.FECHA_NACIMIENTO2 as fecha_nacimiento,
    '' as tipo_doc,
    NULL as documento,
    'Aderente' as sexo,
    '' as nacionalidad,
    '' as estado_civil,
    '' as calle,
    NULL as altura,
    '' as piso,
    '' as circuito,
    '' as barrio,
    '' as localidad,
    NULL as telefono,
    '' as email,
    '' as foto,
    '' as observaciones,
    1 as estado,
    NOW() as creado,
    NOW() as modificado,
    NULL as creado_por_id,
    NULL as modificado_por_id,
    a.CUIL as cuit,
    '' as identidad,
    '' as provincia,
    '' as pais,
    '' as municipio,
    '' as cp,
    '' as manzana,
    '' as prefijo_tel2,
    '' as telefono2,
    '' as prefijo_tel_alt,
    '' as telefono_alt,
    '' as observaciones_benef,
    '' as tiene_Hijos,
    '' as tiene_Cud,
    NULL as cantidad_Hijos,
    '' as presenta_Discapacidad,
    '' as cantidad_Presenta_Discapacidad,
    '' as modalidad_Cobro,
    '' as otra_Modalidad_Cobro
FROM
    hsudev.adherentes a
WHERE
    a.CUIL IS NOT NULL
    AND a.COD_RELACION IS NOT NULL
    AND EXISTS (
        SELECT 1
        FROM hsudev.Legajos_legajos l
        WHERE l.cuit = a.CUIL
    );
    

