from django.urls import path

from core.decorators import permissions_any_required
from organizaciones.views import (
    OrganizacionListView,
    OrganizacionCreateView,
    OrganizacionUpdateView,
    OrganizacionDetailView,
    OrganizacionDeleteView,
    FirmanteCreateView,
    AvalCreateView,
    AvalUpdateView,
    FirmanteUpdateView,
    FirmanteDeleteView,
    AvalDeleteView,
    actualizar_estado_documento_organizacion,
    actualizar_vencimiento_documento_organizacion,
    historial_documento_organizacion,
    sub_tipo_entidad_ajax,
    organizaciones_ajax,
    cuil_check_ajax,
    subir_documento_organizacion,
)
from organizaciones.views_export import OrganizacionExportView

ORGANIZACION_DOCUMENTACION_PERMS = [
    "organizaciones.view_organizacion",
    "auth.role_tecnico_comedor",
    "auth.role_abogado_dupla",
]

urlpatterns = [
    path(
        "organizaciones/listar",
        permissions_any_required(ORGANIZACION_DOCUMENTACION_PERMS)(
            OrganizacionListView.as_view()
        ),
        name="organizaciones",
    ),
    path(
        "organizaciones/exportar",
        permissions_any_required(
            ["organizaciones.view_organizacion", "auth.role_exportar_a_csv"]
        )(OrganizacionExportView.as_view()),
        name="organizacion_exportar",
    ),
    path(
        "organizaciones/crear",
        permissions_any_required(["organizaciones.view_organizacion"])(
            OrganizacionCreateView.as_view()
        ),
        name="organizacion_crear",
    ),
    path(
        "organizaciones/editar/<int:pk>",
        permissions_any_required(["organizaciones.view_organizacion"])(
            OrganizacionUpdateView.as_view()
        ),
        name="organizacion_editar",
    ),
    path(
        "organizaciones/detalle/<int:pk>",
        permissions_any_required(ORGANIZACION_DOCUMENTACION_PERMS)(
            OrganizacionDetailView.as_view()
        ),
        name="organizacion_detalle",
    ),
    path(
        "organizaciones/eliminar/<int:pk>",
        permissions_any_required(["organizaciones.view_organizacion"])(
            OrganizacionDeleteView.as_view()
        ),
        name="organizacion_eliminar",
    ),
    path(
        "organizaciones/<int:organizacion_id>/documentacion/<int:documentacion_id>/subir/",
        permissions_any_required(ORGANIZACION_DOCUMENTACION_PERMS)(
            subir_documento_organizacion
        ),
        name="organizacion_documento_subir",
    ),
    path(
        "organizaciones/documentacion/<int:archivo_id>/estado/",
        permissions_any_required(ORGANIZACION_DOCUMENTACION_PERMS)(
            actualizar_estado_documento_organizacion
        ),
        name="organizacion_documento_estado",
    ),
    path(
        "organizaciones/documentacion/<int:archivo_id>/vencimiento/",
        permissions_any_required(ORGANIZACION_DOCUMENTACION_PERMS)(
            actualizar_vencimiento_documento_organizacion
        ),
        name="organizacion_documento_vencimiento",
    ),
    path(
        "organizaciones/<int:organizacion_id>/documentacion/<int:documentacion_id>/historial/",
        permissions_any_required(ORGANIZACION_DOCUMENTACION_PERMS)(
            historial_documento_organizacion
        ),
        name="organizacion_documento_historial",
    ),
    path(
        "organizaciones/firmante/crear/<int:organizacion_pk>",
        permissions_any_required(["organizaciones.view_organizacion"])(
            FirmanteCreateView.as_view()
        ),
        name="firmante_crear",
    ),
    path(
        "organizaciones/firmante/editar/<int:pk>",
        permissions_any_required(["organizaciones.view_organizacion"])(
            FirmanteUpdateView.as_view()
        ),
        name="firmante_editar",
    ),
    path(
        "organizaciones/firmante/eliminar/<int:pk>",
        permissions_any_required(["organizaciones.view_organizacion"])(
            FirmanteDeleteView.as_view()
        ),
        name="firmante_eliminar",
    ),
    path(
        "organizaciones/aval/crear/<int:organizacion_pk>",
        permissions_any_required(["organizaciones.view_organizacion"])(
            AvalCreateView.as_view()
        ),
        name="aval_crear",
    ),
    path(
        "organizaciones/aval/editar/<int:pk>",
        permissions_any_required(["organizaciones.view_organizacion"])(
            AvalUpdateView.as_view()
        ),
        name="aval_editar",
    ),
    path(
        "organizaciones/aval/eliminar/<int:pk>",
        permissions_any_required(["organizaciones.view_organizacion"])(
            AvalDeleteView.as_view()
        ),
        name="aval_eliminar",
    ),
    path(
        "organizaciones/subtipos-entidad/ajax/",
        permissions_any_required(["organizaciones.view_organizacion"])(
            sub_tipo_entidad_ajax
        ),
        name="organizacion_subtipos_entidad_ajax",
    ),
    path(
        "organizaciones/ajax/",
        permissions_any_required(ORGANIZACION_DOCUMENTACION_PERMS)(organizaciones_ajax),
        name="organizaciones_ajax",
    ),
    path(
        "organizaciones/cuil-check/ajax/",
        permissions_any_required(["organizaciones.view_organizacion"])(cuil_check_ajax),
        name="organizacion_cuil_check_ajax",
    ),
]
