from django.urls import path

from core.decorators import group_required
from organizaciones.views import (
    OrganizacionListView,
    OrganizacionCreateView,
    OrganizacionUpdateView,
    OrganizacionDetailView,
    OrganizacionDeleteView,
    FirmanteCreateView,
    Aval1CreateView,
    Aval2CreateView,
    Aval1UpdateView,
    Aval2UpdateView,
    FirmanteUpdateView,
    FirmanteDeleteView,
    Aval1DeleteView,
    Aval2DeleteView,
    sub_tipo_entidad_ajax,
)

urlpatterns = [
    path(
        "organizaciones/listar",
        group_required(["Organizaciones"])(OrganizacionListView.as_view()),
        name="organizaciones",
    ),
    path(
        "organizaciones/crear",
        group_required(["Organizaciones"])(OrganizacionCreateView.as_view()),
        name="organizacion_crear",
    ),
    path(
        "organizaciones/editar/<int:pk>",
        group_required(["Organizaciones"])(OrganizacionUpdateView.as_view()),
        name="organizacion_editar",
    ),
    path(
        "organizaciones/detalle/<int:pk>",
        group_required(["Organizaciones"])(OrganizacionDetailView.as_view()),
        name="organizacion_detalle",
    ),
    path(
        "organizaciones/eliminar/<int:pk>",
        group_required(["Organizaciones"])(OrganizacionDeleteView.as_view()),
        name="organizacion_eliminar",
    ),
    path(
        "organizaciones/firmante/crear/<int:organizacion_pk>",
        group_required(["Organizaciones"])(FirmanteCreateView.as_view()),
        name="firmante_crear",
    ),
    path(
        "organizaciones/firmante/editar/<int:pk>",
        group_required(["Organizaciones"])(FirmanteUpdateView.as_view()),
        name="firmante_editar",
    ),
    path(
        "organizaciones/firmante/eliminar/<int:pk>",
        group_required(["Organizaciones"])(FirmanteDeleteView.as_view()),
        name="firmante_eliminar",
    ),
    path(
        "organizaciones/aval1/crear/<int:organizacion_pk>",
        group_required(["Organizaciones"])(Aval1CreateView.as_view()),
        name="aval1_crear",
    ),
    path(
        "organizaciones/aval1/editar/<int:pk>",
        group_required(["Organizaciones"])(Aval1UpdateView.as_view()),
        name="aval1_editar",
    ),
    path(
        "organizaciones/aval1/eliminar/<int:pk>",
        group_required(["Organizaciones"])(Aval1DeleteView.as_view()),
        name="aval1_eliminar",
    ),
    path(
        "organizaciones/aval2/crear/<int:organizacion_pk>",
        group_required(["Organizaciones"])(Aval2CreateView.as_view()),
        name="aval2_crear",
    ),
    path(
        "organizaciones/aval2/editar/<int:pk>",
        group_required(["Organizaciones"])(Aval2UpdateView.as_view()),
        name="aval2_editar",
    ),
    path(
        "organizaciones/aval2/eliminar/<int:pk>",
        group_required(["Organizaciones"])(Aval2DeleteView.as_view()),
        name="aval2_eliminar",
    ),
    path(
        "organizaciones/subtipos-entidad/ajax/",
        group_required(["Organizaciones"])(sub_tipo_entidad_ajax),
        name="organizacion_subtipos_entidad_ajax",
    ),
]
