from django.urls import path

from core.decorators import permissions_all_required, permissions_any_required
from pas.views import (
    PasInformeDetailView,
    PasInformeDownloadView,
    PasInformeGenerateView,
    PasInformeListView,
    PasInformePreviewView,
    PasAreaView,
    PasDDJJConfirmacionView,
    PasDDJJDownloadView,
    PasDDJJFormularioView,
    PasDDJJMunicipiosView,
    PasDDJJPrivateMediaView,
    PasCrucesExportarSintysView,
    PasCrucesImportarSintysView,
    PasCrucesActualizarRenaperView,
    PasCrucesView,
    PasFormacionPersonasView,
    PasPersonaCambiarEstadoView,
    PasPersonaCreateView,
    PasPersonaDeleteView,
    PasPersonaDetailView,
    PasPersonaListView,
    PasPersonaUpdateView,
    PasTitularesImportView,
    PasTokensExportView,
)

urlpatterns = [
    path(
        "media/pas/ddjj/<path:path>",
        PasDDJJPrivateMediaView.as_view(),
        name="pas_ddjj_media_privado",
    ),
    path(
        "pas/ddjj/formulario/<uuid:token>",
        PasDDJJFormularioView.as_view(),
        name="pas_ddjj_formulario",
    ),
    path(
        "pas/ddjj/formulario/<uuid:token>/municipios",
        PasDDJJMunicipiosView.as_view(),
        name="pas_ddjj_municipios",
    ),
    path(
        "pas/ddjj/confirmacion",
        PasDDJJConfirmacionView.as_view(),
        name="pas_ddjj_confirmacion",
    ),
    path(
        "pas/ddjj/<int:pk>/descargar",
        permissions_any_required(["pas.view_paspersona"])(
            PasDDJJDownloadView.as_view()
        ),
        name="pas_ddjj_descargar",
    ),
    path(
        "pas/panel-control",
        permissions_any_required(["pas.view_paspersona"])(
            PasPersonaDetailView.as_view()
        ),
        name="pas_panel_control",
    ),
    path(
        "pas/panel-control/<int:pk>",
        permissions_any_required(["pas.view_paspersona"])(
            PasPersonaDetailView.as_view()
        ),
        name="pas_panel_control_persona",
    ),
    path(
        "pas/formacion",
        permissions_any_required(["pas.view_paspersona"])(
            PasAreaView.as_view(area_key="formacion")
        ),
        name="pas_formacion",
    ),
    path(
        "pas/formacion/personas",
        permissions_any_required(["pas.view_paspersona"])(
            PasFormacionPersonasView.as_view()
        ),
        name="pas_formacion_personas",
    ),
    path(
        "pas/cruces",
        permissions_any_required(["pas.view_paspersona"])(PasCrucesView.as_view()),
        name="pas_cruces",
    ),
    path(
        "pas/cruces/exportar-sintys",
        permissions_any_required(["pas.change_paspersona"])(
            PasCrucesExportarSintysView.as_view()
        ),
        name="pas_cruces_exportar_sintys",
    ),
    path(
        "pas/cruces/importar-sintys",
        permissions_any_required(["pas.change_paspersona"])(
            PasCrucesImportarSintysView.as_view()
        ),
        name="pas_cruces_importar_sintys",
    ),
    path(
        "pas/cruces/actualizar-renaper",
        permissions_any_required(["pas.change_paspersona"])(
            PasCrucesActualizarRenaperView.as_view()
        ),
        name="pas_cruces_actualizar_renaper",
    ),
    path(
        "pas/mesa-ayuda",
        permissions_any_required(["pas.view_paspersona"])(
            PasAreaView.as_view(area_key="mesa-ayuda")
        ),
        name="pas_mesa_ayuda",
    ),
    path(
        "pas/liquidacion",
        permissions_any_required(["pas.view_paspersona"])(
            PasAreaView.as_view(area_key="liquidacion")
        ),
        name="pas_liquidacion",
    ),
    path(
        "pas/informes",
        permissions_all_required(["pas.view_paspersona", "pas.view_pasinforme"])(
            PasInformeListView.as_view()
        ),
        name="pas_informe_listar",
    ),
    path(
        "pas/informes/generar",
        permissions_all_required(["pas.view_paspersona", "pas.add_pasinforme"])(
            PasInformeGenerateView.as_view()
        ),
        name="pas_informe_generar",
    ),
    path(
        "pas/informes/previsualizar",
        permissions_all_required(["pas.view_paspersona", "pas.add_pasinforme"])(
            PasInformePreviewView.as_view()
        ),
        name="pas_informe_previsualizar",
    ),
    path(
        "pas/informes/<int:pk>/descargar",
        permissions_all_required(
            [
                "pas.view_paspersona",
                "pas.view_pasinforme",
                "auth.role_exportar_a_csv",
            ]
        )(PasInformeDownloadView.as_view()),
        name="pas_informe_descargar",
    ),
    path(
        "pas/informes/<int:pk>",
        permissions_all_required(["pas.view_paspersona", "pas.view_pasinforme"])(
            PasInformeDetailView.as_view()
        ),
        name="pas_informe_detalle",
    ),
    path(
        "pas/listar",
        permissions_any_required(["pas.view_paspersona"])(PasPersonaListView.as_view()),
        name="pas_persona_listar",
    ),
    path(
        "pas/titulares/importar",
        permissions_any_required(["pas.add_paspersona"])(
            PasTitularesImportView.as_view()
        ),
        name="pas_titulares_importar",
    ),
    path(
        "pas/ddjj/tokens/exportar",
        permissions_any_required(["pas.export_ddjj_tokens"])(
            PasTokensExportView.as_view()
        ),
        name="pas_tokens_exportar",
    ),
    path(
        "pas/crear",
        permissions_any_required(["pas.add_paspersona"])(
            PasPersonaCreateView.as_view()
        ),
        name="pas_persona_crear",
    ),
    path(
        "pas/<int:pk>",
        permissions_any_required(["pas.view_paspersona"])(
            PasPersonaDetailView.as_view()
        ),
        name="pas_persona_detalle",
    ),
    path(
        "pas/<int:pk>/editar",
        permissions_any_required(["pas.change_paspersona"])(
            PasPersonaUpdateView.as_view()
        ),
        name="pas_persona_editar",
    ),
    path(
        "pas/<int:pk>/cambiar-estado",
        permissions_any_required(["pas.change_paspersona"])(
            PasPersonaCambiarEstadoView.as_view()
        ),
        name="pas_persona_cambiar_estado",
    ),
    path(
        "pas/<int:pk>/eliminar",
        permissions_any_required(["pas.delete_paspersona"])(
            PasPersonaDeleteView.as_view()
        ),
        name="pas_persona_eliminar",
    ),
]
