"""Configuracion de columnas para el listado de usuarios."""

from core.services.column_preferences import ColumnDefinition

USUARIOS_LIST_KEY = "usuarios_list"

USUARIOS_COLUMNS = [
    ColumnDefinition(
        key="first_name",
        title="Nombre",
        header={"sortable": True, "sort_key": "first_name", "width": "12%"},
        field={"name": "first_name"},
        default=True,
        export_field="first_name",
        export_title="Nombre",
        sort_field="first_name",
    ),
    ColumnDefinition(
        key="last_name",
        title="Apellido",
        header={"sortable": True, "sort_key": "last_name", "width": "20%"},
        field={"name": "last_name"},
        default=True,
        export_field="last_name",
        export_title="Apellido",
        sort_field="last_name",
    ),
    ColumnDefinition(
        key="username",
        title="Username",
        header={"sortable": True, "sort_key": "username", "width": "10%"},
        field={"name": "username"},
        default=True,
        export_field="username",
        export_title="Username",
        sort_field="username",
    ),
    ColumnDefinition(
        key="email",
        title="Email",
        header={"sortable": True, "sort_key": "email", "width": "8%"},
        field={"name": "email"},
        default=True,
        export_field="email",
        export_title="Email",
        sort_field="email",
    ),
    ColumnDefinition(
        key="rol",
        title="Rol",
        header={"sortable": True, "sort_key": "rol", "width": "20%"},
        field={"name": "rol"},
        default=True,
        export_field="rol",
        export_title="Rol",
        sort_field="rol",
    ),
    ColumnDefinition(
        key="is_active",
        title="Activo",
        header={"sortable": True, "sort_key": "is_active"},
        field={"name": "is_active"},
        default=False,
        export_field="is_active",
        export_title="Activo",
        sort_field="is_active",
    ),
    ColumnDefinition(
        key="is_staff",
        title="Staff",
        header={"sortable": True, "sort_key": "is_staff"},
        field={"name": "is_staff"},
        default=False,
        export_field="is_staff",
        export_title="Staff",
        sort_field="is_staff",
    ),
    ColumnDefinition(
        key="is_superuser",
        title="Superuser",
        header={"sortable": True, "sort_key": "is_superuser"},
        field={"name": "is_superuser"},
        default=False,
        export_field="is_superuser",
        export_title="Superuser",
        sort_field="is_superuser",
    ),
    ColumnDefinition(
        key="last_login",
        title="Ultimo ingreso",
        header={"sortable": True, "sort_key": "last_login"},
        field={"name": "last_login"},
        default=False,
        export_field="last_login",
        export_title="Ultimo ingreso",
        sort_field="last_login",
    ),
    ColumnDefinition(
        key="date_joined",
        title="Fecha alta",
        header={"sortable": True, "sort_key": "date_joined"},
        field={"name": "date_joined"},
        default=False,
        export_field="date_joined",
        export_title="Fecha alta",
        sort_field="date_joined",
    ),
    ColumnDefinition(
        key="id",
        title="ID",
        header={"sortable": True, "sort_key": "id"},
        field={"name": "id"},
        default=False,
        export_field="id",
        export_title="ID",
        sort_field="id",
    ),
]

__all__ = ["USUARIOS_LIST_KEY", "USUARIOS_COLUMNS"]
