# Generated by Django 4.2.20 on 2025-12-22 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("importarexpediente", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivosImportados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archivo", models.FileField(upload_to="importados/")),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                ("error", models.TextField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="importrowlog",
            name="job",
        ),
        migrations.DeleteModel(
            name="ImportJob",
        ),
        migrations.DeleteModel(
            name="ImportRowLog",
        ),
    ]
