# Generated by Django 4.2.20 on 2025-12-26 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("importarexpediente", "0003_archivosimportados_id_archivo"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExitoImportacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fila", models.IntegerField()),
                ("mensaje_exito", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="archivosimportados",
            name="error",
        ),
        migrations.RemoveField(
            model_name="archivosimportados",
            name="id_archivo",
        ),
        migrations.CreateModel(
            name="RegistroImportado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_expediente", models.IntegerField()),
                (
                    "exito_importacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros",
                        to="importarexpediente.exitoimportacion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exitoimportacion",
            name="archivo_importado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exitos",
                to="importarexpediente.archivosimportados",
            ),
        ),
        migrations.CreateModel(
            name="ErroresImportacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fila", models.IntegerField()),
                ("mensaje_error", models.TextField()),
                (
                    "archivo_importado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="errores",
                        to="importarexpediente.archivosimportados",
                    ),
                ),
            ],
        ),
    ]
