# Generated by Django 4.2.20 on 2025-12-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "importarexpediente",
            "0004_exitoimportacion_remove_archivosimportados_error_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="archivosimportados",
            name="count_errores",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="archivosimportados",
            name="count_exitos",
            field=models.IntegerField(default=0),
        ),
    ]
