# Generated by Django 4.2.20 on 2025-12-26 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("importarexpediente", "0005_archivosimportados_count_errores_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivosimportados",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="erroresimportacion",
            name="archivo_importado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="errores",
                to="importarexpediente.archivosimportados",
            ),
        ),
        migrations.AlterField(
            model_name="exitoimportacion",
            name="archivo_importado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="exitos",
                to="importarexpediente.archivosimportados",
            ),
        ),
        migrations.AlterField(
            model_name="registroimportado",
            name="exito_importacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="registros",
                to="importarexpediente.exitoimportacion",
            ),
        ),
    ]
