# Generated by Django 4.2.20 on 2025-12-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("importarexpediente", "0006_alter_archivosimportados_usuario_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="erroresimportacion",
            old_name="mensaje_error",
            new_name="mensaje",
        ),
        migrations.RenameField(
            model_name="exitoimportacion",
            old_name="mensaje_exito",
            new_name="mensaje",
        ),
    ]
