# Generated by Django 4.2.20 on 2025-12-29 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("expedientespagos", "0002_alter_expedientepago_expediente_pago_and_more"),
        (
            "importarexpediente",
            "0007_rename_mensaje_error_erroresimportacion_mensaje_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registroimportado",
            name="id_expediente",
        ),
        migrations.AddField(
            model_name="registroimportado",
            name="expediente_pago",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="registros_importados",
                to="expedientespagos.expedientepago",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="erroresimportacion",
            name="mensaje",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="exitoimportacion",
            name="mensaje",
            field=models.TextField(blank=True, default=""),
        ),
    ]
