# Generated by Django 4.2.20 on 2025-12-29 22:07

from django.db import migrations, models
from django.db.models import F
import django.db.models.deletion


def forwards_copy_expediente(apps, schema_editor):
    RegistroImportado = apps.get_model("importarexpediente", "RegistroImportado")
    RegistroImportado.objects.update(expediente_pago_id=F("id_expediente"))


def backwards_copy_expediente(apps, schema_editor):
    RegistroImportado = apps.get_model("importarexpediente", "RegistroImportado")
    RegistroImportado.objects.update(id_expediente=F("expediente_pago_id"))


class Migration(migrations.Migration):

    dependencies = [
        ("expedientespagos", "0002_alter_expedientepago_expediente_pago_and_more"),
        (
            "importarexpediente",
            "0007_rename_mensaje_error_erroresimportacion_mensaje_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="registroimportado",
            name="expediente_pago",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="registros_importados",
                to="expedientespagos.expedientepago",
            ),
        ),
        migrations.RunPython(
            forwards_copy_expediente, reverse_code=backwards_copy_expediente
        ),
        migrations.AlterField(
            model_name="registroimportado",
            name="expediente_pago",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="registros_importados",
                to="expedientespagos.expedientepago",
            ),
        ),
        migrations.RemoveField(
            model_name="registroimportado",
            name="id_expediente",
        ),
        migrations.AlterField(
            model_name="erroresimportacion",
            name="mensaje",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="exitoimportacion",
            name="mensaje",
            field=models.TextField(blank=True, default=""),
        ),
    ]
