# Generated by Django 4.2.20 on 2026-01-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importarexpediente", "0008_remove_registroimportado_id_expediente_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivosimportados",
            name="importacion_completada",
            field=models.BooleanField(default=False),
        ),
    ]
