# Generated by Django 4.2.27 on 2026-02-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importarexpediente", "0010_archivosimportados_delimiter"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivosimportados",
            name="numero_expedinte_pago",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
