# Generated by Django 4.2.27 on 2026-02-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("importarexpediente", "0011_archivosimportados_numero_expedinte_pago"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archivosimportados",
            name="numero_expedinte_pago",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
