# Generated by Django 4.2.27 on 2026-02-09 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("importarexpediente", "0012_alter_archivosimportados_numero_expedinte_pago"),
    ]

    operations = [
        migrations.RenameField(
            model_name="archivosimportados",
            old_name="numero_expedinte_pago",
            new_name="numero_expediente_pago",
        ),
    ]
