from __future__ import annotations

from dataclasses import dataclass

from core.constants import UserGroups


@dataclass(frozen=True)
class BootstrapGroupSeed:
    """Define un grupo bootstrap y sus permisos canónicos adicionales."""

    name: str
    permission_codes: tuple[str, ...] = ()


LISTADO_DEFINED_GROUPS = (
    BootstrapGroupSeed(
        "Tecnico Comedor",
        (
            "acompanamientos.view_informacionrelevante",
            "admisiones.view_admision",
            "auth.role_acompanamiento_detalle",
            "auth.role_acompanamiento_listar",
            "auth.role_comedores",
            "auth.role_comedores_editar",
            "auth.role_comedores_intervencion_crear",
            "auth.role_comedores_intervencion_editar",
            "auth.role_comedores_intervencion_ver",
            "auth.role_comedores_intervenciones_detalle",
            "auth.role_comedores_listar",
            "auth.role_comedores_nomina_borrar",
            "auth.role_comedores_nomina_crear",
            "auth.role_comedores_nomina_editar",
            "auth.role_comedores_nomina_ver",
            "auth.role_comedores_observaciones_crear",
            "auth.role_comedores_observaciones_detalle",
            "auth.role_comedores_observaciones_editar",
            "auth.role_comedores_relevamiento_detalle",
            "auth.role_comedores_relevamiento_ver",
            "auth.role_comedores_ver",
            "auth.role_tecnico_comedor",
            "comedores.add_nomina",
            "comedores.add_observacion",
            "comedores.change_comedor",
            "comedores.change_nomina",
            "comedores.change_observacion",
            "comedores.delete_nomina",
            "comedores.view_comedor",
            "comedores.view_nomina",
            "comedores.view_observacion",
            "intervenciones.add_intervencion",
            "intervenciones.change_intervencion",
            "intervenciones.view_intervencion",
            "relevamientos.view_relevamiento",
        ),
    ),
    BootstrapGroupSeed(
        "Abogado Dupla",
        (
            "acompanamientos.view_informacionrelevante",
            "admisiones.view_admision",
            "auth.role_abogado_dupla",
            "comedores.view_comedor",
            "auth.role_acompanamiento_detalle",
            "auth.role_acompanamiento_listar",
            "auth.role_area_legales",
            "auth.role_comedores",
            "auth.role_comedores_intervencion_ver",
            "intervenciones.view_intervencion",
            "auth.role_comedores_intervenciones_detalle",
            "auth.role_comedores_nomina_ver",
            "comedores.view_nomina",
            "auth.role_comedores_observaciones_detalle",
            "comedores.view_observacion",
            "auth.role_comedores_relevamiento_detalle",
            "relevamientos.view_relevamiento",
            "auth.role_comedores_relevamiento_ver",
            "auth.role_organizaciones",
            "organizaciones.view_organizacion",
        ),
    ),
    BootstrapGroupSeed(
        "Area Contable",
        (
            "acompanamientos.view_informacionrelevante",
            "auth.role_acompanamiento_detalle",
            "auth.role_acompanamiento_listar",
            "auth.role_area_contable",
            "comedores.view_comedor",
            "expedientespagos.view_expedientepago",
            "auth.role_comedores",
            "auth.role_comedores_intervencion_ver",
            "intervenciones.view_intervencion",
            "auth.role_comedores_intervenciones_detalle",
            "auth.role_comedores_nomina_ver",
            "comedores.view_nomina",
            "auth.role_comedores_observaciones_detalle",
            "comedores.view_observacion",
            "auth.role_comedores_relevamiento_detalle",
            "relevamientos.view_relevamiento",
            "auth.role_comedores_relevamiento_ver",
        ),
    ),
    BootstrapGroupSeed(
        "Area Legales",
        (
            "acompanamientos.view_informacionrelevante",
            "auth.role_acompanamiento_detalle",
            "auth.role_acompanamiento_listar",
            "admisiones.view_admision",
            "auth.role_area_legales",
            "comedores.view_comedor",
            "expedientespagos.view_expedientepago",
            "auth.role_comedores",
            "auth.role_comedores_intervencion_ver",
            "intervenciones.view_intervencion",
            "auth.role_comedores_intervenciones_detalle",
            "auth.role_comedores_nomina_ver",
            "comedores.view_nomina",
            "auth.role_comedores_observaciones_detalle",
            "comedores.view_observacion",
            "auth.role_comedores_relevamiento_detalle",
            "relevamientos.view_relevamiento",
            "auth.role_comedores_relevamiento_ver",
        ),
    ),
    BootstrapGroupSeed(
        "Centro de Infancia Total",
        (
            "auth.role_centro_de_infancia_crear",
            "centrodeinfancia.add_centrodeinfancia",
            "auth.role_centro_de_infancia_editar",
            "centrodeinfancia.change_centrodeinfancia",
            "auth.role_centro_de_infancia_eliminar",
            "centrodeinfancia.delete_centrodeinfancia",
            "auth.role_centro_de_infancia_formulario_borrar",
            "centrodeinfancia.delete_formulariocdi",
            "auth.role_centro_de_infancia_formulario_crear",
            "centrodeinfancia.add_formulariocdi",
            "auth.role_centro_de_infancia_formulario_editar",
            "centrodeinfancia.change_formulariocdi",
            "auth.role_centro_de_infancia_formulario_ver",
            "centrodeinfancia.view_formulariocdi",
            "auth.role_centro_de_infancia_intervencion_borrar",
            "centrodeinfancia.delete_intervencioncentroinfancia",
            "auth.role_centro_de_infancia_intervencion_crear",
            "centrodeinfancia.add_intervencioncentroinfancia",
            "auth.role_centro_de_infancia_intervencion_editar",
            "centrodeinfancia.change_intervencioncentroinfancia",
            "auth.role_centro_de_infancia_listar",
            "centrodeinfancia.view_centrodeinfancia",
            "auth.role_centro_de_infancia_nomina_borrar",
            "centrodeinfancia.delete_nominacentroinfancia",
            "auth.role_centro_de_infancia_nomina_crear",
            "centrodeinfancia.add_nominacentroinfancia",
            "auth.role_centro_de_infancia_nomina_editar",
            "centrodeinfancia.change_nominacentroinfancia",
            "auth.role_centro_de_infancia_nomina_ver",
            "centrodeinfancia.view_nominacentroinfancia",
            "auth.role_centro_de_infancia_ver",
        ),
    ),
    BootstrapGroupSeed(
        "Comedores total",
        (
            "auth.role_comedores",
            "comedores.view_comedor",
            "auth.role_comedores_crear",
            "comedores.add_comedor",
            "auth.role_comedores_dupla_asignar",
            "duplas.change_dupla",
            "auth.role_comedores_editar",
            "comedores.change_comedor",
            "auth.role_comedores_eliminar",
            "comedores.delete_comedor",
            "auth.role_comedores_intervencion_crear",
            "intervenciones.add_intervencion",
            "auth.role_comedores_intervencion_editar",
            "intervenciones.change_intervencion",
            "auth.role_comedores_intervencion_ver",
            "intervenciones.view_intervencion",
            "auth.role_comedores_intervenciones_detalle",
            "auth.role_comedores_listar",
            "auth.role_comedores_nomina_borrar",
            "comedores.delete_nomina",
            "auth.role_comedores_nomina_crear",
            "comedores.add_nomina",
            "auth.role_comedores_nomina_editar",
            "comedores.change_nomina",
            "auth.role_comedores_nomina_ver",
            "comedores.view_nomina",
            "auth.role_comedores_observaciones_crear",
            "comedores.add_observacion",
            "auth.role_comedores_observaciones_detalle",
            "comedores.view_observacion",
            "auth.role_comedores_observaciones_editar",
            "comedores.change_observacion",
            "auth.role_comedores_observaciones_eliminar",
            "comedores.delete_observacion",
            "auth.role_comedores_relevamiento_crear",
            "relevamientos.add_relevamiento",
            "auth.role_comedores_relevamiento_detalle",
            "relevamientos.view_relevamiento",
            "auth.role_comedores_relevamiento_editar",
            "relevamientos.change_relevamiento",
            "auth.role_comedores_relevamiento_ver",
            "auth.role_comedores_ver",
            "auth.role_comunicado_archivar",
            "comunicados.change_comunicado",
            "auth.role_comunicado_comedores_archivar",
            "auth.role_comunicado_comedores_crear",
            "comunicados.add_comunicado",
            "auth.role_comunicado_comedores_editar",
            "auth.role_comunicado_comedores_publicar",
            "auth.role_comunicado_crear",
            "auth.role_comunicado_editar",
            "auth.role_comunicado_interno_archivar",
            "auth.role_comunicado_interno_crear",
            "auth.role_comunicado_interno_editar",
            "auth.role_comunicado_interno_publicar",
            "auth.role_comunicado_publicar",
            "acompanamientos.view_informacionrelevante",
            "admisiones.view_admision",
            "auth.role_coordinador_equipo_tecnico",
            "relevamientos.view_relevamiento",
            "auth.role_coordinador_general",
            "auth.role_abogado_dupla",
            "auth.role_acompanamiento_detalle",
            "auth.role_acompanamiento_listar",
            "auth.role_area_contable",
            "expedientespagos.view_expedientepago",
            "auth.role_area_legales",
            "auth.role_exportar_a_csv",
        ),
    ),
    BootstrapGroupSeed(
        "Celiaquia Total",
        (
            "auth.role_ciudadanos",
            "ciudadanos.view_ciudadano",
            "auth.role_coordinadorceliaquia",
            "celiaquia.view_expediente",
            "auth.role_tecnicoceliaquia",
            "auth.role_provinciaceliaquia",
        ),
    ),
    BootstrapGroupSeed(
        "Provincia VAT",
        (
            "auth.role_provincia_vat",
            "VAT.view_centro",
            "VAT.view_planversioncurricular",
            "VAT.add_planversioncurricular",
        ),
    ),
    BootstrapGroupSeed(
        "ReferenteCentroVAT",
        (
            "auth.role_referentecentrovat",
            "VAT.view_centro",
        ),
    ),
    BootstrapGroupSeed(
        "VAT SSE",
        (
            "auth.role_vat_sse",
            "VAT.view_centro",
            "VAT.view_planversioncurricular",
            "VAT.add_planversioncurricular",
            "VAT.change_planversioncurricular",
            "VAT.delete_planversioncurricular",
        ),
    ),
    BootstrapGroupSeed(
        "Tableros Total",
        (
            "auth.role_dashboard_centrodefamilia",
            "centrodefamilia.view_centro",
            "dashboard.view_dashboard",
            "auth.role_dashboard_comedor",
            "auth.role_tablero_datacalle_catamarca",
            "auth.role_tablero_datacalle_chaco",
            "auth.role_tablero_datacalle_chubut",
            "auth.role_tablero_datacalle_cordoba_alta_gracia",
            "auth.role_tablero_datacalle_cordoba_capital",
            "auth.role_tablero_datacalle_cordoba_san_francisco",
            "auth.role_tablero_datacalle_corrientes",
            "auth.role_tablero_datacalle_entre_rios",
            "auth.role_tablero_datacalle_general",
            "auth.role_tablero_datacalle_la_pampa",
            "auth.role_tablero_datacalle_mendoza",
            "auth.role_tablero_datacalle_misiones",
            "auth.role_tablero_datacalle_rio_negro",
            "auth.role_tablero_datacalle_salta",
            "auth.role_tablero_datacalle_san_juan",
            "auth.role_tablero_datacalle_san_lus",
            "auth.role_tablero_datacalle_santa_cruz",
            "auth.role_tablero_datacalle_santa_fe",
            "auth.role_tablero_datacalle_tucuman",
        ),
    ),
    BootstrapGroupSeed(
        "Tablero DataCalle General",
        ("auth.role_tablero_datacalle_general",),
    ),
    BootstrapGroupSeed(
        "Tablero DataCalle - Chaco",
        ("auth.role_tablero_datacalle_chaco",),
    ),
    BootstrapGroupSeed(
        "Tablero DataCalle - Misiones",
        ("auth.role_tablero_datacalle_misiones",),
    ),
    BootstrapGroupSeed(
        "Tablero DataCalle - Salta",
        ("auth.role_tablero_datacalle_salta",),
    ),
    BootstrapGroupSeed(
        "Tablero DataCalle - Corrientes",
        ("auth.role_tablero_datacalle_corrientes",),
    ),
    BootstrapGroupSeed(
        "Tablero DataCalle - Chubut",
        ("auth.role_tablero_datacalle_chubut",),
    ),
    BootstrapGroupSeed(
        "Tablero DataCalle - San Luis",
        ("auth.role_tablero_datacalle_san_lus",),
    ),
    BootstrapGroupSeed(
        "Tablero DataCalle - Entre Ríos",
        ("auth.role_tablero_datacalle_entre_rios",),
    ),
    BootstrapGroupSeed(
        "Tablero DataCalle - Mendoza",
        ("auth.role_tablero_datacalle_mendoza",),
    ),
    BootstrapGroupSeed(
        "Tablero DataCalle - San Juan",
        ("auth.role_tablero_datacalle_san_juan",),
    ),
    BootstrapGroupSeed(
        "Tablero DataCalle - Santa Cruz",
        ("auth.role_tablero_datacalle_santa_cruz",),
    ),
    BootstrapGroupSeed(
        "Tablero DataCalle - Santa Fe",
        ("auth.role_tablero_datacalle_santa_fe",),
    ),
    BootstrapGroupSeed(
        "Tablero DataCalle - La Pampa",
        ("auth.role_tablero_datacalle_la_pampa",),
    ),
    BootstrapGroupSeed(
        "Tablero DataCalle - Catamarca",
        ("auth.role_tablero_datacalle_catamarca",),
    ),
    BootstrapGroupSeed(
        "Tablero DataCalle - Rio Negro",
        ("auth.role_tablero_datacalle_rio_negro",),
    ),
    BootstrapGroupSeed(
        "Tablero DataCalle - Cordoba - Capital",
        ("auth.role_tablero_datacalle_cordoba_capital",),
    ),
    BootstrapGroupSeed(
        "Tablero DataCalle - Cordoba - San Francisco",
        ("auth.role_tablero_datacalle_cordoba_san_francisco",),
    ),
    BootstrapGroupSeed(
        "Tablero DataCalle - Cordoba - Alta Gracia",
        ("auth.role_tablero_datacalle_cordoba_alta_gracia",),
    ),
    BootstrapGroupSeed(
        "Tablero DataCalle - Tucuman",
        ("auth.role_tablero_datacalle_tucuman",),
    ),
    BootstrapGroupSeed(
        "Tablero Perfilamiento de Espacios Comunitarios",
        ("auth.role_tablero_perfilamiento_de_espacios_comunitarios",),
    ),
    BootstrapGroupSeed(
        "Tablero Seguimiento Espacios Comunitarios",
        ("auth.role_tablero_seguimiento_espacios_comunitarios",),
    ),
    BootstrapGroupSeed(
        "Tablero Aduana",
        ("auth.role_tablero_aduana",),
    ),
    BootstrapGroupSeed(
        "Tablero Aduana Ejecutivo",
        ("auth.role_tablero_aduana_ejecutivo",),
    ),
    BootstrapGroupSeed(
        "Tablero Coordinadores Alimentar Comunidad",
        ("auth.role_tablero_coordinadores_alimentar_comunidad",),
    ),
    BootstrapGroupSeed(
        "Tablero Prestación Alimentar",
        ("auth.role_tablero_prestacion_alimentar",),
    ),
    BootstrapGroupSeed(
        "Tablero Comedores Interno",
        ("auth.role_tablero_comedores_interno",),
    ),
    BootstrapGroupSeed(
        "Tablero DataCalle - Santa Fe Capital",
        ("auth.role_tablero_datacalle_santa_fe_capital",),
    ),
    BootstrapGroupSeed(
        "Tablero DataCalle - Santa Fe Rosario",
        ("auth.role_tablero_datacalle_santa_fe_rosario",),
    ),
    BootstrapGroupSeed(
        "Tablero DataCalle - Santa Fe Rafaela",
        ("auth.role_tablero_datacalle_santa_fe_rafaela",),
    ),
    BootstrapGroupSeed(
        "Comedores Visualización",
        (
            "comedores.view_comedor",
            "intervenciones.view_intervencion",
            "auth.role_comedores_intervenciones_detalle",
            "auth.role_comedores_nomina_ver",
            "comedores.view_nomina",
            "auth.role_comedores_observaciones_detalle",
            "comedores.view_observacion",
            "auth.role_comedores_relevamiento_detalle",
            "relevamientos.view_relevamiento",
            "auth.role_comedores_relevamiento_ver",
            "auth.role_comedores_ver",
            "acompanamientos.view_informacionrelevante",
            "admisiones.view_admision",
            "auth.role_acompanamiento_detalle",
            "expedientespagos.view_expedientepago",
        ),
    ),
    BootstrapGroupSeed(
        "Celiaquia Visualización",
        (
            "ciudadanos.view_ciudadano",
            "celiaquia.view_expediente",
        ),
    ),
    BootstrapGroupSeed(
        "Centros de Familia Total",
        (
            "auth.role_cdf_sse",
            "auth.role_referentecentro",
            "centrodefamilia.view_centro",
        ),
    ),
    BootstrapGroupSeed(
        "Centros de Familia Visualización",
        ("centrodefamilia.view_centro",),
    ),
    BootstrapGroupSeed(
        "Visualización total",
        (
            "acompanamientos.view_informacionrelevante",
            "admisiones.view_admision",
            "comedores.view_comedor",
            "auth.view_group",
            "auth.view_user",
            "expedientespagos.view_expedientepago",
            "centrodefamilia.view_centro",
            "centrodeinfancia.view_formulariocdi",
            "centrodeinfancia.view_centrodeinfancia",
            "centrodeinfancia.view_nominacentroinfancia",
            "ciudadanos.view_ciudadano",
            "intervenciones.view_intervencion",
            "auth.role_comedores_intervenciones_detalle",
            "comedores.view_nomina",
            "auth.role_comedores_observaciones_detalle",
            "comedores.view_observacion",
            "auth.role_comedores_relevamiento_detalle",
            "relevamientos.view_relevamiento",
            "celiaquia.view_expediente",
            "dashboard.view_dashboard",
            "core.view_montoprestacionprograma",
            "organizaciones.view_organizacion",
        ),
    ),
    BootstrapGroupSeed(
        "Centros de Infancia Total",
        (
            "auth.role_centro_de_infancia_crear",
            "centrodeinfancia.add_centrodeinfancia",
            "auth.role_centro_de_infancia_editar",
            "centrodeinfancia.change_centrodeinfancia",
            "auth.role_centro_de_infancia_eliminar",
            "centrodeinfancia.delete_centrodeinfancia",
            "auth.role_centro_de_infancia_formulario_borrar",
            "centrodeinfancia.delete_formulariocdi",
            "auth.role_centro_de_infancia_formulario_crear",
            "centrodeinfancia.add_formulariocdi",
            "auth.role_centro_de_infancia_formulario_editar",
            "centrodeinfancia.change_formulariocdi",
            "auth.role_centro_de_infancia_formulario_ver",
            "centrodeinfancia.view_formulariocdi",
            "auth.role_centro_de_infancia_intervencion_borrar",
            "centrodeinfancia.delete_intervencioncentroinfancia",
            "auth.role_centro_de_infancia_intervencion_crear",
            "centrodeinfancia.add_intervencioncentroinfancia",
            "auth.role_centro_de_infancia_intervencion_editar",
            "centrodeinfancia.change_intervencioncentroinfancia",
            "auth.role_centro_de_infancia_listar",
            "centrodeinfancia.view_centrodeinfancia",
            "auth.role_centro_de_infancia_nomina_borrar",
            "centrodeinfancia.delete_nominacentroinfancia",
            "auth.role_centro_de_infancia_nomina_crear",
            "centrodeinfancia.add_nominacentroinfancia",
            "auth.role_centro_de_infancia_nomina_editar",
            "centrodeinfancia.change_nominacentroinfancia",
            "auth.role_centro_de_infancia_nomina_ver",
            "centrodeinfancia.view_nominacentroinfancia",
            "auth.role_centro_de_infancia_ver",
        ),
    ),
    BootstrapGroupSeed(
        "Centros de Infancia Visualización",
        (
            "centrodeinfancia.view_formulariocdi",
            "centrodeinfancia.view_centrodeinfancia",
            "centrodeinfancia.view_nominacentroinfancia",
        ),
    ),
    BootstrapGroupSeed(
        "Carga de Nomina Comedores",
        (
            "auth.role_comedores",
            "comedores.view_comedor",
            "auth.role_comedores_ver",
            "auth.role_comedores_listar",
            "auth.role_comedores_nomina_borrar",
            "comedores.delete_nomina",
            "auth.role_comedores_nomina_crear",
            "comedores.add_nomina",
            "auth.role_comedores_nomina_editar",
            "comedores.change_nomina",
            "auth.role_comedores_nomina_ver",
            "comedores.view_nomina",
        ),
    ),
    BootstrapGroupSeed(
        "Gestion de comunicados comedores",
        (
            "auth.role_comunicado_archivar",
            "comunicados.change_comunicado",
            "auth.role_comunicado_comedores_archivar",
            "auth.role_comunicado_comedores_crear",
            "comunicados.add_comunicado",
            "auth.role_comunicado_comedores_editar",
            "auth.role_comunicado_comedores_publicar",
            "auth.role_comunicado_crear",
            "auth.role_comunicado_editar",
            "auth.role_comunicado_interno_archivar",
            "auth.role_comunicado_interno_crear",
            "auth.role_comunicado_interno_editar",
            "auth.role_comunicado_interno_publicar",
            "auth.role_comunicado_publicar",
        ),
    ),
    BootstrapGroupSeed(
        UserGroups.COMUNICADO_CREAR,
        (
            "auth.role_comunicado_crear",
            "comunicados.add_comunicado",
        ),
    ),
    BootstrapGroupSeed(
        UserGroups.COMUNICADO_EDITAR,
        (
            "auth.role_comunicado_editar",
            "comunicados.change_comunicado",
        ),
    ),
    BootstrapGroupSeed(
        UserGroups.COMUNICADO_PUBLICAR,
        ("auth.role_comunicado_publicar",),
    ),
    BootstrapGroupSeed(
        UserGroups.COMUNICADO_ARCHIVAR,
        ("auth.role_comunicado_archivar",),
    ),
    BootstrapGroupSeed(
        UserGroups.COMUNICADO_INTERNO_CREAR,
        (
            "auth.role_comunicado_interno_crear",
            "comunicados.add_comunicado",
        ),
    ),
    BootstrapGroupSeed(
        UserGroups.COMUNICADO_INTERNO_EDITAR,
        (
            "auth.role_comunicado_interno_editar",
            "comunicados.change_comunicado",
        ),
    ),
    BootstrapGroupSeed(
        UserGroups.COMUNICADO_INTERNO_PUBLICAR,
        ("auth.role_comunicado_interno_publicar",),
    ),
    BootstrapGroupSeed(
        UserGroups.COMUNICADO_INTERNO_ARCHIVAR,
        ("auth.role_comunicado_interno_archivar",),
    ),
    BootstrapGroupSeed(
        UserGroups.COMUNICADO_COMEDORES_CREAR,
        (
            "auth.role_comunicado_comedores_crear",
            "comunicados.add_comunicado",
        ),
    ),
    BootstrapGroupSeed(
        UserGroups.COMUNICADO_COMEDORES_EDITAR,
        (
            "auth.role_comunicado_comedores_editar",
            "comunicados.change_comunicado",
        ),
    ),
    BootstrapGroupSeed(
        UserGroups.COMUNICADO_COMEDORES_PUBLICAR,
        ("auth.role_comunicado_comedores_publicar",),
    ),
    BootstrapGroupSeed(
        UserGroups.COMUNICADO_COMEDORES_ARCHIVAR,
        ("auth.role_comunicado_comedores_archivar",),
    ),
    BootstrapGroupSeed(
        UserGroups.ADMIN,
        (
            "acompanamientos.view_informacionrelevante",
            "admisiones.view_admision",
            "auth.add_group",
            "auth.add_user",
            "auth.change_group",
            "auth.change_user",
            "auth.delete_group",
            "auth.delete_user",
            "auth.role_abogado_dupla",
            "auth.role_acompanamiento_detalle",
            "auth.role_acompanamiento_listar",
            "auth.role_admin",
            "auth.role_area_contable",
            "auth.role_area_legales",
            "auth.role_cdf_sse",
            "auth.role_centro_de_infancia_crear",
            "auth.role_centro_de_infancia_editar",
            "auth.role_centro_de_infancia_eliminar",
            "auth.role_centro_de_infancia_formulario_borrar",
            "auth.role_centro_de_infancia_formulario_crear",
            "auth.role_centro_de_infancia_formulario_editar",
            "auth.role_centro_de_infancia_formulario_ver",
            "auth.role_centro_de_infancia_intervencion_borrar",
            "auth.role_centro_de_infancia_intervencion_crear",
            "auth.role_centro_de_infancia_intervencion_editar",
            "auth.role_centro_de_infancia_listar",
            "auth.role_centro_de_infancia_nomina_borrar",
            "auth.role_centro_de_infancia_nomina_crear",
            "auth.role_centro_de_infancia_nomina_editar",
            "auth.role_centro_de_infancia_nomina_ver",
            "auth.role_centro_de_infancia_ver",
            "auth.role_ciudadanos",
            "auth.role_comedores",
            "auth.role_comedores_crear",
            "auth.role_comedores_dupla_asignar",
            "auth.role_comedores_editar",
            "auth.role_comedores_eliminar",
            "auth.role_comedores_intervencion_crear",
            "auth.role_comedores_intervencion_editar",
            "auth.role_comedores_intervencion_ver",
            "auth.role_comedores_intervenciones_detalle",
            "auth.role_comedores_listar",
            "auth.role_comedores_nomina_borrar",
            "auth.role_comedores_nomina_crear",
            "auth.role_comedores_nomina_editar",
            "auth.role_comedores_nomina_ver",
            "auth.role_comedores_observaciones_crear",
            "auth.role_comedores_observaciones_detalle",
            "auth.role_comedores_observaciones_editar",
            "auth.role_comedores_observaciones_eliminar",
            "auth.role_comedores_relevamiento_crear",
            "auth.role_comedores_relevamiento_detalle",
            "auth.role_comedores_relevamiento_editar",
            "auth.role_comedores_relevamiento_ver",
            "auth.role_comedores_ver",
            "auth.role_comunicado_archivar",
            "auth.role_comunicado_comedores_archivar",
            "auth.role_comunicado_comedores_crear",
            "auth.role_comunicado_comedores_editar",
            "auth.role_comunicado_comedores_publicar",
            "auth.role_comunicado_crear",
            "auth.role_comunicado_editar",
            "auth.role_comunicado_interno_archivar",
            "auth.role_comunicado_interno_crear",
            "auth.role_comunicado_interno_editar",
            "auth.role_comunicado_interno_publicar",
            "auth.role_comunicado_publicar",
            "auth.role_coordinador_equipo_tecnico",
            "auth.role_coordinador_general",
            "auth.role_coordinadorceliaquia",
            "auth.role_dashboard_centrodefamilia",
            "auth.role_dashboard_comedor",
            "auth.role_exportar_a_csv",
            "auth.role_organizaciones",
            "auth.role_provinciaceliaquia",
            "auth.role_referentecentro",
            "auth.role_tablero_datacalle_catamarca",
            "auth.role_tablero_datacalle_chaco",
            "auth.role_tablero_datacalle_chubut",
            "auth.role_tablero_datacalle_cordoba_alta_gracia",
            "auth.role_tablero_datacalle_cordoba_capital",
            "auth.role_tablero_datacalle_cordoba_san_francisco",
            "auth.role_tablero_datacalle_corrientes",
            "auth.role_tablero_datacalle_entre_rios",
            "auth.role_tablero_datacalle_general",
            "auth.role_tablero_datacalle_la_pampa",
            "auth.role_tablero_datacalle_mendoza",
            "auth.role_tablero_datacalle_misiones",
            "auth.role_tablero_datacalle_rio_negro",
            "auth.role_tablero_datacalle_salta",
            "auth.role_tablero_datacalle_san_juan",
            "auth.role_tablero_datacalle_san_lus",
            "auth.role_tablero_datacalle_santa_cruz",
            "auth.role_tablero_datacalle_santa_fe",
            "auth.role_tablero_datacalle_tucuman",
            "auth.role_tecnico_comedor",
            "auth.role_tecnicoceliaquia",
            "auth.view_group",
            "auth.view_user",
            "celiaquia.view_expediente",
            "centrodefamilia.view_centro",
            "centrodeinfancia.add_centrodeinfancia",
            "centrodeinfancia.add_formulariocdi",
            "centrodeinfancia.add_intervencioncentroinfancia",
            "centrodeinfancia.add_nominacentroinfancia",
            "centrodeinfancia.change_centrodeinfancia",
            "centrodeinfancia.change_formulariocdi",
            "centrodeinfancia.change_intervencioncentroinfancia",
            "centrodeinfancia.change_nominacentroinfancia",
            "centrodeinfancia.delete_centrodeinfancia",
            "centrodeinfancia.delete_formulariocdi",
            "centrodeinfancia.delete_intervencioncentroinfancia",
            "centrodeinfancia.delete_nominacentroinfancia",
            "centrodeinfancia.view_centrodeinfancia",
            "centrodeinfancia.view_formulariocdi",
            "centrodeinfancia.view_nominacentroinfancia",
            "ciudadanos.view_ciudadano",
            "comedores.add_comedor",
            "comedores.add_nomina",
            "comedores.add_observacion",
            "comedores.change_comedor",
            "comedores.change_nomina",
            "comedores.change_observacion",
            "comedores.delete_comedor",
            "comedores.delete_nomina",
            "comedores.delete_observacion",
            "comedores.view_comedor",
            "comedores.view_nomina",
            "comedores.view_observacion",
            "comunicados.add_comunicado",
            "comunicados.change_comunicado",
            "dashboard.view_dashboard",
            "duplas.change_dupla",
            "expedientespagos.view_expedientepago",
            "intervenciones.add_intervencion",
            "intervenciones.change_intervencion",
            "intervenciones.view_intervencion",
            "organizaciones.view_organizacion",
            "relevamientos.add_relevamiento",
            "relevamientos.change_relevamiento",
            "relevamientos.view_relevamiento",
        ),
    ),
)

BOOTSTRAP_GROUPS = LISTADO_DEFINED_GROUPS

BOOTSTRAP_GROUPS_BY_NAME = {group.name: group for group in BOOTSTRAP_GROUPS}

if len(BOOTSTRAP_GROUPS_BY_NAME) != len(BOOTSTRAP_GROUPS):
    raise ValueError("La semilla bootstrap de grupos contiene nombres duplicados.")


def bootstrap_group_names() -> tuple[str, ...]:
    """Retorna los grupos base que deben existir en todos los entornos."""
    return tuple(group.name for group in BOOTSTRAP_GROUPS)


def permission_codes_for_bootstrap_group(group_name: str) -> tuple[str, ...]:
    """Retorna permisos canónicos declarados para un grupo bootstrap."""
    group = BOOTSTRAP_GROUPS_BY_NAME.get(str(group_name or "").strip())
    if not group:
        return tuple()
    return group.permission_codes
