# Generated by Django 4.2.20 on 2025-06-26 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("comedores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comedor",
            name="localidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.localidad",
            ),
        ),
        migrations.AlterField(
            model_name="comedor",
            name="municipio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.municipio",
            ),
        ),
        migrations.AlterField(
            model_name="comedor",
            name="provincia",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.provincia",
            ),
        ),
        migrations.AlterField(
            model_name="nomina",
            name="sexo",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.sexo",
            ),
        ),
    ]
