# Generated by Django 4.2.16 on 2025-01-15 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("configuraciones", "0002_sexo"),
        ("comedores", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomina",
            name="fk_sexo",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="configuraciones.sexo",
            ),
        ),
    ]
