# Generated by Django 4.0.2 on 2024-11-13 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0004_provincia_alter_localidad_options_and_more'),
        ('comedores', '0002_relevamiento_gestionar_uid_relevamiento_observacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedor',
            name='localidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='configuraciones.localidad'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='configuraciones.municipio'),
        ),
        migrations.AlterField(
            model_name='comedor',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='configuraciones.provincia'),
        ),
    ]
