# Generated by Django 4.2.16 on 2025-01-23 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizaciones", "0001_initial"),
        ("comedores", "0002_alter_tipodecomedor_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="comedor",
            name="organizacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="organizaciones.organizacion",
            ),
        ),
    ]
