# Generated by Django 4.2.16 on 2024-12-16 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0003_alter_comedor_localidad_alter_comedor_municipio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValorComida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99999),
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Valor de comida",
                "verbose_name_plural": "Valores de comida",
                "ordering": ["nombre"],
            },
        ),
    ]
