# Generated by Django 4.2.16 on 2024-12-18 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0003_alter_comedor_localidad_alter_comedor_municipio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadosIntervencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "EstadosIntervencion",
                "verbose_name_plural": "EstadosIntervenciones",
            },
        ),
        migrations.CreateModel(
            name="TipoIntervencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "TipoIntervencion",
                "verbose_name_plural": "TiposIntervencion",
            },
        ),
        migrations.CreateModel(
            name="ValorComida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name="comedor",
            name="foto_legajo",
            field=models.ImageField(blank=True, null=True, upload_to="comedor/"),
        ),
        migrations.AlterField(
            model_name="comedor",
            name="gestionar_uid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="relevamiento",
            name="gestionar_uid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="SubIntervencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "fk_subintervencion",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="comedores.tipointervencion",
                    ),
                ),
            ],
            options={
                "verbose_name": "SubIntervencion",
                "verbose_name_plural": "SubIntervenciones",
            },
        ),
        migrations.CreateModel(
            name="ImagenComedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagen", models.ImageField(upload_to="comedor/")),
                (
                    "comedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="comedores.comedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Intervencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "fk_comedor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="comedores.comedor",
                    ),
                ),
                (
                    "fk_estado",
                    models.ForeignKey(
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="comedores.estadosintervencion",
                    ),
                ),
                (
                    "fk_subintervencion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="comedores.subintervencion",
                    ),
                ),
                (
                    "fk_tipo_intervencion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="comedores.tipointervencion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intervencion",
                "verbose_name_plural": "Intervenciones",
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(
                        fields=["fk_comedor"], name="comedores_i_fk_come_87e415_idx"
                    )
                ],
            },
        ),
    ]
