# Generated by Django 4.2.20 on 2025-06-29 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ciudadanos", "0001_initial"),
        ("comedores", "0003_alter_nomina_options_remove_nomina_ciudadano_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nomina",
            name="apellido",
        ),
        migrations.RemoveField(
            model_name="nomina",
            name="dni",
        ),
        migrations.RemoveField(
            model_name="nomina",
            name="nombre",
        ),
        migrations.RemoveField(
            model_name="nomina",
            name="sexo",
        ),
        migrations.AddField(
            model_name="nomina",
            name="ciudadano",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nominas",
                to="ciudadanos.ciudadano",
            ),
            preserve_default=False,
        ),
    ]
