# Generated by Django 4.2.20 on 2025-07-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0003_alter_comedor_localidad_alter_comedor_municipio_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="observacion",
            unique_together=set(),
        ),
    ]
