# Generated by Django 4.2.16 on 2024-12-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0004_alter_comedor_gestionar_uid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValorComida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=50)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateField()),
            ],
        ),
    ]
