# Generated by Django 4.2.16 on 2024-12-17 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0004_alter_comedor_gestionar_uid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comedor",
            name="foto_legajo",
            field=models.ImageField(blank=True, null=True, upload_to="comedor/"),
        ),
        migrations.CreateModel(
            name="ImagenComedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagen", models.ImageField(upload_to="comedor/")),
                (
                    "comedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="comedores.comedor",
                    ),
                ),
            ],
        ),
    ]
