# Generated by Django 4.2.20 on 2025-08-14 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0004_alter_observacion_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="TerritorialCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gestionar_uid", models.CharField(max_length=100, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "fecha_ultimo_sync",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Cache Territorial",
                "verbose_name_plural": "Cache Territoriales",
                "db_table": "comedores_territorial_cache",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TerritorialSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("exitoso", models.BooleanField()),
                ("territoriales_sincronizados", models.IntegerField(default=0)),
                ("error_mensaje", models.TextField(blank=True)),
                ("comedor_id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Log Sync Territorial",
                "verbose_name_plural": "Logs Sync Territoriales",
                "db_table": "comedores_territorial_sync_log",
                "ordering": ["-fecha"],
            },
        ),
    ]
