# Generated by Django 4.2.16 on 2025-01-29 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0005_categoriacomedor_clasificacioncomedor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clasificacioncomedor",
            name="nombre",
        ),
        migrations.AddField(
            model_name="clasificacioncomedor",
            name="fecha",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
