# Generated by Django 4.2.16 on 2024-12-19 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0006_alter_colaboradores_cantidad_colaboradores_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="espaciococina",
            name="abastecimiento_agua",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="comedores.tipoagua",
                verbose_name="2.2.8 El abastecimiento del agua es con",
            ),
        ),
        migrations.AlterField(
            model_name="espaciococina",
            name="abastecimiento_combustible",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="espacios",
                to="comedores.tipocombustible",
                verbose_name="2.2.7 Para cocinar utiliza",
            ),
        ),
        migrations.AlterField(
            model_name="espacioprestacion",
            name="frecuencia_limpieza",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="comedores.frecuencialimpieza",
                verbose_name="2.4.1 ¿Con qué frecuencia se realiza la limpieza de las instalaciones?",
            ),
        ),
        migrations.AlterField(
            model_name="espacioprestacion",
            name="gestion_quejas",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="comedores.tipogestionquejas",
                verbose_name="2.3.10 ¿El Comedor/Merendero cuenta con alguna forma de registro de los reclamos sobre la prestacion alimentaria",
            ),
        ),
    ]
