# Generated by Django 4.2.20 on 2025-08-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0006_add_provincia_to_territorial_cache"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="territorialcache",
            new_name="comedores_t_provinc_38a553_idx",
            old_name="comedores_territorial_provincia_activo_idx",
        ),
    ]
