# Generated by Django 4.2.20 on 2025-10-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "comedores",
            "0007_rename_comedores_territorial_provincia_activo_idx_comedores_t_provinc_38a553_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="comedor",
            name="estado_general",
            field=models.CharField(
                choices=[
                    ("Activo", "Activo"),
                    ("Inactivo", "Inactivo"),
                    ("Sin definir", "Sin definir"),
                ],
                default="Activo",
                max_length=32,
                verbose_name="Estado general",
            ),
        ),
    ]
