# Generated by Django 4.2.20 on 2025-10-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0008_comedor_estado_general"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comedor",
            name="estado_general",
            field=models.CharField(
                choices=[
                    ("Activo", "Activo"),
                    ("Inactivo", "Inactivo"),
                    ("En proceso - Incorporación", "En proceso - Incorporación"),
                    ("En proceso - Renovación", "En proceso - Renovación"),
                    ("Sin definir", "Sin definir"),
                ],
                default="Activo",
                max_length=32,
                verbose_name="Estado general",
            ),
        ),
    ]
