# Generated by Django 4.2.16 on 2025-01-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0009_alter_comedor_barrio_alter_comedor_calle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="observacion",
            name="gestionar_uid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
