# Generated by Django 4.2.20 on 2025-10-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0009_alter_comedor_estado_general"),
    ]

    operations = [
        migrations.AddField(
            model_name="comedor",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
