# Generated by Django 4.2.20 on 2025-10-28 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("comedores", "0010_comedor_fecha_creacion"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditComedorPrograma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comedor_programa_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "comedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programa_changes",
                        to="comedores.comedor",
                    ),
                ),
                (
                    "from_programa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programa_changes_from",
                        to="comedores.programas",
                    ),
                ),
                (
                    "to_programa",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="programa_changes_to",
                        to="comedores.programas",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cambio de programa del comedor",
                "verbose_name_plural": "Cambios de programa del comedor",
                "ordering": ["-changed_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["comedor", "changed_at"],
                        name="comedores_a_comedor_c6234f_idx",
                    ),
                    models.Index(
                        fields=["changed_by"], name="comedores_a_changed_432a95_idx"
                    ),
                ],
            },
        ),
    ]
