# Generated by Django 4.2.20 on 2025-11-11 20:18

from django.db import migrations, models


def _map_legacy_nombre(nombre: str) -> str:
    if not nombre:
        return "pendiente"
    normalized = nombre.strip().lower()
    if normalized in {"pendiente", "pendientes"} or "pend" in normalized:
        return "pendiente"
    if normalized in {"activo", "activos"} or "act" in normalized or "habil" in normalized:
        return "activo"
    if (
        normalized in {"baja", "bajas", "inactivo", "inactivos"}
        or "baj" in normalized
        or "inac" in normalized
        or "fin" in normalized
        or "cerr" in normalized
    ):
        return "baja"
    return "pendiente"


def copy_estado_forward(apps, schema_editor):
    Nomina = apps.get_model("comedores", "Nomina")
    try:
        EstadoIntervencion = apps.get_model("ciudadanos", "EstadoIntervencion")
    except LookupError:
        EstadoIntervencion = None

    db_alias = schema_editor.connection.alias
    legacy_map = {}
    if EstadoIntervencion is not None:
        legacy_map = {
            estado.pk: _map_legacy_nombre(getattr(estado, "nombre", ""))
            for estado in EstadoIntervencion.objects.using(db_alias).all()
        }

    for nomina in Nomina.objects.using(db_alias).all():
        legacy_value = legacy_map.get(getattr(nomina, "estado_id", None))
        if legacy_value is None:
            legacy_value = getattr(nomina, "estado", None)
            if legacy_value not in {"pendiente", "activo", "baja"}:
                legacy_value = _map_legacy_nombre(str(legacy_value or ""))
        Nomina.objects.using(db_alias).filter(pk=nomina.pk).update(
            estado_nuevo=legacy_value or "pendiente"
        )


def copy_estado_backward(apps, schema_editor):
    Nomina = apps.get_model("comedores", "Nomina")
    Nomina.objects.using(schema_editor.connection.alias).update(estado=None)


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0012_alter_comedor_estado_general"),
    ]

    operations = [
        migrations.AddField(
            model_name="nomina",
            name="estado_nuevo",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("activo", "Activo"),
                    ("baja", "Baja"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.RunPython(copy_estado_forward, copy_estado_backward),
        migrations.RemoveField(
            model_name="nomina",
            name="estado",
        ),
        migrations.RenameField(
            model_name="nomina",
            old_name="estado_nuevo",
            new_name="estado",
        ),
    ]
