# Generated by Django 4.2.16 on 2025-01-09 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0010_observacion_gestionar_uid"),
        ("comedores", "0012_nomina_fk_sexo"),
    ]

    operations = []
