# Generated by Django 4.2.20 on 2025-11-14 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0013_comedor_estado_validacion_comedor_fecha_validado_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="historialvalidacion",
            new_name="comedores_h_comedor_86d7a4_idx",
            old_name="comedores_h_comedor_b8b8c8_idx",
        ),
    ]
