# Generated by Django 4.2.16 on 2025-01-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0013_merge_20250109_1245"),
    ]

    operations = [
        migrations.AddField(
            model_name="relevamiento",
            name="docPDF",
            field=models.URLField(blank=True, null=True),
        ),
    ]
