# Generated by Django 4.2.16 on 2025-01-13 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0013_merge_20250109_1245"),
    ]

    operations = [
        migrations.AddField(
            model_name="comedor",
            name="fk_tipocomedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="comedores.tipodecomedor",
            ),
        ),
        migrations.AddField(
            model_name="relevamiento",
            name="docPDF",
            field=models.URLField(blank=True, null=True),
        ),
    ]
