# Generated by Django 4.2.16 on 2025-01-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0014_comedor_fk_tipocomedor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comedor",
            old_name="fk_tipocomedor",
            new_name="tipocomedor",
        ),
    ]
