# Generated by Django 4.2.16 on 2025-01-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0014_comedor_fk_tipocomedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="espaciococina",
            name="abastecimiento_combustible",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="espacios",
                to="comedores.tipocombustible",
                verbose_name="2.2.7 Para cocinar utiliza",
            ),
        ),
    ]
