# Generated by Django 4.2.16 on 2025-03-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0015_entrevistado_relevamiento_entrevistado"),
    ]

    operations = [
        migrations.AddField(
            model_name="comedor",
            name="idExterno",
            field=models.IntegerField(blank=True, null=True, verbose_name="Id Externo"),
        ),
    ]
