# Generated by Django 4.2.16 on 2025-02-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0015_remove_comedor_gestionar_uid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fuenterecursos",
            name="recursos_donaciones_particulares",
        ),
        migrations.RemoveField(
            model_name="fuenterecursos",
            name="recursos_estado_municipal",
        ),
        migrations.RemoveField(
            model_name="fuenterecursos",
            name="recursos_estado_nacional",
        ),
        migrations.RemoveField(
            model_name="fuenterecursos",
            name="recursos_estado_provincial",
        ),
        migrations.RemoveField(
            model_name="fuenterecursos",
            name="recursos_otros",
        ),
        migrations.AddField(
            model_name="fuenterecursos",
            name="recursos_donaciones_particulares",
            field=models.ManyToManyField(
                blank=True,
                related_name="fuentes_donaciones_particulares",
                to="comedores.tiporecurso",
                verbose_name="4.1.9 ¿Qué tipo de recursos recibe de donaciones particulares?",
            ),
        ),
        migrations.AddField(
            model_name="fuenterecursos",
            name="recursos_estado_municipal",
            field=models.ManyToManyField(
                blank=True,
                related_name="fuentes_estado_municipal",
                to="comedores.tiporecurso",
                verbose_name="4.1.15 ¿Qué tipo de recursos recibe del estado municipal?",
            ),
        ),
        migrations.AddField(
            model_name="fuenterecursos",
            name="recursos_estado_nacional",
            field=models.ManyToManyField(
                blank=True,
                related_name="fuentes_estado_nacional",
                to="comedores.tiporecurso",
                verbose_name="4.1.11 ¿Qué tipo de recursos recibe del estado nacional?",
            ),
        ),
        migrations.AddField(
            model_name="fuenterecursos",
            name="recursos_estado_provincial",
            field=models.ManyToManyField(
                blank=True,
                related_name="fuentes_estado_provincial",
                to="comedores.tiporecurso",
                verbose_name="4.1.13 ¿Qué tipo de recursos recibe del estado provincial?",
            ),
        ),
        migrations.AddField(
            model_name="fuenterecursos",
            name="recursos_otros",
            field=models.ManyToManyField(
                blank=True,
                related_name="fuentes_otros",
                to="comedores.tiporecurso",
                verbose_name="4.1.19 ¿Qué tipo de recursos recibe de otras fuentes?",
            ),
        ),
    ]
