# Generated by Django 4.2.20 on 2025-11-15 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0013_estadoactividad_estadodetalle_estadogeneral_and_more"),
        (
            "comedores",
            "0015_rename_comedores_h_comedor_b8b8c8_idx_comedores_h_comedor_86d7a4_idx",
        ),
    ]

    operations = []
