# Generated by Django 4.2.16 on 2025-01-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0016_referente_funcion_relevamiento_responsable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relevamiento",
            name="responsable_es_referente",
            field=models.BooleanField(default=True),
        ),
    ]
