# Generated by Django 4.2.16 on 2025-03-11 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "comedores",
            "0016_remove_fuenterecursos_recursos_donaciones_particulares_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoFrecuenciaBolsones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Frecuencia de entrega de bolsones",
                "verbose_name_plural": "Frecuencias de entrega de bolsones",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoModuloBolsones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Frecuencia de entrega de bolsones",
                "verbose_name_plural": "Frecuencias de entrega de bolsones",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoOtrosRecepcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Otros tipos de insumos recibidos",
                "verbose_name_plural": "Otros tipos de insumos recibidos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="PuntoEntregas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reciben_otros_recepcion",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Otros"
                    ),
                ),
                (
                    "otros_punto_entregas",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Otros punto de entrega",
                    ),
                ),
                ("existe_punto_entregas", models.BooleanField(default=False)),
                ("funciona_punto_entregas", models.BooleanField(default=False)),
                ("observa_entregas", models.BooleanField(default=False)),
                (
                    "retiran_mercaderias_distribucion",
                    models.BooleanField(default=False),
                ),
                ("retiran_mercaderias_comercio", models.BooleanField(default=False)),
                ("reciben_dinero", models.BooleanField(default=False)),
                ("Registran_entrega_bolsones", models.BooleanField(default=False)),
                (
                    "frecuencia_entrega_bolsones",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comedores.tipofrecuenciabolsones",
                        verbose_name="Frecuencia de entrega de bolsones",
                    ),
                ),
                (
                    "frecuencia_recepcion_mercaderias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="frecuencia_recepcion_mercaderias",
                        to="comedores.tipofrecuenciabolsones",
                        verbose_name="frecuencia de recepcion de mercaderias",
                    ),
                ),
                (
                    "tipo_comedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comedores.tipodecomedor",
                        verbose_name="Tipo de comedor",
                    ),
                ),
                (
                    "tipo_modulo_bolsones",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comedores.tipomodulobolsones",
                        verbose_name="Tipo de modulo de bolsones",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="relevamiento",
            name="punto_entregas",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="comedores.puntoentregas",
            ),
        ),
    ]
