# Generated by Django 4.2.20 on 2025-11-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0017_alter_comedor_estado_validacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="historialvalidacion",
            name="opciones_no_validar",
            field=models.JSONField(
                blank=True,
                help_text="Opciones seleccionadas cuando se marca como no validado",
                null=True,
                verbose_name="Opciones de no validación",
            ),
        ),
        migrations.AlterField(
            model_name="historialvalidacion",
            name="comentario",
            field=models.TextField(blank=True, null=True, verbose_name="Comentario"),
        ),
    ]
