# Generated by Django 4.2.16 on 2025-03-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0017_tipofrecuenciabolsones_tipomodulobolsones_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="puntoentregas",
            old_name="Registran_entrega_bolsones",
            new_name="registran_entrega_bolsones",
        ),
    ]
