# Generated by Django 4.2.16 on 2025-01-15 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0018_alter_espaciococina_abastecimiento_combustible"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tipodecomedor",
            options={
                "ordering": ["id"],
                "verbose_name": "TipodeComedor",
                "verbose_name_plural": "TipodeComedor",
            },
        ),
    ]
