# Generated by Django 4.2.16 on 2025-03-18 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0019_merge_20250317_1132"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comedor",
            old_name="idExterno",
            new_name="id_externo",
        ),
    ]
