# Generated by Django 4.2.16 on 2025-03-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0020_rename_idexterno_comedor_id_externo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relevamiento",
            name="referente_comedor",
        ),
    ]
