# Generated by Django 4.2.20 on 2026-01-02 00:00

import django.core.validators
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0020_alter_comedor_comienzo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comedor",
            name="comienzo",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(timezone.now().year),
                ],
                verbose_name="Año en el que comenzó a funcionar",
            ),
        ),
    ]
