# Generated by Django 4.2.27 on 2026-01-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0020_alter_comedor_comienzo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomina",
            name="estado",
            field=models.CharField(
                choices=[
                    ("activo", "Activo"),
                    ("pendiente", "Pendiente"),
                    ("baja", "Baja"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
    ]
