# Generated by Django 4.2.27 on 2026-02-09 00:00

from django.db import migrations
import core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0021_alter_nomina_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referente",
            name="mail",
            field=core.fields.UnicodeEmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Mail del referente",
            ),
        ),
    ]
