# Generated by Django 4.2.16 on 2025-03-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0020_alter_anexo_servicio_internet"),
        ("comedores", "0021_remove_relevamiento_referente_comedor"),
    ]

    operations = []
