# Generated by Django 4.2.16 on 2025-03-27 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0022_merge_20250318_1534"),
        ("comedores", "0022_merge_20250318_1554"),
    ]

    operations = []
