# Generated by Django 4.2.20 on 2025-05-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0022_merge_20250318_1554"),
    ]

    operations = [
        migrations.AddField(
            model_name="comedor",
            name="codigo_de_proyecto",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Código de Proyecto"
            ),
        ),
    ]
