# Generated by Django 4.2.16 on 2025-04-14 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("duplas", "0002_dupla_estado_alter_dupla_fecha"),
        ("comedores", "0022_merge_20250318_1554"),
    ]

    operations = [
        migrations.AddField(
            model_name="comedor",
            name="dupla",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="duplas.dupla",
            ),
        ),
    ]
