# Generated by Django 4.2.20 on 2025-06-10 21:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0023_comedor_codigo_de_proyecto"),
        ("duplas", "0002_dupla_estado_alter_dupla_fecha"),
    ]

    operations = [
        migrations.AddField(
            model_name="comedor",
            name="dupla",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="duplas.dupla",
            ),
        ),
        migrations.AddField(
            model_name="comedor",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Ingreso", "Sin Ingreso"),
                    ("Asignado a Dupla Técnica", "Asignado a Dupla Técnica"),
                ],
                default="Sin Ingreso",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="nomina",
            name="estado",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ciudadanos.estadointervencion",
            ),
        ),
        migrations.AlterField(
            model_name="comedor",
            name="calle",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="La dirección solo puede contener letras, números, espacios y los caracteres ., -",
                        regex="^[a-zA-Z0-9\\s.,áéíóúÁÉÍÓÚñÑ-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="comedor",
            name="departamento",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="La dirección solo puede contener letras, números, espacios y los caracteres ., -",
                        regex="^[a-zA-Z0-9\\s.,áéíóúÁÉÍÓÚñÑ-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="comedor",
            name="entre_calle_1",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="La dirección solo puede contener letras, números, espacios y los caracteres ., -",
                        regex="^[a-zA-Z0-9\\s.,áéíóúÁÉÍÓÚñÑ-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="comedor",
            name="entre_calle_2",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="La dirección solo puede contener letras, números, espacios y los caracteres ., -",
                        regex="^[a-zA-Z0-9\\s.,áéíóúÁÉÍÓÚñÑ-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="comedor",
            name="localidad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="configuraciones.localidad",
            ),
        ),
        migrations.AlterField(
            model_name="comedor",
            name="lote",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="La dirección solo puede contener letras, números, espacios y los caracteres ., -",
                        regex="^[a-zA-Z0-9\\s.,áéíóúÁÉÍÓÚñÑ-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="comedor",
            name="manzana",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="La dirección solo puede contener letras, números, espacios y los caracteres ., -",
                        regex="^[a-zA-Z0-9\\s.,áéíóúÁÉÍÓÚñÑ-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="comedor",
            name="municipio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="configuraciones.municipio",
            ),
        ),
        migrations.AlterField(
            model_name="comedor",
            name="piso",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="La dirección solo puede contener letras, números, espacios y los caracteres ., -",
                        regex="^[a-zA-Z0-9\\s.,áéíóúÁÉÍÓÚñÑ-]*$",
                    )
                ],
            ),
        ),
    ]
