# Generated by Django 4.2.16 on 2025-04-15 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0023_admisiones_tipoconvenio_estadosadmisiones_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archivosadmision",
            name="admision",
        ),
        migrations.RemoveField(
            model_name="archivosadmision",
            name="documentacion",
        ),
        migrations.RemoveField(
            model_name="documentacion",
            name="convenios",
        ),
        migrations.RemoveField(
            model_name="duplacontacto",
            name="comedor",
        ),
        migrations.RemoveField(
            model_name="duplacontacto",
            name="usuario",
        ),
        migrations.DeleteModel(
            name="Admisiones",
        ),
        migrations.DeleteModel(
            name="ArchivosAdmision",
        ),
        migrations.DeleteModel(
            name="Documentacion",
        ),
        migrations.DeleteModel(
            name="DuplaContacto",
        ),
        migrations.DeleteModel(
            name="EstadosAdmisiones",
        ),
        migrations.DeleteModel(
            name="TipoConvenio",
        ),
    ]
