# Generated by Django 4.2.16 on 2025-04-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0023_comedor_dupla"),
    ]

    operations = [
        migrations.AddField(
            model_name="comedor",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Ingreso", "Sin Ingreso"),
                    ("Asignado a Dupla Técnica", "Asignado a Dupla Técnica"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
