# Generated by Django 4.2.27 on 2026-03-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0024_nomina_switch_comedor_to_admision"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="nomina",
            index=models.Index(
                fields=["admision"], name="comedores_n_admisio_b94ec3_idx"
            ),
        ),
    ]
