# Generated by Django 4.2.16 on 2025-04-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0024_remove_archivosadmision_admision_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="intervencion",
            name="comedores_i_fk_come_87e415_idx",
        ),
        migrations.RemoveIndex(
            model_name="nomina",
            name="comedores_n_fk_come_c88eb9_idx",
        ),
        migrations.RenameField(
            model_name="intervencion",
            old_name="fk_comedor",
            new_name="comedor",
        ),
        migrations.RenameField(
            model_name="intervencion",
            old_name="fk_estado",
            new_name="estado",
        ),
        migrations.RenameField(
            model_name="intervencion",
            old_name="fk_subintervencion",
            new_name="subintervencion",
        ),
        migrations.RenameField(
            model_name="intervencion",
            old_name="fk_tipo_intervencion",
            new_name="tipo_intervencion",
        ),
        migrations.RenameField(
            model_name="nomina",
            old_name="fk_comedor",
            new_name="comedor",
        ),
        migrations.RenameField(
            model_name="nomina",
            old_name="fk_estado",
            new_name="estado",
        ),
        migrations.RenameField(
            model_name="nomina",
            old_name="fk_sexo",
            new_name="sexo",
        ),
        migrations.RenameField(
            model_name="subintervencion",
            old_name="fk_subintervencion",
            new_name="subintervencion",
        ),
        migrations.AddIndex(
            model_name="intervencion",
            index=models.Index(
                fields=["comedor"], name="comedores_i_comedor_6fe28a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="nomina",
            index=models.Index(
                fields=["comedor"], name="comedores_n_comedor_2179d8_idx"
            ),
        ),
    ]
