# Generated by Django 4.2.16 on 2025-04-21 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("duplas", "0002_dupla_estado_alter_dupla_fecha"),
        (
            "comedores",
            "0025_remove_intervencion_comedores_i_fk_come_87e415_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="comedor",
            name="dupla",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="duplas.dupla",
            ),
        ),
        migrations.AddField(
            model_name="comedor",
            name="estado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Sin Ingreso", "Sin Ingreso"),
                    ("Asignado a Dupla Técnica", "Asignado a Dupla Técnica"),
                ],
                default="Sin Ingreso",
                max_length=255,
                null=True,
            ),
        ),
    ]
