# Generated by Django 4.2.27 on 2026-03-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0025_nomina_comedores_n_admisio_b94ec3_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="nomina",
            name="comedores_n_admisio_b94ec3_idx",
        ),
    ]
