# Generated by Django 4.2.16 on 2025-04-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0026_comedor_dupla_comedor_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anexo",
            name="actividades_culturales",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="anexo",
            name="actividades_discapacidad",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="anexo",
            name="actividades_huerta",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="anexo",
            name="actividades_jardin_infantes",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="anexo",
            name="actividades_jardin_maternal",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="anexo",
            name="actividades_recreativas",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="anexo",
            name="actividades_religiosas",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="anexo",
            name="alfabetizacion_terminalidad",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="anexo",
            name="apoyo_escolar",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="anexo",
            name="capacitaciones_talleres",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="anexo",
            name="comedor_merendero",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="anexo",
            name="emprendimientos_productivos",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="anexo",
            name="espacio_huerta",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="anexo",
            name="insumos_organizacion",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="anexo",
            name="necesidades_alimentarias",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="anexo",
            name="otras_actividades",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="anexo",
            name="promocion_salud",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="anexo",
            name="servicio_internet",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="anexo",
            name="zona_inundable",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="colaboradores",
            name="colaboradores_capacitados_salud_seguridad",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="colaboradores",
            name="colaboradores_recibieron_capacitacion_alimentos",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="colaboradores",
            name="colaboradores_recibieron_capacitacion_emergencias",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="colaboradores",
            name="colaboradores_recibieron_capacitacion_violencia",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="¿Los colaboradores recibieron capacitación sobre prevención de violencia de género incluyendo acoso sexual, explotación sexual y abuso infantil?",
            ),
        ),
        migrations.AlterField(
            model_name="espaciococina",
            name="almacenamiento_alimentos_secos",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="espaciococina",
            name="espacio_elaboracion_alimentos",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="espaciococina",
            name="freezer",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="espaciococina",
            name="heladera",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="espaciococina",
            name="instalacion_electrica",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="espaciococina",
            name="otros_residuos",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="espaciococina",
            name="recipiente_otros_residuos",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="espaciococina",
            name="recipiente_residuos_organicos",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="espaciococina",
            name="recipiente_residuos_reciclables",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="espacioprestacion",
            name="espacio_equipado",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="espacioprestacion",
            name="salida_emergencia_senializada",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="espacioprestacion",
            name="tiene_botiquin",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="espacioprestacion",
            name="tiene_buena_iluminacion",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="espacioprestacion",
            name="tiene_equipacion_incendio",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="espacioprestacion",
            name="tiene_salida_emergencia",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="espacioprestacion",
            name="tiene_sanitarios",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="espacioprestacion",
            name="tiene_ventilacion",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="fuentecompras",
            name="almacen_cercano",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="fuentecompras",
            name="carniceria",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="fuentecompras",
            name="ferias_comunales",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="fuentecompras",
            name="granja",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="fuentecompras",
            name="mayoristas",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="fuentecompras",
            name="mercado_central",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="fuentecompras",
            name="otro",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="fuentecompras",
            name="pescaderia",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="fuentecompras",
            name="supermercado",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="fuentecompras",
            name="verduleria",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="puntoentregas",
            name="existe_punto_entregas",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="puntoentregas",
            name="funciona_punto_entregas",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="puntoentregas",
            name="observa_entregas",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="puntoentregas",
            name="reciben_dinero",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="puntoentregas",
            name="registran_entrega_bolsones",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="puntoentregas",
            name="retiran_mercaderias_comercio",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="puntoentregas",
            name="retiran_mercaderias_distribucion",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="relevamiento",
            name="responsable_es_referente",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
