# Generated by Django 4.2.16 on 2025-04-22 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0027_alter_anexo_actividades_culturales_and_more"),
        ("comedores", "0027_alter_comedor_localidad_alter_comedor_municipio"),
    ]

    operations = []
