# Generated by Django 4.2.16 on 2025-04-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0028_merge_20250422_1805"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intervencion",
            name="comedor",
        ),
        migrations.RemoveField(
            model_name="intervencion",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="intervencion",
            name="subintervencion",
        ),
        migrations.RemoveField(
            model_name="intervencion",
            name="tipo_intervencion",
        ),
        migrations.RemoveField(
            model_name="subintervencion",
            name="subintervencion",
        ),
    ]
