# Generated by Django 4.2.27 on 2026-03-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0030_colaboradores_espacio"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="colaboradorespacio",
            new_name="comedores_c_comedor_50396a_idx",
            old_name="comedores_c_comedor_6a9f95_idx",
        ),
        migrations.RenameIndex(
            model_name="colaboradorespacio",
            new_name="comedores_c_ciudada_1b9c51_idx",
            old_name="comedores_c_ciudada_05b1f7_idx",
        ),
    ]
