# Generated by Codex on 2026-03-26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comedores", "0031_audit_colaborador_espacio"),
        (
            "comedores",
            "0031_rename_comedores_c_comedor_6a9f95_idx_comedores_c_comedor_50396a_idx_and_more",
        ),
    ]

    operations = []
