# Generated by Django 4.2.20 on 2025-05-15 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0031_alter_nomina_estado"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadoDocumentoRendicionFinal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Estado de Documento",
                "verbose_name_plural": "Estados de Documento",
            },
        ),
        migrations.CreateModel(
            name="TipoDocumentoRendicionFinal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                (
                    "validador",
                    models.CharField(
                        blank=True,
                        default="Dupla",
                        help_text="Quien debe validar el documento. Ej: Dupla, Contabilidad, etc.",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Documento",
                "verbose_name_plural": "Tipos de Documento",
            },
        ),
        migrations.CreateModel(
            name="RendicionCuentasFinal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fisicamente_presentada",
                    models.BooleanField(
                        default=False,
                        verbose_name="Rendición física presentada y aceptada en PAC",
                    ),
                ),
                (
                    "comedor",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rendiciones",
                        to="comedores.comedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rendición de Cuentas Final",
                "verbose_name_plural": "Rendiciones de Cuentas Final",
            },
        ),
        migrations.CreateModel(
            name="DocumentoRendicionFinal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "documento",
                    models.FileField(
                        blank=True, null=True, upload_to="rendicion_cuentas_final/"
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "estado",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comedores.estadodocumentorendicionfinal",
                    ),
                ),
                (
                    "rendicion_final",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="comedores.rendicioncuentasfinal",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comedores.tipodocumentorendicionfinal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Rendición",
                "verbose_name_plural": "Documentos de Rendición",
                "indexes": [
                    models.Index(
                        fields=["rendicion_final"],
                        name="comedores_d_rendici_fdb65b_idx",
                    )
                ],
                "unique_together": {("rendicion_final", "tipo")},
            },
        ),
    ]
