# Generated by Django 4.2.20 on 2025-05-14 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0031_alter_nomina_estado"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstadoDocumentoRendicionFinal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Estado de Documento",
                "verbose_name_plural": "Estados de Documento",
            },
        ),
        migrations.CreateModel(
            name="RendicionCuentaFinal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comedor",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rendiciones",
                        to="comedores.comedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rendición de Cuenta Final",
                "verbose_name_plural": "Rendiciones de Cuenta Final",
            },
        ),
        migrations.CreateModel(
            name="DocumentoRendicionFinal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "documento",
                    models.FileField(
                        blank=True, null=True, upload_to="rendicion_cuenta_final/"
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "estado",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="comedores.estadodocumentorendicionfinal",
                    ),
                ),
                (
                    "rendicion_final",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="comedores.rendicioncuentafinal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento de Rendición",
                "verbose_name_plural": "Documentos de Rendición",
                "indexes": [
                    models.Index(
                        fields=["rendicion_final"],
                        name="comedores_d_rendici_fdb65b_idx",
                    )
                ],
                "unique_together": {("rendicion_final", "nombre")},
            },
        ),
    ]
