# Generated by Django 4.2.20 on 2025-05-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0032_estadodocumentorendicionfinal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipodocumentorendicionfinal",
            name="personalizado",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el tipo de documento es creado por un usuario.",
            ),
        ),
        migrations.AlterField(
            model_name="documentorendicionfinal",
            name="fecha_modificacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
