# Generated by Codex on 2026-03-29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comedores", "0030_programas_usa_admision_para_nomina"),
        ("comedores", "0032_merge_20260326_1545"),
    ]

    operations = []
