# Generated by Django 4.2.20 on 2025-05-15 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "comedores",
            "0032_estadodocumentorendicionfinal_rendicioncuentafinal_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDocumentoRendicionFinal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                (
                    "validador",
                    models.CharField(
                        blank=True,
                        default="Dupla",
                        help_text="Quien debe validar el documento. Ej: Dupla, Contabilidad, etc.",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Documento",
                "verbose_name_plural": "Tipos de Documento",
            },
        ),
        migrations.AddField(
            model_name="documentorendicionfinal",
            name="observaciones",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="rendicioncuentafinal",
            name="fisicamente_presentada",
            field=models.BooleanField(
                default=False,
                verbose_name="Rendición física presentada y aceptada en PAC",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentorendicionfinal",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="documentorendicionfinal",
            name="tipo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="comedores.tipodocumentorendicionfinal",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentorendicionfinal",
            unique_together={("rendicion_final", "tipo")},
        ),
        migrations.RemoveField(
            model_name="documentorendicionfinal",
            name="nombre",
        ),
    ]
