# Generated by Django 4.2.27 on 2026-03-29 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0033_merge_20260329_1458"),
    ]

    operations = []
