# Generated by Django 4.2.20 on 2025-05-27 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0034_merge_20250521_2106"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comedor",
            name="calle",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="La dirección solo puede contener letras, números, espacios y los caracteres ., -",
                        regex="^[a-zA-Z0-9\\s.,áéíóúÁÉÍÓÚñÑ-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="comedor",
            name="departamento",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="La dirección solo puede contener letras, números, espacios y los caracteres ., -",
                        regex="^[a-zA-Z0-9\\s.,áéíóúÁÉÍÓÚñÑ-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="comedor",
            name="entre_calle_1",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="La dirección solo puede contener letras, números, espacios y los caracteres ., -",
                        regex="^[a-zA-Z0-9\\s.,áéíóúÁÉÍÓÚñÑ-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="comedor",
            name="entre_calle_2",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="La dirección solo puede contener letras, números, espacios y los caracteres ., -",
                        regex="^[a-zA-Z0-9\\s.,áéíóúÁÉÍÓÚñÑ-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="comedor",
            name="lote",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="La dirección solo puede contener letras, números, espacios y los caracteres ., -",
                        regex="^[a-zA-Z0-9\\s.,áéíóúÁÉÍÓÚñÑ-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="comedor",
            name="manzana",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="La dirección solo puede contener letras, números, espacios y los caracteres ., -",
                        regex="^[a-zA-Z0-9\\s.,áéíóúÁÉÍÓÚñÑ-]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="comedor",
            name="piso",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="La dirección solo puede contener letras, números, espacios y los caracteres ., -",
                        regex="^[a-zA-Z0-9\\s.,áéíóúÁÉÍÓÚñÑ-]*$",
                    )
                ],
            ),
        ),
    ]
