# Generated by Django 4.2.27 on 2026-05-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0024_squashed_0041"),
    ]

    operations = [
        migrations.CreateModel(
            name="DWECResumenTransacciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comedor_id_sisoc", models.IntegerField(db_index=True)),
                ("periodo", models.CharField(max_length=6)),
                ("cantidad_debitos", models.IntegerField()),
                (
                    "credito_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "debito_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "cereo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Resumen DW - Transacciones",
                "verbose_name_plural": "Resumen DW - Transacciones",
                "db_table": "DW_sisoc.vw_EC_resumen_transacciones",
                "ordering": ["-periodo"],
                "managed": False,
            },
        ),
    ]
