# Generated by Django 4.2.27 on 2026-07-20 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0048_comedor_mes_ejecucion"),
        ("comedores", "0048_replace_pnud_colaboradores"),
    ]

    operations = []
