# Generated by Django 4.2.27 on 2026-07-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0048_imagencomedor_client_uuid"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="imagencomedor",
            name="uniq_imagencomedor_comedor_client_uuid",
        ),
        migrations.AddConstraint(
            model_name="imagencomedor",
            constraint=models.UniqueConstraint(
                fields=("comedor", "client_uuid"),
                name="uniq_imagencomedor_comedor_client_uuid",
            ),
        ),
    ]
