# Generated by Django 4.2.27 on 2026-07-23 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("relevamientos", "0011_alter_menuseguimiento_mejora_alimentacion_ofrecida"),
        ("comedores", "0049_imagencomedor_client_uuid_unique_plano"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagencomedor",
            name="relevamiento",
            field=models.ForeignKey(
                blank=True,
                help_text="Relevamiento (visita) al que pertenece la foto. Opcional: si es null la foto es a nivel comedor (compatibilidad).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="relevamientos.relevamiento",
            ),
        ),
    ]
