# Generated by Django 4.2.27 on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0052_issue_2169_codigo_proyecto"),
    ]

    operations = [
        migrations.AddField(
            model_name="comedor",
            name="es_caritas",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="¿Es CARITAS?"
            ),
        ),
    ]
