# Generated by Django 5.2.16 on 2026-08-24 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0055_issue_2188_personas_declaradas_siph"),
        ("relevamientos", "0011_alter_menuseguimiento_mejora_alimentacion_ofrecida"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagencomedor",
            name="client_uuid",
            field=models.CharField(
                blank=True,
                help_text="Identificador estable generado por el cliente (PWA) para deduplicar reintentos offline de subida.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="imagencomedor",
            name="relevamiento",
            field=models.ForeignKey(
                blank=True,
                help_text="Relevamiento (visita) al que pertenece la foto. Opcional: si es null la foto es a nivel comedor (compatibilidad).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="relevamientos.relevamiento",
            ),
        ),
        migrations.AddConstraint(
            model_name="imagencomedor",
            constraint=models.UniqueConstraint(
                fields=("comedor", "client_uuid"),
                name="uniq_imagencomedor_comedor_client_uuid",
            ),
        ),
    ]
