# Generated by Django 5.2.16 on 2026-08-24 19:16

import django.db.models.deletion
from django.db import migrations, models


class AddFieldIfMissing(migrations.AddField):
    """Agrega el campo sólo cuando no fue creado por la historia PWA previa."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        if self.allow_migrate_model(schema_editor.connection.alias, model):
            with schema_editor.connection.cursor() as cursor:
                columns = {
                    column.name
                    for column in schema_editor.connection.introspection.get_table_description(
                        cursor, model._meta.db_table
                    )
                }
            if model._meta.get_field(self.name).column in columns:
                return
        super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        # La columna puede provenir de la antigua cadena 0048-0050; al revertir
        # no se puede determinar su procedencia sin riesgo de perder datos.
        return


class AddConstraintIfMissing(migrations.AddConstraint):
    """Crea la restricción sólo cuando no existe con el nombre esperado."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        if self.allow_migrate_model(schema_editor.connection.alias, model):
            with schema_editor.connection.cursor() as cursor:
                constraints = schema_editor.connection.introspection.get_constraints(
                    cursor, model._meta.db_table
                )
            if self.constraint.name in constraints:
                return
        super().database_forwards(app_label, schema_editor, from_state, to_state)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        # Ver AddFieldIfMissing.database_backwards: prioriza rollback sin DDL
        # destructivo para los entornos que ya tenían la historia anterior.
        return


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0055_issue_2188_personas_declaradas_siph"),
        ("relevamientos", "0011_alter_menuseguimiento_mejora_alimentacion_ofrecida"),
    ]

    operations = [
        AddFieldIfMissing(
            model_name="imagencomedor",
            name="client_uuid",
            field=models.CharField(
                blank=True,
                help_text="Identificador estable generado por el cliente (PWA) para deduplicar reintentos offline de subida.",
                max_length=64,
                null=True,
            ),
        ),
        AddFieldIfMissing(
            model_name="imagencomedor",
            name="relevamiento",
            field=models.ForeignKey(
                blank=True,
                help_text="Relevamiento (visita) al que pertenece la foto. Opcional: si es null la foto es a nivel comedor (compatibilidad).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="relevamientos.relevamiento",
            ),
        ),
        AddConstraintIfMissing(
            model_name="imagencomedor",
            constraint=models.UniqueConstraint(
                fields=("comedor", "client_uuid"),
                name="uniq_imagencomedor_comedor_client_uuid",
            ),
        ),
    ]
