# Generated by Django 5.2.16 on 2026-09-08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0057_huecos_seguimiento_n19"),
        ("comedores", "0057_issue_2403_responsable_tarjeta"),
    ]

    operations = []
