# Generated by Django 4.2.20 on 2025-06-15 19:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comedores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoContacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Tipo de Contacto",
                "verbose_name_plural": "Tipos de Contacto",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TipoDestinatario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Destinatario",
                "verbose_name_plural": "Destinatarios",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TipoIntervencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Tipo de Intervención",
                "verbose_name_plural": "Tipos de Intervención",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SubIntervencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "tipo_intervencion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subintervenciones",
                        to="intervenciones.tipointervencion",
                        verbose_name="Tipo de Intervención asociada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub-Intervención",
                "verbose_name_plural": "Sub-Intervenciones",
                "ordering": ["tipo_intervencion", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Intervencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha y hora de intervención",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "tiene_documentacion",
                    models.BooleanField(
                        default=False, verbose_name="Documentación adjunta"
                    ),
                ),
                (
                    "documentacion",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documentacion/",
                        verbose_name="Documentación Adjunta",
                    ),
                ),
                (
                    "comedor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intervenciones",
                        to="comedores.comedor",
                        verbose_name="Comedor intervenido",
                    ),
                ),
                (
                    "destinatario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="intervenciones.tipodestinatario",
                        verbose_name="Destinatario",
                    ),
                ),
                (
                    "forma_contacto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="intervenciones.tipocontacto",
                        verbose_name="Forma de contacto",
                    ),
                ),
                (
                    "subintervencion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="intervenciones.subintervencion",
                        verbose_name="Sub-tipo de intervención",
                    ),
                ),
                (
                    "tipo_intervencion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="intervenciones.tipointervencion",
                        verbose_name="Tipo de intervención",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intervención",
                "verbose_name_plural": "Intervenciones",
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(
                        fields=["comedor"], name="intervencio_comedor_c80504_idx"
                    ),
                    models.Index(fields=["fecha"], name="intervencio_fecha_69e8fa_idx"),
                    models.Index(
                        fields=["tipo_intervencion"],
                        name="intervencio_tipo_in_38d798_idx",
                    ),
                ],
            },
        ),
    ]
