# Generated by Django 4.2.20 on 2025-10-24 14:11

from django.db import migrations, models
import django.utils.timezone
import intervenciones.models.intervenciones


class Migration(migrations.Migration):

    dependencies = [
        ("intervenciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intervencion",
            name="fecha",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                validators=[
                    intervenciones.models.intervenciones.validar_rango_anio_fecha
                ],
                verbose_name="Fecha y hora de intervención",
            ),
        ),
    ]
