# Generated by Django 4.2.16 on 2025-05-05 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("intervenciones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Destinatario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Destinatario",
                "verbose_name_plural": "Destinatarios",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="intervencion",
            name="forma_contacto",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Forma de contacto"
            ),
        ),
        migrations.AddField(
            model_name="intervencion",
            name="tiene_documentacion",
            field=models.BooleanField(
                default=False, verbose_name="Documentación adjunta"
            ),
        ),
        migrations.AddField(
            model_name="intervencion",
            name="destinatario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="intervenciones.destinatario",
                verbose_name="Destinatario",
            ),
        ),
    ]
