# Generated by Django 4.2.16 on 2025-05-05 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("intervenciones", "0002_destinatario_intervencion_forma_contacto_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDestinatario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Destinatario",
                "verbose_name_plural": "Destinatarios",
                "ordering": ["id"],
            },
        ),
        migrations.AlterField(
            model_name="intervencion",
            name="destinatario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="intervenciones.tipodestinatario",
                verbose_name="Destinatario",
            ),
        ),
        migrations.DeleteModel(
            name="Destinatario",
        ),
    ]
