# Generated by Django 4.2.16 on 2025-05-07 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("intervenciones", "0004_tipocontacto_intervencion_documentacion_and_more"),
        ("intervenciones", "0005_alter_intervencion_subintervencion_and_more"),
    ]

    dependencies = [
        (
            "intervenciones",
            "0003_tipodestinatario_alter_intervencion_destinatario_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoContacto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Tipo de Contacto",
                "verbose_name_plural": "Tipos de Contacto",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="intervencion",
            name="documentacion",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documentacion/",
                verbose_name="Documentación Adjunta",
            ),
        ),
        migrations.AlterField(
            model_name="intervencion",
            name="forma_contacto",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="intervenciones.tipocontacto",
                verbose_name="Forma de contacto",
            ),
        ),
        migrations.AlterField(
            model_name="intervencion",
            name="subintervencion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="intervenciones.subintervencion",
                verbose_name="Sub-tipo de intervención",
            ),
        ),
        migrations.AlterField(
            model_name="subintervencion",
            name="tipo_intervencion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subintervenciones",
                to="intervenciones.tipointervencion",
                verbose_name="Tipo de Intervención asociada",
            ),
        ),
    ]
