# Generated by Django 4.2.16 on 2025-05-09 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comedores", "0031_alter_nomina_estado"),
        (
            "intervenciones",
            "0004_tipocontacto_intervencion_documentacion_and_more_squashed_0005_alter_intervencion_subintervencion_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="EstadosIntervencion",
        ),
    ]
