# Generated by Django 5.2.16 on 2026-09-06 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_programa_organismo_programa_descripcion"),
        ("datacalle", "0003_encuesta"),
        ("dispositivos", "0005_remove_dispositivo_domicilio_institucion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="encuesta",
            index=models.Index(
                fields=["relevamiento", "-fecha_inicio"],
                name="datacalle_e_relevam_c0184c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="encuesta",
            index=models.Index(
                fields=["relevamiento", "-updated_at"],
                name="datacalle_e_relevam_aa76e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="relevamiento",
            index=models.Index(
                fields=["-fecha_inicio", "denominacion"],
                name="datacalle_r_fecha_i_28966d_idx",
            ),
        ),
    ]
