# Generated by Django 4.2.16 on 2025-06-05 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comedores", "0035_alter_comedor_calle_alter_comedor_departamento_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentacionAdjunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Documento"
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to="documentos_adjuntos/", verbose_name="Archivo"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "ultima_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Modificación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Adjunto",
                "verbose_name_plural": "Documentos Adjuntos",
            },
        ),
        migrations.CreateModel(
            name="RendicionCuentaMensual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.IntegerField(verbose_name="Mes")),
                ("anio", models.IntegerField(verbose_name="Año")),
                (
                    "documento_adjunto",
                    models.BooleanField(
                        default=False, verbose_name="Documento Adjunto"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "ultima_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Modificación"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "arvhios_adjuntos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rendiciones_cuentas_mensuales",
                        to="rendicioncuentasmensual.documentacionadjunta",
                    ),
                ),
                (
                    "comedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rendiciones_cuentas_mensuales",
                        to="comedores.comedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rendición de Cuenta Mensual",
                "verbose_name_plural": "Rendiciones de Cuenta Mensuales",
            },
        ),
    ]
