# Generated by Django 4.2.20 on 2025-06-15 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comedores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RendicionCuentaMensual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mes",
                    models.IntegerField(
                        choices=[
                            (1, "Enero"),
                            (2, "Febrero"),
                            (3, "Marzo"),
                            (4, "Abril"),
                            (5, "Mayo"),
                            (6, "Junio"),
                            (7, "Julio"),
                            (8, "Agosto"),
                            (9, "Septiembre"),
                            (10, "Octubre"),
                            (11, "Noviembre"),
                            (12, "Diciembre"),
                        ],
                        verbose_name="Mes",
                    ),
                ),
                ("anio", models.IntegerField(verbose_name="Año")),
                (
                    "documento_adjunto",
                    models.BooleanField(
                        default=False, verbose_name="Documento Adjunto"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "ultima_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Modificación"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "comedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rendiciones_cuentas_mensuales",
                        to="comedores.comedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rendición de Cuenta Mensual",
                "verbose_name_plural": "Rendiciones de Cuenta Mensuales",
            },
        ),
        migrations.CreateModel(
            name="DocumentacionAdjunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del Documento"
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to="rendicioncuentasmensualdocumentos_adjuntos/",
                        verbose_name="Archivo",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "ultima_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Modificación"
                    ),
                ),
                (
                    "rendicion_cuenta_mensual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="arvhios_adjuntos",
                        to="rendicioncuentasmensual.rendicioncuentamensual",
                        verbose_name="Rendición de Cuenta Mensual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Adjunto",
                "verbose_name_plural": "Documentos Adjuntos",
            },
        ),
    ]
