# Generated by Django 4.2.27 on 2026-05-11 13:42

import core.soft_delete.base
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_mobile_rendicion_permission(apps, schema_editor):
    permission_model = apps.get_model("auth", "Permission")
    content_type_model = apps.get_model("contenttypes", "ContentType")

    content_type, _ = content_type_model.objects.get_or_create(
        app_label="rendicioncuentasmensual",
        model="rendicioncuentamensual",
    )
    permission_model.objects.get_or_create(
        content_type=content_type,
        codename="manage_mobile_rendicion",
        defaults={"name": "Puede gestionar rendiciones mobile"},
    )


class Migration(migrations.Migration):

    initial = True

    replaces = [('rendicioncuentasmensual', '0001_initial'), ('rendicioncuentasmensual', '0002_alter_documentacionadjunta_managers_and_more'), ('rendicioncuentasmensual', '0003_alter_documentacionadjunta_related_name_archivos_adjuntos'), ('rendicioncuentasmensual', '0004_rendicioncuentamensual_datos_mobile'), ('rendicioncuentasmensual', '0005_documentacionadjunta_categorias_estado'), ('rendicioncuentasmensual', '0006_bootstrap_mobile_permission'), ('rendicioncuentasmensual', '0007_alter_rendicioncuentamensual_options_and_more'), ('rendicioncuentasmensual', '0008_rendicioncuentamensual_usuario_creador'), ('rendicioncuentasmensual', '0009_rendicioncuentamensual_usuario_ultima_modificacion'), ('rendicioncuentasmensual', '0010_documentacionadjunta_documento_subsanado')]

    dependencies = [
        ('comedores', '0001_squashed_0023'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RendicionCuentaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('documento_adjunto', models.BooleanField(default=False, verbose_name='Documento Adjunto')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('comedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendiciones_cuentas_mensuales', to='comedores.comedor')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('convenio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Convenio')),
                ('estado', models.CharField(choices=[('elaboracion', 'Presentación en elaboración'), ('revision', 'Presentación en revisión'), ('subsanar', 'Presentación a subsanar'), ('finalizada', 'Presentación finalizada')], default='elaboracion', max_length=20, verbose_name='Estado de Rendición')),
                ('numero_rendicion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Rendición')),
                ('periodo_fin', models.DateField(blank=True, null=True, verbose_name='Período fin')),
                ('periodo_inicio', models.DateField(blank=True, null=True, verbose_name='Período inicio')),
            ],
            options={
                'verbose_name': 'Rendición de Cuenta Mensual',
                'verbose_name_plural': 'Rendiciones de Cuenta Mensuales',
            },
            managers=[
                ('objects', core.soft_delete.base.SoftDeleteManager()),
                ('all_objects', core.soft_delete.base.SoftDeleteManager(include_deleted=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentacionAdjunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Documento')),
                ('archivo', models.FileField(upload_to='rendicioncuentasmensualdocumentos_adjuntos/', verbose_name='Archivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('rendicion_cuenta_mensual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos_adjuntos', to='rendicioncuentasmensual.rendicioncuentamensual', verbose_name='Rendición de Cuenta Mensual')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.CharField(choices=[('formulario_ii', 'Formulario II'), ('formulario_iii', 'Formulario III'), ('formulario_iv', 'Formulario IV'), ('formulario_v', 'Formulario V'), ('formulario_vi', 'Formulario VI'), ('extracto_bancario', 'Extracto Bancario'), ('comprobantes', 'Comprobante/s'), ('planilla_seguros', 'Planilla de Seguros'), ('otros', 'Otros')], default='comprobantes', max_length=40, verbose_name='Categoría')),
                ('estado', models.CharField(choices=[('presentado', 'Presentado'), ('subsanar', 'A Subsanar'), ('validado', 'Validado')], default='presentado', max_length=20, verbose_name='Estado del documento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Documento Adjunto',
                'verbose_name_plural': 'Documentos Adjuntos',
            },
            managers=[
                ('objects', core.soft_delete.base.SoftDeleteManager()),
                ('all_objects', core.soft_delete.base.SoftDeleteManager(include_deleted=True)),
            ],
        ),
        migrations.RunPython(
            create_mobile_rendicion_permission,
            migrations.RunPython.noop,
        ),
        migrations.AlterModelOptions(
            name='rendicioncuentamensual',
            options={'permissions': [('manage_mobile_rendicion', 'Puede gestionar rendiciones mobile')], 'verbose_name': 'Rendición de Cuenta Mensual', 'verbose_name_plural': 'Rendiciones de Cuenta Mensuales'},
        ),
        migrations.AlterField(
            model_name='documentacionadjunta',
            name='categoria',
            field=models.CharField(choices=[('formulario_ii', 'Formulario II'), ('formulario_iii', 'Formulario III'), ('formulario_iv', 'Formulario IV'), ('formulario_v', 'Formulario V'), ('formulario_vi', 'Formulario VI'), ('extracto_bancario', 'Extracto Bancario'), ('comprobantes', 'Comprobante/s'), ('planilla_seguros', 'Planilla de Seguros'), ('otros', 'Documentación Extra')], default='comprobantes', max_length=40, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='rendicioncuentamensual',
            name='usuario_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendiciones_cuentas_mensuales_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creador'),
        ),
        migrations.AddField(
            model_name='rendicioncuentamensual',
            name='usuario_ultima_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendiciones_cuentas_mensuales_modificadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario última modificación'),
        ),
        migrations.AddField(
            model_name='documentacionadjunta',
            name='documento_subsanado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsanaciones', to='rendicioncuentasmensual.documentacionadjunta', verbose_name='Documento subsanado'),
        ),
    ]
