# Generated by Django 4.2.27 on 2026-02-19 17:47

import core.soft_delete
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rendicioncuentasmensual", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="documentacionadjunta",
            managers=[
                ("objects", core.soft_delete.SoftDeleteManager()),
                (
                    "all_objects",
                    core.soft_delete.SoftDeleteManager(include_deleted=True),
                ),
            ],
        ),
        migrations.AlterModelManagers(
            name="rendicioncuentamensual",
            managers=[
                ("objects", core.soft_delete.SoftDeleteManager()),
                (
                    "all_objects",
                    core.soft_delete.SoftDeleteManager(include_deleted=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="documentacionadjunta",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="documentacionadjunta",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rendicioncuentamensual",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="rendicioncuentamensual",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="documentacionadjunta",
            name="rendicion_cuenta_mensual",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arvhios_adjuntos",
                to="rendicioncuentasmensual.rendicioncuentamensual",
                verbose_name="Rendición de Cuenta Mensual",
            ),
        ),
    ]
