# Generated by Django 4.2.16 on 2025-06-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rendicioncuentasmensual", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rendicioncuentamensual",
            name="mes",
            field=models.IntegerField(
                choices=[
                    (1, "Enero"),
                    (2, "Febrero"),
                    (3, "Marzo"),
                    (4, "Abril"),
                    (5, "Mayo"),
                    (6, "Junio"),
                    (7, "Julio"),
                    (8, "Agosto"),
                    (9, "Septiembre"),
                    (10, "Octubre"),
                    (11, "Noviembre"),
                    (12, "Diciembre"),
                ],
                verbose_name="Mes",
            ),
        ),
    ]
