# Generated by Codex on 2026-02-25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rendicioncuentasmensual", "0002_alter_documentacionadjunta_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentacionadjunta",
            name="rendicion_cuenta_mensual",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archivos_adjuntos",
                to="rendicioncuentasmensual.rendicioncuentamensual",
                verbose_name="Rendición de Cuenta Mensual",
            ),
        ),
    ]
