# Generated by Django 4.2.16 on 2025-06-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rendicioncuentasmensual", "0002_alter_rendicioncuentamensual_mes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentacionadjunta",
            name="archivo",
            field=models.FileField(
                upload_to="rendicioncuentasmensual/documentos_adjuntos/",
                verbose_name="Archivo",
            ),
        ),
    ]
