# Generated by Django 4.2.16 on 2025-06-09 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rendicioncuentasmensual", "0003_alter_documentacionadjunta_archivo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rendicioncuentamensual",
            name="arvhios_adjuntos",
        ),
        migrations.AddField(
            model_name="documentacionadjunta",
            name="rendicion_cuenta_mensual",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="arvhios_adjuntos",
                to="rendicioncuentasmensual.rendicioncuentamensual",
                verbose_name="Rendición de Cuenta Mensual",
            ),
        ),
        migrations.AlterField(
            model_name="documentacionadjunta",
            name="archivo",
            field=models.FileField(
                upload_to="rendicioncuentasmensualdocumentos_adjuntos/",
                verbose_name="Archivo",
            ),
        ),
    ]
