# Generated by Django 4.2.27 on 2026-05-26 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rendicioncuentasmensual", "0011_rendicion_linea_programatica_documentos"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rendicioncuentamensual",
            options={
                "permissions": [
                    ("manage_mobile_rendicion", "Puede gestionar rendiciones mobile")
                ],
                "verbose_name": "Rendición de Cuenta Mensual",
                "verbose_name_plural": "Rendiciones de Cuenta Mensuales",
            },
        ),
        migrations.AlterField(
            model_name="documentacionadjunta",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("formulario_i", "Formulario I"),
                    ("formulario_ii", "Formulario II"),
                    ("formulario_iii", "Formulario III"),
                    ("formulario_iii_alimentario", "Formulario III Alimentario"),
                    ("formulario_iii_siph", "Formulario III SIPH"),
                    ("formulario_iv", "Formulario IV"),
                    ("formulario_v", "Formulario V"),
                    ("formulario_v_alimentario", "Formulario V Alimentario"),
                    ("formulario_v_siph", "Formulario V SIPH"),
                    ("formulario_vi", "Formulario VI"),
                    ("extracto_bancario", "Extracto Bancario"),
                    ("comprobantes", "Comprobante/s"),
                    ("planilla_seguros", "Planilla de Seguros"),
                    ("otros", "Documentación Adicional"),
                ],
                default="comprobantes",
                max_length=40,
                verbose_name="Categoría",
            ),
        ),
        migrations.AlterField(
            model_name="documentacionadjunta",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de Creación"
            ),
        ),
        migrations.AlterField(
            model_name="documentacionadjunta",
            name="rendicion_cuenta_mensual",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="archivos_adjuntos",
                to="rendicioncuentasmensual.rendicioncuentamensual",
                verbose_name="Rendición de Cuenta Mensual",
            ),
        ),
        migrations.AlterField(
            model_name="documentacionadjunta",
            name="ultima_modificacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última Modificación"
            ),
        ),
        migrations.AlterField(
            model_name="rendicioncuentamensual",
            name="anio",
            field=models.IntegerField(verbose_name="Año"),
        ),
        migrations.AlterField(
            model_name="rendicioncuentamensual",
            name="estado",
            field=models.CharField(
                choices=[
                    ("elaboracion", "Presentación en elaboración"),
                    ("revision", "Presentación en revisión"),
                    ("subsanar", "Presentación a subsanar"),
                    ("finalizada", "Presentación finalizada"),
                ],
                default="elaboracion",
                max_length=20,
                verbose_name="Estado de Rendición",
            ),
        ),
        migrations.AlterField(
            model_name="rendicioncuentamensual",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de Creación"
            ),
        ),
        migrations.AlterField(
            model_name="rendicioncuentamensual",
            name="numero_rendicion",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Número de Rendición"
            ),
        ),
        migrations.AlterField(
            model_name="rendicioncuentamensual",
            name="periodo_fin",
            field=models.DateField(blank=True, null=True, verbose_name="Período fin"),
        ),
        migrations.AlterField(
            model_name="rendicioncuentamensual",
            name="periodo_inicio",
            field=models.DateField(
                blank=True, null=True, verbose_name="Período inicio"
            ),
        ),
        migrations.AlterField(
            model_name="rendicioncuentamensual",
            name="ultima_modificacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última Modificación"
            ),
        ),
        migrations.AlterField(
            model_name="rendicioncuentamensual",
            name="usuario_ultima_modificacion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rendiciones_cuentas_mensuales_modificadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario última modificación",
            ),
        ),
    ]
