# Generated by Django 5.2.16 on 2026-09-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rendicioncuentasmensual', '0019_reconciliar_comprobantes_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacionadjunta',
            name='categoria',
            field=models.CharField(choices=[('formulario_i', 'Formulario I - Certificación de Cuenta Bancaria'), ('formulario_ii', 'Formulario II - Resumen'), ('formulario_iii', 'Formulario III - Desagregado por Facturas Prestación Alimentaria'), ('formulario_iii_alimentario', 'Formulario III - Desagregado por Facturas Prestación Alimentaria'), ('formulario_iii_siph', 'Formulario III - Desagregado por Facturas SIPH'), ('formulario_iv', 'Formulario IV - Recibo de Fondos'), ('formulario_v', 'Formulario V - Certificación de Prestaciones Alimentarias'), ('formulario_v_alimentario', 'Formulario V - Certificación de Prestaciones Alimentarias'), ('formulario_v_siph', 'Formulario V - Certificación de SIPH'), ('formulario_vi', 'Formulario VI - Planilla de Pagos'), ('extracto_bancario', 'Extracto Bancario'), ('comprobantes_alimentario', 'Facturas y Tickets Prestación Alimentaria'), ('comprobantes_siph', 'Facturas y Tickets SIPH'), ('planilla_seguros', 'Planilla de Seguros'), ('otros', 'Documentación Adicional')], default='comprobantes_alimentario', max_length=40, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='rendicioncuentamensual',
            name='etapa_proceso',
            field=models.CharField(choices=[('carga_documentacion', 'Carga de documentación'), ('revision_documentacion', 'Revisión Territorial'), ('revision_auditoria', 'Revisión para Carga'), ('auditoria', 'Auditoría'), ('regularizacion', 'Regularización')], default='carga_documentacion', max_length=30, verbose_name='Etapa del proceso'),
        ),
        migrations.AlterField(
            model_name='solicituddocumentofaltante',
            name='categoria',
            field=models.CharField(choices=[('formulario_i', 'Formulario I - Certificación de Cuenta Bancaria'), ('formulario_ii', 'Formulario II - Resumen'), ('formulario_iii', 'Formulario III - Desagregado por Facturas Prestación Alimentaria'), ('formulario_iii_alimentario', 'Formulario III - Desagregado por Facturas Prestación Alimentaria'), ('formulario_iii_siph', 'Formulario III - Desagregado por Facturas SIPH'), ('formulario_iv', 'Formulario IV - Recibo de Fondos'), ('formulario_v', 'Formulario V - Certificación de Prestaciones Alimentarias'), ('formulario_v_alimentario', 'Formulario V - Certificación de Prestaciones Alimentarias'), ('formulario_v_siph', 'Formulario V - Certificación de SIPH'), ('formulario_vi', 'Formulario VI - Planilla de Pagos'), ('extracto_bancario', 'Extracto Bancario'), ('comprobantes_alimentario', 'Facturas y Tickets Prestación Alimentaria'), ('comprobantes_siph', 'Facturas y Tickets SIPH'), ('planilla_seguros', 'Planilla de Seguros'), ('otros', 'Documentación Adicional')], max_length=40),
        ),
    ]
