# Generated by Django 5.2.16 on 2026-09-11 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rendicioncuentasmensual", "0020_issue_2377_etiquetas_catalogo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documentacionadjunta",
            name="visualizacion_etapa",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                verbose_name="Etapa en que se confirmó la visualización",
            ),
        ),
        migrations.AddField(
            model_name="documentacionadjunta",
            name="visualizacion_fecha",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Fecha de confirmación de visualización",
            ),
        ),
        migrations.AddField(
            model_name="documentacionadjunta",
            name="visualizacion_usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documentos_rendicion_visualizados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Confirmó la visualización",
            ),
        ),
    ]
