# Generated by Django 5.2.16 on 2026-09-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rendicioncuentasmensual", "0021_issue_2377_visualizacion_documentos"),
    ]

    operations = [
        migrations.AddField(
            model_name="rendicioncuentamensual",
            name="genera_acta_auditoria",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="¿Se genera acta de auditoría?"
            ),
        ),
        migrations.AddField(
            model_name="rendicioncuentamensual",
            name="monto_observado",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                verbose_name="Monto observado",
            ),
        ),
        migrations.AddField(
            model_name="rendicioncuentamensual",
            name="rendiciones_incluidas",
            field=models.ManyToManyField(
                blank=True,
                related_name="incluida_en_actas",
                to="rendicioncuentasmensual.rendicioncuentamensual",
                verbose_name="Rendiciones incluidas en el acta",
            ),
        ),
    ]
