from django.urls import path
from core.decorators import permissions_any_required
from rendicioncuentasmensual.views import (
    RendicionCuentaMensualGlobalListView,
    RendicionCuentaMensualListView,
    RendicionCuentaMensualDetailView,
    RendicionCuentaMensualDownloadPdfView,
    RendicionCuentaMensualDeleteView,
    RendicionCuentaMensualCreateView,
    RendicionCuentaMensualUpdateView,
    eliminar_archivo,
)

urlpatterns = [
    path(
        "rendicioncuentasmensual/listado/",
        permissions_any_required(
            [
                "comedores.view_comedor",
                "admisiones.view_admision",
                "acompanamientos.view_informacionrelevante",
            ]
        )(RendicionCuentaMensualGlobalListView.as_view()),
        name="rendicioncuentasmensual_global_list",
    ),
    path(
        "rendicioncuentasmensual/<int:comedor_id>/",
        permissions_any_required(
            [
                "comedores.view_comedor",
                "admisiones.view_admision",
                "acompanamientos.view_informacionrelevante",
            ]
        )(RendicionCuentaMensualListView.as_view()),
        name="rendicioncuentasmensual_list",
    ),
    path(
        "rendicioncuentasmensual/detalle/<int:pk>/",
        permissions_any_required(
            [
                "comedores.view_comedor",
                "admisiones.view_admision",
                "acompanamientos.view_informacionrelevante",
            ]
        )(RendicionCuentaMensualDetailView.as_view()),
        name="rendicioncuentasmensual_detail",
    ),
    path(
        "rendicioncuentasmensual/detalle/<int:pk>/descargar-pdf/",
        permissions_any_required(
            [
                "comedores.view_comedor",
                "admisiones.view_admision",
                "acompanamientos.view_informacionrelevante",
            ]
        )(RendicionCuentaMensualDownloadPdfView.as_view()),
        name="rendicioncuentasmensual_download_pdf",
    ),
    path(
        "rendicioncuentasmensual/eliminar/<int:pk>/",
        permissions_any_required(
            [
                "comedores.view_comedor",
                "admisiones.view_admision",
                "acompanamientos.view_informacionrelevante",
            ]
        )(RendicionCuentaMensualDeleteView.as_view()),
        name="rendicioncuentasmensual_delete",
    ),
    path(
        "rendicioncuentasmensual/nuevo/<int:comedor_id>/",
        permissions_any_required(
            [
                "comedores.view_comedor",
                "admisiones.view_admision",
                "acompanamientos.view_informacionrelevante",
            ]
        )(RendicionCuentaMensualCreateView.as_view()),
        name="rendicioncuentasmensual_create",
    ),
    path(
        "rendicioncuentasmensual/editar/<int:pk>/",
        permissions_any_required(
            [
                "comedores.view_comedor",
                "admisiones.view_admision",
                "acompanamientos.view_informacionrelevante",
            ]
        )(RendicionCuentaMensualUpdateView.as_view()),
        name="rendicioncuentasmensual_update",
    ),
    path(
        "eliminar-archivo/<int:archivo_id>/", eliminar_archivo, name="eliminar_archivo"
    ),
]
