from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0008_programa_organismo_programa_descripcion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItinerarioVPSL",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("codigo", models.CharField(blank=True, max_length=32, unique=True)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("localidades_tentativas", models.TextField(blank=True)),
                ("sedes_tentativas", models.TextField(blank=True)),
                ("matricula_estimada", models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ("referente_nombre", models.CharField(max_length=255)),
                ("referente_telefono", models.CharField(blank=True, max_length=50)),
                ("referente_email", models.EmailField(blank=True, max_length=254)),
                ("carta_referencia", models.CharField(blank=True, max_length=255)),
                ("carta_fecha_presentacion", models.DateField(blank=True, null=True)),
                ("carta_firmante", models.CharField(blank=True, max_length=255)),
                ("carta_firmante_cargo", models.CharField(blank=True, max_length=255)),
                ("carta_archivo", models.FileField(blank=True, null=True, upload_to="ver_para_ser_libre/cartas/")),
                ("estado", models.CharField(choices=[("borrador", "Borrador"), ("presentado", "Presentado"), ("en_revision", "En revision Nacion"), ("observado", "Observado"), ("subsanado", "Subsanado"), ("aprobado", "Aprobado"), ("en_ejecucion", "En ejecucion"), ("en_post_operativo", "En post-operativo"), ("cerrado", "Cerrado"), ("cancelado", "Cancelado")], db_index=True, default="borrador", max_length=32)),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("creado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="itinerarios_vpsl_creados", to=settings.AUTH_USER_MODEL)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("modificado_por", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="itinerarios_vpsl_modificados", to=settings.AUTH_USER_MODEL)),
                ("provincia", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.provincia")),
            ],
            options={
                "verbose_name": "Itinerario VPSL",
                "verbose_name_plural": "Itinerarios VPSL",
                "ordering": ["-fecha_inicio", "provincia__nombre"],
            },
        ),
        migrations.CreateModel(
            name="HistorialEstadoVPSL",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                ("estado_anterior", models.CharField(blank=True, max_length=64)),
                ("estado_nuevo", models.CharField(max_length=64)),
                ("observacion", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content_type", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype")),
                ("usuario", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Historial de estado VPSL",
                "verbose_name_plural": "Historiales de estado VPSL",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="JornadaVPSL",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("fecha", models.DateField()),
                ("sede", models.CharField(max_length=255)),
                ("direccion", models.CharField(blank=True, max_length=255)),
                ("horario_inicio", models.TimeField(blank=True, null=True)),
                ("horario_fin", models.TimeField(blank=True, null=True)),
                ("referente_nombre", models.CharField(blank=True, max_length=255)),
                ("referente_telefono", models.CharField(blank=True, max_length=50)),
                ("referente_email", models.EmailField(blank=True, max_length=254)),
                ("equipo_asignado", models.CharField(blank=True, max_length=255)),
                ("estado", models.CharField(choices=[("planificada", "Planificada"), ("checklist_pendiente", "Checklist pendiente"), ("habilitada", "Habilitada"), ("en_progreso", "En progreso"), ("pendiente_cierre", "Pendiente de cierre"), ("cerrada", "Cerrada"), ("en_post_operativo", "En post-operativo"), ("cerrada_final", "Cerrada final"), ("observada", "Observada")], db_index=True, default="planificada", max_length=32)),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("itinerario", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="jornadas", to="ver_para_ser_libre.itinerariovpsl")),
                ("localidad", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.localidad")),
                ("municipio", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.municipio")),
            ],
            options={
                "verbose_name": "Jornada VPSL",
                "verbose_name_plural": "Jornadas VPSL",
                "ordering": ["fecha", "sede"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistJornadaVPSL",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item", models.CharField(choices=[("electricidad", "Electricidad"), ("infraestructura", "Infraestructura"), ("viandas", "Viandas / almuerzo"), ("seguridad", "Seguridad / resguardo"), ("movil", "Movil"), ("equipo", "Equipo operativo"), ("otro", "Otro")], max_length=32)),
                ("descripcion", models.CharField(blank=True, max_length=255)),
                ("critico", models.BooleanField(default=True)),
                ("cumple", models.BooleanField(blank=True, null=True)),
                ("observacion", models.TextField(blank=True)),
                ("evidencia", models.FileField(blank=True, null=True, upload_to="ver_para_ser_libre/checklist/")),
                ("responsable", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("jornada", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="checklist", to="ver_para_ser_libre.jornadavpsl")),
            ],
            options={
                "verbose_name": "Checklist de jornada VPSL",
                "verbose_name_plural": "Checklist de jornada VPSL",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="RegistroNominalVPSL",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("dni", models.CharField(blank=True, db_index=True, max_length=16)),
                ("identificador_alternativo", models.CharField(blank=True, max_length=64)),
                ("nombre", models.CharField(max_length=255)),
                ("apellido", models.CharField(max_length=255)),
                ("edad", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("genero", models.CharField(blank=True, max_length=64)),
                ("telefono", models.CharField(blank=True, max_length=50)),
                ("escuela_sede", models.CharField(blank=True, max_length=255)),
                ("numero_acta", models.CharField(max_length=64)),
                ("numero_sobre", models.CharField(blank=True, max_length=64)),
                ("fecha_atencion", models.DateField(default=django.utils.timezone.localdate)),
                ("prescripcion", models.TextField(blank=True)),
                ("resultado", models.CharField(choices=[("entregado_dia", "Entregado en el dia"), ("enviado_laboratorio", "Enviado a laboratorio"), ("no_requiere", "No requiere anteojos"), ("derivado", "Derivado")], max_length=32)),
                ("cantidad_lentes", models.PositiveSmallIntegerField(default=0)),
                ("estado", models.CharField(choices=[("cargado", "Cargado"), ("validado", "Validado"), ("observado", "Observado"), ("corregido", "Corregido"), ("cerrado", "Cerrado")], db_index=True, default="cargado", max_length=32)),
                ("adjunto", models.FileField(blank=True, null=True, upload_to="ver_para_ser_libre/registros/")),
                ("observaciones", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("jornada", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="registros", to="ver_para_ser_libre.jornadavpsl")),
            ],
            options={
                "verbose_name": "Registro nominal VPSL",
                "verbose_name_plural": "Registros nominales VPSL",
                "ordering": ["apellido", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="CierreDiarioVPSL",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("total_controles", models.PositiveIntegerField(default=0)),
                ("anteojos_entregados", models.PositiveIntegerField(default=0)),
                ("casos_laboratorio", models.PositiveIntegerField(default=0)),
                ("no_requiere_anteojos", models.PositiveIntegerField(default=0)),
                ("total_anteojos", models.PositiveIntegerField(default=0)),
                ("responsable_cierre", models.CharField(max_length=255)),
                ("fecha_cierre", models.DateTimeField(default=django.utils.timezone.now)),
                ("consistente", models.BooleanField(default=False)),
                ("acta_adjunta", models.FileField(blank=True, null=True, upload_to="ver_para_ser_libre/cierres/")),
                ("observaciones", models.TextField(blank=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("jornada", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="cierre", to="ver_para_ser_libre.jornadavpsl")),
            ],
            options={
                "verbose_name": "Cierre diario VPSL",
                "verbose_name_plural": "Cierres diarios VPSL",
            },
        ),
        migrations.CreateModel(
            name="CasoLaboratorioVPSL",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("estado", models.CharField(choices=[("pendiente_envio", "Pendiente de envio"), ("enviado", "Enviado a laboratorio"), ("en_produccion", "En produccion"), ("enviado_provincia", "Enviado a provincia"), ("recibido", "Recibido"), ("entregado", "Entregado"), ("cerrado", "Cerrado"), ("incidencia", "Incidencia")], db_index=True, default="pendiente_envio", max_length=32)),
                ("fecha_envio", models.DateField(blank=True, null=True)),
                ("fecha_recepcion", models.DateField(blank=True, null=True)),
                ("fecha_entrega", models.DateField(blank=True, null=True)),
                ("responsable_entrega", models.CharField(blank=True, max_length=255)),
                ("destinatario", models.CharField(blank=True, max_length=255)),
                ("remito", models.FileField(blank=True, null=True, upload_to="ver_para_ser_libre/laboratorio/")),
                ("incidencia", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("registro", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="caso_laboratorio", to="ver_para_ser_libre.registronominalvpsl")),
            ],
            options={
                "verbose_name": "Caso de laboratorio VPSL",
                "verbose_name_plural": "Casos de laboratorio VPSL",
                "ordering": ["estado", "registro__jornada__fecha"],
            },
        ),
        migrations.AddIndex(
            model_name="itinerariovpsl",
            index=models.Index(fields=["estado", "fecha_inicio"], name="ver_para_s_estado_082db5_idx"),
        ),
        migrations.AddIndex(
            model_name="itinerariovpsl",
            index=models.Index(fields=["provincia", "estado"], name="ver_para_s_provinc_7548e8_idx"),
        ),
        migrations.AddConstraint(
            model_name="jornadavpsl",
            constraint=models.UniqueConstraint(fields=("itinerario", "fecha", "sede"), name="uniq_vpsl_jornada_fecha_sede"),
        ),
        migrations.AddConstraint(
            model_name="checklistjornadavpsl",
            constraint=models.UniqueConstraint(fields=("jornada", "item"), name="uniq_vpsl_checklist_jornada_item"),
        ),
        migrations.AddConstraint(
            model_name="registronominalvpsl",
            constraint=models.UniqueConstraint(fields=("jornada", "numero_acta"), name="uniq_vpsl_registro_jornada_acta"),
        ),
    ]
