# Generated by Django 4.2.27 on 2026-05-04 21:28

import core.soft_delete.base
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "ver_para_ser_libre",
            "0003_remove_itinerariovpsl_carta_fecha_presentacion_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="sedevpsl",
            managers=[
                ("objects", core.soft_delete.base.SoftDeleteManager()),
                (
                    "all_objects",
                    core.soft_delete.base.SoftDeleteManager(include_deleted=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="jornadavpsl",
            name="referente_apellido",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="jornadavpsl",
            name="referente_datos_renaper",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jornadavpsl",
            name="referente_dni",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="jornadavpsl",
            name="referente_sexo",
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name="jornadavpsl",
            name="referente_validado_renaper",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registronominalvpsl",
            name="datos_renaper",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registronominalvpsl",
            name="no_verificar_renaper",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="registronominalvpsl",
            name="sexo",
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name="registronominalvpsl",
            name="validado_renaper",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sedevpsl",
            name="deleted_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="sedevpsl",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
