# Generated by Django 4.2.27 on 2026-05-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ver_para_ser_libre", "0004_alter_sedevpsl_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jornadavpsl",
            name="estado",
            field=models.CharField(
                choices=[
                    ("planificada", "Planificada"),
                    ("checklist_pendiente", "Pendiente checklist"),
                    ("pendiente_habilitacion", "Pendiente habilitacion"),
                    ("habilitada", "Habilitada"),
                    ("en_progreso", "En progreso"),
                    ("pendiente_cierre", "Pendiente de cierre"),
                    ("pendiente_cierre_observada", "Pendiente cierre observada"),
                    ("finalizada", "Finalizada"),
                    ("cerrada", "Cerrada"),
                    ("en_post_operativo", "En post-operativo"),
                    ("cerrada_final", "Cerrada final"),
                    ("observada", "Observada"),
                ],
                db_index=True,
                default="planificada",
                max_length=32,
            ),
        ),
    ]
