# Generated by Django 4.2.27 on 2026-05-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ver_para_ser_libre", "0006_itinerariovpsl_carta_archivo_estado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registronominalvpsl",
            name="primera_vez_anteojos",
            field=models.BooleanField(default=False),
        ),
    ]
