# Generated by Django 4.2.27 on 2026-05-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ver_para_ser_libre", "0009_alter_casolaboratoriovpsl_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="jornadavpsl",
            name="vehiculo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("vehiculo_1", "Vehiculo 1"),
                    ("vehiculo_2", "Vehiculo 2"),
                    ("vehiculo_3", "Vehiculo 3"),
                    ("vehiculo_4", "Vehiculo 4"),
                ],
                max_length=32,
            ),
        ),
    ]
