# Generated by Django 4.2.27 on 2026-05-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ver_para_ser_libre", "0010_jornadavpsl_vehiculo"),
    ]

    operations = [
        migrations.AddField(
            model_name="cierrediariovpsl",
            name="derivados",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
