# Generated by Django 4.2.27 on 2026-05-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispositivos", "0002_alter_dispositivo_modo_registro_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispositivo",
            name="documentacion_dispositivo_adicional_1",
            field=models.FileField(
                blank=True, null=True, upload_to="dispositivos/documentacion/"
            ),
        ),
        migrations.AddField(
            model_name="dispositivo",
            name="documentacion_dispositivo_adicional_2",
            field=models.FileField(
                blank=True, null=True, upload_to="dispositivos/documentacion/"
            ),
        ),
        migrations.AddField(
            model_name="dispositivo",
            name="documentacion_dispositivo_adicional_3",
            field=models.FileField(
                blank=True, null=True, upload_to="dispositivos/documentacion/"
            ),
        ),
        migrations.AddField(
            model_name="dispositivo",
            name="documentacion_dispositivo_adicional_4",
            field=models.FileField(
                blank=True, null=True, upload_to="dispositivos/documentacion/"
            ),
        ),
    ]
