# Generated by Django 4.2.27 on 2026-05-11 16:55

import dispositivos.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dispositivos",
            "0003_dispositivo_documentacion_dispositivo_adicional_1_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispositivo",
            name="documentacion_dispositivo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="dispositivos/documentacion/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("pdf", "jpg", "jpeg", "png"),
                        message="Solo se permiten archivos PDF, JPG o PNG.",
                    ),
                    dispositivos.validators.validate_documentacion_file_size,
                    dispositivos.validators.validate_documentacion_content_type,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dispositivo",
            name="documentacion_dispositivo_adicional_1",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="dispositivos/documentacion/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("pdf", "jpg", "jpeg", "png"),
                        message="Solo se permiten archivos PDF, JPG o PNG.",
                    ),
                    dispositivos.validators.validate_documentacion_file_size,
                    dispositivos.validators.validate_documentacion_content_type,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dispositivo",
            name="documentacion_dispositivo_adicional_2",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="dispositivos/documentacion/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("pdf", "jpg", "jpeg", "png"),
                        message="Solo se permiten archivos PDF, JPG o PNG.",
                    ),
                    dispositivos.validators.validate_documentacion_file_size,
                    dispositivos.validators.validate_documentacion_content_type,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dispositivo",
            name="documentacion_dispositivo_adicional_3",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="dispositivos/documentacion/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("pdf", "jpg", "jpeg", "png"),
                        message="Solo se permiten archivos PDF, JPG o PNG.",
                    ),
                    dispositivos.validators.validate_documentacion_file_size,
                    dispositivos.validators.validate_documentacion_content_type,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="dispositivo",
            name="documentacion_dispositivo_adicional_4",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="dispositivos/documentacion/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("pdf", "jpg", "jpeg", "png"),
                        message="Solo se permiten archivos PDF, JPG o PNG.",
                    ),
                    dispositivos.validators.validate_documentacion_file_size,
                    dispositivos.validators.validate_documentacion_content_type,
                ],
            ),
        ),
    ]
