# Generated by Django 4.2.27 on 2026-05-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispositivos", "0004_validate_dispositivo_uploads"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dispositivo",
            name="domicilio_institucion",
        ),
        migrations.RemoveField(
            model_name="dispositivo",
            name="telefono_contacto",
        ),
        migrations.AddField(
            model_name="dispositivo",
            name="altura",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="dispositivo",
            name="calle",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="dispositivo",
            name="telefono_numero",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="dispositivo",
            name="telefono_prefijo",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
