# Generated by Django 4.2.27 on 2026-05-20 17:17

from django.db import migrations, models


def assert_no_legacy_contact_data(apps, schema_editor):
    Dispositivo = apps.get_model("dispositivos", "Dispositivo")
    if not Dispositivo.objects.exists():
        return

    raise RuntimeError(
        "La migración 0005 de dispositivos asume que no hay datos legacy de "
        "Dispositivo. Existen registros cargados; antes de remover "
        "domicilio_institucion y telefono_contacto se debe hacer una "
        "migración con backfill o limpiar el ambiente explícitamente."
    )


class Migration(migrations.Migration):

    dependencies = [
        ("dispositivos", "0004_validate_dispositivo_uploads"),
    ]

    operations = [
        migrations.RunPython(
            assert_no_legacy_contact_data,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="dispositivo",
            name="domicilio_institucion",
        ),
        migrations.RemoveField(
            model_name="dispositivo",
            name="telefono_contacto",
        ),
        migrations.AddField(
            model_name="dispositivo",
            name="altura",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="dispositivo",
            name="calle",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="dispositivo",
            name="telefono_numero",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="dispositivo",
            name="telefono_prefijo",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
