# Generated by Django 4.2.20 on 2025-05-22 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Historial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("accion", models.CharField(max_length=255)),
                ("object_id", models.CharField(max_length=255)),
                ("diferencias", models.JSONField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial",
                "verbose_name_plural": "Historiales",
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(fields=["fecha"], name="historial_h_fecha_3d4854_idx"),
                    models.Index(
                        fields=["usuario"], name="historial_h_usuario_76014d_idx"
                    ),
                    models.Index(
                        fields=["accion"], name="historial_h_accion_083158_idx"
                    ),
                    models.Index(
                        fields=["content_type"], name="historial_h_content_ff36a3_idx"
                    ),
                    models.Index(
                        fields=["object_id"], name="historial_h_object__40c785_idx"
                    ),
                ],
            },
        ),
    ]
