import sys
import os
import pytest
from comedores.services.clasificacion_comedor_service import ClasificacionComedorService
from comedores.models.relevamiento import (
    Relevamiento,
    Espacio,
    Colaboradores,
    FuenteRecursos,
    FuenteCompras,
    Prestacion,
    Anexo,
    Excepcion,
    PuntoEntregas,
    Comedor,
    TipoDeComedor,
    TipoFrecuenciaBolsones,
    TipoDistanciaTransporte,
    TipoAccesoComedor,
    TipoTecnologia,
    TipoFrecuenciaInsumos,
    TipoInsumos,
    TipoRecurso,
    FrecuenciaRecepcionRecursos,
    CantidadColaboradores,
    EspacioPrestacion,
    EspacioCocina,
    TipoEspacio,
    TipoGestionQuejas,
    TipoDesague,
    TipoModalidadPrestacion,
    TipoAgua,
    TipoModuloBolsones,
    FuncionamientoPrestacion,
    TipoCombustible,
    FrecuenciaLimpieza,
    MotivoExcepcion
)
from comedores.models.comedor import (
    Comedor
)
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
@pytest.mark.django_db


def test_get_puntuacion_total():
    # Preparacion: Crear un relevamiento en la BD de prueba
    relevamiento = Relevamiento.objects.create(
        estado="Finalizado",
        comedor=Comedor.objects.create(
            nombre="Comedor Test",
            organizacion=None,
            programa=None,
            id_externo=None,
            comienzo=None,
            tipocomedor=None,
            calle=None,
            numero=None,
            piso=None,
            departamento=None,
            manzana=None,
            lote=None,
            entre_calle_1=None,
            entre_calle_2=None,
            latitud=None,
            longitud=None,
            provincia=None,
            municipio=None,
            localidad=None,
            partido=None,
            barrio=None,
            codigo_postal=None,
            referente=None,
            foto_legajo=None,
        ),
        fecha_visita=None,
        territorial_nombre=None,
        territorial_uid=None,
        funcionamiento=FuncionamientoPrestacion.objects.create(
            modalidad_prestacion=TipoModalidadPrestacion.objects.create(nombre="Comedor"),
            servicio_por_turnos=False,
            cantidad_turnos=1,
        ),
        espacio=Espacio.objects.create(
            tipo_espacio_fisico=TipoEspacio.objects.create(nombre="Espacio alquilado"),
            espacio_fisico_otro="Otro espacio",
            cocina=EspacioCocina.objects.create(
                espacio_elaboracion_alimentos=False,
                almacenamiento_alimentos_secos=False,
                heladera=False,
                freezer=False,
                recipiente_residuos_organicos=False,
                recipiente_residuos_reciclables=False,
                otros_residuos=False,
                recipiente_otros_residuos=False,
                abastecimiento_combustible=TipoCombustible.objects.create(nombre="Gas"),
                abastecimiento_agua=TipoAgua.objects.create(nombre="Red pública"),
                abastecimiento_agua_otro=None,
                instalacion_electrica=False,
            ),
            prestacion=EspacioPrestacion.objects.create(
                espacio_equipado=False,
                tiene_ventilacion=False,
                tiene_salida_emergencia=False,
                salida_emergencia_senializada=False,
                tiene_equipacion_incendio=False,
                tiene_botiquin=False,
                tiene_buena_iluminacion=False,
                tiene_sanitarios=False,
                desague_hinodoro=TipoDesague.objects.create(nombre="Cloacal"),
                gestion_quejas=TipoGestionQuejas.objects.create(nombre="Libro de quejas"),
                gestion_quejas_otro=None,
                informacion_quejas=False,
                frecuencia_limpieza=FrecuenciaLimpieza.objects.create(nombre="Diaria"),
            ),
        ),
        colaboradores=Colaboradores.objects.create(
            cantidad_colaboradores=CantidadColaboradores.objects.create(
                cantidad=1,
            ),
            colaboradores_capacitados_alimentos=False,
            colaboradores_recibieron_capacitacion_alimentos=False,
            colaboradores_capacitados_salud_seguridad=False,
            colaboradores_recibieron_capacitacion_emergencias=False,
            colaboradores_recibieron_capacitacion_violencia=False,
        ),
        recursos=FuenteRecursos.objects.create(
            recibe_donaciones_particulares=False,
            frecuencia_donaciones_particulares=FrecuenciaRecepcionRecursos.objects.create(nombre="Diaria"),
            recursos_donaciones_particulares=TipoRecurso.objects.create(nombre="Alimentos"),
            recibe_estado_nacional=False,
            frecuencia_estado_nacional=FrecuenciaRecepcionRecursos.objects.create(nombre="Diaria"),
            recursos_estado_nacional=TipoRecurso.objects.create(nombre="Alimentos"),
            recibe_estado_provincial=False,
            frecuencia_estado_provincial=FrecuenciaRecepcionRecursos.objects.create(nombre="Diaria"),
            recursos_estado_provincial=TipoRecurso.objects.create(nombre="Alimentos"),
            recibe_estado_municipal=False,
            frecuencia_estado_municipal=FrecuenciaRecepcionRecursos.objects.create(nombre="Diaria"),
            recursos_estado_municipal=TipoRecurso.objects.create(nombre="Alimentos"),
            recibe_otros=False,
            frecuencia_otros=FrecuenciaRecepcionRecursos.objects.create(nombre="Diaria"),
            recursos_otros=TipoRecurso.objects.create(nombre="Alimentos"),
        ),
        compras=FuenteCompras.objects.create(
            almacen_cercano=False,
            verduleria=False,
            carniceria=False,
            granja=False,
            pescaderia=False,
            supermercado=False,
            mercado_central=False,
            ferias_comunales=False,
            mayoristas=False,
            otros=False,
        ),
        prestacion=Prestacion.objects.create(
            lunes_desayuno_actual = None,
            lunes_desayuno_espera = None,
            lunes_almuerzo_actual = None,
            lunes_almuerzo_espera = None,
            lunes_merienda_actual = None,
            lunes_merienda_espera = None,
            lunes_cena_actual = None,
            lunes_cena_espera = None,

            martes_desayuno_actual = None,
            martes_desayuno_espera = None,
            martes_almuerzo_actual = None,
            martes_almuerzo_espera = None,
            martes_merienda_actual = None,
            martes_merienda_espera = None,
            martes_cena_actual = None,
            martes_cena_espera = None,

            miercoles_desayuno_actual = None,
            miercoles_desayuno_espera = None,
            miercoles_almuerzo_actual = None,
            miercoles_almuerzo_espera = None,
            miercoles_merienda_actual = None,
            miercoles_merienda_espera = None,
            miercoles_cena_actual = None,
            miercoles_cena_espera = None,

            jueves_desayuno_actual = None,
            jueves_desayuno_espera = None,
            jueves_almuerzo_actual = None,
            jueves_almuerzo_espera = None,
            jueves_merienda_actual = None,
            jueves_merienda_espera = None,
            jueves_cena_actual = None,
            jueves_cena_espera = None,

            viernes_desayuno_actual = None,
            viernes_desayuno_espera = None,
            viernes_almuerzo_actual = None,
            viernes_almuerzo_espera = None,
            viernes_merienda_actual = None,
            viernes_merienda_espera = None,
            viernes_cena_actual = None,
            viernes_cena_espera = None,

            sabado_desayuno_actual = None,
            sabado_desayuno_espera = None,
            sabado_almuerzo_actual = None,
            sabado_almuerzo_espera = None,
            sabado_merienda_actual = None,
            sabado_merienda_espera = None,
            sabado_cena_actual = None,
            sabado_cena_espera = None,

            domingo_desayuno_actual = None,
            domingo_desayuno_espera = None,
            domingo_almuerzo_actual = None,
            domingo_almuerzo_espera = None,
            domingo_merienda_actual = None,
            domingo_merienda_espera = None,
            domingo_cena_actual = None,
            domingo_cena_espera = None,
        ),
        punto_entregas = PuntoEntregas.objects.create(
            tipo_comedor= TipoDeComedor.objects.create(nombre="Comedor"),
            reciben_otros_recepcion=None,
            frecuencia_recepcion_mercaderias=TipoFrecuenciaBolsones.objects.create(nombre="Diaria"),
            frecuencia_entrega_bolsones=TipoFrecuenciaBolsones.objects.create(nombre="Diaria"),
            tipo_modulo_bolsones=TipoModuloBolsones.objects.create(nombre="Bolsón"),
            otros_punto_entregas=None,
            existe_punto_entregas=False,
            funciona_punto_entregas=False,
            observa_entregas=False,
            retiran_mercaderias_distribucion=False,
            retiran_mercaderias_comercio=False,
            reciben_dinero=False,
            registran_entrega_bolsones=False,
        ),
        excepcion=Excepcion.objects.create(
            motivo=MotivoExcepcion.objects.create(nombre="No hay personal"),
            descripcion=None,
            latitud=None,
            longitud=None,
            adjuntos=None,
            firma=None,
        ),
        anexo=Anexo.objects.create(
            tipo_insumo=TipoInsumos.objects.create(nombre="Alimentos"),
            frecuencia_insumo=TipoFrecuenciaInsumos.objects.create(nombre="Diaria"),
            tecnologia=TipoTecnologia.objects.create(nombre="Internet"),
            acceso_comedor=TipoAccesoComedor.objects.create(nombre="Caminando"),
            distancia_transporte=TipoDistanciaTransporte.objects.create(nombre="Menos de 5 cuadras"),
            comedor_merendero = False,
            insumos_organizacion = False,
            servicio_internet = False,
            zona_inundable = False,
            actividades_jardin_maternal = False,
            actividades_jardin_infantes = False,
            apoyo_escolar = False,
            alfabetizacion_terminalidad = False,
            capacitaciones_talleres = False,
            promocion_salud = False,
            actividades_discapacidad = False,
            necesidades_alimentarias = False,
            actividades_recreativas = False,
            actividades_culturales = False,
            emprendimientos_productivos = False,
            actividades_religiosas = False,
            actividades_huerta = False,
            espacio_huerta = False,
            otras_actividades = False,
            cuales_otras_actividades = False,
            veces_recibio_insumos_2024=0

        ),
        imagenes=None,
        observacion=None,
        docPDF=None,
        responsable_es_referente=False,
        responsable_relevamiento=None,
    )

    # Ejecución: Llamar al método que queremos probar
    resultado = ClasificacionComedorService.get_puntuacion_total(relevamiento)

    # Verificación: Verificar que el resultado es el esperado
    assert resultado == 0