# Generated by Django 4.2.27 on 2026-06-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ocr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ocrjob",
            name="opt_auto_orient",
            field=models.BooleanField(
                default=True, verbose_name="Auto-corrección de orientación"
            ),
        ),
        migrations.AddField(
            model_name="ocrjob",
            name="opt_pdf_text_layer",
            field=models.BooleanField(
                default=True, verbose_name="Capa de texto del PDF (híbrido)"
            ),
        ),
        migrations.AddField(
            model_name="ocrjob",
            name="opt_preprocess",
            field=models.BooleanField(
                default=True, verbose_name="Preprocesado de imagen"
            ),
        ),
    ]
