from django.contrib import admin

from .models import (
    ActividadRealizada,
    Agua,
    AportesJubilacion,
    AreaCurso,
    AsisteEscuela,
    CantidadAmbientes,
    CentrosSalud,
    Condicion,
    UbicacionVivienda,
    Desague,
    DuracionTrabajo,
    EstadoCivil,
    EstadoDerivacion,
    EstadoNivelEducativo,
    EstadoRelacion,
    Frecuencia,
    Grado,
    Importancia,
    Inodoro,
    ModoContratacion,
    MotivoNivelIncompleto,
    Nacionalidad,
    NivelEducativo,
    NobusquedaLaboral,
    Rechazo,
    TiempoBusquedaLaboral,
    TipoConstruccionVivienda,
    TipoDocumento,
    TipoGestion,
    TipoPisosVivienda,
    TipoPosesionVivienda,
    TipoTechoVivienda,
    TipoVivienda,
    Turno,
    VinculoFamiliar,
)


admin.site.register(NivelEducativo)
admin.site.register(EstadoNivelEducativo)
admin.site.register(AsisteEscuela)
admin.site.register(MotivoNivelIncompleto)
admin.site.register(AreaCurso)
admin.site.register(TipoGestion)
admin.site.register(Grado)
admin.site.register(Turno)
admin.site.register(CantidadAmbientes)
admin.site.register(Condicion)
admin.site.register(UbicacionVivienda)
admin.site.register(TipoVivienda)
admin.site.register(TipoPosesionVivienda)
admin.site.register(TipoPisosVivienda)
admin.site.register(TipoTechoVivienda)
admin.site.register(Agua)
admin.site.register(Desague)
admin.site.register(Inodoro)
admin.site.register(TipoConstruccionVivienda)
admin.site.register(EstadoCivil)
admin.site.register(TipoDocumento)
admin.site.register(Nacionalidad)
admin.site.register(CentrosSalud)
admin.site.register(Frecuencia)
admin.site.register(ModoContratacion)
admin.site.register(ActividadRealizada)
admin.site.register(DuracionTrabajo)
admin.site.register(AportesJubilacion)
admin.site.register(TiempoBusquedaLaboral)
admin.site.register(NobusquedaLaboral)
admin.site.register(EstadoRelacion)
admin.site.register(EstadoDerivacion)
admin.site.register(VinculoFamiliar)
admin.site.register(Rechazo)
admin.site.register(Importancia)
