from django.contrib.auth.decorators import login_required
from django.urls import path

from ciudadanos.views import (
    AccionesSocialesView,
    AlertaSelectView,
    CategoriasSelectView,
    CreateArchivo,
    CreateGrupoFamiliar,
    CreateGrupoHogar,
    DeleteAlerta,
    DeleteArchivo,
    DeleteGrupoFamiliar,
    DeleteGrupoHogar,
    DimensionesDetailView,
    DimensionesUpdateView,
    IndicesDetalleView,
    IndicesView,
    IntervencionCreateView,
    IntervencionDeleteView,
    IntervencionDetail,
    IntervencionesSaludView,
    IntervencionUpdateView,
    GrupoFamiliarList,
    GrupoHogarList,
    AlertaCreateView,
    AlertaListView,
    ArchivosCreateView,
    ArchivosListView,
    CiudadanosCreateView,
    CiudadanosDeleteView,
    DerivacionBuscar,
    DerivacionCreateView,
    DerivacionDeleteView,
    DerivacionDetailView,
    DerivacionHistorial,
    DerivacionListView,
    DerivacionUpdateView,
    CiudadanosDetailView,
    CiudadanosGrupoFamiliarCreateView,
    CiudadanosGrupoHogarCreateView,
    CiudadanosListView,
    CiudadanosReportesListView,
    CiudadanosUpdateView,
    LlamadoCreateView,
    LlamadoDeleteView,
    LlamadoDetail,
    LlamadoUpdateView,
    ProgramaIntervencionesView,
    SubEstadosIntervencionesAJax,
    SubEstadosLlamadosAjax,
    TipoEstadosLlamadosAjax,
    busqueda_familiares,
    busqueda_hogar,
    actualizar_programas,
    eliminar_programa,
)

urlpatterns = [
    # Ciudadano
    path(
        "ciudadanos/reportes",
        login_required(CiudadanosReportesListView.as_view()),
        name="ciudadanos_reportes",
    ),
    path(
        "ciudadanos/listar",
        login_required(CiudadanosListView.as_view()),
        name="ciudadanos",
    ),
    path(  # TODO: Eliminar esta URL y migrar la busqueda via query string
        "ciudadanos/listar/<busqueda>",
        login_required(CiudadanosListView.as_view()),
        name="ciudadanos",
    ),
    path(
        "ciudadanos/crear/",
        login_required(CiudadanosCreateView.as_view()),
        name="ciudadanos_crear",
    ),
    path(
        "ciudadanos/ver/<pk>",
        login_required(CiudadanosDetailView.as_view()),
        name="ciudadanos_ver",
    ),
    path(
        "ciudadanos/editar/<pk>",
        login_required(CiudadanosUpdateView.as_view()),
        name="ciudadanos_editar",
    ),
    path(
        "ciudadanos/eliminar/<pk>",
        login_required(CiudadanosDeleteView.as_view()),
        name="ciudadanos_eliminar",
    ),
    # Grupo Familiar
    path(
        "ciudadanos/grupofamiliar/listar/<pk>",
        login_required(GrupoFamiliarList.as_view()),
        name="grupofamiliar_listar",
    ),
    path(
        "ciudadanos/grupofamiliar/crear/<pk>",
        login_required(CiudadanosGrupoFamiliarCreateView.as_view()),
        name="grupofamiliar_crear",
    ),
    path(
        "ciudadanos/grupofamiliar/crear/ajax/",
        login_required(CreateGrupoFamiliar.as_view()),
        name="grupofamiliar_ajax_crear",
    ),
    path(
        "ciudadanos/grupofamiliar/borrar/ajax/",
        login_required(DeleteGrupoFamiliar.as_view()),
        name="grupofamiliar_ajax_borrar",
    ),
    path(
        "ciudadanos/grupofamiliar/buscar/",
        login_required(busqueda_familiares),
        name="familiares_buscar",
    ),
    path(
        "ciudadanos/grupofamiliar/nuevo/",
        login_required(CiudadanosGrupoFamiliarCreateView.as_view()),
        name="nuevoCiudadanoFamiliar_ajax",
    ),
    # Dimensiones
    path(
        "ciudadanos/dimensiones/ver/<pk>",
        login_required(DimensionesDetailView.as_view()),
        name="ciudadanosdimensiones_ver",
    ),
    path(
        "ciudadanos/dimensiones/editar/<pk>",
        login_required(DimensionesUpdateView.as_view()),
        name="ciudadanosdimensiones_editar",
    ),
    # Alertas
    path(
        "ciudadanos/alertas/listar/<pk>",
        login_required(AlertaListView.as_view()),
        name="alertas_listar",
    ),
    path(
        "ciudadanos/alertas/crear/<pk>",
        login_required(AlertaCreateView.as_view()),
        name="alertas_crear",
    ),
    path(
        "ciudadanos/alertas/borrar/ajax/",
        login_required(DeleteAlerta.as_view()),
        name="alerta_ajax_borrar",
    ),
    # URLs para los select dinamicos para alertas_form
    path("alertas-select/", AlertaSelectView.as_view(), name="alertas_select"),
    path(
        "categorias-select/", CategoriasSelectView.as_view(), name="categorias_select"
    ),
    # Archivos
    path(
        "ciudadanos/archivos/listar/<pk>",
        login_required(ArchivosListView.as_view()),
        name="ciudadanosarchivos_listar",
    ),
    path(
        "ciudadanos/archivos/crear/<pk>",
        login_required(ArchivosCreateView.as_view()),
        name="ciudadanosarchivos_crear",
    ),
    path(
        "ciudadanos/archivos/crear/ajax/",
        login_required(CreateArchivo.as_view()),
        name="archivo_ajax_crear",
    ),
    path(
        "ciudadanos/archivos/borrar/ajax/",
        login_required(DeleteArchivo.as_view()),
        name="archivo_ajax_borrar",
    ),
    # Derivaciones
    path(
        "ciudadanos/derivaciones/buscar",
        login_required(DerivacionBuscar.as_view()),
        name="ciudadanosderivaciones_buscar",
    ),
    path(
        "ciudadanos/derivaciones/derivar/<pk>",
        login_required(DerivacionCreateView.as_view()),
        name="ciudadanosderivaciones_crear",
    ),
    path(
        "ciudadanos/derivaciones/listar",
        login_required(DerivacionListView.as_view()),
        name="ciudadanosderivaciones_listar",
    ),
    path(
        "ciudadanos/derivaciones/listar/<str:filtro>",
        login_required(DerivacionListView.as_view()),
        name="ciudadanosderivaciones_listar",
    ),
    path(
        "ciudadanos/derivaciones/ver/<pk>",
        login_required(DerivacionDetailView.as_view()),
        name="ciudadanosderivaciones_ver",
    ),
    path(
        "ciudadanos/derivaciones/editar/<pk>",
        login_required(DerivacionUpdateView.as_view()),
        name="ciudadanosderivaciones_editar",
    ),
    path(
        "ciudadanos/derivaciones/eliminar/<pk>",
        login_required(DerivacionDeleteView.as_view()),
        name="ciudadanosderivaciones_eliminar",
    ),
    path(
        "ciudadanos/derivaciones/historial/<pk>",
        login_required(DerivacionHistorial.as_view()),
        name="ciudadanosderivaciones_historial",
    ),
    # Programas de asistencia
    path(
        "ciudadanos/programas_intervencion/<pk>",
        login_required(ProgramaIntervencionesView.as_view()),
        name="programas_intervencion",
    ),
    # Acciones Sociales
    path(
        "ciudadanos/acciones_sociales/<pk>",
        login_required(AccionesSocialesView.as_view()),
        name="acciones_sociales",
    ),
    # Interveciones de salud
    path(
        "ciudadanos/intervenciones_salud/<pk>",
        login_required(IntervencionesSaludView.as_view()),
        name="intervenciones_salud",
    ),
    # Indices
    path(
        "ciudadanos/indices/<pk>", login_required(IndicesView.as_view()), name="indices"
    ),
    # Indice detalle
    path(
        "ciudadanos/indices_detalle/<pk>",
        login_required(IndicesDetalleView.as_view()),
        name="indices_detalle",
    ),
    # Hogar
    path(
        "ciudadanos/grupoHogar/listar/<pk>",
        login_required(GrupoHogarList.as_view()),
        name="grupohogar_listar",
    ),
    path(
        "ciudadanos/grupoHogar/crear/<pk>",
        login_required(CiudadanosGrupoHogarCreateView.as_view()),
        name="grupohogar_crear",
    ),
    path(
        "ciudadanos/grupoHogar/crear/ajax/",
        login_required(CreateGrupoHogar.as_view()),
        name="grupohogar_ajax_crear",
    ),
    path(
        "ciudadanos/grupoHogar/borrar/ajax/",
        login_required(DeleteGrupoHogar.as_view()),
        name="grupohogar_ajax_borrar",
    ),
    path(
        "ciudadanos/grupoHogar/buscar/",
        login_required(busqueda_hogar),
        name="hogar_buscar",
    ),
    path(
        "ciudadanos/grupoHogar/nuevo/",
        login_required(CiudadanosGrupoHogarCreateView.as_view()),
        name="nuevoCiudadanoFamiliar_ajax",
    ),
    path(
        "ciudadanos/hogar/crear/<pk>",
        login_required(CiudadanosGrupoHogarCreateView.as_view()),
        name="ciudadanosgrupohogar_crear",
    ),
    path(
        "ajax/load-subestadosintervenciones/",
        SubEstadosIntervencionesAJax.as_view(),
        name="ajax_load_subestadosintervenciones",
    ),
    path(
        "ajax/load-subestadosllamados/",
        SubEstadosLlamadosAjax.as_view(),
        name="ajax_load_subestadosllamados",
    ),
    path(
        "ajax/load-tiposllamados/",
        TipoEstadosLlamadosAjax.as_view(),
        name="ajax_load_tiposllamados",
    ),
    path(
        "ciudadanos/intervencion/ver/<pk>",
        login_required(IntervencionDetail.as_view()),
        name="ciudadano_intervencion_ver",
    ),
    path(
        "ciudadanos/intervencion/crear/<pk>",
        login_required(IntervencionCreateView.as_view()),
        name="intervencion_crear",
    ),
    path(
        "ciudadanos/intervencion/editar/<pk>/<pk2>",
        login_required(IntervencionUpdateView.as_view()),
        name="intervencion_editar",
    ),
    path(
        "ciudadanos/intervencion/borrar/<pk>/<pk2>",
        login_required(IntervencionDeleteView.as_view()),
        name="intervencion_borrar",
    ),
    path(
        "ciudadanos/llamados/ver/<pk>",
        login_required(LlamadoDetail.as_view()),
        name="llamados_ver",
    ),
    path(
        "ciudadanos/llamados/editar/<pk>/<pk2>",
        login_required(LlamadoUpdateView.as_view()),
        name="llamados_editar",
    ),
    path(
        "ciudadanos/llamados/crear/<pk>",
        login_required(LlamadoCreateView.as_view()),
        name="llamados_crear",
    ),
    path(
        "ciudadanos/llamados/borrar/<pk>/<pk2>",
        login_required(LlamadoDeleteView.as_view()),
        name="llamados_borrar",
    ),
    path(
        "ciudadanos/<int:ciudadano_id>/actualizar_programas/",
        actualizar_programas,
        name="actualizar_programas",
    ),
    path("eliminar/programa/", eliminar_programa, name="eliminar_programa"),
]
