# Generated by Django 5.2.16 on 2026-08-28 22:34

import django.core.validators
import django.db.models.deletion
import encuestas.models
import encuestas.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Encuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, default="", verbose_name="Descripción"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("publicada", "Publicada"),
                            ("cerrada", "Cerrada"),
                            ("archivada", "Archivada"),
                        ],
                        default="borrador",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "es_anonima",
                    models.BooleanField(default=False, verbose_name="¿Es anónima?"),
                ),
                (
                    "es_obligatoria",
                    models.BooleanField(default=False, verbose_name="¿Es obligatoria?"),
                ),
                (
                    "intervalo_recordatorio_dias",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Solo aplica si la encuesta no es obligatoria.",
                        null=True,
                        verbose_name="Intervalo de recordatorio (días)",
                    ),
                ),
                (
                    "es_recurrente",
                    models.BooleanField(default=False, verbose_name="¿Es recurrente?"),
                ),
                (
                    "intervalo_recurrencia_dias",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Intervalo de recurrencia (días)",
                    ),
                ),
                (
                    "duracion_ronda_dias",
                    models.PositiveIntegerField(
                        verbose_name="Duración de cada ronda (días)"
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(default=1, verbose_name="Versión"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_ultima_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de última modificación"
                    ),
                ),
                (
                    "usuario_creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encuestas_creadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario creador",
                    ),
                ),
                (
                    "usuario_ultima_modificacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="encuestas_modificadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Última modificación por",
                    ),
                ),
                (
                    "version_de",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versiones",
                        to="encuestas.encuesta",
                        verbose_name="Versión de",
                    ),
                ),
            ],
            options={
                "verbose_name": "Encuesta",
                "verbose_name_plural": "Encuestas",
                "ordering": ["-fecha_creacion"],
                "permissions": [
                    ("ver_resultados", "Puede ver los resultados de las encuestas")
                ],
            },
        ),
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=500, verbose_name="Texto")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("texto_corto", "Texto corto"),
                            ("texto_largo", "Texto largo"),
                            ("opcion_unica", "Opción única"),
                            ("opcion_multiple", "Opción múltiple"),
                            ("escala", "Escala"),
                            ("si_no", "Sí/No"),
                            ("numerico", "Numérico"),
                            ("fecha", "Fecha"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de respuesta esperada",
                    ),
                ),
                (
                    "obligatoria",
                    models.BooleanField(default=True, verbose_name="¿Obligatoria?"),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "operador_condicion",
                    models.CharField(
                        blank=True,
                        choices=[("igual", "Igual a"), ("distinto", "Distinto de")],
                        default="",
                        max_length=20,
                        verbose_name="Operador de la condición",
                    ),
                ),
                (
                    "valor_condicion",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Valor esperado",
                    ),
                ),
                (
                    "encuesta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preguntas",
                        to="encuestas.encuesta",
                        verbose_name="Encuesta",
                    ),
                ),
                (
                    "pregunta_condicion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preguntas_dependientes",
                        to="encuestas.pregunta",
                        verbose_name="Mostrar según respuesta de",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta",
                "verbose_name_plural": "Preguntas",
                "ordering": ["encuesta", "orden"],
            },
        ),
        migrations.CreateModel(
            name="OpcionPregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=200, verbose_name="Texto")),
                ("valor", models.CharField(max_length=200, verbose_name="Valor")),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opciones",
                        to="encuestas.pregunta",
                        verbose_name="Pregunta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opción de pregunta",
                "verbose_name_plural": "Opciones de pregunta",
                "ordering": ["pregunta", "orden"],
            },
        ),
        migrations.CreateModel(
            name="RespuestaRonda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_respuesta",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de respuesta"
                    ),
                ),
                (
                    "completa",
                    models.BooleanField(default=False, verbose_name="¿Completa?"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="respuestas_encuesta",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta de ronda",
                "verbose_name_plural": "Respuestas de ronda",
            },
        ),
        migrations.CreateModel(
            name="RespuestaPregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_texto",
                    models.TextField(
                        blank=True, default="", verbose_name="Valor de texto"
                    ),
                ),
                (
                    "valor_numero",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Valor numérico",
                    ),
                ),
                (
                    "valor_fecha",
                    models.DateField(
                        blank=True, null=True, verbose_name="Valor de fecha"
                    ),
                ),
                (
                    "opciones_seleccionadas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="respuestas",
                        to="encuestas.opcionpregunta",
                        verbose_name="Opciones seleccionadas",
                    ),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="respuestas",
                        to="encuestas.pregunta",
                        verbose_name="Pregunta",
                    ),
                ),
                (
                    "respuesta_ronda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas_pregunta",
                        to="encuestas.respuestaronda",
                        verbose_name="Respuesta de ronda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta de pregunta",
                "verbose_name_plural": "Respuestas de pregunta",
            },
        ),
        migrations.CreateModel(
            name="RondaEncuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_ronda",
                    models.PositiveIntegerField(verbose_name="Número de ronda"),
                ),
                (
                    "fecha_apertura",
                    models.DateTimeField(verbose_name="Fecha de apertura"),
                ),
                (
                    "fecha_cierre_programada",
                    models.DateTimeField(verbose_name="Fecha de cierre programada"),
                ),
                (
                    "fecha_cierre_real",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de cierre real"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("abierta", "Abierta"), ("cerrada", "Cerrada")],
                        default="abierta",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "cerrada_manualmente",
                    models.BooleanField(
                        default=False, verbose_name="¿Cerrada manualmente?"
                    ),
                ),
                (
                    "encuesta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rondas",
                        to="encuestas.encuesta",
                        verbose_name="Encuesta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ronda de encuesta",
                "verbose_name_plural": "Rondas de encuesta",
                "ordering": ["-fecha_apertura"],
            },
        ),
        migrations.AddField(
            model_name="respuestaronda",
            name="ronda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="respuestas",
                to="encuestas.rondaencuesta",
                verbose_name="Ronda",
            ),
        ),
        migrations.CreateModel(
            name="CumplimientoRonda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ronda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cumplimientos",
                        to="encuestas.rondaencuesta",
                        verbose_name="Ronda",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cumplimientos_encuesta",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cumplimiento de ronda",
                "verbose_name_plural": "Cumplimientos de ronda",
            },
        ),
        migrations.CreateModel(
            name="RecordatorioUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_proximo_aviso",
                    models.DateTimeField(verbose_name="Fecha del próximo aviso"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordatorios_encuesta",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "ronda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordatorios",
                        to="encuestas.rondaencuesta",
                        verbose_name="Ronda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recordatorio de usuario",
                "verbose_name_plural": "Recordatorios de usuario",
            },
        ),
        migrations.CreateModel(
            name="SegmentacionEncuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("todos_los_usuarios", "Todos los usuarios"),
                            ("listado_documentos", "Listado de documentos"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de segmentación",
                    ),
                ),
                (
                    "archivo_listado",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=encuestas.models.encuesta_listado_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=("xlsx", "csv"),
                                message="Solo se permiten archivos Excel (.xlsx) o CSV.",
                            ),
                            encuestas.validators.validate_listado_file_size,
                        ],
                        verbose_name="Archivo de listado",
                    ),
                ),
                (
                    "encuesta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segmentacion",
                        to="encuestas.encuesta",
                        verbose_name="Encuesta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Segmentación de encuesta",
                "verbose_name_plural": "Segmentaciones de encuesta",
            },
        ),
        migrations.CreateModel(
            name="SegmentacionDestinatario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[("dni", "DNI"), ("cuit", "CUIT"), ("cuil", "CUIL")],
                        max_length=10,
                        verbose_name="Tipo de documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(max_length=20, verbose_name="Número de documento"),
                ),
                (
                    "segmentacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinatarios",
                        to="encuestas.segmentacionencuesta",
                        verbose_name="Segmentación",
                    ),
                ),
            ],
            options={
                "verbose_name": "Destinatario de segmentación",
                "verbose_name_plural": "Destinatarios de segmentación",
            },
        ),
        migrations.AddConstraint(
            model_name="encuesta",
            constraint=models.UniqueConstraint(
                fields=("version_de", "version"),
                name="uniq_encuesta_version_de_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="respuestapregunta",
            constraint=models.UniqueConstraint(
                fields=("respuesta_ronda", "pregunta"), name="uniq_respuesta_pregunta"
            ),
        ),
        migrations.AddConstraint(
            model_name="rondaencuesta",
            constraint=models.UniqueConstraint(
                fields=("encuesta", "numero_ronda"), name="uniq_ronda_encuesta_numero"
            ),
        ),
        migrations.AddConstraint(
            model_name="cumplimientoronda",
            constraint=models.UniqueConstraint(
                fields=("ronda", "usuario"), name="uniq_cumplimiento_ronda_usuario"
            ),
        ),
        migrations.AddConstraint(
            model_name="recordatoriousuario",
            constraint=models.UniqueConstraint(
                fields=("ronda", "usuario"), name="uniq_recordatorio_ronda_usuario"
            ),
        ),
        migrations.AddConstraint(
            model_name="segmentaciondestinatario",
            constraint=models.UniqueConstraint(
                fields=("segmentacion", "tipo_documento", "numero_documento"),
                name="uniq_segmentacion_destinatario",
            ),
        ),
    ]
