# Generated by Django 5.2.16 on 2026-08-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("encuestas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="opcionpregunta",
            name="puntaje",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Solo se usa si la pregunta pondera para el puntaje total.",
                verbose_name="Puntaje",
            ),
        ),
        migrations.AddField(
            model_name="pregunta",
            name="pondera",
            field=models.BooleanField(
                default=False,
                help_text="Solo aplica a Sí/No, Opción única, Opción múltiple y Escala: son los tipos con un conjunto fijo de valores posibles.",
                verbose_name="¿Pondera para el puntaje?",
            ),
        ),
        migrations.AddField(
            model_name="pregunta",
            name="puntaje_no",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Puntaje si responde 'No'"
            ),
        ),
        migrations.AddField(
            model_name="pregunta",
            name="puntaje_si",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Puntaje si responde 'Sí'"
            ),
        ),
    ]
