name: Formateo y linteo

on:
    pull_request:
        branches:
            - main
            - development

jobs:
    setup:
        runs-on: ubuntu-latest
        outputs:
            python-version: ${{ steps.python-version.outputs.python-version }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.7

            - name: Set up Python
              id: python-version
              uses: actions/setup-python@v5.2.0
              with:
                  python-version: '3.9.19'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install black djlint pylint
              id: install-dependencies

    black:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.7

            - name: Set up Python
              uses: actions/setup-python@v5.2.0
              with:
                  python-version: ${{ needs.setup.outputs.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install black

            - name: Run Black
              run: black --check . --config pyproject.toml

            - name: Upload Black report
              if: failure()
              uses: actions/upload-artifact@v4.4.0
              with:
                  name: black-report
                  path: |
                      **/*.py

    djlint:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.7

            - name: Set up Python
              uses: actions/setup-python@v5.2.0
              with:
                  python-version: ${{ needs.setup.outputs.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install djlint

            - name: Run DJLint
              run: |
                  djlint . --check --configuration=.djlintrc

    pylint:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - name: Checkout code
              uses: actions/checkout@v4.1.7

            - name: Set up Python
              uses: actions/setup-python@v5.2.0
              with:
                  python-version: ${{ needs.setup.outputs.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  pip install pylint

            - name: Run pylint
              run: |
                  pylint **/*.py --rcfile=.pylintrc
