# Generated by Django 4.0.2 on 2024-09-06 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Legajos", "0002_legajolocalidad_legajomunicipio_legajoprovincias_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dimensioneconomia",
            name="recibe_plan",
        ),
        migrations.RemoveField(
            model_name="dimensioneducacion",
            name="asiste_escuela",
        ),
        migrations.RemoveField(
            model_name="dimensioneducacion",
            name="interesCurso",
        ),
        migrations.RemoveField(
            model_name="dimensioneducacion",
            name="interesEstudio",
        ),
        migrations.RemoveField(
            model_name="dimensiontrabajo",
            name="conviviente_trabaja",
        ),
        migrations.RemoveField(
            model_name="dimensiontrabajo",
            name="tiene_trabajo",
        ),
        migrations.RemoveField(
            model_name="dimensionvivienda",
            name="PoseenCeludar",
        ),
        migrations.RemoveField(
            model_name="dimensionvivienda",
            name="PoseenPC",
        ),
        migrations.RemoveField(
            model_name="dimensionvivienda",
            name="Poseeninternet",
        ),
        migrations.RemoveField(
            model_name="dimensionvivienda",
            name="hay_agua_caliente",
        ),
        migrations.RemoveField(
            model_name="dimensionvivienda",
            name="hay_banio",
        ),
        migrations.RemoveField(
            model_name="dimensionvivienda",
            name="hay_desmoronamiento",
        ),
    ]
