# Generated by Django 4.0.2 on 2024-07-03 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Legajos', '0002_alter_legajos_apellido_alter_legajos_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legajos',
            name='apellido',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='documento',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(3000000), django.core.validators.MaxValueValidator(100000000)]),
        ),
    ]
