# Generated by Django 4.0.2 on 2024-07-08 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuraciones', '0002_alter_alertas_gravedad'),
        ('Legajos', '0003_alter_legajos_apellido_alter_legajos_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legajos',
            name='apellido',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='documento',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(3000000), django.core.validators.MaxValueValidator(100000000)]),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='estado',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='fecha_nacimiento',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='m2m_alertas',
            field=models.ManyToManyField(blank=True, db_index=True, through='Legajos.LegajoAlertas', to='Configuraciones.Alertas'),
        ),
        migrations.AlterField(
            model_name='legajosderivaciones',
            name='estado',
            field=models.CharField(choices=[(None, ''), ('Pendiente', 'Pendiente'), ('En análisis', 'En análisis'), ('Aceptada', 'Aceptada'), ('Asesoramiento', 'Asesoramiento'), ('finalizada', 'finalizada')], db_index=True, default='Pendiente', max_length=15),
        ),
    ]
