# Generated by Django 4.0.2 on 2024-09-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Legajos", "0003_remove_dimensioneconomia_recibe_plan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dimensioneconomia",
            name="recibe_plan",
            field=models.CharField(
                blank=True,
                choices=[(None, ""), ("SI", "SI"), ("NO", "NO")],
                max_length=100,
                null=True,
                verbose_name="¿Recibe planes sociales?",
            ),
        ),
        migrations.AddField(
            model_name="dimensioneducacion",
            name="asiste_escuela",
            field=models.CharField(
                blank=True,
                choices=[
                    ("a", "Sí, asisto actualmente"),
                    ("b", "Sí, asistí en algún momento"),
                    ("c", "No, nunca asistí"),
                ],
                max_length=100,
                null=True,
                verbose_name="¿Asistís o asististe alguna vez a algún establecimiento educativo?",
            ),
        ),
        migrations.AddField(
            model_name="dimensioneducacion",
            name="interesCurso",
            field=models.CharField(
                blank=True,
                choices=[(None, ""), ("SI", "SI"), ("NO", "NO")],
                max_length=100,
                null=True,
                verbose_name="¿le interesa algun curso?",
            ),
        ),
        migrations.AddField(
            model_name="dimensioneducacion",
            name="interesEstudio",
            field=models.CharField(
                blank=True,
                choices=[(None, ""), ("SI", "SI"), ("NO", "NO")],
                max_length=100,
                null=True,
                verbose_name="¿Le interesa estudiar?",
            ),
        ),
        migrations.AddField(
            model_name="dimensiontrabajo",
            name="conviviente_trabaja",
            field=models.CharField(
                blank=True,
                choices=[(None, ""), ("SI", "SI"), ("NO", "NO")],
                max_length=100,
                null=True,
                verbose_name="¿Conviviente trabaja?",
            ),
        ),
        migrations.AddField(
            model_name="dimensiontrabajo",
            name="tiene_trabajo",
            field=models.CharField(
                blank=True,
                choices=[(None, ""), ("SI", "SI"), ("NO", "NO")],
                max_length=100,
                null=True,
                verbose_name="¿Actualmente realizás alguna actividad laboral, productiva o comunitaria?",
            ),
        ),
        migrations.AddField(
            model_name="dimensionvivienda",
            name="PoseenCeludar",
            field=models.CharField(
                blank=True,
                choices=[(None, ""), ("SI", "SI"), ("NO", "NO")],
                max_length=255,
                null=True,
                verbose_name="¿En tu hogar cuentan con Teléfonos celulares?",
            ),
        ),
        migrations.AddField(
            model_name="dimensionvivienda",
            name="PoseenPC",
            field=models.CharField(
                blank=True,
                choices=[(None, ""), ("SI", "SI"), ("NO", "NO")],
                max_length=255,
                null=True,
                verbose_name="¿En tu hogar cuentan con Computadoras? (de escritorio / laptop / tablet) ",
            ),
        ),
        migrations.AddField(
            model_name="dimensionvivienda",
            name="Poseeninternet",
            field=models.CharField(
                blank=True,
                choices=[(None, ""), ("SI", "SI"), ("NO", "NO")],
                max_length=255,
                null=True,
                verbose_name="En tu hogar cuentan con Internet (a través del celular o por conexión en la vivienda - wifi)",
            ),
        ),
        migrations.AddField(
            model_name="dimensionvivienda",
            name="hay_agua_caliente",
            field=models.CharField(
                blank=True,
                choices=[(None, ""), ("SI", "SI"), ("NO", "NO")],
                max_length=50,
                null=True,
                verbose_name="¿Posee Agua caliente?",
            ),
        ),
        migrations.AddField(
            model_name="dimensionvivienda",
            name="hay_banio",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Inodoro con botón o cadena", "Inodoro con botón o cadena"),
                    ("Inodoro sin botón o cadena", "Inodoro sin botón o cadena"),
                    ("No tiene inodoro", "No tiene inodoro"),
                    ("No tiene baño", "No tiene baño"),
                ],
                max_length=50,
                null=True,
                verbose_name="El baño tiene…",
            ),
        ),
        migrations.AddField(
            model_name="dimensionvivienda",
            name="hay_desmoronamiento",
            field=models.CharField(
                blank=True,
                choices=[(None, ""), ("SI", "SI"), ("NO", "NO")],
                max_length=50,
                null=True,
                verbose_name="Existe riesgo de desmoronamiento?",
            ),
        ),
    ]
