# Generated by Django 4.0.2 on 2024-07-10 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuraciones', '0003_alter_alertas_gravedad_and_more'),
        ('Legajos', '0005_legajogrupofamiliar_legajos_leg_fk_lega_eed99d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legajos',
            name='apellido',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='documento',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(3000000), django.core.validators.MaxValueValidator(100000000)]),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='m2m_alertas',
            field=models.ManyToManyField(blank=True, through='Legajos.LegajoAlertas', to='Configuraciones.Alertas'),
        ),
        migrations.AlterField(
            model_name='legajosderivaciones',
            name='estado',
            field=models.CharField(choices=[(None, ''), ('Pendiente', 'Pendiente'), ('En análisis', 'En análisis'), ('Aceptada', 'Aceptada'), ('Asesoramiento', 'Asesoramiento'), ('finalizada', 'finalizada')], default='Pendiente', max_length=15),
        ),
        migrations.AddIndex(
            model_name='historiallegajoalertas',
            index=models.Index(fields=['fk_legajo'], name='Legajos_his_fk_lega_3b08b1_idx'),
        ),
        migrations.AddIndex(
            model_name='legajoalertas',
            index=models.Index(fields=['fk_alerta'], name='Legajos_leg_fk_aler_ce9e92_idx'),
        ),
        migrations.AddIndex(
            model_name='legajoalertas',
            index=models.Index(fields=['fk_legajo'], name='Legajos_leg_fk_lega_154496_idx'),
        ),
        migrations.AddIndex(
            model_name='legajogrupohogar',
            index=models.Index(fields=['fk_legajo_1Hogar'], name='Legajos_leg_fk_lega_0a0b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='legajogrupohogar',
            index=models.Index(fields=['fk_legajo_2Hogar'], name='Legajos_leg_fk_lega_04152f_idx'),
        ),
        migrations.AddIndex(
            model_name='legajos',
            index=models.Index(fields=['apellido'], name='Legajos_leg_apellid_21347c_idx'),
        ),
        migrations.AddIndex(
            model_name='legajos',
            index=models.Index(fields=['fecha_nacimiento'], name='Legajos_leg_fecha_n_0aa611_idx'),
        ),
        migrations.AddIndex(
            model_name='legajos',
            index=models.Index(fields=['documento'], name='Legajos_leg_documen_272e88_idx'),
        ),
        migrations.AddIndex(
            model_name='legajos',
            index=models.Index(fields=['observaciones'], name='Legajos_leg_observa_9b4f17_idx'),
        ),
        migrations.AddIndex(
            model_name='legajosarchivos',
            index=models.Index(fields=['fk_legajo'], name='Legajos_leg_fk_lega_0604c5_idx'),
        ),
        migrations.AddIndex(
            model_name='legajosderivaciones',
            index=models.Index(fields=['fk_legajo'], name='Legajos_leg_fk_lega_1a13b1_idx'),
        ),
        migrations.AddIndex(
            model_name='legajosderivaciones',
            index=models.Index(fields=['estado'], name='Legajos_leg_estado_69875c_idx'),
        ),
    ]
