# Generated by Django 4.0.2 on 2024-10-28 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0003_barrio_circuito_criterioalerta_dimension_impacto_and_more'),
        ('legajos', '0008_rename_legjosdepartamento_legajodepartamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Acción',
                'verbose_name_plural': 'Acciones',
            },
        ),
        migrations.CreateModel(
            name='ActividadRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Actividad Realizada',
                'verbose_name_plural': 'Actividades Realizadas',
            },
        ),
        migrations.CreateModel(
            name='Agua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Agua',
                'verbose_name_plural': 'Aguas',
            },
        ),
        migrations.CreateModel(
            name='AportesJubilacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aporte', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Aporte Jubilación',
                'verbose_name_plural': 'Aportes Jubilación',
            },
        ),
        migrations.CreateModel(
            name='AreaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Area Curso',
                'verbose_name_plural': 'Areas Cursos',
            },
        ),
        migrations.CreateModel(
            name='AsisteEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiste', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Asiste Escuela',
                'verbose_name_plural': 'Asiste Escuelas',
            },
        ),
        migrations.CreateModel(
            name='CantidadAmbientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Cantidad de Ambientes',
                'verbose_name_plural': 'Cantidades de Ambientes',
            },
        ),
        migrations.CreateModel(
            name='CentrosSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Centro de Salud',
                'verbose_name_plural': 'Centros de Salud',
            },
        ),
        migrations.CreateModel(
            name='CondicionDe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Condición de',
                'verbose_name_plural': 'Condiciones de',
            },
        ),
        migrations.CreateModel(
            name='ContextoCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexto', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Contexto de Casa',
                'verbose_name_plural': 'Contextos de Casa',
            },
        ),
        migrations.CreateModel(
            name='Desague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Desagüe',
                'verbose_name_plural': 'Desagües',
            },
        ),
        migrations.CreateModel(
            name='DuracionTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Duración del Trabajo',
                'verbose_name_plural': 'Duraciones del Trabajo',
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estados Civiles',
            },
        ),
        migrations.CreateModel(
            name='EstadoDerivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Estado de Derivación',
                'verbose_name_plural': 'Estados de Derivación',
            },
        ),
        migrations.CreateModel(
            name='EstadoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Estado Educativo',
                'verbose_name_plural': 'Estados Educativos',
            },
        ),
        migrations.CreateModel(
            name='EstadoIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Estado de Intervención',
                'verbose_name_plural': 'Estados de Intervención',
            },
        ),
        migrations.CreateModel(
            name='EstadoLlamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Estado de Llamado',
                'verbose_name_plural': 'Estados de Llamado',
            },
        ),
        migrations.CreateModel(
            name='EstadoNivelEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Estado Nivel Educativo',
                'verbose_name_plural': 'Estados Niveles Educativos',
            },
        ),
        migrations.CreateModel(
            name='EstadoRelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Estado de Relación',
                'verbose_name_plural': 'Estados de Relación',
            },
        ),
        migrations.CreateModel(
            name='Frecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Frecuencia',
                'verbose_name_plural': 'Frecuencias',
            },
        ),
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Gas',
                'verbose_name_plural': 'Gases',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='GeneroPronombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronombre', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Género Pronombre',
                'verbose_name_plural': 'Géneros Pronombres',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
            },
        ),
        migrations.CreateModel(
            name='Importancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importancia', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Importancia',
                'verbose_name_plural': 'Importancias',
            },
        ),
        migrations.CreateModel(
            name='Inodoro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Inodoro',
                'verbose_name_plural': 'Inodoros',
            },
        ),
        migrations.CreateModel(
            name='InstitucionesEducativas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Institucion Educativa',
                'verbose_name_plural': 'Instituciones Educativas',
            },
        ),
        migrations.CreateModel(
            name='ModoContratacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Modo de Contratación',
                'verbose_name_plural': 'Modos de Contratación',
            },
        ),
        migrations.CreateModel(
            name='MotivoNivelIncompleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Motivo Nivel Incompleto',
                'verbose_name_plural': 'Motivos Niveles Incompletos',
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Nacionalidad',
                'verbose_name_plural': 'Nacionalidades',
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
            },
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Nivel Educativo',
                'verbose_name_plural': 'Niveles Educativos',
            },
        ),
        migrations.CreateModel(
            name='NoBusquedaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Motivo de No Búsqueda Laboral',
                'verbose_name_plural': 'Motivos de No Búsqueda Laboral',
            },
        ),
        migrations.CreateModel(
            name='Rechazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Motivo de Rechazo',
                'verbose_name_plural': 'Motivos de Rechazo',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
            },
        ),
        migrations.CreateModel(
            name='TiempoBusquedaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tiempo de Búsqueda Laboral',
                'verbose_name_plural': 'Tiempos de Búsqueda Laboral',
            },
        ),
        migrations.CreateModel(
            name='TipoAyudaHogar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de Ayuda al Hogar',
                'verbose_name_plural': 'Tipos de Ayuda al Hogar',
            },
        ),
        migrations.CreateModel(
            name='TipoConstruccionVivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de Construcción de Vivienda',
                'verbose_name_plural': 'Tipos de Construcción de Vivienda',
            },
        ),
        migrations.CreateModel(
            name='TipoDiscapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de Discapacidad',
                'verbose_name_plural': 'Tipos de Discapacidad',
            },
        ),
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
            },
        ),
        migrations.CreateModel(
            name='TipoEnfermedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de Enfermedad',
                'verbose_name_plural': 'Tipos de Enfermedad',
            },
        ),
        migrations.CreateModel(
            name='TipoEstadoVivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de Estado de Vivienda',
                'verbose_name_plural': 'Tipos de Estado de Vivienda',
            },
        ),
        migrations.CreateModel(
            name='TipoGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo Gestion',
                'verbose_name_plural': 'Tipos Gestion',
            },
        ),
        migrations.CreateModel(
            name='TipoPisosVivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de Pisos de Vivienda',
                'verbose_name_plural': 'Tipos de Pisos de Vivienda',
            },
        ),
        migrations.CreateModel(
            name='TipoPosesionVivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de Posesión de Vivienda',
                'verbose_name_plural': 'Tipos de Posesión de Vivienda',
            },
        ),
        migrations.CreateModel(
            name='TipoTechoVivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de Techo de Vivienda',
                'verbose_name_plural': 'Tipos de Techo de Vivienda',
            },
        ),
        migrations.CreateModel(
            name='TipoVivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo de Vivienda',
                'verbose_name_plural': 'Tipos de Vivienda',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
            },
        ),
        migrations.CreateModel(
            name='VinculoFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Vínculo Familiar',
                'verbose_name_plural': 'Vínculos Familiares',
            },
        ),
        migrations.RemoveIndex(
            model_name='legajosderivaciones',
            name='legajos_leg_estado_074813_idx',
        ),
        migrations.RemoveField(
            model_name='dimensionvivienda',
            name='PoseenCeludar',
        ),
        migrations.AddField(
            model_name='dimensionvivienda',
            name='PoseenCelular',
            field=models.BooleanField(default=False, verbose_name='¿En tu hogar cuentan con Teléfonos celulares?'),
        ),
        migrations.AlterField(
            model_name='dimensioneconomia',
            name='recibe_plan',
            field=models.BooleanField(default=False, verbose_name='¿Recibe planes sociales?'),
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='interesCapLab',
            field=models.BooleanField(default=False, verbose_name='¿Tenés interés en realizar cursos de capacitación laboral?'),
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='interesCurso',
            field=models.BooleanField(default=False, verbose_name='¿le interesa algun curso?'),
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='interesEstudio',
            field=models.BooleanField(default=False, verbose_name='¿Le interesa estudiar?'),
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='oficio',
            field=models.BooleanField(default=False, verbose_name='¿Tenés conocimiento de algún oficio?'),
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='realizandoCurso',
            field=models.BooleanField(default=False, verbose_name='¿Actualmente te encontrás haciendo algún curso de capacitación?'),
        ),
        migrations.AlterField(
            model_name='dimensiontrabajo',
            name='busquedaLaboral',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Buscaste trabajo en los últimos 30 días?'),
        ),
        migrations.AlterField(
            model_name='dimensiontrabajo',
            name='conviviente_trabaja',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Conviviente trabaja?'),
        ),
        migrations.AlterField(
            model_name='dimensiontrabajo',
            name='tiene_trabajo',
            field=models.BooleanField(blank=True, null=True, verbose_name='¿Actualmente realizás alguna actividad laboral, productiva o comunitaria?'),
        ),
        migrations.AlterField(
            model_name='dimensionvivienda',
            name='PoseenPC',
            field=models.BooleanField(default=False, verbose_name='¿En tu hogar cuentan con Computadoras? (de escritorio / laptop / tablet) '),
        ),
        migrations.AlterField(
            model_name='dimensionvivienda',
            name='Poseeninternet',
            field=models.BooleanField(default=False, verbose_name='En tu hogar cuentan con Internet (a través del celular o por conexión en la vivienda - wifi)'),
        ),
        migrations.AlterField(
            model_name='dimensionvivienda',
            name='hay_agua_caliente',
            field=models.BooleanField(default=False, verbose_name='¿Posee Agua caliente?'),
        ),
        migrations.AlterField(
            model_name='dimensionvivienda',
            name='hay_desmoronamiento',
            field=models.BooleanField(default=False, verbose_name='Existe riesgo de desmoronamiento?'),
        ),
        migrations.AlterField(
            model_name='legajogrupofamiliar',
            name='conviven',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legajogrupofamiliar',
            name='cuidador_principal',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='circuito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuraciones.circuito'),
        ),
        migrations.AddIndex(
            model_name='legajosderivaciones',
            index=models.Index(fields=['estado'], name='legajos_leg_estado__eaaf78_idx'),
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='areaCurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_curso_dimension', to='legajos.areacurso', verbose_name='¿En qué áreas?'),
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='areaOficio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='area_oficio_dimension', to='legajos.areacurso', verbose_name='¿En qué áreas?'),
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='asiste_escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.asisteescuela', verbose_name='¿Asistís o asististe alguna vez a algún establecimiento educativo?'),
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciclo_dimension', to='legajos.niveleducativo'),
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='estado_nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.estadoniveleducativo', verbose_name='Estado del nivel'),
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='gestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.tipogestion', verbose_name='Tipo de gestión'),
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.grado'),
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.institucioneseducativas', verbose_name='Escuela'),
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='max_nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='max_nivel_dimension', to='legajos.niveleducativo', verbose_name='Máximo nivel educativo alcanzado'),
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='nivelIncompleto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nivel_incompleto_dimension', to='legajos.motivonivelincompleto', verbose_name='¿Cuál fue el motivo principal por el que no terminaste tus estudios?'),
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='sinEduFormal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sin_edu_formal_dimension', to='legajos.motivonivelincompleto', verbose_name='¿Cuál fue el motivo principal por el que nunca asististe a un establecimiento educativo?'),
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.turno', verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='dimensionsalud',
            name='frec_controles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.frecuencia', verbose_name='¿Con qué frecuencia realiza controles médicos?'),
        ),
        migrations.AlterField(
            model_name='dimensionsalud',
            name='lugares_atencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.centrossalud', verbose_name='Centro de Salud en donde se atiende'),
        ),
        migrations.AlterField(
            model_name='dimensiontrabajo',
            name='TiempoBusquedaLaboral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.tiempobusquedalaboral', verbose_name='¿Cuánto hace que buscás trabajo?'),
        ),
        migrations.AlterField(
            model_name='dimensiontrabajo',
            name='actividadRealizadaComo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.actividadrealizada', verbose_name='Esa actividad la realizás como…'),
        ),
        migrations.AlterField(
            model_name='dimensiontrabajo',
            name='aportesJubilacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.aportesjubilacion', verbose_name='Por ese trabajo, ¿te descuentan jubilación o aportas vos mismo?'),
        ),
        migrations.AlterField(
            model_name='dimensiontrabajo',
            name='duracionTrabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.duraciontrabajo', verbose_name='¿Este trabajo es…'),
        ),
        migrations.AlterField(
            model_name='dimensiontrabajo',
            name='modo_contratacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.modocontratacion'),
        ),
        migrations.AlterField(
            model_name='dimensiontrabajo',
            name='noBusquedaLaboral',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.nobusquedalaboral', verbose_name='¿Por qué motivo no buscaste trabajo? (Indicá el motivo principal)'),
        ),
        migrations.AlterField(
            model_name='dimensionvivienda',
            name='ContextoCasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.contextocasa'),
        ),
        migrations.AlterField(
            model_name='dimensionvivienda',
            name='agua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.agua'),
        ),
        migrations.AlterField(
            model_name='dimensionvivienda',
            name='cant_ambientes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.cantidadambientes'),
        ),
        migrations.AlterField(
            model_name='dimensionvivienda',
            name='desague',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.desague'),
        ),
        migrations.AlterField(
            model_name='dimensionvivienda',
            name='gas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.gas'),
        ),
        migrations.AlterField(
            model_name='dimensionvivienda',
            name='hay_banio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.inodoro'),
        ),
        migrations.AlterField(
            model_name='dimensionvivienda',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.tipoconstruccionvivienda'),
        ),
        migrations.AlterField(
            model_name='dimensionvivienda',
            name='pisos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.tipopisosvivienda'),
        ),
        migrations.AlterField(
            model_name='dimensionvivienda',
            name='posesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.tipoposesionvivienda'),
        ),
        migrations.AlterField(
            model_name='dimensionvivienda',
            name='techos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.tipotechovivienda'),
        ),
        migrations.AlterField(
            model_name='dimensionvivienda',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.tipovivienda'),
        ),
        migrations.AlterField(
            model_name='legajogrupofamiliar',
            name='estado_relacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.estadorelacion'),
        ),
        migrations.AlterField(
            model_name='legajogrupofamiliar',
            name='vinculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.vinculofamiliar'),
        ),
        migrations.AlterField(
            model_name='legajogrupohogar',
            name='estado_relacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.estadorelacion'),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='estado_civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.estadocivil'),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.nacionalidad'),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='sexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.sexo'),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='tipo_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.tipodoc', verbose_name='Tipo documento'),
        ),
        migrations.AlterField(
            model_name='legajosderivaciones',
            name='estado',
            field=models.ForeignKey(blank=True, default='Pendiente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.estadoderivacion'),
        ),
        migrations.AlterField(
            model_name='legajosderivaciones',
            name='importancia',
            field=models.ForeignKey(blank=True, default='Alta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.importancia'),
        ),
        migrations.AlterField(
            model_name='legajosderivaciones',
            name='motivo_rechazo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legajos.rechazo'),
        ),
    ]
