# Generated by Django 4.0.2 on 2024-07-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Legajos', '0008_dimensionvivienda_legajos_dim_fk_lega_bdcd3a_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dimensionsalud',
            index=models.Index(fields=['fk_legajo'], name='Legajos_dim_fk_lega_e2f7da_idx'),
        ),
    ]
