# Generated by Django 4.0.2 on 2024-10-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0008_rename_legjosdepartamento_legajodepartamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='legajos',
            name='_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='legajos',
            name='cuil',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legajos',
            name='cuit',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
