# Generated by Django 4.0.2 on 2024-07-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Legajos', '0009_dimensionsalud_legajos_dim_fk_lega_e2f7da_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dimensiontrabajo',
            index=models.Index(fields=['fk_legajo'], name='Legajos_dim_fk_lega_bd11d0_idx'),
        ),
    ]
