# Generated by Django 4.0.2 on 2024-11-13 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0004_provincia_alter_localidad_options_and_more'),
        ('comedores', '0003_alter_comedor_localidad_alter_comedor_municipio_and_more'),
        ('provincias', '0002_proyecto_provincia_alter_observacion_proyecto_and_more'),
        ('legajos', '0009_accion_actividadrealizada_agua_aportesjubilacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legajodepartamento',
            name='fk_provincia',
        ),
        migrations.RemoveField(
            model_name='legajolocalidad',
            name='fk_departamento',
        ),
        migrations.RemoveField(
            model_name='legajolocalidad',
            name='fk_municipio',
        ),
        migrations.RemoveField(
            model_name='legajomunicipio',
            name='fk_provincia',
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='localidadInstitucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuraciones.localidad', verbose_name='Localidad de la institucion'),
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='municipioInstitucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuraciones.municipio', verbose_name='Municipio de la institucion'),
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='provinciaInstitucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuraciones.provincia', verbose_name='Provincia de la institucion'),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='fk_asentamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuraciones.asentamiento'),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='fk_departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuraciones.departamento'),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='fk_localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuraciones.localidad'),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='fk_municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuraciones.municipio'),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='fk_provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuraciones.provincia'),
        ),
        migrations.DeleteModel(
            name='LegajoAsentamientos',
        ),
        migrations.DeleteModel(
            name='LegajoDepartamento',
        ),
        migrations.DeleteModel(
            name='LegajoLocalidad',
        ),
        migrations.DeleteModel(
            name='LegajoMunicipio',
        ),
        migrations.DeleteModel(
            name='LegajoProvincias',
        ),
    ]
