# Generated by Django 4.2.16 on 2024-11-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("legajos", "0010_remove_legajodepartamento_fk_provincia_and_more"),
        ("legajos", "0010_vinculofamiliar_inverso"),
    ]

    operations = []
