# Generated by Django 4.0.2 on 2024-08-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Legajos', '0012_legajolocalidad_legajomunicipio_legajoprovincias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legajolocalidad',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='legajomunicipio',
            name='codigo_ifam',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='legajomunicipio',
            name='iso_provincia',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='legajomunicipio',
            name='nombre_region',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='legajoprovincias',
            name='abreviatura',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='legajoprovincias',
            name='iso_provincia',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='legajoprovincias',
            name='nombre',
            field=models.CharField(max_length=250),
        ),
    ]
