# Generated by Django 4.0.2 on 2024-08-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Legajos', '0013_dimensioneconomia_ingresos_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dimensioneconomia',
            name='Legajos_dim_fk_lega_049308_idx',
        ),
        migrations.AlterField(
            model_name='dimensioneconomia',
            name='ingresos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dimensionvivienda',
            name='cant_convivientes',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='¿Cuántas personas viven en la vivienda?'),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='nacionalidad',
            field=models.CharField(blank=True, choices=[(None, ''), ('Argentina', 'Argentina'), ('Boliviana', 'Boliviana'), ('Brasilera', 'Brasilera'), ('Chilena', 'Chilena'), ('Colombiana', 'Colombiana'), ('Paraguaya', 'Paraguaya'), ('Peruana', 'Peruana'), ('Uruguaya', 'Uruguaya'), ('Venezolana', 'Venezolana'), ('Otra', 'Otra')], max_length=50, null=True),
        ),
    ]
