# Generated by Django 4.0.2 on 2024-08-19 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Legajos', '0014_alter_legajolocalidad_cod_bahra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legajos',
            name='fk_localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_localidad', to='Legajos.legajolocalidad'),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='fk_municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_municipio', to='Legajos.legajomunicipio'),
        ),
        migrations.AlterField(
            model_name='legajos',
            name='fk_provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_provincia', to='Legajos.legajoprovincias'),
        ),
    ]
