# Generated by Django 4.0.2 on 2024-08-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Legajos', '0014_remove_dimensioneconomia_legajos_dim_fk_lega_049308_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimensioneconomia',
            name='ingresos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ingresos Mensuales '),
        ),
        migrations.AlterField(
            model_name='dimensioneconomia',
            name='recibe_plan',
            field=models.CharField(blank=True, choices=[(None, ''), ('SI', 'SI'), ('NO', 'NO')], max_length=100, null=True, verbose_name='¿Recibe planes sociales?'),
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='interesCapLab',
            field=models.CharField(blank=True, choices=[(None, ''), ('SI', 'SI'), ('NO', 'NO')], max_length=20, null=True, verbose_name='¿Tenés interés en realizar cursos de capacitación laboral?'),
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='interesCurso',
            field=models.CharField(blank=True, choices=[(None, ''), ('SI', 'SI'), ('NO', 'NO')], max_length=100, null=True, verbose_name='¿le interesa algun curso?'),
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='interesEstudio',
            field=models.CharField(blank=True, choices=[(None, ''), ('SI', 'SI'), ('NO', 'NO')], max_length=100, null=True, verbose_name='¿Le interesa estudiar?'),
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='oficio',
            field=models.CharField(blank=True, choices=[(None, ''), ('SI', 'SI'), ('NO', 'NO')], max_length=20, null=True, verbose_name='¿Tenés conocimiento de algún oficio?'),
        ),
        migrations.AlterField(
            model_name='dimensioneducacion',
            name='realizandoCurso',
            field=models.CharField(blank=True, choices=[(None, ''), ('SI', 'SI'), ('NO', 'NO')], max_length=20, null=True, verbose_name='¿Actualmente te encontrás haciendo algún curso de capacitación?'),
        ),
        migrations.AlterField(
            model_name='dimensiontrabajo',
            name='busquedaLaboral',
            field=models.CharField(blank=True, choices=[(None, ''), ('SI', 'SI'), ('NO', 'NO')], max_length=20, null=True, verbose_name='¿Buscaste trabajo en los últimos 30 días?'),
        ),
        migrations.AlterField(
            model_name='dimensiontrabajo',
            name='conviviente_trabaja',
            field=models.CharField(blank=True, choices=[(None, ''), ('SI', 'SI'), ('NO', 'NO')], max_length=100, null=True, verbose_name='¿Conviviente trabaja?'),
        ),
        migrations.AlterField(
            model_name='dimensiontrabajo',
            name='tiene_trabajo',
            field=models.CharField(blank=True, choices=[(None, ''), ('SI', 'SI'), ('NO', 'NO')], max_length=100, null=True, verbose_name='¿Actualmente realizás alguna actividad laboral, productiva o comunitaria?'),
        ),
        migrations.AlterField(
            model_name='dimensionvivienda',
            name='PoseenCeludar',
            field=models.CharField(blank=True, choices=[(None, ''), ('SI', 'SI'), ('NO', 'NO')], max_length=255, null=True, verbose_name='¿En tu hogar cuentan con Teléfonos celulares?'),
        ),
        migrations.AlterField(
            model_name='dimensionvivienda',
            name='PoseenPC',
            field=models.CharField(blank=True, choices=[(None, ''), ('SI', 'SI'), ('NO', 'NO')], max_length=255, null=True, verbose_name='¿En tu hogar cuentan con Computadoras? (de escritorio / laptop / tablet) '),
        ),
        migrations.AlterField(
            model_name='dimensionvivienda',
            name='Poseeninternet',
            field=models.CharField(blank=True, choices=[(None, ''), ('SI', 'SI'), ('NO', 'NO')], max_length=255, null=True, verbose_name='En tu hogar cuentan con Internet (a través del celular o por conexión en la vivienda - wifi)'),
        ),
        migrations.AlterField(
            model_name='dimensionvivienda',
            name='hay_agua_caliente',
            field=models.CharField(blank=True, choices=[(None, ''), ('SI', 'SI'), ('NO', 'NO')], max_length=50, null=True, verbose_name='¿Posee Agua caliente?'),
        ),
        migrations.AlterField(
            model_name='dimensionvivienda',
            name='hay_desmoronamiento',
            field=models.CharField(blank=True, choices=[(None, ''), ('SI', 'SI'), ('NO', 'NO')], max_length=50, null=True, verbose_name='Existe riesgo de desmoronamiento?'),
        ),
        migrations.AlterField(
            model_name='legajogrupofamiliar',
            name='conviven',
            field=models.CharField(choices=[(None, ''), ('SI', 'SI'), ('NO', 'NO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='legajogrupofamiliar',
            name='cuidador_principal',
            field=models.CharField(choices=[(None, ''), ('SI', 'SI'), ('NO', 'NO')], max_length=50),
        ),
    ]
